openapi: 3.1.0
info:
  title: accessanalyzer
  description: >-
    <p>Identity and Access Management Access Analyzer helps you to set, verify,
    and refine your IAM policies by providing a suite of capabilities. Its
    features include findings for external and unused access, basic and custom
    policy checks for validating policies, and policy generation to generate
    fine-grained policies. To start using IAM Access Analyzer to identify
    external or unused access, you first need to create an analyzer.</p> <p>
    <b>External access analyzers</b> help identify potential risks of accessing
    resources by enabling you to identify any resource policies that grant
    access to an external principal. It does this by using logic-based reasoning
    to analyze resource-based policies in your Amazon Web Services environment.
    An external principal can be another Amazon Web Services account, a root
    user, an IAM user or role, a federated user, an Amazon Web Services service,
    or an anonymous user. You can also use IAM Access Analyzer to preview public
    and cross-account access to your resources before deploying permissions
    changes.</p> <p> <b>Unused access analyzers</b> help identify potential
    identity access risks by enabling you to identify unused IAM roles, unused
    access keys, unused console passwords, and IAM principals with unused
    service and action-level permissions.</p> <p>Beyond findings, IAM Access
    Analyzer provides basic and custom policy checks to validate IAM policies
    before deploying permissions changes. You can use policy generation to
    refine permissions by attaching a policy generated using access activity
    logged in CloudTrail logs. </p> <p>This guide describes the IAM Access
    Analyzer operations that you can call programmatically. For general
    information about IAM Access Analyzer, see <a
    href="https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html">Identity
    and Access Management Access Analyzer</a> in the <b>IAM User Guide</b>.</p>
paths:
  /archive-rule:
    PUT:
      summary: Applyarchiverule
      description: >-
        Retroactively applies the archive rule to existing findings that meet
        the archive rule criteria.
      operationId: amazonWebServicesApplyArchiveRule
  /policy/generation/{jobId}:
    GET:
      summary: Getgeneratedpolicy
      description: 'Retrieves the policy that was generated using StartPolicyGeneration. '
      operationId: amazonWebServicesGetGeneratedPolicy
  /policy/check-access-not-granted:
    POST:
      summary: Checkaccessnotgranted
      description: Checks whether the specified access isn't allowed by a policy.
      operationId: amazonWebServicesCheckAccessNotGranted
  /policy/check-no-new-access:
    POST:
      summary: Checknonewaccess
      description: >-
        Checks whether new access is allowed for an updated policy when compared
        to the existing policy. You can find examples for reference policies and
        learn how to set up and run a custom policy check for new access in the
        IAM Access Analyzer custom policy checks samples repository on GitHub.
        The reference policies in this repository are meant to be passed to the
        existingPolicyDocument request parameter.
      operationId: amazonWebServicesCheckNoNewAccess
  /access-preview:
    GET:
      summary: Listaccesspreviews
      description: Retrieves a list of access previews for the specified analyzer.
      operationId: amazonWebServicesListAccessPreviews
  /analyzer:
    GET:
      summary: Listanalyzers
      description: Retrieves a list of analyzers.
      operationId: amazonWebServicesListAnalyzers
  /analyzer/{analyzerName}/archive-rule:
    GET:
      summary: Listarchiverules
      description: Retrieves a list of archive rules created for the specified analyzer.
      operationId: amazonWebServicesListArchiveRules
  /analyzer/{analyzerName}:
    GET:
      summary: Getanalyzer
      description: Retrieves information about the specified analyzer.
      operationId: amazonWebServicesGetAnalyzer
  /analyzer/{analyzerName}/archive-rule/{ruleName}:
    PUT:
      summary: Updatearchiverule
      description: Updates the criteria and values for the specified archive rule.
      operationId: amazonWebServicesUpdateArchiveRule
  /access-preview/{accessPreviewId}:
    POST:
      summary: Listaccesspreviewfindings
      description: >-
        Retrieves a list of access preview findings generated by the specified
        access preview.
      operationId: amazonWebServicesListAccessPreviewFindings
  /analyzed-resource:
    POST:
      summary: Listanalyzedresources
      description: >-
        Retrieves a list of resources of the specified type that have been
        analyzed by the specified analyzer..
      operationId: amazonWebServicesListAnalyzedResources
  /finding/{id}:
    GET:
      summary: Getfinding
      description: Retrieves information about the specified finding.
      operationId: amazonWebServicesGetFinding
  /findingv2/{id}:
    GET:
      summary: Getfindingv2
      description: Retrieves information about the specified finding.
      operationId: amazonWebServicesGetFindingV2
  /finding:
    PUT:
      summary: Updatefindings
      description: Updates the status for the specified findings.
      operationId: amazonWebServicesUpdateFindings
  /findingv2:
    POST:
      summary: Listfindingsv2
      description: >-
        Retrieves a list of findings generated by the specified analyzer. To
        learn about filter keys that you can use to retrieve a list of findings,
        see IAM Access Analyzer filter keys in the IAM User Guide.
      operationId: amazonWebServicesListFindingsV2
  /policy/generation:
    PUT:
      summary: Startpolicygeneration
      description: Starts the policy generation request.
      operationId: amazonWebServicesStartPolicyGeneration
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes a tag from the specified resource.
      operationId: amazonWebServicesUntagResource
  /resource/scan:
    POST:
      summary: Startresourcescan
      description: >-
        Immediately starts a scan of the policies applied to the specified
        resource.
      operationId: amazonWebServicesStartResourceScan
  /policy/validation:
    POST:
      summary: Validatepolicy
      description: >-
        Requests the validation of a policy and returns a list of findings. The
        findings help you identify issues and provide actionable recommendations
        to resolve the issue and enable you to author functional policies that
        meet security best practices. 
      operationId: amazonWebServicesValidatePolicy
tags: []
