openapi: 3.1.0
info:
  title: account
  description: <p>Operations for Amazon Web Services Account Management</p>
paths:
  /deleteAlternateContact:
    POST:
      summary: Deletealternatecontact
      description: >-
        Deletes the specified alternate contact from an Amazon Web Services
        account. For complete details about how to use the alternate contact
        operations, see Access or updating the alternate contacts.  Before you
        can update the alternate contact information for an Amazon Web Services
        account that is managed by Organizations, you must first enable
        integration between Amazon Web Services Account Management and
        Organizations. For more information, see Enabling trusted access for
        Amazon Web Services Account Management. 
      operationId: amazonWebServicesDeleteAlternateContact
  /disableRegion:
    POST:
      summary: Disableregion
      description: Disables (opts-out) a particular Region for an account.
      operationId: amazonWebServicesDisableRegion
  /enableRegion:
    POST:
      summary: Enableregion
      description: Enables (opts-in) a particular Region for an account.
      operationId: amazonWebServicesEnableRegion
  /getAlternateContact:
    POST:
      summary: Getalternatecontact
      description: >-
        Retrieves the specified alternate contact attached to an Amazon Web
        Services account. For complete details about how to use the alternate
        contact operations, see Access or updating the alternate contacts. 
        Before you can update the alternate contact information for an Amazon
        Web Services account that is managed by Organizations, you must first
        enable integration between Amazon Web Services Account Management and
        Organizations. For more information, see Enabling trusted access for
        Amazon Web Services Account Management. 
      operationId: amazonWebServicesGetAlternateContact
  /getContactInformation:
    POST:
      summary: Getcontactinformation
      description: >-
        Retrieves the primary contact information of an Amazon Web Services
        account. For complete details about how to use the primary contact
        operations, see Update the primary and alternate contact information.
      operationId: amazonWebServicesGetContactInformation
  /getRegionOptStatus:
    POST:
      summary: Getregionoptstatus
      description: Retrieves the opt-in status of a particular Region.
      operationId: amazonWebServicesGetRegionOptStatus
  /listRegions:
    POST:
      summary: Listregions
      description: >-
        Lists all the Regions for a given account and their respective opt-in
        statuses. Optionally, this list can be filtered by the
        region-opt-status-contains parameter. 
      operationId: amazonWebServicesListRegions
  /putAlternateContact:
    POST:
      summary: Putalternatecontact
      description: >-
        Modifies the specified alternate contact attached to an Amazon Web
        Services account. For complete details about how to use the alternate
        contact operations, see Access or updating the alternate contacts. 
        Before you can update the alternate contact information for an Amazon
        Web Services account that is managed by Organizations, you must first
        enable integration between Amazon Web Services Account Management and
        Organizations. For more information, see Enabling trusted access for
        Amazon Web Services Account Management. 
      operationId: amazonWebServicesPutAlternateContact
  /putContactInformation:
    POST:
      summary: Putcontactinformation
      description: >-
        Updates the primary contact information of an Amazon Web Services
        account. For complete details about how to use the primary contact
        operations, see Update the primary and alternate contact information.
      operationId: amazonWebServicesPutContactInformation
tags: []
