openapi: 3.2.0
info:
  title: Amazon Web Services route53-recovery-control-config…
  description: Recovery Control Configuration API Reference for Amazon Route 53 Application Recovery Controller
tags:
- name: Safetyrule
paths:
  /safetyrule:
    PUT:
      summary: Amazon Web Services Updatesafetyrule
      description: Update a safety rule (an assertion rule or gating rule). You can only update the name and the waiting period for a safety rule. To make other updates, delete the safety rule and create a new one.
      operationId: amazonWebServicesUpdateSafetyRule
      tags:
      - Safetyrule
  /safetyrule/{SafetyRuleArn}:
    GET:
      summary: Amazon Web Services Describesafetyrule
      description: Returns information about a safety rule.
      operationId: amazonWebServicesDescribeSafetyRule
      tags:
      - Safetyrule
