openapi: 3.2.0
info:
  title: Amazon Web Services ivs Create Playback Restriction Policy…
  description: 'Introduction


    The Amazon Interactive Video Service (IVS) API is REST compatible, using a standard HTTP API and an Amazon Web Services EventBridge event stream for responses.'
tags:
- name: CreatePlaybackRestrictionPolicy
paths:
  /CreatePlaybackRestrictionPolicy:
    POST:
      summary: Amazon Web Services Createplaybackrestrictionpolicy
      description: Creates a new playback restriction policy, for constraining playback by countries and/or origins.
      operationId: amazonWebServicesCreatePlaybackRestrictionPolicy
      tags:
      - CreatePlaybackRestrictionPolicy
