openapi: 3.2.0
info:
  title: Amazon Web Services auditmanager Delegations API
  description: Welcome to the Audit Manager API reference.
tags:
- name: Delegations
paths:
  /delegations:
    GET:
      summary: Amazon Web Services Getdelegations
      description: Gets a list of delegations from an audit owner to a delegate.
      operationId: amazonWebServicesGetDelegations
      tags:
      - Delegations
