openapi: 3.2.0
info:
  title: Amazon Web Services controltower Update Enabled Baseline API
  description: These interfaces allow you to apply the Amazon Web Services library of pre-defined controls to your organizational units, programmatically.
tags:
- name: Update Enabled Baseline
paths:
  /update-enabled-baseline:
    POST:
      summary: Amazon Web Services Updateenabledbaseline
      description: Updates an EnabledBaseline resource's applied parameters or version.
      operationId: amazonWebServicesUpdateEnabledBaseline
      tags:
      - Update Enabled Baseline
