openapi: 3.2.0
info:
  title: Amazon Web Services medical-imaging Datastore API
  description: This is the AWS HealthImaging API Reference.
tags:
- name: Datastore
paths:
  /datastore/{datastoreId}/imageSet/{sourceImageSetId}/copyImageSet:
    POST:
      summary: Amazon Web Services Copyimageset
      description: Copy an image set.
      operationId: amazonWebServicesCopyImageSet
      tags:
      - Datastore
  /datastore:
    GET:
      summary: Amazon Web Services Listdatastores
      description: List data stores.
      operationId: amazonWebServicesListDatastores
      tags:
      - Datastore
  /datastore/{datastoreId}:
    GET:
      summary: Amazon Web Services Getdatastore
      description: Get data store properties.
      operationId: amazonWebServicesGetDatastore
      tags:
      - Datastore
  /datastore/{datastoreId}/imageSet/{imageSetId}/deleteImageSet:
    POST:
      summary: Amazon Web Services Deleteimageset
      description: Delete an image set.
      operationId: amazonWebServicesDeleteImageSet
      tags:
      - Datastore
  /datastore/{datastoreId}/imageSet/{imageSetId}/getImageFrame:
    POST:
      summary: Amazon Web Services Getimageframe
      description: Get an image frame (pixel data) for an image set.
      operationId: amazonWebServicesGetImageFrame
      tags:
      - Datastore
  /datastore/{datastoreId}/imageSet/{imageSetId}/getImageSet:
    POST:
      summary: Amazon Web Services Getimageset
      description: Get image set properties.
      operationId: amazonWebServicesGetImageSet
      tags:
      - Datastore
  /datastore/{datastoreId}/imageSet/{imageSetId}/getImageSetMetadata:
    POST:
      summary: Amazon Web Services Getimagesetmetadata
      description: Get metadata attributes for an image set.
      operationId: amazonWebServicesGetImageSetMetadata
      tags:
      - Datastore
  /datastore/{datastoreId}/imageSet/{imageSetId}/listImageSetVersions:
    POST:
      summary: Amazon Web Services Listimagesetversions
      description: List image set versions.
      operationId: amazonWebServicesListImageSetVersions
      tags:
      - Datastore
  /datastore/{datastoreId}/searchImageSets:
    POST:
      summary: Amazon Web Services Searchimagesets
      description: Search image sets based on defined input attributes. SearchImageSets accepts a single search query parameter and returns a paginated response of all image sets that have the matching criteria. All range queries must be input as (lowerBound, upperBound). SearchImageSets uses the updatedAt field for sorting in decreasing order from latest to oldest.
      operationId: amazonWebServicesSearchImageSets
      tags:
      - Datastore
  /datastore/{datastoreId}/imageSet/{imageSetId}/updateImageSetMetadata:
    POST:
      summary: Amazon Web Services Updateimagesetmetadata
      description: Update image set metadata attributes.
      operationId: amazonWebServicesUpdateImageSetMetadata
      tags:
      - Datastore
