openapi: 3.2.0
info:
  title: Amazon Web Services finspace-data Credentials API
  description: The FinSpace APIs let you take actions inside the FinSpace.
tags:
- name: Credentials
paths:
  /credentials/programmatic:
    GET:
      summary: Amazon Web Services Getprogrammaticaccesscredentials
      description: Request programmatic credentials to use with FinSpace SDK. For more information, see Step 2. Access credentials programmatically using IAM access key id and secret access key.
      operationId: amazonWebServicesGetProgrammaticAccessCredentials
      tags:
      - Credentials
