openapi: 3.2.0
info:
  title: Amazon Web Services ram Updateresourceshare API
  description: This is the Resource Access Manager API Reference.
tags:
- name: Updateresourceshare
paths:
  /updateresourceshare:
    POST:
      summary: Amazon Web Services Updateresourceshare
      description: Modifies some of the properties of the specified resource share.
      operationId: amazonWebServicesUpdateResourceShare
      tags:
      - Updateresourceshare
