openapi: 3.2.0
info:
  title: Amazon Web Services launch-wizard List Deployment Events API
  description: Launch Wizard offers a guided way of sizing, configuring, and deploying Amazon Web Services resources for third party applications, such as Microsoft SQL Server Always On and HANA based SAP systems, without the need to manually identify and provision individual Amazon Web Services resources.
tags:
- name: listDeploymentEvents
paths:
  /listDeploymentEvents:
    POST:
      summary: Amazon Web Services Listdeploymentevents
      description: Lists the events of a deployment.
      operationId: amazonWebServicesListDeploymentEvents
      tags:
      - listDeploymentEvents
