openapi: 3.2.0
info:
  title: Amazon Web Services resiliencehub List App Input Sources API
  description: Resilience Hub helps you proactively prepare and protect your Amazon Web Services applications from disruptions. It offers continual resiliency assessment and validation that integrates into your software development lifecycle. This enables you to uncover resiliency weaknesses, ensure recovery time objective (RTO) and recovery point objective (RPO) targets for your applications are met, and resolve issues before they are released into production.
tags:
- name: List App Input Sources
paths:
  /list-app-input-sources:
    POST:
      summary: Amazon Web Services Listappinputsources
      description: Lists all the input sources of the Resilience Hub application. For more information about the input sources supported by Resilience Hub, see Discover the structure and describe your Resilience Hub application.
      operationId: amazonWebServicesListAppInputSources
      tags:
      - List App Input Sources
