openapi: 3.2.0
info:
  title: Amazon Web Services mediatailor Playback Configurations API
  description: Use the AWS Elemental MediaTailor SDKs and CLI to configure scalable ad insertion and linear channels.
tags:
- name: Playback Configurations
paths:
  /playbackConfigurations:
    GET:
      summary: Amazon Web Services Listplaybackconfigurations
      description: Retrieves existing playback configurations. For information about MediaTailor configurations, see Working with Configurations in AWS Elemental MediaTailor.
      operationId: amazonWebServicesListPlaybackConfigurations
      tags:
      - Playback Configurations
