openapi: 3.2.0
info:
  title: Amazon Web Services sso Assignment API
  description: AWS IAM Identity Center (successor to AWS Single Sign-On) Portal is a web service that makes it easy for you to assign user access to IAM Identity Center resources such as the AWS access portal.
tags:
- name: Assignment
paths:
  /assignment/roles:
    GET:
      summary: Amazon Web Services Listaccountroles
      description: Lists all roles that are assigned to the user for a given AWS account.
      operationId: amazonWebServicesListAccountRoles
      tags:
      - Assignment
  /assignment/accounts:
    GET:
      summary: Amazon Web Services Listaccounts
      description: Lists all AWS accounts assigned to the user. These AWS accounts are assigned by the administrator of the account. For more information, see Assign User Access in the IAM Identity Center User Guide. This operation returns a paginated response.
      operationId: amazonWebServicesListAccounts
      tags:
      - Assignment
