openapi: 3.2.0
info:
  title: Amazon Web Services kinesisvideo Get Data Endpoint API
  description: ''
tags:
- name: Get Data Endpoint
paths:
  /getDataEndpoint:
    POST:
      summary: Amazon Web Services Getdataendpoint
      description: Gets an endpoint for a specified stream for either reading or writing. Use this endpoint in your application to read from the specified stream (using the GetMedia or GetMediaForFragmentList operations) or write to it (using the PutMedia operation). The returned endpoint does not have the API name appended. The client needs to add the API name to the returned endpoint. In the request, specify the stream either by StreamName or StreamARN.
      operationId: amazonWebServicesGetDataEndpoint
      tags:
      - Get Data Endpoint
