openapi: 3.2.0
info:
  title: Amazon Web Services lakeformation Get Temporary Glue…
  description: 'Lake Formation

    Defines the public endpoint for the Lake Formation service.'
tags:
- name: GetTemporaryGluePartitionCredentials
paths:
  /GetTemporaryGluePartitionCredentials:
    POST:
      summary: Amazon Web Services Gettemporarygluepartitioncredentials
      description: This API is identical to GetTemporaryTableCredentials except that this is used when the target Data Catalog resource is of type Partition. Lake Formation restricts the permission of the vended credentials with the same scope down policy which restricts access to a single Amazon S3 prefix.
      operationId: amazonWebServicesGetTemporaryGluePartitionCredentials
      tags:
      - GetTemporaryGluePartitionCredentials
