openapi: 3.2.0
info:
  title: Amazon Web Services iot Ota Updates API
  description: 'IoT

    IoT provides secure, bi-directional communication between Internet-connected devices (such as sensors, actuators, embedded devices, or smart appliances) and the Amazon Web Services cloud.'
tags:
- name: OTA Updates
paths:
  /otaUpdates/{otaUpdateId}:
    GET:
      summary: Amazon Web Services Getotaupdate
      description: Gets an OTA update. Requires permission to access the GetOTAUpdate action.
      operationId: amazonWebServicesGetOTAUpdate
      tags:
      - OTA Updates
  /otaUpdates:
    GET:
      summary: Amazon Web Services Listotaupdates
      description: Lists OTA updates. Requires permission to access the ListOTAUpdates action.
      operationId: amazonWebServicesListOTAUpdates
      tags:
      - OTA Updates
