openapi: 3.2.0
info:
  title: Amazon Web Services apigatewayv2 Cors API
  description: Amazon API Gateway V2
tags:
- name: CORS
paths:
  /v2/apis/{apiId}/cors:
    DELETE:
      summary: Amazon Web Services Deletecorsconfiguration
      description: Deletes a CORS configuration.
      operationId: amazonWebServicesDeleteCorsConfiguration
      tags:
      - CORS
