openapi: 3.2.0
info:
  title: Amazon Web Services trustedadvisor Checks API
  description: TrustedAdvisor Public API
tags:
- name: Checks
paths:
  /v1/checks:
    GET:
      summary: Amazon Web Services Listchecks
      description: List a filterable set of Checks
      operationId: amazonWebServicesListChecks
      tags:
      - Checks
