openapi: 3.2.0
info:
  title: Amazon Web Services lakeformation Get Table Objects API
  description: 'Lake Formation

    Defines the public endpoint for the Lake Formation service.'
tags:
- name: GetTableObjects
paths:
  /GetTableObjects:
    POST:
      summary: Amazon Web Services Gettableobjects
      description: Returns the set of Amazon S3 objects that make up the specified governed table. A transaction ID or timestamp can be specified for time-travel queries.
      operationId: amazonWebServicesGetTableObjects
      tags:
      - GetTableObjects
