openapi: 3.2.0
info:
  title: Amazon Web Services batch Updateschedulingpolicy API
  description: 'Batch

    Using Batch, you can run batch computing workloads on the Amazon Web Services Cloud.'
tags:
- name: Updateschedulingpolicy
paths:
  /v1/updateschedulingpolicy:
    POST:
      summary: Amazon Web Services Updateschedulingpolicy
      description: Updates a scheduling policy.
      operationId: amazonWebServicesUpdateSchedulingPolicy
      tags:
      - Updateschedulingpolicy
