openapi: 3.2.0
info:
  title: Amazon Web Services robomaker Restart Simulation Job API
  description: This section provides documentation for the AWS RoboMaker API operations.
tags:
- name: Restart Simulation Job
paths:
  /restartSimulationJob:
    POST:
      summary: Amazon Web Services Restartsimulationjob
      description: Restarts a running simulation job.
      operationId: amazonWebServicesRestartSimulationJob
      tags:
      - Restart Simulation Job
