openapi: 3.2.0
info:
  title: Amazon Web Services kinesisvideo Get Signaling Channel…
  description: ''
tags:
- name: Get Signaling Channel Endpoint
paths:
  /getSignalingChannelEndpoint:
    POST:
      summary: Amazon Web Services Getsignalingchannelendpoint
      description: Provides an endpoint for the specified signaling channel to send and receive messages. This API uses the SingleMasterChannelEndpointConfiguration input parameter, which consists of the Protocols and Role properties. Protocols is used to determine the communication mechanism. For example, if you specify WSS as the protocol, this API produces a secure websocket endpoint. If you specify HTTPS as the protocol, this API generates an HTTPS endpoint. Role determines the messaging permissions. A MASTER role results in this API generating an endpoint that a client can use to communicate with any of the viewers on the channel. A VIEWER role results in this API generating an endpoint that a client can use to communicate only with a MASTER.
      operationId: amazonWebServicesGetSignalingChannelEndpoint
      tags:
      - Get Signaling Channel Endpoint
