openapi: 3.2.0
info:
  title: Amazon Web Services route53-recovery-control-config…
  description: Recovery Control Configuration API Reference for Amazon Route 53 Application Recovery Controller
tags:
- name: Controlpanels
paths:
  /controlpanels:
    GET:
      summary: Amazon Web Services Listcontrolpanels
      description: Returns an array of control panels in an account or in a cluster.
      operationId: amazonWebServicesListControlPanels
      tags:
      - Controlpanels
