openapi: 3.2.0
info:
  title: Amazon Web Services vpc-lattice…
  description: Amazon VPC Lattice is a fully managed application networking service that you use to connect, secure, and monitor all of your services across multiple accounts and virtual private clouds (VPCs). Amazon VPC Lattice interconnects your microservices and legacy services within a logical boundary, so that you can discover and manage them more efficiently. For more information, see the Amazon VPC Lattice User Guide
tags:
- name: Servicenetworkvpcassociations
paths:
  /servicenetworkvpcassociations:
    GET:
      summary: Amazon Web Services Listservicenetworkvpcassociations
      description: Lists the service network and VPC associations. You can filter the list either by VPC or service network. You must provide either the service network identifier or the VPC identifier.
      operationId: amazonWebServicesListServiceNetworkVpcAssociations
      tags:
      - Servicenetworkvpcassociations
  /servicenetworkvpcassociations/{serviceNetworkVpcAssociationIdentifier}:
    PATCH:
      summary: Amazon Web Services Updateservicenetworkvpcassociation
      description: Updates the service network and VPC association. Once you add a security group, it cannot be removed.
      operationId: amazonWebServicesUpdateServiceNetworkVpcAssociation
      tags:
      - Servicenetworkvpcassociations
