openapi: 3.2.0
info:
  title: Amazon Web Services appfabric Useraccess API
  description: Amazon Web Services AppFabric quickly connects software as a service (SaaS) applications across your organization.
tags:
- name: User Access
paths:
  /useraccess/batchget:
    POST:
      summary: Amazon Web Services Batchgetuseraccesstasks
      description: Gets user access details in a batch request. This action polls data from the tasks that are kicked off by the StartUserAccessTasks action.
      operationId: amazonWebServicesBatchGetUserAccessTasks
      tags:
      - User Access
  /useraccess/start:
    POST:
      summary: Amazon Web Services Startuseraccesstasks
      description: Starts the tasks to search user access status for a specific email address. The tasks are stopped when the user access status data is found. The tasks are terminated when the API calls to the application time out.
      operationId: amazonWebServicesStartUserAccessTasks
      tags:
      - User Access
