openapi: 3.2.0
info:
  title: Amazon Web Services iotwireless Positions API
  description: AWS IoT Wireless provides bi-directional communication between internet-connected wireless devices and the AWS Cloud.
tags:
- name: Positions
paths:
  /positions/{ResourceIdentifier}:
    PATCH:
      summary: Amazon Web Services Updateposition
      description: Update the position information of a resource. This action is no longer supported. Calls to update the position information should use the UpdateResourcePosition API operation instead.
      operationId: amazonWebServicesUpdatePosition
      tags:
      - Positions
