openapi: 3.2.0
info:
  title: Amazon Web Services ivs Batch Get Stream Key API
  description: 'Introduction


    The Amazon Interactive Video Service (IVS) API is REST compatible, using a standard HTTP API and an Amazon Web Services EventBridge event stream for responses.'
tags:
- name: BatchGetStreamKey
paths:
  /BatchGetStreamKey:
    POST:
      summary: Amazon Web Services Batchgetstreamkey
      description: Performs GetStreamKey on multiple ARNs simultaneously.
      operationId: amazonWebServicesBatchGetStreamKey
      tags:
      - BatchGetStreamKey
