openapi: 3.2.0
info:
  title: Amazon Web Services controltower Create Landingzone API
  description: These interfaces allow you to apply the Amazon Web Services library of pre-defined controls to your organizational units, programmatically.
tags:
- name: Create Landingzone
paths:
  /create-landingzone:
    POST:
      summary: Amazon Web Services Createlandingzone
      description: Creates a new landing zone. This API call starts an asynchronous operation that creates and configures a landing zone, based on the parameters specified in the manifest JSON file.
      operationId: amazonWebServicesCreateLandingZone
      tags:
      - Create Landingzone
