openapi: 3.2.0
info:
  title: Amazon Web Services ivs Delete Recording Configuration API
  description: 'Introduction


    The Amazon Interactive Video Service (IVS) API is REST compatible, using a standard HTTP API and an Amazon Web Services EventBridge event stream for responses.'
tags:
- name: DeleteRecordingConfiguration
paths:
  /DeleteRecordingConfiguration:
    POST:
      summary: Amazon Web Services Deleterecordingconfiguration
      description: Deletes the recording configuration for the specified ARN. If you try to delete a recording configuration that is associated with a channel, you will get an error (409 ConflictException). To avoid this, for all channels that reference the recording configuration, first use UpdateChannel to set the recordingConfigurationArn field to an empty string, then use DeleteRecordingConfiguration.
      operationId: amazonWebServicesDeleteRecordingConfiguration
      tags:
      - DeleteRecordingConfiguration
