openapi: 3.2.0
info:
  title: Amazon Web Services appflow Create Flow API
  description: Welcome to the Amazon AppFlow API reference.
tags:
- name: Create Flow
paths:
  /create-flow:
    POST:
      summary: Amazon Web Services Createflow
      description: Enables your application to create a new flow using Amazon AppFlow. You must create a connector profile before calling this API. Please note that the Request Syntax below shows syntax for multiple destinations, however, you can only transfer data to one item in this list at a time. Amazon AppFlow does not currently support flows to multiple destinations at once.
      operationId: amazonWebServicesCreateFlow
      tags:
      - Create Flow
