openapi: 3.2.0
info:
  title: Amazon Web Services mgn List Source Server Actions API
  description: The Application Migration Service service.
tags:
- name: ListSourceServerActions
paths:
  /ListSourceServerActions:
    POST:
      summary: Amazon Web Services Listsourceserveractions
      description: List source server post migration custom actions.
      operationId: amazonWebServicesListSourceServerActions
      tags:
      - ListSourceServerActions
