openapi: 3.2.0
info:
  title: Amazon Web Services codeguruprofiler Internal API
  description: This section provides documentation for the Amazon CodeGuru Profiler API operations.
tags:
- name: Internal
paths:
  /internal/findingsReports:
    GET:
      summary: Amazon Web Services Getfindingsreportaccountsummary
      description: Returns a list of FindingsReportSummary objects that contain analysis results for all profiling groups in your AWS account.
      operationId: amazonWebServicesGetFindingsReportAccountSummary
      tags:
      - Internal
  /internal/profilingGroups/{profilingGroupName}/recommendations:
    GET:
      summary: Amazon Web Services Getrecommendations
      description: Returns a list of Recommendation objects that contain recommendations for a profiling group for a given time period. A list of Anomaly objects that contains details about anomalies detected in the profiling group for the same time period is also returned.
      operationId: amazonWebServicesGetRecommendations
      tags:
      - Internal
  /internal/profilingGroups/{profilingGroupName}/findingsReports:
    GET:
      summary: Amazon Web Services Listfindingsreports
      description: List the available reports for a given profiling group and time range.
      operationId: amazonWebServicesListFindingsReports
      tags:
      - Internal
  /internal/profilingGroups/{profilingGroupName}/anomalies/{anomalyInstanceId}/feedback:
    POST:
      summary: Amazon Web Services Submitfeedback
      description: Sends feedback to CodeGuru Profiler about whether the anomaly detected by the analysis is useful or not.
      operationId: amazonWebServicesSubmitFeedback
      tags:
      - Internal
