openapi: 3.2.0
info:
  title: Amazon Web Services lakeformation Get Query Statistics API
  description: 'Lake Formation

    Defines the public endpoint for the Lake Formation service.'
tags:
- name: GetQueryStatistics
paths:
  /GetQueryStatistics:
    POST:
      summary: Amazon Web Services Getquerystatistics
      description: Retrieves statistics on the planning and execution of a query.
      operationId: amazonWebServicesGetQueryStatistics
      tags:
      - GetQueryStatistics
