openapi: 3.1.0
info:
  title: Amazon Web Services accessanalyzer 2012 09 25 Meshes API
  description: <p>Identity and Access Management Access Analyzer helps you to set, verify, and refine your IAM policies by providing a suite of capabilities. Its features include findings for external and unused access, basic and custom policy checks for validating policies, and policy generation to generate fine-grained policies. To start using IAM Access Analyzer to identify external or unused access, you first need to create an analyzer.</p> <p> <b>External access analyzers</b> help identify potential risks of accessing resources by enabling you to identify any resource policies that grant access to an external principal. It does this by using logic-based reasoning to analyze resource-based policies in your Amazon Web Services environment. An external principal can be another Amazon Web Services account, a root user, an IAM user or role, a federated user, an Amazon Web Services service, or an anonymous user. You can also use IAM Access Analyzer to preview public and cross-account access to your resources before deploying permissions changes.</p> <p> <b>Unused access analyzers</b> help identify potential identity access risks by enabling you to identify unused IAM roles, unused access keys, unused console passwords, and IAM principals with unused service and action-level permissions.</p> <p>Beyond findings, IAM Access Analyzer provides basic and custom policy checks to validate IAM policies before deploying permissions changes. You can use policy generation to refine permissions by attaching a policy generated using access activity logged in CloudTrail logs. </p> <p>This guide describes the IAM Access Analyzer operations that you can call programmatically. For general information about IAM Access Analyzer, see <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html">Identity and Access Management Access Analyzer</a> in the <b>IAM User Guide</b>.</p>
tags:
- name: Meshes
paths:
  /v20190125/meshes/{meshName}/virtualGateway/{virtualGatewayName}/gatewayRoutes:
    GET:
      summary: Amazon Web Services Listgatewayroutes
      description: Returns a list of existing gateway routes that are associated to a virtual gateway.
      operationId: amazonWebServicesListGatewayRoutes
      tags:
      - Meshes
  /v20190125/meshes:
    GET:
      summary: Amazon Web Services Listmeshes
      description: Returns a list of existing service meshes.
      operationId: amazonWebServicesListMeshes
      tags:
      - Meshes
  /v20190125/meshes/{meshName}/virtualRouter/{virtualRouterName}/routes:
    GET:
      summary: Amazon Web Services Listroutes
      description: Returns a list of existing routes in a service mesh.
      operationId: amazonWebServicesListRoutes
      tags:
      - Meshes
  /v20190125/meshes/{meshName}/virtualGateways:
    GET:
      summary: Amazon Web Services Listvirtualgateways
      description: Returns a list of existing virtual gateways in a service mesh.
      operationId: amazonWebServicesListVirtualGateways
      tags:
      - Meshes
  /v20190125/meshes/{meshName}/virtualNodes:
    GET:
      summary: Amazon Web Services Listvirtualnodes
      description: Returns a list of existing virtual nodes.
      operationId: amazonWebServicesListVirtualNodes
      tags:
      - Meshes
  /v20190125/meshes/{meshName}/virtualRouters:
    GET:
      summary: Amazon Web Services Listvirtualrouters
      description: Returns a list of existing virtual routers in a service mesh.
      operationId: amazonWebServicesListVirtualRouters
      tags:
      - Meshes
  /v20190125/meshes/{meshName}/virtualServices:
    GET:
      summary: Amazon Web Services Listvirtualservices
      description: Returns a list of existing virtual services in a service mesh.
      operationId: amazonWebServicesListVirtualServices
      tags:
      - Meshes
  /v20190125/meshes/{meshName}/virtualGateway/{virtualGatewayName}/gatewayRoutes/{gatewayRouteName}:
    PUT:
      summary: Amazon Web Services Updategatewayroute
      description: Updates an existing gateway route that is associated to a specified virtual gateway in a service mesh.
      operationId: amazonWebServicesUpdateGatewayRoute
      tags:
      - Meshes
  /v20190125/meshes/{meshName}:
    PUT:
      summary: Amazon Web Services Updatemesh
      description: Updates an existing service mesh.
      operationId: amazonWebServicesUpdateMesh
      tags:
      - Meshes
  /v20190125/meshes/{meshName}/virtualRouter/{virtualRouterName}/routes/{routeName}:
    PUT:
      summary: Amazon Web Services Updateroute
      description: Updates an existing route for a specified service mesh and virtual router.
      operationId: amazonWebServicesUpdateRoute
      tags:
      - Meshes
  /v20190125/meshes/{meshName}/virtualGateways/{virtualGatewayName}:
    PUT:
      summary: Amazon Web Services Updatevirtualgateway
      description: Updates an existing virtual gateway in a specified service mesh.
      operationId: amazonWebServicesUpdateVirtualGateway
      tags:
      - Meshes
  /v20190125/meshes/{meshName}/virtualNodes/{virtualNodeName}:
    PUT:
      summary: Amazon Web Services Updatevirtualnode
      description: Updates an existing virtual node in a specified service mesh.
      operationId: amazonWebServicesUpdateVirtualNode
      tags:
      - Meshes
  /v20190125/meshes/{meshName}/virtualRouters/{virtualRouterName}:
    PUT:
      summary: Amazon Web Services Updatevirtualrouter
      description: Updates an existing virtual router in a specified service mesh.
      operationId: amazonWebServicesUpdateVirtualRouter
      tags:
      - Meshes
  /v20190125/meshes/{meshName}/virtualServices/{virtualServiceName}:
    PUT:
      summary: Amazon Web Services Updatevirtualservice
      description: Updates an existing virtual service in a specified service mesh.
      operationId: amazonWebServicesUpdateVirtualService
      tags:
      - Meshes
