openapi: 3.2.0
info:
  title: Amazon Web Services mgn Start Import API
  description: The Application Migration Service service.
tags:
- name: StartImport
paths:
  /StartImport:
    POST:
      summary: Amazon Web Services Startimport
      description: Start import.
      operationId: amazonWebServicesStartImport
      tags:
      - StartImport
