openapi: 3.2.0
info:
  title: Amazon Web Services billingconductor List Billing Groups API
  description: Amazon Web Services Billing Conductor is a fully managed service that you can use to customize a proforma version of your billing data each month, to accurately show or chargeback your end customers.
tags:
- name: List Billing Groups
paths:
  /list-billing-groups:
    POST:
      summary: Amazon Web Services Listbillinggroups
      description: A paginated call to retrieve a list of billing groups for the given billing period. If you don't provide a billing group, the current billing period is used.
      operationId: amazonWebServicesListBillingGroups
      tags:
      - List Billing Groups
