openapi: 3.2.0
info:
  title: Amazon Web Services robomaker List Simulation Applications…
  description: This section provides documentation for the AWS RoboMaker API operations.
tags:
- name: List Simulation Applications
paths:
  /listSimulationApplications:
    POST:
      summary: Amazon Web Services Listsimulationapplications
      description: Returns a list of simulation applications. You can optionally provide filters to retrieve specific simulation applications.
      operationId: amazonWebServicesListSimulationApplications
      tags:
      - List Simulation Applications
