openapi: 3.2.0
info:
  title: Amazon Web Services neptune-graph Summary API
  description: Neptune Analytics is a new analytics database engine for Amazon Neptune that helps customers get to insights faster by quickly processing large amounts of graph data, invoking popular graph analytic algorithms in low-latency queries, and getting analytics results in seconds.
tags:
- name: Summary
paths:
  /summary:
    GET:
      summary: Amazon Web Services Getgraphsummary
      description: Gets a graph summary for a property graph.
      operationId: amazonWebServicesGetGraphSummary
      tags:
      - Summary
