openapi: 3.2.0
info:
  title: Amazon Web Services rolesanywhere Crl API
  description: Identity and Access Management Roles Anywhere provides a secure way for your workloads such as servers, containers, and applications that run outside of Amazon Web Services to obtain temporary Amazon Web Services credentials.
tags:
- name: Crl
paths:
  /crl/{crlId}:
    PATCH:
      summary: Amazon Web Services Updatecrl
      description: 'Updates the certificate revocation list (CRL). A CRL is a list of certificates that have been revoked by the issuing certificate authority (CA). IAM Roles Anywhere validates against the CRL before issuing credentials. Required permissions: rolesanywhere:UpdateCrl.'
      operationId: amazonWebServicesUpdateCrl
      tags:
      - Crl
  /crl/{crlId}/disable:
    POST:
      summary: Amazon Web Services Disablecrl
      description: 'Disables a certificate revocation list (CRL). Required permissions: rolesanywhere:DisableCrl.'
      operationId: amazonWebServicesDisableCrl
      tags:
      - Crl
  /crl/{crlId}/enable:
    POST:
      summary: Amazon Web Services Enablecrl
      description: 'Enables a certificate revocation list (CRL). When enabled, certificates stored in the CRL are unauthorized to receive session credentials. Required permissions: rolesanywhere:EnableCrl.'
      operationId: amazonWebServicesEnableCrl
      tags:
      - Crl
