openapi: 3.2.0
info:
  title: Amazon Web Services iot-roborunner Delete Worker API
  description: An example service, deployed with the Octane Service creator, which will echo the string
tags:
- name: deleteWorker
paths:
  /deleteWorker:
    POST:
      summary: Amazon Web Services Deleteworker
      description: Grants permission to delete a worker
      operationId: amazonWebServicesDeleteWorker
      tags:
      - deleteWorker
