openapi: 3.2.0
info:
  title: Amazon Web Services managedblockchain-query Get Token…
  description: Amazon Managed Blockchain (AMB) Query provides you with convenient access to multi-blockchain network data, which makes it easier for you to extract contextual data related to blockchain activity.
tags:
- name: Get Token Balance
paths:
  /get-token-balance:
    POST:
      summary: Amazon Web Services Gettokenbalance
      description: Gets the balance of a specific token, including native tokens, for a given address (wallet or contract) on the blockchain. Only the native tokens BTC and ETH, and the ERC-20, ERC-721, and ERC 1155 token standards are supported.
      operationId: amazonWebServicesGetTokenBalance
      tags:
      - Get Token Balance
