openapi: 3.2.0
info:
  title: Amazon Web Services oam Update Link API
  description: Use Amazon CloudWatch Observability Access Manager to create and manage links between source accounts and monitoring accounts by using CloudWatch cross-account observability.
tags:
- name: UpdateLink
paths:
  /UpdateLink:
    POST:
      summary: Amazon Web Services Updatelink
      description: Use this operation to change what types of data are shared from a source account to its linked monitoring account sink. You can't change the sink or change the monitoring account with this operation. To update the list of tags associated with the sink, use TagResource.
      operationId: amazonWebServicesUpdateLink
      tags:
      - UpdateLink
