openapi: 3.2.0
info:
  title: Amazon Web Services connect Contact Evaluations API
  description: Amazon Connect is a cloud-based contact center solution that you use to set up and manage a customer contact center and provide reliable customer engagement at any scale.
tags:
- name: Contact Evaluations
paths:
  /contact-evaluations/{InstanceId}/{EvaluationId}:
    POST:
      summary: Amazon Web Services Updatecontactevaluation
      description: Updates details about a contact evaluation in the specified Amazon Connect instance. A contact evaluation must be in draft state. Answers included in the request are merged with existing answers for the given evaluation. An answer or note can be deleted by passing an empty object ({}) to the question identifier.
      operationId: amazonWebServicesUpdateContactEvaluation
      tags:
      - Contact Evaluations
  /contact-evaluations/{InstanceId}:
    PUT:
      summary: Amazon Web Services Startcontactevaluation
      description: Starts an empty evaluation in the specified Amazon Connect instance, using the given evaluation form for the particular contact. The evaluation form version used for the contact evaluation corresponds to the currently activated version. If no version is activated for the evaluation form, the contact evaluation cannot be started. Evaluations created through the public API do not contain answer values suggested from automation.
      operationId: amazonWebServicesStartContactEvaluation
      tags:
      - Contact Evaluations
  /contact-evaluations/{InstanceId}/{EvaluationId}/submit:
    POST:
      summary: Amazon Web Services Submitcontactevaluation
      description: Submits a contact evaluation in the specified Amazon Connect instance. Answers included in the request are merged with existing answers for the given evaluation. If no answers or notes are passed, the evaluation is submitted with the existing answers and notes. You can delete an answer or note by passing an empty object ({}) to the question identifier. If a contact evaluation is already in submitted state, this operation will trigger a resubmission.
      operationId: amazonWebServicesSubmitContactEvaluation
      tags:
      - Contact Evaluations
