openapi: 3.2.0
info:
  title: Amazon Web Services batch Registerjobdefinition API
  description: 'Batch

    Using Batch, you can run batch computing workloads on the Amazon Web Services Cloud.'
tags:
- name: Registerjobdefinition
paths:
  /v1/registerjobdefinition:
    POST:
      summary: Amazon Web Services Registerjobdefinition
      description: Registers an Batch job definition.
      operationId: amazonWebServicesRegisterJobDefinition
      tags:
      - Registerjobdefinition
