openapi: 3.2.0
info:
  title: Amazon Web Services billingconductor Delete Pricing Plan API
  description: Amazon Web Services Billing Conductor is a fully managed service that you can use to customize a proforma version of your billing data each month, to accurately show or chargeback your end customers.
tags:
- name: Delete Pricing Plan
paths:
  /delete-pricing-plan:
    POST:
      summary: Amazon Web Services Deletepricingplan
      description: Deletes a pricing plan. The pricing plan must not be associated with any billing groups to delete successfully.
      operationId: amazonWebServicesDeletePricingPlan
      tags:
      - Delete Pricing Plan
