openapi: 3.2.0
info:
  title: Amazon Web Services ssm-incidents Delete Response Plan API
  description: Systems Manager Incident Manager is an incident management console designed to help users mitigate and recover from incidents affecting their Amazon Web Services-hosted applications.
tags:
- name: Delete Response Plan
paths:
  /deleteResponsePlan:
    POST:
      summary: Amazon Web Services Deleteresponseplan
      description: Deletes the specified response plan. Deleting a response plan stops all linked CloudWatch alarms and EventBridge events from creating an incident with this response plan.
      operationId: amazonWebServicesDeleteResponsePlan
      tags:
      - Delete Response Plan
