openapi: 3.2.0
info:
  title: Amazon Web Services eks Cluster Registrations API
  description: Amazon Elastic Kubernetes Service (Amazon EKS) is a managed service that makes it easy for you to run Kubernetes on Amazon Web Services without needing to setup or maintain your own Kubernetes control plane.
tags:
- name: Cluster Registrations
paths:
  /cluster-registrations/{name}:
    DELETE:
      summary: Amazon Web Services Deregistercluster
      description: Deregisters a connected cluster to remove it from the Amazon EKS control plane. A connected cluster is a Kubernetes cluster that you've connected to your control plane using the Amazon EKS Connector.
      operationId: amazonWebServicesDeregisterCluster
      tags:
      - Cluster Registrations
  /cluster-registrations:
    POST:
      summary: Amazon Web Services Registercluster
      description: Connects a Kubernetes cluster to the Amazon EKS control plane. Any Kubernetes cluster can be connected to the Amazon EKS control plane to view current information about the cluster and its nodes. Cluster connection requires two steps. First, send a RegisterClusterRequest to add it to the Amazon EKS control plane. Second, a Manifest containing the activationID and activationCode must be applied to the Kubernetes cluster through it's native provider to provide visibility. After the manifest is updated and applied, the connected cluster is visible to the Amazon EKS control plane. If the manifest isn't applied within three days, the connected cluster will no longer be visible and must be deregistered using DeregisterCluster.
      operationId: amazonWebServicesRegisterCluster
      tags:
      - Cluster Registrations
