openapi: 3.2.0
info:
  title: Amazon Web Services iotwireless Wireless Device Import…
  description: AWS IoT Wireless provides bi-directional communication between internet-connected wireless devices and the AWS Cloud.
tags:
- name: Wireless Device Import Tasks
paths:
  /wireless_device_import_tasks:
    GET:
      summary: Amazon Web Services Listwirelessdeviceimporttasks
      description: List wireless devices that have been added to an import task.
      operationId: amazonWebServicesListWirelessDeviceImportTasks
      tags:
      - Wireless Device Import Tasks
