openapi: 3.2.0
info:
  title: Amazon Web Services entityresolution Providerservices API
  description: Welcome to the Entity Resolution API Reference.
tags:
- name: Providerservices
paths:
  /providerservices/{providerName}/{providerServiceName}:
    GET:
      summary: Amazon Web Services Getproviderservice
      description: Returns the ProviderService of a given name.
      operationId: amazonWebServicesGetProviderService
      tags:
      - Providerservices
  /providerservices:
    GET:
      summary: Amazon Web Services Listproviderservices
      description: Returns a list of all the ProviderServices that are available in this Amazon Web Services Region.
      operationId: amazonWebServicesListProviderServices
      tags:
      - Providerservices
