openapi: 3.2.0
info:
  title: Amazon Web Services launch-wizard List Workloads API
  description: Launch Wizard offers a guided way of sizing, configuring, and deploying Amazon Web Services resources for third party applications, such as Microsoft SQL Server Always On and HANA based SAP systems, without the need to manually identify and provision individual Amazon Web Services resources.
tags:
- name: listWorkloads
paths:
  /listWorkloads:
    POST:
      summary: Amazon Web Services Listworkloads
      description: Lists the workloads.
      operationId: amazonWebServicesListWorkloads
      tags:
      - listWorkloads
