openapi: 3.2.0
info:
  title: Amazon Web Services ivschat Send Event API
  description: 'Introduction


    The Amazon IVS Chat control-plane API enables you to create and manage Amazon IVS Chat resources.'
tags:
- name: Send Event
paths:
  /SendEvent:
    POST:
      summary: Amazon Web Services Sendevent
      description: Sends an event to a room. Use this within your application’s business logic to send events to clients of a room; e.g., to notify clients to change the way the chat UI is rendered.
      operationId: amazonWebServicesSendEvent
      tags:
      - Send Event
