openapi: 3.2.0
info:
  title: Amazon Web Services route53 Accountlimit API
  description: 'Amazon Route 53 is a highly available and scalable Domain Name System (DNS) web service.


    You can use Route 53 to:


    Register domain names.


    For more information, see How domain registration works.


    Route internet traffic to the resources for your domain


    For more information, see How internet traffic is routed to your website or web application.


    Check the health of your resources.


    For more information, see How Route 53 checks the health of your resources.'
tags:
- name: Accountlimit
paths:
  /2013-04-01/accountlimit/{Type}:
    GET:
      summary: Amazon Web Services Getaccountlimit
      description: Gets the specified limit for the current account, for example, the maximum number of health checks that you can create using the account. For the default limit, see Limits in the Amazon Route 53 Developer Guide. To request a higher limit, open a case. You can also view account limits in Amazon Web Services Trusted Advisor. Sign in to the Amazon Web Services Management Console and open the Trusted Advisor console at https://console.aws.amazon.com/trustedadvisor/. Then choose Service limits in the navigation pane.
      operationId: amazonWebServicesGetAccountLimit
      tags:
      - Accountlimit
