openapi: 3.2.0
info:
  title: Amazon Web Services codeartifact Domain API
  description: CodeArtifact is a fully managed artifact repository compatible with language-native package managers and build tools such as npm, Apache Maven, pip, and dotnet.
tags:
- name: Domain
paths:
  /v1/domain:
    GET:
      summary: Amazon Web Services Describedomain
      description: Returns a DomainDescription object that contains information about the requested domain.
      operationId: amazonWebServicesDescribeDomain
      tags:
      - Domain
  /v1/domain/permissions/policy:
    PUT:
      summary: Amazon Web Services Putdomainpermissionspolicy
      description: Sets a resource policy on a domain that specifies permissions to access it. When you call PutDomainPermissionsPolicy, the resource policy on the domain is ignored when evaluting permissions. This ensures that the owner of a domain cannot lock themselves out of the domain, which would prevent them from being able to update the resource policy.
      operationId: amazonWebServicesPutDomainPermissionsPolicy
      tags:
      - Domain
  /v1/domain/repositories:
    POST:
      summary: Amazon Web Services Listrepositoriesindomain
      description: Returns a list of RepositorySummary objects. Each RepositorySummary contains information about a repository in the specified domain and that matches the input parameters.
      operationId: amazonWebServicesListRepositoriesInDomain
      tags:
      - Domain
