openapi: 3.2.0
info:
  title: Amazon Web Services kafkaconnect Custom Plugins API
  description: ''
tags:
- name: Custom Plugins
paths:
  /v1/custom-plugins:
    GET:
      summary: Amazon Web Services Listcustomplugins
      description: Returns a list of all of the custom plugins in this account and Region.
      operationId: amazonWebServicesListCustomPlugins
      tags:
      - Custom Plugins
  /v1/custom-plugins/{customPluginArn}:
    GET:
      summary: Amazon Web Services Describecustomplugin
      description: A summary description of the custom plugin.
      operationId: amazonWebServicesDescribeCustomPlugin
      tags:
      - Custom Plugins
