openapi: 3.2.0
info:
  title: Amazon Web Services m2 Engine Versions API
  description: Amazon Web Services Mainframe Modernization provides tools and resources to help you plan and implement migration and modernization from mainframes to Amazon Web Services managed runtime environments. It provides tools for analyzing existing mainframe applications, developing or updating mainframe applications using COBOL or PL/I, and implementing an automated pipeline for continuous integration and continuous delivery (CI/CD) of the applications.
tags:
- name: Engine Versions
paths:
  /engine-versions:
    GET:
      summary: Amazon Web Services Listengineversions
      description: Lists the available engine versions.
      operationId: amazonWebServicesListEngineVersions
      tags:
      - Engine Versions
