openapi: 3.2.0
info:
  title: Amazon Web Services mgn Create Application API
  description: The Application Migration Service service.
tags:
- name: CreateApplication
paths:
  /CreateApplication:
    POST:
      summary: Amazon Web Services Createapplication
      description: Create application.
      operationId: amazonWebServicesCreateApplication
      tags:
      - CreateApplication
