openapi: 3.2.0
info:
  title: Amazon Web Services migrationhubstrategy Get Portfolio…
  description: 'Migration Hub Strategy Recommendations

    This API reference provides descriptions, syntax, and other details about each of the actions and data types for Migration Hub Strategy Recommendations (Strategy Recommendations). The topic for each action shows the API request parameters and the response. Alternatively, you can use one of the AWS SDKs to access an API that is tailored to the programming language or platform that you''re using. For more information, see AWS SDKs.'
tags:
- name: Get Portfolio Summary
paths:
  /get-portfolio-summary:
    GET:
      summary: Amazon Web Services Getportfoliosummary
      description: Retrieves overall summary including the number of servers to rehost and the overall number of anti-patterns.
      operationId: amazonWebServicesGetPortfolioSummary
      tags:
      - Get Portfolio Summary
