openapi: 3.2.0
info:
  title: Amazon Web Services iot V2 Logging Options API
  description: 'IoT

    IoT provides secure, bi-directional communication between Internet-connected devices (such as sensors, actuators, embedded devices, or smart appliances) and the Amazon Web Services cloud.'
tags:
- name: V2 Logging Options
paths:
  /v2LoggingOptions:
    POST:
      summary: Amazon Web Services Setv2loggingoptions
      description: Sets the logging options for the V2 logging service. Requires permission to access the SetV2LoggingOptions action.
      operationId: amazonWebServicesSetV2LoggingOptions
      tags:
      - V2 Logging Options
