openapi: 3.2.0
info:
  title: Amazon Web Services ivs Delete Stream Key API
  description: 'Introduction


    The Amazon Interactive Video Service (IVS) API is REST compatible, using a standard HTTP API and an Amazon Web Services EventBridge event stream for responses.'
tags:
- name: DeleteStreamKey
paths:
  /DeleteStreamKey:
    POST:
      summary: Amazon Web Services Deletestreamkey
      description: Deletes the stream key for the specified ARN, so it can no longer be used to stream.
      operationId: amazonWebServicesDeleteStreamKey
      tags:
      - DeleteStreamKey
