openapi: 3.2.0
info:
  title: Amazon Web Services groundstation Satellite API
  description: Welcome to the AWS Ground Station API Reference. AWS Ground Station is a fully managed service that enables you to control satellite communications, downlink and process satellite data, and scale your satellite operations efficiently and cost-effectively without having to build or manage your own ground station infrastructure.
tags:
- name: Satellite
paths:
  /satellite/{satelliteId}:
    GET:
      summary: Amazon Web Services Getsatellite
      description: Returns a satellite.
      operationId: amazonWebServicesGetSatellite
      tags:
      - Satellite
  /satellite:
    GET:
      summary: Amazon Web Services Listsatellites
      description: Returns a list of satellites.
      operationId: amazonWebServicesListSatellites
      tags:
      - Satellite
