openapi: 3.2.0
info:
  title: Amazon Web Services kinesisvideo Describe Stream API
  description: ''
tags:
- name: Describe Stream
paths:
  /describeStream:
    POST:
      summary: Amazon Web Services Describestream
      description: Returns the most current information about the specified stream. You must specify either the StreamName or the StreamARN.
      operationId: amazonWebServicesDescribeStream
      tags:
      - Describe Stream
