openapi: 3.2.0
info:
  title: Amazon Web Services ivs Delete Playback Restriction Policy…
  description: 'Introduction


    The Amazon Interactive Video Service (IVS) API is REST compatible, using a standard HTTP API and an Amazon Web Services EventBridge event stream for responses.'
tags:
- name: DeletePlaybackRestrictionPolicy
paths:
  /DeletePlaybackRestrictionPolicy:
    POST:
      summary: Amazon Web Services Deleteplaybackrestrictionpolicy
      description: Deletes the specified playback restriction policy.
      operationId: amazonWebServicesDeletePlaybackRestrictionPolicy
      tags:
      - DeletePlaybackRestrictionPolicy
