openapi: 3.2.0
info:
  title: Amazon Web Services robomaker Update Simulation Application…
  description: This section provides documentation for the AWS RoboMaker API operations.
tags:
- name: Update Simulation Application
paths:
  /updateSimulationApplication:
    POST:
      summary: Amazon Web Services Updatesimulationapplication
      description: Updates a simulation application.
      operationId: amazonWebServicesUpdateSimulationApplication
      tags:
      - Update Simulation Application
