openapi: 3.2.0
info:
  title: Amazon Web Services lookoutmetrics Get Anomaly Group API
  description: This is the Amazon Lookout for Metrics API Reference. For an introduction to the service with tutorials for getting started, visit Amazon Lookout for Metrics Developer Guide.
tags:
- name: GetAnomalyGroup
paths:
  /GetAnomalyGroup:
    POST:
      summary: Amazon Web Services Getanomalygroup
      description: Returns details about a group of anomalous metrics.
      operationId: amazonWebServicesGetAnomalyGroup
      tags:
      - GetAnomalyGroup
