openapi: 3.2.0
info:
  title: Amazon Web Services ivschat Delete Logging Configuration API
  description: 'Introduction


    The Amazon IVS Chat control-plane API enables you to create and manage Amazon IVS Chat resources.'
tags:
- name: DeleteLoggingConfiguration
paths:
  /DeleteLoggingConfiguration:
    POST:
      summary: Amazon Web Services Deleteloggingconfiguration
      description: Deletes the specified logging configuration.
      operationId: amazonWebServicesDeleteLoggingConfiguration
      tags:
      - DeleteLoggingConfiguration
