openapi: 3.2.0
info:
  title: Amazon Web Services rbin List Rules API
  description: This is the Recycle Bin API Reference.
tags:
- name: List Rules
paths:
  /list-rules:
    POST:
      summary: Amazon Web Services Listrules
      description: Lists the Recycle Bin retention rules in the Region.
      operationId: amazonWebServicesListRules
      tags:
      - List Rules
