openapi: 3.2.0
info:
  title: Amazon Web Services ssm-incidents List Related Items API
  description: Systems Manager Incident Manager is an incident management console designed to help users mitigate and recover from incidents affecting their Amazon Web Services-hosted applications.
tags:
- name: List Related Items
paths:
  /listRelatedItems:
    POST:
      summary: Amazon Web Services Listrelateditems
      description: List all related items for an incident record.
      operationId: amazonWebServicesListRelatedItems
      tags:
      - List Related Items
