openapi: 3.2.0
info:
  title: Amazon Web Services wellarchitected Consolidated Report API
  description: 'Well-Architected Tool

    This is the Well-Architected Tool API Reference. The WA Tool API provides programmatic access to the Well-Architected Tool in the Amazon Web Services Management Console. For information about the Well-Architected Tool, see the Well-Architected Tool User Guide.'
tags:
- name: consolidatedReport
paths:
  /consolidatedReport:
    GET:
      summary: Amazon Web Services Getconsolidatedreport
      description: Get a consolidated report of your workloads. You can optionally choose to include workloads that have been shared with you.
      operationId: amazonWebServicesGetConsolidatedReport
      tags:
      - consolidatedReport
