openapi: 3.2.0
info:
  title: Amazon Web Services mgn Pause Replication API
  description: The Application Migration Service service.
tags:
- name: PauseReplication
paths:
  /PauseReplication:
    POST:
      summary: Amazon Web Services Pausereplication
      description: Pause Replication.
      operationId: amazonWebServicesPauseReplication
      tags:
      - PauseReplication
