openapi: 3.2.0
info:
  title: Amazon Web Services iot Cacertificate API
  description: 'IoT

    IoT provides secure, bi-directional communication between Internet-connected devices (such as sensors, actuators, embedded devices, or smart appliances) and the Amazon Web Services cloud.'
tags:
- name: Cacertificate
paths:
  /cacertificate/{caCertificateId}:
    PUT:
      summary: Amazon Web Services Updatecacertificate
      description: Updates a registered CA certificate. Requires permission to access the UpdateCACertificate action.
      operationId: amazonWebServicesUpdateCACertificate
      tags:
      - Cacertificate
  /cacertificate:
    POST:
      summary: Amazon Web Services Registercacertificate
      description: Registers a CA certificate with Amazon Web Services IoT Core. There is no limit to the number of CA certificates you can register in your Amazon Web Services account. You can register up to 10 CA certificates with the same CA subject field per Amazon Web Services account. Requires permission to access the RegisterCACertificate action.
      operationId: amazonWebServicesRegisterCACertificate
      tags:
      - Cacertificate
