openapi: 3.2.0
info:
  title: Amazon Web Services sagemaker-geospatial Tile API
  description: Provides APIs for creating and managing SageMaker geospatial resources.
tags:
- name: Tile
paths:
  /tile/{z}/{x}/{y}:
    GET:
      summary: Amazon Web Services Gettile
      description: Gets a web mercator tile for the given Earth Observation job.
      operationId: amazonWebServicesGetTile
      tags:
      - Tile
