openapi: 3.2.0
info:
  title: Amazon Web Services amp Scrapers API
  description: Amazon Managed Service for Prometheus is a serverless, Prometheus-compatible monitoring service for container metrics that makes it easier to securely monitor container environments at scale.
tags:
- name: Scrapers
paths:
  /scrapers:
    GET:
      summary: Amazon Web Services Listscrapers
      description: The ListScrapers operation lists all of the scrapers in your account. This includes scrapers being created or deleted. You can optionally filter the returned list.
      operationId: amazonWebServicesListScrapers
      tags:
      - Scrapers
  /scrapers/{scraperId}:
    GET:
      summary: Amazon Web Services Describescraper
      description: The DescribeScraper operation displays information about an existing scraper.
      operationId: amazonWebServicesDescribeScraper
      tags:
      - Scrapers
