openapi: 3.2.0
info:
  title: Amazon Web Services lookoutmetrics List Metric Sets API
  description: This is the Amazon Lookout for Metrics API Reference. For an introduction to the service with tutorials for getting started, visit Amazon Lookout for Metrics Developer Guide.
tags:
- name: ListMetricSets
paths:
  /ListMetricSets:
    POST:
      summary: Amazon Web Services Listmetricsets
      description: Lists the datasets in the current AWS Region. Amazon Lookout for Metrics API actions are eventually consistent. If you do a read operation on a resource immediately after creating or modifying it, use retries to allow time for the write operation to complete.
      operationId: amazonWebServicesListMetricSets
      tags:
      - ListMetricSets
