openapi: 3.2.0
info:
  title: Amazon Web Services apigateway Restapis?mode=import API
  description: 'Amazon API Gateway

    Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.'
tags:
- name: Restapis?mode=import
paths:
  /restapis?mode=import:
    POST:
      summary: Amazon Web Services Importrestapi
      description: A feature of the API Gateway control service for creating a new API from an external API definition file.
      operationId: amazonWebServicesImportRestApi
      tags:
      - Restapis?mode=import
