openapi: 3.2.0
info:
  title: Amazon Web Services iotwireless Device Profiles API
  description: AWS IoT Wireless provides bi-directional communication between internet-connected wireless devices and the AWS Cloud.
tags:
- name: Device Profiles
paths:
  /device-profiles:
    GET:
      summary: Amazon Web Services Listdeviceprofiles
      description: Lists the device profiles registered to your AWS account.
      operationId: amazonWebServicesListDeviceProfiles
      tags:
      - Device Profiles
  /device-profiles/{Id}:
    GET:
      summary: Amazon Web Services Getdeviceprofile
      description: Gets information about a device profile.
      operationId: amazonWebServicesGetDeviceProfile
      tags:
      - Device Profiles
