openapi: 3.2.0
info:
  title: Amazon Web Services mgn List Imports API
  description: The Application Migration Service service.
tags:
- name: ListImports
paths:
  /ListImports:
    POST:
      summary: Amazon Web Services Listimports
      description: List imports.
      operationId: amazonWebServicesListImports
      tags:
      - ListImports
