openapi: 3.2.0
info:
  title: Amazon Web Services AWS S3 Bucket Location API
  description: 'The API for Amazon Simple Storage Service (Amazon S3) provides an object

    storage solution with top-notch scalability, data availability, security,

    and performance. It caters to customers of varying sizes and industries,

    offering the ability to store and secure any volume of data for a wide

    range of purposes, including data lakes, cloud-native applications, and

    mobile apps.'
tags:
- name: Bucket Location
paths:
  /{Bucket}?location:
    GET:
      summary: Amazon Web Services Get Bucket Location
      description: This operation is not supported by directory buckets Returns the Region the bucket resides in
      tags:
      - Bucket Location
      operationId: getBucketLocation
