openapi: 3.2.0
info:
  title: Amazon Web Services controltower Get Baseline Operation API
  description: These interfaces allow you to apply the Amazon Web Services library of pre-defined controls to your organizational units, programmatically.
tags:
- name: Get Baseline Operation
paths:
  /get-baseline-operation:
    POST:
      summary: Amazon Web Services Getbaselineoperation
      description: 'Returns the details of an asynchronous baseline operation, as initiated by any of these APIs: EnableBaseline, DisableBaseline, UpdateEnabledBaseline, ResetEnabledBaseline. A status message is displayed in case of operation failure.'
      operationId: amazonWebServicesGetBaselineOperation
      tags:
      - Get Baseline Operation
