openapi: 3.2.0
info:
  title: Amazon Web Services ssm-sap Get Resource Permission API
  description: This API reference provides descriptions, syntax, and other details about each of the actions and data types for AWS Systems Manager for SAP. The topic for each action shows the API request parameters and responses.
tags:
- name: Get Resource Permission
paths:
  /get-resource-permission:
    POST:
      summary: Amazon Web Services Getresourcepermission
      description: Gets permissions associated with the target database.
      operationId: amazonWebServicesGetResourcePermission
      tags:
      - Get Resource Permission
