openapi: 3.2.0
info:
  title: Amazon Web Services robomaker Describe Robot Application API
  description: This section provides documentation for the AWS RoboMaker API operations.
tags:
- name: Describe Robot Application
paths:
  /describeRobotApplication:
    POST:
      summary: Amazon Web Services Describerobotapplication
      description: Describes a robot application.
      operationId: amazonWebServicesDescribeRobotApplication
      tags:
      - Describe Robot Application
