openapi: 3.2.0
info:
  title: Amazon Web Services imagebuilder List Image Scan Finding…
  description: EC2 Image Builder is a fully managed Amazon Web Services service that makes it easier to automate the creation, management, and deployment of customized, secure, and up-to-date "golden" server images that are pre-installed and pre-configured with software and settings to meet specific IT standards.
tags:
- name: ListImageScanFindingAggregations
paths:
  /ListImageScanFindingAggregations:
    POST:
      summary: Amazon Web Services Listimagescanfindingaggregations
      description: 'Returns a list of image scan aggregations for your account. You can filter by the type of key that Image Builder uses to group results. For example, if you want to get a list of findings by severity level for one of your pipelines, you might specify your pipeline with the imagePipelineArn filter. If you don''t specify a filter, Image Builder returns an aggregation for your account. To streamline results, you can use the following filters in your request: accountId imageBuildVersionArn imagePipelineArn vulnerabilityId'
      operationId: amazonWebServicesListImageScanFindingAggregations
      tags:
      - ListImageScanFindingAggregations
