openapi: 3.2.0
info:
  title: Amazon Web Services codecatalyst Session API
  description: Welcome to the Amazon CodeCatalyst API reference.
tags:
- name: Session
paths:
  /session:
    GET:
      summary: Amazon Web Services Verifysession
      description: Verifies whether the calling user has a valid Amazon CodeCatalyst login and session. If successful, this returns the ID of the user in Amazon CodeCatalyst.
      operationId: amazonWebServicesVerifySession
      tags:
      - Session
