openapi: 3.2.0
info:
  title: Amazon Web Services iot Thing Registration Tasks API
  description: 'IoT

    IoT provides secure, bi-directional communication between Internet-connected devices (such as sensors, actuators, embedded devices, or smart appliances) and the Amazon Web Services cloud.'
tags:
- name: Thing Registration Tasks
paths:
  /thing-registration-tasks/{taskId}:
    GET:
      summary: Amazon Web Services Describethingregistrationtask
      description: Describes a bulk thing provisioning task. Requires permission to access the DescribeThingRegistrationTask action.
      operationId: amazonWebServicesDescribeThingRegistrationTask
      tags:
      - Thing Registration Tasks
  /thing-registration-tasks/{taskId}/reports:
    GET:
      summary: Amazon Web Services Listthingregistrationtaskreports
      description: Information about the thing registration tasks.
      operationId: amazonWebServicesListThingRegistrationTaskReports
      tags:
      - Thing Registration Tasks
  /thing-registration-tasks:
    POST:
      summary: Amazon Web Services Startthingregistrationtask
      description: Creates a bulk thing provisioning task. Requires permission to access the StartThingRegistrationTask action.
      operationId: amazonWebServicesStartThingRegistrationTask
      tags:
      - Thing Registration Tasks
  /thing-registration-tasks/{taskId}/cancel:
    PUT:
      summary: Amazon Web Services Stopthingregistrationtask
      description: Cancels a bulk thing provisioning task. Requires permission to access the StopThingRegistrationTask action.
      operationId: amazonWebServicesStopThingRegistrationTask
      tags:
      - Thing Registration Tasks
