openapi: 3.2.0
info:
  title: Amazon Web Services ssm-incidents Get Replication Set API
  description: Systems Manager Incident Manager is an incident management console designed to help users mitigate and recover from incidents affecting their Amazon Web Services-hosted applications.
tags:
- name: getReplicationSet
paths:
  /getReplicationSet:
    GET:
      summary: Amazon Web Services Getreplicationset
      description: Retrieve your Incident Manager replication set.
      operationId: amazonWebServicesGetReplicationSet
      tags:
      - getReplicationSet
