openapi: 3.2.0
info:
  title: Amazon Web Services mgn List Exports API
  description: The Application Migration Service service.
tags:
- name: ListExports
paths:
  /ListExports:
    POST:
      summary: Amazon Web Services Listexports
      description: List exports.
      operationId: amazonWebServicesListExports
      tags:
      - ListExports
