openapi: 3.2.0
info:
  title: Amazon Web Services ivs-realtime Get Participant API
  description: 'Introduction


    The Amazon Interactive Video Service (IVS) real-time API is REST compatible, using a standard HTTP API and an AWS EventBridge event stream for responses.'
tags:
- name: GetParticipant
paths:
  /GetParticipant:
    POST:
      summary: Amazon Web Services Getparticipant
      description: Gets information about the specified participant token.
      operationId: amazonWebServicesGetParticipant
      tags:
      - GetParticipant
