openapi: 3.2.0
info:
  title: Amazon Web Services resource-explorer-2 Get Index API
  description: Amazon Web Services Resource Explorer is a resource search and discovery service.
tags:
- name: GetIndex
paths:
  /GetIndex:
    POST:
      summary: Amazon Web Services Getindex
      description: Retrieves details about the Amazon Web Services Resource Explorer index in the Amazon Web Services Region in which you invoked the operation.
      operationId: amazonWebServicesGetIndex
      tags:
      - GetIndex
