openapi: 3.2.0
info:
  title: Amazon Web Services lakeformation Create Lake Formation Opt…
  description: 'Lake Formation

    Defines the public endpoint for the Lake Formation service.'
tags:
- name: CreateLakeFormationOptIn
paths:
  /CreateLakeFormationOptIn:
    POST:
      summary: Amazon Web Services Createlakeformationoptin
      description: Enforce Lake Formation permissions for the given databases, tables, and principals.
      operationId: amazonWebServicesCreateLakeFormationOptIn
      tags:
      - CreateLakeFormationOptIn
