openapi: 3.2.0
info:
  title: Amazon Web Services appsync Types API
  description: AppSync provides API actions for creating and interacting with data sources using GraphQL from your application.
tags:
- name: Types
paths:
  /v1/apis/{apiId}/types/{typeName}/resolvers:
    GET:
      summary: Amazon Web Services Listresolvers
      description: Lists the resolvers for a given API and type.
      operationId: amazonWebServicesListResolvers
      tags:
      - Types
  /v1/apis/{apiId}/types:
    GET:
      summary: Amazon Web Services Listtypes
      description: Lists the types for a given API.
      operationId: amazonWebServicesListTypes
      tags:
      - Types
  /v1/apis/{apiId}/types/{typeName}/resolvers/{fieldName}:
    POST:
      summary: Amazon Web Services Updateresolver
      description: Updates a Resolver object.
      operationId: amazonWebServicesUpdateResolver
      tags:
      - Types
  /v1/apis/{apiId}/types/{typeName}:
    POST:
      summary: Amazon Web Services Updatetype
      description: Updates a Type object.
      operationId: amazonWebServicesUpdateType
      tags:
      - Types
