openapi: 3.2.0
info:
  title: Amazon Web Services lakeformation Grant Permissions API
  description: 'Lake Formation

    Defines the public endpoint for the Lake Formation service.'
tags:
- name: GrantPermissions
paths:
  /GrantPermissions:
    POST:
      summary: Amazon Web Services Grantpermissions
      description: Grants permissions to the principal to access metadata in the Data Catalog and data organized in underlying data storage such as Amazon S3. For information about permissions, see Security and Access Control to Metadata and Data.
      operationId: amazonWebServicesGrantPermissions
      tags:
      - GrantPermissions
