openapi: 3.2.0
info:
  title: Amazon Web Services snow-device-management Tasks API
  description: Amazon Web Services Snow Device Management documentation.
tags:
- name: Tasks
paths:
  /tasks:
    GET:
      summary: Amazon Web Services Listtasks
      description: Returns a list of tasks that can be filtered by state.
      operationId: amazonWebServicesListTasks
      tags:
      - Tasks
