openapi: 3.2.0
info:
  title: Amazon Web Services robomaker List Worlds API
  description: This section provides documentation for the AWS RoboMaker API operations.
tags:
- name: List Worlds
paths:
  /listWorlds:
    POST:
      summary: Amazon Web Services Listworlds
      description: Lists worlds.
      operationId: amazonWebServicesListWorlds
      tags:
      - List Worlds
