openapi: 3.2.0
info:
  title: Amazon Web Services honeycode Screendata API
  description: Amazon Honeycode is a fully managed service that allows you to quickly build mobile and web apps for teams—without programming. Build Honeycode apps for managing almost anything, like projects, customers, operations, approvals, resources, and even your team.
tags:
- name: Screendata
paths:
  /screendata:
    POST:
      summary: Amazon Web Services Getscreendata
      description: The GetScreenData API allows retrieval of data from a screen in a Honeycode app. The API allows setting local variables in the screen to filter, sort or otherwise affect what will be displayed on the screen.
      operationId: amazonWebServicesGetScreenData
      tags:
      - Screendata
