openapi: 3.2.0
info:
  title: Amazon Web Services lakeformation Create Lake Formation…
  description: 'Lake Formation

    Defines the public endpoint for the Lake Formation service.'
tags:
- name: CreateLakeFormationIdentityCenterConfiguration
paths:
  /CreateLakeFormationIdentityCenterConfiguration:
    POST:
      summary: Amazon Web Services Createlakeformationidentitycenterconfiguration
      description: Creates an IAM Identity Center connection with Lake Formation to allow IAM Identity Center users and groups to access Data Catalog resources.
      operationId: amazonWebServicesCreateLakeFormationIdentityCenterConfiguration
      tags:
      - CreateLakeFormationIdentityCenterConfiguration
