openapi: 3.2.0
info:
  title: Amazon Web Services outposts Sites API
  description: Amazon Web Services Outposts is a fully managed service that extends Amazon Web Services infrastructure, APIs, and tools to customer premises. By providing local access to Amazon Web Services managed infrastructure, Amazon Web Services Outposts enables customers to build and run applications on premises using the same programming interfaces as in Amazon Web Services Regions, while using local compute and storage resources for lower latency and local data processing needs.
tags:
- name: Sites
paths:
  /sites:
    GET:
      summary: Amazon Web Services Listsites
      description: Lists the Outpost sites for your Amazon Web Services account. Use filters to return specific results. Use filters to return specific results. If you specify multiple filters, the results include only the resources that match all of the specified filters. For a filter where you can specify multiple values, the results include items that match any of the values that you specify for the filter.
      operationId: amazonWebServicesListSites
      tags:
      - Sites
  /sites/{SiteId}:
    PATCH:
      summary: Amazon Web Services Updatesite
      description: Updates the specified site.
      operationId: amazonWebServicesUpdateSite
      tags:
      - Sites
  /sites/{SiteId}/address:
    PUT:
      summary: Amazon Web Services Updatesiteaddress
      description: Updates the address of the specified site. You can't update a site address if there is an order in progress. You must wait for the order to complete or cancel the order. You can update the operating address before you place an order at the site, or after all Outposts that belong to the site have been deactivated.
      operationId: amazonWebServicesUpdateSiteAddress
      tags:
      - Sites
  /sites/{SiteId}/rackPhysicalProperties:
    PATCH:
      summary: Amazon Web Services Updatesiterackphysicalproperties
      description: Update the physical and logistical details for a rack at a site. For more information about hardware requirements for racks, see Network readiness checklist in the Amazon Web Services Outposts User Guide. To update a rack at a site with an order of IN_PROGRESS, you must wait for the order to complete or cancel the order.
      operationId: amazonWebServicesUpdateSiteRackPhysicalProperties
      tags:
      - Sites
