openapi: 3.2.0
info:
  title: Amazon Web Services personalize-runtime Action…
  description: ''
tags:
- name: Action Recommendations
paths:
  /action-recommendations:
    POST:
      summary: Amazon Web Services Getactionrecommendations
      description: Returns a list of recommended actions in sorted in descending order by prediction score. Use the GetActionRecommendations API if you have a custom campaign that deploys a solution version trained with a PERSONALIZED_ACTIONS recipe. For more information about PERSONALIZED_ACTIONS recipes, see PERSONALIZED_ACTIONS recipes. For more information about getting action recommendations, see Getting action recommendations.
      operationId: amazonWebServicesGetActionRecommendations
      tags:
      - Action Recommendations
