openapi: 3.2.0
info:
  title: Amazon Web Services mgn Mark As Archived API
  description: The Application Migration Service service.
tags:
- name: MarkAsArchived
paths:
  /MarkAsArchived:
    POST:
      summary: Amazon Web Services Markasarchived
      description: Archives specific Source Servers by setting the SourceServer.isArchived property to true for specified SourceServers by ID. This command only works for SourceServers with a lifecycle. state which equals DISCONNECTED or CUTOVER.
      operationId: amazonWebServicesMarkAsArchived
      tags:
      - MarkAsArchived
