openapi: 3.2.0
info:
  title: Amazon Web Services controltower List Landingzones API
  description: These interfaces allow you to apply the Amazon Web Services library of pre-defined controls to your organizational units, programmatically.
tags:
- name: List Landingzones
paths:
  /list-landingzones:
    POST:
      summary: Amazon Web Services Listlandingzones
      description: Returns the landing zone ARN for the landing zone deployed in your managed account. This API also creates an ARN for existing accounts that do not yet have a landing zone ARN. Returns one landing zone ARN.
      operationId: amazonWebServicesListLandingZones
      tags:
      - List Landingzones
