openapi: 3.2.0
info:
  title: Amazon Web Services finspace-data Datasetsv2 API
  description: The FinSpace APIs let you take actions inside the FinSpace.
tags:
- name: Datasets V2
paths:
  /datasetsv2:
    GET:
      summary: Amazon Web Services Listdatasets
      description: Lists all of the active Datasets that a user has access to.
      operationId: amazonWebServicesListDatasets
      tags:
      - Datasets V2
  /datasetsv2/{datasetId}:
    PUT:
      summary: Amazon Web Services Updatedataset
      description: Updates a FinSpace Dataset.
      operationId: amazonWebServicesUpdateDataset
      tags:
      - Datasets V2
