openapi: 3.2.0
info:
  title: Amazon Web Services billingconductor List Custom Line Items…
  description: Amazon Web Services Billing Conductor is a fully managed service that you can use to customize a proforma version of your billing data each month, to accurately show or chargeback your end customers.
tags:
- name: List Custom Line Items
paths:
  /list-custom-line-items:
    POST:
      summary: Amazon Web Services Listcustomlineitems
      description: A paginated call to get a list of all custom line items (FFLIs) for the given billing period. If you don't provide a billing period, the current billing period is used.
      operationId: amazonWebServicesListCustomLineItems
      tags:
      - List Custom Line Items
