openapi: 3.2.0
info:
  title: Amazon Web Services appsync Schemacreation API
  description: AppSync provides API actions for creating and interacting with data sources using GraphQL from your application.
tags:
- name: Schemacreation
paths:
  /v1/apis/{apiId}/schemacreation:
    POST:
      summary: Amazon Web Services Startschemacreation
      description: Adds a new schema to your GraphQL API. This operation is asynchronous. Use to determine when it has completed.
      operationId: amazonWebServicesStartSchemaCreation
      tags:
      - Schemacreation
