openapi: 3.2.0
info:
  title: Amazon Web Services ivs List Playback Restriction Policies…
  description: 'Introduction


    The Amazon Interactive Video Service (IVS) API is REST compatible, using a standard HTTP API and an Amazon Web Services EventBridge event stream for responses.'
tags:
- name: ListPlaybackRestrictionPolicies
paths:
  /ListPlaybackRestrictionPolicies:
    POST:
      summary: Amazon Web Services Listplaybackrestrictionpolicies
      description: Gets summary information about playback restriction policies.
      operationId: amazonWebServicesListPlaybackRestrictionPolicies
      tags:
      - ListPlaybackRestrictionPolicies
