openapi: 3.2.0
info:
  title: Amazon Web Services signer Signing Jobs API
  description: AWS Signer is a fully managed code-signing service to help you ensure the trust and integrity of your code.
tags:
- name: Signing Jobs
paths:
  /signing-jobs/{jobId}:
    GET:
      summary: Amazon Web Services Describesigningjob
      description: Returns information about a specific code signing job. You specify the job by using the jobId value that is returned by the StartSigningJob operation.
      operationId: amazonWebServicesDescribeSigningJob
      tags:
      - Signing Jobs
  /signing-jobs:
    POST:
      summary: Amazon Web Services Startsigningjob
      description: 'Initiates a signing job to be performed on the code provided. Signing jobs are viewable by the ListSigningJobs operation for two years after they are performed. Note the following requirements: You must create an Amazon S3 source bucket. For more information, see Creating a Bucket in the Amazon S3 Getting Started Guide. Your S3 source bucket must be version enabled. You must create an S3 destination bucket. AWS Signer uses your S3 destination bucket to write your signed code. You specify the name of the source and destination buckets when calling the StartSigningJob operation. You must also specify a request token that identifies your request to Signer. You can call the DescribeSigningJob and the ListSigningJobs actions after you call StartSigningJob. For a Java example that shows how to use this action, see StartSigningJob.'
      operationId: amazonWebServicesStartSigningJob
      tags:
      - Signing Jobs
  /signing-jobs/{jobId}/revoke:
    PUT:
      summary: Amazon Web Services Revokesignature
      description: Changes the state of a signing job to REVOKED. This indicates that the signature is no longer valid.
      operationId: amazonWebServicesRevokeSignature
      tags:
      - Signing Jobs
  /signing-jobs/with-payload:
    POST:
      summary: Amazon Web Services Signpayload
      description: Signs a binary payload and returns a signature envelope.
      operationId: amazonWebServicesSignPayload
      tags:
      - Signing Jobs
