openapi: 3.2.0
info:
  title: Amazon Web Services mediatailor Playback Configuration API
  description: Use the AWS Elemental MediaTailor SDKs and CLI to configure scalable ad insertion and linear channels.
tags:
- name: Playback Configuration
paths:
  /playbackConfiguration/{Name}:
    GET:
      summary: Amazon Web Services Getplaybackconfiguration
      description: Retrieves a playback configuration. For information about MediaTailor configurations, see Working with configurations in AWS Elemental MediaTailor.
      operationId: amazonWebServicesGetPlaybackConfiguration
      tags:
      - Playback Configuration
  /playbackConfiguration:
    PUT:
      summary: Amazon Web Services Putplaybackconfiguration
      description: Creates a playback configuration. For information about MediaTailor configurations, see Working with configurations in AWS Elemental MediaTailor.
      operationId: amazonWebServicesPutPlaybackConfiguration
      tags:
      - Playback Configuration
