openapi: 3.2.0
info:
  title: Amazon Web Services ivs-realtime Delete Storage…
  description: 'Introduction


    The Amazon Interactive Video Service (IVS) real-time API is REST compatible, using a standard HTTP API and an AWS EventBridge event stream for responses.'
tags:
- name: DeleteStorageConfiguration
paths:
  /DeleteStorageConfiguration:
    POST:
      summary: Amazon Web Services Deletestorageconfiguration
      description: Deletes the storage configuration for the specified ARN. If you try to delete a storage configuration that is used by a Composition, you will get an error (409 ConflictException). To avoid this, for all Compositions that reference the storage configuration, first use StopComposition and wait for it to complete, then use DeleteStorageConfiguration.
      operationId: amazonWebServicesDeleteStorageConfiguration
      tags:
      - DeleteStorageConfiguration
