openapi: 3.2.0
info:
  title: Amazon Web Services controltower Enable Control API
  description: These interfaces allow you to apply the Amazon Web Services library of pre-defined controls to your organizational units, programmatically.
tags:
- name: Enable Control
paths:
  /enable-control:
    POST:
      summary: Amazon Web Services Enablecontrol
      description: This API call activates a control. It starts an asynchronous operation that creates Amazon Web Services resources on the specified organizational unit and the accounts it contains. The resources created will vary according to the control that you specify. For usage examples, see the Amazon Web Services Control Tower User Guide .
      operationId: amazonWebServicesEnableControl
      tags:
      - Enable Control
