openapi: 3.2.0
info:
  title: Amazon Web Services codeguru-security Account Configuration…
  description: Amazon CodeGuru Security is in preview release and is subject to change.
tags:
- name: Account Configuration
paths:
  /accountConfiguration/get:
    GET:
      summary: Amazon Web Services Getaccountconfiguration
      description: Use to get account level configuration.
      operationId: amazonWebServicesGetAccountConfiguration
      tags:
      - Account Configuration
