openapi: 3.2.0
info:
  title: Amazon Web Services connect Search Users API
  description: Amazon Connect is a cloud-based contact center solution that you use to set up and manage a customer contact center and provide reliable customer engagement at any scale.
tags:
- name: Search Users
paths:
  /search-users:
    POST:
      summary: Amazon Web Services Searchusers
      description: Searches users in an Amazon Connect instance, with optional filtering. AfterContactWorkTimeLimit is returned in milliseconds.
      operationId: amazonWebServicesSearchUsers
      tags:
      - Search Users
