openapi: 3.2.0
info:
  title: Amazon Web Services appsync Flush Cache API
  description: AppSync provides API actions for creating and interacting with data sources using GraphQL from your application.
tags:
- name: Flush Cache
paths:
  /v1/apis/{apiId}/FlushCache:
    DELETE:
      summary: Amazon Web Services Flushapicache
      description: Flushes an ApiCache object.
      operationId: amazonWebServicesFlushApiCache
      tags:
      - Flush Cache
