openapi: 3.2.0
info:
  title: Amazon Web Services bedrock Provisioned Model Throughput API
  description: Describes the API operations for creating and managing Amazon Bedrock models.
tags:
- name: Provisioned Model Throughput
paths:
  /provisioned-model-throughput:
    POST:
      summary: Amazon Web Services Createprovisionedmodelthroughput
      description: Creates a provisioned throughput with dedicated capacity for a foundation model or a fine-tuned model. For more information, see Provisioned throughput in the Bedrock User Guide.
      operationId: amazonWebServicesCreateProvisionedModelThroughput
      tags:
      - Provisioned Model Throughput
  /provisioned-model-throughput/{provisionedModelId}:
    PATCH:
      summary: Amazon Web Services Updateprovisionedmodelthroughput
      description: Update a provisioned throughput. For more information, see Provisioned throughput in the Bedrock User Guide.
      operationId: amazonWebServicesUpdateProvisionedModelThroughput
      tags:
      - Provisioned Model Throughput
