openapi: 3.2.0
info:
  title: Amazon Web Services ivs List Stream Keys API
  description: 'Introduction


    The Amazon Interactive Video Service (IVS) API is REST compatible, using a standard HTTP API and an Amazon Web Services EventBridge event stream for responses.'
tags:
- name: ListStreamKeys
paths:
  /ListStreamKeys:
    POST:
      summary: Amazon Web Services Liststreamkeys
      description: Gets summary information about stream keys for the specified channel.
      operationId: amazonWebServicesListStreamKeys
      tags:
      - ListStreamKeys
