openapi: 3.2.0
info:
  title: Amazon Web Services mgn Associate Source Servers API
  description: The Application Migration Service service.
tags:
- name: AssociateSourceServers
paths:
  /AssociateSourceServers:
    POST:
      summary: Amazon Web Services Associatesourceservers
      description: Associate source servers to application.
      operationId: amazonWebServicesAssociateSourceServers
      tags:
      - AssociateSourceServers
