openapi: 3.2.0
info:
  title: Amazon Web Services ivs-realtime Create Participant Token…
  description: 'Introduction


    The Amazon Interactive Video Service (IVS) real-time API is REST compatible, using a standard HTTP API and an AWS EventBridge event stream for responses.'
tags:
- name: CreateParticipantToken
paths:
  /CreateParticipantToken:
    POST:
      summary: Amazon Web Services Createparticipanttoken
      description: Creates an additional token for a specified stage. This can be done after stage creation or when tokens expire. Tokens always are scoped to the stage for which they are created. Encryption keys are owned by Amazon IVS and never used directly by your application.
      operationId: amazonWebServicesCreateParticipantToken
      tags:
      - CreateParticipantToken
