openapi: 3.2.0
info:
  title: Amazon Web Services iotevents Alarm Models API
  description: AWS IoT Events monitors your equipment or device fleets for failures or changes in operation, and triggers actions when such events occur. You can use AWS IoT Events API operations to create, read, update, and delete inputs and detector models, and to list their versions.
tags:
- name: Alarm Models
paths:
  /alarm-models:
    GET:
      summary: Amazon Web Services Listalarmmodels
      description: Lists the alarm models that you created. The operation returns only the metadata associated with each alarm model.
      operationId: amazonWebServicesListAlarmModels
      tags:
      - Alarm Models
  /alarm-models/{alarmModelName}:
    POST:
      summary: Amazon Web Services Updatealarmmodel
      description: Updates an alarm model. Any alarms that were created based on the previous version are deleted and then created again as new data arrives.
      operationId: amazonWebServicesUpdateAlarmModel
      tags:
      - Alarm Models
  /alarm-models/{alarmModelName}/versions:
    GET:
      summary: Amazon Web Services Listalarmmodelversions
      description: Lists all the versions of an alarm model. The operation returns only the metadata associated with each alarm model version.
      operationId: amazonWebServicesListAlarmModelVersions
      tags:
      - Alarm Models
