openapi: 3.2.0
info:
  title: Amazon Web Services connect Hours of Operations API
  description: Amazon Connect is a cloud-based contact center solution that you use to set up and manage a customer contact center and provide reliable customer engagement at any scale.
tags:
- name: Hours of Operations
paths:
  /hours-of-operations/{InstanceId}:
    PUT:
      summary: Amazon Web Services Createhoursofoperation
      description: This API is in preview release for Amazon Connect and is subject to change. Creates hours of operation.
      operationId: amazonWebServicesCreateHoursOfOperation
      tags:
      - Hours of Operations
  /hours-of-operations/{InstanceId}/{HoursOfOperationId}:
    POST:
      summary: Amazon Web Services Updatehoursofoperation
      description: This API is in preview release for Amazon Connect and is subject to change. Updates the hours of operation.
      operationId: amazonWebServicesUpdateHoursOfOperation
      tags:
      - Hours of Operations
