openapi: 3.2.0
info:
  title: Amazon Web Services arc-zonal-shift Managedresources API
  description: Welcome to the Zonal Shift API Reference Guide for Amazon Route 53 Application Recovery Controller (Route 53 ARC).
tags:
- name: Managedresources
paths:
  /managedresources/{resourceIdentifier}:
    PUT:
      summary: Amazon Web Services Updatezonalautoshiftconfiguration
      description: You can update the zonal autoshift status for a resource, to enable or disable zonal autoshift. When zonal autoshift is ENABLED, Amazon Web Services shifts away resource traffic from an Availability Zone, on your behalf, when Amazon Web Services determines that there's an issue in the Availability Zone that could potentially affect customers.
      operationId: amazonWebServicesUpdateZonalAutoshiftConfiguration
      tags:
      - Managedresources
  /managedresources:
    GET:
      summary: Amazon Web Services Listmanagedresources
      description: Lists all the resources in your Amazon Web Services account in this Amazon Web Services Region that are managed for zonal shifts in Amazon Route 53 Application Recovery Controller, and information about them. The information includes the zonal autoshift status for the resource, as well as the Amazon Resource Name (ARN), the Availability Zones that each resource is deployed in, and the resource name.
      operationId: amazonWebServicesListManagedResources
      tags:
      - Managedresources
