openapi: 3.2.0
info:
  title: Amazon Web Services ram Deletepermission API
  description: This is the Resource Access Manager API Reference.
tags:
- name: Deletepermission
paths:
  /deletepermission:
    DELETE:
      summary: Amazon Web Services Deletepermission
      description: Deletes the specified customer managed permission in the Amazon Web Services Region in which you call this operation. You can delete a customer managed permission only if it isn't attached to any resource share. The operation deletes all versions associated with the customer managed permission.
      operationId: amazonWebServicesDeletePermission
      tags:
      - Deletepermission
