openapi: 3.2.0
info:
  title: Amazon Web Services iot-roborunner Delete Worker Fleet API
  description: An example service, deployed with the Octane Service creator, which will echo the string
tags:
- name: deleteWorkerFleet
paths:
  /deleteWorkerFleet:
    POST:
      summary: Amazon Web Services Deleteworkerfleet
      description: Grants permission to delete a worker fleet
      operationId: amazonWebServicesDeleteWorkerFleet
      tags:
      - deleteWorkerFleet
