openapi: 3.2.0
info:
  title: Amazon Web Services resource-groups Groups List API
  description: Resource Groups lets you organize Amazon Web Services resources such as Amazon Elastic Compute Cloud instances, Amazon Relational Database Service databases, and Amazon Simple Storage Service buckets into groups using criteria that you define as tags.
tags:
- name: Groups List
paths:
  /groups-list:
    POST:
      summary: Amazon Web Services Listgroups
      description: 'Returns a list of existing Resource Groups in your account. Minimum permissions To run this command, you must have the following permissions: resource-groups:ListGroups'
      operationId: amazonWebServicesListGroups
      tags:
      - Groups List
