openapi: 3.2.0
info:
  title: Amazon Web Services sso Federation API
  description: AWS IAM Identity Center (successor to AWS Single Sign-On) Portal is a web service that makes it easy for you to assign user access to IAM Identity Center resources such as the AWS access portal.
tags:
- name: Federation
paths:
  /federation/credentials:
    GET:
      summary: Amazon Web Services Getrolecredentials
      description: Returns the STS short-term credentials for a given role name that is assigned to the user.
      operationId: amazonWebServicesGetRoleCredentials
      tags:
      - Federation
