openapi: 3.2.0
info:
  title: Amazon Web Services mq Broker Engine Types API
  description: Amazon MQ is a managed message broker service for Apache ActiveMQ and RabbitMQ that makes it easy to set up and operate message brokers in the cloud. A message broker allows software applications and components to communicate using various programming languages, operating systems, and formal messaging protocols.
tags:
- name: Broker Engine Types
paths:
  /v1/broker-engine-types:
    GET:
      summary: Amazon Web Services Describebrokerenginetypes
      description: Describe available engine types and versions.
      operationId: amazonWebServicesDescribeBrokerEngineTypes
      tags:
      - Broker Engine Types
