openapi: 3.2.0
info:
  title: Amazon Web Services accessanalyzer Analyzed Resource API
  description: Identity and Access Management Access Analyzer helps you to set, verify, and refine your IAM policies by providing a suite of capabilities.
tags:
- name: Analyzed Resource
paths:
  /analyzed-resource:
    POST:
      summary: Amazon Web Services Listanalyzedresources
      description: Retrieves a list of resources of the specified type that have been analyzed by the specified analyzer..
      operationId: amazonWebServicesListAnalyzedResources
      tags:
      - Analyzed Resource
