openapi: 3.2.0
info:
  title: Amazon Web Services lakeformation Delete Lake Formation…
  description: 'Lake Formation

    Defines the public endpoint for the Lake Formation service.'
tags:
- name: DeleteLakeFormationIdentityCenterConfiguration
paths:
  /DeleteLakeFormationIdentityCenterConfiguration:
    POST:
      summary: Amazon Web Services Deletelakeformationidentitycenterconfiguration
      description: Deletes an IAM Identity Center connection with Lake Formation.
      operationId: amazonWebServicesDeleteLakeFormationIdentityCenterConfiguration
      tags:
      - DeleteLakeFormationIdentityCenterConfiguration
