openapi: 3.2.0
info:
  title: Amazon Web Services billingconductor Associate Pricing…
  description: Amazon Web Services Billing Conductor is a fully managed service that you can use to customize a proforma version of your billing data each month, to accurately show or chargeback your end customers.
tags:
- name: Associate Pricing Rules
paths:
  /associate-pricing-rules:
    PUT:
      summary: Amazon Web Services Associatepricingrules
      description: Connects an array of PricingRuleArns to a defined PricingPlan. The maximum number PricingRuleArn that can be associated in one call is 30.
      operationId: amazonWebServicesAssociatePricingRules
      tags:
      - Associate Pricing Rules
