openapi: 3.2.0
info:
  title: Amazon Web Services drs Describe Recovery Instances API
  description: AWS Elastic Disaster Recovery Service.
tags:
- name: DescribeRecoveryInstances
paths:
  /DescribeRecoveryInstances:
    POST:
      summary: Amazon Web Services Describerecoveryinstances
      description: Lists all Recovery Instances or multiple Recovery Instances by ID.
      operationId: amazonWebServicesDescribeRecoveryInstances
      tags:
      - DescribeRecoveryInstances
