openapi: 3.2.0
info:
  title: Amazon Web Services inspector2 Cissession API
  description: Amazon Inspector is a vulnerability discovery service that automates continuous scanning for security vulnerabilities within your Amazon EC2, Amazon ECR, and Amazon Web Services Lambda environments.
tags:
- name: Cissession
paths:
  /cissession/health/send:
    PUT:
      summary: Amazon Web Services Sendcissessionhealth
      description: Sends a CIS session health. This API is used by the Amazon Inspector SSM plugin to communicate with the Amazon Inspector service. The Amazon Inspector SSM plugin calls this API to start a CIS scan session for the scan ID supplied by the service.
      operationId: amazonWebServicesSendCisSessionHealth
      tags:
      - Cissession
  /cissession/telemetry/send:
    PUT:
      summary: Amazon Web Services Sendcissessiontelemetry
      description: Sends a CIS session telemetry. This API is used by the Amazon Inspector SSM plugin to communicate with the Amazon Inspector service. The Amazon Inspector SSM plugin calls this API to start a CIS scan session for the scan ID supplied by the service.
      operationId: amazonWebServicesSendCisSessionTelemetry
      tags:
      - Cissession
  /cissession/start:
    PUT:
      summary: Amazon Web Services Startcissession
      description: Starts a CIS session. This API is used by the Amazon Inspector SSM plugin to communicate with the Amazon Inspector service. The Amazon Inspector SSM plugin calls this API to start a CIS scan session for the scan ID supplied by the service.
      operationId: amazonWebServicesStartCisSession
      tags:
      - Cissession
  /cissession/stop:
    PUT:
      summary: Amazon Web Services Stopcissession
      description: Stops a CIS session. This API is used by the Amazon Inspector SSM plugin to communicate with the Amazon Inspector service. The Amazon Inspector SSM plugin calls this API to start a CIS scan session for the scan ID supplied by the service.
      operationId: amazonWebServicesStopCisSession
      tags:
      - Cissession
