openapi: 3.1.0
info:
  title: Amazon Web Services accessanalyzer 2012 09 25 Matchingworkflows API
  description: <p>Identity and Access Management Access Analyzer helps you to set, verify, and refine your IAM policies by providing a suite of capabilities. Its features include findings for external and unused access, basic and custom policy checks for validating policies, and policy generation to generate fine-grained policies. To start using IAM Access Analyzer to identify external or unused access, you first need to create an analyzer.</p> <p> <b>External access analyzers</b> help identify potential risks of accessing resources by enabling you to identify any resource policies that grant access to an external principal. It does this by using logic-based reasoning to analyze resource-based policies in your Amazon Web Services environment. An external principal can be another Amazon Web Services account, a root user, an IAM user or role, a federated user, an Amazon Web Services service, or an anonymous user. You can also use IAM Access Analyzer to preview public and cross-account access to your resources before deploying permissions changes.</p> <p> <b>Unused access analyzers</b> help identify potential identity access risks by enabling you to identify unused IAM roles, unused access keys, unused console passwords, and IAM principals with unused service and action-level permissions.</p> <p>Beyond findings, IAM Access Analyzer provides basic and custom policy checks to validate IAM policies before deploying permissions changes. You can use policy generation to refine permissions by attaching a policy generated using access activity logged in CloudTrail logs. </p> <p>This guide describes the IAM Access Analyzer operations that you can call programmatically. For general information about IAM Access Analyzer, see <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html">Identity and Access Management Access Analyzer</a> in the <b>IAM User Guide</b>.</p>
tags:
- name: Matchingworkflows
paths:
  /matchingworkflows:
    GET:
      summary: Amazon Web Services Listmatchingworkflows
      description: Returns a list of all the MatchingWorkflows that have been created for an Amazon Web Services account.
      operationId: amazonWebServicesListMatchingWorkflows
      tags:
      - Matchingworkflows
  /matchingworkflows/{workflowName}:
    PUT:
      summary: Amazon Web Services Updatematchingworkflow
      description: Updates an existing MatchingWorkflow. This method is identical to CreateMatchingWorkflow, except it uses an HTTP PUT request instead of a POST request, and the MatchingWorkflow must already exist for the method to succeed.
      operationId: amazonWebServicesUpdateMatchingWorkflow
      tags:
      - Matchingworkflows
  /matchingworkflows/{workflowName}/matches:
    POST:
      summary: Amazon Web Services Getmatchid
      description: Returns the corresponding Match ID of a customer record if the record has been processed.
      operationId: amazonWebServicesGetMatchId
      tags:
      - Matchingworkflows
  /matchingworkflows/{workflowName}/jobs/{jobId}:
    GET:
      summary: Amazon Web Services Getmatchingjob
      description: Gets the status, metrics, and errors (if there are any) that are associated with a job.
      operationId: amazonWebServicesGetMatchingJob
      tags:
      - Matchingworkflows
  /matchingworkflows/{workflowName}/jobs:
    POST:
      summary: Amazon Web Services Startmatchingjob
      description: Starts the MatchingJob of a workflow. The workflow must have previously been created using the CreateMatchingWorkflow endpoint.
      operationId: amazonWebServicesStartMatchingJob
      tags:
      - Matchingworkflows
