openapi: 3.2.0
info:
  title: Amazon Web Services kinesis-video-archived-media Get HLS…
  description: ''
tags:
- name: getHLSStreamingSessionURL
paths:
  /getHLSStreamingSessionURL:
    POST:
      summary: Amazon Web Services Gethlsstreamingsessionurl
      description: Retrieves an HTTP Live Streaming (HLS) URL for the stream.
      operationId: amazonWebServicesGetHLSStreamingSessionURL
      tags:
      - getHLSStreamingSessionURL
