openapi: 3.2.0
info:
  title: Amazon Web Services connect Security Profiles Applications…
  description: Amazon Connect is a cloud-based contact center solution that you use to set up and manage a customer contact center and provide reliable customer engagement at any scale.
tags:
- name: Security Profiles Applications
paths:
  /security-profiles-applications/{InstanceId}/{SecurityProfileId}:
    GET:
      summary: Amazon Web Services Listsecurityprofileapplications
      description: Returns a list of third-party applications in a specific security profile.
      operationId: amazonWebServicesListSecurityProfileApplications
      tags:
      - Security Profiles Applications
