openapi: 3.2.0
info:
  title: Amazon Web Services drs Create Source Network API
  description: AWS Elastic Disaster Recovery Service.
tags:
- name: CreateSourceNetwork
paths:
  /CreateSourceNetwork:
    POST:
      summary: Amazon Web Services Createsourcenetwork
      description: Create a new Source Network resource for a provided VPC ID.
      operationId: amazonWebServicesCreateSourceNetwork
      tags:
      - CreateSourceNetwork
