openapi: 3.2.0
info:
  title: Amazon Web Services bedrock Foundation Models API
  description: Describes the API operations for creating and managing Amazon Bedrock models.
tags:
- name: Foundation Models
paths:
  /foundation-models/{modelIdentifier}:
    GET:
      summary: Amazon Web Services Getfoundationmodel
      description: Get details about a Amazon Bedrock foundation model.
      operationId: amazonWebServicesGetFoundationModel
      tags:
      - Foundation Models
  /foundation-models:
    GET:
      summary: Amazon Web Services Listfoundationmodels
      description: List of Amazon Bedrock foundation models that you can use. For more information, see Foundation models in the Bedrock User Guide.
      operationId: amazonWebServicesListFoundationModels
      tags:
      - Foundation Models
