openapi: 3.2.0
info:
  title: Amazon Web Services resiliencehub Describe App Version API
  description: Resilience Hub helps you proactively prepare and protect your Amazon Web Services applications from disruptions. It offers continual resiliency assessment and validation that integrates into your software development lifecycle. This enables you to uncover resiliency weaknesses, ensure recovery time objective (RTO) and recovery point objective (RPO) targets for your applications are met, and resolve issues before they are released into production.
tags:
- name: Describe App Version
paths:
  /describe-app-version:
    POST:
      summary: Amazon Web Services Describeappversion
      description: Describes the Resilience Hub application version.
      operationId: amazonWebServicesDescribeAppVersion
      tags:
      - Describe App Version
