openapi: 3.2.0
info:
  title: Amazon Web Services iot Streams API
  description: 'IoT

    IoT provides secure, bi-directional communication between Internet-connected devices (such as sensors, actuators, embedded devices, or smart appliances) and the Amazon Web Services cloud.'
tags:
- name: Streams
paths:
  /streams/{streamId}:
    PUT:
      summary: Amazon Web Services Updatestream
      description: Updates an existing stream. The stream version will be incremented by one. Requires permission to access the UpdateStream action.
      operationId: amazonWebServicesUpdateStream
      tags:
      - Streams
  /streams:
    GET:
      summary: Amazon Web Services Liststreams
      description: Lists all of the streams in your Amazon Web Services account. Requires permission to access the ListStreams action.
      operationId: amazonWebServicesListStreams
      tags:
      - Streams
