openapi: 3.2.0
info:
  title: Amazon Web Services iot Detect API
  description: 'IoT

    IoT provides secure, bi-directional communication between Internet-connected devices (such as sensors, actuators, embedded devices, or smart appliances) and the Amazon Web Services cloud.'
tags:
- name: Detect
paths:
  /detect/mitigationactions/tasks/{taskId}/cancel:
    PUT:
      summary: Amazon Web Services Canceldetectmitigationactionstask
      description: Cancels a Device Defender ML Detect mitigation action. Requires permission to access the CancelDetectMitigationActionsTask action.
      operationId: amazonWebServicesCancelDetectMitigationActionsTask
      tags:
      - Detect
  /detect/mitigationactions/tasks/{taskId}:
    PUT:
      summary: Amazon Web Services Startdetectmitigationactionstask
      description: Starts a Device Defender ML Detect mitigation actions task. Requires permission to access the StartDetectMitigationActionsTask action.
      operationId: amazonWebServicesStartDetectMitigationActionsTask
      tags:
      - Detect
  /detect/mitigationactions/executions:
    GET:
      summary: Amazon Web Services Listdetectmitigationactionsexecutions
      description: Lists mitigation actions executions for a Device Defender ML Detect Security Profile. Requires permission to access the ListDetectMitigationActionsExecutions action.
      operationId: amazonWebServicesListDetectMitigationActionsExecutions
      tags:
      - Detect
  /detect/mitigationactions/tasks:
    GET:
      summary: Amazon Web Services Listdetectmitigationactionstasks
      description: List of Device Defender ML Detect mitigation actions tasks. Requires permission to access the ListDetectMitigationActionsTasks action.
      operationId: amazonWebServicesListDetectMitigationActionsTasks
      tags:
      - Detect
