openapi: 3.2.0
info:
  title: Amazon Web Services inspector2 Ec2deepinspectionstatus API
  description: Amazon Inspector is a vulnerability discovery service that automates continuous scanning for security vulnerabilities within your Amazon EC2, Amazon ECR, and Amazon Web Services Lambda environments.
tags:
- name: Ec2deepinspectionstatus
paths:
  /ec2deepinspectionstatus/member/batch/get:
    POST:
      summary: Amazon Web Services Batchgetmemberec2deepinspectionstatus
      description: Retrieves Amazon Inspector deep inspection activation status of multiple member accounts within your organization. You must be the delegated administrator of an organization in Amazon Inspector to use this API.
      operationId: amazonWebServicesBatchGetMemberEc2DeepInspectionStatus
      tags:
      - Ec2deepinspectionstatus
  /ec2deepinspectionstatus/member/batch/update:
    POST:
      summary: Amazon Web Services Batchupdatememberec2deepinspectionstatus
      description: Activates or deactivates Amazon Inspector deep inspection for the provided member accounts in your organization. You must be the delegated administrator of an organization in Amazon Inspector to use this API.
      operationId: amazonWebServicesBatchUpdateMemberEc2DeepInspectionStatus
      tags:
      - Ec2deepinspectionstatus
