openapi: 3.2.0
info:
  title: Amazon Web Services robomaker Delete Robot Application API
  description: This section provides documentation for the AWS RoboMaker API operations.
tags:
- name: Delete Robot Application
paths:
  /deleteRobotApplication:
    POST:
      summary: Amazon Web Services Deleterobotapplication
      description: Deletes a robot application.
      operationId: amazonWebServicesDeleteRobotApplication
      tags:
      - Delete Robot Application
