openapi: 3.2.0
info:
  title: Amazon Web Services iotanalytics Pipelineactivities API
  description: IoT Analytics allows you to collect large amounts of device data, process messages, and store them.
tags:
- name: Pipelineactivities
paths:
  /pipelineactivities/run:
    POST:
      summary: Amazon Web Services Runpipelineactivity
      description: Simulates the results of running a pipeline activity on a message payload.
      operationId: amazonWebServicesRunPipelineActivity
      tags:
      - Pipelineactivities
