openapi: 3.2.0
info:
  title: Amazon Web Services databrew Recipes API
  description: Glue DataBrew is a visual, cloud-scale data-preparation service. DataBrew simplifies data preparation tasks, targeting data issues that are hard to spot and time-consuming to fix. DataBrew empowers users of all technical levels to visualize the data and perform one-click data transformations, with no coding required.
tags:
- name: Recipes
paths:
  /recipes/{name}/batchDeleteRecipeVersion:
    POST:
      summary: Amazon Web Services Batchdeleterecipeversion
      description: 'Deletes one or more versions of a recipe at a time. The entire request will be rejected if: The recipe does not exist. There is an invalid version identifier in the list of versions. The version list is empty. The version list size exceeds 50. The version list contains duplicate entries. The request will complete successfully, but with partial failures, if: A version does not exist. A version is being used by a job. You specify LATEST_WORKING, but it''s being used by a project. The version fails to be deleted. The LATEST_WORKING version will only be deleted if the recipe has no other versions. If you try to delete LATEST_WORKING while other versions exist (or if they can''t be deleted), then LATEST_WORKING will be listed as partial failure in the response.'
      operationId: amazonWebServicesBatchDeleteRecipeVersion
      tags:
      - Recipes
  /recipes:
    GET:
      summary: Amazon Web Services Listrecipes
      description: Lists all of the DataBrew recipes that are defined.
      operationId: amazonWebServicesListRecipes
      tags:
      - Recipes
  /recipes/{name}/recipeVersion/{recipeVersion}:
    DELETE:
      summary: Amazon Web Services Deleterecipeversion
      description: Deletes a single version of a DataBrew recipe.
      operationId: amazonWebServicesDeleteRecipeVersion
      tags:
      - Recipes
  /recipes/{name}:
    PUT:
      summary: Amazon Web Services Updaterecipe
      description: Modifies the definition of the LATEST_WORKING version of a DataBrew recipe.
      operationId: amazonWebServicesUpdateRecipe
      tags:
      - Recipes
  /recipes/{name}/publishRecipe:
    POST:
      summary: Amazon Web Services Publishrecipe
      description: Publishes a new version of a DataBrew recipe.
      operationId: amazonWebServicesPublishRecipe
      tags:
      - Recipes
