openapi: 3.2.0
info:
  title: Amazon Web Services imagebuilder Create Workflow API
  description: EC2 Image Builder is a fully managed Amazon Web Services service that makes it easier to automate the creation, management, and deployment of customized, secure, and up-to-date "golden" server images that are pre-installed and pre-configured with software and settings to meet specific IT standards.
tags:
- name: CreateWorkflow
paths:
  /CreateWorkflow:
    PUT:
      summary: Amazon Web Services Createworkflow
      description: Create a new workflow or a new version of an existing workflow.
      operationId: amazonWebServicesCreateWorkflow
      tags:
      - CreateWorkflow
