openapi: 3.2.0
info:
  title: Amazon Web Services connect Contact Flow Modules API
  description: Amazon Connect is a cloud-based contact center solution that you use to set up and manage a customer contact center and provide reliable customer engagement at any scale.
tags:
- name: Contact Flow Modules
paths:
  /contact-flow-modules/{InstanceId}:
    PUT:
      summary: Amazon Web Services Createcontactflowmodule
      description: Creates a flow module for the specified Amazon Connect instance.
      operationId: amazonWebServicesCreateContactFlowModule
      tags:
      - Contact Flow Modules
  /contact-flow-modules/{InstanceId}/{ContactFlowModuleId}:
    GET:
      summary: Amazon Web Services Describecontactflowmodule
      description: Describes the specified flow module.
      operationId: amazonWebServicesDescribeContactFlowModule
      tags:
      - Contact Flow Modules
  /contact-flow-modules/{InstanceId}/{ContactFlowModuleId}/content:
    POST:
      summary: Amazon Web Services Updatecontactflowmodulecontent
      description: Updates specified flow module for the specified Amazon Connect instance.
      operationId: amazonWebServicesUpdateContactFlowModuleContent
      tags:
      - Contact Flow Modules
  /contact-flow-modules/{InstanceId}/{ContactFlowModuleId}/metadata:
    POST:
      summary: Amazon Web Services Updatecontactflowmodulemetadata
      description: Updates metadata about specified flow module.
      operationId: amazonWebServicesUpdateContactFlowModuleMetadata
      tags:
      - Contact Flow Modules
