openapi: 3.2.0
info:
  title: Amazon Web Services batch Updatecomputeenvironment API
  description: 'Batch

    Using Batch, you can run batch computing workloads on the Amazon Web Services Cloud.'
tags:
- name: Updatecomputeenvironment
paths:
  /v1/updatecomputeenvironment:
    POST:
      summary: Amazon Web Services Updatecomputeenvironment
      description: Updates an Batch compute environment.
      operationId: amazonWebServicesUpdateComputeEnvironment
      tags:
      - Updatecomputeenvironment
