openapi: 3.2.0
info:
  title: Amazon Web Services simspaceweaver Describesimulation API
  description: SimSpace Weaver (SimSpace Weaver) is a service that you can use to build and run large-scale spatial simulations in the Amazon Web Services Cloud.
tags:
- name: Describesimulation
paths:
  /describesimulation:
    GET:
      summary: Amazon Web Services Describesimulation
      description: Returns the current state of the given simulation.
      operationId: amazonWebServicesDescribeSimulation
      tags:
      - Describesimulation
