openapi: 3.2.0
info:
  title: Amazon Web Services workspaces-thin-client Softwaresets API
  description: Amazon WorkSpaces Thin Client is a affordable device built to work with Amazon Web Services End User Computing (EUC) virtual desktops to provide users with a complete cloud desktop solution.
tags:
- name: Softwaresets
paths:
  /softwaresets/{id}:
    PATCH:
      summary: Amazon Web Services Updatesoftwareset
      description: Updates a software set.
      operationId: amazonWebServicesUpdateSoftwareSet
      tags:
      - Softwaresets
  /softwaresets:
    GET:
      summary: Amazon Web Services Listsoftwaresets
      description: Returns a list of software sets.
      operationId: amazonWebServicesListSoftwareSets
      tags:
      - Softwaresets
