openapi: 3.2.0
info:
  title: Amazon Web Services inspector2 Filters API
  description: Amazon Inspector is a vulnerability discovery service that automates continuous scanning for security vulnerabilities within your Amazon EC2, Amazon ECR, and Amazon Web Services Lambda environments.
tags:
- name: Filters
paths:
  /filters/create:
    POST:
      summary: Amazon Web Services Createfilter
      description: Creates a filter resource using specified filter criteria. When the filter action is set to SUPPRESS this action creates a suppression rule.
      operationId: amazonWebServicesCreateFilter
      tags:
      - Filters
  /filters/delete:
    POST:
      summary: Amazon Web Services Deletefilter
      description: Deletes a filter resource.
      operationId: amazonWebServicesDeleteFilter
      tags:
      - Filters
  /filters/list:
    POST:
      summary: Amazon Web Services Listfilters
      description: Lists the filters associated with your account.
      operationId: amazonWebServicesListFilters
      tags:
      - Filters
  /filters/update:
    POST:
      summary: Amazon Web Services Updatefilter
      description: Specifies the action that is to be applied to the findings that match the filter.
      operationId: amazonWebServicesUpdateFilter
      tags:
      - Filters
