openapi: 3.2.0
info:
  title: Amazon Web Services lookoutmetrics Describe Alert API
  description: This is the Amazon Lookout for Metrics API Reference. For an introduction to the service with tutorials for getting started, visit Amazon Lookout for Metrics Developer Guide.
tags:
- name: DescribeAlert
paths:
  /DescribeAlert:
    POST:
      summary: Amazon Web Services Describealert
      description: Describes an alert. Amazon Lookout for Metrics API actions are eventually consistent. If you do a read operation on a resource immediately after creating or modifying it, use retries to allow time for the write operation to complete.
      operationId: amazonWebServicesDescribeAlert
      tags:
      - DescribeAlert
