openapi: 3.2.0
info:
  title: Amazon Web Services amplifyuibuilder Tokens API
  description: The Amplify UI Builder API provides a programmatic interface for creating and configuring user interface (UI) component libraries and themes for use in your Amplify applications.
tags:
- name: Tokens
paths:
  /tokens/{provider}:
    POST:
      summary: Amazon Web Services Exchangecodefortoken
      description: This is for internal use. Amplify uses this action to exchange an access code for a token.
      operationId: amazonWebServicesExchangeCodeForToken
      tags:
      - Tokens
  /tokens/{provider}/refresh:
    POST:
      summary: Amazon Web Services Refreshtoken
      description: This is for internal use. Amplify uses this action to refresh a previously issued access token that might have expired.
      operationId: amazonWebServicesRefreshToken
      tags:
      - Tokens
