openapi: 3.2.0
info:
  title: Amazon Web Services wellarchitected Share Invitations API
  description: 'Well-Architected Tool

    This is the Well-Architected Tool API Reference. The WA Tool API provides programmatic access to the Well-Architected Tool in the Amazon Web Services Management Console. For information about the Well-Architected Tool, see the Well-Architected Tool User Guide.'
tags:
- name: Share Invitations
paths:
  /shareInvitations:
    GET:
      summary: Amazon Web Services Listshareinvitations
      description: List the share invitations. WorkloadNamePrefix, LensNamePrefix, ProfileNamePrefix, and TemplateNamePrefix are mutually exclusive. Use the parameter that matches your ShareResourceType.
      operationId: amazonWebServicesListShareInvitations
      tags:
      - Share Invitations
  /shareInvitations/{ShareInvitationId}:
    PATCH:
      summary: Amazon Web Services Updateshareinvitation
      description: Update a workload or custom lens share invitation. This API operation can be called independently of any resource. Previous documentation implied that a workload ARN must be specified.
      operationId: amazonWebServicesUpdateShareInvitation
      tags:
      - Share Invitations
