openapi: 3.2.0
info:
  title: Amazon Web Services elasticfilesystem Delete Tags API
  description: 'Amazon Elastic File System

    Amazon Elastic File System (Amazon EFS) provides simple, scalable file storage for use with Amazon EC2 Linux and Mac instances in the Amazon Web Services Cloud. With Amazon EFS, storage capacity is elastic, growing and shrinking automatically as you add and remove files, so that your applications have the storage they need, when they need it. For more information, see the Amazon Elastic File System API Reference and the Amazon Elastic File System User Guide.'
tags:
- name: Delete Tags
paths:
  /2015-02-01/delete-tags/{FileSystemId}:
    POST:
      summary: Amazon Web Services Deletetags
      description: DEPRECATED - DeleteTags is deprecated and not maintained. To remove tags from EFS resources, use the API action. Deletes the specified tags from a file system. If the DeleteTags request includes a tag key that doesn't exist, Amazon EFS ignores it and doesn't cause an error. For more information about tags and related restrictions, see Tag restrictions in the Billing and Cost Management User Guide. This operation requires permissions for the elasticfilesystem:DeleteTags action.
      operationId: amazonWebServicesDeleteTags
      tags:
      - Delete Tags
