openapi: 3.2.0
info:
  title: Amazon Web Services ram Listresourcetypes API
  description: This is the Resource Access Manager API Reference.
tags:
- name: Listresourcetypes
paths:
  /listresourcetypes:
    POST:
      summary: Amazon Web Services Listresourcetypes
      description: Lists the resource types that can be shared by RAM.
      operationId: amazonWebServicesListResourceTypes
      tags:
      - Listresourcetypes
