openapi: 3.2.0
info:
  title: Amazon Web Services oam Get Sink Policy API
  description: Use Amazon CloudWatch Observability Access Manager to create and manage links between source accounts and monitoring accounts by using CloudWatch cross-account observability.
tags:
- name: GetSinkPolicy
paths:
  /GetSinkPolicy:
    POST:
      summary: Amazon Web Services Getsinkpolicy
      description: Returns the current sink policy attached to this sink. The sink policy specifies what accounts can attach to this sink as source accounts, and what types of data they can share.
      operationId: amazonWebServicesGetSinkPolicy
      tags:
      - GetSinkPolicy
