openapi: 3.2.0
info:
  title: Amazon Web Services cloudfront Distributions API
  description: 'Amazon CloudFront

    This is the Amazon CloudFront API Reference. This guide is for developers who need detailed information about CloudFront API actions, data types, and errors. For detailed information about CloudFront features, see the Amazon CloudFront Developer Guide.'
tags:
- name: Distributions
paths:
  /2020-05-31/distributions/{DistributionId}/monitoring-subscription/:
    GET:
      summary: Amazon Web Services Getmonitoringsubscription
      description: Gets information about whether additional CloudWatch metrics are enabled for the specified CloudFront distribution.
      operationId: amazonWebServicesGetMonitoringSubscription
      tags:
      - Distributions
