openapi: 3.2.0
info:
  title: Amazon Web Services lakeformation Get Data Lake Settings API
  description: 'Lake Formation

    Defines the public endpoint for the Lake Formation service.'
tags:
- name: GetDataLakeSettings
paths:
  /GetDataLakeSettings:
    POST:
      summary: Amazon Web Services Getdatalakesettings
      description: Retrieves the list of the data lake administrators of a Lake Formation-managed data lake.
      operationId: amazonWebServicesGetDataLakeSettings
      tags:
      - GetDataLakeSettings
