openapi: 3.2.0
info:
  title: Amazon Web Services backup Copy Jobs API
  description: 'Backup

    Backup is a unified backup service designed to protect Amazon Web Services services and their associated data. Backup simplifies the creation, migration, restoration, and deletion of backups, while also providing reporting and auditing.'
tags:
- name: Copy Jobs
paths:
  /copy-jobs/{copyJobId}:
    GET:
      summary: Amazon Web Services Describecopyjob
      description: Returns metadata associated with creating a copy of a resource.
      operationId: amazonWebServicesDescribeCopyJob
      tags:
      - Copy Jobs
  /copy-jobs/:
    GET:
      summary: Amazon Web Services Listcopyjobs
      description: Returns metadata about your copy jobs.
      operationId: amazonWebServicesListCopyJobs
      tags:
      - Copy Jobs
  /copy-jobs:
    PUT:
      summary: Amazon Web Services Startcopyjob
      description: Starts a job to create a one-time copy of the specified resource. Does not support continuous backups.
      operationId: amazonWebServicesStartCopyJob
      tags:
      - Copy Jobs
