openapi: 3.2.0
info:
  title: Amazon Web Services controltower Delete Landingzone API
  description: These interfaces allow you to apply the Amazon Web Services library of pre-defined controls to your organizational units, programmatically.
tags:
- name: Delete Landingzone
paths:
  /delete-landingzone:
    POST:
      summary: Amazon Web Services Deletelandingzone
      description: Decommissions a landing zone. This API call starts an asynchronous operation that deletes Amazon Web Services Control Tower resources deployed in accounts managed by Amazon Web Services Control Tower.
      operationId: amazonWebServicesDeleteLandingZone
      tags:
      - Delete Landingzone
