openapi: 3.2.0
info:
  title: Amazon Web Services batch Deleteschedulingpolicy API
  description: 'Batch

    Using Batch, you can run batch computing workloads on the Amazon Web Services Cloud.'
tags:
- name: Deleteschedulingpolicy
paths:
  /v1/deleteschedulingpolicy:
    POST:
      summary: Amazon Web Services Deleteschedulingpolicy
      description: Deletes the specified scheduling policy. You can't delete a scheduling policy that's used in any job queues.
      operationId: amazonWebServicesDeleteSchedulingPolicy
      tags:
      - Deleteschedulingpolicy
