openapi: 3.2.0
info:
  title: Amazon Web Services macie2 Resource Profiles API
  description: Amazon Macie is a fully managed data security and data privacy service that uses machine learning and pattern matching to help you discover and protect your sensitive data in AWS.
tags:
- name: Resource Profiles
paths:
  /resource-profiles:
    PATCH:
      summary: Amazon Web Services Updateresourceprofile
      description: Updates the sensitivity score for an S3 bucket.
      operationId: amazonWebServicesUpdateResourceProfile
      tags:
      - Resource Profiles
  /resource-profiles/artifacts:
    GET:
      summary: Amazon Web Services Listresourceprofileartifacts
      description: Retrieves information about objects that were selected from an S3 bucket for automated sensitive data discovery.
      operationId: amazonWebServicesListResourceProfileArtifacts
      tags:
      - Resource Profiles
  /resource-profiles/detections:
    PATCH:
      summary: Amazon Web Services Updateresourceprofiledetections
      description: Updates the sensitivity scoring settings for an S3 bucket.
      operationId: amazonWebServicesUpdateResourceProfileDetections
      tags:
      - Resource Profiles
