openapi: 3.2.0
info:
  title: Amazon Web Services iotwireless Wireless Devices API
  description: AWS IoT Wireless provides bi-directional communication between internet-connected wireless devices and the AWS Cloud.
tags:
- name: Wireless Devices
paths:
  /wireless-devices/{Id}/thing:
    DELETE:
      summary: Amazon Web Services Disassociatewirelessdevicefromthing
      description: Disassociates a wireless device from its currently associated thing.
      operationId: amazonWebServicesDisassociateWirelessDeviceFromThing
      tags:
      - Wireless Devices
  /wireless-devices:
    GET:
      summary: Amazon Web Services Listwirelessdevices
      description: Lists the wireless devices registered to your AWS account.
      operationId: amazonWebServicesListWirelessDevices
      tags:
      - Wireless Devices
  /wireless-devices/{Id}/data:
    POST:
      summary: Amazon Web Services Senddatatowirelessdevice
      description: Sends a decrypted application data frame to a device.
      operationId: amazonWebServicesSendDataToWirelessDevice
      tags:
      - Wireless Devices
  /wireless-devices/{Id}:
    PATCH:
      summary: Amazon Web Services Updatewirelessdevice
      description: Updates properties of a wireless device.
      operationId: amazonWebServicesUpdateWirelessDevice
      tags:
      - Wireless Devices
  /wireless-devices/{Identifier}/deregister:
    PATCH:
      summary: Amazon Web Services Deregisterwirelessdevice
      description: Deregister a wireless device from AWS IoT Wireless.
      operationId: amazonWebServicesDeregisterWirelessDevice
      tags:
      - Wireless Devices
  /wireless-devices/{Identifier}:
    GET:
      summary: Amazon Web Services Getwirelessdevice
      description: Gets information about a wireless device.
      operationId: amazonWebServicesGetWirelessDevice
      tags:
      - Wireless Devices
  /wireless-devices/{Id}/statistics:
    GET:
      summary: Amazon Web Services Getwirelessdevicestatistics
      description: Gets operating information about a wireless device.
      operationId: amazonWebServicesGetWirelessDeviceStatistics
      tags:
      - Wireless Devices
  /wireless-devices/{Id}/test:
    POST:
      summary: Amazon Web Services Testwirelessdevice
      description: Simulates a provisioned device by sending an uplink data payload of Hello.
      operationId: amazonWebServicesTestWirelessDevice
      tags:
      - Wireless Devices
