openapi: 3.2.0
info:
  title: Amazon Web Services connect Default Vocabulary API
  description: Amazon Connect is a cloud-based contact center solution that you use to set up and manage a customer contact center and provide reliable customer engagement at any scale.
tags:
- name: Default Vocabulary
paths:
  /default-vocabulary/{InstanceId}/{LanguageCode}:
    PUT:
      summary: Amazon Web Services Associatedefaultvocabulary
      description: Associates an existing vocabulary as the default. Contact Lens for Amazon Connect uses the vocabulary in post-call and real-time analysis sessions for the given language.
      operationId: amazonWebServicesAssociateDefaultVocabulary
      tags:
      - Default Vocabulary
