openapi: 3.2.0
info:
  title: Amazon Web Services mediatailor Configure Logs API
  description: Use the AWS Elemental MediaTailor SDKs and CLI to configure scalable ad insertion and linear channels.
tags:
- name: Configure Logs
paths:
  /configureLogs/channel:
    PUT:
      summary: Amazon Web Services Configurelogsforchannel
      description: Configures Amazon CloudWatch log settings for a channel.
      operationId: amazonWebServicesConfigureLogsForChannel
      tags:
      - Configure Logs
  /configureLogs/playbackConfiguration:
    PUT:
      summary: Amazon Web Services Configurelogsforplaybackconfiguration
      description: Amazon CloudWatch log settings for a playback configuration.
      operationId: amazonWebServicesConfigureLogsForPlaybackConfiguration
      tags:
      - Configure Logs
