openapi: 3.2.0
info:
  title: Amazon Web Services kafkaconnect Worker Configurations API
  description: ''
tags:
- name: Worker Configurations
paths:
  /v1/worker-configurations:
    GET:
      summary: Amazon Web Services Listworkerconfigurations
      description: Returns a list of all of the worker configurations in this account and Region.
      operationId: amazonWebServicesListWorkerConfigurations
      tags:
      - Worker Configurations
  /v1/worker-configurations/{workerConfigurationArn}:
    GET:
      summary: Amazon Web Services Describeworkerconfiguration
      description: Returns information about a worker configuration.
      operationId: amazonWebServicesDescribeWorkerConfiguration
      tags:
      - Worker Configurations
