openapi: 3.2.0
info:
  title: Amazon Web Services iotwireless Log Levels API
  description: AWS IoT Wireless provides bi-directional communication between internet-connected wireless devices and the AWS Cloud.
tags:
- name: Log Levels
paths:
  /log-levels:
    POST:
      summary: Amazon Web Services Updateloglevelsbyresourcetypes
      description: Set default log level, or log levels by resource types. This can be for wireless device log options or wireless gateways log options and is used to control the log messages that'll be displayed in CloudWatch.
      operationId: amazonWebServicesUpdateLogLevelsByResourceTypes
      tags:
      - Log Levels
  /log-levels/{ResourceIdentifier}:
    DELETE:
      summary: Amazon Web Services Resetresourceloglevel
      description: Removes the log-level override, if any, for a specific resource-ID and resource-type. It can be used for a wireless device or a wireless gateway.
      operationId: amazonWebServicesResetResourceLogLevel
      tags:
      - Log Levels
