openapi: 3.2.0
info:
  title: Amazon Web Services securityhub Configuration Policy API
  description: Security Hub provides you with a comprehensive view of your security state in Amazon Web Services and helps you assess your Amazon Web Services environment against security industry standards and best practices.
tags:
- name: Configuration - Policy
paths:
  /configurationPolicy/create:
    POST:
      summary: Amazon Web Services Createconfigurationpolicy
      description: Creates a configuration policy with the defined configuration. Only the Security Hub delegated administrator can invoke this operation from the home Region.
      operationId: amazonWebServicesCreateConfigurationPolicy
      tags:
      - Configuration - Policy
  /configurationPolicy/{Identifier}:
    PATCH:
      summary: Amazon Web Services Updateconfigurationpolicy
      description: Updates a configuration policy. Only the Security Hub delegated administrator can invoke this operation from the home Region.
      operationId: amazonWebServicesUpdateConfigurationPolicy
      tags:
      - Configuration - Policy
  /configurationPolicy/get/{Identifier}:
    GET:
      summary: Amazon Web Services Getconfigurationpolicy
      description: Provides information about a configuration policy. Only the Security Hub delegated administrator can invoke this operation from the home Region.
      operationId: amazonWebServicesGetConfigurationPolicy
      tags:
      - Configuration - Policy
  /configurationPolicy/list:
    GET:
      summary: Amazon Web Services Listconfigurationpolicies
      description: Lists the configuration policies that the Security Hub delegated administrator has created for your organization. Only the delegated administrator can invoke this operation from the home Region.
      operationId: amazonWebServicesListConfigurationPolicies
      tags:
      - Configuration - Policy
