openapi: 3.2.0
info:
  title: Amazon Web Services billingconductor Create Custom Line…
  description: Amazon Web Services Billing Conductor is a fully managed service that you can use to customize a proforma version of your billing data each month, to accurately show or chargeback your end customers.
tags:
- name: Create Custom Line Item
paths:
  /create-custom-line-item:
    POST:
      summary: Amazon Web Services Createcustomlineitem
      description: Creates a custom line item that can be used to create a one-time fixed charge that can be applied to a single billing group for the current or previous billing period. The one-time fixed charge is either a fee or discount.
      operationId: amazonWebServicesCreateCustomLineItem
      tags:
      - Create Custom Line Item
