openapi: 3.2.0
info:
  title: Amazon Web Services imagebuilder List Image Pipeline Images…
  description: EC2 Image Builder is a fully managed Amazon Web Services service that makes it easier to automate the creation, management, and deployment of customized, secure, and up-to-date "golden" server images that are pre-installed and pre-configured with software and settings to meet specific IT standards.
tags:
- name: ListImagePipelineImages
paths:
  /ListImagePipelineImages:
    POST:
      summary: Amazon Web Services Listimagepipelineimages
      description: Returns a list of images created by the specified pipeline.
      operationId: amazonWebServicesListImagePipelineImages
      tags:
      - ListImagePipelineImages
