openapi: 3.2.0
info:
  title: Amazon Web Services iot Cancel Certificate Transfer API
  description: 'IoT

    IoT provides secure, bi-directional communication between Internet-connected devices (such as sensors, actuators, embedded devices, or smart appliances) and the Amazon Web Services cloud.'
tags:
- name: Cancel Certificate Transfer
paths:
  /cancel-certificate-transfer/{certificateId}:
    PATCH:
      summary: Amazon Web Services Cancelcertificatetransfer
      description: Cancels a pending transfer for the specified certificate. Note Only the transfer source account can use this operation to cancel a transfer. (Transfer destinations can use RejectCertificateTransfer instead.) After transfer, IoT returns the certificate to the source account in the INACTIVE state. After the destination account has accepted the transfer, the transfer cannot be cancelled. After a certificate transfer is cancelled, the status of the certificate changes from PENDING_TRANSFER to INACTIVE. Requires permission to access the CancelCertificateTransfer action.
      operationId: amazonWebServicesCancelCertificateTransfer
      tags:
      - Cancel Certificate Transfer
