openapi: 3.2.0
info:
  title: Amazon Web Services cleanrooms Memberships API
  description: Welcome to the Clean Rooms API Reference.
tags:
- name: Memberships
paths:
  /memberships/{membershipIdentifier}/analysistemplates:
    GET:
      summary: Amazon Web Services Listanalysistemplates
      description: Lists analysis templates that the caller owns.
      operationId: amazonWebServicesListAnalysisTemplates
      tags:
      - Memberships
  /memberships/{membershipIdentifier}/configuredaudiencemodelassociations:
    GET:
      summary: Amazon Web Services Listconfiguredaudiencemodelassociations
      description: Lists information about requested configured audience model associations.
      operationId: amazonWebServicesListConfiguredAudienceModelAssociations
      tags:
      - Memberships
  /memberships/{membershipIdentifier}/configuredTableAssociations:
    GET:
      summary: Amazon Web Services Listconfiguredtableassociations
      description: Lists configured table associations for a membership.
      operationId: amazonWebServicesListConfiguredTableAssociations
      tags:
      - Memberships
  /memberships:
    GET:
      summary: Amazon Web Services Listmemberships
      description: Lists all memberships resources within the caller's account.
      operationId: amazonWebServicesListMemberships
      tags:
      - Memberships
  /memberships/{membershipIdentifier}/privacybudgettemplates:
    GET:
      summary: Amazon Web Services Listprivacybudgettemplates
      description: Returns detailed information about the privacy budget templates in a specified membership.
      operationId: amazonWebServicesListPrivacyBudgetTemplates
      tags:
      - Memberships
  /memberships/{membershipIdentifier}/analysistemplates/{analysisTemplateIdentifier}:
    PATCH:
      summary: Amazon Web Services Updateanalysistemplate
      description: Updates the analysis template metadata.
      operationId: amazonWebServicesUpdateAnalysisTemplate
      tags:
      - Memberships
  /memberships/{membershipIdentifier}/configuredaudiencemodelassociations/{configuredAudienceModelAssociationIdentifier}:
    PATCH:
      summary: Amazon Web Services Updateconfiguredaudiencemodelassociation
      description: Provides the details necessary to update a configured audience model association.
      operationId: amazonWebServicesUpdateConfiguredAudienceModelAssociation
      tags:
      - Memberships
  /memberships/{membershipIdentifier}/configuredTableAssociations/{configuredTableAssociationIdentifier}:
    PATCH:
      summary: Amazon Web Services Updateconfiguredtableassociation
      description: Updates a configured table association.
      operationId: amazonWebServicesUpdateConfiguredTableAssociation
      tags:
      - Memberships
  /memberships/{membershipIdentifier}:
    PATCH:
      summary: Amazon Web Services Updatemembership
      description: Updates a membership.
      operationId: amazonWebServicesUpdateMembership
      tags:
      - Memberships
  /memberships/{membershipIdentifier}/privacybudgettemplates/{privacyBudgetTemplateIdentifier}:
    PATCH:
      summary: Amazon Web Services Updateprivacybudgettemplate
      description: Updates the privacy budget template for the specified membership.
      operationId: amazonWebServicesUpdatePrivacyBudgetTemplate
      tags:
      - Memberships
  /memberships/{membershipIdentifier}/protectedQueries/{protectedQueryIdentifier}:
    PATCH:
      summary: Amazon Web Services Updateprotectedquery
      description: Updates the processing of a currently running query.
      operationId: amazonWebServicesUpdateProtectedQuery
      tags:
      - Memberships
  /memberships/{membershipIdentifier}/privacybudgets:
    GET:
      summary: Amazon Web Services Listprivacybudgets
      description: Returns detailed information about the privacy budgets in a specified membership.
      operationId: amazonWebServicesListPrivacyBudgets
      tags:
      - Memberships
  /memberships/{membershipIdentifier}/protectedQueries:
    POST:
      summary: Amazon Web Services Startprotectedquery
      description: Creates a protected query that is started by Clean Rooms.
      operationId: amazonWebServicesStartProtectedQuery
      tags:
      - Memberships
  /memberships/{membershipIdentifier}/previewprivacyimpact:
    POST:
      summary: Amazon Web Services Previewprivacyimpact
      description: An estimate of the number of aggregation functions that the member who can query can run given epsilon and noise parameters.
      operationId: amazonWebServicesPreviewPrivacyImpact
      tags:
      - Memberships
