openapi: 3.2.0
info:
  title: Amazon Web Services xray Create Group API
  description: Amazon Web Services X-Ray provides APIs for managing debug traces and retrieving service maps and other data created by processing those traces.
tags:
- name: CreateGroup
paths:
  /CreateGroup:
    POST:
      summary: Amazon Web Services Creategroup
      description: Creates a group resource with a name and a filter expression.
      operationId: amazonWebServicesCreateGroup
      tags:
      - CreateGroup
