openapi: 3.2.0
info:
  title: Amazon Web Services entityresolution Schemas API
  description: Welcome to the Entity Resolution API Reference.
tags:
- name: Schemas
paths:
  /schemas:
    GET:
      summary: Amazon Web Services Listschemamappings
      description: Returns a list of all the SchemaMappings that have been created for an Amazon Web Services account.
      operationId: amazonWebServicesListSchemaMappings
      tags:
      - Schemas
  /schemas/{schemaName}:
    PUT:
      summary: Amazon Web Services Updateschemamapping
      description: Updates a schema mapping. A schema is immutable if it is being used by a workflow. Therefore, you can't update a schema mapping if it's associated with a workflow.
      operationId: amazonWebServicesUpdateSchemaMapping
      tags:
      - Schemas
