openapi: 3.2.0
info:
  title: Amazon Web Services imagebuilder Create Lifecycle Policy API
  description: EC2 Image Builder is a fully managed Amazon Web Services service that makes it easier to automate the creation, management, and deployment of customized, secure, and up-to-date "golden" server images that are pre-installed and pre-configured with software and settings to meet specific IT standards.
tags:
- name: CreateLifecyclePolicy
paths:
  /CreateLifecyclePolicy:
    PUT:
      summary: Amazon Web Services Createlifecyclepolicy
      description: Create a lifecycle policy resource.
      operationId: amazonWebServicesCreateLifecyclePolicy
      tags:
      - CreateLifecyclePolicy
