openapi: 3.2.0
info:
  title: Amazon Web Services iottwinmaker Metadata Transfer Jobs API
  description: IoT TwinMaker is a service with which you can build operational digital twins of physical systems. IoT TwinMaker overlays measurements and analysis from real-world sensors, cameras, and enterprise applications so you can create data visualizations to monitor your physical factory, building, or industrial plant. You can use this real-world data to monitor operations and diagnose and repair errors.
tags:
- name: Metadata Transfer Jobs
paths:
  /metadata-transfer-jobs/{metadataTransferJobId}/cancel:
    PUT:
      summary: Amazon Web Services Cancelmetadatatransferjob
      description: Cancels the metadata transfer job.
      operationId: amazonWebServicesCancelMetadataTransferJob
      tags:
      - Metadata Transfer Jobs
  /metadata-transfer-jobs:
    POST:
      summary: Amazon Web Services Createmetadatatransferjob
      description: Creates a new metadata transfer job.
      operationId: amazonWebServicesCreateMetadataTransferJob
      tags:
      - Metadata Transfer Jobs
  /metadata-transfer-jobs/{metadataTransferJobId}:
    GET:
      summary: Amazon Web Services Getmetadatatransferjob
      description: Gets a nmetadata transfer job.
      operationId: amazonWebServicesGetMetadataTransferJob
      tags:
      - Metadata Transfer Jobs
