openapi: 3.2.0
info:
  title: Amazon Web Services connect-contact-lens Realtime Contact…
  description: Contact Lens for Amazon Connect enables you to analyze conversations between customer and agents, by using speech transcription, natural language processing, and intelligent search capabilities.
tags:
- name: Realtime Contact Analysis
paths:
  /realtime-contact-analysis/analysis-segments:
    POST:
      summary: Amazon Web Services Listrealtimecontactanalysissegments
      description: Provides a list of analysis segments for a real-time analysis session.
      operationId: amazonWebServicesListRealtimeContactAnalysisSegments
      tags:
      - Realtime Contact Analysis
