openapi: 3.2.0
info:
  title: Amazon Web Services imagebuilder Delete Image Recipe API
  description: EC2 Image Builder is a fully managed Amazon Web Services service that makes it easier to automate the creation, management, and deployment of customized, secure, and up-to-date "golden" server images that are pre-installed and pre-configured with software and settings to meet specific IT standards.
tags:
- name: DeleteImageRecipe
paths:
  /DeleteImageRecipe:
    DELETE:
      summary: Amazon Web Services Deleteimagerecipe
      description: Deletes an image recipe.
      operationId: amazonWebServicesDeleteImageRecipe
      tags:
      - DeleteImageRecipe
