openapi: 3.2.0
info:
  title: Amazon Web Services lookoutmetrics Describe Anomaly…
  description: This is the Amazon Lookout for Metrics API Reference. For an introduction to the service with tutorials for getting started, visit Amazon Lookout for Metrics Developer Guide.
tags:
- name: DescribeAnomalyDetectionExecutions
paths:
  /DescribeAnomalyDetectionExecutions:
    POST:
      summary: Amazon Web Services Describeanomalydetectionexecutions
      description: Returns information about the status of the specified anomaly detection jobs.
      operationId: amazonWebServicesDescribeAnomalyDetectionExecutions
      tags:
      - DescribeAnomalyDetectionExecutions
