openapi: 3.2.0
info:
  title: Amazon Web Services billingconductor List Resources…
  description: Amazon Web Services Billing Conductor is a fully managed service that you can use to customize a proforma version of your billing data each month, to accurately show or chargeback your end customers.
tags:
- name: List Resources Associated to Custom Line Item
paths:
  /list-resources-associated-to-custom-line-item:
    POST:
      summary: Amazon Web Services Listresourcesassociatedtocustomlineitem
      description: List the resources that are associated to a custom line item.
      operationId: amazonWebServicesListResourcesAssociatedToCustomLineItem
      tags:
      - List Resources Associated to Custom Line Item
