openapi: 3.2.0
info:
  title: Amazon Web Services resiliencehub Put Draft App Version…
  description: Resilience Hub helps you proactively prepare and protect your Amazon Web Services applications from disruptions. It offers continual resiliency assessment and validation that integrates into your software development lifecycle. This enables you to uncover resiliency weaknesses, ensure recovery time objective (RTO) and recovery point objective (RPO) targets for your applications are met, and resolve issues before they are released into production.
tags:
- name: Put Draft App Version Template
paths:
  /put-draft-app-version-template:
    POST:
      summary: Amazon Web Services Putdraftappversiontemplate
      description: Adds or updates the app template for an Resilience Hub application draft version.
      operationId: amazonWebServicesPutDraftAppVersionTemplate
      tags:
      - Put Draft App Version Template
