openapi: 3.2.0
info:
  title: Amazon Web Services lakeformation Update Lake Formation…
  description: 'Lake Formation

    Defines the public endpoint for the Lake Formation service.'
tags:
- name: UpdateLakeFormationIdentityCenterConfiguration
paths:
  /UpdateLakeFormationIdentityCenterConfiguration:
    POST:
      summary: Amazon Web Services Updatelakeformationidentitycenterconfiguration
      description: Updates the IAM Identity Center connection parameters.
      operationId: amazonWebServicesUpdateLakeFormationIdentityCenterConfiguration
      tags:
      - UpdateLakeFormationIdentityCenterConfiguration
