openapi: 3.2.0
info:
  title: Amazon Web Services worklink Describe Device Policy…
  description: Amazon WorkLink is a cloud-based service that provides secure access to internal websites and web apps from iOS and Android phones.
tags:
- name: describeDevicePolicyConfiguration
paths:
  /describeDevicePolicyConfiguration:
    POST:
      summary: Amazon Web Services Describedevicepolicyconfiguration
      description: Describes the device policy configuration for the specified fleet.
      operationId: amazonWebServicesDescribeDevicePolicyConfiguration
      tags:
      - describeDevicePolicyConfiguration
