openapi: 3.2.0
info:
  title: Amazon Web Services xray Get Sampling Rules API
  description: Amazon Web Services X-Ray provides APIs for managing debug traces and retrieving service maps and other data created by processing those traces.
tags:
- name: GetSamplingRules
paths:
  /GetSamplingRules:
    POST:
      summary: Amazon Web Services Getsamplingrules
      description: Retrieves all sampling rules.
      operationId: amazonWebServicesGetSamplingRules
      tags:
      - GetSamplingRules
