openapi: 3.2.0
info:
  title: Amazon Web Services resiliencehub Describe App Version…
  description: Resilience Hub helps you proactively prepare and protect your Amazon Web Services applications from disruptions. It offers continual resiliency assessment and validation that integrates into your software development lifecycle. This enables you to uncover resiliency weaknesses, ensure recovery time objective (RTO) and recovery point objective (RPO) targets for your applications are met, and resolve issues before they are released into production.
tags:
- name: Describe App Version Resource
paths:
  /describe-app-version-resource:
    POST:
      summary: Amazon Web Services Describeappversionresource
      description: 'Describes a resource of the Resilience Hub application. This API accepts only one of the following parameters to descibe the resource: resourceName logicalResourceId physicalResourceId (Along with physicalResourceId, you can also provide awsAccountId, and awsRegion)'
      operationId: amazonWebServicesDescribeAppVersionResource
      tags:
      - Describe App Version Resource
