openapi: 3.2.0
info:
  title: Amazon Web Services devops-guru List Log Anomalies API
  description: Amazon DevOps Guru is a fully managed service that helps you identify anomalous behavior in business critical operational applications.
tags:
- name: List Log Anomalies
paths:
  /list-log-anomalies:
    POST:
      summary: Amazon Web Services Listanomalousloggroups
      description: Returns the list of log groups that contain log anomalies.
      operationId: amazonWebServicesListAnomalousLogGroups
      tags:
      - List Log Anomalies
