openapi: 3.2.0
info:
  title: Amazon Web Services mgn List Import Errors API
  description: The Application Migration Service service.
tags:
- name: ListImportErrors
paths:
  /ListImportErrors:
    POST:
      summary: Amazon Web Services Listimporterrors
      description: List import errors.
      operationId: amazonWebServicesListImportErrors
      tags:
      - ListImportErrors
