openapi: 3.2.0
info:
  title: Amazon Web Services batch Describejobdefinitions API
  description: 'Batch

    Using Batch, you can run batch computing workloads on the Amazon Web Services Cloud.'
tags:
- name: Describejobdefinitions
paths:
  /v1/describejobdefinitions:
    POST:
      summary: Amazon Web Services Describejobdefinitions
      description: Describes a list of job definitions. You can specify a status (such as ACTIVE) to only return job definitions that match that status.
      operationId: amazonWebServicesDescribeJobDefinitions
      tags:
      - Describejobdefinitions
