openapi: 3.2.0
info:
  title: Amazon Web Services ivs Update Channel API
  description: 'Introduction


    The Amazon Interactive Video Service (IVS) API is REST compatible, using a standard HTTP API and an Amazon Web Services EventBridge event stream for responses.'
tags:
- name: UpdateChannel
paths:
  /UpdateChannel:
    POST:
      summary: Amazon Web Services Updatechannel
      description: Updates a channel's configuration. Live channels cannot be updated. You must stop the ongoing stream, update the channel, and restart the stream for the changes to take effect.
      operationId: amazonWebServicesUpdateChannel
      tags:
      - UpdateChannel
