openapi: 3.1.0
info:
  title: amp
  description: >-
    <p>Amazon Managed Service for Prometheus is a serverless,
    Prometheus-compatible monitoring service for container metrics that makes it
    easier to securely monitor container environments at scale. With Amazon
    Managed Service for Prometheus, you can use the same open-source Prometheus
    data model and query language that you use today to monitor the performance
    of your containerized workloads, and also enjoy improved scalability,
    availability, and security without having to manage the underlying
    infrastructure.</p> <p>For more information about Amazon Managed Service for
    Prometheus, see the <a
    href="https://docs.aws.amazon.com/prometheus/latest/userguide/what-is-Amazon-Managed-Service-Prometheus.html">Amazon
    Managed Service for Prometheus</a> User Guide.</p> <p>Amazon Managed Service
    for Prometheus includes two APIs.</p> <ul> <li> <p>Use the Amazon Web
    Services API described in this guide to manage Amazon Managed Service for
    Prometheus resources, such as workspaces, rule groups, and alert
    managers.</p> </li> <li> <p>Use the <a
    href="https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-APIReference.html#AMP-APIReference-Prometheus-Compatible-Apis">Prometheus-compatible
    API</a> to work within your Prometheus workspace.</p> </li> </ul>
paths:
  /workspaces/{workspaceId}/alertmanager/definition:
    PUT:
      summary: Putalertmanagerdefinition
      description: >-
        Updates an existing alert manager definition in a workspace. If the
        workspace does not already have an alert manager definition, don't use
        this operation to create it. Instead, use CreateAlertManagerDefinition.
      operationId: amazonWebServicesPutAlertManagerDefinition
  /workspaces/{workspaceId}/logging:
    PUT:
      summary: Updateloggingconfiguration
      description: >-
        Updates the log group ARN or the workspace ID of the current logging
        configuration.
      operationId: amazonWebServicesUpdateLoggingConfiguration
  /workspaces/{workspaceId}/rulegroupsnamespaces:
    GET:
      summary: Listrulegroupsnamespaces
      description: Returns a list of rule groups namespaces in a workspace.
      operationId: amazonWebServicesListRuleGroupsNamespaces
  /scrapers:
    GET:
      summary: Listscrapers
      description: >-
        The ListScrapers operation lists all of the scrapers in your account.
        This includes scrapers being created or deleted. You can optionally
        filter the returned list.
      operationId: amazonWebServicesListScrapers
  /workspaces:
    GET:
      summary: Listworkspaces
      description: >-
        Lists all of the Amazon Managed Service for Prometheus workspaces in
        your account. This includes workspaces being created or deleted. 
      operationId: amazonWebServicesListWorkspaces
  /workspaces/{workspaceId}/rulegroupsnamespaces/{name}:
    PUT:
      summary: Putrulegroupsnamespace
      description: >-
        Updates an existing rule groups namespace within a workspace. A rule
        groups namespace is associated with exactly one rules file. A workspace
        can have multiple rule groups namespaces. Use this operation only to
        update existing rule groups namespaces. To create a new rule groups
        namespace, use CreateRuleGroupsNamespace. You can't use this operation
        to add tags to an existing rule groups namespace. Instead, use
        TagResource.
      operationId: amazonWebServicesPutRuleGroupsNamespace
  /scrapers/{scraperId}:
    GET:
      summary: Describescraper
      description: >-
        The DescribeScraper operation displays information about an existing
        scraper.
      operationId: amazonWebServicesDescribeScraper
  /workspaces/{workspaceId}:
    GET:
      summary: Describeworkspace
      description: 'Returns information about an existing workspace. '
      operationId: amazonWebServicesDescribeWorkspace
  /scraperconfiguration:
    GET:
      summary: Getdefaultscraperconfiguration
      description: >-
        The GetDefaultScraperConfiguration operation returns the default scraper
        configuration used when Amazon EKS creates a scraper for you.
      operationId: amazonWebServicesGetDefaultScraperConfiguration
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: >-
        Removes the specified tags from an Amazon Managed Service for Prometheus
        resource. The only resources that can be tagged are workspaces and rule
        groups namespaces. 
      operationId: amazonWebServicesUntagResource
  /workspaces/{workspaceId}/alias:
    POST:
      summary: Updateworkspacealias
      description: 'Updates the alias of an existing workspace. '
      operationId: amazonWebServicesUpdateWorkspaceAlias
tags: []
