openapi: 3.1.0
info:
  title: amplifyuibuilder
  description: >-
    <p>The Amplify UI Builder API provides a programmatic interface for creating
    and configuring user interface (UI) component libraries and themes for use
    in your Amplify applications. You can then connect these UI components to an
    application's backend Amazon Web Services resources.</p> <p>You can also use
    the Amplify Studio visual designer to create UI components and model data
    for an app. For more information, see <a
    href="https://docs.amplify.aws/console/adminui/intro">Introduction</a> in
    the <i>Amplify Docs</i>.</p> <p>The Amplify Framework is a comprehensive set
    of SDKs, libraries, tools, and documentation for client app development. For
    more information, see the <a href="https://docs.amplify.aws/">Amplify
    Framework</a>. For more information about deploying an Amplify application
    to Amazon Web Services, see the <a
    href="https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html">Amplify
    User Guide</a>.</p>
paths:
  /app/{appId}/environment/{environmentName}/components:
    GET:
      summary: Listcomponents
      description: >-
        Retrieves a list of components for a specified Amplify app and backend
        environment.
      operationId: amazonWebServicesListComponents
  /app/{appId}/environment/{environmentName}/forms:
    GET:
      summary: Listforms
      description: >-
        Retrieves a list of forms for a specified Amplify app and backend
        environment.
      operationId: amazonWebServicesListForms
  /app/{appId}/environment/{environmentName}/themes:
    GET:
      summary: Listthemes
      description: >-
        Retrieves a list of themes for a specified Amplify app and backend
        environment.
      operationId: amazonWebServicesListThemes
  /app/{appId}/environment/{environmentName}/components/{id}:
    PATCH:
      summary: Updatecomponent
      description: Updates an existing component.
      operationId: amazonWebServicesUpdateComponent
  /app/{appId}/environment/{environmentName}/forms/{id}:
    PATCH:
      summary: Updateform
      description: Updates an existing form.
      operationId: amazonWebServicesUpdateForm
  /app/{appId}/environment/{environmentName}/themes/{id}:
    PATCH:
      summary: Updatetheme
      description: Updates an existing theme.
      operationId: amazonWebServicesUpdateTheme
  /tokens/{provider}:
    POST:
      summary: Exchangecodefortoken
      description: ' This is for internal use.  Amplify uses this action to exchange an access code for a token.'
      operationId: amazonWebServicesExchangeCodeForToken
  /export/app/{appId}/environment/{environmentName}/components:
    GET:
      summary: Exportcomponents
      description: >-
        Exports component configurations to code that is ready to integrate into
        an Amplify app.
      operationId: amazonWebServicesExportComponents
  /export/app/{appId}/environment/{environmentName}/forms:
    GET:
      summary: Exportforms
      description: >-
        Exports form configurations to code that is ready to integrate into an
        Amplify app.
      operationId: amazonWebServicesExportForms
  /export/app/{appId}/environment/{environmentName}/themes:
    GET:
      summary: Exportthemes
      description: >-
        Exports theme configurations to code that is ready to integrate into an
        Amplify app.
      operationId: amazonWebServicesExportThemes
  /app/{appId}/environment/{environmentName}/codegen-jobs/{id}:
    GET:
      summary: Getcodegenjob
      description: Returns an existing code generation job.
      operationId: amazonWebServicesGetCodegenJob
  /app/{appId}/environment/{environmentName}/metadata:
    GET:
      summary: Getmetadata
      description: Returns existing metadata for an Amplify app.
      operationId: amazonWebServicesGetMetadata
  /app/{appId}/environment/{environmentName}/codegen-jobs:
    POST:
      summary: Startcodegenjob
      description: >-
        Starts a code generation job for a specified Amplify app and backend
        environment.
      operationId: amazonWebServicesStartCodegenJob
  /app/{appId}/environment/{environmentName}/metadata/features/{featureName}:
    PUT:
      summary: Putmetadataflag
      description: Stores the metadata information about a feature on a form.
      operationId: amazonWebServicesPutMetadataFlag
  /tokens/{provider}/refresh:
    POST:
      summary: Refreshtoken
      description: ' This is for internal use.  Amplify uses this action to refresh a previously issued access token that might have expired.'
      operationId: amazonWebServicesRefreshToken
tags: []
