openapi: 3.1.0
info:
  title: amplifybackend
  description: <p>AWS Amplify Admin API</p>
paths:
  /backend/{appId}/environments/{backendEnvironmentName}/clone:
    POST:
      summary: Clonebackend
      description: This operation clones an existing backend.
      operationId: amazonWebServicesCloneBackend
  /backend:
    POST:
      summary: Createbackend
      description: >-
        This operation creates a backend for an Amplify app. Backends are
        automatically created at the time of app creation.
      operationId: amazonWebServicesCreateBackend
  /backend/{appId}/api:
    POST:
      summary: Createbackendapi
      description: Creates a new backend API resource.
      operationId: amazonWebServicesCreateBackendAPI
  /backend/{appId}/auth:
    POST:
      summary: Createbackendauth
      description: Creates a new backend authentication resource.
      operationId: amazonWebServicesCreateBackendAuth
  /backend/{appId}/config:
    POST:
      summary: Createbackendconfig
      description: Creates a config object for a backend.
      operationId: amazonWebServicesCreateBackendConfig
  /backend/{appId}/storage:
    POST:
      summary: Createbackendstorage
      description: Creates a backend storage resource.
      operationId: amazonWebServicesCreateBackendStorage
  /backend/{appId}/challenge:
    POST:
      summary: Createtoken
      description: >-
        Generates a one-time challenge code to authenticate a user into your
        Amplify Admin UI.
      operationId: amazonWebServicesCreateToken
  /backend/{appId}/environments/{backendEnvironmentName}/remove:
    POST:
      summary: Deletebackend
      description: Removes an existing environment from your Amplify project.
      operationId: amazonWebServicesDeleteBackend
  /backend/{appId}/api/{backendEnvironmentName}/remove:
    POST:
      summary: Deletebackendapi
      description: Deletes an existing backend API resource.
      operationId: amazonWebServicesDeleteBackendAPI
  /backend/{appId}/auth/{backendEnvironmentName}/remove:
    POST:
      summary: Deletebackendauth
      description: Deletes an existing backend authentication resource.
      operationId: amazonWebServicesDeleteBackendAuth
  /backend/{appId}/storage/{backendEnvironmentName}/remove:
    POST:
      summary: Deletebackendstorage
      description: Removes the specified backend storage resource.
      operationId: amazonWebServicesDeleteBackendStorage
  /backend/{appId}/challenge/{sessionId}/remove:
    POST:
      summary: Deletetoken
      description: Deletes the challenge token based on the given appId and sessionId.
      operationId: amazonWebServicesDeleteToken
  /backend/{appId}/api/{backendEnvironmentName}/generateModels:
    POST:
      summary: Generatebackendapimodels
      description: Generates a model schema for an existing backend API resource.
      operationId: amazonWebServicesGenerateBackendAPIModels
  /backend/{appId}/details:
    POST:
      summary: Getbackend
      description: Provides project-level details for your Amplify UI project.
      operationId: amazonWebServicesGetBackend
  /backend/{appId}/api/{backendEnvironmentName}/details:
    POST:
      summary: Getbackendapi
      description: Gets the details for a backend API.
      operationId: amazonWebServicesGetBackendAPI
  /backend/{appId}/api/{backendEnvironmentName}/getModels:
    POST:
      summary: Getbackendapimodels
      description: Gets a model introspection schema for an existing backend API resource.
      operationId: amazonWebServicesGetBackendAPIModels
  /backend/{appId}/auth/{backendEnvironmentName}/details:
    POST:
      summary: Getbackendauth
      description: Gets a backend auth details.
      operationId: amazonWebServicesGetBackendAuth
  /backend/{appId}/job/{backendEnvironmentName}/{jobId}:
    POST:
      summary: Updatebackendjob
      description: Updates a specific job.
      operationId: amazonWebServicesUpdateBackendJob
  /backend/{appId}/storage/{backendEnvironmentName}/details:
    POST:
      summary: Getbackendstorage
      description: Gets details for a backend storage resource.
      operationId: amazonWebServicesGetBackendStorage
  /backend/{appId}/challenge/{sessionId}:
    GET:
      summary: Gettoken
      description: Gets the challenge token based on the given appId and sessionId.
      operationId: amazonWebServicesGetToken
  /backend/{appId}/auth/{backendEnvironmentName}/import:
    POST:
      summary: Importbackendauth
      description: Imports an existing backend authentication resource.
      operationId: amazonWebServicesImportBackendAuth
  /backend/{appId}/storage/{backendEnvironmentName}/import:
    POST:
      summary: Importbackendstorage
      description: Imports an existing backend storage resource.
      operationId: amazonWebServicesImportBackendStorage
  /backend/{appId}/job/{backendEnvironmentName}:
    POST:
      summary: Listbackendjobs
      description: Lists the jobs for the backend of an Amplify app.
      operationId: amazonWebServicesListBackendJobs
  /s3Buckets:
    POST:
      summary: Lists3buckets
      description: The list of S3 buckets in your account.
      operationId: amazonWebServicesListS3Buckets
  /backend/{appId}/remove:
    POST:
      summary: Removeallbackends
      description: Removes all backend environments from your Amplify project.
      operationId: amazonWebServicesRemoveAllBackends
  /backend/{appId}/config/remove:
    POST:
      summary: Removebackendconfig
      description: Removes the AWS resources required to access the Amplify Admin UI.
      operationId: amazonWebServicesRemoveBackendConfig
  /backend/{appId}/api/{backendEnvironmentName}:
    POST:
      summary: Updatebackendapi
      description: Updates an existing backend API resource.
      operationId: amazonWebServicesUpdateBackendAPI
  /backend/{appId}/auth/{backendEnvironmentName}:
    POST:
      summary: Updatebackendauth
      description: Updates an existing backend authentication resource.
      operationId: amazonWebServicesUpdateBackendAuth
  /backend/{appId}/config/update:
    POST:
      summary: Updatebackendconfig
      description: Updates the AWS resources required to access the Amplify Admin UI.
      operationId: amazonWebServicesUpdateBackendConfig
  /backend/{appId}/storage/{backendEnvironmentName}:
    POST:
      summary: Updatebackendstorage
      description: Updates an existing backend storage resource.
      operationId: amazonWebServicesUpdateBackendStorage
tags: []
