openapi: 3.1.0
info:
  title: amplify
  description: >-
    <p>Amplify enables developers to develop and deploy cloud-powered mobile and
    web apps. Amplify Hosting provides a continuous delivery and hosting service
    for web applications. For more information, see the <a
    href="https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html">Amplify
    Hosting User Guide</a>. The Amplify Framework is a comprehensive set of
    SDKs, libraries, tools, and documentation for client app development. For
    more information, see the <a href="https://docs.amplify.aws/">Amplify
    Framework.</a> </p>
paths:
  /apps:
    GET:
      summary: Listapps
      description: 'Returns a list of the existing Amplify apps. '
      operationId: amazonWebServicesListApps
  /apps/{appId}/backendenvironments:
    GET:
      summary: Listbackendenvironments
      description: 'Lists the backend environments for an Amplify app. '
      operationId: amazonWebServicesListBackendEnvironments
  /apps/{appId}/branches:
    GET:
      summary: Listbranches
      description: ' Lists the branches of an Amplify app. '
      operationId: amazonWebServicesListBranches
  /apps/{appId}/branches/{branchName}/deployments:
    POST:
      summary: Createdeployment
      description: >-
        Creates a deployment for a manually deployed Amplify app. Manually
        deployed apps are not connected to a repository.  The maximum duration
        between the CreateDeployment call and the StartDeployment call cannot
        exceed 8 hours. If the duration exceeds 8 hours, the StartDeployment
        call and the associated Job will fail.
      operationId: amazonWebServicesCreateDeployment
  /apps/{appId}/domains:
    GET:
      summary: Listdomainassociations
      description: ' Returns the domain associations for an Amplify app. '
      operationId: amazonWebServicesListDomainAssociations
  /apps/{appId}/webhooks:
    GET:
      summary: Listwebhooks
      description: 'Returns a list of webhooks for an Amplify app. '
      operationId: amazonWebServicesListWebhooks
  /apps/{appId}:
    POST:
      summary: Updateapp
      description: 'Updates an existing Amplify app. '
      operationId: amazonWebServicesUpdateApp
  /apps/{appId}/backendenvironments/{environmentName}:
    GET:
      summary: Getbackendenvironment
      description: 'Returns a backend environment for an Amplify app. '
      operationId: amazonWebServicesGetBackendEnvironment
  /apps/{appId}/branches/{branchName}:
    POST:
      summary: Updatebranch
      description: ' Updates a branch for an Amplify app. '
      operationId: amazonWebServicesUpdateBranch
  /apps/{appId}/domains/{domainName}:
    POST:
      summary: Updatedomainassociation
      description: ' Creates a new domain association for an Amplify app.'
      operationId: amazonWebServicesUpdateDomainAssociation
  /apps/{appId}/branches/{branchName}/jobs/{jobId}:
    GET:
      summary: Getjob
      description: ' Returns a job for a branch of an Amplify app. '
      operationId: amazonWebServicesGetJob
  /webhooks/{webhookId}:
    POST:
      summary: Updatewebhook
      description: 'Updates a webhook. '
      operationId: amazonWebServicesUpdateWebhook
  /apps/{appId}/accesslogs:
    POST:
      summary: Generateaccesslogs
      description: >-
        Returns the website access logs for a specific time range using a
        presigned URL. 
      operationId: amazonWebServicesGenerateAccessLogs
  /artifacts/{artifactId}:
    GET:
      summary: Getartifacturl
      description: 'Returns the artifact info that corresponds to an artifact id. '
      operationId: amazonWebServicesGetArtifactUrl
  /apps/{appId}/branches/{branchName}/jobs/{jobId}/artifacts:
    GET:
      summary: Listartifacts
      description: 'Returns a list of artifacts for a specified app, branch, and job. '
      operationId: amazonWebServicesListArtifacts
  /apps/{appId}/branches/{branchName}/jobs:
    POST:
      summary: Startjob
      description: ' Starts a new job for a branch of an Amplify app. '
      operationId: amazonWebServicesStartJob
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Untags a resource with a specified Amazon Resource Name (ARN).
      operationId: amazonWebServicesUntagResource
  /apps/{appId}/branches/{branchName}/deployments/start:
    POST:
      summary: Startdeployment
      description: >-
        Starts a deployment for a manually deployed app. Manually deployed apps
        are not connected to a repository.  The maximum duration between the
        CreateDeployment call and the StartDeployment call cannot exceed 8
        hours. If the duration exceeds 8 hours, the StartDeployment call and the
        associated Job will fail.
      operationId: amazonWebServicesStartDeployment
  /apps/{appId}/branches/{branchName}/jobs/{jobId}/stop:
    DELETE:
      summary: Stopjob
      description: ' Stops a job that is in progress for a branch of an Amplify app. '
      operationId: amazonWebServicesStopJob
tags: []
