openapi: 3.1.0
info:
  title: apigateway
  description: >-
    <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps
    developers deliver robust, secure, and scalable mobile and web application
    back ends. API Gateway allows developers to securely connect mobile and web
    applications to APIs that run on Lambda, Amazon EC2, or other publicly
    addressable web services that are hosted outside of AWS.</p>
paths:
  /apikeys:
    GET:
      summary: Getapikeys
      description: Gets information about the current ApiKeys resource.
      operationId: amazonWebServicesGetApiKeys
  /restapis/{restapi_id}/authorizers:
    GET:
      summary: Getauthorizers
      description: Describe an existing Authorizers resource.
      operationId: amazonWebServicesGetAuthorizers
  /domainnames/{domain_name}/basepathmappings:
    GET:
      summary: Getbasepathmappings
      description: Represents a collection of BasePathMapping resources.
      operationId: amazonWebServicesGetBasePathMappings
  /restapis/{restapi_id}/deployments:
    GET:
      summary: Getdeployments
      description: Gets information about a Deployments collection.
      operationId: amazonWebServicesGetDeployments
  /restapis/{restapi_id}/documentation/parts:
    PUT:
      summary: Importdocumentationparts
      description: Imports documentation parts
      operationId: amazonWebServicesImportDocumentationParts
  /restapis/{restapi_id}/documentation/versions:
    GET:
      summary: Getdocumentationversions
      description: Gets documentation versions.
      operationId: amazonWebServicesGetDocumentationVersions
  /domainnames:
    GET:
      summary: Getdomainnames
      description: Represents a collection of DomainName resources.
      operationId: amazonWebServicesGetDomainNames
  /restapis/{restapi_id}/models:
    GET:
      summary: Getmodels
      description: Describes existing Models defined for a RestApi resource.
      operationId: amazonWebServicesGetModels
  /restapis/{restapi_id}/requestvalidators:
    GET:
      summary: Getrequestvalidators
      description: Gets the RequestValidators collection of a given RestApi.
      operationId: amazonWebServicesGetRequestValidators
  /restapis/{restapi_id}/resources/{parent_id}:
    POST:
      summary: Createresource
      description: Creates a Resource resource.
      operationId: amazonWebServicesCreateResource
  /restapis:
    GET:
      summary: Getrestapis
      description: Lists the RestApis resources for your collection.
      operationId: amazonWebServicesGetRestApis
  /restapis/{restapi_id}/stages:
    GET:
      summary: Getstages
      description: Gets information about one or more Stage resources.
      operationId: amazonWebServicesGetStages
  /usageplans:
    GET:
      summary: Getusageplans
      description: Gets all the usage plans of the caller's account.
      operationId: amazonWebServicesGetUsagePlans
  /usageplans/{usageplanId}/keys:
    GET:
      summary: Getusageplankeys
      description: >-
        Gets all the usage plan keys representing the API keys added to a
        specified usage plan.
      operationId: amazonWebServicesGetUsagePlanKeys
  /vpclinks:
    GET:
      summary: Getvpclinks
      description: >-
        Gets the VpcLinks collection under the caller's account in a selected
        region.
      operationId: amazonWebServicesGetVpcLinks
  /apikeys/{api_Key}:
    PATCH:
      summary: Updateapikey
      description: Changes information about an ApiKey resource.
      operationId: amazonWebServicesUpdateApiKey
  /restapis/{restapi_id}/authorizers/{authorizer_id}:
    PATCH:
      summary: Updateauthorizer
      description: Updates an existing Authorizer resource.
      operationId: amazonWebServicesUpdateAuthorizer
  /domainnames/{domain_name}/basepathmappings/{base_path}:
    PATCH:
      summary: Updatebasepathmapping
      description: Changes information about the BasePathMapping resource.
      operationId: amazonWebServicesUpdateBasePathMapping
  /clientcertificates/{clientcertificate_id}:
    PATCH:
      summary: Updateclientcertificate
      description: Changes information about an ClientCertificate resource.
      operationId: amazonWebServicesUpdateClientCertificate
  /restapis/{restapi_id}/deployments/{deployment_id}:
    PATCH:
      summary: Updatedeployment
      description: Changes information about a Deployment resource.
      operationId: amazonWebServicesUpdateDeployment
  /restapis/{restapi_id}/documentation/parts/{part_id}:
    PATCH:
      summary: Updatedocumentationpart
      description: Updates a documentation part.
      operationId: amazonWebServicesUpdateDocumentationPart
  /restapis/{restapi_id}/documentation/versions/{doc_version}:
    PATCH:
      summary: Updatedocumentationversion
      description: Updates a documentation version.
      operationId: amazonWebServicesUpdateDocumentationVersion
  /domainnames/{domain_name}:
    PATCH:
      summary: Updatedomainname
      description: Changes information about the DomainName resource.
      operationId: amazonWebServicesUpdateDomainName
  /restapis/{restapi_id}/gatewayresponses/{response_type}:
    PATCH:
      summary: Updategatewayresponse
      description: >-
        Updates a GatewayResponse of a specified response type on the given
        RestApi.
      operationId: amazonWebServicesUpdateGatewayResponse
  /restapis/{restapi_id}/resources/{resource_id}/methods/{http_method}/integration:
    PATCH:
      summary: Updateintegration
      description: Represents an update integration.
      operationId: amazonWebServicesUpdateIntegration
  /restapis/{restapi_id}/resources/{resource_id}/methods/{http_method}/integration/responses/{status_code}:
    PATCH:
      summary: Updateintegrationresponse
      description: Represents an update integration response.
      operationId: amazonWebServicesUpdateIntegrationResponse
  /restapis/{restapi_id}/resources/{resource_id}/methods/{http_method}:
    PATCH:
      summary: Updatemethod
      description: Updates an existing Method resource.
      operationId: amazonWebServicesUpdateMethod
  /restapis/{restapi_id}/resources/{resource_id}/methods/{http_method}/responses/{status_code}:
    PATCH:
      summary: Updatemethodresponse
      description: Updates an existing MethodResponse resource.
      operationId: amazonWebServicesUpdateMethodResponse
  /restapis/{restapi_id}/models/{model_name}:
    PATCH:
      summary: Updatemodel
      description: Changes information about a model.
      operationId: amazonWebServicesUpdateModel
  /restapis/{restapi_id}/requestvalidators/{requestvalidator_id}:
    PATCH:
      summary: Updaterequestvalidator
      description: Updates a RequestValidator of a given RestApi.
      operationId: amazonWebServicesUpdateRequestValidator
  /restapis/{restapi_id}/resources/{resource_id}:
    PATCH:
      summary: Updateresource
      description: Changes information about a Resource resource.
      operationId: amazonWebServicesUpdateResource
  /restapis/{restapi_id}:
    PATCH:
      summary: Updaterestapi
      description: Changes information about the specified API.
      operationId: amazonWebServicesUpdateRestApi
  /restapis/{restapi_id}/stages/{stage_name}:
    PATCH:
      summary: Updatestage
      description: Changes information about a Stage resource.
      operationId: amazonWebServicesUpdateStage
  /usageplans/{usageplanId}:
    PATCH:
      summary: Updateusageplan
      description: Updates a usage plan of a given plan Id.
      operationId: amazonWebServicesUpdateUsagePlan
  /usageplans/{usageplanId}/keys/{keyId}:
    GET:
      summary: Getusageplankey
      description: Gets a usage plan key of a given key identifier.
      operationId: amazonWebServicesGetUsagePlanKey
  /vpclinks/{vpclink_id}:
    PATCH:
      summary: Updatevpclink
      description: Updates an existing VpcLink of a specified identifier.
      operationId: amazonWebServicesUpdateVpcLink
  /restapis/{restapi_id}/stages/{stage_name}/cache/authorizers:
    DELETE:
      summary: Flushstageauthorizerscache
      description: Flushes all authorizer cache entries on a stage.
      operationId: amazonWebServicesFlushStageAuthorizersCache
  /restapis/{restapi_id}/stages/{stage_name}/cache/data:
    DELETE:
      summary: Flushstagecache
      description: Flushes a stage's cache.
      operationId: amazonWebServicesFlushStageCache
  /clientcertificates:
    GET:
      summary: Getclientcertificates
      description: Gets a collection of ClientCertificate resources.
      operationId: amazonWebServicesGetClientCertificates
  /account:
    PATCH:
      summary: Updateaccount
      description: Changes information about the current Account resource.
      operationId: amazonWebServicesUpdateAccount
  /restapis/{restapi_id}/stages/{stage_name}/exports/{export_type}:
    GET:
      summary: Getexport
      description: Exports a deployed version of a RestApi in a specified format.
      operationId: amazonWebServicesGetExport
  /restapis/{restapi_id}/gatewayresponses:
    GET:
      summary: Getgatewayresponses
      description: >-
        Gets the GatewayResponses collection on the given RestApi. If an API
        developer has not added any definitions for gateway responses, the
        result will be the API Gateway-generated default GatewayResponses
        collection for the supported response types.
      operationId: amazonWebServicesGetGatewayResponses
  /restapis/{restapi_id}/models/{model_name}/default_template:
    GET:
      summary: Getmodeltemplate
      description: >-
        Generates a sample mapping template that can be used to transform a
        payload into the structure of a model.
      operationId: amazonWebServicesGetModelTemplate
  /restapis/{restapi_id}/resources:
    GET:
      summary: Getresources
      description: Lists information about a collection of Resource resources.
      operationId: amazonWebServicesGetResources
  /restapis/{restapi_id}/stages/{stage_name}/sdks/{sdk_type}:
    GET:
      summary: Getsdk
      description: Generates a client SDK for a RestApi and Stage.
      operationId: amazonWebServicesGetSdk
  /sdktypes/{sdktype_id}:
    GET:
      summary: Getsdktype
      description: Gets an SDK type.
      operationId: amazonWebServicesGetSdkType
  /sdktypes:
    GET:
      summary: Getsdktypes
      description: Gets SDK types
      operationId: amazonWebServicesGetSdkTypes
  /tags/{resource_arn}:
    DELETE:
      summary: Untagresource
      description: Removes a tag from a given resource.
      operationId: amazonWebServicesUntagResource
  /usageplans/{usageplanId}/usage:
    GET:
      summary: Getusage
      description: Gets the usage data of a usage plan in a specified time interval.
      operationId: amazonWebServicesGetUsage
  /apikeys?mode=import:
    POST:
      summary: Importapikeys
      description: Import API keys from an external source, such as a CSV-formatted file.
      operationId: amazonWebServicesImportApiKeys
  /restapis?mode=import:
    POST:
      summary: Importrestapi
      description: >-
        A feature of the API Gateway control service for creating a new API from
        an external API definition file.
      operationId: amazonWebServicesImportRestApi
  /usageplans/{usageplanId}/keys/{keyId}/usage:
    PATCH:
      summary: Updateusage
      description: >-
        Grants a temporary extension to the remaining quota of a usage plan
        associated with a specified API key.
      operationId: amazonWebServicesUpdateUsage
tags: []
