openapi: 3.1.0
info:
  title: apigatewayv2
  description: <p>Amazon API Gateway V2</p>
paths:
  /v2/apis:
    PUT:
      summary: Importapi
      description: Imports an API.
      operationId: amazonWebServicesImportApi
  /v2/domainnames/{domainName}/apimappings:
    GET:
      summary: Getapimappings
      description: Gets API mappings.
      operationId: amazonWebServicesGetApiMappings
  /v2/apis/{apiId}/authorizers:
    GET:
      summary: Getauthorizers
      description: Gets the Authorizers for an API.
      operationId: amazonWebServicesGetAuthorizers
  /v2/apis/{apiId}/deployments:
    GET:
      summary: Getdeployments
      description: Gets the Deployments for an API.
      operationId: amazonWebServicesGetDeployments
  /v2/domainnames:
    GET:
      summary: Getdomainnames
      description: Gets the domain names for an AWS account.
      operationId: amazonWebServicesGetDomainNames
  /v2/apis/{apiId}/integrations:
    GET:
      summary: Getintegrations
      description: Gets the Integrations for an API.
      operationId: amazonWebServicesGetIntegrations
  /v2/apis/{apiId}/integrations/{integrationId}/integrationresponses:
    GET:
      summary: Getintegrationresponses
      description: Gets the IntegrationResponses for an Integration.
      operationId: amazonWebServicesGetIntegrationResponses
  /v2/apis/{apiId}/models:
    GET:
      summary: Getmodels
      description: Gets the Models for an API.
      operationId: amazonWebServicesGetModels
  /v2/apis/{apiId}/routes:
    GET:
      summary: Getroutes
      description: Gets the Routes for an API.
      operationId: amazonWebServicesGetRoutes
  /v2/apis/{apiId}/routes/{routeId}/routeresponses:
    GET:
      summary: Getrouteresponses
      description: Gets the RouteResponses for a Route.
      operationId: amazonWebServicesGetRouteResponses
  /v2/apis/{apiId}/stages:
    GET:
      summary: Getstages
      description: Gets the Stages for an API.
      operationId: amazonWebServicesGetStages
  /v2/vpclinks:
    GET:
      summary: Getvpclinks
      description: Gets a collection of VPC links.
      operationId: amazonWebServicesGetVpcLinks
  /v2/apis/{apiId}/stages/{stageName}/accesslogsettings:
    DELETE:
      summary: Deleteaccesslogsettings
      description: >-
        Deletes the AccessLogSettings for a Stage. To disable access logging for
        a Stage, delete its AccessLogSettings.
      operationId: amazonWebServicesDeleteAccessLogSettings
  /v2/apis/{apiId}:
    PATCH:
      summary: Updateapi
      description: Updates an Api resource.
      operationId: amazonWebServicesUpdateApi
  /v2/domainnames/{domainName}/apimappings/{apiMappingId}:
    PATCH:
      summary: Updateapimapping
      description: The API mapping.
      operationId: amazonWebServicesUpdateApiMapping
  /v2/apis/{apiId}/authorizers/{authorizerId}:
    PATCH:
      summary: Updateauthorizer
      description: Updates an Authorizer.
      operationId: amazonWebServicesUpdateAuthorizer
  /v2/apis/{apiId}/cors:
    DELETE:
      summary: Deletecorsconfiguration
      description: Deletes a CORS configuration.
      operationId: amazonWebServicesDeleteCorsConfiguration
  /v2/apis/{apiId}/deployments/{deploymentId}:
    PATCH:
      summary: Updatedeployment
      description: Updates a Deployment.
      operationId: amazonWebServicesUpdateDeployment
  /v2/domainnames/{domainName}:
    PATCH:
      summary: Updatedomainname
      description: Updates a domain name.
      operationId: amazonWebServicesUpdateDomainName
  /v2/apis/{apiId}/integrations/{integrationId}:
    PATCH:
      summary: Updateintegration
      description: Updates an Integration.
      operationId: amazonWebServicesUpdateIntegration
  /v2/apis/{apiId}/integrations/{integrationId}/integrationresponses/{integrationResponseId}:
    PATCH:
      summary: Updateintegrationresponse
      description: Updates an IntegrationResponses.
      operationId: amazonWebServicesUpdateIntegrationResponse
  /v2/apis/{apiId}/models/{modelId}:
    PATCH:
      summary: Updatemodel
      description: Updates a Model.
      operationId: amazonWebServicesUpdateModel
  /v2/apis/{apiId}/routes/{routeId}:
    PATCH:
      summary: Updateroute
      description: Updates a Route.
      operationId: amazonWebServicesUpdateRoute
  /v2/apis/{apiId}/routes/{routeId}/requestparameters/{requestParameterKey}:
    DELETE:
      summary: Deleterouterequestparameter
      description: Deletes a route request parameter.
      operationId: amazonWebServicesDeleteRouteRequestParameter
  /v2/apis/{apiId}/routes/{routeId}/routeresponses/{routeResponseId}:
    PATCH:
      summary: Updaterouteresponse
      description: Updates a RouteResponse.
      operationId: amazonWebServicesUpdateRouteResponse
  /v2/apis/{apiId}/stages/{stageName}/routesettings/{routeKey}:
    DELETE:
      summary: Deleteroutesettings
      description: Deletes the RouteSettings for a stage.
      operationId: amazonWebServicesDeleteRouteSettings
  /v2/apis/{apiId}/stages/{stageName}:
    PATCH:
      summary: Updatestage
      description: Updates a Stage.
      operationId: amazonWebServicesUpdateStage
  /v2/vpclinks/{vpcLinkId}:
    PATCH:
      summary: Updatevpclink
      description: Updates a VPC link.
      operationId: amazonWebServicesUpdateVpcLink
  /v2/apis/{apiId}/exports/{specification}:
    GET:
      summary: Exportapi
      description: >-
        Exports a definition of an API in a particular output format and
        specification.
      operationId: amazonWebServicesExportApi
  /v2/apis/{apiId}/stages/{stageName}/cache/authorizers:
    DELETE:
      summary: Resetauthorizerscache
      description: >-
        Resets all authorizer cache entries for the specified stage. Supported
        only for HTTP API Lambda authorizers.
      operationId: amazonWebServicesResetAuthorizersCache
  /v2/apis/{apiId}/models/{modelId}/template:
    GET:
      summary: Getmodeltemplate
      description: Gets a model template.
      operationId: amazonWebServicesGetModelTemplate
  /v2/tags/{resource-arn}:
    DELETE:
      summary: Untagresource
      description: Deletes a Tag.
      operationId: amazonWebServicesUntagResource
tags: []
