openapi: 3.1.0
info:
  title: appconfig
  description: >-
    <p>Use AppConfig, a capability of Amazon Web Services Systems Manager, to
    create, manage, and quickly deploy application configurations. AppConfig
    supports controlled deployments to applications of any size and includes
    built-in validation checks and monitoring. You can use AppConfig with
    applications hosted on Amazon EC2 instances, Lambda, containers, mobile
    applications, or IoT devices.</p> <p>To prevent errors when deploying
    application configurations, especially for production systems where a simple
    typo could cause an unexpected outage, AppConfig includes validators. A
    validator provides a syntactic or semantic check to ensure that the
    configuration you want to deploy works as intended. To validate your
    application configuration data, you provide a schema or an Amazon Web
    Services Lambda function that runs against the configuration. The
    configuration deployment or update can only proceed when the configuration
    data is valid.</p> <p>During a configuration deployment, AppConfig monitors
    the application to ensure that the deployment is successful. If the system
    encounters an error, AppConfig rolls back the change to minimize impact for
    your application users. You can configure a deployment strategy for each
    application or environment that includes deployment criteria, including
    velocity, bake time, and alarms to monitor. Similar to error monitoring, if
    a deployment triggers an alarm, AppConfig automatically rolls back to the
    previous version. </p> <p>AppConfig supports multiple use cases. Here are
    some examples:</p> <ul> <li> <p> <b>Feature flags</b>: Use AppConfig to turn
    on new features that require a timely deployment, such as a product launch
    or announcement. </p> </li> <li> <p> <b>Application tuning</b>: Use
    AppConfig to carefully introduce changes to your application that can only
    be tested with production traffic.</p> </li> <li> <p> <b>Allow list</b>: Use
    AppConfig to allow premium subscribers to access paid content. </p> </li>
    <li> <p> <b>Operational issues</b>: Use AppConfig to reduce stress on your
    application when a dependency or other external factor impacts the
    system.</p> </li> </ul> <p>This reference is intended to be used with the <a
    href="http://docs.aws.amazon.com/appconfig/latest/userguide/what-is-appconfig.html">AppConfig
    User Guide</a>.</p>
paths:
  /applications:
    GET:
      summary: Listapplications
      description: Lists all applications in your Amazon Web Services account.
      operationId: amazonWebServicesListApplications
  /applications/{ApplicationId}/configurationprofiles:
    GET:
      summary: Listconfigurationprofiles
      description: Lists the configuration profiles for an application.
      operationId: amazonWebServicesListConfigurationProfiles
  /deploymentstrategies:
    GET:
      summary: Listdeploymentstrategies
      description: Lists deployment strategies.
      operationId: amazonWebServicesListDeploymentStrategies
  /applications/{ApplicationId}/environments:
    GET:
      summary: Listenvironments
      description: Lists the environments for an application.
      operationId: amazonWebServicesListEnvironments
  /extensions:
    GET:
      summary: Listextensions
      description: >-
        Lists all custom and Amazon Web Services authored AppConfig extensions
        in the account. For more information about extensions, see Working with
        AppConfig extensions in the AppConfig User Guide.
      operationId: amazonWebServicesListExtensions
  /extensionassociations:
    GET:
      summary: Listextensionassociations
      description: >-
        Lists all AppConfig extension associations in the account. For more
        information about extensions and associations, see Working with
        AppConfig extensions in the AppConfig User Guide.
      operationId: amazonWebServicesListExtensionAssociations
  /applications/{ApplicationId}/configurationprofiles/{ConfigurationProfileId}/hostedconfigurationversions:
    GET:
      summary: Listhostedconfigurationversions
      description: >-
        Lists configurations stored in the AppConfig hosted configuration store
        by version.
      operationId: amazonWebServicesListHostedConfigurationVersions
  /applications/{ApplicationId}:
    PATCH:
      summary: Updateapplication
      description: Updates an application.
      operationId: amazonWebServicesUpdateApplication
  /applications/{ApplicationId}/configurationprofiles/{ConfigurationProfileId}:
    PATCH:
      summary: Updateconfigurationprofile
      description: Updates a configuration profile.
      operationId: amazonWebServicesUpdateConfigurationProfile
  /deployementstrategies/{DeploymentStrategyId}:
    DELETE:
      summary: Deletedeploymentstrategy
      description: >-
        Deletes a deployment strategy. Deleting a deployment strategy does not
        delete a configuration from a host.
      operationId: amazonWebServicesDeleteDeploymentStrategy
  /applications/{ApplicationId}/environments/{EnvironmentId}:
    PATCH:
      summary: Updateenvironment
      description: Updates an environment.
      operationId: amazonWebServicesUpdateEnvironment
  /extensions/{ExtensionIdentifier}:
    PATCH:
      summary: Updateextension
      description: >-
        Updates an AppConfig extension. For more information about extensions,
        see Working with AppConfig extensions in the AppConfig User Guide.
      operationId: amazonWebServicesUpdateExtension
  /extensionassociations/{ExtensionAssociationId}:
    PATCH:
      summary: Updateextensionassociation
      description: >-
        Updates an association. For more information about extensions and
        associations, see Working with AppConfig extensions in the AppConfig
        User Guide.
      operationId: amazonWebServicesUpdateExtensionAssociation
  /applications/{ApplicationId}/configurationprofiles/{ConfigurationProfileId}/hostedconfigurationversions/{VersionNumber}:
    GET:
      summary: Gethostedconfigurationversion
      description: Retrieves information about a specific configuration version.
      operationId: amazonWebServicesGetHostedConfigurationVersion
  /applications/{Application}/environments/{Environment}/configurations/{Configuration}:
    GET:
      summary: Getconfiguration
      description: >-
        (Deprecated) Retrieves the latest deployed configuration.  Note the
        following important information.   This API action is deprecated. Calls
        to receive configuration data should use the StartConfigurationSession
        and GetLatestConfiguration APIs instead.     GetConfiguration is a
        priced call. For more information, see Pricing.   
      operationId: amazonWebServicesGetConfiguration
  /applications/{ApplicationId}/environments/{EnvironmentId}/deployments/{DeploymentNumber}:
    DELETE:
      summary: Stopdeployment
      description: >-
        Stops a deployment. This API action works only on deployments that have
        a status of DEPLOYING. This action moves the deployment to a status of
        ROLLED_BACK.
      operationId: amazonWebServicesStopDeployment
  /deploymentstrategies/{DeploymentStrategyId}:
    PATCH:
      summary: Updatedeploymentstrategy
      description: Updates a deployment strategy.
      operationId: amazonWebServicesUpdateDeploymentStrategy
  /applications/{ApplicationId}/environments/{EnvironmentId}/deployments:
    POST:
      summary: Startdeployment
      description: Starts a deployment.
      operationId: amazonWebServicesStartDeployment
  /tags/{ResourceArn}:
    DELETE:
      summary: Untagresource
      description: Deletes a tag key and value from an AppConfig resource.
      operationId: amazonWebServicesUntagResource
  /applications/{ApplicationId}/configurationprofiles/{ConfigurationProfileId}/validators:
    POST:
      summary: Validateconfiguration
      description: >-
        Uses the validators in a configuration profile to validate a
        configuration.
      operationId: amazonWebServicesValidateConfiguration
tags: []
