openapi: 3.1.0
info:
  title: appflow
  description: >-
    <p>Welcome to the Amazon AppFlow API reference. This guide is for developers
    who need detailed information about the Amazon AppFlow API operations, data
    types, and errors. </p> <p>Amazon AppFlow is a fully managed integration
    service that enables you to securely transfer data between software as a
    service (SaaS) applications like Salesforce, Marketo, Slack, and ServiceNow,
    and Amazon Web Services like Amazon S3 and Amazon Redshift. </p> <p>Use the
    following links to get started on the Amazon AppFlow API:</p> <ul> <li> <p>
    <a
    href="https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Operations.html">Actions</a>:
    An alphabetical list of all Amazon AppFlow API operations.</p> </li> <li>
    <p> <a
    href="https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Types.html">Data
    types</a>: An alphabetical list of all Amazon AppFlow data types.</p> </li>
    <li> <p> <a
    href="https://docs.aws.amazon.com/appflow/1.0/APIReference/CommonParameters.html">Common
    parameters</a>: Parameters that all Query operations can use.</p> </li> <li>
    <p> <a
    href="https://docs.aws.amazon.com/appflow/1.0/APIReference/CommonErrors.html">Common
    errors</a>: Client and server errors that all operations can return.</p>
    </li> </ul> <p>If you're new to Amazon AppFlow, we recommend that you review
    the <a
    href="https://docs.aws.amazon.com/appflow/latest/userguide/what-is-appflow.html">Amazon
    AppFlow User Guide</a>.</p> <p>Amazon AppFlow API users can use
    vendor-specific mechanisms for OAuth, and include applicable OAuth
    attributes (such as <code>auth-code</code> and <code>redirecturi</code>)
    with the connector-specific <code>ConnectorProfileProperties</code> when
    creating a new connector profile using Amazon AppFlow API operations. For
    example, Salesforce users can refer to the <a
    href="https://help.salesforce.com/articleView?id=remoteaccess_authenticate.htm">
    <i>Authorize Apps with OAuth</i> </a> documentation.</p>
paths:
  /cancel-flow-executions:
    POST:
      summary: Cancelflowexecutions
      description: >-
        Cancels active runs for a flow. You can cancel all of the active runs
        for a flow, or you can cancel specific runs by providing their IDs. You
        can cancel a flow run only when the run is in progress. You can't cancel
        a run that has already completed or failed. You also can't cancel a run
        that's scheduled to occur but hasn't started yet. To prevent a scheduled
        run, you can deactivate the flow with the StopFlow action. You cannot
        resume a run after you cancel it. When you send your request, the status
        for each run becomes CancelStarted. When the cancellation completes, the
        status becomes Canceled.  When you cancel a run, you still incur charges
        for any data that the run already processed before the cancellation. If
        the run had already written some data to the flow destination, then that
        data remains in the destination. If you configured the flow to use a
        batch API (such as the Salesforce Bulk API 2.0), then the run will
        finish reading or writing its entire batch of data after the
        cancellation. For these operations, the data processing charges for
        Amazon AppFlow apply. For the pricing information, see Amazon AppFlow
        pricing. 
      operationId: amazonWebServicesCancelFlowExecutions
  /create-connector-profile:
    POST:
      summary: Createconnectorprofile
      description: ' Creates a new connector profile associated with your Amazon Web Services account. There is a soft quota of 100 connector profiles per Amazon Web Services account. If you need more connector profiles than this quota allows, you can submit a request to the Amazon AppFlow team through the Amazon AppFlow support channel. In each connector profile that you create, you can provide the credentials and properties for only one connector.'
      operationId: amazonWebServicesCreateConnectorProfile
  /create-flow:
    POST:
      summary: Createflow
      description: ' Enables your application to create a new flow using Amazon AppFlow. You must create a connector profile before calling this API. Please note that the Request Syntax below shows syntax for multiple destinations, however, you can only transfer data to one item in this list at a time. Amazon AppFlow does not currently support flows to multiple destinations at once. '
      operationId: amazonWebServicesCreateFlow
  /delete-connector-profile:
    POST:
      summary: Deleteconnectorprofile
      description: ' Enables you to delete an existing connector profile. '
      operationId: amazonWebServicesDeleteConnectorProfile
  /delete-flow:
    POST:
      summary: Deleteflow
      description: ' Enables your application to delete an existing flow. Before deleting the flow, Amazon AppFlow validates the request by checking the flow configuration and status. You can delete flows one at a time. '
      operationId: amazonWebServicesDeleteFlow
  /describe-connector:
    POST:
      summary: Describeconnector
      description: >-
        Describes the given custom connector registered in your Amazon Web
        Services account. This API can be used for custom connectors that are
        registered in your account and also for Amazon authored connectors.
      operationId: amazonWebServicesDescribeConnector
  /describe-connector-entity:
    POST:
      summary: Describeconnectorentity
      description: ' Provides details regarding the entity used with the connector, with a description of the data model for each field in that entity. '
      operationId: amazonWebServicesDescribeConnectorEntity
  /describe-connector-profiles:
    POST:
      summary: Describeconnectorprofiles
      description: ' Returns a list of connector-profile details matching the provided connector-profile names and connector-types. Both input lists are optional, and you can use them to filter the result.  If no names or connector-types are provided, returns all connector profiles in a paginated form. If there is no match, this operation returns an empty list.'
      operationId: amazonWebServicesDescribeConnectorProfiles
  /describe-connectors:
    POST:
      summary: Describeconnectors
      description: ' Describes the connectors vended by Amazon AppFlow for specified connector types. If you don''t specify a connector type, this operation describes all connectors vended by Amazon AppFlow. If there are more connectors than can be returned in one page, the response contains a nextToken object, which can be be passed in to the next call to the DescribeConnectors API operation to retrieve the next page. '
      operationId: amazonWebServicesDescribeConnectors
  /describe-flow:
    POST:
      summary: Describeflow
      description: ' Provides a description of the specified flow. '
      operationId: amazonWebServicesDescribeFlow
  /describe-flow-execution-records:
    POST:
      summary: Describeflowexecutionrecords
      description: ' Fetches the execution history of the flow. '
      operationId: amazonWebServicesDescribeFlowExecutionRecords
  /list-connector-entities:
    POST:
      summary: Listconnectorentities
      description: ' Returns the list of available connector entities supported by Amazon AppFlow. For example, you can query Salesforce for Account and Opportunity entities, or query ServiceNow for the Incident entity. '
      operationId: amazonWebServicesListConnectorEntities
  /list-connectors:
    POST:
      summary: Listconnectors
      description: >-
        Returns the list of all registered custom connectors in your Amazon Web
        Services account. This API lists only custom connectors registered in
        this account, not the Amazon Web Services authored connectors. 
      operationId: amazonWebServicesListConnectors
  /list-flows:
    POST:
      summary: Listflows
      description: ' Lists all of the flows associated with your account. '
      operationId: amazonWebServicesListFlows
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: ' Removes a tag from the specified flow. '
      operationId: amazonWebServicesUntagResource
  /register-connector:
    POST:
      summary: Registerconnector
      description: >-
        Registers a new custom connector with your Amazon Web Services account.
        Before you can register the connector, you must deploy the associated
        AWS lambda function in your account.
      operationId: amazonWebServicesRegisterConnector
  /reset-connector-metadata-cache:
    POST:
      summary: Resetconnectormetadatacache
      description: >-
        Resets metadata about your connector entities that Amazon AppFlow stored
        in its cache. Use this action when you want Amazon AppFlow to return the
        latest information about the data that you have in a source application.
        Amazon AppFlow returns metadata about your entities when you use the
        ListConnectorEntities or DescribeConnectorEntities actions. Following
        these actions, Amazon AppFlow caches the metadata to reduce the number
        of API requests that it must send to the source application. Amazon
        AppFlow automatically resets the cache once every hour, but you can use
        this action when you want to get the latest metadata right away.
      operationId: amazonWebServicesResetConnectorMetadataCache
  /start-flow:
    POST:
      summary: Startflow
      description: ' Activates an existing flow. For on-demand flows, this operation runs the flow immediately. For schedule and event-triggered flows, this operation activates the flow. '
      operationId: amazonWebServicesStartFlow
  /stop-flow:
    POST:
      summary: Stopflow
      description: ' Deactivates the existing flow. For on-demand flows, this operation returns an unsupportedOperationException error message. For schedule and event-triggered flows, this operation deactivates the flow. '
      operationId: amazonWebServicesStopFlow
  /unregister-connector:
    POST:
      summary: Unregisterconnector
      description: >-
        Unregisters the custom connector registered in your account that matches
        the connector label provided in the request.
      operationId: amazonWebServicesUnregisterConnector
  /update-connector-profile:
    POST:
      summary: Updateconnectorprofile
      description: ' Updates a given connector profile associated with your account. '
      operationId: amazonWebServicesUpdateConnectorProfile
  /update-connector-registration:
    POST:
      summary: Updateconnectorregistration
      description: >-
        Updates a custom connector that you've previously registered. This
        operation updates the connector with one of the following:   The latest
        version of the AWS Lambda function that's assigned to the connector   A
        new AWS Lambda function that you specify  
      operationId: amazonWebServicesUpdateConnectorRegistration
  /update-flow:
    POST:
      summary: Updateflow
      description: ' Updates an existing flow. '
      operationId: amazonWebServicesUpdateFlow
tags: []
