openapi: 3.1.0
info:
  title: appfabric
  description: >-
    <p>Amazon Web Services AppFabric quickly connects software as a service
    (SaaS) applications across your organization. This allows IT and security
    teams to easily manage and secure applications using a standard schema, and
    employees can complete everyday tasks faster using generative artificial
    intelligence (AI). You can use these APIs to complete AppFabric tasks, such
    as setting up audit log ingestions or viewing user access. For more
    information about AppFabric, including the required permissions to use the
    service, see the <a
    href="https://docs.aws.amazon.com/appfabric/latest/adminguide/">Amazon Web
    Services AppFabric Administration Guide</a>. For more information about
    using the Command Line Interface (CLI) to manage your AppFabric resources,
    see the <a
    href="https://docs.aws.amazon.com/cli/latest/reference/appfabric/index.html">AppFabric
    section of the CLI Reference</a>.</p>
paths:
  /useraccess/batchget:
    POST:
      summary: Batchgetuseraccesstasks
      description: >-
        Gets user access details in a batch request. This action polls data from
        the tasks that are kicked off by the StartUserAccessTasks action.
      operationId: amazonWebServicesBatchGetUserAccessTasks
  /appbundles/{appBundleIdentifier}/appauthorizations/{appAuthorizationIdentifier}/connect:
    POST:
      summary: Connectappauthorization
      description: >-
        Establishes a connection between Amazon Web Services AppFabric and an
        application, which allows AppFabric to call the APIs of the application.
      operationId: amazonWebServicesConnectAppAuthorization
  /appbundles/{appBundleIdentifier}/appauthorizations:
    GET:
      summary: Listappauthorizations
      description: Returns a list of all app authorizations configured for an app bundle.
      operationId: amazonWebServicesListAppAuthorizations
  /appbundles:
    GET:
      summary: Listappbundles
      description: Returns a list of app bundles.
      operationId: amazonWebServicesListAppBundles
  /appbundles/{appBundleIdentifier}/ingestions:
    GET:
      summary: Listingestions
      description: Returns a list of all ingestions configured for an app bundle.
      operationId: amazonWebServicesListIngestions
  /appbundles/{appBundleIdentifier}/ingestions/{ingestionIdentifier}/ingestiondestinations:
    GET:
      summary: Listingestiondestinations
      description: >-
        Returns a list of all ingestion destinations configured for an
        ingestion.
      operationId: amazonWebServicesListIngestionDestinations
  /appbundles/{appBundleIdentifier}/appauthorizations/{appAuthorizationIdentifier}:
    PATCH:
      summary: Updateappauthorization
      description: >-
        Updates an app authorization within an app bundle, which allows
        AppFabric to connect to an application. If the app authorization was in
        a connected state, updating the app authorization will set it back to a
        PendingConnect state.
      operationId: amazonWebServicesUpdateAppAuthorization
  /appbundles/{appBundleIdentifier}:
    GET:
      summary: Getappbundle
      description: Returns information about an app bundle.
      operationId: amazonWebServicesGetAppBundle
  /appbundles/{appBundleIdentifier}/ingestions/{ingestionIdentifier}:
    GET:
      summary: Getingestion
      description: Returns information about an ingestion.
      operationId: amazonWebServicesGetIngestion
  /appbundles/{appBundleIdentifier}/ingestions/{ingestionIdentifier}/ingestiondestinations/{ingestionDestinationIdentifier}:
    PATCH:
      summary: Updateingestiondestination
      description: >-
        Updates an ingestion destination, which specifies how an application's
        ingested data is processed by Amazon Web Services AppFabric and where
        it's delivered.
      operationId: amazonWebServicesUpdateIngestionDestination
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes a tag or tags from a resource.
      operationId: amazonWebServicesUntagResource
  /appbundles/{appBundleIdentifier}/ingestions/{ingestionIdentifier}/start:
    POST:
      summary: Startingestion
      description: Starts (enables) an ingestion, which collects data from an application.
      operationId: amazonWebServicesStartIngestion
  /useraccess/start:
    POST:
      summary: Startuseraccesstasks
      description: >-
        Starts the tasks to search user access status for a specific email
        address. The tasks are stopped when the user access status data is
        found. The tasks are terminated when the API calls to the application
        time out.
      operationId: amazonWebServicesStartUserAccessTasks
  /appbundles/{appBundleIdentifier}/ingestions/{ingestionIdentifier}/stop:
    POST:
      summary: Stopingestion
      description: Stops (disables) an ingestion.
      operationId: amazonWebServicesStopIngestion
tags: []
