openapi: 3.1.0
info:
  title: appintegrations
  description: >-
    <p>The Amazon AppIntegrations service enables you to configure and reuse
    connections to external applications.</p> <p>For information about how you
    can use external applications with Amazon Connect, see <a
    href="https://docs.aws.amazon.com/connect/latest/adminguide/crm.html">Set up
    pre-built integrations</a> and <a
    href="https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-wisdom.html">Deliver
    information to agents using Amazon Connect Wisdom</a> in the <i>Amazon
    Connect Administrator Guide</i>.</p>
paths:
  /applications:
    GET:
      summary: Listapplications
      description: >-
        This API is in preview release and subject to change. Lists applications
        in the account.
      operationId: amazonWebServicesListApplications
  /dataIntegrations:
    GET:
      summary: Listdataintegrations
      description: >-
        Returns a paginated list of DataIntegrations in the account.  You cannot
        create a DataIntegration association for a DataIntegration that has been
        previously associated. Use a different DataIntegration, or recreate the
        DataIntegration using the CreateDataIntegration API. 
      operationId: amazonWebServicesListDataIntegrations
  /eventIntegrations:
    GET:
      summary: Listeventintegrations
      description: Returns a paginated list of event integrations in the account.
      operationId: amazonWebServicesListEventIntegrations
  /applications/{ApplicationIdentifier}:
    PATCH:
      summary: Updateapplication
      description: >-
        This API is in preview release and subject to change. Updates and
        persists an Application resource.
      operationId: amazonWebServicesUpdateApplication
  /dataIntegrations/{Identifier}:
    PATCH:
      summary: Updatedataintegration
      description: >-
        Updates the description of a DataIntegration.  You cannot create a
        DataIntegration association for a DataIntegration that has been
        previously associated. Use a different DataIntegration, or recreate the
        DataIntegration using the CreateDataIntegration API. 
      operationId: amazonWebServicesUpdateDataIntegration
  /eventIntegrations/{Name}:
    PATCH:
      summary: Updateeventintegration
      description: Updates the description of an event integration.
      operationId: amazonWebServicesUpdateEventIntegration
  /applications/{ApplicationIdentifier}/associations:
    GET:
      summary: Listapplicationassociations
      description: Returns a paginated list of application associations for an application.
      operationId: amazonWebServicesListApplicationAssociations
  /dataIntegrations/{Identifier}/associations:
    GET:
      summary: Listdataintegrationassociations
      description: >-
        Returns a paginated list of DataIntegration associations in the
        account.  You cannot create a DataIntegration association for a
        DataIntegration that has been previously associated. Use a different
        DataIntegration, or recreate the DataIntegration using the
        CreateDataIntegration API. 
      operationId: amazonWebServicesListDataIntegrationAssociations
  /eventIntegrations/{Name}/associations:
    GET:
      summary: Listeventintegrationassociations
      description: >-
        Returns a paginated list of event integration associations in the
        account. 
      operationId: amazonWebServicesListEventIntegrationAssociations
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes the specified tags from the specified resource.
      operationId: amazonWebServicesUntagResource
tags: []
