openapi: 3.1.0
info:
  title: applicationcostprofiler
  description: >-
    <p>This reference provides descriptions of the AWS Application Cost Profiler
    API.</p> <p>The AWS Application Cost Profiler API provides programmatic
    access to view, create, update, and delete application cost report
    definitions, as well as to import your usage data into the Application Cost
    Profiler service.</p> <p>For more information about using this service, see
    the <a
    href="https://docs.aws.amazon.com/application-cost-profiler/latest/userguide/introduction.html">AWS
    Application Cost Profiler User Guide</a>.</p>
paths:
  /reportDefinition/{reportId}:
    PUT:
      summary: Updatereportdefinition
      description: Updates existing report in AWS Application Cost Profiler.
      operationId: amazonWebServicesUpdateReportDefinition
  /importApplicationUsage:
    POST:
      summary: Importapplicationusage
      description: >-
        Ingests application usage data from Amazon Simple Storage Service
        (Amazon S3). The data must already exist in the S3 location. As part of
        the action, AWS Application Cost Profiler copies the object from your S3
        bucket to an S3 bucket owned by Amazon for processing asynchronously.
      operationId: amazonWebServicesImportApplicationUsage
  /reportDefinition:
    POST:
      summary: Putreportdefinition
      description: Creates the report definition for a report in Application Cost Profiler.
      operationId: amazonWebServicesPutReportDefinition
tags: []
