openapi: 3.1.0
info:
  title: appmesh
  description: >-
    <p>App Mesh is a service mesh based on the Envoy proxy that makes it easy to
    monitor and control microservices. App Mesh standardizes how your
    microservices communicate, giving you end-to-end visibility and helping to
    ensure high availability for your applications.</p> <p>App Mesh gives you
    consistent visibility and network traffic controls for every microservice in
    an application. You can use App Mesh with Amazon Web Services Fargate,
    Amazon ECS, Amazon EKS, Kubernetes on Amazon Web Services, and Amazon
    EC2.</p> <note> <p>App Mesh supports microservice applications that use
    service discovery naming for their components. For more information about
    service discovery on Amazon ECS, see <a
    href="https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-discovery.html">Service
    Discovery</a> in the <i>Amazon Elastic Container Service Developer
    Guide</i>. Kubernetes <code>kube-dns</code> and <code>coredns</code> are
    supported. For more information, see <a
    href="https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/">DNS
    for Services and Pods</a> in the Kubernetes documentation.</p> </note>
paths:
  /v20190125/meshes/{meshName}/virtualGateway/{virtualGatewayName}/gatewayRoutes:
    GET:
      summary: Listgatewayroutes
      description: >-
        Returns a list of existing gateway routes that are associated to a
        virtual gateway.
      operationId: amazonWebServicesListGatewayRoutes
  /v20190125/meshes:
    GET:
      summary: Listmeshes
      description: Returns a list of existing service meshes.
      operationId: amazonWebServicesListMeshes
  /v20190125/meshes/{meshName}/virtualRouter/{virtualRouterName}/routes:
    GET:
      summary: Listroutes
      description: Returns a list of existing routes in a service mesh.
      operationId: amazonWebServicesListRoutes
  /v20190125/meshes/{meshName}/virtualGateways:
    GET:
      summary: Listvirtualgateways
      description: Returns a list of existing virtual gateways in a service mesh.
      operationId: amazonWebServicesListVirtualGateways
  /v20190125/meshes/{meshName}/virtualNodes:
    GET:
      summary: Listvirtualnodes
      description: Returns a list of existing virtual nodes.
      operationId: amazonWebServicesListVirtualNodes
  /v20190125/meshes/{meshName}/virtualRouters:
    GET:
      summary: Listvirtualrouters
      description: Returns a list of existing virtual routers in a service mesh.
      operationId: amazonWebServicesListVirtualRouters
  /v20190125/meshes/{meshName}/virtualServices:
    GET:
      summary: Listvirtualservices
      description: Returns a list of existing virtual services in a service mesh.
      operationId: amazonWebServicesListVirtualServices
  /v20190125/meshes/{meshName}/virtualGateway/{virtualGatewayName}/gatewayRoutes/{gatewayRouteName}:
    PUT:
      summary: Updategatewayroute
      description: >-
        Updates an existing gateway route that is associated to a specified
        virtual gateway in a service mesh.
      operationId: amazonWebServicesUpdateGatewayRoute
  /v20190125/meshes/{meshName}:
    PUT:
      summary: Updatemesh
      description: Updates an existing service mesh.
      operationId: amazonWebServicesUpdateMesh
  /v20190125/meshes/{meshName}/virtualRouter/{virtualRouterName}/routes/{routeName}:
    PUT:
      summary: Updateroute
      description: >-
        Updates an existing route for a specified service mesh and virtual
        router.
      operationId: amazonWebServicesUpdateRoute
  /v20190125/meshes/{meshName}/virtualGateways/{virtualGatewayName}:
    PUT:
      summary: Updatevirtualgateway
      description: Updates an existing virtual gateway in a specified service mesh.
      operationId: amazonWebServicesUpdateVirtualGateway
  /v20190125/meshes/{meshName}/virtualNodes/{virtualNodeName}:
    PUT:
      summary: Updatevirtualnode
      description: Updates an existing virtual node in a specified service mesh.
      operationId: amazonWebServicesUpdateVirtualNode
  /v20190125/meshes/{meshName}/virtualRouters/{virtualRouterName}:
    PUT:
      summary: Updatevirtualrouter
      description: Updates an existing virtual router in a specified service mesh.
      operationId: amazonWebServicesUpdateVirtualRouter
  /v20190125/meshes/{meshName}/virtualServices/{virtualServiceName}:
    PUT:
      summary: Updatevirtualservice
      description: Updates an existing virtual service in a specified service mesh.
      operationId: amazonWebServicesUpdateVirtualService
  /v20190125/tags:
    GET:
      summary: Listtagsforresource
      description: List the tags for an App Mesh resource.
      operationId: amazonWebServicesListTagsForResource
  /v20190125/tag:
    PUT:
      summary: Tagresource
      description: >-
        Associates the specified tags to a resource with the specified
        resourceArn. If existing tags on a resource aren't specified in the
        request parameters, they aren't changed. When a resource is deleted, the
        tags associated with that resource are also deleted.
      operationId: amazonWebServicesTagResource
  /v20190125/untag:
    PUT:
      summary: Untagresource
      description: Deletes specified tags from a resource.
      operationId: amazonWebServicesUntagResource
tags: []
