openapi: 3.1.0
info:
  title: bedrock-agent
  description: >-
    <p>An example service, deployed with the Octane Service creator, which will
    echo the string</p>
paths:
  /agents/{agentId}/agentversions/{agentVersion}/knowledgebases/:
    POST:
      summary: Listagentknowledgebases
      description: >-
        List of Knowledge Bases associated to an existing Amazon Bedrock Agent
        Version
      operationId: amazonWebServicesListAgentKnowledgeBases
  /agents/:
    POST:
      summary: Listagents
      description: Lists Agents
      operationId: amazonWebServicesListAgents
  /agents/{agentId}/agentversions/{agentVersion}/actiongroups/:
    POST:
      summary: Listagentactiongroups
      description: Lists an Action Group for existing Amazon Bedrock Agent Version
      operationId: amazonWebServicesListAgentActionGroups
  /agents/{agentId}/agentaliases/:
    POST:
      summary: Listagentaliases
      description: Lists all the Aliases for an Amazon Bedrock Agent
      operationId: amazonWebServicesListAgentAliases
  /knowledgebases/{knowledgeBaseId}/datasources/:
    POST:
      summary: Listdatasources
      description: List data sources
      operationId: amazonWebServicesListDataSources
  /knowledgebases/:
    POST:
      summary: Listknowledgebases
      description: List Knowledge Bases
      operationId: amazonWebServicesListKnowledgeBases
  /agents/{agentId}/:
    PUT:
      summary: Updateagent
      description: Updates an existing Amazon Bedrock Agent
      operationId: amazonWebServicesUpdateAgent
  /agents/{agentId}/agentversions/{agentVersion}/actiongroups/{actionGroupId}/:
    PUT:
      summary: Updateagentactiongroup
      description: Updates an existing Action Group for Amazon Bedrock Agent
      operationId: amazonWebServicesUpdateAgentActionGroup
  /agents/{agentId}/agentaliases/{agentAliasId}/:
    PUT:
      summary: Updateagentalias
      description: Updates an existing Alias for an Amazon Bedrock Agent
      operationId: amazonWebServicesUpdateAgentAlias
  /agents/{agentId}/agentversions/{agentVersion}/:
    GET:
      summary: Getagentversion
      description: Gets an Agent version for existing Amazon Bedrock Agent
      operationId: amazonWebServicesGetAgentVersion
  /knowledgebases/{knowledgeBaseId}/datasources/{dataSourceId}:
    PUT:
      summary: Updatedatasource
      description: Update an existing data source
      operationId: amazonWebServicesUpdateDataSource
  /knowledgebases/{knowledgeBaseId}:
    PUT:
      summary: Updateknowledgebase
      description: Update an existing knowledge base
      operationId: amazonWebServicesUpdateKnowledgeBase
  /agents/{agentId}/agentversions/{agentVersion}/knowledgebases/{knowledgeBaseId}/:
    PUT:
      summary: Updateagentknowledgebase
      description: Updates an existing Knowledge Base associated to an Amazon Bedrock Agent
      operationId: amazonWebServicesUpdateAgentKnowledgeBase
  /knowledgebases/{knowledgeBaseId}/datasources/{dataSourceId}/ingestionjobs/{ingestionJobId}:
    GET:
      summary: Getingestionjob
      description: Get an ingestion job
      operationId: amazonWebServicesGetIngestionJob
  /agents/{agentId}/agentversions/:
    POST:
      summary: Listagentversions
      description: Lists Agent Versions
      operationId: amazonWebServicesListAgentVersions
  /knowledgebases/{knowledgeBaseId}/datasources/{dataSourceId}/ingestionjobs/:
    PUT:
      summary: Startingestionjob
      description: Start a new ingestion job
      operationId: amazonWebServicesStartIngestionJob
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Untag a resource
      operationId: amazonWebServicesUntagResource
tags: []
