openapi: 3.1.0
info:
  title: bedrock
  description: >-
    <p>Describes the API operations for creating and managing Amazon Bedrock
    models.</p>
paths:
  /model-customization-jobs:
    GET:
      summary: Listmodelcustomizationjobs
      description: >-
        Returns a list of model customization jobs that you have submitted. You
        can filter the jobs to return based on one or more criteria. For more
        information, see Custom models in the Bedrock User Guide.
      operationId: amazonWebServicesListModelCustomizationJobs
  /provisioned-model-throughput:
    POST:
      summary: Createprovisionedmodelthroughput
      description: >-
        Creates a provisioned throughput with dedicated capacity for a
        foundation model or a fine-tuned model. For more information, see
        Provisioned throughput in the Bedrock User Guide.
      operationId: amazonWebServicesCreateProvisionedModelThroughput
  /custom-models/{modelIdentifier}:
    GET:
      summary: Getcustommodel
      description: >-
        Get the properties associated with a Amazon Bedrock custom model that
        you have created.For more information, see Custom models in the Bedrock
        User Guide.
      operationId: amazonWebServicesGetCustomModel
  /logging/modelinvocations:
    PUT:
      summary: Putmodelinvocationloggingconfiguration
      description: Set the configuration values for model invocation logging.
      operationId: amazonWebServicesPutModelInvocationLoggingConfiguration
  /provisioned-model-throughput/{provisionedModelId}:
    PATCH:
      summary: Updateprovisionedmodelthroughput
      description: >-
        Update a provisioned throughput. For more information, see Provisioned
        throughput in the Bedrock User Guide.
      operationId: amazonWebServicesUpdateProvisionedModelThroughput
  /foundation-models/{modelIdentifier}:
    GET:
      summary: Getfoundationmodel
      description: Get details about a Amazon Bedrock foundation model.
      operationId: amazonWebServicesGetFoundationModel
  /model-customization-jobs/{jobIdentifier}:
    GET:
      summary: Getmodelcustomizationjob
      description: >-
        Retrieves the properties associated with a model-customization job,
        including the status of the job. For more information, see Custom models
        in the Bedrock User Guide.
      operationId: amazonWebServicesGetModelCustomizationJob
  /custom-models:
    GET:
      summary: Listcustommodels
      description: >-
        Returns a list of the custom models that you have created with the
        CreateModelCustomizationJob operation. For more information, see Custom
        models in the Bedrock User Guide.
      operationId: amazonWebServicesListCustomModels
  /foundation-models:
    GET:
      summary: Listfoundationmodels
      description: >-
        List of Amazon Bedrock foundation models that you can use. For more
        information, see Foundation models in the Bedrock User Guide.
      operationId: amazonWebServicesListFoundationModels
  /provisioned-model-throughputs:
    GET:
      summary: Listprovisionedmodelthroughputs
      description: >-
        List the provisioned capacities. For more information, see Provisioned
        throughput in the Bedrock User Guide.
      operationId: amazonWebServicesListProvisionedModelThroughputs
  /listTagsForResource:
    POST:
      summary: Listtagsforresource
      description: >-
        List the tags associated with the specified resource. For more
        information, see Tagging resources in the Bedrock User Guide.
      operationId: amazonWebServicesListTagsForResource
  /model-customization-jobs/{jobIdentifier}/stop:
    POST:
      summary: Stopmodelcustomizationjob
      description: >-
        Stops an active model customization job. For more information, see
        Custom models in the Bedrock User Guide.
      operationId: amazonWebServicesStopModelCustomizationJob
  /tagResource:
    POST:
      summary: Tagresource
      description: >-
        Associate tags with a resource. For more information, see Tagging
        resources in the Bedrock User Guide.
      operationId: amazonWebServicesTagResource
  /untagResource:
    POST:
      summary: Untagresource
      description: >-
        Remove one or more tags from a resource. For more information, see
        Tagging resources in the Bedrock User Guide.
      operationId: amazonWebServicesUntagResource
tags: []
