openapi: 3.1.0
info:
  title: bedrock-agent-runtime
  description: <p>Amazon Bedrock Agent</p>
paths:
  /agents/{agentId}/agentAliases/{agentAliasId}/sessions/{sessionId}/text:
    POST:
      summary: Invokeagent
      description: >-
        Invokes the specified Bedrock model to run inference using the input
        provided in the request body.
      operationId: amazonWebServicesInvokeAgent
  /knowledgebases/{knowledgeBaseId}/retrieve:
    POST:
      summary: Retrieve
      description: Retrieve from knowledge base.
      operationId: amazonWebServicesRetrieve
  /retrieveAndGenerate:
    POST:
      summary: Retrieveandgenerate
      description: RetrieveAndGenerate API
      operationId: amazonWebServicesRetrieveAndGenerate
tags: []
