openapi: 3.1.0
info:
  title: billingconductor
  description: >-
    <p>Amazon Web Services Billing Conductor is a fully managed service that you
    can use to customize a <a
    href="https://docs.aws.amazon.com/billingconductor/latest/userguide/understanding-eb.html#eb-other-definitions">proforma</a>
    version of your billing data each month, to accurately show or chargeback
    your end customers. Amazon Web Services Billing Conductor doesn't change the
    way you're billed by Amazon Web Services each month by design. Instead, it
    provides you with a mechanism to configure, generate, and display rates to
    certain customers over a given billing period. You can also analyze the
    difference between the rates you apply to your accounting groupings relative
    to your actual rates from Amazon Web Services. As a result of your Amazon
    Web Services Billing Conductor configuration, the payer account can also see
    the custom rate applied on the billing details page of the <a
    href="https://console.aws.amazon.com/billing">Amazon Web Services Billing
    console</a>, or configure a cost and usage report per billing group.</p>
    <p>This documentation shows how you can configure Amazon Web Services
    Billing Conductor using its API. For more information about using the <a
    href="https://console.aws.amazon.com/billingconductor/">Amazon Web Services
    Billing Conductor</a> user interface, see the <a
    href="https://docs.aws.amazon.com/billingconductor/latest/userguide/what-is-billingconductor.html">
    Amazon Web Services Billing Conductor User Guide</a>.</p>
paths:
  /associate-accounts:
    POST:
      summary: Associateaccounts
      description: >-
        Connects an array of account IDs in a consolidated billing family to a
        predefined billing group. The account IDs must be a part of the
        consolidated billing family during the current month, and not already
        associated with another billing group. The maximum number of accounts
        that can be associated in one call is 30. 
      operationId: amazonWebServicesAssociateAccounts
  /associate-pricing-rules:
    PUT:
      summary: Associatepricingrules
      description: >-
        Connects an array of PricingRuleArns to a defined PricingPlan. The
        maximum number PricingRuleArn that can be associated in one call is 30. 
      operationId: amazonWebServicesAssociatePricingRules
  /batch-associate-resources-to-custom-line-item:
    PUT:
      summary: Batchassociateresourcestocustomlineitem
      description: ' Associates a batch of resources to a percentage custom line item. '
      operationId: amazonWebServicesBatchAssociateResourcesToCustomLineItem
  /batch-disassociate-resources-from-custom-line-item:
    PUT:
      summary: Batchdisassociateresourcesfromcustomlineitem
      description: ' Disassociates a batch of resources from a percentage custom line item. '
      operationId: amazonWebServicesBatchDisassociateResourcesFromCustomLineItem
  /create-billing-group:
    POST:
      summary: Createbillinggroup
      description: ' Creates a billing group that resembles a consolidated billing family that Amazon Web Services charges, based off of the predefined pricing plan computation. '
      operationId: amazonWebServicesCreateBillingGroup
  /create-custom-line-item:
    POST:
      summary: Createcustomlineitem
      description: >-
        Creates a custom line item that can be used to create a one-time fixed
        charge that can be applied to a single billing group for the current or
        previous billing period. The one-time fixed charge is either a fee or
        discount. 
      operationId: amazonWebServicesCreateCustomLineItem
  /create-pricing-plan:
    POST:
      summary: Createpricingplan
      description: >-
        Creates a pricing plan that is used for computing Amazon Web Services
        charges for billing groups. 
      operationId: amazonWebServicesCreatePricingPlan
  /create-pricing-rule:
    POST:
      summary: Createpricingrule
      description: ' Creates a pricing rule can be associated to a pricing plan, or a set of pricing plans. '
      operationId: amazonWebServicesCreatePricingRule
  /delete-billing-group:
    POST:
      summary: Deletebillinggroup
      description: ' Deletes a billing group. '
      operationId: amazonWebServicesDeleteBillingGroup
  /delete-custom-line-item:
    POST:
      summary: Deletecustomlineitem
      description: ' Deletes the custom line item identified by the given ARN in the current, or previous billing period. '
      operationId: amazonWebServicesDeleteCustomLineItem
  /delete-pricing-plan:
    POST:
      summary: Deletepricingplan
      description: >-
        Deletes a pricing plan. The pricing plan must not be associated with any
        billing groups to delete successfully.
      operationId: amazonWebServicesDeletePricingPlan
  /delete-pricing-rule:
    POST:
      summary: Deletepricingrule
      description: ' Deletes the pricing rule that''s identified by the input Amazon Resource Name (ARN). '
      operationId: amazonWebServicesDeletePricingRule
  /disassociate-accounts:
    POST:
      summary: Disassociateaccounts
      description: 'Removes the specified list of account IDs from the given billing group. '
      operationId: amazonWebServicesDisassociateAccounts
  /disassociate-pricing-rules:
    PUT:
      summary: Disassociatepricingrules
      description: ' Disassociates a list of pricing rules from a pricing plan. '
      operationId: amazonWebServicesDisassociatePricingRules
  /get-billing-group-cost-report:
    POST:
      summary: Getbillinggroupcostreport
      description: >-
        Retrieves the margin summary report, which includes the Amazon Web
        Services cost and charged amount (pro forma cost) by Amazon Web Service
        for a specific billing group.
      operationId: amazonWebServicesGetBillingGroupCostReport
  /list-account-associations:
    POST:
      summary: Listaccountassociations
      description: ' This is a paginated call to list linked accounts that are linked to the payer account for the specified time period. If no information is provided, the current billing period is used. The response will optionally include the billing group that''s associated with the linked account.'
      operationId: amazonWebServicesListAccountAssociations
  /list-billing-group-cost-reports:
    POST:
      summary: Listbillinggroupcostreports
      description: >-
        A paginated call to retrieve a summary report of actual Amazon Web
        Services charges and the calculated Amazon Web Services charges based on
        the associated pricing plan of a billing group.
      operationId: amazonWebServicesListBillingGroupCostReports
  /list-billing-groups:
    POST:
      summary: Listbillinggroups
      description: >-
        A paginated call to retrieve a list of billing groups for the given
        billing period. If you don't provide a billing group, the current
        billing period is used.
      operationId: amazonWebServicesListBillingGroups
  /list-custom-line-item-versions:
    POST:
      summary: Listcustomlineitemversions
      description: A paginated call to get a list of all custom line item versions.
      operationId: amazonWebServicesListCustomLineItemVersions
  /list-custom-line-items:
    POST:
      summary: Listcustomlineitems
      description: ' A paginated call to get a list of all custom line items (FFLIs) for the given billing period. If you don''t provide a billing period, the current billing period is used. '
      operationId: amazonWebServicesListCustomLineItems
  /list-pricing-plans:
    POST:
      summary: Listpricingplans
      description: >-
        A paginated call to get pricing plans for the given billing period. If
        you don't provide a billing period, the current billing period is used. 
      operationId: amazonWebServicesListPricingPlans
  /list-pricing-plans-associated-with-pricing-rule:
    POST:
      summary: Listpricingplansassociatedwithpricingrule
      description: ' A list of the pricing plans that are associated with a pricing rule. '
      operationId: amazonWebServicesListPricingPlansAssociatedWithPricingRule
  /list-pricing-rules:
    POST:
      summary: Listpricingrules
      description: ' Describes a pricing rule that can be associated to a pricing plan, or set of pricing plans. '
      operationId: amazonWebServicesListPricingRules
  /list-pricing-rules-associated-to-pricing-plan:
    POST:
      summary: Listpricingrulesassociatedtopricingplan
      description: ' Lists the pricing rules that are associated with a pricing plan. '
      operationId: amazonWebServicesListPricingRulesAssociatedToPricingPlan
  /list-resources-associated-to-custom-line-item:
    POST:
      summary: Listresourcesassociatedtocustomlineitem
      description: ' List the resources that are associated to a custom line item. '
      operationId: amazonWebServicesListResourcesAssociatedToCustomLineItem
  /tags/{ResourceArn}:
    DELETE:
      summary: Untagresource
      description: ' Deletes specified tags from a resource. '
      operationId: amazonWebServicesUntagResource
  /update-billing-group:
    POST:
      summary: Updatebillinggroup
      description: 'This updates an existing billing group. '
      operationId: amazonWebServicesUpdateBillingGroup
  /update-custom-line-item:
    POST:
      summary: Updatecustomlineitem
      description: ' Update an existing custom line item in the current or previous billing period. '
      operationId: amazonWebServicesUpdateCustomLineItem
  /update-pricing-plan:
    PUT:
      summary: Updatepricingplan
      description: 'This updates an existing pricing plan. '
      operationId: amazonWebServicesUpdatePricingPlan
  /update-pricing-rule:
    PUT:
      summary: Updatepricingrule
      description: ' Updates an existing pricing rule. '
      operationId: amazonWebServicesUpdatePricingRule
tags: []
