openapi: 3.1.0
info:
  title: braket
  description: >-
    <p>The Amazon Braket API Reference provides information about the operations
    and structures supported in Amazon Braket.</p> <p>Additional Resources:</p>
    <ul> <li> <p> <a
    href="https://docs.aws.amazon.com/braket/latest/developerguide/what-is-braket.html">Amazon
    Braket Developer Guide</a> </p> </li> </ul>
paths:
  /job/{jobArn}/cancel:
    PUT:
      summary: Canceljob
      description: Cancels an Amazon Braket job.
      operationId: amazonWebServicesCancelJob
  /quantum-task/{quantumTaskArn}/cancel:
    PUT:
      summary: Cancelquantumtask
      description: Cancels the specified task.
      operationId: amazonWebServicesCancelQuantumTask
  /job:
    POST:
      summary: Createjob
      description: Creates an Amazon Braket job.
      operationId: amazonWebServicesCreateJob
  /quantum-task:
    POST:
      summary: Createquantumtask
      description: Creates a quantum task.
      operationId: amazonWebServicesCreateQuantumTask
  /device/{deviceArn}:
    GET:
      summary: Getdevice
      description: >-
        Retrieves the devices available in Amazon Braket.  For backwards
        compatibility with older versions of BraketSchemas, OpenQASM information
        is omitted from GetDevice API calls. To get this information the
        user-agent needs to present a recent version of the BraketSchemas (1.8.0
        or later). The Braket SDK automatically reports this for you. If you do
        not see OpenQASM results in the GetDevice response when using a Braket
        SDK, you may need to set AWS_EXECUTION_ENV environment variable to
        configure user-agent. See the code examples provided below for how to do
        this for the AWS CLI, Boto3, and the Go, Java, and JavaScript/TypeScript
        SDKs. 
      operationId: amazonWebServicesGetDevice
  /job/{jobArn}:
    GET:
      summary: Getjob
      description: Retrieves the specified Amazon Braket job.
      operationId: amazonWebServicesGetJob
  /quantum-task/{quantumTaskArn}:
    GET:
      summary: Getquantumtask
      description: Retrieves the specified quantum task.
      operationId: amazonWebServicesGetQuantumTask
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Remove tags from a resource.
      operationId: amazonWebServicesUntagResource
  /devices:
    POST:
      summary: Searchdevices
      description: Searches for devices using the specified filters.
      operationId: amazonWebServicesSearchDevices
  /jobs:
    POST:
      summary: Searchjobs
      description: Searches for Amazon Braket jobs that match the specified filter values.
      operationId: amazonWebServicesSearchJobs
  /quantum-tasks:
    POST:
      summary: Searchquantumtasks
      description: Searches for tasks that match the specified filter values.
      operationId: amazonWebServicesSearchQuantumTasks
tags: []
