openapi: 3.1.0
info:
  title: chime-sdk-voice
  description: >-
    <p>The Amazon Chime SDK telephony APIs in this section enable developers to
    create PSTN calling solutions that use Amazon Chime SDK Voice Connectors,
    and Amazon Chime SDK SIP media applications. Developers can also order and
    manage phone numbers, create and manage Voice Connectors and SIP media
    applications, and run voice analytics.</p>
paths:
  /voice-connectors/{voiceConnectorId}?operation=associate-phone-numbers:
    POST:
      summary: Associatephonenumberswithvoiceconnector
      description: >-
        Associates phone numbers with the specified Amazon Chime SDK Voice
        Connector.
      operationId: amazonWebServicesAssociatePhoneNumbersWithVoiceConnector
  /voice-connector-groups/{voiceConnectorGroupId}?operation=associate-phone-numbers:
    POST:
      summary: Associatephonenumberswithvoiceconnectorgroup
      description: >-
        Associates phone numbers with the specified Amazon Chime SDK Voice
        Connector group.
      operationId: amazonWebServicesAssociatePhoneNumbersWithVoiceConnectorGroup
  /phone-numbers?operation=batch-delete:
    POST:
      summary: Batchdeletephonenumber
      description: ' Moves phone numbers into the Deletion queue. Phone numbers must be disassociated from any users or Amazon Chime SDK Voice Connectors before they can be deleted.   Phone numbers remain in the Deletion queue for 7 days before they are deleted permanently. '
      operationId: amazonWebServicesBatchDeletePhoneNumber
  /phone-numbers?operation=batch-update:
    POST:
      summary: Batchupdatephonenumber
      description: Updates one or more phone numbers.
      operationId: amazonWebServicesBatchUpdatePhoneNumber
  /phone-number-orders:
    GET:
      summary: Listphonenumberorders
      description: Lists the phone numbers for an administrator's Amazon Chime SDK account.
      operationId: amazonWebServicesListPhoneNumberOrders
  /voice-connectors/{voiceConnectorId}/proxy-sessions:
    GET:
      summary: Listproxysessions
      description: >-
        Lists the proxy sessions for the specified Amazon Chime SDK Voice
        Connector.
      operationId: amazonWebServicesListProxySessions
  /sip-media-applications:
    GET:
      summary: Listsipmediaapplications
      description: Lists the SIP media applications under the administrator's AWS account.
      operationId: amazonWebServicesListSipMediaApplications
  /sip-media-applications/{sipMediaApplicationId}/calls:
    POST:
      summary: Createsipmediaapplicationcall
      description: >-
        Creates an outbound call to a phone number from the phone number
        specified in the request, and it invokes the endpoint of the specified
        sipMediaApplicationId.
      operationId: amazonWebServicesCreateSipMediaApplicationCall
  /sip-rules:
    GET:
      summary: Listsiprules
      description: Lists the SIP rules under the administrator's AWS account.
      operationId: amazonWebServicesListSipRules
  /voice-connectors:
    GET:
      summary: Listvoiceconnectors
      description: >-
        Lists the Amazon Chime SDK Voice Connectors in the administrators AWS
        account.
      operationId: amazonWebServicesListVoiceConnectors
  /voice-connector-groups:
    GET:
      summary: Listvoiceconnectorgroups
      description: >-
        Lists the Amazon Chime SDK Voice Connector groups in the administrator's
        AWS account.
      operationId: amazonWebServicesListVoiceConnectorGroups
  /voice-profiles:
    GET:
      summary: Listvoiceprofiles
      description: Lists the voice profiles in a voice profile domain.
      operationId: amazonWebServicesListVoiceProfiles
  /voice-profile-domains:
    GET:
      summary: Listvoiceprofiledomains
      description: >-
        Lists the specified voice profile domains in the administrator's AWS
        account. 
      operationId: amazonWebServicesListVoiceProfileDomains
  /phone-numbers/{phoneNumberId}:
    POST:
      summary: Updatephonenumber
      description: >-
        Updates phone number details, such as product type or calling name, for
        the specified phone number ID. You can update one phone number detail at
        a time. For example, you can update either the product type or the
        calling name in one action. For numbers outside the U.S., you must use
        the Amazon Chime SDK SIP Media Application Dial-In product type. Updates
        to outbound calling names can take 72 hours to complete. Pending updates
        to outbound calling names must be complete before you can request
        another update.
      operationId: amazonWebServicesUpdatePhoneNumber
  /voice-connectors/{voiceConnectorId}/proxy-sessions/{proxySessionId}:
    POST:
      summary: Updateproxysession
      description: >-
        Updates the specified proxy session details, such as voice or SMS
        capabilities.
      operationId: amazonWebServicesUpdateProxySession
  /sip-media-applications/{sipMediaApplicationId}:
    PUT:
      summary: Updatesipmediaapplication
      description: Updates the details of the specified SIP media application.
      operationId: amazonWebServicesUpdateSipMediaApplication
  /sip-rules/{sipRuleId}:
    PUT:
      summary: Updatesiprule
      description: Updates the details of the specified SIP rule.
      operationId: amazonWebServicesUpdateSipRule
  /voice-connectors/{voiceConnectorId}:
    PUT:
      summary: Updatevoiceconnector
      description: Updates the details for the specified Amazon Chime SDK Voice Connector.
      operationId: amazonWebServicesUpdateVoiceConnector
  /voice-connectors/{voiceConnectorId}/emergency-calling-configuration:
    PUT:
      summary: Putvoiceconnectoremergencycallingconfiguration
      description: Updates a Voice Connector's emergency calling configuration.
      operationId: amazonWebServicesPutVoiceConnectorEmergencyCallingConfiguration
  /voice-connector-groups/{voiceConnectorGroupId}:
    PUT:
      summary: Updatevoiceconnectorgroup
      description: >-
        Updates the settings for the specified Amazon Chime SDK Voice Connector
        group.
      operationId: amazonWebServicesUpdateVoiceConnectorGroup
  /voice-connectors/{voiceConnectorId}/origination:
    PUT:
      summary: Putvoiceconnectororigination
      description: Updates a Voice Connector's origination settings.
      operationId: amazonWebServicesPutVoiceConnectorOrigination
  /voice-connectors/{voiceConnectorId}/programmable-numbers/proxy:
    PUT:
      summary: Putvoiceconnectorproxy
      description: >-
        Puts the specified proxy configuration to the specified Amazon Chime SDK
        Voice Connector.
      operationId: amazonWebServicesPutVoiceConnectorProxy
  /voice-connectors/{voiceConnectorId}/streaming-configuration:
    PUT:
      summary: Putvoiceconnectorstreamingconfiguration
      description: Updates a Voice Connector's streaming configuration settings.
      operationId: amazonWebServicesPutVoiceConnectorStreamingConfiguration
  /voice-connectors/{voiceConnectorId}/termination:
    PUT:
      summary: Putvoiceconnectortermination
      description: Updates a Voice Connector's termination settings.
      operationId: amazonWebServicesPutVoiceConnectorTermination
  /voice-connectors/{voiceConnectorId}/termination/credentials?operation=delete:
    POST:
      summary: Deletevoiceconnectorterminationcredentials
      description: >-
        Deletes the specified SIP credentials used by your equipment to
        authenticate during call termination.
      operationId: amazonWebServicesDeleteVoiceConnectorTerminationCredentials
  /voice-profiles/{VoiceProfileId}:
    PUT:
      summary: Updatevoiceprofile
      description: >-
        Updates the specified voice profile’s voice print and refreshes its
        expiration timestamp.  As a condition of using this feature, you
        acknowledge that the collection, use, storage, and retention of your
        caller’s biometric identifiers and biometric information (“biometric
        data”) in the form of a digital voiceprint requires the caller’s
        informed consent via a written release. Such consent is required under
        various state laws, including biometrics laws in Illinois, Texas,
        Washington and other state privacy laws. You must provide a written
        release to each caller through a process that clearly reflects each
        caller’s informed consent before using Amazon Chime SDK Voice Insights
        service, as required under the terms of your agreement with AWS
        governing your use of the service. 
      operationId: amazonWebServicesUpdateVoiceProfile
  /voice-profile-domains/{VoiceProfileDomainId}:
    PUT:
      summary: Updatevoiceprofiledomain
      description: Updates the settings for the specified voice profile domain.
      operationId: amazonWebServicesUpdateVoiceProfileDomain
  /voice-connectors/{voiceConnectorId}?operation=disassociate-phone-numbers:
    POST:
      summary: Disassociatephonenumbersfromvoiceconnector
      description: >-
        Disassociates the specified phone numbers from the specified Amazon
        Chime SDK Voice Connector.
      operationId: amazonWebServicesDisassociatePhoneNumbersFromVoiceConnector
  /voice-connector-groups/{voiceConnectorGroupId}?operation=disassociate-phone-numbers:
    POST:
      summary: Disassociatephonenumbersfromvoiceconnectorgroup
      description: >-
        Disassociates the specified phone numbers from the specified Amazon
        Chime SDK Voice Connector group.
      operationId: amazonWebServicesDisassociatePhoneNumbersFromVoiceConnectorGroup
  /settings:
    PUT:
      summary: Updateglobalsettings
      description: >-
        Updates global settings for the Amazon Chime SDK Voice Connectors in an
        AWS account.
      operationId: amazonWebServicesUpdateGlobalSettings
  /phone-number-orders/{phoneNumberOrderId}:
    GET:
      summary: Getphonenumberorder
      description: >-
        Retrieves details for the specified phone number order, such as the
        order creation timestamp, phone numbers in E.164 format, product type,
        and order status.
      operationId: amazonWebServicesGetPhoneNumberOrder
  /settings/phone-number:
    PUT:
      summary: Updatephonenumbersettings
      description: >-
        Updates the phone number settings for the administrator's AWS account,
        such as the default outbound calling name. You can update the default
        outbound calling name once every seven days. Outbound calling names can
        take up to 72 hours to update.
      operationId: amazonWebServicesUpdatePhoneNumberSettings
  /sip-media-applications/{sipMediaApplicationId}/alexa-skill-configuration:
    PUT:
      summary: Putsipmediaapplicationalexaskillconfiguration
      description: Updates the Alexa Skill configuration for the SIP media application.
      operationId: amazonWebServicesPutSipMediaApplicationAlexaSkillConfiguration
  /sip-media-applications/{sipMediaApplicationId}/logging-configuration:
    PUT:
      summary: Putsipmediaapplicationloggingconfiguration
      description: >-
        Updates the logging configuration for the specified SIP media
        application.
      operationId: amazonWebServicesPutSipMediaApplicationLoggingConfiguration
  /voice-connectors/{VoiceConnectorId}/speaker-search-tasks/{SpeakerSearchTaskId}:
    GET:
      summary: Getspeakersearchtask
      description: Retrieves the details of the specified speaker search task.
      operationId: amazonWebServicesGetSpeakerSearchTask
  /voice-connectors/{voiceConnectorId}/logging-configuration:
    PUT:
      summary: Putvoiceconnectorloggingconfiguration
      description: Updates a Voice Connector's logging configuration.
      operationId: amazonWebServicesPutVoiceConnectorLoggingConfiguration
  /voice-connectors/{voiceConnectorId}/termination/health:
    GET:
      summary: Getvoiceconnectorterminationhealth
      description: >-
        Retrieves information about the last time a SIP OPTIONS ping was
        received from your SIP infrastructure for the specified Amazon Chime SDK
        Voice Connector.
      operationId: amazonWebServicesGetVoiceConnectorTerminationHealth
  /voice-connectors/{VoiceConnectorId}/voice-tone-analysis-tasks/{VoiceToneAnalysisTaskId}:
    GET:
      summary: Getvoicetoneanalysistask
      description: Retrieves the details of a voice tone analysis task.
      operationId: amazonWebServicesGetVoiceToneAnalysisTask
  /voice-connector-regions:
    GET:
      summary: Listavailablevoiceconnectorregions
      description: >-
        Lists the available AWS Regions in which you can create an Amazon Chime
        SDK Voice Connector.
      operationId: amazonWebServicesListAvailableVoiceConnectorRegions
  /phone-numbers:
    GET:
      summary: Listphonenumbers
      description: >-
        Lists the phone numbers for the specified Amazon Chime SDK account,
        Amazon Chime SDK user, Amazon Chime SDK Voice Connector, or Amazon Chime
        SDK Voice Connector group.
      operationId: amazonWebServicesListPhoneNumbers
  /phone-number-countries:
    GET:
      summary: Listsupportedphonenumbercountries
      description: Lists the countries that you can order phone numbers from.
      operationId: amazonWebServicesListSupportedPhoneNumberCountries
  /tags:
    GET:
      summary: Listtagsforresource
      description: Returns a list of the tags in a given resource.
      operationId: amazonWebServicesListTagsForResource
  /voice-connectors/{voiceConnectorId}/termination/credentials:
    GET:
      summary: Listvoiceconnectorterminationcredentials
      description: >-
        Lists the SIP credentials for the specified Amazon Chime SDK Voice
        Connector.
      operationId: amazonWebServicesListVoiceConnectorTerminationCredentials
  /voice-connectors/{voiceConnectorId}/termination/credentials?operation=put:
    POST:
      summary: Putvoiceconnectorterminationcredentials
      description: Updates a Voice Connector's termination credentials.
      operationId: amazonWebServicesPutVoiceConnectorTerminationCredentials
  /phone-numbers/{phoneNumberId}?operation=restore:
    POST:
      summary: Restorephonenumber
      description: Restores a deleted phone number.
      operationId: amazonWebServicesRestorePhoneNumber
  /search?type=phone-numbers:
    GET:
      summary: Searchavailablephonenumbers
      description: Searches the provisioned phone numbers in an organization.
      operationId: amazonWebServicesSearchAvailablePhoneNumbers
  /voice-connectors/{VoiceConnectorId}/speaker-search-tasks:
    POST:
      summary: Startspeakersearchtask
      description: >-
        Starts a speaker search task.  Before starting any speaker search tasks,
        you must provide all notices and obtain all consents from the speaker as
        required under applicable privacy and biometrics laws, and as required
        under the AWS service terms for the Amazon Chime SDK. 
      operationId: amazonWebServicesStartSpeakerSearchTask
  /voice-connectors/{VoiceConnectorId}/voice-tone-analysis-tasks:
    POST:
      summary: Startvoicetoneanalysistask
      description: >-
        Starts a voice tone analysis task. For more information about voice tone
        analysis, see Using Amazon Chime SDK voice analytics in the Amazon Chime
        SDK Developer Guide.  Before starting any voice tone analysis tasks, you
        must provide all notices and obtain all consents from the speaker as
        required under applicable privacy and biometrics laws, and as required
        under the AWS service terms for the Amazon Chime SDK. 
      operationId: amazonWebServicesStartVoiceToneAnalysisTask
  /voice-connectors/{VoiceConnectorId}/speaker-search-tasks/{SpeakerSearchTaskId}?operation=stop:
    POST:
      summary: Stopspeakersearchtask
      description: Stops a speaker search task.
      operationId: amazonWebServicesStopSpeakerSearchTask
  /voice-connectors/{VoiceConnectorId}/voice-tone-analysis-tasks/{VoiceToneAnalysisTaskId}?operation=stop:
    POST:
      summary: Stopvoicetoneanalysistask
      description: Stops a voice tone analysis task.
      operationId: amazonWebServicesStopVoiceToneAnalysisTask
  /tags?operation=tag-resource:
    POST:
      summary: Tagresource
      description: Adds a tag to the specified resource.
      operationId: amazonWebServicesTagResource
  /tags?operation=untag-resource:
    POST:
      summary: Untagresource
      description: Removes tags from a resource.
      operationId: amazonWebServicesUntagResource
  /sip-media-applications/{sipMediaApplicationId}/calls/{transactionId}:
    POST:
      summary: Updatesipmediaapplicationcall
      description: >-
        Invokes the AWS Lambda function associated with the SIP media
        application and transaction ID in an update request. The Lambda function
        can then return a new set of actions.
      operationId: amazonWebServicesUpdateSipMediaApplicationCall
  /emergency-calling/address:
    POST:
      summary: Validatee911address
      description: >-
        Validates an address to be used for 911 calls made with Amazon Chime SDK
        Voice Connectors. You can use validated addresses in a Presence
        Information Data Format Location Object file that you include in SIP
        requests. That helps ensure that addresses are routed to the appropriate
        Public Safety Answering Point.
      operationId: amazonWebServicesValidateE911Address
tags: []
