openapi: 3.1.0
info:
  title: chime-sdk-messaging
  description: >-
    <p>The Amazon Chime SDK messaging APIs in this section allow software
    developers to send and receive messages in custom messaging applications.
    These APIs depend on the frameworks provided by the Amazon Chime SDK
    identity APIs. For more information about the messaging APIs, see <a
    href="https://docs.aws.amazon.com/chime/latest/APIReference/API_Operations_Amazon_Chime_SDK_Messaging.html">Amazon
    Chime SDK messaging</a>.</p>
paths:
  /channels/{channelArn}/channel-flow:
    PUT:
      summary: Associatechannelflow
      description: >-
        Associates a channel flow with a channel. Once associated, all messages
        to that channel go through channel flow processors. To stop processing,
        use the DisassociateChannelFlow API.  Only administrators or channel
        moderators can associate a channel flow. The x-amz-chime-bearer request
        header is mandatory. Use the ARN of the AppInstanceUser or
        AppInstanceBot that makes the API call as the value in the header. 
      operationId: amazonWebServicesAssociateChannelFlow
  /channels/{channelArn}/memberships?operation=batch-create:
    POST:
      summary: Batchcreatechannelmembership
      description: 'Adds a specified number of users and bots to a channel. '
      operationId: amazonWebServicesBatchCreateChannelMembership
  /channels/{channelArn}?operation=channel-flow-callback:
    POST:
      summary: Channelflowcallback
      description: >-
        Calls back Amazon Chime SDK messaging with a processing response
        message. This should be invoked from the processor Lambda. This is a
        developer API. You can return one of the following processing
        responses:   Update message content or metadata   Deny a message   Make
        no changes to the message  
      operationId: amazonWebServicesChannelFlowCallback
  /channels:
    GET:
      summary: Listchannels
      description: >-
        Lists all Channels created under a single Chime App as a paginated list.
        You can specify filters to narrow results.  Functionality &amp;
        restrictions    Use privacy = PUBLIC to retrieve all public channels in
        the account.   Only an AppInstanceAdmin can set privacy = PRIVATE to
        list the private channels in an account.    The x-amz-chime-bearer
        request header is mandatory. Use the ARN of the AppInstanceUser or
        AppInstanceBot that makes the API call as the value in the header. 
      operationId: amazonWebServicesListChannels
  /channels/{channelArn}/bans:
    GET:
      summary: Listchannelbans
      description: >-
        Lists all the users and bots banned from a particular channel.  The
        x-amz-chime-bearer request header is mandatory. Use the ARN of the
        AppInstanceUser or AppInstanceBot that makes the API call as the value
        in the header. 
      operationId: amazonWebServicesListChannelBans
  /channel-flows:
    GET:
      summary: Listchannelflows
      description: >-
        Returns a paginated lists of all the channel flows created under a
        single Chime. This is a developer API.
      operationId: amazonWebServicesListChannelFlows
  /channels/{channelArn}/memberships:
    GET:
      summary: Listchannelmemberships
      description: >-
        Lists all channel memberships in a channel.  The x-amz-chime-bearer
        request header is mandatory. Use the ARN of the AppInstanceUser or
        AppInstanceBot that makes the API call as the value in the header.  If
        you want to list the channels to which a specific app instance user
        belongs, see the ListChannelMembershipsForAppInstanceUser API.
      operationId: amazonWebServicesListChannelMemberships
  /channels/{channelArn}/moderators:
    GET:
      summary: Listchannelmoderators
      description: >-
        Lists all the moderators for a channel.  The x-amz-chime-bearer request
        header is mandatory. Use the ARN of the AppInstanceUser or
        AppInstanceBot that makes the API call as the value in the header. 
      operationId: amazonWebServicesListChannelModerators
  /channels/{channelArn}:
    PUT:
      summary: Updatechannel
      description: >-
        Update a channel's attributes.  Restriction: You can't change a
        channel's privacy.   The x-amz-chime-bearer request header is mandatory.
        Use the ARN of the AppInstanceUser or AppInstanceBot that makes the API
        call as the value in the header. 
      operationId: amazonWebServicesUpdateChannel
  /channels/{channelArn}/bans/{memberArn}:
    GET:
      summary: Describechannelban
      description: >-
        Returns the full details of a channel ban.  The x-amz-chime-bearer
        request header is mandatory. Use the ARN of the AppInstanceUser or
        AppInstanceBot that makes the API call as the value in the header. 
      operationId: amazonWebServicesDescribeChannelBan
  /channel-flows/{channelFlowArn}:
    PUT:
      summary: Updatechannelflow
      description: Updates channel flow attributes. This is a developer API.
      operationId: amazonWebServicesUpdateChannelFlow
  /channels/{channelArn}/memberships/{memberArn}:
    GET:
      summary: Describechannelmembership
      description: >-
        Returns the full details of a user's channel membership.  The
        x-amz-chime-bearer request header is mandatory. Use the ARN of the
        AppInstanceUser or AppInstanceBot that makes the API call as the value
        in the header. 
      operationId: amazonWebServicesDescribeChannelMembership
  /channels/{channelArn}/messages/{messageId}:
    PUT:
      summary: Updatechannelmessage
      description: >-
        Updates the content of a message.  The x-amz-chime-bearer request header
        is mandatory. Use the ARN of the AppInstanceUser or AppInstanceBot that
        makes the API call as the value in the header. 
      operationId: amazonWebServicesUpdateChannelMessage
  /channels/{channelArn}/moderators/{channelModeratorArn}:
    GET:
      summary: Describechannelmoderator
      description: >-
        Returns the full details of a single ChannelModerator.  The
        x-amz-chime-bearer request header is mandatory. Use the
        AppInstanceUserArn of the user that makes the API call as the value in
        the header. 
      operationId: amazonWebServicesDescribeChannelModerator
  /app-instances/{appInstanceArn}/streaming-configurations:
    PUT:
      summary: Putmessagingstreamingconfigurations
      description: >-
        Sets the data streaming configuration for an AppInstance. For more
        information, see Streaming messaging data in the Amazon Chime SDK
        Developer Guide.
      operationId: amazonWebServicesPutMessagingStreamingConfigurations
  /channels/{channelArn}?scope=app-instance-user-membership:
    GET:
      summary: Describechannelmembershipforappinstanceuser
      description: ' Returns the details of a channel based on the membership of the specified AppInstanceUser or AppInstanceBot.  The x-amz-chime-bearer request header is mandatory. Use the ARN of the AppInstanceUser or AppInstanceBot that makes the API call as the value in the header. '
      operationId: amazonWebServicesDescribeChannelMembershipForAppInstanceUser
  /channels/{channelArn}?scope=app-instance-user-moderated-channel:
    GET:
      summary: Describechannelmoderatedbyappinstanceuser
      description: >-
        Returns the full details of a channel moderated by the specified
        AppInstanceUser or AppInstanceBot.  The x-amz-chime-bearer request
        header is mandatory. Use the ARN of the AppInstanceUser or
        AppInstanceBot that makes the API call as the value in the header. 
      operationId: amazonWebServicesDescribeChannelModeratedByAppInstanceUser
  /channels/{channelArn}/channel-flow/{channelFlowArn}:
    DELETE:
      summary: Disassociatechannelflow
      description: >-
        Disassociates a channel flow from all its channels. Once disassociated,
        all messages to that channel stop going through the channel flow
        processor.  Only administrators or channel moderators can disassociate a
        channel flow. The x-amz-chime-bearer request header is mandatory. Use
        the ARN of the AppInstanceUser or AppInstanceBot that makes the API call
        as the value in the header. 
      operationId: amazonWebServicesDisassociateChannelFlow
  /channels/{channelArn}/memberships/{memberArn}/preferences:
    PUT:
      summary: Putchannelmembershippreferences
      description: >-
        Sets the membership preferences of an AppInstanceUser or AppInstanceBot
        for the specified channel. The user or bot must be a member of the
        channel. Only the user or bot who owns the membership can set
        preferences. Users or bots in the AppInstanceAdmin and channel moderator
        roles can't set preferences for other users. Banned users or bots can't
        set membership preferences for the channel from which they are banned. 
        The x-amz-chime-bearer request header is mandatory. Use the ARN of an
        AppInstanceUser or AppInstanceBot that makes the API call as the value
        in the header. 
      operationId: amazonWebServicesPutChannelMembershipPreferences
  /channels/{channelArn}/messages/{messageId}?scope=message-status:
    GET:
      summary: Getchannelmessagestatus
      description: >-
        Gets message status for a specified messageId. Use this API to determine
        the intermediate status of messages going through channel flow
        processing. The API provides an alternative to retrieving message status
        if the event was not received because a client wasn't connected to a
        websocket.  Messages can have any one of these statuses.  SENT  Message
        processed successfully  PENDING  Ongoing processing  FAILED  Processing
        failed  DENIED  Message denied by the processor      This API does not
        return statuses for denied messages, because we don't store them once
        the processor denies them.    Only the message sender can invoke this
        API.   The x-amz-chime-bearer request header is mandatory. Use the ARN
        of the AppInstanceUser or AppInstanceBot that makes the API call as the
        value in the header.   
      operationId: amazonWebServicesGetChannelMessageStatus
  /endpoints/messaging-session:
    GET:
      summary: Getmessagingsessionendpoint
      description: The details of the endpoint for the messaging session.
      operationId: amazonWebServicesGetMessagingSessionEndpoint
  /channels?scope=app-instance-user-memberships:
    GET:
      summary: Listchannelmembershipsforappinstanceuser
      description: ' Lists all channels that an AppInstanceUser or AppInstanceBot is a part of. Only an AppInstanceAdmin can call the API with a user ARN that is not their own.   The x-amz-chime-bearer request header is mandatory. Use the ARN of the AppInstanceUser or AppInstanceBot that makes the API call as the value in the header. '
      operationId: amazonWebServicesListChannelMembershipsForAppInstanceUser
  /channels/{channelArn}/messages:
    POST:
      summary: Sendchannelmessage
      description: >-
        Sends a message to a particular channel that the member is a part of. 
        The x-amz-chime-bearer request header is mandatory. Use the ARN of the
        AppInstanceUser or AppInstanceBot that makes the API call as the value
        in the header. Also, STANDARD messages can be up to 4KB in size and
        contain metadata. Metadata is arbitrary, and you can use it in a variety
        of ways, such as containing a link to an attachment.  CONTROL messages
        are limited to 30 bytes and do not contain metadata. 
      operationId: amazonWebServicesSendChannelMessage
  /channels?scope=channel-flow-associations:
    GET:
      summary: Listchannelsassociatedwithchannelflow
      description: >-
        Lists all channels associated with a specified channel flow. You can
        associate a channel flow with multiple channels, but you can only
        associate a channel with one channel flow. This is a developer API.
      operationId: amazonWebServicesListChannelsAssociatedWithChannelFlow
  /channels?scope=app-instance-user-moderated-channels:
    GET:
      summary: Listchannelsmoderatedbyappinstanceuser
      description: >-
        A list of the channels moderated by an AppInstanceUser.  The
        x-amz-chime-bearer request header is mandatory. Use the ARN of the
        AppInstanceUser or AppInstanceBot that makes the API call as the value
        in the header. 
      operationId: amazonWebServicesListChannelsModeratedByAppInstanceUser
  /channels/{channelArn}/subchannels:
    GET:
      summary: Listsubchannels
      description: >-
        Lists all the SubChannels in an elastic channel when given a channel ID.
        Available only to the app instance admins and channel moderators of
        elastic channels.
      operationId: amazonWebServicesListSubChannels
  /tags:
    GET:
      summary: Listtagsforresource
      description: Lists the tags applied to an Amazon Chime SDK messaging resource.
      operationId: amazonWebServicesListTagsForResource
  /channels/{channelArn}/expiration-settings:
    PUT:
      summary: Putchannelexpirationsettings
      description: >-
        Sets the number of days before the channel is automatically deleted.   
        A background process deletes expired channels within 6 hours of
        expiration. Actual deletion times may vary.   Expired channels that have
        not yet been deleted appear as active, and you can update their
        expiration settings. The system honors the new settings.   The
        x-amz-chime-bearer request header is mandatory. Use the ARN of the
        AppInstanceUser or AppInstanceBot that makes the API call as the value
        in the header.   
      operationId: amazonWebServicesPutChannelExpirationSettings
  /channels/{channelArn}/messages/{messageId}?operation=redact:
    POST:
      summary: Redactchannelmessage
      description: >-
        Redacts message content, but not metadata. The message exists in the
        back end, but the action returns null content, and the state shows as
        redacted.  The x-amz-chime-bearer request header is mandatory. Use the
        ARN of the AppInstanceUser or AppInstanceBot that makes the API call as
        the value in the header. 
      operationId: amazonWebServicesRedactChannelMessage
  /channels?operation=search:
    POST:
      summary: Searchchannels
      description: >-
        Allows the ChimeBearer to search channels by channel members. Users or
        bots can search across the channels that they belong to. Users in the
        AppInstanceAdmin role can search across all channels. The
        x-amz-chime-bearer request header is mandatory. Use the ARN of the
        AppInstanceUser or AppInstanceBot that makes the API call as the value
        in the header.
      operationId: amazonWebServicesSearchChannels
  /tags?operation=tag-resource:
    POST:
      summary: Tagresource
      description: >-
        Applies the specified tags to the specified Amazon Chime SDK messaging
        resource.
      operationId: amazonWebServicesTagResource
  /tags?operation=untag-resource:
    POST:
      summary: Untagresource
      description: >-
        Removes the specified tags from the specified Amazon Chime SDK messaging
        resource.
      operationId: amazonWebServicesUntagResource
  /channels/{channelArn}/readMarker:
    PUT:
      summary: Updatechannelreadmarker
      description: >-
        The details of the time when a user last read messages in a channel. 
        The x-amz-chime-bearer request header is mandatory. Use the ARN of the
        AppInstanceUser or AppInstanceBot that makes the API call as the value
        in the header. 
      operationId: amazonWebServicesUpdateChannelReadMarker
tags: []
