openapi: 3.1.0
info:
  title: chime-sdk-media-pipelines
  description: >-
    <p>The Amazon Chime SDK media pipeline APIs in this section allow software
    developers to create Amazon Chime SDK media pipelines that capture,
    concatenate, or stream your Amazon Chime SDK meetings. For more information
    about media pipelines, see <a
    href="https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_Operations_Amazon_Chime_SDK_Media_Pipelines.html">Amazon
    Chime SDK media pipelines</a>. </p>
paths:
  /sdk-media-capture-pipelines:
    GET:
      summary: Listmediacapturepipelines
      description: Returns a list of media pipelines.
      operationId: amazonWebServicesListMediaCapturePipelines
  /sdk-media-concatenation-pipelines:
    POST:
      summary: Createmediaconcatenationpipeline
      description: Creates a media concatenation pipeline.
      operationId: amazonWebServicesCreateMediaConcatenationPipeline
  /media-insights-pipelines:
    POST:
      summary: Createmediainsightspipeline
      description: Creates a media insights pipeline.
      operationId: amazonWebServicesCreateMediaInsightsPipeline
  /media-insights-pipeline-configurations:
    GET:
      summary: Listmediainsightspipelineconfigurations
      description: Lists the available media insights pipeline configurations.
      operationId: amazonWebServicesListMediaInsightsPipelineConfigurations
  /sdk-media-live-connector-pipelines:
    POST:
      summary: Createmedialiveconnectorpipeline
      description: Creates a media live connector pipeline in an Amazon Chime SDK meeting.
      operationId: amazonWebServicesCreateMediaLiveConnectorPipeline
  /media-pipeline-kinesis-video-stream-pools:
    GET:
      summary: Listmediapipelinekinesisvideostreampools
      description: Lists the video stream pools in the media pipeline.
      operationId: amazonWebServicesListMediaPipelineKinesisVideoStreamPools
  /sdk-media-stream-pipelines:
    POST:
      summary: Createmediastreampipeline
      description: Creates a streaming media pipeline.
      operationId: amazonWebServicesCreateMediaStreamPipeline
  /sdk-media-capture-pipelines/{mediaPipelineId}:
    GET:
      summary: Getmediacapturepipeline
      description: Gets an existing media pipeline.
      operationId: amazonWebServicesGetMediaCapturePipeline
  /media-insights-pipeline-configurations/{identifier}:
    PUT:
      summary: Updatemediainsightspipelineconfiguration
      description: Updates the media insights pipeline's configuration settings.
      operationId: amazonWebServicesUpdateMediaInsightsPipelineConfiguration
  /sdk-media-pipelines/{mediaPipelineId}:
    GET:
      summary: Getmediapipeline
      description: Gets an existing media pipeline.
      operationId: amazonWebServicesGetMediaPipeline
  /media-pipeline-kinesis-video-stream-pools/{identifier}:
    PUT:
      summary: Updatemediapipelinekinesisvideostreampool
      description: Updates an Kinesis video stream pool in a media pipeline.
      operationId: amazonWebServicesUpdateMediaPipelineKinesisVideoStreamPool
  /media-insights-pipelines/{identifier}/speaker-search-tasks/{speakerSearchTaskId}:
    GET:
      summary: Getspeakersearchtask
      description: Retrieves the details of the specified speaker search task.
      operationId: amazonWebServicesGetSpeakerSearchTask
  /media-insights-pipelines/{identifier}/voice-tone-analysis-tasks/{voiceToneAnalysisTaskId}:
    GET:
      summary: Getvoicetoneanalysistask
      description: Retrieves the details of a voice tone analysis task.
      operationId: amazonWebServicesGetVoiceToneAnalysisTask
  /sdk-media-pipelines:
    GET:
      summary: Listmediapipelines
      description: Returns a list of media pipelines.
      operationId: amazonWebServicesListMediaPipelines
  /tags:
    GET:
      summary: Listtagsforresource
      description: Lists the tags available for a media pipeline.
      operationId: amazonWebServicesListTagsForResource
  /media-insights-pipelines/{identifier}/speaker-search-tasks?operation=start:
    POST:
      summary: Startspeakersearchtask
      description: >-
        Starts a speaker search task.  Before starting any speaker search tasks,
        you must provide all notices and obtain all consents from the speaker as
        required under applicable privacy and biometrics laws, and as required
        under the AWS service terms for the Amazon Chime SDK. 
      operationId: amazonWebServicesStartSpeakerSearchTask
  /media-insights-pipelines/{identifier}/voice-tone-analysis-tasks?operation=start:
    POST:
      summary: Startvoicetoneanalysistask
      description: >-
        Starts a voice tone analysis task. For more information about voice tone
        analysis, see Using Amazon Chime SDK voice analytics in the Amazon Chime
        SDK Developer Guide.  Before starting any voice tone analysis tasks, you
        must provide all notices and obtain all consents from the speaker as
        required under applicable privacy and biometrics laws, and as required
        under the AWS service terms for the Amazon Chime SDK. 
      operationId: amazonWebServicesStartVoiceToneAnalysisTask
  /media-insights-pipelines/{identifier}/speaker-search-tasks/{speakerSearchTaskId}?operation=stop:
    POST:
      summary: Stopspeakersearchtask
      description: Stops a speaker search task.
      operationId: amazonWebServicesStopSpeakerSearchTask
  /media-insights-pipelines/{identifier}/voice-tone-analysis-tasks/{voiceToneAnalysisTaskId}?operation=stop:
    POST:
      summary: Stopvoicetoneanalysistask
      description: Stops a voice tone analysis task.
      operationId: amazonWebServicesStopVoiceToneAnalysisTask
  /tags?operation=tag-resource:
    POST:
      summary: Tagresource
      description: >-
        The ARN of the media pipeline that you want to tag. Consists of the
        pipeline's endpoint region, resource ID, and pipeline ID.
      operationId: amazonWebServicesTagResource
  /tags?operation=untag-resource:
    POST:
      summary: Untagresource
      description: Removes any tags from a media pipeline.
      operationId: amazonWebServicesUntagResource
  /media-insights-pipeline-status/{identifier}:
    PUT:
      summary: Updatemediainsightspipelinestatus
      description: Updates the status of a media insights pipeline.
      operationId: amazonWebServicesUpdateMediaInsightsPipelineStatus
tags: []
