openapi: 3.1.0
info:
  title: chime-sdk-meetings
  description: >-
    <p>The Amazon Chime SDK meetings APIs in this section allow software
    developers to create Amazon Chime SDK meetings, set the Amazon Web Services
    Regions for meetings, create and manage users, and send and receive meeting
    notifications. For more information about the meeting APIs, see <a
    href="https://docs.aws.amazon.com/chime/latest/APIReference/API_Operations_Amazon_Chime_SDK_Meetings.html">Amazon
    Chime SDK meetings</a>.</p>
paths:
  /meetings/{MeetingId}/attendees?operation=batch-create:
    POST:
      summary: Batchcreateattendee
      description: >-
        Creates up to 100 attendees for an active Amazon Chime SDK meeting. For
        more information about the Amazon Chime SDK, see Using the Amazon Chime
        SDK in the Amazon Chime Developer Guide.
      operationId: amazonWebServicesBatchCreateAttendee
  /meetings/{MeetingId}/attendees/capabilities?operation=batch-update-except:
    PUT:
      summary: Batchupdateattendeecapabilitiesexcept
      description: >-
        Updates AttendeeCapabilities except the capabilities listed in an
        ExcludedAttendeeIds table.  You use the capabilities with a set of
        values that control what the capabilities can do, such as SendReceive
        data. For more information about those values, see .  When using
        capabilities, be aware of these corner cases:   If you specify
        MeetingFeatures:Video:MaxResolution:None when you create a meeting, all
        API requests that include SendReceive, Send, or Receive for
        AttendeeCapabilities:Video will be rejected with ValidationError 400.  
        If you specify MeetingFeatures:Content:MaxResolution:None when you
        create a meeting, all API requests that include SendReceive, Send, or
        Receive for AttendeeCapabilities:Content will be rejected with
        ValidationError 400.   You can't set content capabilities to SendReceive
        or Receive unless you also set video capabilities to SendReceive or
        Receive. If you don't set the video capability to receive, the response
        will contain an HTTP 400 Bad Request status code. However, you can set
        your video capability to receive and you set your content capability to
        not receive.   When you change an audio capability from None or Receive
        to Send or SendReceive , and if the attendee left their microphone
        unmuted, audio will flow from the attendee to the other meeting
        participants.   When you change a video or content capability from None
        or Receive to Send or SendReceive , and if the attendee turned on their
        video or content streams, remote attendees can receive those streams,
        but only after media renegotiation between the client and the Amazon
        Chime back-end server.  
      operationId: amazonWebServicesBatchUpdateAttendeeCapabilitiesExcept
  /meetings/{MeetingId}/attendees:
    GET:
      summary: Listattendees
      description: ' Lists the attendees for the specified Amazon Chime SDK meeting. For more information about the Amazon Chime SDK, see Using the Amazon Chime SDK in the Amazon Chime Developer Guide. '
      operationId: amazonWebServicesListAttendees
  /meetings:
    POST:
      summary: Createmeeting
      description: >-
        Creates a new Amazon Chime SDK meeting in the specified media Region
        with no initial attendees. For more information about specifying media
        Regions, see Amazon Chime SDK Media Regions in the Amazon Chime
        Developer Guide. For more information about the Amazon Chime SDK, see
        Using the Amazon Chime SDK in the Amazon Chime Developer Guide. 
      operationId: amazonWebServicesCreateMeeting
  /meetings?operation=create-attendees:
    POST:
      summary: Createmeetingwithattendees
      description: ' Creates a new Amazon Chime SDK meeting in the specified media Region, with attendees. For more information about specifying media Regions, see Amazon Chime SDK Media Regions in the Amazon Chime Developer Guide. For more information about the Amazon Chime SDK, see Using the Amazon Chime SDK in the Amazon Chime Developer Guide. '
      operationId: amazonWebServicesCreateMeetingWithAttendees
  /meetings/{MeetingId}/attendees/{AttendeeId}:
    GET:
      summary: Getattendee
      description: ' Gets the Amazon Chime SDK attendee details for a specified meeting ID and attendee ID. For more information about the Amazon Chime SDK, see Using the Amazon Chime SDK in the Amazon Chime Developer Guide. '
      operationId: amazonWebServicesGetAttendee
  /meetings/{MeetingId}:
    GET:
      summary: Getmeeting
      description: >-
        Gets the Amazon Chime SDK meeting details for the specified meeting ID.
        For more information about the Amazon Chime SDK, see Using the Amazon
        Chime SDK in the Amazon Chime Developer Guide.
      operationId: amazonWebServicesGetMeeting
  /tags:
    GET:
      summary: Listtagsforresource
      description: Returns a list of the tags available for the specified resource.
      operationId: amazonWebServicesListTagsForResource
  /meetings/{MeetingId}/transcription?operation=start:
    POST:
      summary: Startmeetingtranscription
      description: >-
        Starts transcription for the specified meetingId. For more information,
        refer to  Using Amazon Chime SDK live transcription  in the Amazon Chime
        SDK Developer Guide. If you specify an invalid configuration, a
        TranscriptFailed event will be sent with the contents of the
        BadRequestException generated by Amazon Transcribe. For more information
        on each parameter and which combinations are valid, refer to the
        StartStreamTranscription API in the Amazon Transcribe Developer Guide. 
        By default, Amazon Transcribe may use and store audio content processed
        by the service to develop and improve Amazon Web Services AI/ML services
        as further described in section 50 of the Amazon Web Services Service
        Terms. Using Amazon Transcribe may be subject to federal and state laws
        or regulations regarding the recording or interception of electronic
        communications. It is your and your end users’ responsibility to comply
        with all applicable laws regarding the recording, including properly
        notifying all participants in a recorded session or communication that
        the session or communication is being recorded, and obtaining all
        necessary consents. You can opt out from Amazon Web Services using audio
        content to develop and improve AWS AI/ML services by configuring an AI
        services opt out policy using Amazon Web Services Organizations. 
      operationId: amazonWebServicesStartMeetingTranscription
  /meetings/{MeetingId}/transcription?operation=stop:
    POST:
      summary: Stopmeetingtranscription
      description: >-
        Stops transcription for the specified meetingId. For more information,
        refer to  Using Amazon Chime SDK live transcription  in the Amazon Chime
        SDK Developer Guide.  By default, Amazon Transcribe may use and store
        audio content processed by the service to develop and improve Amazon Web
        Services AI/ML services as further described in section 50 of the Amazon
        Web Services Service Terms. Using Amazon Transcribe may be subject to
        federal and state laws or regulations regarding the recording or
        interception of electronic communications. It is your and your end
        users’ responsibility to comply with all applicable laws regarding the
        recording, including properly notifying all participants in a recorded
        session or communication that the session or communication is being
        recorded, and obtaining all necessary consents. You can opt out from
        Amazon Web Services using audio content to develop and improve Amazon
        Web Services AI/ML services by configuring an AI services opt out policy
        using Amazon Web Services Organizations. 
      operationId: amazonWebServicesStopMeetingTranscription
  /tags?operation=tag-resource:
    POST:
      summary: Tagresource
      description: The resource that supports tags.
      operationId: amazonWebServicesTagResource
  /tags?operation=untag-resource:
    POST:
      summary: Untagresource
      description: >-
        Removes the specified tags from the specified resources. When you
        specify a tag key, the action removes both that key and its associated
        value. The operation succeeds even if you attempt to remove tags from a
        resource that were already removed. Note the following:   To remove tags
        from a resource, you need the necessary permissions for the service that
        the resource belongs to as well as permissions for removing tags. For
        more information, see the documentation for the service whose resource
        you want to untag.   You can only tag resources that are located in the
        specified Amazon Web Services Region for the calling Amazon Web Services
        account.    Minimum permissions  In addition to the tag:UntagResources
        permission required by this operation, you must also have the remove
        tags permission defined by the service that created the resource. For
        example, to remove the tags from an Amazon EC2 instance using the
        UntagResources operation, you must have both of the following
        permissions:  tag:UntagResource   ChimeSDKMeetings:DeleteTags 
      operationId: amazonWebServicesUntagResource
  /meetings/{MeetingId}/attendees/{AttendeeId}/capabilities:
    PUT:
      summary: Updateattendeecapabilities
      description: >-
        The capabilities that you want to update.  You use the capabilities with
        a set of values that control what the capabilities can do, such as
        SendReceive data. For more information about those values, see .  When
        using capabilities, be aware of these corner cases:   If you specify
        MeetingFeatures:Video:MaxResolution:None when you create a meeting, all
        API requests that include SendReceive, Send, or Receive for
        AttendeeCapabilities:Video will be rejected with ValidationError 400.  
        If you specify MeetingFeatures:Content:MaxResolution:None when you
        create a meeting, all API requests that include SendReceive, Send, or
        Receive for AttendeeCapabilities:Content will be rejected with
        ValidationError 400.   You can't set content capabilities to SendReceive
        or Receive unless you also set video capabilities to SendReceive or
        Receive. If you don't set the video capability to receive, the response
        will contain an HTTP 400 Bad Request status code. However, you can set
        your video capability to receive and you set your content capability to
        not receive.   When you change an audio capability from None or Receive
        to Send or SendReceive , and if the attendee left their microphone
        unmuted, audio will flow from the attendee to the other meeting
        participants.   When you change a video or content capability from None
        or Receive to Send or SendReceive , and if the attendee turned on their
        video or content streams, remote attendees can receive those streams,
        but only after media renegotiation between the client and the Amazon
        Chime back-end server.  
      operationId: amazonWebServicesUpdateAttendeeCapabilities
tags: []
