openapi: 3.1.0
info:
  title: chime-sdk-identity
  description: >-
    <p>The Amazon Chime SDK Identity APIs in this section allow software
    developers to create and manage unique instances of their messaging
    applications. These APIs provide the overarching framework for creating and
    sending messages. For more information about the identity APIs, refer to <a
    href="https://docs.aws.amazon.com/chime/latest/APIReference/API_Operations_Amazon_Chime_SDK_Identity.html">Amazon
    Chime SDK identity</a>.</p>
paths:
  /app-instances:
    GET:
      summary: Listappinstances
      description: Lists all Amazon Chime AppInstances created under a single AWS account.
      operationId: amazonWebServicesListAppInstances
  /app-instances/{appInstanceArn}/admins:
    GET:
      summary: Listappinstanceadmins
      description: Returns a list of the administrators in the AppInstance.
      operationId: amazonWebServicesListAppInstanceAdmins
  /app-instance-bots:
    GET:
      summary: Listappinstancebots
      description: Lists all AppInstanceBots created under a single AppInstance.
      operationId: amazonWebServicesListAppInstanceBots
  /app-instance-users:
    GET:
      summary: Listappinstanceusers
      description: List all AppInstanceUsers created under a single AppInstance.
      operationId: amazonWebServicesListAppInstanceUsers
  /app-instances/{appInstanceArn}:
    PUT:
      summary: Updateappinstance
      description: Updates AppInstance metadata.
      operationId: amazonWebServicesUpdateAppInstance
  /app-instances/{appInstanceArn}/admins/{appInstanceAdminArn}:
    GET:
      summary: Describeappinstanceadmin
      description: Returns the full details of an AppInstanceAdmin.
      operationId: amazonWebServicesDescribeAppInstanceAdmin
  /app-instance-bots/{appInstanceBotArn}:
    PUT:
      summary: Updateappinstancebot
      description: Updates the name and metadata of an AppInstanceBot.
      operationId: amazonWebServicesUpdateAppInstanceBot
  /app-instance-users/{appInstanceUserArn}:
    PUT:
      summary: Updateappinstanceuser
      description: >-
        Updates the details of an AppInstanceUser. You can update names and
        metadata.
      operationId: amazonWebServicesUpdateAppInstanceUser
  /app-instance-users/{appInstanceUserArn}/endpoints/{endpointId}:
    PUT:
      summary: Updateappinstanceuserendpoint
      description: >-
        Updates the details of an AppInstanceUserEndpoint. You can update the
        name and AllowMessage values.
      operationId: amazonWebServicesUpdateAppInstanceUserEndpoint
  /app-instances/{appInstanceArn}/retention-settings:
    PUT:
      summary: Putappinstanceretentionsettings
      description: Sets the amount of time in days that a given AppInstance retains data.
      operationId: amazonWebServicesPutAppInstanceRetentionSettings
  /app-instance-users/{appInstanceUserArn}/endpoints:
    POST:
      summary: Registerappinstanceuserendpoint
      description: >-
        Registers an endpoint under an Amazon Chime AppInstanceUser. The
        endpoint receives messages for a user. For push notifications, the
        endpoint is a mobile device used to receive mobile push notifications
        for a user.
      operationId: amazonWebServicesRegisterAppInstanceUserEndpoint
  /tags:
    GET:
      summary: Listtagsforresource
      description: Lists the tags applied to an Amazon Chime SDK identity resource.
      operationId: amazonWebServicesListTagsForResource
  /app-instance-users/{appInstanceUserArn}/expiration-settings:
    PUT:
      summary: Putappinstanceuserexpirationsettings
      description: >-
        Sets the number of days before the AppInstanceUser is automatically
        deleted.  A background process deletes expired AppInstanceUsers within 6
        hours of expiration. Actual deletion times may vary. Expired
        AppInstanceUsers that have not yet been deleted appear as active, and
        you can update their expiration settings. The system honors the new
        settings. 
      operationId: amazonWebServicesPutAppInstanceUserExpirationSettings
  /tags?operation=tag-resource:
    POST:
      summary: Tagresource
      description: >-
        Applies the specified tags to the specified Amazon Chime SDK identity
        resource.
      operationId: amazonWebServicesTagResource
  /tags?operation=untag-resource:
    POST:
      summary: Untagresource
      description: >-
        Removes the specified tags from the specified Amazon Chime SDK identity
        resource.
      operationId: amazonWebServicesUntagResource
tags: []
