openapi: 3.1.0
info:
  title: cleanroomsml
  description: >-
    <p>Welcome to the <i>Amazon Web Services Clean Rooms ML API
    Reference</i>.</p> <p>Amazon Web Services Clean Rooms ML provides a
    privacy-enhancing method for two parties to identify similar users in their
    data without the need to share their data with each other. The first party
    brings the training data to Clean Rooms so that they can create and
    configure an audience model (lookalike model) and associate it with a
    collaboration. The second party then brings their seed data to Clean Rooms
    and generates an audience (lookalike segment) that resembles the training
    data.</p> <p>To learn more about Amazon Web Services Clean Rooms ML
    concepts, procedures, and best practices, see the <a
    href="https://docs.aws.amazon.com/clean-rooms/latest/userguide/machine-learning.html">Clean
    Rooms User Guide</a>.</p> <p>To learn more about SQL commands, functions,
    and conditions supported in Clean Rooms, see the <a
    href="https://docs.aws.amazon.com/clean-rooms/latest/sql-reference/sql-reference.html">Clean
    Rooms SQL Reference</a>.</p>
paths:
  /audience-model:
    GET:
      summary: Listaudiencemodels
      description: Returns a list of audience models.
      operationId: amazonWebServicesListAudienceModels
  /configured-audience-model:
    GET:
      summary: Listconfiguredaudiencemodels
      description: Returns a list of the configured audience models.
      operationId: amazonWebServicesListConfiguredAudienceModels
  /training-dataset:
    GET:
      summary: Listtrainingdatasets
      description: Returns a list of training datasets.
      operationId: amazonWebServicesListTrainingDatasets
  /audience-generation-job/{audienceGenerationJobArn}:
    GET:
      summary: Getaudiencegenerationjob
      description: Returns information about an audience generation job.
      operationId: amazonWebServicesGetAudienceGenerationJob
  /audience-model/{audienceModelArn}:
    GET:
      summary: Getaudiencemodel
      description: Returns information about an audience model
      operationId: amazonWebServicesGetAudienceModel
  /configured-audience-model/{configuredAudienceModelArn}:
    PATCH:
      summary: Updateconfiguredaudiencemodel
      description: >-
        Provides the information necessary to update a configured audience
        model. Updates that impact audience generation jobs take effect when a
        new job starts, but do not impact currently running jobs.
      operationId: amazonWebServicesUpdateConfiguredAudienceModel
  /configured-audience-model/{configuredAudienceModelArn}/policy:
    PUT:
      summary: Putconfiguredaudiencemodelpolicy
      description: Create or update the resource policy for a configured audience model.
      operationId: amazonWebServicesPutConfiguredAudienceModelPolicy
  /training-dataset/{trainingDatasetArn}:
    GET:
      summary: Gettrainingdataset
      description: Returns information about a training dataset.
      operationId: amazonWebServicesGetTrainingDataset
  /audience-export-job:
    POST:
      summary: Startaudienceexportjob
      description: >-
        Export an audience of a specified size after you have generated an
        audience.
      operationId: amazonWebServicesStartAudienceExportJob
  /audience-generation-job:
    POST:
      summary: Startaudiencegenerationjob
      description: Information necessary to start the audience generation job.
      operationId: amazonWebServicesStartAudienceGenerationJob
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes metadata tags from a specified resource.
      operationId: amazonWebServicesUntagResource
tags: []
