openapi: 3.1.0
info:
  title: cleanrooms
  description: >-
    <p>Welcome to the <i>Clean Rooms API Reference</i>.</p> <p>Clean Rooms is an
    Amazon Web Services service that helps multiple parties to join their data
    together in a secure collaboration workspace. In the collaboration, members
    who can query and receive results can get insights into the collective
    datasets without either party getting access to the other party's raw
    data.</p> <p>To learn more about Clean Rooms concepts, procedures, and best
    practices, see the <a
    href="https://docs.aws.amazon.com/clean-rooms/latest/userguide/what-is.html">Clean
    Rooms User Guide</a>.</p> <p>To learn more about SQL commands, functions,
    and conditions supported in Clean Rooms, see the <a
    href="https://docs.aws.amazon.com/clean-rooms/latest/sql-reference/sql-reference.html">Clean
    Rooms SQL Reference</a>.</p>
paths:
  /collaborations/{collaborationIdentifier}/batch-analysistemplates:
    POST:
      summary: Batchgetcollaborationanalysistemplate
      description: >-
        Retrieves multiple analysis templates within a collaboration by their
        Amazon Resource Names (ARNs).
      operationId: amazonWebServicesBatchGetCollaborationAnalysisTemplate
  /collaborations/{collaborationIdentifier}/batch-schema:
    POST:
      summary: Batchgetschema
      description: Retrieves multiple schemas by their identifiers.
      operationId: amazonWebServicesBatchGetSchema
  /memberships/{membershipIdentifier}/analysistemplates:
    GET:
      summary: Listanalysistemplates
      description: Lists analysis templates that the caller owns.
      operationId: amazonWebServicesListAnalysisTemplates
  /collaborations:
    GET:
      summary: Listcollaborations
      description: >-
        Lists collaborations the caller owns, is active in, or has been invited
        to.
      operationId: amazonWebServicesListCollaborations
  /memberships/{membershipIdentifier}/configuredaudiencemodelassociations:
    GET:
      summary: Listconfiguredaudiencemodelassociations
      description: >-
        Lists information about requested configured audience model
        associations.
      operationId: amazonWebServicesListConfiguredAudienceModelAssociations
  /configuredTables:
    GET:
      summary: Listconfiguredtables
      description: Lists configured tables.
      operationId: amazonWebServicesListConfiguredTables
  /configuredTables/{configuredTableIdentifier}/analysisRule:
    POST:
      summary: Createconfiguredtableanalysisrule
      description: >-
        Creates a new analysis rule for a configured table. Currently, only one
        analysis rule can be created for a given configured table.
      operationId: amazonWebServicesCreateConfiguredTableAnalysisRule
  /memberships/{membershipIdentifier}/configuredTableAssociations:
    GET:
      summary: Listconfiguredtableassociations
      description: Lists configured table associations for a membership.
      operationId: amazonWebServicesListConfiguredTableAssociations
  /memberships:
    GET:
      summary: Listmemberships
      description: Lists all memberships resources within the caller's account.
      operationId: amazonWebServicesListMemberships
  /memberships/{membershipIdentifier}/privacybudgettemplates:
    GET:
      summary: Listprivacybudgettemplates
      description: >-
        Returns detailed information about the privacy budget templates in a
        specified membership.
      operationId: amazonWebServicesListPrivacyBudgetTemplates
  /memberships/{membershipIdentifier}/analysistemplates/{analysisTemplateIdentifier}:
    PATCH:
      summary: Updateanalysistemplate
      description: Updates the analysis template metadata.
      operationId: amazonWebServicesUpdateAnalysisTemplate
  /collaborations/{collaborationIdentifier}:
    PATCH:
      summary: Updatecollaboration
      description: >-
        Updates collaboration metadata and can only be called by the
        collaboration owner.
      operationId: amazonWebServicesUpdateCollaboration
  /memberships/{membershipIdentifier}/configuredaudiencemodelassociations/{configuredAudienceModelAssociationIdentifier}:
    PATCH:
      summary: Updateconfiguredaudiencemodelassociation
      description: >-
        Provides the details necessary to update a configured audience model
        association.
      operationId: amazonWebServicesUpdateConfiguredAudienceModelAssociation
  /configuredTables/{configuredTableIdentifier}:
    PATCH:
      summary: Updateconfiguredtable
      description: Updates a configured table.
      operationId: amazonWebServicesUpdateConfiguredTable
  /configuredTables/{configuredTableIdentifier}/analysisRule/{analysisRuleType}:
    PATCH:
      summary: Updateconfiguredtableanalysisrule
      description: Updates a configured table analysis rule.
      operationId: amazonWebServicesUpdateConfiguredTableAnalysisRule
  /memberships/{membershipIdentifier}/configuredTableAssociations/{configuredTableAssociationIdentifier}:
    PATCH:
      summary: Updateconfiguredtableassociation
      description: Updates a configured table association.
      operationId: amazonWebServicesUpdateConfiguredTableAssociation
  /collaborations/{collaborationIdentifier}/member/{accountId}:
    DELETE:
      summary: Deletemember
      description: >-
        Removes the specified member from a collaboration. The removed member is
        placed in the Removed status and can't interact with the collaboration.
        The removed member's data is inaccessible to active members of the
        collaboration.
      operationId: amazonWebServicesDeleteMember
  /memberships/{membershipIdentifier}:
    PATCH:
      summary: Updatemembership
      description: Updates a membership.
      operationId: amazonWebServicesUpdateMembership
  /memberships/{membershipIdentifier}/privacybudgettemplates/{privacyBudgetTemplateIdentifier}:
    PATCH:
      summary: Updateprivacybudgettemplate
      description: Updates the privacy budget template for the specified membership.
      operationId: amazonWebServicesUpdatePrivacyBudgetTemplate
  /collaborations/{collaborationIdentifier}/analysistemplates/{analysisTemplateArn}:
    GET:
      summary: Getcollaborationanalysistemplate
      description: Retrieves an analysis template within a collaboration.
      operationId: amazonWebServicesGetCollaborationAnalysisTemplate
  /collaborations/{collaborationIdentifier}/configuredaudiencemodelassociations/{configuredAudienceModelAssociationIdentifier}:
    GET:
      summary: Getcollaborationconfiguredaudiencemodelassociation
      description: >-
        Retrieves a configured audience model association within a
        collaboration.
      operationId: amazonWebServicesGetCollaborationConfiguredAudienceModelAssociation
  /collaborations/{collaborationIdentifier}/privacybudgettemplates/{privacyBudgetTemplateIdentifier}:
    GET:
      summary: Getcollaborationprivacybudgettemplate
      description: Returns details about a specified privacy budget template.
      operationId: amazonWebServicesGetCollaborationPrivacyBudgetTemplate
  /memberships/{membershipIdentifier}/protectedQueries/{protectedQueryIdentifier}:
    PATCH:
      summary: Updateprotectedquery
      description: Updates the processing of a currently running query.
      operationId: amazonWebServicesUpdateProtectedQuery
  /collaborations/{collaborationIdentifier}/schemas/{name}:
    GET:
      summary: Getschema
      description: Retrieves the schema for a relation within a collaboration.
      operationId: amazonWebServicesGetSchema
  /collaborations/{collaborationIdentifier}/schemas/{name}/analysisRule/{type}:
    GET:
      summary: Getschemaanalysisrule
      description: Retrieves a schema analysis rule.
      operationId: amazonWebServicesGetSchemaAnalysisRule
  /collaborations/{collaborationIdentifier}/analysistemplates:
    GET:
      summary: Listcollaborationanalysistemplates
      description: Lists analysis templates within a collaboration.
      operationId: amazonWebServicesListCollaborationAnalysisTemplates
  /collaborations/{collaborationIdentifier}/configuredaudiencemodelassociations:
    GET:
      summary: Listcollaborationconfiguredaudiencemodelassociations
      description: Lists configured audience model associations within a collaboration.
      operationId: amazonWebServicesListCollaborationConfiguredAudienceModelAssociations
  /collaborations/{collaborationIdentifier}/privacybudgettemplates:
    GET:
      summary: Listcollaborationprivacybudgettemplates
      description: >-
        Returns an array that summarizes each privacy budget template in a
        specified collaboration.
      operationId: amazonWebServicesListCollaborationPrivacyBudgetTemplates
  /collaborations/{collaborationIdentifier}/privacybudgets:
    GET:
      summary: Listcollaborationprivacybudgets
      description: >-
        Returns an array that summarizes each privacy budget in a specified
        collaboration. The summary includes the collaboration ARN, creation
        time, creating account, and privacy budget details.
      operationId: amazonWebServicesListCollaborationPrivacyBudgets
  /collaborations/{collaborationIdentifier}/members:
    GET:
      summary: Listmembers
      description: Lists all members within a collaboration.
      operationId: amazonWebServicesListMembers
  /memberships/{membershipIdentifier}/privacybudgets:
    GET:
      summary: Listprivacybudgets
      description: >-
        Returns detailed information about the privacy budgets in a specified
        membership.
      operationId: amazonWebServicesListPrivacyBudgets
  /memberships/{membershipIdentifier}/protectedQueries:
    POST:
      summary: Startprotectedquery
      description: Creates a protected query that is started by Clean Rooms.
      operationId: amazonWebServicesStartProtectedQuery
  /collaborations/{collaborationIdentifier}/schemas:
    GET:
      summary: Listschemas
      description: Lists the schemas for relations within a collaboration.
      operationId: amazonWebServicesListSchemas
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes a tag or list of tags from a resource.
      operationId: amazonWebServicesUntagResource
  /memberships/{membershipIdentifier}/previewprivacyimpact:
    POST:
      summary: Previewprivacyimpact
      description: >-
        An estimate of the number of aggregation functions that the member who
        can query can run given epsilon and noise parameters.
      operationId: amazonWebServicesPreviewPrivacyImpact
tags: []
