openapi: 3.1.0
info:
  title: cloudcontrol
  description: >-
    <p>For more information about Amazon Web Services Cloud Control API, see the
    <a
    href="https://docs.aws.amazon.com/cloudcontrolapi/latest/userguide/what-is-cloudcontrolapi.html">Amazon
    Web Services Cloud Control API User Guide</a>.</p>
paths:
  /:
    POST:
      summary: Updateresource
      description: >-
        Updates the specified property values in the resource. You specify your
        resource property updates as a list of patch operations contained in a
        JSON patch document that adheres to the  RFC 6902 - JavaScript Object
        Notation (JSON) Patch  standard. For details on how Cloud Control API
        performs resource update operations, see Updating a resource in the
        Amazon Web Services Cloud Control API User Guide. After you have
        initiated a resource update request, you can monitor the progress of
        your request by calling GetResourceRequestStatus using the RequestToken
        of the ProgressEvent returned by UpdateResource. For more information
        about the properties of a specific resource, refer to the related topic
        for the resource in the Resource and property types reference in the
        CloudFormation Users Guide.
      operationId: amazonWebServicesUpdateResource
tags: []
