openapi: 3.1.0
info:
  title: cloudhsm
  description: >-
    <fullname>AWS CloudHSM Service</fullname> <p>This is documentation for
    <b>AWS CloudHSM Classic</b>. For more information, see <a
    href="http://aws.amazon.com/cloudhsm/faqs-classic/">AWS CloudHSM Classic
    FAQs</a>, the <a
    href="https://docs.aws.amazon.com/cloudhsm/classic/userguide/">AWS CloudHSM
    Classic User Guide</a>, and the <a
    href="https://docs.aws.amazon.com/cloudhsm/classic/APIReference/">AWS
    CloudHSM Classic API Reference</a>.</p> <p> <b>For information about the
    current version of AWS CloudHSM</b>, see <a
    href="http://aws.amazon.com/cloudhsm/">AWS CloudHSM</a>, the <a
    href="https://docs.aws.amazon.com/cloudhsm/latest/userguide/">AWS CloudHSM
    User Guide</a>, and the <a
    href="https://docs.aws.amazon.com/cloudhsm/latest/APIReference/">AWS
    CloudHSM API Reference</a>.</p>
paths:
  /:
    POST:
      summary: Removetagsfromresource
      description: >-
        This is documentation for AWS CloudHSM Classic. For more information,
        see AWS CloudHSM Classic FAQs, the AWS CloudHSM Classic User Guide, and
        the AWS CloudHSM Classic API Reference.  For information about the
        current version of AWS CloudHSM, see AWS CloudHSM, the AWS CloudHSM User
        Guide, and the AWS CloudHSM API Reference. Removes one or more tags from
        the specified AWS CloudHSM resource. To remove a tag, specify only the
        tag key to remove (not the value). To overwrite the value for an
        existing tag, use AddTagsToResource.
      operationId: amazonWebServicesRemoveTagsFromResource
tags: []
