openapi: 3.1.0
info:
  title: codeguru-reviewer
  description: >-
    <p>This section provides documentation for the Amazon CodeGuru Reviewer API
    operations. CodeGuru Reviewer is a service that uses program analysis and
    machine learning to detect potential defects that are difficult for
    developers to find and recommends fixes in your Java and Python code.</p>
    <p>By proactively detecting and providing recommendations for addressing
    code defects and implementing best practices, CodeGuru Reviewer improves the
    overall quality and maintainability of your code base during the code review
    stage. For more information about CodeGuru Reviewer, see the <i> <a
    href="https://docs.aws.amazon.com/codeguru/latest/reviewer-ug/welcome.html">Amazon
    CodeGuru Reviewer User Guide</a>.</i> </p> <p>To improve the security of
    your CodeGuru Reviewer API calls, you can establish a private connection
    between your VPC and CodeGuru Reviewer by creating an <i>interface VPC
    endpoint</i>. For more information, see <a
    href="https://docs.aws.amazon.com/codeguru/latest/reviewer-ug/vpc-interface-endpoints.html">CodeGuru
    Reviewer and interface VPC endpoints (Amazon Web Services PrivateLink)</a>
    in the <i>Amazon CodeGuru Reviewer User Guide</i>.</p>
paths:
  /associations:
    GET:
      summary: Listrepositoryassociations
      description: >-
        Returns a list of RepositoryAssociationSummary objects that contain
        summary information about a repository association. You can filter the
        returned list by ProviderType, Name, State, and Owner.
      operationId: amazonWebServicesListRepositoryAssociations
  /codereviews:
    GET:
      summary: Listcodereviews
      description: >-
        Lists all the code reviews that the customer has created in the past 90
        days.
      operationId: amazonWebServicesListCodeReviews
  /codereviews/{CodeReviewArn}:
    GET:
      summary: Describecodereview
      description: >-
        Returns the metadata associated with the code review along with its
        status.
      operationId: amazonWebServicesDescribeCodeReview
  /feedback/{CodeReviewArn}:
    GET:
      summary: Describerecommendationfeedback
      description: Describes the customer feedback for a CodeGuru Reviewer recommendation.
      operationId: amazonWebServicesDescribeRecommendationFeedback
  /associations/{AssociationArn}:
    DELETE:
      summary: Disassociaterepository
      description: >-
        Removes the association between Amazon CodeGuru Reviewer and a
        repository.
      operationId: amazonWebServicesDisassociateRepository
  /feedback/{CodeReviewArn}/RecommendationFeedback:
    GET:
      summary: Listrecommendationfeedback
      description: >-
        Returns a list of RecommendationFeedbackSummary objects that contain
        customer recommendation feedback for all CodeGuru Reviewer users.
      operationId: amazonWebServicesListRecommendationFeedback
  /codereviews/{CodeReviewArn}/Recommendations:
    GET:
      summary: Listrecommendations
      description: Returns the list of all recommendations for a completed code review.
      operationId: amazonWebServicesListRecommendations
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes a tag from an associated repository.
      operationId: amazonWebServicesUntagResource
  /feedback:
    PUT:
      summary: Putrecommendationfeedback
      description: >-
        Stores customer feedback for a CodeGuru Reviewer recommendation. When
        this API is called again with different reactions the previous feedback
        is overwritten.
      operationId: amazonWebServicesPutRecommendationFeedback
tags: []
