openapi: 3.1.0
info:
  title: codestar-notifications
  description: >-
    <p>This AWS CodeStar Notifications API Reference provides descriptions and
    usage examples of the operations and data types for the AWS CodeStar
    Notifications API. You can use the AWS CodeStar Notifications API to work
    with the following objects:</p> <p>Notification rules, by calling the
    following: </p> <ul> <li> <p> <a>CreateNotificationRule</a>, which creates a
    notification rule for a resource in your account. </p> </li> <li> <p>
    <a>DeleteNotificationRule</a>, which deletes a notification rule. </p> </li>
    <li> <p> <a>DescribeNotificationRule</a>, which provides information about a
    notification rule. </p> </li> <li> <p> <a>ListNotificationRules</a>, which
    lists the notification rules associated with your account. </p> </li> <li>
    <p> <a>UpdateNotificationRule</a>, which changes the name, events, or
    targets associated with a notification rule. </p> </li> <li> <p>
    <a>Subscribe</a>, which subscribes a target to a notification rule. </p>
    </li> <li> <p> <a>Unsubscribe</a>, which removes a target from a
    notification rule. </p> </li> </ul> <p>Targets, by calling the following:
    </p> <ul> <li> <p> <a>DeleteTarget</a>, which removes a notification rule
    target from a notification rule. </p> </li> <li> <p> <a>ListTargets</a>,
    which lists the targets associated with a notification rule. </p> </li>
    </ul> <p>Events, by calling the following: </p> <ul> <li> <p>
    <a>ListEventTypes</a>, which lists the event types you can include in a
    notification rule. </p> </li> </ul> <p>Tags, by calling the following: </p>
    <ul> <li> <p> <a>ListTagsForResource</a>, which lists the tags already
    associated with a notification rule in your account. </p> </li> <li> <p>
    <a>TagResource</a>, which associates a tag you provide with a notification
    rule in your account. </p> </li> <li> <p> <a>UntagResource</a>, which
    removes a tag from a notification rule in your account. </p> </li> </ul> <p>
    For information about how to use AWS CodeStar Notifications, see the <a
    href="https://docs.aws.amazon.com/dtconsole/latest/userguide/what-is-dtconsole.html">Amazon
    Web Services Developer Tools Console User Guide</a>. </p>
paths:
  /createNotificationRule:
    POST:
      summary: Createnotificationrule
      description: >-
        Creates a notification rule for a resource. The rule specifies the
        events you want notifications about and the targets (such as Chatbot
        topics or Chatbot clients configured for Slack) where you want to
        receive them.
      operationId: amazonWebServicesCreateNotificationRule
  /deleteNotificationRule:
    POST:
      summary: Deletenotificationrule
      description: Deletes a notification rule for a resource.
      operationId: amazonWebServicesDeleteNotificationRule
  /deleteTarget:
    POST:
      summary: Deletetarget
      description: Deletes a specified target for notifications.
      operationId: amazonWebServicesDeleteTarget
  /describeNotificationRule:
    POST:
      summary: Describenotificationrule
      description: Returns information about a specified notification rule.
      operationId: amazonWebServicesDescribeNotificationRule
  /listEventTypes:
    POST:
      summary: Listeventtypes
      description: >-
        Returns information about the event types available for configuring
        notifications.
      operationId: amazonWebServicesListEventTypes
  /listNotificationRules:
    POST:
      summary: Listnotificationrules
      description: >-
        Returns a list of the notification rules for an Amazon Web Services
        account.
      operationId: amazonWebServicesListNotificationRules
  /listTagsForResource:
    POST:
      summary: Listtagsforresource
      description: Returns a list of the tags associated with a notification rule.
      operationId: amazonWebServicesListTagsForResource
  /listTargets:
    POST:
      summary: Listtargets
      description: >-
        Returns a list of the notification rule targets for an Amazon Web
        Services account.
      operationId: amazonWebServicesListTargets
  /subscribe:
    POST:
      summary: Subscribe
      description: >-
        Creates an association between a notification rule and an Chatbot topic
        or Chatbot client so that the associated target can receive
        notifications when the events described in the rule are triggered.
      operationId: amazonWebServicesSubscribe
  /tagResource:
    POST:
      summary: Tagresource
      description: Associates a set of provided tags with a notification rule.
      operationId: amazonWebServicesTagResource
  /unsubscribe:
    POST:
      summary: Unsubscribe
      description: >-
        Removes an association between a notification rule and an Chatbot topic
        so that subscribers to that topic stop receiving notifications when the
        events described in the rule are triggered.
      operationId: amazonWebServicesUnsubscribe
  /untagResource/{resourceArn}:
    POST:
      summary: Untagresource
      description: >-
        Removes the association between one or more provided tags and a
        notification rule.
      operationId: amazonWebServicesUntagResource
  /updateNotificationRule:
    POST:
      summary: Updatenotificationrule
      description: >-
        Updates a notification rule for a resource. You can change the events
        that trigger the notification rule, the status of the rule, and the
        targets that receive the notifications.  To add or remove tags for a
        notification rule, you must use TagResource and UntagResource. 
      operationId: amazonWebServicesUpdateNotificationRule
tags: []
