openapi: 3.1.0
info:
  title: codebuild
  description: >-
    <fullname>CodeBuild</fullname> <p>CodeBuild is a fully managed build service
    in the cloud. CodeBuild compiles your source code, runs unit tests, and
    produces artifacts that are ready to deploy. CodeBuild eliminates the need
    to provision, manage, and scale your own build servers. It provides
    prepackaged build environments for the most popular programming languages
    and build tools, such as Apache Maven, Gradle, and more. You can also fully
    customize build environments in CodeBuild to use your own build tools.
    CodeBuild scales automatically to meet peak build requests. You pay only for
    the build time you consume. For more information about CodeBuild, see the
    <i> <a
    href="https://docs.aws.amazon.com/codebuild/latest/userguide/welcome.html">CodeBuild
    User Guide</a>.</i> </p>
paths:
  /:
    POST:
      summary: Updatewebhook
      description: ' Updates the webhook associated with an CodeBuild build project.    If you use Bitbucket for your repository, rotateSecret is ignored.  '
      operationId: amazonWebServicesUpdateWebhook
tags: []
