openapi: 3.1.0
info:
  title: codeguru-security
  description: >-
    <note> <p>Amazon CodeGuru Security is in preview release and is subject to
    change.</p> </note> <p>This section provides documentation for the Amazon
    CodeGuru Security API operations. CodeGuru Security is a service that uses
    program analysis and machine learning to detect security policy violations
    and vulnerabilities, and recommends ways to address these security
    risks.</p> <p>By proactively detecting and providing recommendations for
    addressing security risks, CodeGuru Security improves the overall security
    of your application code. For more information about CodeGuru Security, see
    the <a
    href="https://docs.aws.amazon.com/codeguru/latest/security-ug/what-is-codeguru-security.html">Amazon
    CodeGuru Security User Guide</a>. </p>
paths:
  /batchGetFindings:
    POST:
      summary: Batchgetfindings
      description: Returns a list of all requested findings.
      operationId: amazonWebServicesBatchGetFindings
  /scans:
    GET:
      summary: Listscans
      description: >-
        Returns a list of all the standard scans in an account. Does not return
        express scans.
      operationId: amazonWebServicesListScans
  /uploadUrl:
    POST:
      summary: Createuploadurl
      description: >-
        Generates a pre-signed URL and request headers used to upload a code
        resource. You can upload your code resource to the URL and add the
        request headers using any HTTP client.
      operationId: amazonWebServicesCreateUploadUrl
  /accountConfiguration/get:
    GET:
      summary: Getaccountconfiguration
      description: Use to get account level configuration.
      operationId: amazonWebServicesGetAccountConfiguration
  /findings/{scanName}:
    GET:
      summary: Getfindings
      description: Returns a list of all findings generated by a particular scan.
      operationId: amazonWebServicesGetFindings
  /metrics/summary:
    GET:
      summary: Getmetricssummary
      description: >-
        Returns top level metrics about an account from a specified date,
        including number of open findings, the categories with most findings,
        the scans with most open findings, and scans with most open critical
        findings. 
      operationId: amazonWebServicesGetMetricsSummary
  /scans/{scanName}:
    GET:
      summary: Getscan
      description: >-
        Returns details about a scan, including whether or not a scan has
        completed.
      operationId: amazonWebServicesGetScan
  /metrics/findings:
    GET:
      summary: Listfindingsmetrics
      description: >-
        Returns metrics about all findings in an account within a specified time
        range.
      operationId: amazonWebServicesListFindingsMetrics
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Use to remove one or more tags from an existing scan.
      operationId: amazonWebServicesUntagResource
  /updateAccountConfiguration:
    PUT:
      summary: Updateaccountconfiguration
      description: Use to update account-level configuration with an encryption key.
      operationId: amazonWebServicesUpdateAccountConfiguration
tags: []
