openapi: 3.1.0
info:
  title: connectcases
  description: >-
    <p>With Amazon Connect Cases, your agents can track and manage customer
    issues that require multiple interactions, follow-up tasks, and teams in
    your contact center. A case represents a customer issue. It records the
    issue, the steps and interactions taken to resolve the issue, and the
    outcome. For more information, see <a
    href="https://docs.aws.amazon.com/connect/latest/adminguide/cases.html">Amazon
    Connect Cases</a> in the <i>Amazon Connect Administrator Guide</i>.</p>
paths:
  /domains/{domainId}/fields-batch:
    POST:
      summary: Batchgetfield
      description: >-
        Returns the description for the list of fields in the request
        parameters. 
      operationId: amazonWebServicesBatchGetField
  /domains/{domainId}/fields/{fieldId}/options:
    PUT:
      summary: Batchputfieldoptions
      description: >-
        Creates and updates a set of field options for a single select field in
        a Cases domain.
      operationId: amazonWebServicesBatchPutFieldOptions
  /domains/{domainId}/cases:
    POST:
      summary: Createcase
      description: ' If you provide a value for PerformedBy.UserArn you must also have connect:DescribeUser permission on the User ARN resource that you provide   &lt;p&gt;Creates a case in the specified Cases domain. Case system and custom fields are taken as an array id/value pairs with a declared data types.&lt;/p&gt; &lt;p&gt;The following fields are required when creating a case:&lt;/p&gt; &lt;ul&gt; &lt;li&gt; &lt;p&gt; &lt;code&gt;customer_id&lt;/code&gt; - You must provide the full customer profile ARN in this format: &lt;code&gt;arn:aws:profile:your_AWS_Region:your_AWS_account ID:domains/your_profiles_domain_name/profiles/profile_ID&lt;/code&gt; &lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt; &lt;code&gt;title&lt;/code&gt; &lt;/p&gt; &lt;/li&gt; &lt;/ul&gt; '
      operationId: amazonWebServicesCreateCase
  /domains:
    POST:
      summary: Createdomain
      description: >-
        Creates a domain, which is a container for all case data, such as cases,
        fields, templates and layouts. Each Amazon Connect instance can be
        associated with only one Cases domain.  This will not associate your
        connect instance to Cases domain. Instead, use the Amazon Connect
        CreateIntegrationAssociation API. You need specific IAM permissions to
        successfully associate the Cases domain. For more information, see
        Onboard to Cases.  &lt;/important&gt; 
      operationId: amazonWebServicesCreateDomain
  /domains/{domainId}/fields:
    POST:
      summary: Createfield
      description: >-
        Creates a field in the Cases domain. This field is used to define the
        case object model (that is, defines what data can be captured on cases)
        in a Cases domain. 
      operationId: amazonWebServicesCreateField
  /domains/{domainId}/layouts:
    POST:
      summary: Createlayout
      description: >-
        Creates a layout in the Cases domain. Layouts define the following
        configuration in the top section and More Info tab of the Cases user
        interface:   Fields to display to the users   Field ordering    Title
        and Status fields cannot be part of layouts since they are not
        configurable. 
      operationId: amazonWebServicesCreateLayout
  /domains/{domainId}/cases/{caseId}/related-items/:
    POST:
      summary: Createrelateditem
      description: >-
        Creates a related item (comments, tasks, and contacts) and associates it
        with a case.    A Related Item is a resource that is associated with a
        case. It may or may not have an external identifier linking it to an
        external resource (for example, a contactArn). All Related Items have
        their own internal identifier, the relatedItemArn. Examples of related
        items include comments and contacts.   If you provide a value for
        performedBy.userArn you must also have DescribeUser permission on the
        ARN of the user that you provide.    &lt;/note&gt; 
      operationId: amazonWebServicesCreateRelatedItem
  /domains/{domainId}/templates:
    POST:
      summary: Createtemplate
      description: >-
        Creates a template in the Cases domain. This template is used to define
        the case object model (that is, to define what data can be captured on
        cases) in a Cases domain. A template must have a unique name within a
        domain, and it must reference existing field IDs and layout IDs.
        Additionally, multiple fields with same IDs are not allowed within the
        same Template. A template can be either Active or Inactive, as indicated
        by its status. Inactive templates cannot be used to create cases.
      operationId: amazonWebServicesCreateTemplate
  /domains/{domainId}:
    POST:
      summary: Getdomain
      description: 'Returns information about a specific domain if it exists. '
      operationId: amazonWebServicesGetDomain
  /domains/{domainId}/cases/{caseId}:
    PUT:
      summary: Updatecase
      description: ' If you provide a value for PerformedBy.UserArn you must also have connect:DescribeUser permission on the User ARN resource that you provide   &lt;p&gt;Updates the values of fields on a case. Fields to be updated are received as an array of id/value pairs identical to the &lt;code&gt;CreateCase&lt;/code&gt; input .&lt;/p&gt; &lt;p&gt;If the action is successful, the service sends back an HTTP 200 response with an empty HTTP body.&lt;/p&gt; '
      operationId: amazonWebServicesUpdateCase
  /domains/{domainId}/cases/{caseId}/audit-history:
    POST:
      summary: Getcaseauditevents
      description: Returns the audit history about a specific case if it exists.
      operationId: amazonWebServicesGetCaseAuditEvents
  /domains/{domainId}/case-event-configuration:
    PUT:
      summary: Putcaseeventconfiguration
      description: >-
        Adds case event publishing configuration. For a complete list of fields
        you can add to the event message, see Create case fields in the Amazon
        Connect Administrator Guide 
      operationId: amazonWebServicesPutCaseEventConfiguration
  /domains/{domainId}/layouts/{layoutId}:
    PUT:
      summary: Updatelayout
      description: >-
        Updates the attributes of an existing layout. If the action is
        successful, the service sends back an HTTP 200 response with an empty
        HTTP body. A ValidationException is returned when you add non-existent
        fieldIds to a layout.  Title and Status fields cannot be part of layouts
        because they are not configurable. 
      operationId: amazonWebServicesUpdateLayout
  /domains/{domainId}/templates/{templateId}:
    PUT:
      summary: Updatetemplate
      description: >-
        Updates the attributes of an existing template. The template attributes
        that can be modified include name, description, layoutConfiguration,
        requiredFields, and status. At least one of these attributes must not be
        null. If a null value is provided for a given attribute, that attribute
        is ignored and its current value is preserved.
      operationId: amazonWebServicesUpdateTemplate
  /domains/{domainId}/list-cases-for-contact:
    POST:
      summary: Listcasesforcontact
      description: Lists cases for a given contact.
      operationId: amazonWebServicesListCasesForContact
  /domains-list:
    POST:
      summary: Listdomains
      description: >-
        Lists all cases domains in the Amazon Web Services account. Each list
        item is a condensed summary object of the domain.
      operationId: amazonWebServicesListDomains
  /domains/{domainId}/fields/{fieldId}/options-list:
    POST:
      summary: Listfieldoptions
      description: 'Lists all of the field options for a field identifier in the domain. '
      operationId: amazonWebServicesListFieldOptions
  /domains/{domainId}/fields-list:
    POST:
      summary: Listfields
      description: Lists all fields in a Cases domain.
      operationId: amazonWebServicesListFields
  /domains/{domainId}/layouts-list:
    POST:
      summary: Listlayouts
      description: >-
        Lists all layouts in the given cases domain. Each list item is a
        condensed summary object of the layout.
      operationId: amazonWebServicesListLayouts
  /tags/{arn}:
    DELETE:
      summary: Untagresource
      description: Untags a resource.
      operationId: amazonWebServicesUntagResource
  /domains/{domainId}/templates-list:
    POST:
      summary: Listtemplates
      description: >-
        Lists all of the templates in a Cases domain. Each list item is a
        condensed summary object of the template. 
      operationId: amazonWebServicesListTemplates
  /domains/{domainId}/cases-search:
    POST:
      summary: Searchcases
      description: >-
        Searches for cases within their associated Cases domain. Search results
        are returned as a paginated list of abridged case documents.  For
        customer_id you must provide the full customer profile ARN in this
        format:  arn:aws:profile:your AWS Region:your AWS account
        ID:domains/profiles domain name/profiles/profile ID.  
      operationId: amazonWebServicesSearchCases
  /domains/{domainId}/cases/{caseId}/related-items-search:
    POST:
      summary: Searchrelateditems
      description: >-
        Searches for related items that are associated with a case.  If no
        filters are provided, this returns all related items associated with a
        case. 
      operationId: amazonWebServicesSearchRelatedItems
  /domains/{domainId}/fields/{fieldId}:
    PUT:
      summary: Updatefield
      description: 'Updates the properties of an existing field. '
      operationId: amazonWebServicesUpdateField
tags: []
