openapi: 3.1.0
info:
  title: connectcampaigns
  description: <p>Provide APIs to create and manage Amazon Connect Campaigns.</p>
paths:
  /campaigns:
    PUT:
      summary: Createcampaign
      description: >-
        Creates a campaign for the specified Amazon Connect account. This API is
        idempotent.
      operationId: amazonWebServicesCreateCampaign
  /campaigns/{id}:
    GET:
      summary: Describecampaign
      description: Describes the specific campaign.
      operationId: amazonWebServicesDescribeCampaign
  /connect-instance/{connectInstanceId}/config:
    GET:
      summary: Getconnectinstanceconfig
      description: Get the specific Connect instance config.
      operationId: amazonWebServicesGetConnectInstanceConfig
  /connect-instance/{connectInstanceId}/onboarding:
    PUT:
      summary: Startinstanceonboardingjob
      description: Onboard the specific Amazon Connect instance to Connect Campaigns.
      operationId: amazonWebServicesStartInstanceOnboardingJob
  /campaigns/{id}/state:
    GET:
      summary: Getcampaignstate
      description: Get state of a campaign for the specified Amazon Connect account.
      operationId: amazonWebServicesGetCampaignState
  /campaigns-state:
    POST:
      summary: Getcampaignstatebatch
      description: Get state of campaigns for the specified Amazon Connect account.
      operationId: amazonWebServicesGetCampaignStateBatch
  /campaigns-summary:
    POST:
      summary: Listcampaigns
      description: >-
        Provides summary information about the campaigns under the specified
        Amazon Connect account.
      operationId: amazonWebServicesListCampaigns
  /tags/{arn}:
    DELETE:
      summary: Untagresource
      description: Untag a resource.
      operationId: amazonWebServicesUntagResource
  /campaigns/{id}/pause:
    POST:
      summary: Pausecampaign
      description: Pauses a campaign for the specified Amazon Connect account.
      operationId: amazonWebServicesPauseCampaign
  /campaigns/{id}/dial-requests:
    PUT:
      summary: Putdialrequestbatch
      description: >-
        Creates dials requests for the specified campaign Amazon Connect
        account. This API is idempotent.
      operationId: amazonWebServicesPutDialRequestBatch
  /campaigns/{id}/resume:
    POST:
      summary: Resumecampaign
      description: Stops a campaign for the specified Amazon Connect account.
      operationId: amazonWebServicesResumeCampaign
  /campaigns/{id}/start:
    POST:
      summary: Startcampaign
      description: Starts a campaign for the specified Amazon Connect account.
      operationId: amazonWebServicesStartCampaign
  /campaigns/{id}/stop:
    POST:
      summary: Stopcampaign
      description: Stops a campaign for the specified Amazon Connect account.
      operationId: amazonWebServicesStopCampaign
  /campaigns/{id}/dialer-config:
    POST:
      summary: Updatecampaigndialerconfig
      description: Updates the dialer config of a campaign. This API is idempotent.
      operationId: amazonWebServicesUpdateCampaignDialerConfig
  /campaigns/{id}/name:
    POST:
      summary: Updatecampaignname
      description: Updates the name of a campaign. This API is idempotent.
      operationId: amazonWebServicesUpdateCampaignName
  /campaigns/{id}/outbound-call-config:
    POST:
      summary: Updatecampaignoutboundcallconfig
      description: Updates the outbound call config of a campaign. This API is idempotent.
      operationId: amazonWebServicesUpdateCampaignOutboundCallConfig
tags: []
