openapi: 3.1.0
info:
  title: connectparticipant
  description: >-
    <p>Amazon Connect is an easy-to-use omnichannel cloud contact center service
    that enables companies of any size to deliver superior customer service at a
    lower cost. Amazon Connect communications capabilities make it easy for
    companies to deliver personalized interactions across communication
    channels, including chat. </p> <p>Use the Amazon Connect Participant Service
    to manage participants (for example, agents, customers, and managers
    listening in), and to send messages and events within a chat contact. The
    APIs in the service enable the following: sending chat messages, attachment
    sharing, managing a participant's connection state and message events, and
    retrieving chat transcripts.</p>
paths:
  /participant/complete-attachment-upload:
    POST:
      summary: Completeattachmentupload
      description: >-
        Allows you to confirm that the attachment has been uploaded using the
        pre-signed URL provided in StartAttachmentUpload API.    ConnectionToken
        is used for invoking this API instead of ParticipantToken.  The Amazon
        Connect Participant Service APIs do not use Signature Version 4
        authentication.
      operationId: amazonWebServicesCompleteAttachmentUpload
  /participant/connection:
    POST:
      summary: Createparticipantconnection
      description: >-
        Creates the participant's connection.    ParticipantToken is used for
        invoking this API instead of ConnectionToken.  The participant token is
        valid for the lifetime of the participant – until they are part of a
        contact. The response URL for WEBSOCKET Type has a connect expiry
        timeout of 100s. Clients must manually connect to the returned websocket
        URL and subscribe to the desired topic.  For chat, you need to publish
        the following on the established websocket connection: 
        {"topic":"aws/subscribe","content":{"topics":["aws/chat"]}}  Upon
        websocket URL expiry, as specified in the response ConnectionExpiry
        parameter, clients need to call this API again to obtain a new websocket
        URL and perform the same steps as before.  Message streaming support:
        This API can also be used together with the StartContactStreaming API to
        create a participant connection for chat contacts that are not using a
        websocket. For more information about message streaming, Enable
        real-time chat message streaming in the Amazon Connect Administrator
        Guide.  Feature specifications: For information about feature
        specifications, such as the allowed number of open websocket connections
        per participant, see Feature specifications in the Amazon Connect
        Administrator Guide.   The Amazon Connect Participant Service APIs do
        not use Signature Version 4 authentication. 
      operationId: amazonWebServicesCreateParticipantConnection
  /participant/views/{ViewToken}:
    GET:
      summary: Describeview
      description: Retrieves the view for the specified view token.
      operationId: amazonWebServicesDescribeView
  /participant/disconnect:
    POST:
      summary: Disconnectparticipant
      description: >-
        Disconnects a participant.    ConnectionToken is used for invoking this
        API instead of ParticipantToken.  The Amazon Connect Participant Service
        APIs do not use Signature Version 4 authentication.
      operationId: amazonWebServicesDisconnectParticipant
  /participant/attachment:
    POST:
      summary: Getattachment
      description: >-
        Provides a pre-signed URL for download of a completed attachment. This
        is an asynchronous API for use with active contacts.   ConnectionToken
        is used for invoking this API instead of ParticipantToken.  The Amazon
        Connect Participant Service APIs do not use Signature Version 4
        authentication.
      operationId: amazonWebServicesGetAttachment
  /participant/transcript:
    POST:
      summary: Gettranscript
      description: >-
        Retrieves a transcript of the session, including details about any
        attachments. For information about accessing past chat contact
        transcripts for a persistent chat, see Enable persistent chat.   
        ConnectionToken is used for invoking this API instead of
        ParticipantToken.  The Amazon Connect Participant Service APIs do not
        use Signature Version 4 authentication.
      operationId: amazonWebServicesGetTranscript
  /participant/event:
    POST:
      summary: Sendevent
      description: >-
        Sends an event.    ConnectionToken is used for invoking this API instead
        of ParticipantToken.  The Amazon Connect Participant Service APIs do not
        use Signature Version 4 authentication.
      operationId: amazonWebServicesSendEvent
  /participant/message:
    POST:
      summary: Sendmessage
      description: >-
        Sends a message.   ConnectionToken is used for invoking this API instead
        of ParticipantToken.  The Amazon Connect Participant Service APIs do not
        use Signature Version 4 authentication.
      operationId: amazonWebServicesSendMessage
  /participant/start-attachment-upload:
    POST:
      summary: Startattachmentupload
      description: >-
        Provides a pre-signed Amazon S3 URL in response for uploading the file
        directly to S3.   ConnectionToken is used for invoking this API instead
        of ParticipantToken.  The Amazon Connect Participant Service APIs do not
        use Signature Version 4 authentication.
      operationId: amazonWebServicesStartAttachmentUpload
tags: []
