openapi: 3.1.0
info:
  title: customer-profiles
  description: >-
    <fullname>Amazon Connect Customer Profiles</fullname> <p>Amazon Connect
    Customer Profiles is a unified customer profile for your contact center that
    has pre-built connectors powered by AppFlow that make it easy to combine
    customer information from third party applications, such as Salesforce
    (CRM), ServiceNow (ITSM), and your enterprise resource planning (ERP), with
    contact history from your Amazon Connect contact center. If you're new to
    Amazon Connect, you might find it helpful to review the <a
    href="https://docs.aws.amazon.com/connect/latest/adminguide/">Amazon Connect
    Administrator Guide</a>.</p>
paths:
  /domains/{DomainName}/profiles/keys:
    POST:
      summary: Addprofilekey
      description: >-
        Associates a new key value with a specific profile, such as a Contact
        Record ContactId. A profile object can have a single unique key and any
        number of additional keys that can be used to identify the profile that
        it belongs to.
      operationId: amazonWebServicesAddProfileKey
  /domains/{DomainName}/calculated-attributes/{CalculatedAttributeName}:
    PUT:
      summary: Updatecalculatedattributedefinition
      description: >-
        Updates an existing calculated attribute definition. When updating the
        Conditions, note that increasing the date range of a calculated
        attribute will not trigger inclusion of historical data greater than the
        current date range.
      operationId: amazonWebServicesUpdateCalculatedAttributeDefinition
  /domains/{DomainName}:
    PUT:
      summary: Updatedomain
      description: >-
        Updates the properties of a domain, including creating or selecting a
        dead letter queue or an encryption key. After a domain is created, the
        name can’t be changed. Use this API or CreateDomain to enable identity
        resolution: set Matching to true. To prevent cross-service impersonation
        when you call this API, see Cross-service confused deputy prevention for
        sample policies that you should apply.  To add or remove tags on an
        existing Domain, see TagResource/UntagResource.
      operationId: amazonWebServicesUpdateDomain
  /domains/{DomainName}/event-streams/{EventStreamName}:
    GET:
      summary: Geteventstream
      description: >-
        Returns information about the specified event stream in a specific
        domain.
      operationId: amazonWebServicesGetEventStream
  /domains/{DomainName}/workflows/integrations:
    POST:
      summary: Createintegrationworkflow
      description: ' Creates an integration workflow. An integration workflow is an async process which ingests historic data and sets up an integration for ongoing updates. The supported Amazon AppFlow sources are Salesforce, ServiceNow, and Marketo. '
      operationId: amazonWebServicesCreateIntegrationWorkflow
  /domains/{DomainName}/profiles:
    PUT:
      summary: Updateprofile
      description: >-
        Updates the properties of a profile. The ProfileId is required for
        updating a customer profile. When calling the UpdateProfile API,
        specifying an empty string value means that any existing value will be
        removed. Not specifying a string value means that any value already
        there will be kept.
      operationId: amazonWebServicesUpdateProfile
  /domains/{DomainName}/integrations/delete:
    POST:
      summary: Deleteintegration
      description: Removes an integration from a specific domain.
      operationId: amazonWebServicesDeleteIntegration
  /domains/{DomainName}/profiles/delete:
    POST:
      summary: Deleteprofile
      description: >-
        Deletes the standard customer profile and all data pertaining to the
        profile.
      operationId: amazonWebServicesDeleteProfile
  /domains/{DomainName}/profiles/keys/delete:
    POST:
      summary: Deleteprofilekey
      description: Removes a searchable key from a customer profile.
      operationId: amazonWebServicesDeleteProfileKey
  /domains/{DomainName}/profiles/objects/delete:
    POST:
      summary: Deleteprofileobject
      description: >-
        Removes an object associated with a profile of a given
        ProfileObjectType.
      operationId: amazonWebServicesDeleteProfileObject
  /domains/{DomainName}/object-types/{ObjectTypeName}:
    PUT:
      summary: Putprofileobjecttype
      description: >-
        Defines a ProfileObjectType. To add or remove tags on an existing
        ObjectType, see  TagResource/UntagResource.
      operationId: amazonWebServicesPutProfileObjectType
  /domains/{DomainName}/workflows/{WorkflowId}:
    GET:
      summary: Getworkflow
      description: Get details of specified workflow.
      operationId: amazonWebServicesGetWorkflow
  /domains/{DomainName}/detect/object-types:
    POST:
      summary: Detectprofileobjecttype
      description: >-
        The process of detecting profile object type mapping by using given
        objects.
      operationId: amazonWebServicesDetectProfileObjectType
  /domains/{DomainName}/identity-resolution-jobs/auto-merging-preview:
    POST:
      summary: Getautomergingpreview
      description: >-
        Tests the auto-merging settings of your Identity Resolution Job without
        merging your data. It randomly selects a sample of matching groups from
        the existing matching results, and applies the automerging settings that
        you provided. You can then view the number of profiles in the sample,
        the number of matches, and the number of profiles identified to be
        merged. This enables you to evaluate the accuracy of the attributes in
        your matching list.  You can't view which profiles are matched and would
        be merged.  We strongly recommend you use this API to do a dry run of
        the automerging process before running the Identity Resolution Job.
        Include at least two matching attributes. If your matching list includes
        too few attributes (such as only FirstName or only LastName), there may
        be a large number of matches. This increases the chances of erroneous
        merges. 
      operationId: amazonWebServicesGetAutoMergingPreview
  /domains/{DomainName}/profile/{ProfileId}/calculated-attributes/{CalculatedAttributeName}:
    GET:
      summary: Getcalculatedattributeforprofile
      description: Retrieve a calculated attribute for a customer profile.
      operationId: amazonWebServicesGetCalculatedAttributeForProfile
  /domains/{DomainName}/identity-resolution-jobs/{JobId}:
    GET:
      summary: Getidentityresolutionjob
      description: >-
        Returns information about an Identity Resolution Job in a specific
        domain.  Identity Resolution Jobs are set up using the Amazon Connect
        admin console. For more information, see Use Identity Resolution to
        consolidate similar profiles.
      operationId: amazonWebServicesGetIdentityResolutionJob
  /domains/{DomainName}/integrations:
    PUT:
      summary: Putintegration
      description: >-
        Adds an integration between the service and a third-party service, which
        includes Amazon AppFlow and Amazon Connect. An integration can belong to
        only one domain. To add or remove tags on an existing Integration, see 
        TagResource / UntagResource.
      operationId: amazonWebServicesPutIntegration
  /domains/{DomainName}/matches:
    POST:
      summary: Getsimilarprofiles
      description: >-
        Returns a set of profiles that belong to the same matching group using
        the matchId or profileId. You can also specify the type of matching that
        you want for finding similar profiles using either RULE_BASED_MATCHING
        or ML_BASED_MATCHING.
      operationId: amazonWebServicesGetSimilarProfiles
  /templates/{TemplateId}:
    GET:
      summary: Getprofileobjecttypetemplate
      description: >-
        Returns the template information for a specific object type. A template
        is a predefined ProfileObjectType, such as “Salesforce-Account” or
        “Salesforce-Contact.” When a user sends a ProfileObject, using the
        PutProfileObject API, with an ObjectTypeName that matches one of the
        TemplateIds, it uses the mappings from the template.
      operationId: amazonWebServicesGetProfileObjectTypeTemplate
  /domains/{DomainName}/workflows/{WorkflowId}/steps:
    GET:
      summary: Getworkflowsteps
      description: Get granular list of steps in workflow.
      operationId: amazonWebServicesGetWorkflowSteps
  /integrations:
    POST:
      summary: Listaccountintegrations
      description: >-
        Lists all of the integrations associated to a specific URI in the AWS
        account.
      operationId: amazonWebServicesListAccountIntegrations
  /domains/{DomainName}/calculated-attributes:
    GET:
      summary: Listcalculatedattributedefinitions
      description: Lists calculated attribute definitions for Customer Profiles
      operationId: amazonWebServicesListCalculatedAttributeDefinitions
  /domains/{DomainName}/profile/{ProfileId}/calculated-attributes:
    GET:
      summary: Listcalculatedattributesforprofile
      description: Retrieve a list of calculated attributes for a customer profile.
      operationId: amazonWebServicesListCalculatedAttributesForProfile
  /domains:
    GET:
      summary: Listdomains
      description: >-
        Returns a list of all the domains for an AWS account that have been
        created.
      operationId: amazonWebServicesListDomains
  /domains/{DomainName}/event-streams:
    GET:
      summary: Listeventstreams
      description: Returns a list of all the event streams in a specific domain.
      operationId: amazonWebServicesListEventStreams
  /domains/{DomainName}/identity-resolution-jobs:
    GET:
      summary: Listidentityresolutionjobs
      description: >-
        Lists all of the Identity Resolution Jobs in your domain. The response
        sorts the list by JobStartTime.
      operationId: amazonWebServicesListIdentityResolutionJobs
  /templates:
    GET:
      summary: Listprofileobjecttypetemplates
      description: Lists all of the template information for object types.
      operationId: amazonWebServicesListProfileObjectTypeTemplates
  /domains/{DomainName}/object-types:
    GET:
      summary: Listprofileobjecttypes
      description: Lists all of the templates available within the service.
      operationId: amazonWebServicesListProfileObjectTypes
  /domains/{DomainName}/profiles/objects:
    PUT:
      summary: Putprofileobject
      description: >-
        Adds additional objects to customer profiles of a given ObjectType. When
        adding a specific profile object, like a Contact Record, an inferred
        profile can get created if it is not mapped to an existing profile. The
        resulting profile will only have a phone number populated in the
        standard ProfileObject. Any additional Contact Records with the same
        phone number will be mapped to the same inferred profile. When a
        ProfileObject is created and if a ProfileObjectType already exists for
        the ProfileObject, it will provide data to a standard profile depending
        on the ProfileObjectType definition. PutProfileObject needs an
        ObjectType, which can be created using PutProfileObjectType.
      operationId: amazonWebServicesPutProfileObject
  /domains/{DomainName}/profiles/ruleBasedMatches:
    GET:
      summary: Listrulebasedmatches
      description: Returns a set of MatchIds that belong to the given domain.
      operationId: amazonWebServicesListRuleBasedMatches
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: >-
        Removes one or more tags from the specified Amazon Connect Customer
        Profiles resource. In Connect Customer Profiles, domains, profile object
        types, and integrations can be tagged.
      operationId: amazonWebServicesUntagResource
  /domains/{DomainName}/workflows:
    POST:
      summary: Listworkflows
      description: Query to list all workflows.
      operationId: amazonWebServicesListWorkflows
  /domains/{DomainName}/profiles/objects/merge:
    POST:
      summary: Mergeprofiles
      description: >-
        Runs an AWS Lambda job that does the following:   All the profileKeys in
        the ProfileToBeMerged will be moved to the main profile.   All the
        objects in the ProfileToBeMerged will be moved to the main profile.  
        All the ProfileToBeMerged will be deleted at the end.   All the
        profileKeys in the ProfileIdsToBeMerged will be moved to the main
        profile.   Standard fields are merged as follows:   Fields are always
        "union"-ed if there are no conflicts in standard fields or
        attributeKeys.   When there are conflicting fields:   If no
        SourceProfileIds entry is specified, the main Profile value is always
        taken.    If a SourceProfileIds entry is specified, the specified
        profileId is always taken, even if it is a NULL value.       You can use
        MergeProfiles together with GetMatches, which returns potentially
        matching profiles, or use it with the results of another matching
        system. After profiles have been merged, they cannot be separated
        (unmerged).
      operationId: amazonWebServicesMergeProfiles
  /domains/{DomainName}/profiles/search:
    POST:
      summary: Searchprofiles
      description: >-
        Searches for profiles within a specific domain using one or more
        predefined search keys (e.g., _fullName, _phone, _email, _account, etc.)
        and/or custom-defined search keys. A search key is a data type pair that
        consists of a KeyName and Values list. This operation supports searching
        for profiles with a minimum of 1 key-value(s) pair and up to 5
        key-value(s) pairs using either AND or OR logic.
      operationId: amazonWebServicesSearchProfiles
tags: []
