openapi: 3.1.0
info:
  title: databrew
  description: >-
    <p>Glue DataBrew is a visual, cloud-scale data-preparation service. DataBrew
    simplifies data preparation tasks, targeting data issues that are hard to
    spot and time-consuming to fix. DataBrew empowers users of all technical
    levels to visualize the data and perform one-click data transformations,
    with no coding required.</p>
paths:
  /recipes/{name}/batchDeleteRecipeVersion:
    POST:
      summary: Batchdeleterecipeversion
      description: >-
        Deletes one or more versions of a recipe at a time. The entire request
        will be rejected if:   The recipe does not exist.   There is an invalid
        version identifier in the list of versions.   The version list is
        empty.   The version list size exceeds 50.   The version list contains
        duplicate entries.   The request will complete successfully, but with
        partial failures, if:   A version does not exist.   A version is being
        used by a job.   You specify LATEST_WORKING, but it's being used by a
        project.   The version fails to be deleted.   The LATEST_WORKING version
        will only be deleted if the recipe has no other versions. If you try to
        delete LATEST_WORKING while other versions exist (or if they can't be
        deleted), then LATEST_WORKING will be listed as partial failure in the
        response.
      operationId: amazonWebServicesBatchDeleteRecipeVersion
  /datasets:
    GET:
      summary: Listdatasets
      description: Lists all of the DataBrew datasets.
      operationId: amazonWebServicesListDatasets
  /profileJobs:
    POST:
      summary: Createprofilejob
      description: Creates a new job to analyze a dataset and create its data profile.
      operationId: amazonWebServicesCreateProfileJob
  /projects:
    GET:
      summary: Listprojects
      description: Lists all of the DataBrew projects that are defined.
      operationId: amazonWebServicesListProjects
  /recipes:
    GET:
      summary: Listrecipes
      description: Lists all of the DataBrew recipes that are defined.
      operationId: amazonWebServicesListRecipes
  /recipeJobs:
    POST:
      summary: Createrecipejob
      description: >-
        Creates a new job to transform input data, using steps defined in an
        existing Glue DataBrew recipe
      operationId: amazonWebServicesCreateRecipeJob
  /rulesets:
    GET:
      summary: Listrulesets
      description: >-
        List all rulesets available in the current account or rulesets
        associated with a specific resource (dataset).
      operationId: amazonWebServicesListRulesets
  /schedules:
    GET:
      summary: Listschedules
      description: Lists the DataBrew schedules that are defined.
      operationId: amazonWebServicesListSchedules
  /datasets/{name}:
    PUT:
      summary: Updatedataset
      description: Modifies the definition of an existing DataBrew dataset.
      operationId: amazonWebServicesUpdateDataset
  /jobs/{name}:
    GET:
      summary: Describejob
      description: Returns the definition of a specific DataBrew job.
      operationId: amazonWebServicesDescribeJob
  /projects/{name}:
    PUT:
      summary: Updateproject
      description: Modifies the definition of an existing DataBrew project.
      operationId: amazonWebServicesUpdateProject
  /recipes/{name}/recipeVersion/{recipeVersion}:
    DELETE:
      summary: Deleterecipeversion
      description: Deletes a single version of a DataBrew recipe.
      operationId: amazonWebServicesDeleteRecipeVersion
  /rulesets/{name}:
    PUT:
      summary: Updateruleset
      description: Updates specified ruleset.
      operationId: amazonWebServicesUpdateRuleset
  /schedules/{name}:
    PUT:
      summary: Updateschedule
      description: Modifies the definition of an existing DataBrew schedule.
      operationId: amazonWebServicesUpdateSchedule
  /jobs/{name}/jobRun/{runId}:
    GET:
      summary: Describejobrun
      description: Represents one run of a DataBrew job.
      operationId: amazonWebServicesDescribeJobRun
  /recipes/{name}:
    PUT:
      summary: Updaterecipe
      description: >-
        Modifies the definition of the LATEST_WORKING version of a DataBrew
        recipe.
      operationId: amazonWebServicesUpdateRecipe
  /jobs/{name}/jobRuns:
    GET:
      summary: Listjobruns
      description: Lists all of the previous runs of a particular DataBrew job.
      operationId: amazonWebServicesListJobRuns
  /jobs:
    GET:
      summary: Listjobs
      description: Lists all of the DataBrew jobs that are defined.
      operationId: amazonWebServicesListJobs
  /recipeVersions:
    GET:
      summary: Listrecipeversions
      description: >-
        Lists the versions of a particular DataBrew recipe, except for
        LATEST_WORKING.
      operationId: amazonWebServicesListRecipeVersions
  /tags/{ResourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes metadata tags from a DataBrew resource.
      operationId: amazonWebServicesUntagResource
  /recipes/{name}/publishRecipe:
    POST:
      summary: Publishrecipe
      description: Publishes a new version of a DataBrew recipe.
      operationId: amazonWebServicesPublishRecipe
  /projects/{name}/sendProjectSessionAction:
    PUT:
      summary: Sendprojectsessionaction
      description: >-
        Performs a recipe step within an interactive DataBrew session that's
        currently open.
      operationId: amazonWebServicesSendProjectSessionAction
  /jobs/{name}/startJobRun:
    POST:
      summary: Startjobrun
      description: Runs a DataBrew job.
      operationId: amazonWebServicesStartJobRun
  /projects/{name}/startProjectSession:
    PUT:
      summary: Startprojectsession
      description: >-
        Creates an interactive session, enabling you to manipulate data in a
        DataBrew project.
      operationId: amazonWebServicesStartProjectSession
  /jobs/{name}/jobRun/{runId}/stopJobRun:
    POST:
      summary: Stopjobrun
      description: Stops a particular run of a job.
      operationId: amazonWebServicesStopJobRun
  /profileJobs/{name}:
    PUT:
      summary: Updateprofilejob
      description: Modifies the definition of an existing profile job.
      operationId: amazonWebServicesUpdateProfileJob
  /recipeJobs/{name}:
    PUT:
      summary: Updaterecipejob
      description: Modifies the definition of an existing DataBrew recipe job.
      operationId: amazonWebServicesUpdateRecipeJob
tags: []
