openapi: 3.1.0
info:
  title: datasync
  description: >-
    <fullname>DataSync</fullname> <p>DataSync is an online data movement and
    discovery service that simplifies data migration and helps you quickly,
    easily, and securely transfer your file or object data to, from, and between
    Amazon Web Services storage services.</p> <p>This API interface reference
    includes documentation for using DataSync programmatically. For complete
    information, see the <i> <a
    href="https://docs.aws.amazon.com/datasync/latest/userguide/what-is-datasync.html">DataSync
    User Guide</a> </i>.</p>
paths:
  /:
    POST:
      summary: Updatetaskexecution
      description: >-
        Updates the configuration of a running DataSync task execution. 
        Currently, the only Option that you can modify with UpdateTaskExecution
        is  BytesPerSecond , which throttles bandwidth for a running or queued
        task execution. 
      operationId: amazonWebServicesUpdateTaskExecution
tags: []
