openapi: 3.1.0
info:
  title: dataexchange
  description: >-
    <p>AWS Data Exchange is a service that makes it easy for AWS customers to
    exchange data in the cloud. You can use the AWS Data Exchange APIs to
    create, update, manage, and access file-based data set in the AWS Cloud.</p>
    <p>As a subscriber, you can view and access the data sets that you have an
    entitlement to through a subscription. You can use the APIs to download or
    copy your entitled data sets to Amazon Simple Storage Service (Amazon S3)
    for use across a variety of AWS analytics and machine learning services.</p>
    <p>As a provider, you can create and manage your data sets that you would
    like to publish to a product. Being able to package and provide your data
    sets into products requires a few steps to determine eligibility. For more
    information, visit the <i>AWS Data Exchange User Guide</i>.</p> <p>A data
    set is a collection of data that can be changed or updated over time. Data
    sets can be updated using revisions, which represent a new version or
    incremental change to a data set. A revision contains one or more assets. An
    asset in AWS Data Exchange is a piece of data that can be stored as an
    Amazon S3 object, Redshift datashare, API Gateway API, AWS Lake Formation
    data permission, or Amazon S3 data access. The asset can be a structured
    data file, an image file, or some other data file. Jobs are asynchronous
    import or export operations used to create or copy assets.</p>
paths:
  /v1/jobs/{JobId}:
    PATCH:
      summary: Startjob
      description: This operation starts a job.
      operationId: amazonWebServicesStartJob
  /v1/data-sets:
    GET:
      summary: Listdatasets
      description: >-
        This operation lists your data sets. When listing by origin OWNED,
        results are sorted by CreatedAt in descending order. When listing by
        origin ENTITLED, there is no order and the maxResults parameter is
        ignored.
      operationId: amazonWebServicesListDataSets
  /v1/event-actions:
    GET:
      summary: Listeventactions
      description: This operation lists your event actions.
      operationId: amazonWebServicesListEventActions
  /v1/jobs:
    GET:
      summary: Listjobs
      description: This operation lists your jobs sorted by CreatedAt in descending order.
      operationId: amazonWebServicesListJobs
  /v1/data-sets/{DataSetId}/revisions:
    GET:
      summary: Listdatasetrevisions
      description: >-
        This operation lists a data set's revisions sorted by CreatedAt in
        descending order.
      operationId: amazonWebServicesListDataSetRevisions
  /v1/data-sets/{DataSetId}/revisions/{RevisionId}/assets/{AssetId}:
    PATCH:
      summary: Updateasset
      description: This operation updates an asset.
      operationId: amazonWebServicesUpdateAsset
  /v1/data-sets/{DataSetId}:
    PATCH:
      summary: Updatedataset
      description: This operation updates a data set.
      operationId: amazonWebServicesUpdateDataSet
  /v1/event-actions/{EventActionId}:
    PATCH:
      summary: Updateeventaction
      description: This operation updates the event action.
      operationId: amazonWebServicesUpdateEventAction
  /v1/data-sets/{DataSetId}/revisions/{RevisionId}:
    PATCH:
      summary: Updaterevision
      description: This operation updates a revision.
      operationId: amazonWebServicesUpdateRevision
  /v1/data-sets/{DataSetId}/revisions/{RevisionId}/assets:
    GET:
      summary: Listrevisionassets
      description: >-
        This operation lists a revision's assets sorted alphabetically in
        descending order.
      operationId: amazonWebServicesListRevisionAssets
  /tags/{ResourceArn}:
    DELETE:
      summary: Untagresource
      description: This operation removes one or more tags from a resource.
      operationId: amazonWebServicesUntagResource
  /v1/data-sets/{DataSetId}/revisions/{RevisionId}/revoke:
    POST:
      summary: Revokerevision
      description: This operation revokes subscribers' access to a revision.
      operationId: amazonWebServicesRevokeRevision
  /v1:
    POST:
      summary: Sendapiasset
      description: >-
        This operation invokes an API Gateway API asset. The request is proxied
        to the provider’s API Gateway API.
      operationId: amazonWebServicesSendApiAsset
  /v1/data-sets/{DataSetId}/notification:
    POST:
      summary: Senddatasetnotification
      description: The type of event associated with the data set.
      operationId: amazonWebServicesSendDataSetNotification
tags: []
