openapi: 3.1.0
info:
  title: devops-guru
  description: >-
    <p> Amazon DevOps Guru is a fully managed service that helps you identify
    anomalous behavior in business critical operational applications. You
    specify the Amazon Web Services resources that you want DevOps Guru to
    cover, then the Amazon CloudWatch metrics and Amazon Web Services CloudTrail
    events related to those resources are analyzed. When anomalous behavior is
    detected, DevOps Guru creates an <i>insight</i> that includes
    recommendations, related events, and related metrics that can help you
    improve your operational applications. For more information, see <a
    href="https://docs.aws.amazon.com/devops-guru/latest/userguide/welcome.html">What
    is Amazon DevOps Guru</a>. </p> <p> You can specify 1 or 2 Amazon Simple
    Notification Service topics so you are notified every time a new insight is
    created. You can also enable DevOps Guru to generate an OpsItem in Amazon
    Web Services Systems Manager for each insight to help you manage and track
    your work addressing insights. </p> <p> To learn about the DevOps Guru
    workflow, see <a
    href="https://docs.aws.amazon.com/devops-guru/latest/userguide/welcome.html#how-it-works">How
    DevOps Guru works</a>. To learn about DevOps Guru concepts, see <a
    href="https://docs.aws.amazon.com/devops-guru/latest/userguide/concepts.html">Concepts
    in DevOps Guru</a>. </p>
paths:
  /channels:
    POST:
      summary: Listnotificationchannels
      description: ' Returns a list of notification channels configured for DevOps Guru. Each notification channel is used to notify you when DevOps Guru generates an insight that contains information about how to improve your operations. The one supported notification channel is Amazon Simple Notification Service (Amazon SNS). '
      operationId: amazonWebServicesListNotificationChannels
  /insights/{Id}:
    GET:
      summary: Describeinsight
      description: ' Returns details about an insight that you specify using its ID. '
      operationId: amazonWebServicesDescribeInsight
  /accounts/health:
    GET:
      summary: Describeaccounthealth
      description: ' Returns the number of open reactive insights, the number of open proactive insights, and the number of metrics analyzed in your Amazon Web Services account. Use these numbers to gauge the health of operations in your Amazon Web Services account. '
      operationId: amazonWebServicesDescribeAccountHealth
  /accounts/overview:
    POST:
      summary: Describeaccountoverview
      description: ' For the time range passed in, returns the number of open reactive insight that were created, the number of open proactive insights that were created, and the Mean Time to Recover (MTTR) for all closed reactive insights. '
      operationId: amazonWebServicesDescribeAccountOverview
  /anomalies/{Id}:
    GET:
      summary: Describeanomaly
      description: ' Returns details about an anomaly that you specify using its ID. '
      operationId: amazonWebServicesDescribeAnomaly
  /event-sources:
    PUT:
      summary: Updateeventsourcesconfig
      description: >-
        Enables or disables integration with a service that can be integrated
        with DevOps Guru. The one service that can be integrated with DevOps
        Guru is Amazon CodeGuru Profiler, which can produce proactive
        recommendations which can be stored and viewed in DevOps Guru.
      operationId: amazonWebServicesUpdateEventSourcesConfig
  /feedback:
    PUT:
      summary: Putfeedback
      description: ' Collects customer feedback about the specified insight. '
      operationId: amazonWebServicesPutFeedback
  /organization/health:
    POST:
      summary: Describeorganizationhealth
      description: >-
        Returns active insights, predictive insights, and resource hours
        analyzed in last hour.
      operationId: amazonWebServicesDescribeOrganizationHealth
  /organization/overview:
    POST:
      summary: Describeorganizationoverview
      description: >-
        Returns an overview of your organization's history based on the
        specified time range. The overview includes the total reactive and
        proactive insights.
      operationId: amazonWebServicesDescribeOrganizationOverview
  /organization/health/resource-collection:
    POST:
      summary: Describeorganizationresourcecollectionhealth
      description: >-
        Provides an overview of your system's health. If additional member
        accounts are part of your organization, you can filter those accounts
        using the AccountIds field.
      operationId: amazonWebServicesDescribeOrganizationResourceCollectionHealth
  /accounts/health/resource-collection/{ResourceCollectionType}:
    GET:
      summary: Describeresourcecollectionhealth
      description: ' Returns the number of open proactive insights, open reactive insights, and the Mean Time to Recover (MTTR) for all closed insights in resource collections in your account. You specify the type of Amazon Web Services resources collection. The two types of Amazon Web Services resource collections supported are Amazon Web Services CloudFormation stacks and Amazon Web Services resources that contain the same Amazon Web Services tag. DevOps Guru can be configured to analyze the Amazon Web Services resources that are defined in the stacks or that are tagged using the same tag key. You can specify up to 500 Amazon Web Services CloudFormation stacks. '
      operationId: amazonWebServicesDescribeResourceCollectionHealth
  /service-integrations:
    PUT:
      summary: Updateserviceintegration
      description: ' Enables or disables integration with a service that can be integrated with DevOps Guru. The one service that can be integrated with DevOps Guru is Amazon Web Services Systems Manager, which can be used to create an OpsItem for each generated insight. '
      operationId: amazonWebServicesUpdateServiceIntegration
  /cost-estimation:
    PUT:
      summary: Startcostestimation
      description: >-
        Starts the creation of an estimate of the monthly cost to analyze your
        Amazon Web Services resources.
      operationId: amazonWebServicesStartCostEstimation
  /resource-collections/{ResourceCollectionType}:
    GET:
      summary: Getresourcecollection
      description: ' Returns lists Amazon Web Services resources that are of the specified resource collection type. The two types of Amazon Web Services resource collections supported are Amazon Web Services CloudFormation stacks and Amazon Web Services resources that contain the same Amazon Web Services tag. DevOps Guru can be configured to analyze the Amazon Web Services resources that are defined in the stacks or that are tagged using the same tag key. You can specify up to 500 Amazon Web Services CloudFormation stacks. '
      operationId: amazonWebServicesGetResourceCollection
  /anomalies/insight/{InsightId}:
    POST:
      summary: Listanomaliesforinsight
      description: ' Returns a list of the anomalies that belong to an insight that you specify using its ID. '
      operationId: amazonWebServicesListAnomaliesForInsight
  /list-log-anomalies:
    POST:
      summary: Listanomalousloggroups
      description: ' Returns the list of log groups that contain log anomalies. '
      operationId: amazonWebServicesListAnomalousLogGroups
  /events:
    POST:
      summary: Listevents
      description: ' Returns a list of the events emitted by the resources that are evaluated by DevOps Guru. You can use filters to specify which events are returned. '
      operationId: amazonWebServicesListEvents
  /insights:
    POST:
      summary: Listinsights
      description: ' Returns a list of insights in your Amazon Web Services account. You can specify which insights are returned by their start time and status (ONGOING, CLOSED, or ANY). '
      operationId: amazonWebServicesListInsights
  /monitoredResources:
    POST:
      summary: Listmonitoredresources
      description: ' Returns the list of all log groups that are being monitored and tagged by DevOps Guru. '
      operationId: amazonWebServicesListMonitoredResources
  /organization/insights:
    POST:
      summary: Listorganizationinsights
      description: Returns a list of insights associated with the account or OU Id.
      operationId: amazonWebServicesListOrganizationInsights
  /recommendations:
    POST:
      summary: Listrecommendations
      description: ' Returns a list of a specified insight''s recommendations. Each recommendation includes a list of related metrics and a list of related events. '
      operationId: amazonWebServicesListRecommendations
  /channels/{Id}:
    DELETE:
      summary: Removenotificationchannel
      description: ' Removes a notification channel from DevOps Guru. A notification channel is used to notify you when DevOps Guru generates an insight that contains information about how to improve your operations. '
      operationId: amazonWebServicesRemoveNotificationChannel
  /insights/search:
    POST:
      summary: Searchinsights
      description: ' Returns a list of insights in your Amazon Web Services account. You can specify which insights are returned by their start time, one or more statuses (ONGOING or CLOSED), one or more severities (LOW, MEDIUM, and HIGH), and type (REACTIVE or PROACTIVE).   Use the Filters parameter to specify status and severity search parameters. Use the Type parameter to specify REACTIVE or PROACTIVE in your search. '
      operationId: amazonWebServicesSearchInsights
  /organization/insights/search:
    POST:
      summary: Searchorganizationinsights
      description: ' Returns a list of insights in your organization. You can specify which insights are returned by their start time, one or more statuses (ONGOING, CLOSED, and CLOSED), one or more severities (LOW, MEDIUM, and HIGH), and type (REACTIVE or PROACTIVE).   Use the Filters parameter to specify status and severity search parameters. Use the Type parameter to specify REACTIVE or PROACTIVE in your search. '
      operationId: amazonWebServicesSearchOrganizationInsights
  /resource-collections:
    PUT:
      summary: Updateresourcecollection
      description: ' Updates the collection of resources that DevOps Guru analyzes. The two types of Amazon Web Services resource collections supported are Amazon Web Services CloudFormation stacks and Amazon Web Services resources that contain the same Amazon Web Services tag. DevOps Guru can be configured to analyze the Amazon Web Services resources that are defined in the stacks or that are tagged using the same tag key. You can specify up to 500 Amazon Web Services CloudFormation stacks. This method also creates the IAM role required for you to use DevOps Guru. '
      operationId: amazonWebServicesUpdateResourceCollection
tags: []
