openapi: 3.1.0
info:
  title: dlm
  description: >-
    <fullname>Amazon Data Lifecycle Manager</fullname> <p>With Amazon Data
    Lifecycle Manager, you can manage the lifecycle of your Amazon Web Services
    resources. You create lifecycle policies, which are used to automate
    operations on the specified resources.</p> <p>Amazon Data Lifecycle Manager
    supports Amazon EBS volumes and snapshots. For information about using
    Amazon Data Lifecycle Manager with Amazon EBS, see <a
    href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/snapshot-lifecycle.html">
    Amazon Data Lifecycle Manager</a> in the <i>Amazon EC2 User Guide</i>.</p>
paths:
  /policies:
    GET:
      summary: Getlifecyclepolicies
      description: >-
        Gets summary information about all or the specified data lifecycle
        policies. To get complete information about a policy, use
        GetLifecyclePolicy.
      operationId: amazonWebServicesGetLifecyclePolicies
  /policies/{policyId}:
    PATCH:
      summary: Updatelifecyclepolicy
      description: >-
        Updates the specified lifecycle policy. For more information about
        updating a policy, see Modify lifecycle policies.
      operationId: amazonWebServicesUpdateLifecyclePolicy
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes the specified tags from the specified resource.
      operationId: amazonWebServicesUntagResource
tags: []
