openapi: 3.1.0
info:
  title: docdb
  description: >-
    <p>Amazon DocumentDB is a fast, reliable, and fully managed database
    service. Amazon DocumentDB makes it easy to set up, operate, and scale
    MongoDB-compatible databases in the cloud. With Amazon DocumentDB, you can
    run the same application code and use the same drivers and tools that you
    use with MongoDB.</p>
paths:
  /:
    POST:
      summary: Stopdbcluster
      description: >-
        Stops the running cluster that is specified by DBClusterIdentifier. The
        cluster must be in the available state. For more information, see
        Stopping and Starting an Amazon DocumentDB Cluster.
      operationId: amazonWebServicesStopDBCluster
tags: []
