openapi: 3.1.0
info:
  title: docdb-elastic
  description: <p>The new Amazon Elastic DocumentDB service endpoint.</p>
paths:
  /cluster:
    POST:
      summary: Createcluster
      description: >-
        Creates a new Elastic DocumentDB cluster and returns its Cluster
        structure.
      operationId: amazonWebServicesCreateCluster
  /cluster-snapshot:
    POST:
      summary: Createclustersnapshot
      description: Creates a snapshot of a cluster.
      operationId: amazonWebServicesCreateClusterSnapshot
  /cluster/{clusterArn}:
    PUT:
      summary: Updatecluster
      description: >-
        Modifies a Elastic DocumentDB cluster. This includes updating
        admin-username/password, upgrading API version setting up a backup
        window and maintenance window
      operationId: amazonWebServicesUpdateCluster
  /cluster-snapshot/{snapshotArn}:
    GET:
      summary: Getclustersnapshot
      description: Returns information about a specific Elastic DocumentDB snapshot
      operationId: amazonWebServicesGetClusterSnapshot
  /cluster-snapshots:
    GET:
      summary: Listclustersnapshots
      description: >-
        Returns information about Elastic DocumentDB snapshots for a specified
        cluster.
      operationId: amazonWebServicesListClusterSnapshots
  /clusters:
    GET:
      summary: Listclusters
      description: Returns information about provisioned Elastic DocumentDB clusters.
      operationId: amazonWebServicesListClusters
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes metadata tags to a Elastic DocumentDB resource
      operationId: amazonWebServicesUntagResource
  /cluster-snapshot/{snapshotArn}/restore:
    POST:
      summary: Restoreclusterfromsnapshot
      description: Restores a Elastic DocumentDB cluster from a snapshot.
      operationId: amazonWebServicesRestoreClusterFromSnapshot
tags: []
