openapi: 3.1.0
info:
  title: dynamodb
  description: >-
    <fullname>Amazon DynamoDB</fullname> <p>Amazon DynamoDB is a fully managed
    NoSQL database service that provides fast and predictable performance with
    seamless scalability. DynamoDB lets you offload the administrative burdens
    of operating and scaling a distributed database, so that you don't have to
    worry about hardware provisioning, setup and configuration, replication,
    software patching, or cluster scaling.</p> <p>With DynamoDB, you can create
    database tables that can store and retrieve any amount of data, and serve
    any level of request traffic. You can scale up or scale down your tables'
    throughput capacity without downtime or performance degradation, and use the
    Amazon Web Services Management Console to monitor resource utilization and
    performance metrics.</p> <p>DynamoDB automatically spreads the data and
    traffic for your tables over a sufficient number of servers to handle your
    throughput and storage requirements, while maintaining consistent and fast
    performance. All of your data is stored on solid state disks (SSDs) and
    automatically replicated across multiple Availability Zones in an Amazon Web
    Services Region, providing built-in high availability and data
    durability.</p>
paths:
  /:
    POST:
      summary: Updatetimetolive
      description: >-
        The UpdateTimeToLive method enables or disables Time to Live (TTL) for
        the specified table. A successful UpdateTimeToLive call returns the
        current TimeToLiveSpecification. It can take up to one hour for the
        change to fully process. Any additional UpdateTimeToLive calls for the
        same table during this one hour duration result in a
        ValidationException.  TTL compares the current time in epoch time format
        to the time stored in the TTL attribute of an item. If the epoch time
        value stored in the attribute is less than the current time, the item is
        marked as expired and subsequently deleted.   The epoch time format is
        the number of seconds elapsed since 12:00:00 AM January 1, 1970 UTC.  
        DynamoDB deletes expired items on a best-effort basis to ensure
        availability of throughput for other data operations.   DynamoDB
        typically deletes expired items within two days of expiration. The exact
        duration within which an item gets deleted after expiration is specific
        to the nature of the workload. Items that have expired and not been
        deleted will still show up in reads, queries, and scans.  As items are
        deleted, they are removed from any local secondary index and global
        secondary index immediately in the same eventually consistent way as a
        standard delete operation. For more information, see Time To Live in the
        Amazon DynamoDB Developer Guide. 
      operationId: amazonWebServicesUpdateTimeToLive
tags: []
