openapi: 3.1.0
info:
  title: ec2-instance-connect
  description: >-
    <p>Amazon EC2 Instance Connect enables system administrators to publish
    one-time use SSH public keys to EC2, providing users a simple and secure way
    to connect to their instances.</p>
paths:
  /:
    POST:
      summary: Sendserialconsolesshpublickey
      description: >-
        Pushes an SSH public key to the specified EC2 instance. The key remains
        for 60 seconds, which gives you 60 seconds to establish a serial console
        connection to the instance using SSH. For more information, see EC2
        Serial Console in the Amazon EC2 User Guide.
      operationId: amazonWebServicesSendSerialConsoleSSHPublicKey
tags: []
