openapi: 3.1.0
info:
  title: ecr-public
  description: >-
    <fullname>Amazon Elastic Container Registry Public</fullname> <p>Amazon
    Elastic Container Registry Public (Amazon ECR Public) is a managed container
    image registry service. Amazon ECR provides both public and private
    registries to host your container images. You can use the Docker CLI or your
    preferred client to push, pull, and manage images. Amazon ECR provides a
    secure, scalable, and reliable registry for your Docker or Open Container
    Initiative (OCI) images. Amazon ECR supports public repositories with this
    API. For information about the Amazon ECR API for private repositories, see
    <a
    href="https://docs.aws.amazon.com/AmazonECR/latest/APIReference/Welcome.html">Amazon
    Elastic Container Registry API Reference</a>.</p>
paths:
  /:
    POST:
      summary: Uploadlayerpart
      description: >-
        Uploads an image layer part to Amazon ECR. When an image is pushed, each
        new image layer is uploaded in parts. The maximum size of each image
        layer part can be 20971520 bytes (about 20MB). The UploadLayerPart API
        is called once for each new image layer part.  This operation is used by
        the Amazon ECR proxy and is not generally used by customers for pulling
        and pushing images. In most cases, you should use the docker CLI to
        pull, tag, and push images. 
      operationId: amazonWebServicesUploadLayerPart
tags: []
