openapi: 3.1.0
info:
  title: eks-auth
  description: >-
    <p>The Amazon EKS Auth API and the <code>AssumeRoleForPodIdentity</code>
    action are only used by the EKS Pod Identity Agent.</p>
paths:
  /clusters/{clusterName}/assume-role-for-pod-identity:
    POST:
      summary: Assumeroleforpodidentity
      description: >-
        The Amazon EKS Auth API and the AssumeRoleForPodIdentity action are only
        used by the EKS Pod Identity Agent. We recommend that applications use
        the Amazon Web Services SDKs to connect to Amazon Web Services services;
        if credentials from an EKS Pod Identity association are available in the
        pod, the latest versions of the SDKs use them automatically.
      operationId: amazonWebServicesAssumeRoleForPodIdentity
tags: []
