openapi: 3.1.0
info:
  title: elasticfilesystem
  description: >-
    <fullname>Amazon Elastic File System</fullname> <p>Amazon Elastic File
    System (Amazon EFS) provides simple, scalable file storage for use with
    Amazon EC2 Linux and Mac instances in the Amazon Web Services Cloud. With
    Amazon EFS, storage capacity is elastic, growing and shrinking automatically
    as you add and remove files, so that your applications have the storage they
    need, when they need it. For more information, see the <a
    href="https://docs.aws.amazon.com/efs/latest/ug/api-reference.html">Amazon
    Elastic File System API Reference</a> and the <a
    href="https://docs.aws.amazon.com/efs/latest/ug/whatisefs.html">Amazon
    Elastic File System User Guide</a>.</p>
paths:
  /2015-02-01/access-points:
    GET:
      summary: Describeaccesspoints
      description: >-
        Returns the description of a specific Amazon EFS access point if the
        AccessPointId is provided. If you provide an EFS FileSystemId, it
        returns descriptions of all access points for that file system. You can
        provide either an AccessPointId or a FileSystemId in the request, but
        not both.  This operation requires permissions for the
        elasticfilesystem:DescribeAccessPoints action.
      operationId: amazonWebServicesDescribeAccessPoints
  /2015-02-01/file-systems:
    GET:
      summary: Describefilesystems
      description: >-
        Returns the description of a specific Amazon EFS file system if either
        the file system CreationToken or the FileSystemId is provided.
        Otherwise, it returns descriptions of all file systems owned by the
        caller's Amazon Web Services account in the Amazon Web Services Region
        of the endpoint that you're calling. When retrieving all file system
        descriptions, you can optionally specify the MaxItems parameter to limit
        the number of descriptions in a response. This number is automatically
        set to 100. If more file system descriptions remain, Amazon EFS returns
        a NextMarker, an opaque token, in the response. In this case, you should
        send a subsequent request with the Marker request parameter set to the
        value of NextMarker.  To retrieve a list of your file system
        descriptions, this operation is used in an iterative process, where
        DescribeFileSystems is called first without the Marker and then the
        operation continues to call it with the Marker parameter set to the
        value of the NextMarker from the previous response until the response
        has no NextMarker.   The order of file systems returned in the response
        of one DescribeFileSystems call and the order of file systems returned
        across the responses of a multi-call iteration is unspecified.   This
        operation requires permissions for the
        elasticfilesystem:DescribeFileSystems action. 
      operationId: amazonWebServicesDescribeFileSystems
  /2015-02-01/mount-targets:
    GET:
      summary: Describemounttargets
      description: >-
        Returns the descriptions of all the current mount targets, or a specific
        mount target, for a file system. When requesting all of the current
        mount targets, the order of mount targets returned in the response is
        unspecified. This operation requires permissions for the
        elasticfilesystem:DescribeMountTargets action, on either the file system
        ID that you specify in FileSystemId, or on the file system of the mount
        target that you specify in MountTargetId.
      operationId: amazonWebServicesDescribeMountTargets
  /2015-02-01/file-systems/{SourceFileSystemId}/replication-configuration:
    DELETE:
      summary: Deletereplicationconfiguration
      description: >-
        Deletes a replication configuration. Deleting a replication
        configuration ends the replication process. After a replication
        configuration is deleted, the destination file system becomes Writeable
        and its replication overwrite protection is re-enabled. For more
        information, see Delete a replication configuration. This operation
        requires permissions for the
        elasticfilesystem:DeleteReplicationConfiguration action. 
      operationId: amazonWebServicesDeleteReplicationConfiguration
  /2015-02-01/create-tags/{FileSystemId}:
    POST:
      summary: Createtags
      description: ' DEPRECATED - CreateTags is deprecated and not maintained. To create tags for EFS resources, use the API action.  Creates or overwrites tags associated with a file system. Each tag is a key-value pair. If a tag key specified in the request already exists on the file system, this operation overwrites its value with the value provided in the request. If you add the Name tag to your file system, Amazon EFS returns it in the response to the DescribeFileSystems operation.  This operation requires permission for the elasticfilesystem:CreateTags action.'
      operationId: amazonWebServicesCreateTags
  /2015-02-01/access-points/{AccessPointId}:
    DELETE:
      summary: Deleteaccesspoint
      description: >-
        Deletes the specified access point. After deletion is complete, new
        clients can no longer connect to the access points. Clients connected to
        the access point at the time of deletion will continue to function until
        they terminate their connection. This operation requires permissions for
        the elasticfilesystem:DeleteAccessPoint action.
      operationId: amazonWebServicesDeleteAccessPoint
  /2015-02-01/file-systems/{FileSystemId}:
    PUT:
      summary: Updatefilesystem
      description: >-
        Updates the throughput mode or the amount of provisioned throughput of
        an existing file system.
      operationId: amazonWebServicesUpdateFileSystem
  /2015-02-01/file-systems/{FileSystemId}/policy:
    PUT:
      summary: Putfilesystempolicy
      description: >-
        Applies an Amazon EFS FileSystemPolicy to an Amazon EFS file system. A
        file system policy is an IAM resource-based policy and can contain
        multiple policy statements. A file system always has exactly one file
        system policy, which can be the default policy or an explicit policy set
        or updated using this API operation. EFS file system policies have a
        20,000 character limit. When an explicit policy is set, it overrides the
        default policy. For more information about the default file system
        policy, see Default EFS File System Policy.   EFS file system policies
        have a 20,000 character limit.  This operation requires permissions for
        the elasticfilesystem:PutFileSystemPolicy action.
      operationId: amazonWebServicesPutFileSystemPolicy
  /2015-02-01/mount-targets/{MountTargetId}:
    DELETE:
      summary: Deletemounttarget
      description: >-
        Deletes the specified mount target. This operation forcibly breaks any
        mounts of the file system by using the mount target that is being
        deleted, which might disrupt instances or applications using those
        mounts. To avoid applications getting cut off abruptly, you might
        consider unmounting any mounts of the mount target, if feasible. The
        operation also deletes the associated network interface. Uncommitted
        writes might be lost, but breaking a mount target using this operation
        does not corrupt the file system itself. The file system you created
        remains. You can mount an EC2 instance in your VPC by using another
        mount target. This operation requires permissions for the following
        action on the file system:    elasticfilesystem:DeleteMountTarget    
        The DeleteMountTarget call returns while the mount target state is still
        deleting. You can check the mount target deletion by calling the
        DescribeMountTargets operation, which returns a list of mount target
        descriptions for the given file system.   The operation also requires
        permissions for the following Amazon EC2 action on the mount target's
        network interface:    ec2:DeleteNetworkInterface   
      operationId: amazonWebServicesDeleteMountTarget
  /2015-02-01/delete-tags/{FileSystemId}:
    POST:
      summary: Deletetags
      description: ' DEPRECATED - DeleteTags is deprecated and not maintained. To remove tags from EFS resources, use the API action.  Deletes the specified tags from a file system. If the DeleteTags request includes a tag key that doesn''t exist, Amazon EFS ignores it and doesn''t cause an error. For more information about tags and related restrictions, see Tag restrictions in the Billing and Cost Management User Guide. This operation requires permissions for the elasticfilesystem:DeleteTags action.'
      operationId: amazonWebServicesDeleteTags
  /2015-02-01/account-preferences:
    PUT:
      summary: Putaccountpreferences
      description: >-
        Use this operation to set the account preference in the current Amazon
        Web Services Region to use long 17 character (63 bit) or short 8
        character (32 bit) resource IDs for new EFS file system and mount target
        resources. All existing resource IDs are not affected by any changes you
        make. You can set the ID preference during the opt-in period as EFS
        transitions to long resource IDs. For more information, see Managing
        Amazon EFS resource IDs.  Starting in October, 2021, you will receive an
        error if you try to set the account preference to use the short 8
        character format resource ID. Contact Amazon Web Services support if you
        receive an error and must use short IDs for file system and mount target
        resources. 
      operationId: amazonWebServicesPutAccountPreferences
  /2015-02-01/file-systems/{FileSystemId}/backup-policy:
    PUT:
      summary: Putbackuppolicy
      description: >-
        Updates the file system's backup policy. Use this action to start or
        stop automatic backups of the file system. 
      operationId: amazonWebServicesPutBackupPolicy
  /2015-02-01/file-systems/{FileSystemId}/lifecycle-configuration:
    PUT:
      summary: Putlifecycleconfiguration
      description: >-
        Use this action to manage storage for your file system. A
        LifecycleConfiguration consists of one or more LifecyclePolicy objects
        that define the following:     TransitionToIA  – When to move files in
        the file system from primary storage (Standard storage class) into the
        Infrequent Access (IA) storage.     TransitionToArchive  – When to move
        files in the file system from their current storage class (either IA or
        Standard storage) into the Archive storage. File systems cannot
        transition into Archive storage before transitioning into IA storage.
        Therefore, TransitionToArchive must either not be set or must be later
        than TransitionToIA.   The Archive storage class is available only for
        file systems that use the Elastic Throughput mode and the General
        Purpose Performance mode.         TransitionToPrimaryStorageClass  –
        Whether to move files in the file system back to primary storage
        (Standard storage class) after they are accessed in IA or Archive
        storage.   For more information, see  Managing file system storage. Each
        Amazon EFS file system supports one lifecycle configuration, which
        applies to all files in the file system. If a LifecycleConfiguration
        object already exists for the specified file system, a
        PutLifecycleConfiguration call modifies the existing configuration. A
        PutLifecycleConfiguration call with an empty LifecyclePolicies array in
        the request body deletes any existing LifecycleConfiguration. In the
        request, specify the following:    The ID for the file system for which
        you are enabling, disabling, or modifying Lifecycle management.   A
        LifecyclePolicies array of LifecyclePolicy objects that define when to
        move files to IA storage, to Archive storage, and back to primary
        storage.  Amazon EFS requires that each LifecyclePolicy object have only
        have a single transition, so the LifecyclePolicies array needs to be
        structured with separate LifecyclePolicy objects. See the example
        requests in the following section for more information.    This
        operation requires permissions for the
        elasticfilesystem:PutLifecycleConfiguration operation. To apply a
        LifecycleConfiguration object to an encrypted file system, you need the
        same Key Management Service permissions as when you created the
        encrypted file system.
      operationId: amazonWebServicesPutLifecycleConfiguration
  /2015-02-01/mount-targets/{MountTargetId}/security-groups:
    PUT:
      summary: Modifymounttargetsecuritygroups
      description: >-
        Modifies the set of security groups in effect for a mount target. When
        you create a mount target, Amazon EFS also creates a new network
        interface. For more information, see CreateMountTarget. This operation
        replaces the security groups in effect for the network interface
        associated with a mount target, with the SecurityGroups provided in the
        request. This operation requires that the network interface of the mount
        target has been created and the lifecycle state of the mount target is
        not deleted.  The operation requires permissions for the following
        actions:    elasticfilesystem:ModifyMountTargetSecurityGroups action on
        the mount target's file system.     ec2:ModifyNetworkInterfaceAttribute
        action on the mount target's network interface.   
      operationId: amazonWebServicesModifyMountTargetSecurityGroups
  /2015-02-01/file-systems/replication-configurations:
    GET:
      summary: Describereplicationconfigurations
      description: >-
        Retrieves the replication configuration for a specific file system. If a
        file system is not specified, all of the replication configurations for
        the Amazon Web Services account in an Amazon Web Services Region are
        retrieved.
      operationId: amazonWebServicesDescribeReplicationConfigurations
  /2015-02-01/tags/{FileSystemId}/:
    GET:
      summary: Describetags
      description: ' DEPRECATED - The DescribeTags action is deprecated and not maintained. To view tags associated with EFS resources, use the ListTagsForResource API action.  Returns the tags associated with a file system. The order of tags returned in the response of one DescribeTags call and the order of tags returned across the responses of a multiple-call iteration (when using pagination) is unspecified.   This operation requires permissions for the elasticfilesystem:DescribeTags action. '
      operationId: amazonWebServicesDescribeTags
  /2015-02-01/resource-tags/{ResourceId}:
    DELETE:
      summary: Untagresource
      description: >-
        Removes tags from an EFS resource. You can remove tags from EFS file
        systems and access points using this API operation. This operation
        requires permissions for the elasticfilesystem:UntagResource action.
      operationId: amazonWebServicesUntagResource
  /2015-02-01/file-systems/{FileSystemId}/protection:
    PUT:
      summary: Updatefilesystemprotection
      description: >-
        Updates protection on the file system. This operation requires
        permissions for the elasticfilesystem:UpdateFileSystemProtection
        action. 
      operationId: amazonWebServicesUpdateFileSystemProtection
tags: []
