openapi: 3.1.0
info:
  title: elastic-inference
  description: >-
    <p> Elastic Inference public APIs. </p> <p> February 15, 2023: Starting
    April 15, 2023, AWS will not onboard new customers to Amazon Elastic
    Inference (EI), and will help current customers migrate their workloads to
    options that offer better price and performance. After April 15, 2023, new
    customers will not be able to launch instances with Amazon EI accelerators
    in Amazon SageMaker, Amazon ECS, or Amazon EC2. However, customers who have
    used Amazon EI at least once during the past 30-day period are considered
    current customers and will be able to continue using the service. </p>
paths:
  /describe-accelerator-offerings:
    POST:
      summary: Describeacceleratorofferings
      description: ' Describes the locations in which a given accelerator type or set of types is present in a given region.   February 15, 2023: Starting April 15, 2023, AWS will not onboard new customers to Amazon Elastic Inference (EI), and will help current customers migrate their workloads to options that offer better price and performance. After April 15, 2023, new customers will not be able to launch instances with Amazon EI accelerators in Amazon SageMaker, Amazon ECS, or Amazon EC2. However, customers who have used Amazon EI at least once during the past 30-day period are considered current customers and will be able to continue using the service. '
      operationId: amazonWebServicesDescribeAcceleratorOfferings
  /describe-accelerator-types:
    GET:
      summary: Describeacceleratortypes
      description: ' Describes the accelerator types available in a given region, as well as their characteristics, such as memory and throughput.   February 15, 2023: Starting April 15, 2023, AWS will not onboard new customers to Amazon Elastic Inference (EI), and will help current customers migrate their workloads to options that offer better price and performance. After April 15, 2023, new customers will not be able to launch instances with Amazon EI accelerators in Amazon SageMaker, Amazon ECS, or Amazon EC2. However, customers who have used Amazon EI at least once during the past 30-day period are considered current customers and will be able to continue using the service. '
      operationId: amazonWebServicesDescribeAcceleratorTypes
  /describe-accelerators:
    POST:
      summary: Describeaccelerators
      description: ' Describes information over a provided set of accelerators belonging to an account.   February 15, 2023: Starting April 15, 2023, AWS will not onboard new customers to Amazon Elastic Inference (EI), and will help current customers migrate their workloads to options that offer better price and performance. After April 15, 2023, new customers will not be able to launch instances with Amazon EI accelerators in Amazon SageMaker, Amazon ECS, or Amazon EC2. However, customers who have used Amazon EI at least once during the past 30-day period are considered current customers and will be able to continue using the service. '
      operationId: amazonWebServicesDescribeAccelerators
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: ' Removes the specified tags from an Elastic Inference Accelerator.   February 15, 2023: Starting April 15, 2023, AWS will not onboard new customers to Amazon Elastic Inference (EI), and will help current customers migrate their workloads to options that offer better price and performance. After April 15, 2023, new customers will not be able to launch instances with Amazon EI accelerators in Amazon SageMaker, Amazon ECS, or Amazon EC2. However, customers who have used Amazon EI at least once during the past 30-day period are considered current customers and will be able to continue using the service. '
      operationId: amazonWebServicesUntagResource
tags: []
