openapi: 3.1.0
info:
  title: elasticloadbalancing
  description: >-
    <fullname>Elastic Load Balancing</fullname> <p>A load balancer can
    distribute incoming traffic across your EC2 instances. This enables you to
    increase the availability of your application. The load balancer also
    monitors the health of its registered instances and ensures that it routes
    traffic only to healthy instances. You configure your load balancer to
    accept incoming traffic by specifying one or more listeners, which are
    configured with a protocol and port number for connections from clients to
    the load balancer and a protocol and port number for connections from the
    load balancer to the instances.</p> <p>Elastic Load Balancing supports three
    types of load balancers: Application Load Balancers, Network Load Balancers,
    and Classic Load Balancers. You can select a load balancer based on your
    application needs. For more information, see the <a
    href="https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/">Elastic
    Load Balancing User Guide</a>.</p> <p>This reference covers the 2012-06-01
    API, which supports Classic Load Balancers. The 2015-12-01 API supports
    Application Load Balancers and Network Load Balancers.</p> <p>To get
    started, create a load balancer with one or more listeners using
    <a>CreateLoadBalancer</a>. Register your instances with the load balancer
    using <a>RegisterInstancesWithLoadBalancer</a>.</p> <p>All Elastic Load
    Balancing operations are <i>idempotent</i>, which means that they complete
    at most one time. If you repeat an operation, it succeeds with a 200 OK
    response code.</p>
paths:
  /:
    POST:
      summary: Setloadbalancerpoliciesoflistener
      description: >-
        Replaces the current set of policies for the specified load balancer
        port with the specified set of policies. To enable back-end server
        authentication, use SetLoadBalancerPoliciesForBackendServer. For more
        information about setting policies, see Update the SSL Negotiation
        Configuration, Duration-Based Session Stickiness, and
        Application-Controlled Session Stickiness in the Classic Load Balancers
        Guide.
      operationId: amazonWebServicesSetLoadBalancerPoliciesOfListener
tags: []
