openapi: 3.1.0
info:
  title: emr-serverless
  description: >-
    <p>Amazon EMR Serverless is a new deployment option for Amazon EMR. Amazon
    EMR Serverless provides a serverless runtime environment that simplifies
    running analytics applications using the latest open source frameworks such
    as Apache Spark and Apache Hive. With Amazon EMR Serverless, you don’t have
    to configure, optimize, secure, or operate clusters to run applications with
    these frameworks.</p> <p>The API reference to Amazon EMR Serverless is
    <code>emr-serverless</code>. The <code>emr-serverless</code> prefix is used
    in the following scenarios: </p> <ul> <li> <p>It is the prefix in the CLI
    commands for Amazon EMR Serverless. For example, <code>aws emr-serverless
    start-job-run</code>.</p> </li> <li> <p>It is the prefix before IAM policy
    actions for Amazon EMR Serverless. For example, <code>"Action":
    ["emr-serverless:StartJobRun"]</code>. For more information, see <a
    href="https://docs.aws.amazon.com/emr/latest/EMR-Serverless-UserGuide/security_iam_service-with-iam.html#security_iam_service-with-iam-id-based-policies-actions">Policy
    actions for Amazon EMR Serverless</a>.</p> </li> <li> <p>It is the prefix
    used in Amazon EMR Serverless service endpoints. For example,
    <code>emr-serverless.us-east-2.amazonaws.com</code>.</p> </li> </ul>
paths:
  /applications/{applicationId}/jobruns/{jobRunId}:
    GET:
      summary: Getjobrun
      description: Displays detailed information about a job run.
      operationId: amazonWebServicesGetJobRun
  /applications:
    GET:
      summary: Listapplications
      description: Lists applications based on a set of parameters.
      operationId: amazonWebServicesListApplications
  /applications/{applicationId}:
    PATCH:
      summary: Updateapplication
      description: >-
        Updates a specified application. An application has to be in a stopped
        or created state in order to be updated.
      operationId: amazonWebServicesUpdateApplication
  /applications/{applicationId}/jobruns/{jobRunId}/dashboard:
    GET:
      summary: Getdashboardforjobrun
      description: >-
        Creates and returns a URL that you can use to access the application UIs
        for a job run. For jobs in a running state, the application UI is a live
        user interface such as the Spark or Tez web UI. For completed jobs, the
        application UI is a persistent application user interface such as the
        Spark History Server or persistent Tez UI.  The URL is valid for one
        hour after you generate it. To access the application UI after that hour
        elapses, you must invoke the API again to generate a new URL. 
      operationId: amazonWebServicesGetDashboardForJobRun
  /applications/{applicationId}/jobruns:
    POST:
      summary: Startjobrun
      description: Starts a job run.
      operationId: amazonWebServicesStartJobRun
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes tags from resources.
      operationId: amazonWebServicesUntagResource
  /applications/{applicationId}/start:
    POST:
      summary: Startapplication
      description: >-
        Starts a specified application and initializes initial capacity if
        configured.
      operationId: amazonWebServicesStartApplication
  /applications/{applicationId}/stop:
    POST:
      summary: Stopapplication
      description: >-
        Stops a specified application and releases initial capacity if
        configured. All scheduled and running jobs must be completed or
        cancelled before stopping an application.
      operationId: amazonWebServicesStopApplication
tags: []
