openapi: 3.1.0
info:
  title: entityresolution
  description: >-
    <p>Welcome to the <i>Entity Resolution API Reference</i>.</p> <p>Entity
    Resolution is an Amazon Web Services service that provides pre-configured
    entity resolution capabilities that enable developers and analysts at
    advertising and marketing companies to build an accurate and complete view
    of their consumers.</p> <p> With Entity Resolution, you can match source
    records containing consumer identifiers, such as name, email address, and
    phone number. This is true even when these records have incomplete or
    conflicting identifiers. For example, Entity Resolution can effectively
    match a source record from a customer relationship management (CRM) system
    with a source record from a marketing system containing campaign
    information.</p> <p>To learn more about Entity Resolution concepts,
    procedures, and best practices, see the <a
    href="https://docs.aws.amazon.com/entityresolution/latest/userguide/what-is-service.html">Entity
    Resolution User Guide</a>.</p>
paths:
  /idmappingworkflows:
    GET:
      summary: Listidmappingworkflows
      description: >-
        Returns a list of all the IdMappingWorkflows that have been created for
        an Amazon Web Services account.
      operationId: amazonWebServicesListIdMappingWorkflows
  /matchingworkflows:
    GET:
      summary: Listmatchingworkflows
      description: >-
        Returns a list of all the MatchingWorkflows that have been created for
        an Amazon Web Services account.
      operationId: amazonWebServicesListMatchingWorkflows
  /schemas:
    GET:
      summary: Listschemamappings
      description: >-
        Returns a list of all the SchemaMappings that have been created for an
        Amazon Web Services account.
      operationId: amazonWebServicesListSchemaMappings
  /idmappingworkflows/{workflowName}:
    PUT:
      summary: Updateidmappingworkflow
      description: >-
        Updates an existing IdMappingWorkflow. This method is identical to
        CreateIdMappingWorkflow, except it uses an HTTP PUT request instead of a
        POST request, and the IdMappingWorkflow must already exist for the
        method to succeed.
      operationId: amazonWebServicesUpdateIdMappingWorkflow
  /matchingworkflows/{workflowName}:
    PUT:
      summary: Updatematchingworkflow
      description: >-
        Updates an existing MatchingWorkflow. This method is identical to
        CreateMatchingWorkflow, except it uses an HTTP PUT request instead of a
        POST request, and the MatchingWorkflow must already exist for the method
        to succeed.
      operationId: amazonWebServicesUpdateMatchingWorkflow
  /schemas/{schemaName}:
    PUT:
      summary: Updateschemamapping
      description: >-
        Updates a schema mapping.  A schema is immutable if it is being used by
        a workflow. Therefore, you can't update a schema mapping if it's
        associated with a workflow.  
      operationId: amazonWebServicesUpdateSchemaMapping
  /idmappingworkflows/{workflowName}/jobs/{jobId}:
    GET:
      summary: Getidmappingjob
      description: >-
        Gets the status, metrics, and errors (if there are any) that are
        associated with a job.
      operationId: amazonWebServicesGetIdMappingJob
  /matchingworkflows/{workflowName}/matches:
    POST:
      summary: Getmatchid
      description: >-
        Returns the corresponding Match ID of a customer record if the record
        has been processed.
      operationId: amazonWebServicesGetMatchId
  /matchingworkflows/{workflowName}/jobs/{jobId}:
    GET:
      summary: Getmatchingjob
      description: >-
        Gets the status, metrics, and errors (if there are any) that are
        associated with a job.
      operationId: amazonWebServicesGetMatchingJob
  /providerservices/{providerName}/{providerServiceName}:
    GET:
      summary: Getproviderservice
      description: Returns the ProviderService of a given name.
      operationId: amazonWebServicesGetProviderService
  /idmappingworkflows/{workflowName}/jobs:
    POST:
      summary: Startidmappingjob
      description: >-
        Starts the IdMappingJob of a workflow. The workflow must have previously
        been created using the CreateIdMappingWorkflow endpoint.
      operationId: amazonWebServicesStartIdMappingJob
  /matchingworkflows/{workflowName}/jobs:
    POST:
      summary: Startmatchingjob
      description: >-
        Starts the MatchingJob of a workflow. The workflow must have previously
        been created using the CreateMatchingWorkflow endpoint.
      operationId: amazonWebServicesStartMatchingJob
  /providerservices:
    GET:
      summary: Listproviderservices
      description: >-
        Returns a list of all the ProviderServices that are available in this
        Amazon Web Services Region.
      operationId: amazonWebServicesListProviderServices
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: >-
        Removes one or more tags from the specified Entity Resolution resource.
        In Entity Resolution, SchemaMapping, and MatchingWorkflow can be tagged.
      operationId: amazonWebServicesUntagResource
tags: []
