openapi: 3.1.0
info:
  title: es
  description: >-
    <fullname>Amazon Elasticsearch Configuration Service</fullname> <p>Use the
    Amazon Elasticsearch Configuration API to create, configure, and manage
    Elasticsearch domains.</p> <p>For sample code that uses the Configuration
    API, see the <a
    href="https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-configuration-samples.html">Amazon
    Elasticsearch Service Developer Guide</a>. The guide also contains <a
    href="https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html">sample
    code for sending signed HTTP requests to the Elasticsearch APIs</a>.</p>
    <p>The endpoint for configuration service requests is region-specific:
    es.<i>region</i>.amazonaws.com. For example, es.us-east-1.amazonaws.com. For
    a current list of supported regions and endpoints, see <a
    href="http://docs.aws.amazon.com/general/latest/gr/rande.html#elasticsearch-service-regions"
    target="_blank">Regions and Endpoints</a>.</p>
paths:
  /2015-01-01/es/ccs/inboundConnection/{ConnectionId}/accept:
    PUT:
      summary: Acceptinboundcrossclustersearchconnection
      description: >-
        Allows the destination domain owner to accept an inbound cross-cluster
        search connection request.
      operationId: amazonWebServicesAcceptInboundCrossClusterSearchConnection
  /2015-01-01/tags:
    POST:
      summary: Addtags
      description: >-
        Attaches tags to an existing Elasticsearch domain. Tags are a set of
        case-sensitive key value pairs. An Elasticsearch domain may have up to
        10 tags. See  Tagging Amazon Elasticsearch Service Domains for more
        information.
      operationId: amazonWebServicesAddTags
  /2015-01-01/packages/associate/{PackageID}/{DomainName}:
    POST:
      summary: Associatepackage
      description: Associates a package with an Amazon ES domain.
      operationId: amazonWebServicesAssociatePackage
  /2015-01-01/es/domain/{DomainName}/authorizeVpcEndpointAccess:
    POST:
      summary: Authorizevpcendpointaccess
      description: >-
        Provides access to an Amazon OpenSearch Service domain through the use
        of an interface VPC endpoint.
      operationId: amazonWebServicesAuthorizeVpcEndpointAccess
  /2015-01-01/es/domain/{DomainName}/config/cancel:
    POST:
      summary: Canceldomainconfigchange
      description: >-
        Cancels a pending configuration change on an Amazon OpenSearch Service
        domain.
      operationId: amazonWebServicesCancelDomainConfigChange
  /2015-01-01/es/serviceSoftwareUpdate/cancel:
    POST:
      summary: Cancelelasticsearchservicesoftwareupdate
      description: >-
        Cancels a scheduled service software update for an Amazon ES domain. You
        can only perform this operation before the AutomatedUpdateDate and when
        the UpdateStatus is in the PENDING_UPDATE state.
      operationId: amazonWebServicesCancelElasticsearchServiceSoftwareUpdate
  /2015-01-01/es/domain:
    POST:
      summary: Createelasticsearchdomain
      description: >-
        Creates a new Elasticsearch domain. For more information, see Creating
        Elasticsearch Domains in the Amazon Elasticsearch Service Developer
        Guide.
      operationId: amazonWebServicesCreateElasticsearchDomain
  /2015-01-01/es/ccs/outboundConnection:
    POST:
      summary: Createoutboundcrossclustersearchconnection
      description: >-
        Creates a new cross-cluster search connection from a source domain to a
        destination domain.
      operationId: amazonWebServicesCreateOutboundCrossClusterSearchConnection
  /2015-01-01/packages:
    POST:
      summary: Createpackage
      description: Create a package for use with Amazon ES domains.
      operationId: amazonWebServicesCreatePackage
  /2015-01-01/es/vpcEndpoints:
    GET:
      summary: Listvpcendpoints
      description: >-
        Retrieves all Amazon OpenSearch Service-managed VPC endpoints in the
        current account and Region.
      operationId: amazonWebServicesListVpcEndpoints
  /2015-01-01/es/domain/{DomainName}:
    GET:
      summary: Describeelasticsearchdomain
      description: >-
        Returns domain configuration information about the specified
        Elasticsearch domain, including the domain ID, domain endpoint, and
        domain ARN.
      operationId: amazonWebServicesDescribeElasticsearchDomain
  /2015-01-01/es/role:
    DELETE:
      summary: Deleteelasticsearchservicerole
      description: >-
        Deletes the service-linked role that Elasticsearch Service uses to
        manage and maintain VPC domains. Role deletion will fail if any existing
        VPC domains use the role. You must delete any such Elasticsearch domains
        before deleting the role. See Deleting Elasticsearch Service Role in VPC
        Endpoints for Amazon Elasticsearch Service Domains.
      operationId: amazonWebServicesDeleteElasticsearchServiceRole
  /2015-01-01/es/ccs/inboundConnection/{ConnectionId}:
    DELETE:
      summary: Deleteinboundcrossclustersearchconnection
      description: >-
        Allows the destination domain owner to delete an existing inbound
        cross-cluster search connection.
      operationId: amazonWebServicesDeleteInboundCrossClusterSearchConnection
  /2015-01-01/es/ccs/outboundConnection/{ConnectionId}:
    DELETE:
      summary: Deleteoutboundcrossclustersearchconnection
      description: >-
        Allows the source domain owner to delete an existing outbound
        cross-cluster search connection.
      operationId: amazonWebServicesDeleteOutboundCrossClusterSearchConnection
  /2015-01-01/packages/{PackageID}:
    DELETE:
      summary: Deletepackage
      description: Delete the package.
      operationId: amazonWebServicesDeletePackage
  /2015-01-01/es/vpcEndpoints/{VpcEndpointId}:
    DELETE:
      summary: Deletevpcendpoint
      description: Deletes an Amazon OpenSearch Service-managed interface VPC endpoint.
      operationId: amazonWebServicesDeleteVpcEndpoint
  /2015-01-01/es/domain/{DomainName}/autoTunes:
    GET:
      summary: Describedomainautotunes
      description: >-
        Provides scheduled Auto-Tune action details for the Elasticsearch
        domain, such as Auto-Tune action type, description, severity, and
        scheduled date.
      operationId: amazonWebServicesDescribeDomainAutoTunes
  /2015-01-01/es/domain/{DomainName}/progress:
    GET:
      summary: Describedomainchangeprogress
      description: >-
        Returns information about the current blue/green deployment happening on
        a domain, including a change ID, status, and progress stages.
      operationId: amazonWebServicesDescribeDomainChangeProgress
  /2015-01-01/es/domain/{DomainName}/config:
    POST:
      summary: Updateelasticsearchdomainconfig
      description: >-
        Modifies the cluster configuration of the specified Elasticsearch
        domain, setting as setting the instance type and the number of
        instances. 
      operationId: amazonWebServicesUpdateElasticsearchDomainConfig
  /2015-01-01/es/domain-info:
    POST:
      summary: Describeelasticsearchdomains
      description: >-
        Returns domain configuration information about the specified
        Elasticsearch domains, including the domain ID, domain endpoint, and
        domain ARN.
      operationId: amazonWebServicesDescribeElasticsearchDomains
  /2015-01-01/es/instanceTypeLimits/{ElasticsearchVersion}/{InstanceType}:
    GET:
      summary: Describeelasticsearchinstancetypelimits
      description: ' Describe Elasticsearch Limits for a given InstanceType and ElasticsearchVersion. When modifying existing Domain, specify the  DomainName  to know what Limits are supported for modifying. '
      operationId: amazonWebServicesDescribeElasticsearchInstanceTypeLimits
  /2015-01-01/es/ccs/inboundConnection/search:
    POST:
      summary: Describeinboundcrossclustersearchconnections
      description: >-
        Lists all the inbound cross-cluster search connections for a destination
        domain.
      operationId: amazonWebServicesDescribeInboundCrossClusterSearchConnections
  /2015-01-01/es/ccs/outboundConnection/search:
    POST:
      summary: Describeoutboundcrossclustersearchconnections
      description: >-
        Lists all the outbound cross-cluster search connections for a source
        domain.
      operationId: amazonWebServicesDescribeOutboundCrossClusterSearchConnections
  /2015-01-01/packages/describe:
    POST:
      summary: Describepackages
      description: >-
        Describes all packages available to Amazon ES. Includes options for
        filtering, limiting the number of results, and pagination.
      operationId: amazonWebServicesDescribePackages
  /2015-01-01/es/reservedInstanceOfferings:
    GET:
      summary: Describereservedelasticsearchinstanceofferings
      description: Lists available reserved Elasticsearch instance offerings.
      operationId: amazonWebServicesDescribeReservedElasticsearchInstanceOfferings
  /2015-01-01/es/reservedInstances:
    GET:
      summary: Describereservedelasticsearchinstances
      description: >-
        Returns information about reserved Elasticsearch instances for this
        account.
      operationId: amazonWebServicesDescribeReservedElasticsearchInstances
  /2015-01-01/es/vpcEndpoints/describe:
    POST:
      summary: Describevpcendpoints
      description: Describes one or more Amazon OpenSearch Service-managed VPC endpoints.
      operationId: amazonWebServicesDescribeVpcEndpoints
  /2015-01-01/packages/dissociate/{PackageID}/{DomainName}:
    POST:
      summary: Dissociatepackage
      description: Dissociates a package from the Amazon ES domain.
      operationId: amazonWebServicesDissociatePackage
  /2015-01-01/es/compatibleVersions:
    GET:
      summary: Getcompatibleelasticsearchversions
      description: ' Returns a list of upgrade compatible Elastisearch versions. You can optionally pass a  DomainName  to get all upgrade compatible Elasticsearch versions for that specific domain. '
      operationId: amazonWebServicesGetCompatibleElasticsearchVersions
  /2015-01-01/packages/{PackageID}/history:
    GET:
      summary: Getpackageversionhistory
      description: >-
        Returns a list of versions of the package, along with their creation
        time and commit message.
      operationId: amazonWebServicesGetPackageVersionHistory
  /2015-01-01/es/upgradeDomain/{DomainName}/history:
    GET:
      summary: Getupgradehistory
      description: >-
        Retrieves the complete history of the last 10 upgrades that were
        performed on the domain.
      operationId: amazonWebServicesGetUpgradeHistory
  /2015-01-01/es/upgradeDomain/{DomainName}/status:
    GET:
      summary: Getupgradestatus
      description: >-
        Retrieves the latest status of the last upgrade or upgrade eligibility
        check that was performed on the domain.
      operationId: amazonWebServicesGetUpgradeStatus
  /2015-01-01/domain:
    GET:
      summary: Listdomainnames
      description: >-
        Returns the name of all Elasticsearch domains owned by the current
        user's account. 
      operationId: amazonWebServicesListDomainNames
  /2015-01-01/packages/{PackageID}/domains:
    GET:
      summary: Listdomainsforpackage
      description: Lists all Amazon ES domains associated with the package.
      operationId: amazonWebServicesListDomainsForPackage
  /2015-01-01/es/instanceTypes/{ElasticsearchVersion}:
    GET:
      summary: Listelasticsearchinstancetypes
      description: >-
        List all Elasticsearch instance types that are supported for given
        ElasticsearchVersion
      operationId: amazonWebServicesListElasticsearchInstanceTypes
  /2015-01-01/es/versions:
    GET:
      summary: Listelasticsearchversions
      description: List all supported Elasticsearch versions
      operationId: amazonWebServicesListElasticsearchVersions
  /2015-01-01/domain/{DomainName}/packages:
    GET:
      summary: Listpackagesfordomain
      description: Lists all packages associated with the Amazon ES domain.
      operationId: amazonWebServicesListPackagesForDomain
  /2015-01-01/tags/:
    GET:
      summary: Listtags
      description: Returns all tags for the given Elasticsearch domain.
      operationId: amazonWebServicesListTags
  /2015-01-01/es/domain/{DomainName}/listVpcEndpointAccess:
    GET:
      summary: Listvpcendpointaccess
      description: >-
        Retrieves information about each principal that is allowed to access a
        given Amazon OpenSearch Service domain through the use of an interface
        VPC endpoint.
      operationId: amazonWebServicesListVpcEndpointAccess
  /2015-01-01/es/domain/{DomainName}/vpcEndpoints:
    GET:
      summary: Listvpcendpointsfordomain
      description: >-
        Retrieves all Amazon OpenSearch Service-managed VPC endpoints associated
        with a particular domain.
      operationId: amazonWebServicesListVpcEndpointsForDomain
  /2015-01-01/es/purchaseReservedInstanceOffering:
    POST:
      summary: Purchasereservedelasticsearchinstanceoffering
      description: Allows you to purchase reserved Elasticsearch instances.
      operationId: amazonWebServicesPurchaseReservedElasticsearchInstanceOffering
  /2015-01-01/es/ccs/inboundConnection/{ConnectionId}/reject:
    PUT:
      summary: Rejectinboundcrossclustersearchconnection
      description: >-
        Allows the destination domain owner to reject an inbound cross-cluster
        search connection request.
      operationId: amazonWebServicesRejectInboundCrossClusterSearchConnection
  /2015-01-01/tags-removal:
    POST:
      summary: Removetags
      description: >-
        Removes the specified set of tags from the specified Elasticsearch
        domain.
      operationId: amazonWebServicesRemoveTags
  /2015-01-01/es/domain/{DomainName}/revokeVpcEndpointAccess:
    POST:
      summary: Revokevpcendpointaccess
      description: >-
        Revokes access to an Amazon OpenSearch Service domain that was provided
        through an interface VPC endpoint.
      operationId: amazonWebServicesRevokeVpcEndpointAccess
  /2015-01-01/es/serviceSoftwareUpdate/start:
    POST:
      summary: Startelasticsearchservicesoftwareupdate
      description: Schedules a service software update for an Amazon ES domain.
      operationId: amazonWebServicesStartElasticsearchServiceSoftwareUpdate
  /2015-01-01/packages/update:
    POST:
      summary: Updatepackage
      description: Updates a package for use with Amazon ES domains.
      operationId: amazonWebServicesUpdatePackage
  /2015-01-01/es/vpcEndpoints/update:
    POST:
      summary: Updatevpcendpoint
      description: Modifies an Amazon OpenSearch Service-managed interface VPC endpoint.
      operationId: amazonWebServicesUpdateVpcEndpoint
  /2015-01-01/es/upgradeDomain:
    POST:
      summary: Upgradeelasticsearchdomain
      description: >-
        Allows you to either upgrade your domain or perform an Upgrade
        eligibility check to a compatible Elasticsearch version.
      operationId: amazonWebServicesUpgradeElasticsearchDomain
tags: []
