openapi: 3.1.0
info:
  title: finspace
  description: >-
    <p>The FinSpace management service provides the APIs for managing FinSpace
    environments.</p>
paths:
  /environment:
    GET:
      summary: Listenvironments
      description: A list of all of your FinSpace environments.
      operationId: amazonWebServicesListEnvironments
  /kx/environments/{environmentId}/databases/{databaseName}/changesets:
    GET:
      summary: Listkxchangesets
      description: Returns a list of all the changesets for a database.
      operationId: amazonWebServicesListKxChangesets
  /kx/environments/{environmentId}/clusters:
    GET:
      summary: Listkxclusters
      description: Returns a list of clusters.
      operationId: amazonWebServicesListKxClusters
  /kx/environments/{environmentId}/databases:
    GET:
      summary: Listkxdatabases
      description: Returns a list of all the databases in the kdb environment.
      operationId: amazonWebServicesListKxDatabases
  /kx/environments/{environmentId}/databases/{databaseName}/dataviews:
    GET:
      summary: Listkxdataviews
      description: ' Returns a list of all the dataviews in the database.'
      operationId: amazonWebServicesListKxDataviews
  /kx/environments:
    GET:
      summary: Listkxenvironments
      description: Returns a list of kdb environments created in an account.
      operationId: amazonWebServicesListKxEnvironments
  /kx/environments/{environmentId}/scalingGroups:
    GET:
      summary: Listkxscalinggroups
      description: ' Returns a list of scaling groups in a kdb environment.'
      operationId: amazonWebServicesListKxScalingGroups
  /kx/environments/{environmentId}/users:
    GET:
      summary: Listkxusers
      description: Lists all the users in a kdb environment.
      operationId: amazonWebServicesListKxUsers
  /kx/environments/{environmentId}/kxvolumes:
    GET:
      summary: Listkxvolumes
      description: ' Lists all the volumes in a kdb environment. '
      operationId: amazonWebServicesListKxVolumes
  /environment/{environmentId}:
    PUT:
      summary: Updateenvironment
      description: Update your FinSpace environment.
      operationId: amazonWebServicesUpdateEnvironment
  /kx/environments/{environmentId}/clusters/{clusterName}:
    GET:
      summary: Getkxcluster
      description: Retrieves information about a kdb cluster.
      operationId: amazonWebServicesGetKxCluster
  /kx/environments/{environmentId}/databases/{databaseName}:
    PUT:
      summary: Updatekxdatabase
      description: Updates information for the given kdb database.
      operationId: amazonWebServicesUpdateKxDatabase
  /kx/environments/{environmentId}/databases/{databaseName}/dataviews/{dataviewName}:
    PUT:
      summary: Updatekxdataview
      description: ' Updates the specified dataview. The dataviews get automatically updated when any new changesets are ingested. Each update of the dataview creates a new version, including changeset details and cache configurations'
      operationId: amazonWebServicesUpdateKxDataview
  /kx/environments/{environmentId}:
    PUT:
      summary: Updatekxenvironment
      description: Updates information for the given kdb environment.
      operationId: amazonWebServicesUpdateKxEnvironment
  /kx/environments/{environmentId}/scalingGroups/{scalingGroupName}:
    GET:
      summary: Getkxscalinggroup
      description: ' Retrieves details of a scaling group.'
      operationId: amazonWebServicesGetKxScalingGroup
  /kx/environments/{environmentId}/users/{userName}:
    PUT:
      summary: Updatekxuser
      description: >-
        Updates the user details. You can only update the IAM role associated
        with a user.
      operationId: amazonWebServicesUpdateKxUser
  /kx/environments/{environmentId}/kxvolumes/{volumeName}:
    PATCH:
      summary: Updatekxvolume
      description: ' Updates the throughput or capacity of a volume. During the update process, the filesystem might be unavailable for a few minutes. You can retry any operations after the update is complete. '
      operationId: amazonWebServicesUpdateKxVolume
  /kx/environments/{environmentId}/databases/{databaseName}/changesets/{changesetId}:
    GET:
      summary: Getkxchangeset
      description: Returns information about a kdb changeset.
      operationId: amazonWebServicesGetKxChangeset
  /kx/environments/{environmentId}/connectionString:
    GET:
      summary: Getkxconnectionstring
      description: >-
        Retrieves a connection string for a user to connect to a kdb cluster.
        You must call this API using the same role that you have defined while
        creating a user. 
      operationId: amazonWebServicesGetKxConnectionString
  /kx/environments/{environmentId}/clusters/{clusterName}/nodes:
    GET:
      summary: Listkxclusternodes
      description: Lists all the nodes in a kdb cluster.
      operationId: amazonWebServicesListKxClusterNodes
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes metadata tags from a FinSpace resource.
      operationId: amazonWebServicesUntagResource
  /kx/environments/{environmentId}/clusters/{clusterName}/configuration/code:
    PUT:
      summary: Updatekxclustercodeconfiguration
      description: ' Allows you to update code configuration on a running cluster. By using this API you can update the code, the initialization script path, and the command line arguments for a specific cluster. The configuration that you want to update will override any existing configurations on the cluster. '
      operationId: amazonWebServicesUpdateKxClusterCodeConfiguration
  /kx/environments/{environmentId}/clusters/{clusterName}/configuration/databases:
    PUT:
      summary: Updatekxclusterdatabases
      description: >-
        Updates the databases mounted on a kdb cluster, which includes the
        changesetId and all the dbPaths to be cached. This API does not allow
        you to change a database name or add a database if you created a cluster
        without one.  Using this API you can point a cluster to a different
        changeset and modify a list of partitions being cached.
      operationId: amazonWebServicesUpdateKxClusterDatabases
  /kx/environments/{environmentId}/network:
    PUT:
      summary: Updatekxenvironmentnetwork
      description: >-
        Updates environment network to connect to your internal network by using
        a transit gateway. This API supports request to create a transit gateway
        attachment from FinSpace VPC to your transit gateway ID and create a
        custom Route-53 outbound resolvers. Once you send a request to update a
        network, you cannot change it again. Network update might require
        termination of any clusters that are running in the existing network.
      operationId: amazonWebServicesUpdateKxEnvironmentNetwork
tags: []
