openapi: 3.1.0
info:
  title: finspace-data
  description: <p> The FinSpace APIs let you take actions inside the FinSpace.</p>
paths:
  /permission-group/{permissionGroupId}/users/{userId}:
    DELETE:
      summary: Disassociateuserfrompermissiongroup
      description: Removes a user from a permission group.
      operationId: amazonWebServicesDisassociateUserFromPermissionGroup
  /datasets/{datasetId}/changesetsv2:
    GET:
      summary: Listchangesets
      description: Lists the FinSpace Changesets for a Dataset.
      operationId: amazonWebServicesListChangesets
  /datasets/{datasetId}/dataviewsv2:
    GET:
      summary: Listdataviews
      description: Lists all available Dataviews for a Dataset.
      operationId: amazonWebServicesListDataViews
  /datasetsv2:
    GET:
      summary: Listdatasets
      description: Lists all of the active Datasets that a user has access to.
      operationId: amazonWebServicesListDatasets
  /permission-group:
    GET:
      summary: Listpermissiongroups
      description: Lists all available permission groups in FinSpace.
      operationId: amazonWebServicesListPermissionGroups
  /user:
    GET:
      summary: Listusers
      description: Lists all available users in FinSpace.
      operationId: amazonWebServicesListUsers
  /datasetsv2/{datasetId}:
    PUT:
      summary: Updatedataset
      description: Updates a FinSpace Dataset.
      operationId: amazonWebServicesUpdateDataset
  /permission-group/{permissionGroupId}:
    PUT:
      summary: Updatepermissiongroup
      description: >-
        Modifies the details of a permission group. You cannot modify a
        permissionGroupID.
      operationId: amazonWebServicesUpdatePermissionGroup
  /user/{userId}/disable:
    POST:
      summary: Disableuser
      description: >-
        Denies access to the FinSpace web application and API for the specified
        user.
      operationId: amazonWebServicesDisableUser
  /user/{userId}/enable:
    POST:
      summary: Enableuser
      description: ' Allows the specified user to access the FinSpace web application and API.'
      operationId: amazonWebServicesEnableUser
  /datasets/{datasetId}/changesetsv2/{changesetId}:
    PUT:
      summary: Updatechangeset
      description: Updates a FinSpace Changeset.
      operationId: amazonWebServicesUpdateChangeset
  /datasets/{datasetId}/dataviewsv2/{dataviewId}:
    GET:
      summary: Getdataview
      description: Gets information about a Dataview.
      operationId: amazonWebServicesGetDataView
  /datasets/{datasetId}/dataviewsv2/{dataviewId}/external-access-details:
    POST:
      summary: Getexternaldataviewaccessdetails
      description: >-
        Returns the credentials to access the external Dataview from an S3
        location. To call this API:   You must retrieve the programmatic
        credentials.   You must be a member of a FinSpace user group, where the
        dataset that you want to access has Read Dataset Data permissions.  
      operationId: amazonWebServicesGetExternalDataViewAccessDetails
  /credentials/programmatic:
    GET:
      summary: Getprogrammaticaccesscredentials
      description: >-
        Request programmatic credentials to use with FinSpace SDK. For more
        information, see Step 2. Access credentials programmatically using IAM
        access key id and secret access key.
      operationId: amazonWebServicesGetProgrammaticAccessCredentials
  /user/{userId}:
    PUT:
      summary: Updateuser
      description: >-
        Modifies the details of the specified user. You cannot update the userId
        for a user.
      operationId: amazonWebServicesUpdateUser
  /workingLocationV1:
    POST:
      summary: Getworkinglocation
      description: >-
        A temporary Amazon S3 location, where you can copy your files from a
        source location to stage or use as a scratch space in FinSpace notebook.
      operationId: amazonWebServicesGetWorkingLocation
  /user/{userId}/permission-groups:
    GET:
      summary: Listpermissiongroupsbyuser
      description: >-
        Lists all the permission groups that are associated with a specific
        user.
      operationId: amazonWebServicesListPermissionGroupsByUser
  /permission-group/{permissionGroupId}/users:
    GET:
      summary: Listusersbypermissiongroup
      description: Lists details of all the users in a specific permission group.
      operationId: amazonWebServicesListUsersByPermissionGroup
  /user/{userId}/password:
    POST:
      summary: Resetuserpassword
      description: >-
        Resets the password for a specified user ID and generates a temporary
        one. Only a superuser can reset password for other users. Resetting the
        password immediately invalidates the previous password associated with
        the user.
      operationId: amazonWebServicesResetUserPassword
tags: []
