openapi: 3.1.0
info:
  title: fis
  description: >-
    <p>Fault Injection Simulator is a managed service that enables you to
    perform fault injection experiments on your Amazon Web Services workloads.
    For more information, see the <a
    href="https://docs.aws.amazon.com/fis/latest/userguide/">Fault Injection
    Simulator User Guide</a>.</p>
paths:
  /experimentTemplates:
    GET:
      summary: Listexperimenttemplates
      description: Lists your experiment templates.
      operationId: amazonWebServicesListExperimentTemplates
  /experimentTemplates/{id}/targetAccountConfigurations/{accountId}:
    PATCH:
      summary: Updatetargetaccountconfiguration
      description: >-
        Updates the target account configuration for the specified experiment
        template.
      operationId: amazonWebServicesUpdateTargetAccountConfiguration
  /experimentTemplates/{id}:
    PATCH:
      summary: Updateexperimenttemplate
      description: Updates the specified experiment template.
      operationId: amazonWebServicesUpdateExperimentTemplate
  /actions/{id}:
    GET:
      summary: Getaction
      description: Gets information about the specified FIS action.
      operationId: amazonWebServicesGetAction
  /experiments/{id}:
    DELETE:
      summary: Stopexperiment
      description: Stops the specified experiment.
      operationId: amazonWebServicesStopExperiment
  /experiments/{id}/targetAccountConfigurations/{accountId}:
    GET:
      summary: Getexperimenttargetaccountconfiguration
      description: >-
        Gets information about the specified target account configuration of the
        experiment.
      operationId: amazonWebServicesGetExperimentTargetAccountConfiguration
  /targetResourceTypes/{resourceType}:
    GET:
      summary: Gettargetresourcetype
      description: Gets information about the specified resource type.
      operationId: amazonWebServicesGetTargetResourceType
  /actions:
    GET:
      summary: Listactions
      description: Lists the available FIS actions.
      operationId: amazonWebServicesListActions
  /experiments/{id}/resolvedTargets:
    GET:
      summary: Listexperimentresolvedtargets
      description: Lists the resolved targets information of the specified experiment.
      operationId: amazonWebServicesListExperimentResolvedTargets
  /experiments/{id}/targetAccountConfigurations:
    GET:
      summary: Listexperimenttargetaccountconfigurations
      description: Lists the target account configurations of the specified experiment.
      operationId: amazonWebServicesListExperimentTargetAccountConfigurations
  /experiments:
    POST:
      summary: Startexperiment
      description: Starts running an experiment from the specified experiment template.
      operationId: amazonWebServicesStartExperiment
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes the specified tags from the specified resource.
      operationId: amazonWebServicesUntagResource
  /experimentTemplates/{id}/targetAccountConfigurations:
    GET:
      summary: Listtargetaccountconfigurations
      description: >-
        Lists the target account configurations of the specified experiment
        template.
      operationId: amazonWebServicesListTargetAccountConfigurations
  /targetResourceTypes:
    GET:
      summary: Listtargetresourcetypes
      description: Lists the target resource types.
      operationId: amazonWebServicesListTargetResourceTypes
tags: []
