openapi: 3.1.0
info:
  title: Amazon Web Services forecastquery
  description: <p>Provides APIs for creating and managing Amazon Forecast resources.</p>
paths:
  /:
    POST:
      summary: Amazon Web Services Querywhatifforecast
      description: Retrieves a what-if forecast.
      operationId: amazonWebServicesQueryWhatIfForecast
tags: []
