openapi: 3.1.0
info:
  title: forecastquery
  description: <p>Provides APIs for creating and managing Amazon Forecast resources.</p>
paths:
  /:
    POST:
      summary: Querywhatifforecast
      description: Retrieves a what-if forecast.
      operationId: amazonWebServicesQueryWhatIfForecast
tags: []
