openapi: 3.1.0
info:
  title: forecast
  description: <p>Provides APIs for creating and managing Amazon Forecast resources.</p>
paths:
  /:
    POST:
      summary: Updatedatasetgroup
      description: >-
        Replaces the datasets in a dataset group with the specified datasets. 
        The Status of the dataset group must be ACTIVE before you can use the
        dataset group to create a predictor. Use the DescribeDatasetGroup
        operation to get the status. 
      operationId: amazonWebServicesUpdateDatasetGroup
tags: []
