openapi: 3.1.0
info:
  title: fsx
  description: >-
    <p>Amazon FSx is a fully managed service that makes it easy for storage and
    application administrators to launch and use shared file storage.</p>
paths:
  /:
    POST:
      summary: Updatevolume
      description: >-
        Updates the configuration of an Amazon FSx for NetApp ONTAP or Amazon
        FSx for OpenZFS volume.
      operationId: amazonWebServicesUpdateVolume
tags: []
