openapi: 3.1.0
info:
  title: glue
  description: >-
    <fullname>Glue</fullname> <p>Defines the public endpoint for the Glue
    service.</p>
paths:
  /:
    POST:
      summary: Updateworkflow
      description: Updates an existing workflow.
      operationId: amazonWebServicesUpdateWorkflow
tags: []
