openapi: 3.1.0
info:
  title: grafana
  description: >-
    <p>Amazon Managed Grafana is a fully managed and secure data visualization
    service that you can use to instantly query, correlate, and visualize
    operational metrics, logs, and traces from multiple sources. Amazon Managed
    Grafana makes it easy to deploy, operate, and scale Grafana, a widely
    deployed data visualization tool that is popular for its extensible data
    support.</p> <p>With Amazon Managed Grafana, you create logically isolated
    Grafana servers called <i>workspaces</i>. In a workspace, you can create
    Grafana dashboards and visualizations to analyze your metrics, logs, and
    traces without having to build, package, or deploy any hardware to run
    Grafana servers. </p>
paths:
  /workspaces/{workspaceId}/licenses/{licenseType}:
    DELETE:
      summary: Disassociatelicense
      description: Removes the Grafana Enterprise license from a workspace.
      operationId: amazonWebServicesDisassociateLicense
  /workspaces:
    GET:
      summary: Listworkspaces
      description: >-
        Returns a list of Amazon Managed Grafana workspaces in the account, with
        some information about each workspace. For more complete information
        about one workspace, use DescribeWorkspace.
      operationId: amazonWebServicesListWorkspaces
  /workspaces/{workspaceId}/apikeys:
    POST:
      summary: Createworkspaceapikey
      description: >-
        Creates a Grafana API key for the workspace. This key can be used to
        authenticate requests sent to the workspace's HTTP API. See
        https://docs.aws.amazon.com/grafana/latest/userguide/Using-Grafana-APIs.html
        for available APIs and example requests.
      operationId: amazonWebServicesCreateWorkspaceApiKey
  /workspaces/{workspaceId}:
    PUT:
      summary: Updateworkspace
      description: >-
        Modifies an existing Amazon Managed Grafana workspace. If you use this
        operation and omit any optional parameters, the existing values of those
        parameters are not changed. To modify the user authentication methods
        that the workspace uses, such as SAML or IAM Identity Center, use
        UpdateWorkspaceAuthentication. To modify which users in the workspace
        have the Admin and Editor Grafana roles, use UpdatePermissions.
      operationId: amazonWebServicesUpdateWorkspace
  /workspaces/{workspaceId}/apikeys/{keyName}:
    DELETE:
      summary: Deleteworkspaceapikey
      description: Deletes a Grafana API key for the workspace.
      operationId: amazonWebServicesDeleteWorkspaceApiKey
  /workspaces/{workspaceId}/authentication:
    POST:
      summary: Updateworkspaceauthentication
      description: >-
        Use this operation to define the identity provider (IdP) that this
        workspace authenticates users from, using SAML. You can also map SAML
        assertion attributes to workspace user information and define which
        groups in the assertion attribute are to have the Admin and Editor roles
        in the workspace.  Changes to the authentication method for a workspace
        may take a few minutes to take effect. 
      operationId: amazonWebServicesUpdateWorkspaceAuthentication
  /workspaces/{workspaceId}/configuration:
    PUT:
      summary: Updateworkspaceconfiguration
      description: Updates the configuration string for the given workspace
      operationId: amazonWebServicesUpdateWorkspaceConfiguration
  /workspaces/{workspaceId}/permissions:
    PATCH:
      summary: Updatepermissions
      description: >-
        Updates which users in a workspace have the Grafana Admin or Editor
        roles.
      operationId: amazonWebServicesUpdatePermissions
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: >-
        The UntagResource operation removes the association of the tag with the
        Amazon Managed Grafana resource. 
      operationId: amazonWebServicesUntagResource
  /versions:
    GET:
      summary: Listversions
      description: >-
        Lists available versions of Grafana. These are available when calling
        CreateWorkspace. Optionally, include a workspace to list the versions to
        which it can be upgraded.
      operationId: amazonWebServicesListVersions
tags: []
