openapi: 3.1.0
info:
  title: greengrass
  description: >-
    AWS IoT Greengrass seamlessly extends AWS onto physical devices so they can
    act locally on the data they generate, while still using the cloud for
    management, analytics, and durable storage. AWS IoT Greengrass ensures your
    devices can respond quickly to local events and operate with intermittent
    connectivity. AWS IoT Greengrass minimizes the cost of transmitting data to
    the cloud by allowing you to author AWS Lambda functions that execute
    locally.
paths:
  /greengrass/groups/{GroupId}/role:
    GET:
      summary: Getassociatedrole
      description: Retrieves the role associated with a particular group.
      operationId: amazonWebServicesGetAssociatedRole
  /greengrass/servicerole:
    GET:
      summary: Getserviceroleforaccount
      description: Retrieves the service role that is attached to your account.
      operationId: amazonWebServicesGetServiceRoleForAccount
  /greengrass/definition/connectors:
    GET:
      summary: Listconnectordefinitions
      description: Retrieves a list of connector definitions.
      operationId: amazonWebServicesListConnectorDefinitions
  /greengrass/definition/connectors/{ConnectorDefinitionId}/versions:
    GET:
      summary: Listconnectordefinitionversions
      description: >-
        Lists the versions of a connector definition, which are containers for
        connectors. Connectors run on the Greengrass core and contain built-in
        integration with local infrastructure, device protocols, AWS, and other
        cloud services.
      operationId: amazonWebServicesListConnectorDefinitionVersions
  /greengrass/definition/cores:
    GET:
      summary: Listcoredefinitions
      description: Retrieves a list of core definitions.
      operationId: amazonWebServicesListCoreDefinitions
  /greengrass/definition/cores/{CoreDefinitionId}/versions:
    GET:
      summary: Listcoredefinitionversions
      description: Lists the versions of a core definition.
      operationId: amazonWebServicesListCoreDefinitionVersions
  /greengrass/groups/{GroupId}/deployments:
    GET:
      summary: Listdeployments
      description: Returns a history of deployments for the group.
      operationId: amazonWebServicesListDeployments
  /greengrass/definition/devices:
    GET:
      summary: Listdevicedefinitions
      description: Retrieves a list of device definitions.
      operationId: amazonWebServicesListDeviceDefinitions
  /greengrass/definition/devices/{DeviceDefinitionId}/versions:
    GET:
      summary: Listdevicedefinitionversions
      description: Lists the versions of a device definition.
      operationId: amazonWebServicesListDeviceDefinitionVersions
  /greengrass/definition/functions:
    GET:
      summary: Listfunctiondefinitions
      description: Retrieves a list of Lambda function definitions.
      operationId: amazonWebServicesListFunctionDefinitions
  /greengrass/definition/functions/{FunctionDefinitionId}/versions:
    GET:
      summary: Listfunctiondefinitionversions
      description: Lists the versions of a Lambda function definition.
      operationId: amazonWebServicesListFunctionDefinitionVersions
  /greengrass/groups:
    GET:
      summary: Listgroups
      description: Retrieves a list of groups.
      operationId: amazonWebServicesListGroups
  /greengrass/groups/{GroupId}/certificateauthorities:
    GET:
      summary: Listgroupcertificateauthorities
      description: Retrieves the current CAs for a group.
      operationId: amazonWebServicesListGroupCertificateAuthorities
  /greengrass/groups/{GroupId}/versions:
    GET:
      summary: Listgroupversions
      description: Lists the versions of a group.
      operationId: amazonWebServicesListGroupVersions
  /greengrass/definition/loggers:
    GET:
      summary: Listloggerdefinitions
      description: Retrieves a list of logger definitions.
      operationId: amazonWebServicesListLoggerDefinitions
  /greengrass/definition/loggers/{LoggerDefinitionId}/versions:
    GET:
      summary: Listloggerdefinitionversions
      description: Lists the versions of a logger definition.
      operationId: amazonWebServicesListLoggerDefinitionVersions
  /greengrass/definition/resources:
    GET:
      summary: Listresourcedefinitions
      description: Retrieves a list of resource definitions.
      operationId: amazonWebServicesListResourceDefinitions
  /greengrass/definition/resources/{ResourceDefinitionId}/versions:
    GET:
      summary: Listresourcedefinitionversions
      description: Lists the versions of a resource definition.
      operationId: amazonWebServicesListResourceDefinitionVersions
  /greengrass/updates:
    POST:
      summary: Createsoftwareupdatejob
      description: >-
        Creates a software update for a core or group of cores (specified as an
        IoT thing group.) Use this to update the OTA Agent as well as the
        Greengrass core software. It makes use of the IoT Jobs feature which
        provides additional commands to manage a Greengrass core software update
        job.
      operationId: amazonWebServicesCreateSoftwareUpdateJob
  /greengrass/definition/subscriptions:
    GET:
      summary: Listsubscriptiondefinitions
      description: Retrieves a list of subscription definitions.
      operationId: amazonWebServicesListSubscriptionDefinitions
  /greengrass/definition/subscriptions/{SubscriptionDefinitionId}/versions:
    GET:
      summary: Listsubscriptiondefinitionversions
      description: Lists the versions of a subscription definition.
      operationId: amazonWebServicesListSubscriptionDefinitionVersions
  /greengrass/definition/connectors/{ConnectorDefinitionId}:
    PUT:
      summary: Updateconnectordefinition
      description: Updates a connector definition.
      operationId: amazonWebServicesUpdateConnectorDefinition
  /greengrass/definition/cores/{CoreDefinitionId}:
    PUT:
      summary: Updatecoredefinition
      description: Updates a core definition.
      operationId: amazonWebServicesUpdateCoreDefinition
  /greengrass/definition/devices/{DeviceDefinitionId}:
    PUT:
      summary: Updatedevicedefinition
      description: Updates a device definition.
      operationId: amazonWebServicesUpdateDeviceDefinition
  /greengrass/definition/functions/{FunctionDefinitionId}:
    PUT:
      summary: Updatefunctiondefinition
      description: Updates a Lambda function definition.
      operationId: amazonWebServicesUpdateFunctionDefinition
  /greengrass/groups/{GroupId}:
    PUT:
      summary: Updategroup
      description: Updates a group.
      operationId: amazonWebServicesUpdateGroup
  /greengrass/definition/loggers/{LoggerDefinitionId}:
    PUT:
      summary: Updateloggerdefinition
      description: Updates a logger definition.
      operationId: amazonWebServicesUpdateLoggerDefinition
  /greengrass/definition/resources/{ResourceDefinitionId}:
    PUT:
      summary: Updateresourcedefinition
      description: Updates a resource definition.
      operationId: amazonWebServicesUpdateResourceDefinition
  /greengrass/definition/subscriptions/{SubscriptionDefinitionId}:
    PUT:
      summary: Updatesubscriptiondefinition
      description: Updates a subscription definition.
      operationId: amazonWebServicesUpdateSubscriptionDefinition
  /greengrass/bulk/deployments/{BulkDeploymentId}/status:
    GET:
      summary: Getbulkdeploymentstatus
      description: Returns the status of a bulk deployment.
      operationId: amazonWebServicesGetBulkDeploymentStatus
  /greengrass/things/{ThingName}/connectivityInfo:
    PUT:
      summary: Updateconnectivityinfo
      description: >-
        Updates the connectivity information for the core. Any devices that
        belong to the group which has this core will receive this information in
        order to find the location of the core and connect to it.
      operationId: amazonWebServicesUpdateConnectivityInfo
  /greengrass/definition/connectors/{ConnectorDefinitionId}/versions/{ConnectorDefinitionVersionId}:
    GET:
      summary: Getconnectordefinitionversion
      description: >-
        Retrieves information about a connector definition version, including
        the connectors that the version contains. Connectors are prebuilt
        modules that interact with local infrastructure, device protocols, AWS,
        and other cloud services.
      operationId: amazonWebServicesGetConnectorDefinitionVersion
  /greengrass/definition/cores/{CoreDefinitionId}/versions/{CoreDefinitionVersionId}:
    GET:
      summary: Getcoredefinitionversion
      description: Retrieves information about a core definition version.
      operationId: amazonWebServicesGetCoreDefinitionVersion
  /greengrass/groups/{GroupId}/deployments/{DeploymentId}/status:
    GET:
      summary: Getdeploymentstatus
      description: Returns the status of a deployment.
      operationId: amazonWebServicesGetDeploymentStatus
  /greengrass/definition/devices/{DeviceDefinitionId}/versions/{DeviceDefinitionVersionId}:
    GET:
      summary: Getdevicedefinitionversion
      description: Retrieves information about a device definition version.
      operationId: amazonWebServicesGetDeviceDefinitionVersion
  /greengrass/definition/functions/{FunctionDefinitionId}/versions/{FunctionDefinitionVersionId}:
    GET:
      summary: Getfunctiondefinitionversion
      description: >-
        Retrieves information about a Lambda function definition version,
        including which Lambda functions are included in the version and their
        configurations.
      operationId: amazonWebServicesGetFunctionDefinitionVersion
  /greengrass/groups/{GroupId}/certificateauthorities/{CertificateAuthorityId}:
    GET:
      summary: Getgroupcertificateauthority
      description: >-
        Retreives the CA associated with a group. Returns the public key of the
        CA.
      operationId: amazonWebServicesGetGroupCertificateAuthority
  /greengrass/groups/{GroupId}/certificateauthorities/configuration/expiry:
    PUT:
      summary: Updategroupcertificateconfiguration
      description: Updates the Certificate expiry time for a group.
      operationId: amazonWebServicesUpdateGroupCertificateConfiguration
  /greengrass/groups/{GroupId}/versions/{GroupVersionId}:
    GET:
      summary: Getgroupversion
      description: Retrieves information about a group version.
      operationId: amazonWebServicesGetGroupVersion
  /greengrass/definition/loggers/{LoggerDefinitionId}/versions/{LoggerDefinitionVersionId}:
    GET:
      summary: Getloggerdefinitionversion
      description: Retrieves information about a logger definition version.
      operationId: amazonWebServicesGetLoggerDefinitionVersion
  /greengrass/definition/resources/{ResourceDefinitionId}/versions/{ResourceDefinitionVersionId}:
    GET:
      summary: Getresourcedefinitionversion
      description: >-
        Retrieves information about a resource definition version, including
        which resources are included in the version.
      operationId: amazonWebServicesGetResourceDefinitionVersion
  /greengrass/definition/subscriptions/{SubscriptionDefinitionId}/versions/{SubscriptionDefinitionVersionId}:
    GET:
      summary: Getsubscriptiondefinitionversion
      description: Retrieves information about a subscription definition version.
      operationId: amazonWebServicesGetSubscriptionDefinitionVersion
  /greengrass/things/{ThingName}/runtimeconfig:
    PUT:
      summary: Updatethingruntimeconfiguration
      description: Updates the runtime configuration of a thing.
      operationId: amazonWebServicesUpdateThingRuntimeConfiguration
  /greengrass/bulk/deployments/{BulkDeploymentId}/detailed-reports:
    GET:
      summary: Listbulkdeploymentdetailedreports
      description: >-
        Gets a paginated list of the deployments that have been started in a
        bulk deployment operation, and their current deployment status.
      operationId: amazonWebServicesListBulkDeploymentDetailedReports
  /greengrass/bulk/deployments:
    POST:
      summary: Startbulkdeployment
      description: >-
        Deploys multiple groups in one operation. This action starts the bulk
        deployment of a specified set of group versions. Each group version
        deployment will be triggered with an adaptive rate that has a fixed
        upper limit. We recommend that you include an ''X-Amzn-Client-Token''
        token in every ''StartBulkDeployment'' request. These requests are
        idempotent with respect to the token and the request parameters.
      operationId: amazonWebServicesStartBulkDeployment
  /tags/{resource-arn}:
    DELETE:
      summary: Untagresource
      description: Remove resource tags from a Greengrass Resource.
      operationId: amazonWebServicesUntagResource
  /greengrass/groups/{GroupId}/deployments/$reset:
    POST:
      summary: Resetdeployments
      description: Resets a group's deployments.
      operationId: amazonWebServicesResetDeployments
  /greengrass/bulk/deployments/{BulkDeploymentId}/$stop:
    PUT:
      summary: Stopbulkdeployment
      description: >-
        Stops the execution of a bulk deployment. This action returns a status
        of ''Stopping'' until the deployment is stopped. You cannot start a new
        bulk deployment while a previous deployment is in the ''Stopping''
        state. This action doesn't rollback completed deployments or cancel
        pending deployments.
      operationId: amazonWebServicesStopBulkDeployment
tags: []
