openapi: 3.1.0
info:
  title: greengrassv2
  description: >-
    <p>IoT Greengrass brings local compute, messaging, data management, sync,
    and ML inference capabilities to edge devices. This enables devices to
    collect and analyze data closer to the source of information, react
    autonomously to local events, and communicate securely with each other on
    local networks. Local devices can also communicate securely with Amazon Web
    Services IoT Core and export IoT data to the Amazon Web Services Cloud. IoT
    Greengrass developers can use Lambda functions and components to create and
    deploy applications to fleets of edge devices for local operation.</p>
    <p>IoT Greengrass Version 2 provides a new major version of the IoT
    Greengrass Core software, new APIs, and a new console. Use this API
    reference to learn how to use the IoT Greengrass V2 API operations to manage
    components, manage deployments, and core devices.</p> <p>For more
    information, see <a
    href="https://docs.aws.amazon.com/greengrass/v2/developerguide/what-is-iot-greengrass.html">What
    is IoT Greengrass?</a> in the <i>IoT Greengrass V2 Developer Guide</i>.</p>
paths:
  /greengrass/servicerole:
    GET:
      summary: Getserviceroleforaccount
      description: >-
        Gets the service role associated with IoT Greengrass for your Amazon Web
        Services account in this Amazon Web Services Region. IoT Greengrass uses
        this role to verify the identity of client devices and manage core
        device connectivity information. For more information, see Greengrass
        service role in the IoT Greengrass Version 2 Developer Guide.
      operationId: amazonWebServicesGetServiceRoleForAccount
  /greengrass/v2/coreDevices/{coreDeviceThingName}/associateClientDevices:
    POST:
      summary: Batchassociateclientdevicewithcoredevice
      description: >-
        Associates a list of client devices with a core device. Use this API
        operation to specify which client devices can discover a core device
        through cloud discovery. With cloud discovery, client devices connect to
        IoT Greengrass to retrieve associated core devices' connectivity
        information and certificates. For more information, see Configure cloud
        discovery in the IoT Greengrass V2 Developer Guide.  Client devices are
        local IoT devices that connect to and communicate with an IoT Greengrass
        core device over MQTT. You can connect client devices to a core device
        to sync MQTT messages and data to Amazon Web Services IoT Core and
        interact with client devices in Greengrass components. For more
        information, see Interact with local IoT devices in the IoT Greengrass
        V2 Developer Guide. 
      operationId: amazonWebServicesBatchAssociateClientDeviceWithCoreDevice
  /greengrass/v2/coreDevices/{coreDeviceThingName}/disassociateClientDevices:
    POST:
      summary: Batchdisassociateclientdevicefromcoredevice
      description: >-
        Disassociates a list of client devices from a core device. After you
        disassociate a client device from a core device, the client device won't
        be able to use cloud discovery to retrieve the core device's
        connectivity information and certificates.
      operationId: amazonWebServicesBatchDisassociateClientDeviceFromCoreDevice
  /greengrass/v2/deployments/{deploymentId}/cancel:
    POST:
      summary: Canceldeployment
      description: >-
        Cancels a deployment. This operation cancels the deployment for devices
        that haven't yet received it. If a device already received the
        deployment, this operation doesn't change anything for that device.
      operationId: amazonWebServicesCancelDeployment
  /greengrass/v2/createComponentVersion:
    POST:
      summary: Createcomponentversion
      description: >-
        Creates a component. Components are software that run on Greengrass core
        devices. After you develop and test a component on your core device, you
        can use this operation to upload your component to IoT Greengrass. Then,
        you can deploy the component to other core devices. You can use this
        operation to do the following:    Create components from recipes  Create
        a component from a recipe, which is a file that defines the component's
        metadata, parameters, dependencies, lifecycle, artifacts, and platform
        capability. For more information, see IoT Greengrass component recipe
        reference in the IoT Greengrass V2 Developer Guide. To create a
        component from a recipe, specify inlineRecipe when you call this
        operation.    Create components from Lambda functions  Create a
        component from an Lambda function that runs on IoT Greengrass. This
        creates a recipe and artifacts from the Lambda function's deployment
        package. You can use this operation to migrate Lambda functions from IoT
        Greengrass V1 to IoT Greengrass V2. This function only accepts Lambda
        functions that use the following runtimes:   Python 2.7 – python2.7   
        Python 3.7 – python3.7    Python 3.8 – python3.8    Python 3.9 –
        python3.9    Java 8 – java8    Java 11 – java11    Node.js 10 –
        nodejs10.x    Node.js 12 – nodejs12.x    Node.js 14 – nodejs14.x    To
        create a component from a Lambda function, specify lambdaFunction when
        you call this operation.  IoT Greengrass currently supports Lambda
        functions on only Linux core devices.   
      operationId: amazonWebServicesCreateComponentVersion
  /greengrass/v2/deployments:
    GET:
      summary: Listdeployments
      description: Retrieves a paginated list of deployments.
      operationId: amazonWebServicesListDeployments
  /greengrass/v2/components/{arn}:
    GET:
      summary: Getcomponent
      description: Gets the recipe for a version of a component.
      operationId: amazonWebServicesGetComponent
  /greengrass/v2/coreDevices/{coreDeviceThingName}:
    GET:
      summary: Getcoredevice
      description: >-
        Retrieves metadata for a Greengrass core device.  IoT Greengrass relies
        on individual devices to send status updates to the Amazon Web Services
        Cloud. If the IoT Greengrass Core software isn't running on the device,
        or if device isn't connected to the Amazon Web Services Cloud, then the
        reported status of that device might not reflect its current status. The
        status timestamp indicates when the device status was last updated. Core
        devices send status updates at the following times:   When the IoT
        Greengrass Core software starts   When the core device receives a
        deployment from the Amazon Web Services Cloud   When the status of any
        component on the core device becomes BROKEN    At a regular interval
        that you can configure, which defaults to 24 hours   For IoT Greengrass
        Core v2.7.0, the core device sends status updates upon local deployment
        and cloud deployment   
      operationId: amazonWebServicesGetCoreDevice
  /greengrass/v2/deployments/{deploymentId}:
    GET:
      summary: Getdeployment
      description: >-
        Gets a deployment. Deployments define the components that run on
        Greengrass core devices.
      operationId: amazonWebServicesGetDeployment
  /greengrass/v2/components/{arn}/metadata:
    GET:
      summary: Describecomponent
      description: Retrieves metadata for a version of a component.
      operationId: amazonWebServicesDescribeComponent
  /greengrass/v2/components/{arn}/artifacts/{artifactName+}:
    GET:
      summary: Getcomponentversionartifact
      description: >-
        Gets the pre-signed URL to download a public or a Lambda component
        artifact. Core devices call this operation to identify the URL that they
        can use to download an artifact to install.
      operationId: amazonWebServicesGetComponentVersionArtifact
  /greengrass/things/{thingName}/connectivityInfo:
    PUT:
      summary: Updateconnectivityinfo
      description: >-
        Updates connectivity information for a Greengrass core device.
        Connectivity information includes endpoints and ports where client
        devices can connect to an MQTT broker on the core device. When a client
        device calls the IoT Greengrass discovery API, IoT Greengrass returns
        connectivity information for all of the core devices where the client
        device can connect. For more information, see Connect client devices to
        core devices in the IoT Greengrass Version 2 Developer Guide.
      operationId: amazonWebServicesUpdateConnectivityInfo
  /greengrass/v2/coreDevices/{coreDeviceThingName}/associatedClientDevices:
    GET:
      summary: Listclientdevicesassociatedwithcoredevice
      description: >-
        Retrieves a paginated list of client devices that are associated with a
        core device.
      operationId: amazonWebServicesListClientDevicesAssociatedWithCoreDevice
  /greengrass/v2/components/{arn}/versions:
    GET:
      summary: Listcomponentversions
      description: >-
        Retrieves a paginated list of all versions for a component. Greater
        versions are listed first.
      operationId: amazonWebServicesListComponentVersions
  /greengrass/v2/components:
    GET:
      summary: Listcomponents
      description: >-
        Retrieves a paginated list of component summaries. This list includes
        components that you have permission to view.
      operationId: amazonWebServicesListComponents
  /greengrass/v2/coreDevices:
    GET:
      summary: Listcoredevices
      description: >-
        Retrieves a paginated list of Greengrass core devices.  IoT Greengrass
        relies on individual devices to send status updates to the Amazon Web
        Services Cloud. If the IoT Greengrass Core software isn't running on the
        device, or if device isn't connected to the Amazon Web Services Cloud,
        then the reported status of that device might not reflect its current
        status. The status timestamp indicates when the device status was last
        updated. Core devices send status updates at the following times:   When
        the IoT Greengrass Core software starts   When the core device receives
        a deployment from the Amazon Web Services Cloud   When the status of any
        component on the core device becomes BROKEN    At a regular interval
        that you can configure, which defaults to 24 hours   For IoT Greengrass
        Core v2.7.0, the core device sends status updates upon local deployment
        and cloud deployment   
      operationId: amazonWebServicesListCoreDevices
  /greengrass/v2/coreDevices/{coreDeviceThingName}/effectiveDeployments:
    GET:
      summary: Listeffectivedeployments
      description: >-
        Retrieves a paginated list of deployment jobs that IoT Greengrass sends
        to Greengrass core devices.
      operationId: amazonWebServicesListEffectiveDeployments
  /greengrass/v2/coreDevices/{coreDeviceThingName}/installedComponents:
    GET:
      summary: Listinstalledcomponents
      description: >-
        Retrieves a paginated list of the components that a Greengrass core
        device runs. By default, this list doesn't include components that are
        deployed as dependencies of other components. To include dependencies in
        the response, set the topologyFilter parameter to ALL.  IoT Greengrass
        relies on individual devices to send status updates to the Amazon Web
        Services Cloud. If the IoT Greengrass Core software isn't running on the
        device, or if device isn't connected to the Amazon Web Services Cloud,
        then the reported status of that device might not reflect its current
        status. The status timestamp indicates when the device status was last
        updated. Core devices send status updates at the following times:   When
        the IoT Greengrass Core software starts   When the core device receives
        a deployment from the Amazon Web Services Cloud   When the status of any
        component on the core device becomes BROKEN    At a regular interval
        that you can configure, which defaults to 24 hours   For IoT Greengrass
        Core v2.7.0, the core device sends status updates upon local deployment
        and cloud deployment   
      operationId: amazonWebServicesListInstalledComponents
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes a tag from an IoT Greengrass resource.
      operationId: amazonWebServicesUntagResource
  /greengrass/v2/resolveComponentCandidates:
    POST:
      summary: Resolvecomponentcandidates
      description: >-
        Retrieves a list of components that meet the component, version, and
        platform requirements of a deployment. Greengrass core devices call this
        operation when they receive a deployment to identify the components to
        install. This operation identifies components that meet all dependency
        requirements for a deployment. If the requirements conflict, then this
        operation returns an error and the deployment fails. For example, this
        occurs if component A requires version &gt;2.0.0 and component B
        requires version &lt;2.0.0 of a component dependency. When you specify
        the component candidates to resolve, IoT Greengrass compares each
        component's digest from the core device with the component's digest in
        the Amazon Web Services Cloud. If the digests don't match, then IoT
        Greengrass specifies to use the version from the Amazon Web Services
        Cloud.  To use this operation, you must use the data plane API endpoint
        and authenticate with an IoT device certificate. For more information,
        see IoT Greengrass endpoints and quotas. 
      operationId: amazonWebServicesResolveComponentCandidates
tags: []
