openapi: 3.1.0
info:
  title: groundstation
  description: >-
    <p>Welcome to the AWS Ground Station API Reference. AWS Ground Station is a
    fully managed service that enables you to control satellite communications,
    downlink and process satellite data, and scale your satellite operations
    efficiently and cost-effectively without having to build or manage your own
    ground station infrastructure.</p>
paths:
  /contact/{contactId}:
    GET:
      summary: Describecontact
      description: Describes an existing contact.
      operationId: amazonWebServicesDescribeContact
  /config:
    GET:
      summary: Listconfigs
      description: Returns a list of Config objects.
      operationId: amazonWebServicesListConfigs
  /dataflowEndpointGroup:
    GET:
      summary: Listdataflowendpointgroups
      description: Returns a list of DataflowEndpoint groups.
      operationId: amazonWebServicesListDataflowEndpointGroups
  /ephemeris:
    POST:
      summary: Createephemeris
      description: Creates an Ephemeris with the specified EphemerisData.
      operationId: amazonWebServicesCreateEphemeris
  /missionprofile:
    GET:
      summary: Listmissionprofiles
      description: Returns a list of mission profiles.
      operationId: amazonWebServicesListMissionProfiles
  /config/{configType}/{configId}:
    PUT:
      summary: Updateconfig
      description: >-
        Updates the Config used when scheduling contacts. Updating a Config will
        not update the execution parameters for existing future contacts
        scheduled with this Config.
      operationId: amazonWebServicesUpdateConfig
  /dataflowEndpointGroup/{dataflowEndpointGroupId}:
    GET:
      summary: Getdataflowendpointgroup
      description: Returns the dataflow endpoint group.
      operationId: amazonWebServicesGetDataflowEndpointGroup
  /ephemeris/{ephemerisId}:
    PUT:
      summary: Updateephemeris
      description: Updates an existing ephemeris
      operationId: amazonWebServicesUpdateEphemeris
  /missionprofile/{missionProfileId}:
    PUT:
      summary: Updatemissionprofile
      description: >-
        Updates a mission profile. Updating a mission profile will not update
        the execution parameters for existing future contacts.
      operationId: amazonWebServicesUpdateMissionProfile
  /agent/{agentId}/configuration:
    GET:
      summary: Getagentconfiguration
      description: '  For use by AWS Ground Station Agent and shouldn''t be called directly.  Gets the latest configuration information for a registered agent.'
      operationId: amazonWebServicesGetAgentConfiguration
  /minute-usage:
    POST:
      summary: Getminuteusage
      description: Returns the number of reserved minutes used by account.
      operationId: amazonWebServicesGetMinuteUsage
  /satellite/{satelliteId}:
    GET:
      summary: Getsatellite
      description: Returns a satellite.
      operationId: amazonWebServicesGetSatellite
  /contacts:
    POST:
      summary: Listcontacts
      description: >-
        Returns a list of contacts. If statusList contains AVAILABLE, the
        request must include groundStation, missionprofileArn, and
        satelliteArn. 
      operationId: amazonWebServicesListContacts
  /ephemerides:
    POST:
      summary: Listephemerides
      description: List existing ephemerides.
      operationId: amazonWebServicesListEphemerides
  /groundstation:
    GET:
      summary: Listgroundstations
      description: 'Returns a list of ground stations. '
      operationId: amazonWebServicesListGroundStations
  /satellite:
    GET:
      summary: Listsatellites
      description: Returns a list of satellites.
      operationId: amazonWebServicesListSatellites
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Deassigns a resource tag.
      operationId: amazonWebServicesUntagResource
  /agent:
    POST:
      summary: Registeragent
      description: '  For use by AWS Ground Station Agent and shouldn''t be called directly.   Registers a new agent with AWS Ground Station. '
      operationId: amazonWebServicesRegisterAgent
  /contact:
    POST:
      summary: Reservecontact
      description: Reserves a contact using specified parameters.
      operationId: amazonWebServicesReserveContact
  /agent/{agentId}:
    PUT:
      summary: Updateagentstatus
      description: '  For use by AWS Ground Station Agent and shouldn''t be called directly.  Update the status of the agent.'
      operationId: amazonWebServicesUpdateAgentStatus
tags: []
