openapi: 3.1.0
info:
  title: honeycode
  description: >-
    <p> Amazon Honeycode is a fully managed service that allows you to quickly
    build mobile and web apps for teams—without programming. Build Honeycode
    apps for managing almost anything, like projects, customers, operations,
    approvals, resources, and even your team. </p>
paths:
  /workbooks/{workbookId}/tables/{tableId}/rows/batchcreate:
    POST:
      summary: Batchcreatetablerows
      description: ' The BatchCreateTableRows API allows you to create one or more rows at the end of a table in a workbook. The API allows you to specify the values to set in some or all of the columns in the new rows.   If a column is not explicitly set in a specific row, then the column level formula specified in the table will be applied to the new row. If there is no column level formula but the last row of the table has a formula, then that formula will be copied down to the new row. If there is no column level formula and no formula in the last row of the table, then that column will be left blank for the new rows. '
      operationId: amazonWebServicesBatchCreateTableRows
  /workbooks/{workbookId}/tables/{tableId}/rows/batchdelete:
    POST:
      summary: Batchdeletetablerows
      description: ' The BatchDeleteTableRows API allows you to delete one or more rows from a table in a workbook. You need to specify the ids of the rows that you want to delete from the table. '
      operationId: amazonWebServicesBatchDeleteTableRows
  /workbooks/{workbookId}/tables/{tableId}/rows/batchupdate:
    POST:
      summary: Batchupdatetablerows
      description: ' The BatchUpdateTableRows API allows you to update one or more rows in a table in a workbook.   You can specify the values to set in some or all of the columns in the table for the specified rows. If a column is not explicitly specified in a particular row, then that column will not be updated for that row. To clear out the data in a specific cell, you need to set the value as an empty string (""). '
      operationId: amazonWebServicesBatchUpdateTableRows
  /workbooks/{workbookId}/tables/{tableId}/rows/batchupsert:
    POST:
      summary: Batchupserttablerows
      description: ' The BatchUpsertTableRows API allows you to upsert one or more rows in a table. The upsert operation takes a filter expression as input and evaluates it to find matching rows on the destination table. If matching rows are found, it will update the cells in the matching rows to new values specified in the request. If no matching rows are found, a new row is added at the end of the table and the cells in that row are set to the new values specified in the request.   You can specify the values to set in some or all of the columns in the table for the matching or newly appended rows. If a column is not explicitly specified for a particular row, then that column will not be updated for that row. To clear out the data in a specific cell, you need to set the value as an empty string (""). '
      operationId: amazonWebServicesBatchUpsertTableRows
  /workbooks/{workbookId}/tables/{tableId}/import/{jobId}:
    GET:
      summary: Describetabledataimportjob
      description: ' The DescribeTableDataImportJob API allows you to retrieve the status and details of a table data import job. '
      operationId: amazonWebServicesDescribeTableDataImportJob
  /screendata:
    POST:
      summary: Getscreendata
      description: ' The GetScreenData API allows retrieval of data from a screen in a Honeycode app. The API allows setting local variables in the screen to filter, sort or otherwise affect what will be displayed on the screen. '
      operationId: amazonWebServicesGetScreenData
  /workbooks/{workbookId}/apps/{appId}/screens/{screenId}/automations/{automationId}:
    POST:
      summary: Invokescreenautomation
      description: ' The InvokeScreenAutomation API allows invoking an action defined in a screen in a Honeycode app. The API allows setting local variables, which can then be used in the automation being invoked. This allows automating the Honeycode app interactions to write, update or delete data in the workbook. '
      operationId: amazonWebServicesInvokeScreenAutomation
  /workbooks/{workbookId}/tables/{tableId}/columns:
    GET:
      summary: Listtablecolumns
      description: ' The ListTableColumns API allows you to retrieve a list of all the columns in a table in a workbook. '
      operationId: amazonWebServicesListTableColumns
  /workbooks/{workbookId}/tables/{tableId}/rows/list:
    POST:
      summary: Listtablerows
      description: ' The ListTableRows API allows you to retrieve a list of all the rows in a table in a workbook. '
      operationId: amazonWebServicesListTableRows
  /workbooks/{workbookId}/tables:
    GET:
      summary: Listtables
      description: ' The ListTables API allows you to retrieve a list of all the tables in a workbook. '
      operationId: amazonWebServicesListTables
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: ' The UntagResource API allows you to removes tags from an ARN-able resource. Resource includes workbook, table, screen and screen-automation. '
      operationId: amazonWebServicesUntagResource
  /workbooks/{workbookId}/tables/{tableId}/rows/query:
    POST:
      summary: Querytablerows
      description: ' The QueryTableRows API allows you to use a filter formula to query for specific rows in a table. '
      operationId: amazonWebServicesQueryTableRows
  /workbooks/{workbookId}/tables/{tableId}/import:
    POST:
      summary: Starttabledataimportjob
      description: ' The StartTableDataImportJob API allows you to start an import job on a table. This API will only return the id of the job that was started. To find out the status of the import request, you need to call the DescribeTableDataImportJob API. '
      operationId: amazonWebServicesStartTableDataImportJob
tags: []
