openapi: 3.1.0
info:
  title: iam
  description: >-
    <fullname>Identity and Access Management</fullname> <p>Identity and Access
    Management (IAM) is a web service for securely controlling access to Amazon
    Web Services services. With IAM, you can centrally manage users, security
    credentials such as access keys, and permissions that control which Amazon
    Web Services resources users and applications can access. For more
    information about IAM, see <a href="http://aws.amazon.com/iam/">Identity and
    Access Management (IAM)</a> and the <a
    href="https://docs.aws.amazon.com/IAM/latest/UserGuide/">Identity and Access
    Management User Guide</a>.</p>
paths:
  /:
    POST:
      summary: Uploadsigningcertificate
      description: >-
        Uploads an X.509 signing certificate and associates it with the
        specified IAM user. Some Amazon Web Services services require you to use
        certificates to validate requests that are signed with a corresponding
        private key. When you upload the certificate, its default status is
        Active. For information about when you would use an X.509 signing
        certificate, see Managing server certificates in IAM in the IAM User
        Guide. If the UserName is not specified, the IAM user name is determined
        implicitly based on the Amazon Web Services access key ID used to sign
        the request. This operation works for access keys under the Amazon Web
        Services account. Consequently, you can use this operation to manage
        Amazon Web Services account root user credentials even if the Amazon Web
        Services account has no associated users.  Because the body of an X.509
        certificate can be large, you should use POST rather than GET when
        calling UploadSigningCertificate. For information about setting up
        signatures and authorization through the API, see Signing Amazon Web
        Services API requests in the Amazon Web Services General Reference. For
        general information about using the Query API with IAM, see Making query
        requests in the IAM User Guide. 
      operationId: amazonWebServicesUploadSigningCertificate
tags: []
