openapi: 3.1.0
info:
  title: inspector2
  description: >-
    <p>Amazon Inspector is a vulnerability discovery service that automates
    continuous scanning for security vulnerabilities within your Amazon EC2,
    Amazon ECR, and Amazon Web Services Lambda environments.</p>
paths:
  /members/associate:
    POST:
      summary: Associatemember
      description: >-
        Associates an Amazon Web Services account with an Amazon Inspector
        delegated administrator. An HTTP 200 response indicates the association
        was successfully started, but doesn’t indicate whether it was completed.
        You can check if the association completed by using ListMembers for
        multiple accounts or GetMembers for a single account.
      operationId: amazonWebServicesAssociateMember
  /status/batch/get:
    POST:
      summary: Batchgetaccountstatus
      description: >-
        Retrieves the Amazon Inspector status of multiple Amazon Web Services
        accounts within your environment.
      operationId: amazonWebServicesBatchGetAccountStatus
  /codesnippet/batchget:
    POST:
      summary: Batchgetcodesnippet
      description: >-
        Retrieves code snippets from findings that Amazon Inspector detected
        code vulnerabilities in.
      operationId: amazonWebServicesBatchGetCodeSnippet
  /findings/details/batch/get:
    POST:
      summary: Batchgetfindingdetails
      description: Gets vulnerability details for findings.
      operationId: amazonWebServicesBatchGetFindingDetails
  /freetrialinfo/batchget:
    POST:
      summary: Batchgetfreetrialinfo
      description: Gets free trial status for multiple Amazon Web Services accounts.
      operationId: amazonWebServicesBatchGetFreeTrialInfo
  /ec2deepinspectionstatus/member/batch/get:
    POST:
      summary: Batchgetmemberec2deepinspectionstatus
      description: >-
        Retrieves Amazon Inspector deep inspection activation status of multiple
        member accounts within your organization. You must be the delegated
        administrator of an organization in Amazon Inspector to use this API.
      operationId: amazonWebServicesBatchGetMemberEc2DeepInspectionStatus
  /ec2deepinspectionstatus/member/batch/update:
    POST:
      summary: Batchupdatememberec2deepinspectionstatus
      description: >-
        Activates or deactivates Amazon Inspector deep inspection for the
        provided member accounts in your organization. You must be the delegated
        administrator of an organization in Amazon Inspector to use this API.
      operationId: amazonWebServicesBatchUpdateMemberEc2DeepInspectionStatus
  /reporting/cancel:
    POST:
      summary: Cancelfindingsreport
      description: Cancels the given findings report.
      operationId: amazonWebServicesCancelFindingsReport
  /sbomexport/cancel:
    POST:
      summary: Cancelsbomexport
      description: Cancels a software bill of materials (SBOM) report.
      operationId: amazonWebServicesCancelSbomExport
  /cis/scan-configuration/create:
    POST:
      summary: Createcisscanconfiguration
      description: Creates a CIS scan configuration.
      operationId: amazonWebServicesCreateCisScanConfiguration
  /filters/create:
    POST:
      summary: Createfilter
      description: >-
        Creates a filter resource using specified filter criteria. When the
        filter action is set to SUPPRESS this action creates a suppression rule.
      operationId: amazonWebServicesCreateFilter
  /reporting/create:
    POST:
      summary: Createfindingsreport
      description: >-
        Creates a finding report. By default only ACTIVE findings are returned
        in the report. To see SUPRESSED or CLOSED findings you must specify a
        value for the findingStatus filter criteria. 
      operationId: amazonWebServicesCreateFindingsReport
  /sbomexport/create:
    POST:
      summary: Createsbomexport
      description: Creates a software bill of materials (SBOM) report.
      operationId: amazonWebServicesCreateSbomExport
  /cis/scan-configuration/delete:
    POST:
      summary: Deletecisscanconfiguration
      description: Deletes a CIS scan configuration.
      operationId: amazonWebServicesDeleteCisScanConfiguration
  /filters/delete:
    POST:
      summary: Deletefilter
      description: Deletes a filter resource.
      operationId: amazonWebServicesDeleteFilter
  /organizationconfiguration/describe:
    POST:
      summary: Describeorganizationconfiguration
      description: >-
        Describe Amazon Inspector configuration settings for an Amazon Web
        Services organization.
      operationId: amazonWebServicesDescribeOrganizationConfiguration
  /disable:
    POST:
      summary: Disable
      description: >-
        Disables Amazon Inspector scans for one or more Amazon Web Services
        accounts. Disabling all scan types in an account disables the Amazon
        Inspector service.
      operationId: amazonWebServicesDisable
  /delegatedadminaccounts/disable:
    POST:
      summary: Disabledelegatedadminaccount
      description: >-
        Disables the Amazon Inspector delegated administrator for your
        organization.
      operationId: amazonWebServicesDisableDelegatedAdminAccount
  /members/disassociate:
    POST:
      summary: Disassociatemember
      description: >-
        Disassociates a member account from an Amazon Inspector delegated
        administrator.
      operationId: amazonWebServicesDisassociateMember
  /enable:
    POST:
      summary: Enable
      description: >-
        Enables Amazon Inspector scans for one or more Amazon Web Services
        accounts.
      operationId: amazonWebServicesEnable
  /delegatedadminaccounts/enable:
    POST:
      summary: Enabledelegatedadminaccount
      description: >-
        Enables the Amazon Inspector delegated administrator for your
        Organizations organization.
      operationId: amazonWebServicesEnableDelegatedAdminAccount
  /cis/scan/report/get:
    POST:
      summary: Getcisscanreport
      description: Retrieves a CIS scan report.
      operationId: amazonWebServicesGetCisScanReport
  /cis/scan-result/details/get:
    POST:
      summary: Getcisscanresultdetails
      description: Retrieves CIS scan result details.
      operationId: amazonWebServicesGetCisScanResultDetails
  /configuration/get:
    POST:
      summary: Getconfiguration
      description: Retrieves setting configurations for Inspector scans.
      operationId: amazonWebServicesGetConfiguration
  /delegatedadminaccounts/get:
    POST:
      summary: Getdelegatedadminaccount
      description: >-
        Retrieves information about the Amazon Inspector delegated administrator
        for your organization.
      operationId: amazonWebServicesGetDelegatedAdminAccount
  /ec2deepinspectionconfiguration/get:
    POST:
      summary: Getec2deepinspectionconfiguration
      description: >-
        Retrieves the activation status of Amazon Inspector deep inspection and
        custom paths associated with your account. 
      operationId: amazonWebServicesGetEc2DeepInspectionConfiguration
  /encryptionkey/get:
    GET:
      summary: Getencryptionkey
      description: Gets an encryption key.
      operationId: amazonWebServicesGetEncryptionKey
  /reporting/status/get:
    POST:
      summary: Getfindingsreportstatus
      description: Gets the status of a findings report.
      operationId: amazonWebServicesGetFindingsReportStatus
  /members/get:
    POST:
      summary: Getmember
      description: Gets member information for your organization.
      operationId: amazonWebServicesGetMember
  /sbomexport/get:
    POST:
      summary: Getsbomexport
      description: Gets details of a software bill of materials (SBOM) report.
      operationId: amazonWebServicesGetSbomExport
  /accountpermissions/list:
    POST:
      summary: Listaccountpermissions
      description: Lists the permissions an account has to configure Amazon Inspector.
      operationId: amazonWebServicesListAccountPermissions
  /cis/scan-configuration/list:
    POST:
      summary: Listcisscanconfigurations
      description: Lists CIS scan configurations.
      operationId: amazonWebServicesListCisScanConfigurations
  /cis/scan-result/check/list:
    POST:
      summary: Listcisscanresultsaggregatedbychecks
      description: Lists scan results aggregated by checks.
      operationId: amazonWebServicesListCisScanResultsAggregatedByChecks
  /cis/scan-result/resource/list:
    POST:
      summary: Listcisscanresultsaggregatedbytargetresource
      description: Lists scan results aggregated by a target resource.
      operationId: amazonWebServicesListCisScanResultsAggregatedByTargetResource
  /cis/scan/list:
    POST:
      summary: Listcisscans
      description: Returns a CIS scan list.
      operationId: amazonWebServicesListCisScans
  /coverage/list:
    POST:
      summary: Listcoverage
      description: Lists coverage details for you environment.
      operationId: amazonWebServicesListCoverage
  /coverage/statistics/list:
    POST:
      summary: Listcoveragestatistics
      description: Lists Amazon Inspector coverage statistics for your environment.
      operationId: amazonWebServicesListCoverageStatistics
  /delegatedadminaccounts/list:
    POST:
      summary: Listdelegatedadminaccounts
      description: >-
        Lists information about the Amazon Inspector delegated administrator of
        your organization.
      operationId: amazonWebServicesListDelegatedAdminAccounts
  /filters/list:
    POST:
      summary: Listfilters
      description: Lists the filters associated with your account.
      operationId: amazonWebServicesListFilters
  /findings/aggregation/list:
    POST:
      summary: Listfindingaggregations
      description: >-
        Lists aggregated finding data for your environment based on specific
        criteria.
      operationId: amazonWebServicesListFindingAggregations
  /findings/list:
    POST:
      summary: Listfindings
      description: Lists findings for your environment.
      operationId: amazonWebServicesListFindings
  /members/list:
    POST:
      summary: Listmembers
      description: >-
        List members associated with the Amazon Inspector delegated
        administrator for your organization.
      operationId: amazonWebServicesListMembers
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes tags from a resource.
      operationId: amazonWebServicesUntagResource
  /usage/list:
    POST:
      summary: Listusagetotals
      description: Lists the Amazon Inspector usage totals over the last 30 days.
      operationId: amazonWebServicesListUsageTotals
  /encryptionkey/reset:
    PUT:
      summary: Resetencryptionkey
      description: >-
        Resets an encryption key. After the key is reset your resources will be
        encrypted by an Amazon Web Services owned key.
      operationId: amazonWebServicesResetEncryptionKey
  /vulnerabilities/search:
    POST:
      summary: Searchvulnerabilities
      description: Lists Amazon Inspector coverage details for a specific vulnerability.
      operationId: amazonWebServicesSearchVulnerabilities
  /cissession/health/send:
    PUT:
      summary: Sendcissessionhealth
      description: ' Sends a CIS session health. This API is used by the Amazon Inspector SSM plugin to communicate with the Amazon Inspector service. The Amazon Inspector SSM plugin calls this API to start a CIS scan session for the scan ID supplied by the service. '
      operationId: amazonWebServicesSendCisSessionHealth
  /cissession/telemetry/send:
    PUT:
      summary: Sendcissessiontelemetry
      description: ' Sends a CIS session telemetry. This API is used by the Amazon Inspector SSM plugin to communicate with the Amazon Inspector service. The Amazon Inspector SSM plugin calls this API to start a CIS scan session for the scan ID supplied by the service. '
      operationId: amazonWebServicesSendCisSessionTelemetry
  /cissession/start:
    PUT:
      summary: Startcissession
      description: ' Starts a CIS session. This API is used by the Amazon Inspector SSM plugin to communicate with the Amazon Inspector service. The Amazon Inspector SSM plugin calls this API to start a CIS scan session for the scan ID supplied by the service. '
      operationId: amazonWebServicesStartCisSession
  /cissession/stop:
    PUT:
      summary: Stopcissession
      description: ' Stops a CIS session. This API is used by the Amazon Inspector SSM plugin to communicate with the Amazon Inspector service. The Amazon Inspector SSM plugin calls this API to start a CIS scan session for the scan ID supplied by the service. '
      operationId: amazonWebServicesStopCisSession
  /cis/scan-configuration/update:
    POST:
      summary: Updatecisscanconfiguration
      description: Updates a CIS scan configuration.
      operationId: amazonWebServicesUpdateCisScanConfiguration
  /configuration/update:
    POST:
      summary: Updateconfiguration
      description: >-
        Updates setting configurations for your Amazon Inspector account. When
        you use this API as an Amazon Inspector delegated administrator this
        updates the setting for all accounts you manage. Member accounts in an
        organization cannot update this setting.
      operationId: amazonWebServicesUpdateConfiguration
  /ec2deepinspectionconfiguration/update:
    POST:
      summary: Updateec2deepinspectionconfiguration
      description: >-
        Activates, deactivates Amazon Inspector deep inspection, or updates
        custom paths for your account. 
      operationId: amazonWebServicesUpdateEc2DeepInspectionConfiguration
  /encryptionkey/update:
    PUT:
      summary: Updateencryptionkey
      description: >-
        Updates an encryption key. A ResourceNotFoundException means that an
        Amazon Web Services owned key is being used for encryption.
      operationId: amazonWebServicesUpdateEncryptionKey
  /filters/update:
    POST:
      summary: Updatefilter
      description: >-
        Specifies the action that is to be applied to the findings that match
        the filter.
      operationId: amazonWebServicesUpdateFilter
  /ec2deepinspectionconfiguration/org/update:
    POST:
      summary: Updateorgec2deepinspectionconfiguration
      description: >-
        Updates the Amazon Inspector deep inspection custom paths for your
        organization. You must be an Amazon Inspector delegated administrator to
        use this API.
      operationId: amazonWebServicesUpdateOrgEc2DeepInspectionConfiguration
  /organizationconfiguration/update:
    POST:
      summary: Updateorganizationconfiguration
      description: Updates the configurations for your Amazon Inspector organization.
      operationId: amazonWebServicesUpdateOrganizationConfiguration
tags: []
