openapi: 3.1.0
info:
  title: inspector-scan
  description: >-
    <p>Amazon Inspector Scan is a vulnerability discovery service that scans a
    provided Software Bill of Materials (SBOM) for security vulnerabilities.</p>
paths:
  /scan/sbom:
    POST:
      summary: Scansbom
      description: >-
        Scans a provided CycloneDX 1.5 SBOM and reports on any vulnerabilities
        discovered in that SBOM. You can generate compatible SBOMs for your
        resources using the Amazon Inspector SBOM generator.
      operationId: amazonWebServicesScanSbom
tags: []
