openapi: 3.1.0
info:
  title: iot-roborunner
  description: >-
    <p>An example service, deployed with the Octane Service creator, which will
    echo the string</p>
paths:
  /createDestination:
    POST:
      summary: Createdestination
      description: Grants permission to create a destination
      operationId: amazonWebServicesCreateDestination
  /createSite:
    POST:
      summary: Createsite
      description: Grants permission to create a site
      operationId: amazonWebServicesCreateSite
  /createWorker:
    POST:
      summary: Createworker
      description: Grants permission to create a worker
      operationId: amazonWebServicesCreateWorker
  /createWorkerFleet:
    POST:
      summary: Createworkerfleet
      description: Grants permission to create a worker fleet
      operationId: amazonWebServicesCreateWorkerFleet
  /deleteDestination:
    POST:
      summary: Deletedestination
      description: Grants permission to delete a destination
      operationId: amazonWebServicesDeleteDestination
  /deleteSite:
    POST:
      summary: Deletesite
      description: Grants permission to delete a site
      operationId: amazonWebServicesDeleteSite
  /deleteWorker:
    POST:
      summary: Deleteworker
      description: Grants permission to delete a worker
      operationId: amazonWebServicesDeleteWorker
  /deleteWorkerFleet:
    POST:
      summary: Deleteworkerfleet
      description: Grants permission to delete a worker fleet
      operationId: amazonWebServicesDeleteWorkerFleet
  /getDestination:
    GET:
      summary: Getdestination
      description: Grants permission to get a destination
      operationId: amazonWebServicesGetDestination
  /getSite:
    GET:
      summary: Getsite
      description: Grants permission to get a site
      operationId: amazonWebServicesGetSite
  /getWorker:
    GET:
      summary: Getworker
      description: Grants permission to get a worker
      operationId: amazonWebServicesGetWorker
  /getWorkerFleet:
    GET:
      summary: Getworkerfleet
      description: Grants permission to get a worker fleet
      operationId: amazonWebServicesGetWorkerFleet
  /listDestinations:
    GET:
      summary: Listdestinations
      description: Grants permission to list destinations
      operationId: amazonWebServicesListDestinations
  /listSites:
    GET:
      summary: Listsites
      description: Grants permission to list sites
      operationId: amazonWebServicesListSites
  /listWorkerFleets:
    GET:
      summary: Listworkerfleets
      description: Grants permission to list worker fleets
      operationId: amazonWebServicesListWorkerFleets
  /listWorkers:
    GET:
      summary: Listworkers
      description: Grants permission to list workers
      operationId: amazonWebServicesListWorkers
  /updateDestination:
    POST:
      summary: Updatedestination
      description: Grants permission to update a destination
      operationId: amazonWebServicesUpdateDestination
  /updateSite:
    POST:
      summary: Updatesite
      description: Grants permission to update a site
      operationId: amazonWebServicesUpdateSite
  /updateWorker:
    POST:
      summary: Updateworker
      description: Grants permission to update a worker
      operationId: amazonWebServicesUpdateWorker
  /updateWorkerFleet:
    POST:
      summary: Updateworkerfleet
      description: Grants permission to update a worker fleet
      operationId: amazonWebServicesUpdateWorkerFleet
tags: []
