openapi: 3.1.0
info:
  title: iot-data
  description: >-
    <fullname>IoT data</fullname> <p>IoT data enables secure, bi-directional
    communication between Internet-connected things (such as sensors, actuators,
    embedded devices, or smart appliances) and the Amazon Web Services cloud. It
    implements a broker for applications and things to publish messages over
    HTTP (Publish) and retrieve, update, and delete shadows. A shadow is a
    persistent representation of your things and their state in the Amazon Web
    Services cloud.</p> <p>Find the endpoint address for actions in IoT data by
    running this CLI command:</p> <p> <code>aws iot describe-endpoint
    --endpoint-type iot:Data-ATS</code> </p> <p>The service name used by <a
    href="https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html">Amazon
    Web ServicesSignature Version 4</a> to sign requests is:
    <i>iotdevicegateway</i>.</p>
paths:
  /things/{thingName}/shadow:
    POST:
      summary: Updatethingshadow
      description: >-
        Updates the shadow for the specified thing. Requires permission to
        access the UpdateThingShadow action. For more information, see
        UpdateThingShadow in the IoT Developer Guide.
      operationId: amazonWebServicesUpdateThingShadow
  /retainedMessage/{topic}:
    GET:
      summary: Getretainedmessage
      description: >-
        Gets the details of a single retained message for the specified topic.
        This action returns the message payload of the retained message, which
        can incur messaging costs. To list only the topic names of the retained
        messages, call ListRetainedMessages. Requires permission to access the
        GetRetainedMessage action. For more information about messaging costs,
        see Amazon Web Services IoT Core pricing - Messaging.
      operationId: amazonWebServicesGetRetainedMessage
  /api/things/shadow/ListNamedShadowsForThing/{thingName}:
    GET:
      summary: Listnamedshadowsforthing
      description: >-
        Lists the shadows for the specified thing. Requires permission to access
        the ListNamedShadowsForThing action.
      operationId: amazonWebServicesListNamedShadowsForThing
  /retainedMessage:
    GET:
      summary: Listretainedmessages
      description: >-
        Lists summary information about the retained messages stored for the
        account. This action returns only the topic names of the retained
        messages. It doesn't return any message payloads. Although this action
        doesn't return a message payload, it can still incur messaging costs. To
        get the message payload of a retained message, call GetRetainedMessage
        with the topic name of the retained message. Requires permission to
        access the ListRetainedMessages action. For more information about
        messaging costs, see Amazon Web Services IoT Core pricing - Messaging.
      operationId: amazonWebServicesListRetainedMessages
  /topics/{topic}:
    POST:
      summary: Publish
      description: >-
        Publishes an MQTT message. Requires permission to access the Publish
        action. For more information about MQTT messages, see MQTT Protocol in
        the IoT Developer Guide. For more information about messaging costs, see
        Amazon Web Services IoT Core pricing - Messaging.
      operationId: amazonWebServicesPublish
tags: []
