openapi: 3.1.0
info:
  title: iot1click-devices
  description: >-
    <p>Describes all of the AWS IoT 1-Click device-related API operations for
    the service.
     Also provides sample requests, responses, and errors for the supported web services
     protocols.</p>
paths:
  /claims/{claimCode}:
    PUT:
      summary: Claimdevicesbyclaimcode
      description: >-
        Adds device(s) to your account (i.e., claim one or more devices) if and
        only if you<br> received a claim code with the device(s).
      operationId: amazonWebServicesClaimDevicesByClaimCode
  /devices/{deviceId}:
    GET:
      summary: Describedevice
      description: >-
        Given a device ID, returns a DescribeDeviceResponse object describing
        the<br> details of the device.
      operationId: amazonWebServicesDescribeDevice
  /devices/{deviceId}/finalize-claim:
    PUT:
      summary: Finalizedeviceclaim
      description: >-
        Given a device ID, finalizes the claim request for the associated
        device.<br> Claiming a device consists of initiating a claim, then
        publishing a device event,<br> and finalizing the claim. For a device of
        type button, a device event can<br> be published by simply clicking the
        device.<br> 
      operationId: amazonWebServicesFinalizeDeviceClaim
  /devices/{deviceId}/methods:
    POST:
      summary: Invokedevicemethod
      description: >-
        Given a device ID, issues a request to invoke a named device method
        (with possible<br> parameters). See the "Example POST" code snippet
        below.
      operationId: amazonWebServicesInvokeDeviceMethod
  /devices/{deviceId}/initiate-claim:
    PUT:
      summary: Initiatedeviceclaim
      description: >-
        Given a device ID, initiates a claim request for the associated
        device.<br> Claiming a device consists of initiating a claim, then
        publishing a device event,<br> and finalizing the claim. For a device of
        type button, a device event can<br> be published by simply clicking the
        device.<br> 
      operationId: amazonWebServicesInitiateDeviceClaim
  /devices/{deviceId}/events:
    GET:
      summary: Listdeviceevents
      description: >-
        Using a device ID, returns a DeviceEventsResponse object containing
        an<br> array of events for the device.
      operationId: amazonWebServicesListDeviceEvents
  /devices:
    GET:
      summary: Listdevices
      description: Lists the 1-Click compatible devices associated with your AWS account.
      operationId: amazonWebServicesListDevices
  /tags/{resource-arn}:
    DELETE:
      summary: Untagresource
      description: >-
        Using tag keys, deletes the tags (key/value pairs) associated with the
        specified<br> resource ARN.
      operationId: amazonWebServicesUntagResource
  /devices/{deviceId}/unclaim:
    PUT:
      summary: Unclaimdevice
      description: Disassociates a device from your AWS account using its device ID.
      operationId: amazonWebServicesUnclaimDevice
  /devices/{deviceId}/state:
    PUT:
      summary: Updatedevicestate
      description: >-
        Using a Boolean value (true or false), this operation<br> enables or
        disables the device given a device ID.
      operationId: amazonWebServicesUpdateDeviceState
tags: []
