openapi: 3.1.0
info:
  title: iot1click-projects
  description: <p>The AWS IoT 1-Click Projects API Reference</p>
paths:
  /projects/{projectName}/placements/{placementName}/devices/{deviceTemplateName}:
    DELETE:
      summary: Disassociatedevicefromplacement
      description: Removes a physical device from a placement.
      operationId: amazonWebServicesDisassociateDeviceFromPlacement
  /projects/{projectName}/placements:
    GET:
      summary: Listplacements
      description: Lists the placement(s) of a project.
      operationId: amazonWebServicesListPlacements
  /projects:
    GET:
      summary: Listprojects
      description: >-
        Lists the AWS IoT 1-Click project(s) associated with your AWS account
        and region.
      operationId: amazonWebServicesListProjects
  /projects/{projectName}/placements/{placementName}:
    PUT:
      summary: Updateplacement
      description: >-
        Updates a placement with the given attributes. To clear an attribute,
        pass an empty value (i.e., "").
      operationId: amazonWebServicesUpdatePlacement
  /projects/{projectName}:
    PUT:
      summary: Updateproject
      description: >-
        Updates a project associated with your AWS account and region. With the
        exception of device template names, you can pass just the values that
        need to be updated because the update request will change only the
        values that are provided. To clear a value, pass the empty string (i.e.,
        "").
      operationId: amazonWebServicesUpdateProject
  /projects/{projectName}/placements/{placementName}/devices:
    GET:
      summary: Getdevicesinplacement
      description: Returns an object enumerating the devices in a placement.
      operationId: amazonWebServicesGetDevicesInPlacement
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes one or more tags (metadata key/value pairs) from a resource.
      operationId: amazonWebServicesUntagResource
tags: []
