openapi: 3.1.0
info:
  title: iotanalytics
  description: >-
    <p>IoT Analytics allows you to collect large amounts of device data, process
    messages, and store them. You can then query the data and run sophisticated
    analytics on it. IoT Analytics enables advanced data exploration through
    integration with Jupyter Notebooks and data visualization through
    integration with Amazon QuickSight.</p> <p>Traditional analytics and
    business intelligence tools are designed to process structured data. IoT
    data often comes from devices that record noisy processes (such as
    temperature, motion, or sound). As a result the data from these devices can
    have significant gaps, corrupted messages, and false readings that must be
    cleaned up before analysis can occur. Also, IoT data is often only
    meaningful in the context of other data from external sources. </p> <p>IoT
    Analytics automates the steps required to analyze data from IoT devices. IoT
    Analytics filters, transforms, and enriches IoT data before storing it in a
    time-series data store for analysis. You can set up the service to collect
    only the data you need from your devices, apply mathematical transforms to
    process the data, and enrich the data with device-specific metadata such as
    device type and location before storing it. Then, you can analyze your data
    by running queries using the built-in SQL query engine, or perform more
    complex analytics and machine learning inference. IoT Analytics includes
    pre-built models for common IoT use cases so you can answer questions like
    which devices are about to fail or which customers are at risk of abandoning
    their wearable devices.</p>
paths:
  /messages/batch:
    POST:
      summary: Batchputmessage
      description: Sends messages to a channel.
      operationId: amazonWebServicesBatchPutMessage
  /pipelines/{pipelineName}/reprocessing/{reprocessingId}:
    DELETE:
      summary: Cancelpipelinereprocessing
      description: Cancels the reprocessing of data through the pipeline.
      operationId: amazonWebServicesCancelPipelineReprocessing
  /channels:
    GET:
      summary: Listchannels
      description: Retrieves a list of channels.
      operationId: amazonWebServicesListChannels
  /datasets:
    GET:
      summary: Listdatasets
      description: Retrieves information about datasets.
      operationId: amazonWebServicesListDatasets
  /datasets/{datasetName}/content:
    GET:
      summary: Getdatasetcontent
      description: Retrieves the contents of a dataset as presigned URIs.
      operationId: amazonWebServicesGetDatasetContent
  /datastores:
    GET:
      summary: Listdatastores
      description: Retrieves a list of data stores.
      operationId: amazonWebServicesListDatastores
  /pipelines:
    GET:
      summary: Listpipelines
      description: Retrieves a list of pipelines.
      operationId: amazonWebServicesListPipelines
  /channels/{channelName}:
    PUT:
      summary: Updatechannel
      description: Used to update the settings of a channel.
      operationId: amazonWebServicesUpdateChannel
  /datasets/{datasetName}:
    PUT:
      summary: Updatedataset
      description: Updates the settings of a dataset.
      operationId: amazonWebServicesUpdateDataset
  /datastores/{datastoreName}:
    PUT:
      summary: Updatedatastore
      description: Used to update the settings of a data store.
      operationId: amazonWebServicesUpdateDatastore
  /pipelines/{pipelineName}:
    PUT:
      summary: Updatepipeline
      description: >-
        Updates the settings of a pipeline. You must specify both a channel and
        a datastore activity and, optionally, as many as 23 additional
        activities in the pipelineActivities array.
      operationId: amazonWebServicesUpdatePipeline
  /logging:
    PUT:
      summary: Putloggingoptions
      description: >-
        Sets or updates the IoT Analytics logging options. If you update the
        value of any loggingOptions field, it takes up to one minute for the
        change to take effect. Also, if you change the policy attached to the
        role you specified in the roleArn field (for example, to correct an
        invalid policy), it takes up to five minutes for that change to take
        effect. 
      operationId: amazonWebServicesPutLoggingOptions
  /datasets/{datasetName}/contents:
    GET:
      summary: Listdatasetcontents
      description: Lists information about dataset contents that have been created.
      operationId: amazonWebServicesListDatasetContents
  /tags:
    DELETE:
      summary: Untagresource
      description: Removes the given tags (metadata) from the resource.
      operationId: amazonWebServicesUntagResource
  /pipelineactivities/run:
    POST:
      summary: Runpipelineactivity
      description: >-
        Simulates the results of running a pipeline activity on a message
        payload.
      operationId: amazonWebServicesRunPipelineActivity
  /channels/{channelName}/sample:
    GET:
      summary: Samplechanneldata
      description: >-
        Retrieves a sample of messages from the specified channel ingested
        during the specified timeframe. Up to 10 messages can be retrieved.
      operationId: amazonWebServicesSampleChannelData
  /pipelines/{pipelineName}/reprocessing:
    POST:
      summary: Startpipelinereprocessing
      description: Starts the reprocessing of raw message data through the pipeline.
      operationId: amazonWebServicesStartPipelineReprocessing
tags: []
