openapi: 3.1.0
info:
  title: iotdeviceadvisor
  description: >-
    <p>Amazon Web Services IoT Core Device Advisor is a cloud-based, fully
    managed test capability for validating IoT devices during device software
    development. Device Advisor provides pre-built tests that you can use to
    validate IoT devices for reliable and secure connectivity with Amazon Web
    Services IoT Core before deploying devices to production. By using Device
    Advisor, you can confirm that your devices can connect to Amazon Web
    Services IoT Core, follow security best practices and, if applicable,
    receive software updates from IoT Device Management. You can also download
    signed qualification reports to submit to the Amazon Web Services Partner
    Network to get your device qualified for the Amazon Web Services Partner
    Device Catalog without the need to send your device in and wait for it to be
    tested.</p>
paths:
  /suiteDefinitions:
    GET:
      summary: Listsuitedefinitions
      description: >-
        Lists the Device Advisor test suites you have created. Requires
        permission to access the ListSuiteDefinitions action.
      operationId: amazonWebServicesListSuiteDefinitions
  /suiteDefinitions/{suiteDefinitionId}:
    PATCH:
      summary: Updatesuitedefinition
      description: >-
        Updates a Device Advisor test suite. Requires permission to access the
        UpdateSuiteDefinition action.
      operationId: amazonWebServicesUpdateSuiteDefinition
  /endpoint:
    GET:
      summary: Getendpoint
      description: Gets information about an Device Advisor endpoint.
      operationId: amazonWebServicesGetEndpoint
  /suiteDefinitions/{suiteDefinitionId}/suiteRuns/{suiteRunId}:
    GET:
      summary: Getsuiterun
      description: >-
        Gets information about a Device Advisor test suite run. Requires
        permission to access the GetSuiteRun action.
      operationId: amazonWebServicesGetSuiteRun
  /suiteDefinitions/{suiteDefinitionId}/suiteRuns/{suiteRunId}/report:
    GET:
      summary: Getsuiterunreport
      description: >-
        Gets a report download link for a successful Device Advisor qualifying
        test suite run. Requires permission to access the GetSuiteRunReport
        action.
      operationId: amazonWebServicesGetSuiteRunReport
  /suiteRuns:
    GET:
      summary: Listsuiteruns
      description: >-
        Lists runs of the specified Device Advisor test suite. You can list all
        runs of the test suite, or the runs of a specific version of the test
        suite. Requires permission to access the ListSuiteRuns action.
      operationId: amazonWebServicesListSuiteRuns
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: >-
        Removes tags from an IoT Device Advisor resource. Requires permission to
        access the UntagResource action.
      operationId: amazonWebServicesUntagResource
  /suiteDefinitions/{suiteDefinitionId}/suiteRuns:
    POST:
      summary: Startsuiterun
      description: >-
        Starts a Device Advisor test suite run. Requires permission to access
        the StartSuiteRun action.
      operationId: amazonWebServicesStartSuiteRun
  /suiteDefinitions/{suiteDefinitionId}/suiteRuns/{suiteRunId}/stop:
    POST:
      summary: Stopsuiterun
      description: >-
        Stops a Device Advisor test suite run that is currently running.
        Requires permission to access the StopSuiteRun action.
      operationId: amazonWebServicesStopSuiteRun
tags: []
