openapi: 3.1.0
info:
  title: iotevents-data
  description: >-
    <p>IoT Events monitors your equipment or device fleets for failures or
    changes in operation, and triggers actions when such events occur. You can
    use IoT Events Data API commands to send inputs to detectors, list
    detectors, and view or update a detector's status.</p> <p> For more
    information, see <a
    href="https://docs.aws.amazon.com/iotevents/latest/developerguide/what-is-iotevents.html">What
    is IoT Events?</a> in the <i>IoT Events Developer Guide</i>.</p>
paths:
  /alarms/acknowledge:
    POST:
      summary: Batchacknowledgealarm
      description: >-
        Acknowledges one or more alarms. The alarms change to the ACKNOWLEDGED
        state after you acknowledge them.
      operationId: amazonWebServicesBatchAcknowledgeAlarm
  /detectors/delete:
    POST:
      summary: Batchdeletedetector
      description: >-
        Deletes one or more detectors that were created. When a detector is
        deleted, its state will be cleared and the detector will be removed from
        the list of detectors. The deleted detector will no longer appear if
        referenced in the ListDetectors API call.
      operationId: amazonWebServicesBatchDeleteDetector
  /alarms/disable:
    POST:
      summary: Batchdisablealarm
      description: >-
        Disables one or more alarms. The alarms change to the DISABLED state
        after you disable them.
      operationId: amazonWebServicesBatchDisableAlarm
  /alarms/enable:
    POST:
      summary: Batchenablealarm
      description: >-
        Enables one or more alarms. The alarms change to the NORMAL state after
        you enable them.
      operationId: amazonWebServicesBatchEnableAlarm
  /inputs/messages:
    POST:
      summary: Batchputmessage
      description: >-
        Sends a set of messages to the IoT Events system. Each message payload
        is transformed into the input you specify ("inputName") and ingested
        into any detectors that monitor that input. If multiple messages are
        sent, the order in which the messages are processed isn't guaranteed. To
        guarantee ordering, you must send messages one at a time and wait for a
        successful response.
      operationId: amazonWebServicesBatchPutMessage
  /alarms/reset:
    POST:
      summary: Batchresetalarm
      description: >-
        Resets one or more alarms. The alarms return to the NORMAL state after
        you reset them.
      operationId: amazonWebServicesBatchResetAlarm
  /alarms/snooze:
    POST:
      summary: Batchsnoozealarm
      description: >-
        Changes one or more alarms to the snooze mode. The alarms change to the
        SNOOZE_DISABLED state after you set them to the snooze mode.
      operationId: amazonWebServicesBatchSnoozeAlarm
  /detectors:
    POST:
      summary: Batchupdatedetector
      description: >-
        Updates the state, variable values, and timer settings of one or more
        detectors (instances) of a specified detector model.
      operationId: amazonWebServicesBatchUpdateDetector
  /alarms/{alarmModelName}/keyValues/:
    GET:
      summary: Describealarm
      description: Retrieves information about an alarm.
      operationId: amazonWebServicesDescribeAlarm
  /detectors/{detectorModelName}/keyValues/:
    GET:
      summary: Describedetector
      description: Returns information about the specified detector (instance).
      operationId: amazonWebServicesDescribeDetector
  /alarms/{alarmModelName}:
    GET:
      summary: Listalarms
      description: >-
        Lists one or more alarms. The operation returns only the metadata
        associated with each alarm.
      operationId: amazonWebServicesListAlarms
  /detectors/{detectorModelName}:
    GET:
      summary: Listdetectors
      description: Lists detectors (the instances of a detector model).
      operationId: amazonWebServicesListDetectors
tags: []
