openapi: 3.1.0
info:
  title: iotfleethub
  description: >-
    <p>With Fleet Hub for AWS IoT Device Management you can build stand-alone
    web applications for monitoring the health of your device fleets.</p> <note>
    <p>Fleet Hub for AWS IoT Device Management is in public preview and is
    subject to change.</p> </note>
paths:
  /applications:
    GET:
      summary: Listapplications
      description: >-
        Gets a list of Fleet Hub for AWS IoT Device Management web applications
        for the current account.  Fleet Hub for AWS IoT Device Management is in
        public preview and is subject to change. 
      operationId: amazonWebServicesListApplications
  /applications/{applicationId}:
    PATCH:
      summary: Updateapplication
      description: >-
        Updates information about a Fleet Hub for a AWS IoT Device Management
        web application.  Fleet Hub for AWS IoT Device Management is in public
        preview and is subject to change. 
      operationId: amazonWebServicesUpdateApplication
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: >-
        Removes the specified tags (metadata) from the resource.  Fleet Hub for
        AWS IoT Device Management is in public preview and is subject to
        change. 
      operationId: amazonWebServicesUntagResource
tags: []
