openapi: 3.1.0
info:
  title: iottwinmaker
  description: >-
    <p>IoT TwinMaker is a service with which you can build operational digital
    twins of physical systems. IoT TwinMaker overlays measurements and analysis
    from real-world sensors, cameras, and enterprise applications so you can
    create data visualizations to monitor your physical factory, building, or
    industrial plant. You can use this real-world data to monitor operations and
    diagnose and repair errors.</p>
paths:
  /workspaces/{workspaceId}/entity-properties:
    POST:
      summary: Batchputpropertyvalues
      description: Sets values for multiple time series properties.
      operationId: amazonWebServicesBatchPutPropertyValues
  /metadata-transfer-jobs/{metadataTransferJobId}/cancel:
    PUT:
      summary: Cancelmetadatatransferjob
      description: Cancels the metadata transfer job.
      operationId: amazonWebServicesCancelMetadataTransferJob
  /workspaces/{workspaceId}/component-types/{componentTypeId}:
    PUT:
      summary: Updatecomponenttype
      description: Updates information in a component type.
      operationId: amazonWebServicesUpdateComponentType
  /workspaces/{workspaceId}/entities:
    POST:
      summary: Createentity
      description: Creates an entity.
      operationId: amazonWebServicesCreateEntity
  /metadata-transfer-jobs:
    POST:
      summary: Createmetadatatransferjob
      description: Creates a new metadata transfer job.
      operationId: amazonWebServicesCreateMetadataTransferJob
  /workspaces/{workspaceId}/scenes:
    POST:
      summary: Createscene
      description: Creates a scene.
      operationId: amazonWebServicesCreateScene
  /workspaces/{workspaceId}/sync-jobs/{syncSource}:
    DELETE:
      summary: Deletesyncjob
      description: Delete the SyncJob.
      operationId: amazonWebServicesDeleteSyncJob
  /workspaces/{workspaceId}:
    PUT:
      summary: Updateworkspace
      description: Updates a workspace.
      operationId: amazonWebServicesUpdateWorkspace
  /workspaces/{workspaceId}/entities/{entityId}:
    PUT:
      summary: Updateentity
      description: Updates an entity.
      operationId: amazonWebServicesUpdateEntity
  /workspaces/{workspaceId}/scenes/{sceneId}:
    PUT:
      summary: Updatescene
      description: Updates a scene.
      operationId: amazonWebServicesUpdateScene
  /queries/execution:
    POST:
      summary: Executequery
      description: >-
        Run queries to access information from your knowledge graph of entities
        within individual workspaces.  The ExecuteQuery action only works with
        Amazon Web Services Java SDK2. ExecuteQuery will not work with any
        Amazon Web Services Java SDK version &lt; 2.x. 
      operationId: amazonWebServicesExecuteQuery
  /metadata-transfer-jobs/{metadataTransferJobId}:
    GET:
      summary: Getmetadatatransferjob
      description: Gets a nmetadata transfer job.
      operationId: amazonWebServicesGetMetadataTransferJob
  /pricingplan:
    POST:
      summary: Updatepricingplan
      description: Update the pricing plan.
      operationId: amazonWebServicesUpdatePricingPlan
  /workspaces/{workspaceId}/entity-properties/value:
    POST:
      summary: Getpropertyvalue
      description: >-
        Gets the property values for a component, component type, entity, or
        workspace. You must specify a value for either componentName,
        componentTypeId, entityId, or workspaceId.
      operationId: amazonWebServicesGetPropertyValue
  /workspaces/{workspaceId}/entity-properties/history:
    POST:
      summary: Getpropertyvaluehistory
      description: >-
        Retrieves information about the history of a time series property value
        for a component, component type, entity, or workspace. You must specify
        a value for workspaceId. For entity-specific queries, specify values for
        componentName and entityId. For cross-entity quries, specify a value for
        componentTypeId.
      operationId: amazonWebServicesGetPropertyValueHistory
  /sync-jobs/{syncSource}:
    GET:
      summary: Getsyncjob
      description: Gets the SyncJob.
      operationId: amazonWebServicesGetSyncJob
  /workspaces/{workspaceId}/component-types-list:
    POST:
      summary: Listcomponenttypes
      description: Lists all component types in a workspace.
      operationId: amazonWebServicesListComponentTypes
  /workspaces/{workspaceId}/entities/{entityId}/components-list:
    POST:
      summary: Listcomponents
      description: This API lists the components of an entity.
      operationId: amazonWebServicesListComponents
  /workspaces/{workspaceId}/entities-list:
    POST:
      summary: Listentities
      description: Lists all entities in a workspace.
      operationId: amazonWebServicesListEntities
  /metadata-transfer-jobs-list:
    POST:
      summary: Listmetadatatransferjobs
      description: Lists the metadata transfer jobs.
      operationId: amazonWebServicesListMetadataTransferJobs
  /workspaces/{workspaceId}/properties-list:
    POST:
      summary: Listproperties
      description: This API lists the properties of a component.
      operationId: amazonWebServicesListProperties
  /workspaces/{workspaceId}/scenes-list:
    POST:
      summary: Listscenes
      description: Lists all scenes in a workspace.
      operationId: amazonWebServicesListScenes
  /workspaces/{workspaceId}/sync-jobs-list:
    POST:
      summary: Listsyncjobs
      description: List all SyncJobs.
      operationId: amazonWebServicesListSyncJobs
  /workspaces/{workspaceId}/sync-jobs/{syncSource}/resources-list:
    POST:
      summary: Listsyncresources
      description: Lists the sync resources.
      operationId: amazonWebServicesListSyncResources
  /tags-list:
    POST:
      summary: Listtagsforresource
      description: Lists all tags associated with a resource.
      operationId: amazonWebServicesListTagsForResource
  /workspaces-list:
    POST:
      summary: Listworkspaces
      description: Retrieves information about workspaces in the current account.
      operationId: amazonWebServicesListWorkspaces
  /tags:
    DELETE:
      summary: Untagresource
      description: Removes tags from a resource.
      operationId: amazonWebServicesUntagResource
tags: []
