openapi: 3.1.0
info:
  title: iotwireless
  description: >-
    <p>AWS IoT Wireless provides bi-directional communication between
    internet-connected wireless devices and the AWS Cloud. To onboard both
    LoRaWAN and Sidewalk devices to AWS IoT, use the IoT Wireless API. These
    wireless devices use the Low Power Wide Area Networking (LPWAN)
    communication protocol to communicate with AWS IoT.</p> <p>Using the API,
    you can perform create, read, update, and delete operations for your
    wireless devices, gateways, destinations, and profiles. After onboarding
    your devices, you can use the API operations to set log levels and monitor
    your devices with CloudWatch.</p> <p>You can also use the API operations to
    create multicast groups and schedule a multicast session for sending a
    downlink message to devices in the group. By using Firmware Updates
    Over-The-Air (FUOTA) API operations, you can create a FUOTA task and
    schedule a session to update the firmware of individual devices or an entire
    group of devices in a multicast group.</p>
paths:
  /partner-accounts:
    GET:
      summary: Listpartneraccounts
      description: Lists the partner accounts associated with your AWS account.
      operationId: amazonWebServicesListPartnerAccounts
  /fuota-tasks/{Id}/multicast-group:
    PUT:
      summary: Associatemulticastgroupwithfuotatask
      description: Associate a multicast group with a FUOTA task.
      operationId: amazonWebServicesAssociateMulticastGroupWithFuotaTask
  /fuota-tasks/{Id}/wireless-device:
    PUT:
      summary: Associatewirelessdevicewithfuotatask
      description: Associate a wireless device with a FUOTA task.
      operationId: amazonWebServicesAssociateWirelessDeviceWithFuotaTask
  /multicast-groups/{Id}/wireless-device:
    PUT:
      summary: Associatewirelessdevicewithmulticastgroup
      description: Associates a wireless device with a multicast group.
      operationId: amazonWebServicesAssociateWirelessDeviceWithMulticastGroup
  /wireless-devices/{Id}/thing:
    DELETE:
      summary: Disassociatewirelessdevicefromthing
      description: Disassociates a wireless device from its currently associated thing.
      operationId: amazonWebServicesDisassociateWirelessDeviceFromThing
  /wireless-gateways/{Id}/certificate:
    GET:
      summary: Getwirelessgatewaycertificate
      description: >-
        Gets the ID of the certificate that is currently associated with a
        wireless gateway.
      operationId: amazonWebServicesGetWirelessGatewayCertificate
  /wireless-gateways/{Id}/thing:
    DELETE:
      summary: Disassociatewirelessgatewayfromthing
      description: Disassociates a wireless gateway from its currently associated thing.
      operationId: amazonWebServicesDisassociateWirelessGatewayFromThing
  /multicast-groups/{Id}/session:
    PUT:
      summary: Startmulticastgroupsession
      description: Starts a multicast group session.
      operationId: amazonWebServicesStartMulticastGroupSession
  /destinations:
    GET:
      summary: Listdestinations
      description: Lists the destinations registered to your AWS account.
      operationId: amazonWebServicesListDestinations
  /device-profiles:
    GET:
      summary: Listdeviceprofiles
      description: Lists the device profiles registered to your AWS account.
      operationId: amazonWebServicesListDeviceProfiles
  /fuota-tasks:
    GET:
      summary: Listfuotatasks
      description: Lists the FUOTA tasks registered to your AWS account.
      operationId: amazonWebServicesListFuotaTasks
  /multicast-groups:
    GET:
      summary: Listmulticastgroups
      description: Lists the multicast groups registered to your AWS account.
      operationId: amazonWebServicesListMulticastGroups
  /network-analyzer-configurations:
    GET:
      summary: Listnetworkanalyzerconfigurations
      description: Lists the network analyzer configurations.
      operationId: amazonWebServicesListNetworkAnalyzerConfigurations
  /service-profiles:
    GET:
      summary: Listserviceprofiles
      description: Lists the service profiles registered to your AWS account.
      operationId: amazonWebServicesListServiceProfiles
  /wireless-devices:
    GET:
      summary: Listwirelessdevices
      description: Lists the wireless devices registered to your AWS account.
      operationId: amazonWebServicesListWirelessDevices
  /wireless-gateways:
    GET:
      summary: Listwirelessgateways
      description: Lists the wireless gateways registered to your AWS account.
      operationId: amazonWebServicesListWirelessGateways
  /wireless-gateways/{Id}/tasks:
    GET:
      summary: Getwirelessgatewaytask
      description: Gets information about a wireless gateway task.
      operationId: amazonWebServicesGetWirelessGatewayTask
  /wireless-gateway-task-definitions:
    GET:
      summary: Listwirelessgatewaytaskdefinitions
      description: >-
        List the wireless gateway tasks definitions registered to your AWS
        account.
      operationId: amazonWebServicesListWirelessGatewayTaskDefinitions
  /destinations/{Name}:
    PATCH:
      summary: Updatedestination
      description: Updates properties of a destination.
      operationId: amazonWebServicesUpdateDestination
  /device-profiles/{Id}:
    GET:
      summary: Getdeviceprofile
      description: Gets information about a device profile.
      operationId: amazonWebServicesGetDeviceProfile
  /fuota-tasks/{Id}:
    PATCH:
      summary: Updatefuotatask
      description: Updates properties of a FUOTA task.
      operationId: amazonWebServicesUpdateFuotaTask
  /multicast-groups/{Id}:
    PATCH:
      summary: Updatemulticastgroup
      description: Updates properties of a multicast group session.
      operationId: amazonWebServicesUpdateMulticastGroup
  /network-analyzer-configurations/{ConfigurationName}:
    PATCH:
      summary: Updatenetworkanalyzerconfiguration
      description: Update network analyzer configuration.
      operationId: amazonWebServicesUpdateNetworkAnalyzerConfiguration
  /wireless-devices/{Id}/data:
    POST:
      summary: Senddatatowirelessdevice
      description: Sends a decrypted application data frame to a device.
      operationId: amazonWebServicesSendDataToWirelessDevice
  /service-profiles/{Id}:
    GET:
      summary: Getserviceprofile
      description: Gets information about a service profile.
      operationId: amazonWebServicesGetServiceProfile
  /wireless-devices/{Id}:
    PATCH:
      summary: Updatewirelessdevice
      description: Updates properties of a wireless device.
      operationId: amazonWebServicesUpdateWirelessDevice
  /wireless_device_import_task/{Id}:
    PATCH:
      summary: Updatewirelessdeviceimporttask
      description: Update an import task to add more devices to the task.
      operationId: amazonWebServicesUpdateWirelessDeviceImportTask
  /wireless-gateways/{Id}:
    PATCH:
      summary: Updatewirelessgateway
      description: Updates properties of a wireless gateway.
      operationId: amazonWebServicesUpdateWirelessGateway
  /wireless-gateway-task-definitions/{Id}:
    GET:
      summary: Getwirelessgatewaytaskdefinition
      description: Gets information about a wireless gateway task definition.
      operationId: amazonWebServicesGetWirelessGatewayTaskDefinition
  /wireless-devices/{Identifier}/deregister:
    PATCH:
      summary: Deregisterwirelessdevice
      description: Deregister a wireless device from AWS IoT Wireless.
      operationId: amazonWebServicesDeregisterWirelessDevice
  /partner-accounts/{PartnerAccountId}:
    PATCH:
      summary: Updatepartneraccount
      description: Updates properties of a partner account.
      operationId: amazonWebServicesUpdatePartnerAccount
  /fuota-tasks/{Id}/multicast-groups/{MulticastGroupId}:
    DELETE:
      summary: Disassociatemulticastgroupfromfuotatask
      description: Disassociates a multicast group from a fuota task.
      operationId: amazonWebServicesDisassociateMulticastGroupFromFuotaTask
  /fuota-tasks/{Id}/wireless-devices/{WirelessDeviceId}:
    DELETE:
      summary: Disassociatewirelessdevicefromfuotatask
      description: Disassociates a wireless device from a FUOTA task.
      operationId: amazonWebServicesDisassociateWirelessDeviceFromFuotaTask
  /multicast-groups/{Id}/wireless-devices/{WirelessDeviceId}:
    DELETE:
      summary: Disassociatewirelessdevicefrommulticastgroup
      description: Disassociates a wireless device from a multicast group.
      operationId: amazonWebServicesDisassociateWirelessDeviceFromMulticastGroup
  /event-configurations-resource-types:
    PATCH:
      summary: Updateeventconfigurationbyresourcetypes
      description: Update the event configuration based on resource types.
      operationId: amazonWebServicesUpdateEventConfigurationByResourceTypes
  /log-levels:
    POST:
      summary: Updateloglevelsbyresourcetypes
      description: >-
        Set default log level, or log levels by resource types. This can be for
        wireless device log options or wireless gateways log options and is used
        to control the log messages that'll be displayed in CloudWatch.
      operationId: amazonWebServicesUpdateLogLevelsByResourceTypes
  /positions/{ResourceIdentifier}:
    PATCH:
      summary: Updateposition
      description: >-
        Update the position information of a resource.  This action is no longer
        supported. Calls to update the position information should use the
        UpdateResourcePosition API operation instead. 
      operationId: amazonWebServicesUpdatePosition
  /position-configurations/{ResourceIdentifier}:
    PUT:
      summary: Putpositionconfiguration
      description: >-
        Put position configuration for a given resource.  This action is no
        longer supported. Calls to update the position configuration should use
        the UpdateResourcePosition API operation instead. 
      operationId: amazonWebServicesPutPositionConfiguration
  /position-estimate:
    POST:
      summary: Getpositionestimate
      description: >-
        Get estimated position information as a payload in GeoJSON format. The
        payload measurement data is resolved using solvers that are provided by
        third-party vendors.
      operationId: amazonWebServicesGetPositionEstimate
  /event-configurations/{Identifier}:
    PATCH:
      summary: Updateresourceeventconfiguration
      description: Update the event configuration for a particular resource identifier.
      operationId: amazonWebServicesUpdateResourceEventConfiguration
  /log-levels/{ResourceIdentifier}:
    DELETE:
      summary: Resetresourceloglevel
      description: >-
        Removes the log-level override, if any, for a specific resource-ID and
        resource-type. It can be used for a wireless device or a wireless
        gateway.
      operationId: amazonWebServicesResetResourceLogLevel
  /resource-positions/{ResourceIdentifier}:
    PATCH:
      summary: Updateresourceposition
      description: >-
        Update the position information of a given wireless device or a wireless
        gateway resource. The position coordinates are based on the  World
        Geodetic System (WGS84).
      operationId: amazonWebServicesUpdateResourcePosition
  /service-endpoint:
    GET:
      summary: Getserviceendpoint
      description: >-
        Gets the account-specific endpoint for Configuration and Update Server
        (CUPS) protocol or LoRaWAN Network Server (LNS) connections.
      operationId: amazonWebServicesGetServiceEndpoint
  /wireless-devices/{Identifier}:
    GET:
      summary: Getwirelessdevice
      description: Gets information about a wireless device.
      operationId: amazonWebServicesGetWirelessDevice
  /wireless-devices/{Id}/statistics:
    GET:
      summary: Getwirelessdevicestatistics
      description: Gets operating information about a wireless device.
      operationId: amazonWebServicesGetWirelessDeviceStatistics
  /wireless-gateways/{Identifier}:
    GET:
      summary: Getwirelessgateway
      description: Gets information about a wireless gateway.
      operationId: amazonWebServicesGetWirelessGateway
  /wireless-gateways/{Id}/firmware-information:
    GET:
      summary: Getwirelessgatewayfirmwareinformation
      description: >-
        Gets the firmware version and other information about a wireless
        gateway.
      operationId: amazonWebServicesGetWirelessGatewayFirmwareInformation
  /wireless-gateways/{Id}/statistics:
    GET:
      summary: Getwirelessgatewaystatistics
      description: Gets operating information about a wireless gateway.
      operationId: amazonWebServicesGetWirelessGatewayStatistics
  /wireless_device_import_task:
    POST:
      summary: Startwirelessdeviceimporttask
      description: >-
        Start import task for provisioning Sidewalk devices in bulk using an S3
        CSV file.
      operationId: amazonWebServicesStartWirelessDeviceImportTask
  /event-configurations:
    GET:
      summary: Listeventconfigurations
      description: >-
        List event configurations where at least one event topic has been
        enabled.
      operationId: amazonWebServicesListEventConfigurations
  /fuota-tasks/{Id}/multicast-groups:
    GET:
      summary: Listmulticastgroupsbyfuotatask
      description: List all multicast groups associated with a fuota task.
      operationId: amazonWebServicesListMulticastGroupsByFuotaTask
  /position-configurations:
    GET:
      summary: Listpositionconfigurations
      description: >-
        List position configurations for a given resource, such as positioning
        solvers.  This action is no longer supported. Calls to retrieve position
        information should use the GetResourcePosition API operation instead. 
      operationId: amazonWebServicesListPositionConfigurations
  /tags:
    DELETE:
      summary: Untagresource
      description: Removes one or more tags from a resource.
      operationId: amazonWebServicesUntagResource
  /wireless_device_import_tasks:
    GET:
      summary: Listwirelessdeviceimporttasks
      description: List wireless devices that have been added to an import task.
      operationId: amazonWebServicesListWirelessDeviceImportTasks
  /multicast-groups/{Id}/data:
    POST:
      summary: Senddatatomulticastgroup
      description: Sends the specified data to a multicast group.
      operationId: amazonWebServicesSendDataToMulticastGroup
  /multicast-groups/{Id}/bulk:
    POST:
      summary: Startbulkdisassociatewirelessdevicefrommulticastgroup
      description: >-
        Starts a bulk disassociatin of all qualifying wireless devices from a
        multicast group.
      operationId: amazonWebServicesStartBulkDisassociateWirelessDeviceFromMulticastGroup
  /wireless_single_device_import_task:
    POST:
      summary: Startsinglewirelessdeviceimporttask
      description: Start import task for a single wireless device.
      operationId: amazonWebServicesStartSingleWirelessDeviceImportTask
  /wireless-devices/{Id}/test:
    POST:
      summary: Testwirelessdevice
      description: >-
        Simulates a provisioned device by sending an uplink data payload of
        Hello.
      operationId: amazonWebServicesTestWirelessDevice
tags: []
