openapi: 3.1.0
info:
  title: kafka
  description: <p>The operations for managing an Amazon MSK cluster.</p>
paths:
  /v1/clusters/{clusterArn}/scram-secrets:
    GET:
      summary: Listscramsecrets
      description: >-
        Returns a list of the Scram Secrets associated with an Amazon MSK
        cluster.
      operationId: amazonWebServicesListScramSecrets
  /v1/clusters:
    GET:
      summary: Listclusters
      description: Returns a list of all the MSK clusters in the current Region.
      operationId: amazonWebServicesListClusters
  /api/v2/clusters:
    GET:
      summary: Listclustersv2
      description: Returns a list of all the MSK clusters in the current Region.
      operationId: amazonWebServicesListClustersV2
  /replication/v1/replicators:
    GET:
      summary: Listreplicators
      description: Lists the replicators.
      operationId: amazonWebServicesListReplicators
  /v1/configurations:
    GET:
      summary: Listconfigurations
      description: Returns a list of all the MSK configurations in this Region.
      operationId: amazonWebServicesListConfigurations
  /v1/vpc-connection:
    POST:
      summary: Createvpcconnection
      description: Creates a new Amazon MSK VPC connection.
      operationId: amazonWebServicesCreateVpcConnection
  /v1/clusters/{clusterArn}:
    GET:
      summary: Describecluster
      description: >-
        Returns a description of the MSK cluster whose Amazon Resource Name
        (ARN) is specified in the request.
      operationId: amazonWebServicesDescribeCluster
  /v1/clusters/{clusterArn}/policy:
    PUT:
      summary: Putclusterpolicy
      description: >-
        Creates or updates the specified MSK cluster policy. If updating the
        policy, the currentVersion field is required in the request payload.
      operationId: amazonWebServicesPutClusterPolicy
  /v1/configurations/{arn}:
    PUT:
      summary: Updateconfiguration
      description: >-
        Updates an existing MSK configuration. The configuration must be in the
        Active state.
      operationId: amazonWebServicesUpdateConfiguration
  /replication/v1/replicators/{replicatorArn}:
    GET:
      summary: Describereplicator
      description: >-
        Returns a description of the Kafka Replicator whose Amazon Resource Name
        (ARN) is specified in the request.
      operationId: amazonWebServicesDescribeReplicator
  /v1/vpc-connection/{arn}:
    GET:
      summary: Describevpcconnection
      description: Displays information about the specified Amazon MSK VPC connection.
      operationId: amazonWebServicesDescribeVpcConnection
  /api/v2/clusters/{clusterArn}:
    GET:
      summary: Describeclusterv2
      description: >-
        Returns a description of the MSK cluster of either the provisioned or
        the serverless type whose Amazon Resource Name (ARN) is specified in the
        request.
      operationId: amazonWebServicesDescribeClusterV2
  /v1/operations/{clusterOperationArn}:
    GET:
      summary: Describeclusteroperation
      description: Returns a description of the cluster operation specified by the ARN.
      operationId: amazonWebServicesDescribeClusterOperation
  /api/v2/operations/{clusterOperationArn}:
    GET:
      summary: Describeclusteroperationv2
      description: Returns a description of the cluster operation specified by the ARN.
      operationId: amazonWebServicesDescribeClusterOperationV2
  /v1/configurations/{arn}/revisions/{revision}:
    GET:
      summary: Describeconfigurationrevision
      description: Returns a description of this revision of the configuration.
      operationId: amazonWebServicesDescribeConfigurationRevision
  /v1/clusters/{clusterArn}/bootstrap-brokers:
    GET:
      summary: Getbootstrapbrokers
      description: A list of brokers that a client application can use to bootstrap.
      operationId: amazonWebServicesGetBootstrapBrokers
  /v1/compatible-kafka-versions:
    GET:
      summary: Getcompatiblekafkaversions
      description: Gets the Apache Kafka versions to which you can update the MSK cluster.
      operationId: amazonWebServicesGetCompatibleKafkaVersions
  /v1/clusters/{clusterArn}/client-vpc-connections:
    GET:
      summary: Listclientvpcconnections
      description: Displays a list of client VPC connections.
      operationId: amazonWebServicesListClientVpcConnections
  /v1/clusters/{clusterArn}/operations:
    GET:
      summary: Listclusteroperations
      description: >-
        Returns a list of all the operations that have been performed on the
        specified MSK cluster.
      operationId: amazonWebServicesListClusterOperations
  /api/v2/clusters/{clusterArn}/operations:
    GET:
      summary: Listclusteroperationsv2
      description: >-
        Returns a list of all the operations that have been performed on the
        specified MSK cluster.
      operationId: amazonWebServicesListClusterOperationsV2
  /v1/configurations/{arn}/revisions:
    GET:
      summary: Listconfigurationrevisions
      description: Returns a list of all the revisions of an MSK configuration.
      operationId: amazonWebServicesListConfigurationRevisions
  /v1/kafka-versions:
    GET:
      summary: Listkafkaversions
      description: Returns a list of Apache Kafka versions.
      operationId: amazonWebServicesListKafkaVersions
  /v1/clusters/{clusterArn}/nodes:
    GET:
      summary: Listnodes
      description: Returns a list of the broker nodes in the cluster.
      operationId: amazonWebServicesListNodes
  /v1/tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: >-
        Removes the tags associated with the keys that are provided in the
        query.
      operationId: amazonWebServicesUntagResource
  /v1/vpc-connections:
    GET:
      summary: Listvpcconnections
      description: Displays a list of Amazon MSK VPC connections.
      operationId: amazonWebServicesListVpcConnections
  /v1/clusters/{clusterArn}/reboot-broker:
    PUT:
      summary: Rebootbroker
      description: Executes a reboot on a broker.
      operationId: amazonWebServicesRebootBroker
  /v1/clusters/{clusterArn}/nodes/count:
    PUT:
      summary: Updatebrokercount
      description: >-
        Updates the number of broker nodes in the cluster. You can use this
        operation to increase the number of brokers in an existing cluster. You
        can't decrease the number of brokers.
      operationId: amazonWebServicesUpdateBrokerCount
  /v1/clusters/{clusterArn}/nodes/type:
    PUT:
      summary: Updatebrokertype
      description: Updates all the brokers in the cluster to the specified type.
      operationId: amazonWebServicesUpdateBrokerType
  /v1/clusters/{clusterArn}/nodes/storage:
    PUT:
      summary: Updatebrokerstorage
      description: Updates the EBS storage associated with MSK brokers.
      operationId: amazonWebServicesUpdateBrokerStorage
  /v1/clusters/{clusterArn}/connectivity:
    PUT:
      summary: Updateconnectivity
      description: Updates the connectivity configuration for the MSK cluster.
      operationId: amazonWebServicesUpdateConnectivity
  /v1/clusters/{clusterArn}/configuration:
    PUT:
      summary: Updateclusterconfiguration
      description: >-
        Updates the cluster with the configuration that is specified in the
        request body.
      operationId: amazonWebServicesUpdateClusterConfiguration
  /v1/clusters/{clusterArn}/version:
    PUT:
      summary: Updateclusterkafkaversion
      description: Updates the Apache Kafka version for the cluster.
      operationId: amazonWebServicesUpdateClusterKafkaVersion
  /v1/clusters/{clusterArn}/monitoring:
    PUT:
      summary: Updatemonitoring
      description: >-
        Updates the monitoring settings for the cluster. You can use this
        operation to specify which Apache Kafka metrics you want Amazon MSK to
        send to Amazon CloudWatch. You can also specify settings for open
        monitoring with Prometheus.
      operationId: amazonWebServicesUpdateMonitoring
  /replication/v1/replicators/{replicatorArn}/replication-info:
    PUT:
      summary: Updatereplicationinfo
      description: Updates replication info of a replicator.
      operationId: amazonWebServicesUpdateReplicationInfo
  /v1/clusters/{clusterArn}/security:
    PATCH:
      summary: Updatesecurity
      description: >-
        You can use this operation to update the encrypting and authentication
        settings for an existing cluster.
      operationId: amazonWebServicesUpdateSecurity
  /v1/clusters/{clusterArn}/storage:
    PUT:
      summary: Updatestorage
      description: >-
        Updates cluster broker volume size (or) sets cluster storage mode to
        TIERED.
      operationId: amazonWebServicesUpdateStorage
tags: []
