openapi: 3.1.0
info:
  title: kafkaconnect
  description: <p/>
paths:
  /v1/connectors:
    GET:
      summary: Listconnectors
      description: >-
        Returns a list of all the connectors in this account and Region. The
        list is limited to connectors whose name starts with the specified
        prefix. The response also includes a description of each of the listed
        connectors.
      operationId: amazonWebServicesListConnectors
  /v1/custom-plugins:
    GET:
      summary: Listcustomplugins
      description: Returns a list of all of the custom plugins in this account and Region.
      operationId: amazonWebServicesListCustomPlugins
  /v1/worker-configurations:
    GET:
      summary: Listworkerconfigurations
      description: >-
        Returns a list of all of the worker configurations in this account and
        Region.
      operationId: amazonWebServicesListWorkerConfigurations
  /v1/connectors/{connectorArn}:
    PUT:
      summary: Updateconnector
      description: Updates the specified connector.
      operationId: amazonWebServicesUpdateConnector
  /v1/custom-plugins/{customPluginArn}:
    GET:
      summary: Describecustomplugin
      description: A summary description of the custom plugin.
      operationId: amazonWebServicesDescribeCustomPlugin
  /v1/worker-configurations/{workerConfigurationArn}:
    GET:
      summary: Describeworkerconfiguration
      description: Returns information about a worker configuration.
      operationId: amazonWebServicesDescribeWorkerConfiguration
tags: []
