openapi: 3.1.0
info:
  title: kendra
  description: <p>Amazon Kendra is a service for indexing large document sets.</p>
paths:
  /:
    POST:
      summary: Updatethesaurus
      description: Updates a thesaurus for an index.
      operationId: amazonWebServicesUpdateThesaurus
tags: []
