openapi: 3.1.0
info:
  title: kinesisanalyticsv2
  description: >-
    <p>Amazon Kinesis Data Analytics is a fully managed service that you can use
    to process and analyze streaming data using Java, SQL, or Scala. The service
    enables you to quickly author and run Java, SQL, or Scala code against
    streaming sources to perform time series analytics, feed real-time
    dashboards, and create real-time metrics.</p>
paths:
  /:
    POST:
      summary: Updateapplicationmaintenanceconfiguration
      description: >-
        Updates the maintenance configuration of the Kinesis Data Analytics
        application.  You can invoke this operation on an application that is in
        one of the two following states: READY or RUNNING. If you invoke it when
        the application is in a state other than these two states, it throws a
        ResourceInUseException. The service makes use of the updated
        configuration the next time it schedules maintenance for the
        application. If you invoke this operation after the service schedules
        maintenance, the service will apply the configuration update the next
        time it schedules maintenance for the application. This means that you
        might not see the maintenance configuration update applied to the
        maintenance process that follows a successful invocation of this
        operation, but to the following maintenance process instead. To see the
        current maintenance configuration of your application, invoke the
        DescribeApplication operation. For information about application
        maintenance, see Kinesis Data Analytics for Apache Flink Maintenance. 
        This operation is supported only for Amazon Kinesis Data Analytics for
        Apache Flink. 
      operationId: amazonWebServicesUpdateApplicationMaintenanceConfiguration
tags: []
