openapi: 3.1.0
info:
  title: kinesis
  description: >-
    <fullname>Amazon Kinesis Data Streams Service API Reference</fullname>
    <p>Amazon Kinesis Data Streams is a managed service that scales elastically
    for real-time processing of streaming big data.</p>
paths:
  /:
    POST:
      summary: Updatestreammode
      description: ' Updates the capacity mode of the data stream. Currently, in Kinesis Data Streams, you can choose between an on-demand capacity mode and a provisioned capacity mode for your data stream. '
      operationId: amazonWebServicesUpdateStreamMode
tags: []
