openapi: 3.1.0
info:
  title: kinesisanalytics
  description: >-
    <fullname>Amazon Kinesis Analytics</fullname> <p> <b>Overview</b> </p>
    <note> <p>This documentation is for version 1 of the Amazon Kinesis Data
    Analytics API, which only supports SQL applications. Version 2 of the API
    supports SQL and Java applications. For more information about version 2,
    see <a href="/kinesisanalytics/latest/apiv2/Welcome.html">Amazon Kinesis
    Data Analytics API V2 Documentation</a>.</p> </note> <p>This is the
    <i>Amazon Kinesis Analytics v1 API Reference</i>. The Amazon Kinesis
    Analytics Developer Guide provides additional information. </p>
paths:
  /:
    POST:
      summary: Updateapplication
      description: ' This documentation is for version 1 of the Amazon Kinesis Data Analytics API, which only supports SQL applications. Version 2 of the API supports SQL and Java applications. For more information about version 2, see Amazon Kinesis Data Analytics API V2 Documentation.  Updates an existing Amazon Kinesis Analytics application. Using this API, you can update application code, input configuration, and output configuration.  Note that Amazon Kinesis Analytics updates the CurrentApplicationVersionId each time you update your application.  This operation requires permission for the kinesisanalytics:UpdateApplication action.'
      operationId: amazonWebServicesUpdateApplication
tags: []
