openapi: 3.1.0
info:
  title: launch-wizard
  description: >-
    <p>Launch Wizard offers a guided way of sizing, configuring, and deploying
    Amazon Web Services resources for third party applications, such as
    Microsoft SQL Server Always On and HANA based SAP systems, without the need
    to manually identify and provision individual Amazon Web Services
    resources.</p>
paths:
  /createDeployment:
    POST:
      summary: Createdeployment
      description: >-
        Creates a deployment for the given workload. Deployments created by this
        operation are not available in the Launch Wizard console to use the
        Clone deployment action on.
      operationId: amazonWebServicesCreateDeployment
  /deleteDeployment:
    POST:
      summary: Deletedeployment
      description: Deletes a deployment.
      operationId: amazonWebServicesDeleteDeployment
  /getDeployment:
    POST:
      summary: Getdeployment
      description: Returns information about the deployment.
      operationId: amazonWebServicesGetDeployment
  /getWorkload:
    POST:
      summary: Getworkload
      description: Returns information about a workload.
      operationId: amazonWebServicesGetWorkload
  /listDeploymentEvents:
    POST:
      summary: Listdeploymentevents
      description: Lists the events of a deployment.
      operationId: amazonWebServicesListDeploymentEvents
  /listDeployments:
    POST:
      summary: Listdeployments
      description: Lists the deployments that have been created.
      operationId: amazonWebServicesListDeployments
  /listWorkloadDeploymentPatterns:
    POST:
      summary: Listworkloaddeploymentpatterns
      description: Lists the workload deployment patterns.
      operationId: amazonWebServicesListWorkloadDeploymentPatterns
  /listWorkloads:
    POST:
      summary: Listworkloads
      description: Lists the workloads.
      operationId: amazonWebServicesListWorkloads
tags: []
