openapi: 3.1.0
info:
  title: license-manager-linux-subscriptions
  description: >-
    <p>With License Manager, you can discover and track your commercial Linux
    subscriptions on running Amazon EC2 instances.</p>
paths:
  /subscription/GetServiceSettings:
    POST:
      summary: Getservicesettings
      description: Lists the Linux subscriptions service settings.
      operationId: amazonWebServicesGetServiceSettings
  /subscription/ListLinuxSubscriptionInstances:
    POST:
      summary: Listlinuxsubscriptioninstances
      description: >-
        Lists the running Amazon EC2 instances that were discovered with
        commercial Linux subscriptions.
      operationId: amazonWebServicesListLinuxSubscriptionInstances
  /subscription/ListLinuxSubscriptions:
    POST:
      summary: Listlinuxsubscriptions
      description: >-
        Lists the Linux subscriptions that have been discovered. If you have
        linked your organization, the returned results will include data
        aggregated across your accounts in Organizations.
      operationId: amazonWebServicesListLinuxSubscriptions
  /subscription/UpdateServiceSettings:
    POST:
      summary: Updateservicesettings
      description: Updates the service settings for Linux subscriptions.
      operationId: amazonWebServicesUpdateServiceSettings
tags: []
