openapi: 3.1.0
info:
  title: license-manager
  description: >-
    <p>License Manager makes it easier to manage licenses from software vendors
    across multiple Amazon Web Services accounts and on-premises servers.</p>
paths:
  /:
    POST:
      summary: Updateservicesettings
      description: Updates License Manager settings for the current Region.
      operationId: amazonWebServicesUpdateServiceSettings
tags: []
