openapi: 3.1.0
info:
  title: license-manager-user-subscriptions
  description: >-
    <p>With License Manager, you can create user-based subscriptions to utilize
    licensed software with a per user subscription fee on Amazon EC2
    instances.</p>
paths:
  /user/AssociateUser:
    POST:
      summary: Associateuser
      description: >-
        Associates the user to an EC2 instance to utilize user-based
        subscriptions.  Your estimated bill for charges on the number of users
        and related costs will take 48 hours to appear for billing periods that
        haven't closed (marked as Pending billing status) in Amazon Web Services
        Billing. For more information, see Viewing your monthly charges in the
        Amazon Web Services Billing User Guide. 
      operationId: amazonWebServicesAssociateUser
  /identity-provider/DeregisterIdentityProvider:
    POST:
      summary: Deregisteridentityprovider
      description: >-
        Deregisters the identity provider from providing user-based
        subscriptions.
      operationId: amazonWebServicesDeregisterIdentityProvider
  /user/DisassociateUser:
    POST:
      summary: Disassociateuser
      description: >-
        Disassociates the user from an EC2 instance providing user-based
        subscriptions.
      operationId: amazonWebServicesDisassociateUser
  /identity-provider/ListIdentityProviders:
    POST:
      summary: Listidentityproviders
      description: Lists the identity providers for user-based subscriptions.
      operationId: amazonWebServicesListIdentityProviders
  /instance/ListInstances:
    POST:
      summary: Listinstances
      description: Lists the EC2 instances providing user-based subscriptions.
      operationId: amazonWebServicesListInstances
  /user/ListProductSubscriptions:
    POST:
      summary: Listproductsubscriptions
      description: >-
        Lists the user-based subscription products available from an identity
        provider.
      operationId: amazonWebServicesListProductSubscriptions
  /user/ListUserAssociations:
    POST:
      summary: Listuserassociations
      description: Lists user associations for an identity provider.
      operationId: amazonWebServicesListUserAssociations
  /identity-provider/RegisterIdentityProvider:
    POST:
      summary: Registeridentityprovider
      description: Registers an identity provider for user-based subscriptions.
      operationId: amazonWebServicesRegisterIdentityProvider
  /user/StartProductSubscription:
    POST:
      summary: Startproductsubscription
      description: >-
        Starts a product subscription for a user with the specified identity
        provider.  Your estimated bill for charges on the number of users and
        related costs will take 48 hours to appear for billing periods that
        haven't closed (marked as Pending billing status) in Amazon Web Services
        Billing. For more information, see Viewing your monthly charges in the
        Amazon Web Services Billing User Guide. 
      operationId: amazonWebServicesStartProductSubscription
  /user/StopProductSubscription:
    POST:
      summary: Stopproductsubscription
      description: >-
        Stops a product subscription for a user with the specified identity
        provider.
      operationId: amazonWebServicesStopProductSubscription
  /identity-provider/UpdateIdentityProviderSettings:
    POST:
      summary: Updateidentityprovidersettings
      description: >-
        Updates additional product configuration settings for the registered
        identity provider.
      operationId: amazonWebServicesUpdateIdentityProviderSettings
tags: []
