openapi: 3.1.0
info:
  title: location
  description: >-
    <p>"Suite of geospatial services including Maps, Places, Routes, Tracking,
    and Geofencing"</p>
paths:
  /tracking/v0/trackers/{TrackerName}/consumers:
    POST:
      summary: Associatetrackerconsumer
      description: >-
        Creates an association between a geofence collection and a tracker
        resource. This allows the tracker resource to communicate location data
        to the linked geofence collection.  You can associate up to five
        geofence collections to each tracker resource.  Currently not supported
        — Cross-account configurations, such as creating associations between a
        tracker resource in one account and a geofence collection in another
        account. 
      operationId: amazonWebServicesAssociateTrackerConsumer
  /tracking/v0/trackers/{TrackerName}/delete-positions:
    POST:
      summary: Batchdeletedevicepositionhistory
      description: >-
        Deletes the position history of one or more devices from a tracker
        resource.
      operationId: amazonWebServicesBatchDeleteDevicePositionHistory
  /geofencing/v0/collections/{CollectionName}/delete-geofences:
    POST:
      summary: Batchdeletegeofence
      description: >-
        Deletes a batch of geofences from a geofence collection.  This operation
        deletes the resource permanently. 
      operationId: amazonWebServicesBatchDeleteGeofence
  /geofencing/v0/collections/{CollectionName}/positions:
    POST:
      summary: Batchevaluategeofences
      description: >-
        Evaluates device positions against the geofence geometries from a given
        geofence collection. This operation always returns an empty response
        because geofences are asynchronously evaluated. The evaluation
        determines if the device has entered or exited a geofenced area, and
        then publishes one of the following events to Amazon EventBridge:   
        ENTER if Amazon Location determines that the tracked device has entered
        a geofenced area.    EXIT if Amazon Location determines that the tracked
        device has exited a geofenced area.    The last geofence that a device
        was observed within is tracked for 30 days after the most recent device
        position update.   Geofence evaluation uses the given device position.
        It does not account for the optional Accuracy of a
        DevicePositionUpdate.   The DeviceID is used as a string to represent
        the device. You do not need to have a Tracker associated with the
        DeviceID. 
      operationId: amazonWebServicesBatchEvaluateGeofences
  /tracking/v0/trackers/{TrackerName}/get-positions:
    POST:
      summary: Batchgetdeviceposition
      description: Lists the latest device positions for requested devices.
      operationId: amazonWebServicesBatchGetDevicePosition
  /geofencing/v0/collections/{CollectionName}/put-geofences:
    POST:
      summary: Batchputgeofence
      description: >-
        A batch request for storing geofence geometries into a given geofence
        collection, or updates the geometry of an existing geofence if a
        geofence ID is included in the request.
      operationId: amazonWebServicesBatchPutGeofence
  /tracking/v0/trackers/{TrackerName}/positions:
    POST:
      summary: Batchupdatedeviceposition
      description: >-
        Uploads position update data for one or more devices to a tracker
        resource (up to 10 devices per batch). Amazon Location uses the data
        when it reports the last known device position and position history.
        Amazon Location retains location data for 30 days.  Position updates are
        handled based on the PositionFiltering property of the tracker. When
        PositionFiltering is set to TimeBased, updates are evaluated against
        linked geofence collections, and location data is stored at a maximum of
        one position per 30 second interval. If your update frequency is more
        often than every 30 seconds, only one update per 30 seconds is stored
        for each unique device ID. When PositionFiltering is set to
        DistanceBased filtering, location data is stored and evaluated against
        linked geofence collections only if the device has moved more than 30 m
        (98.4 ft). When PositionFiltering is set to AccuracyBased filtering,
        location data is stored and evaluated against linked geofence
        collections only if the device has moved more than the measured
        accuracy. For example, if two consecutive updates from a device have a
        horizontal accuracy of 5 m and 10 m, the second update is neither stored
        or evaluated if the device has moved less than 15 m. If
        PositionFiltering is set to AccuracyBased filtering, Amazon Location
        uses the default value { "Horizontal": 0} when accuracy is not provided
        on a DevicePositionUpdate. 
      operationId: amazonWebServicesBatchUpdateDevicePosition
  /routes/v0/calculators/{CalculatorName}/calculate/route:
    POST:
      summary: Calculateroute
      description: ' Calculates a route given the following required parameters: DeparturePosition and DestinationPosition. Requires that you first create a route calculator resource. By default, a request that doesn''t specify a departure time uses the best time of day to travel with the best traffic conditions when calculating the route. Additional options include:    Specifying a departure time using either DepartureTime or DepartNow. This calculates a route based on predictive traffic data at the given time.   You can''t specify both DepartureTime and DepartNow in a single request. Specifying both parameters returns a validation error.     Specifying a travel mode using TravelMode sets the transportation mode used to calculate the routes. This also lets you specify additional route preferences in CarModeOptions if traveling by Car, or TruckModeOptions if traveling by Truck.  If you specify walking for the travel mode and your data provider is Esri, the start and destination must be within 40km.   '
      operationId: amazonWebServicesCalculateRoute
  /routes/v0/calculators/{CalculatorName}/calculate/route-matrix:
    POST:
      summary: Calculateroutematrix
      description: '  Calculates a route matrix given the following required parameters: DeparturePositions and DestinationPositions. CalculateRouteMatrix calculates routes and returns the travel time and travel distance from each departure position to each destination position in the request. For example, given departure positions A and B, and destination positions X and Y, CalculateRouteMatrix will return time and distance for routes from A to X, A to Y, B to X, and B to Y (in that order). The number of results returned (and routes calculated) will be the number of DeparturePositions times the number of DestinationPositions.  Your account is charged for each route calculated, not the number of requests.  Requires that you first create a route calculator resource. By default, a request that doesn''t specify a departure time uses the best time of day to travel with the best traffic conditions when calculating routes. Additional options include:     Specifying a departure time using either DepartureTime or DepartNow. This calculates routes based on predictive traffic data at the given time.   You can''t specify both DepartureTime and DepartNow in a single request. Specifying both parameters returns a validation error.     Specifying a travel mode using TravelMode sets the transportation mode used to calculate the routes. This also lets you specify additional route preferences in CarModeOptions if traveling by Car, or TruckModeOptions if traveling by Truck.  '
      operationId: amazonWebServicesCalculateRouteMatrix
  /geofencing/v0/collections:
    POST:
      summary: Creategeofencecollection
      description: Creates a geofence collection, which manages and stores geofences.
      operationId: amazonWebServicesCreateGeofenceCollection
  /metadata/v0/keys:
    POST:
      summary: Createkey
      description: >-
        Creates an API key resource in your Amazon Web Services account, which
        lets you grant actions for Amazon Location resources to the API key
        bearer.  For more information, see Using API keys. 
      operationId: amazonWebServicesCreateKey
  /maps/v0/maps:
    POST:
      summary: Createmap
      description: >-
        Creates a map resource in your Amazon Web Services account, which
        provides map tiles of different styles sourced from global location data
        providers.  If your application is tracking or routing assets you use in
        your business, such as delivery vehicles or employees, you must not use
        Esri as your geolocation provider. See section 82 of the Amazon Web
        Services service terms for more details. 
      operationId: amazonWebServicesCreateMap
  /places/v0/indexes:
    POST:
      summary: Createplaceindex
      description: >-
        Creates a place index resource in your Amazon Web Services account. Use
        a place index resource to geocode addresses and other text queries by
        using the SearchPlaceIndexForText operation, and reverse geocode
        coordinates by using the SearchPlaceIndexForPosition operation, and
        enable autosuggestions by using the SearchPlaceIndexForSuggestions
        operation.  If your application is tracking or routing assets you use in
        your business, such as delivery vehicles or employees, you must not use
        Esri as your geolocation provider. See section 82 of the Amazon Web
        Services service terms for more details. 
      operationId: amazonWebServicesCreatePlaceIndex
  /routes/v0/calculators:
    POST:
      summary: Createroutecalculator
      description: >-
        Creates a route calculator resource in your Amazon Web Services account.
        You can send requests to a route calculator resource to estimate travel
        time, distance, and get directions. A route calculator sources traffic
        and road network data from your chosen data provider.  If your
        application is tracking or routing assets you use in your business, such
        as delivery vehicles or employees, you must not use Esri as your
        geolocation provider. See section 82 of the Amazon Web Services service
        terms for more details. 
      operationId: amazonWebServicesCreateRouteCalculator
  /tracking/v0/trackers:
    POST:
      summary: Createtracker
      description: >-
        Creates a tracker resource in your Amazon Web Services account, which
        lets you retrieve current and historical location of devices.
      operationId: amazonWebServicesCreateTracker
  /geofencing/v0/collections/{CollectionName}:
    PATCH:
      summary: Updategeofencecollection
      description: Updates the specified properties of a given geofence collection.
      operationId: amazonWebServicesUpdateGeofenceCollection
  /metadata/v0/keys/{KeyName}:
    PATCH:
      summary: Updatekey
      description: Updates the specified properties of a given API key resource.
      operationId: amazonWebServicesUpdateKey
  /maps/v0/maps/{MapName}:
    PATCH:
      summary: Updatemap
      description: Updates the specified properties of a given map resource.
      operationId: amazonWebServicesUpdateMap
  /places/v0/indexes/{IndexName}:
    PATCH:
      summary: Updateplaceindex
      description: Updates the specified properties of a given place index resource.
      operationId: amazonWebServicesUpdatePlaceIndex
  /routes/v0/calculators/{CalculatorName}:
    PATCH:
      summary: Updateroutecalculator
      description: Updates the specified properties for a given route calculator resource.
      operationId: amazonWebServicesUpdateRouteCalculator
  /tracking/v0/trackers/{TrackerName}:
    PATCH:
      summary: Updatetracker
      description: Updates the specified properties of a given tracker resource.
      operationId: amazonWebServicesUpdateTracker
  /tracking/v0/trackers/{TrackerName}/consumers/{ConsumerArn}:
    DELETE:
      summary: Disassociatetrackerconsumer
      description: >-
        Removes the association between a tracker resource and a geofence
        collection.  Once you unlink a tracker resource from a geofence
        collection, the tracker positions will no longer be automatically
        evaluated against geofences. 
      operationId: amazonWebServicesDisassociateTrackerConsumer
  /tracking/v0/trackers/{TrackerName}/devices/{DeviceId}/positions/latest:
    GET:
      summary: Getdeviceposition
      description: >-
        Retrieves a device's most recent position according to its sample time. 
        Device positions are deleted after 30 days. 
      operationId: amazonWebServicesGetDevicePosition
  /tracking/v0/trackers/{TrackerName}/devices/{DeviceId}/list-positions:
    POST:
      summary: Getdevicepositionhistory
      description: >-
        Retrieves the device position history from a tracker resource within a
        specified range of time.  Device positions are deleted after 30 days. 
      operationId: amazonWebServicesGetDevicePositionHistory
  /geofencing/v0/collections/{CollectionName}/geofences/{GeofenceId}:
    PUT:
      summary: Putgeofence
      description: >-
        Stores a geofence geometry in a given geofence collection, or updates
        the geometry of an existing geofence if a geofence ID is included in the
        request. 
      operationId: amazonWebServicesPutGeofence
  /maps/v0/maps/{MapName}/glyphs/{FontStack}/{FontUnicodeRange}:
    GET:
      summary: Getmapglyphs
      description: Retrieves glyphs used to display labels on a map.
      operationId: amazonWebServicesGetMapGlyphs
  /maps/v0/maps/{MapName}/sprites/{FileName}:
    GET:
      summary: Getmapsprites
      description: >-
        Retrieves the sprite sheet corresponding to a map resource. The sprite
        sheet is a PNG image paired with a JSON document describing the offsets
        of individual icons that will be displayed on a rendered map.
      operationId: amazonWebServicesGetMapSprites
  /maps/v0/maps/{MapName}/style-descriptor:
    GET:
      summary: Getmapstyledescriptor
      description: >-
        Retrieves the map style descriptor from a map resource.  The style
        descriptor contains speciﬁcations on how features render on a map. For
        example, what data to display, what order to display the data in, and
        the style for the data. Style descriptors follow the Mapbox Style
        Specification.
      operationId: amazonWebServicesGetMapStyleDescriptor
  /maps/v0/maps/{MapName}/tiles/{Z}/{X}/{Y}:
    GET:
      summary: Getmaptile
      description: >-
        Retrieves a vector data tile from the map resource. Map tiles are used
        by clients to render a map. they're addressed using a grid arrangement
        with an X coordinate, Y coordinate, and Z (zoom) level.  The origin (0,
        0) is the top left of the map. Increasing the zoom level by 1 doubles
        both the X and Y dimensions, so a tile containing data for the entire
        world at (0/0/0) will be split into 4 tiles at zoom 1 (1/0/0, 1/0/1,
        1/1/0, 1/1/1).
      operationId: amazonWebServicesGetMapTile
  /places/v0/indexes/{IndexName}/places/{PlaceId}:
    GET:
      summary: Getplace
      description: >-
        Finds a place by its unique ID. A PlaceId is returned by other search
        operations.  A PlaceId is valid only if all of the following are the
        same in the original search request and the call to GetPlace.   Customer
        Amazon Web Services account   Amazon Web Services Region   Data provider
        specified in the place index resource   
      operationId: amazonWebServicesGetPlace
  /tracking/v0/trackers/{TrackerName}/list-positions:
    POST:
      summary: Listdevicepositions
      description: A batch request to retrieve all device positions.
      operationId: amazonWebServicesListDevicePositions
  /geofencing/v0/list-collections:
    POST:
      summary: Listgeofencecollections
      description: Lists geofence collections in your Amazon Web Services account.
      operationId: amazonWebServicesListGeofenceCollections
  /geofencing/v0/collections/{CollectionName}/list-geofences:
    POST:
      summary: Listgeofences
      description: Lists geofences stored in a given geofence collection.
      operationId: amazonWebServicesListGeofences
  /metadata/v0/list-keys:
    POST:
      summary: Listkeys
      description: Lists API key resources in your Amazon Web Services account.
      operationId: amazonWebServicesListKeys
  /maps/v0/list-maps:
    POST:
      summary: Listmaps
      description: Lists map resources in your Amazon Web Services account.
      operationId: amazonWebServicesListMaps
  /places/v0/list-indexes:
    POST:
      summary: Listplaceindexes
      description: Lists place index resources in your Amazon Web Services account.
      operationId: amazonWebServicesListPlaceIndexes
  /routes/v0/list-calculators:
    POST:
      summary: Listroutecalculators
      description: Lists route calculator resources in your Amazon Web Services account.
      operationId: amazonWebServicesListRouteCalculators
  /tags/{ResourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes one or more tags from the specified Amazon Location resource.
      operationId: amazonWebServicesUntagResource
  /tracking/v0/trackers/{TrackerName}/list-consumers:
    POST:
      summary: Listtrackerconsumers
      description: >-
        Lists geofence collections currently associated to the given tracker
        resource.
      operationId: amazonWebServicesListTrackerConsumers
  /tracking/v0/list-trackers:
    POST:
      summary: Listtrackers
      description: Lists tracker resources in your Amazon Web Services account.
      operationId: amazonWebServicesListTrackers
  /places/v0/indexes/{IndexName}/search/position:
    POST:
      summary: Searchplaceindexforposition
      description: >-
        Reverse geocodes a given coordinate and returns a legible address.
        Allows you to search for Places or points of interest near a given
        position.
      operationId: amazonWebServicesSearchPlaceIndexForPosition
  /places/v0/indexes/{IndexName}/search/suggestions:
    POST:
      summary: Searchplaceindexforsuggestions
      description: >-
        Generates suggestions for addresses and points of interest based on
        partial or misspelled free-form text. This operation is also known as
        autocomplete, autosuggest, or fuzzy matching. Optional parameters let
        you narrow your search results by bounding box or country, or bias your
        search toward a specific position on the globe.  You can search for
        suggested place names near a specified position by using BiasPosition,
        or filter results within a bounding box by using FilterBBox. These
        parameters are mutually exclusive; using both BiasPosition and
        FilterBBox in the same command returns an error. 
      operationId: amazonWebServicesSearchPlaceIndexForSuggestions
  /places/v0/indexes/{IndexName}/search/text:
    POST:
      summary: Searchplaceindexfortext
      description: >-
        Geocodes free-form text, such as an address, name, city, or region to
        allow you to search for Places or points of interest.  Optional
        parameters let you narrow your search results by bounding box or
        country, or bias your search toward a specific position on the globe. 
        You can search for places near a given position using BiasPosition, or
        filter results within a bounding box using FilterBBox. Providing both
        parameters simultaneously returns an error.  Search results are returned
        in order of highest to lowest relevance.
      operationId: amazonWebServicesSearchPlaceIndexForText
tags: []
