openapi: 3.1.0
info:
  title: lookoutequipment
  description: >-
    <p>Amazon Lookout for Equipment is a machine learning service that uses
    advanced analytics to identify anomalies in machines from sensor data for
    use in predictive maintenance. </p>
paths:
  /:
    POST:
      summary: Updateretrainingscheduler
      description: 'Updates a retraining scheduler. '
      operationId: amazonWebServicesUpdateRetrainingScheduler
tags: []
