openapi: 3.1.0
info:
  title: lookoutmetrics
  description: >-
    <p>This is the <i>Amazon Lookout for Metrics API Reference</i>. For an
    introduction to the service with tutorials for getting started, visit <a
    href="https://docs.aws.amazon.com/lookoutmetrics/latest/dev">Amazon Lookout
    for Metrics Developer Guide</a>.</p>
paths:
  /ActivateAnomalyDetector:
    POST:
      summary: Activateanomalydetector
      description: Activates an anomaly detector.
      operationId: amazonWebServicesActivateAnomalyDetector
  /BackTestAnomalyDetector:
    POST:
      summary: Backtestanomalydetector
      description: Runs a backtest for anomaly detection for the specified resource.
      operationId: amazonWebServicesBackTestAnomalyDetector
  /CreateAlert:
    POST:
      summary: Createalert
      description: Creates an alert for an anomaly detector.
      operationId: amazonWebServicesCreateAlert
  /CreateAnomalyDetector:
    POST:
      summary: Createanomalydetector
      description: Creates an anomaly detector.
      operationId: amazonWebServicesCreateAnomalyDetector
  /CreateMetricSet:
    POST:
      summary: Createmetricset
      description: Creates a dataset.
      operationId: amazonWebServicesCreateMetricSet
  /DeactivateAnomalyDetector:
    POST:
      summary: Deactivateanomalydetector
      description: Deactivates an anomaly detector.
      operationId: amazonWebServicesDeactivateAnomalyDetector
  /DeleteAlert:
    POST:
      summary: Deletealert
      description: Deletes an alert.
      operationId: amazonWebServicesDeleteAlert
  /DeleteAnomalyDetector:
    POST:
      summary: Deleteanomalydetector
      description: >-
        Deletes a detector. Deleting an anomaly detector will delete all of its
        corresponding resources including any configured datasets and alerts.
      operationId: amazonWebServicesDeleteAnomalyDetector
  /DescribeAlert:
    POST:
      summary: Describealert
      description: >-
        Describes an alert. Amazon Lookout for Metrics API actions are
        eventually consistent. If you do a read operation on a resource
        immediately after creating or modifying it, use retries to allow time
        for the write operation to complete.
      operationId: amazonWebServicesDescribeAlert
  /DescribeAnomalyDetectionExecutions:
    POST:
      summary: Describeanomalydetectionexecutions
      description: >-
        Returns information about the status of the specified anomaly detection
        jobs.
      operationId: amazonWebServicesDescribeAnomalyDetectionExecutions
  /DescribeAnomalyDetector:
    POST:
      summary: Describeanomalydetector
      description: >-
        Describes a detector. Amazon Lookout for Metrics API actions are
        eventually consistent. If you do a read operation on a resource
        immediately after creating or modifying it, use retries to allow time
        for the write operation to complete.
      operationId: amazonWebServicesDescribeAnomalyDetector
  /DescribeMetricSet:
    POST:
      summary: Describemetricset
      description: >-
        Describes a dataset. Amazon Lookout for Metrics API actions are
        eventually consistent. If you do a read operation on a resource
        immediately after creating or modifying it, use retries to allow time
        for the write operation to complete.
      operationId: amazonWebServicesDescribeMetricSet
  /DetectMetricSetConfig:
    POST:
      summary: Detectmetricsetconfig
      description: Detects an Amazon S3 dataset's file format, interval, and offset.
      operationId: amazonWebServicesDetectMetricSetConfig
  /GetAnomalyGroup:
    POST:
      summary: Getanomalygroup
      description: Returns details about a group of anomalous metrics.
      operationId: amazonWebServicesGetAnomalyGroup
  /GetDataQualityMetrics:
    POST:
      summary: Getdataqualitymetrics
      description: Returns details about the requested data quality metrics.
      operationId: amazonWebServicesGetDataQualityMetrics
  /GetFeedback:
    POST:
      summary: Getfeedback
      description: Get feedback for an anomaly group.
      operationId: amazonWebServicesGetFeedback
  /GetSampleData:
    POST:
      summary: Getsampledata
      description: Returns a selection of sample records from an Amazon S3 datasource.
      operationId: amazonWebServicesGetSampleData
  /ListAlerts:
    POST:
      summary: Listalerts
      description: >-
        Lists the alerts attached to a detector. Amazon Lookout for Metrics API
        actions are eventually consistent. If you do a read operation on a
        resource immediately after creating or modifying it, use retries to
        allow time for the write operation to complete.
      operationId: amazonWebServicesListAlerts
  /ListAnomalyDetectors:
    POST:
      summary: Listanomalydetectors
      description: >-
        Lists the detectors in the current AWS Region. Amazon Lookout for
        Metrics API actions are eventually consistent. If you do a read
        operation on a resource immediately after creating or modifying it, use
        retries to allow time for the write operation to complete.
      operationId: amazonWebServicesListAnomalyDetectors
  /ListAnomalyGroupRelatedMetrics:
    POST:
      summary: Listanomalygrouprelatedmetrics
      description: >-
        Returns a list of measures that are potential causes or effects of an
        anomaly group.
      operationId: amazonWebServicesListAnomalyGroupRelatedMetrics
  /ListAnomalyGroupSummaries:
    POST:
      summary: Listanomalygroupsummaries
      description: Returns a list of anomaly groups.
      operationId: amazonWebServicesListAnomalyGroupSummaries
  /ListAnomalyGroupTimeSeries:
    POST:
      summary: Listanomalygrouptimeseries
      description: Gets a list of anomalous metrics for a measure in an anomaly group.
      operationId: amazonWebServicesListAnomalyGroupTimeSeries
  /ListMetricSets:
    POST:
      summary: Listmetricsets
      description: >-
        Lists the datasets in the current AWS Region. Amazon Lookout for Metrics
        API actions are eventually consistent. If you do a read operation on a
        resource immediately after creating or modifying it, use retries to
        allow time for the write operation to complete.
      operationId: amazonWebServicesListMetricSets
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes tags from a detector, dataset, or alert.
      operationId: amazonWebServicesUntagResource
  /PutFeedback:
    POST:
      summary: Putfeedback
      description: Add feedback for an anomalous metric.
      operationId: amazonWebServicesPutFeedback
  /UpdateAlert:
    POST:
      summary: Updatealert
      description: Make changes to an existing alert.
      operationId: amazonWebServicesUpdateAlert
  /UpdateAnomalyDetector:
    POST:
      summary: Updateanomalydetector
      description: >-
        Updates a detector. After activation, you can only change a detector's
        ingestion delay and description.
      operationId: amazonWebServicesUpdateAnomalyDetector
  /UpdateMetricSet:
    POST:
      summary: Updatemetricset
      description: Updates a dataset.
      operationId: amazonWebServicesUpdateMetricSet
tags: []
