openapi: 3.1.0
info:
  title: machinelearning
  description: Definition of the public APIs exposed by Amazon Machine Learning
paths:
  /:
    POST:
      summary: Updatemlmodel
      description: >-
        Updates the MLModelName and the ScoreThreshold of an MLModel. You can
        use the GetMLModel operation to view the contents of the updated data
        element.
      operationId: amazonWebServicesUpdateMLModel
tags: []
