openapi: 3.1.0
info:
  title: macie2
  description: >-
    <p>Amazon Macie is a fully managed data security and data privacy service
    that uses machine learning and pattern matching to help you discover and
    protect your sensitive data in AWS. Macie automates the discovery of
    sensitive data, such as PII and intellectual property, to provide you with
    insight into the data that your organization stores in AWS. Macie also
    provides an inventory of your Amazon S3 buckets, which it continually
    monitors for you. If Macie detects sensitive data or potential data access
    issues, it generates detailed findings for you to review and act upon as
    necessary.</p>
paths:
  /invitations/accept:
    POST:
      summary: Acceptinvitation
      description: >-
        Accepts an Amazon Macie membership invitation that was received from a
        specific account.
      operationId: amazonWebServicesAcceptInvitation
  /custom-data-identifiers/get:
    POST:
      summary: Batchgetcustomdataidentifiers
      description: Retrieves information about one or more custom data identifiers.
      operationId: amazonWebServicesBatchGetCustomDataIdentifiers
  /allow-lists:
    GET:
      summary: Listallowlists
      description: >-
        Retrieves a subset of information about all the allow lists for an
        account.
      operationId: amazonWebServicesListAllowLists
  /jobs:
    POST:
      summary: Createclassificationjob
      description: Creates and defines the settings for a classification job.
      operationId: amazonWebServicesCreateClassificationJob
  /custom-data-identifiers:
    POST:
      summary: Createcustomdataidentifier
      description: >-
        Creates and defines the criteria and other settings for a custom data
        identifier.
      operationId: amazonWebServicesCreateCustomDataIdentifier
  /findingsfilters:
    GET:
      summary: Listfindingsfilters
      description: >-
        Retrieves a subset of information about all the findings filters for an
        account.
      operationId: amazonWebServicesListFindingsFilters
  /invitations:
    GET:
      summary: Listinvitations
      description: >-
        Retrieves information about the Amazon Macie membership invitations that
        were received by an account.
      operationId: amazonWebServicesListInvitations
  /members:
    GET:
      summary: Listmembers
      description: >-
        Retrieves information about the accounts that are associated with an
        Amazon Macie administrator account.
      operationId: amazonWebServicesListMembers
  /findings/sample:
    POST:
      summary: Createsamplefindings
      description: Creates sample findings.
      operationId: amazonWebServicesCreateSampleFindings
  /invitations/decline:
    POST:
      summary: Declineinvitations
      description: >-
        Declines Amazon Macie membership invitations that were received from
        specific accounts.
      operationId: amazonWebServicesDeclineInvitations
  /allow-lists/{id}:
    PUT:
      summary: Updateallowlist
      description: Updates the settings for an allow list.
      operationId: amazonWebServicesUpdateAllowList
  /custom-data-identifiers/{id}:
    GET:
      summary: Getcustomdataidentifier
      description: Retrieves the criteria and other settings for a custom data identifier.
      operationId: amazonWebServicesGetCustomDataIdentifier
  /findingsfilters/{id}:
    PATCH:
      summary: Updatefindingsfilter
      description: Updates the criteria and other settings for a findings filter.
      operationId: amazonWebServicesUpdateFindingsFilter
  /invitations/delete:
    POST:
      summary: Deleteinvitations
      description: >-
        Deletes Amazon Macie membership invitations that were received from
        specific accounts.
      operationId: amazonWebServicesDeleteInvitations
  /members/{id}:
    GET:
      summary: Getmember
      description: >-
        Retrieves information about an account that's associated with an Amazon
        Macie administrator account.
      operationId: amazonWebServicesGetMember
  /datasources/s3:
    POST:
      summary: Describebuckets
      description: >-
        Retrieves (queries) statistical data and other information about one or
        more S3 buckets that Amazon Macie monitors and analyzes for an account.
      operationId: amazonWebServicesDescribeBuckets
  /jobs/{jobId}:
    PATCH:
      summary: Updateclassificationjob
      description: Changes the status of a classification job.
      operationId: amazonWebServicesUpdateClassificationJob
  /admin/configuration:
    PATCH:
      summary: Updateorganizationconfiguration
      description: >-
        Updates the Amazon Macie configuration settings for an organization in
        Organizations.
      operationId: amazonWebServicesUpdateOrganizationConfiguration
  /macie:
    PATCH:
      summary: Updatemaciesession
      description: >-
        Suspends or re-enables Amazon Macie, or updates the configuration
        settings for a Macie account.
      operationId: amazonWebServicesUpdateMacieSession
  /admin:
    GET:
      summary: Listorganizationadminaccounts
      description: >-
        Retrieves information about the delegated Amazon Macie administrator
        account for an organization in Organizations.
      operationId: amazonWebServicesListOrganizationAdminAccounts
  /administrator/disassociate:
    POST:
      summary: Disassociatefromadministratoraccount
      description: >-
        Disassociates a member account from its Amazon Macie administrator
        account.
      operationId: amazonWebServicesDisassociateFromAdministratorAccount
  /master/disassociate:
    POST:
      summary: Disassociatefrommasteraccount
      description: >-
        (Deprecated) Disassociates a member account from its Amazon Macie
        administrator account. This operation has been replaced by the
        DisassociateFromAdministratorAccount operation.
      operationId: amazonWebServicesDisassociateFromMasterAccount
  /members/disassociate/{id}:
    POST:
      summary: Disassociatemember
      description: >-
        Disassociates an Amazon Macie administrator account from a member
        account.
      operationId: amazonWebServicesDisassociateMember
  /administrator:
    GET:
      summary: Getadministratoraccount
      description: >-
        Retrieves information about the Amazon Macie administrator account for
        an account.
      operationId: amazonWebServicesGetAdministratorAccount
  /automated-discovery/configuration:
    PUT:
      summary: Updateautomateddiscoveryconfiguration
      description: Enables or disables automated sensitive data discovery for an account.
      operationId: amazonWebServicesUpdateAutomatedDiscoveryConfiguration
  /datasources/s3/statistics:
    POST:
      summary: Getbucketstatistics
      description: >-
        Retrieves (queries) aggregated statistical data about all the S3 buckets
        that Amazon Macie monitors and analyzes for an account.
      operationId: amazonWebServicesGetBucketStatistics
  /classification-export-configuration:
    PUT:
      summary: Putclassificationexportconfiguration
      description: >-
        Creates or updates the configuration settings for storing data
        classification results.
      operationId: amazonWebServicesPutClassificationExportConfiguration
  /classification-scopes/{id}:
    PATCH:
      summary: Updateclassificationscope
      description: Updates the classification scope settings for an account.
      operationId: amazonWebServicesUpdateClassificationScope
  /findings/statistics:
    POST:
      summary: Getfindingstatistics
      description: Retrieves (queries) aggregated statistical data about findings.
      operationId: amazonWebServicesGetFindingStatistics
  /findings/describe:
    POST:
      summary: Getfindings
      description: Retrieves the details of one or more findings.
      operationId: amazonWebServicesGetFindings
  /findings-publication-configuration:
    PUT:
      summary: Putfindingspublicationconfiguration
      description: >-
        Updates the configuration settings for publishing findings to Security
        Hub.
      operationId: amazonWebServicesPutFindingsPublicationConfiguration
  /invitations/count:
    GET:
      summary: Getinvitationscount
      description: >-
        Retrieves the count of Amazon Macie membership invitations that were
        received by an account.
      operationId: amazonWebServicesGetInvitationsCount
  /master:
    GET:
      summary: Getmasteraccount
      description: >-
        (Deprecated) Retrieves information about the Amazon Macie administrator
        account for an account. This operation has been replaced by the
        GetAdministratorAccount operation.
      operationId: amazonWebServicesGetMasterAccount
  /resource-profiles:
    PATCH:
      summary: Updateresourceprofile
      description: Updates the sensitivity score for an S3 bucket.
      operationId: amazonWebServicesUpdateResourceProfile
  /reveal-configuration:
    PUT:
      summary: Updaterevealconfiguration
      description: >-
        Updates the status and configuration settings for retrieving occurrences
        of sensitive data reported by findings.
      operationId: amazonWebServicesUpdateRevealConfiguration
  /findings/{findingId}/reveal:
    GET:
      summary: Getsensitivedataoccurrences
      description: Retrieves occurrences of sensitive data reported by a finding.
      operationId: amazonWebServicesGetSensitiveDataOccurrences
  /findings/{findingId}/reveal/availability:
    GET:
      summary: Getsensitivedataoccurrencesavailability
      description: >-
        Checks whether occurrences of sensitive data can be retrieved for a
        finding.
      operationId: amazonWebServicesGetSensitiveDataOccurrencesAvailability
  /templates/sensitivity-inspections/{id}:
    PUT:
      summary: Updatesensitivityinspectiontemplate
      description: ' Updates the settings for the sensitivity inspection template for an account.'
      operationId: amazonWebServicesUpdateSensitivityInspectionTemplate
  /usage/statistics:
    POST:
      summary: Getusagestatistics
      description: >-
        Retrieves (queries) quotas and aggregated usage data for one or more
        accounts.
      operationId: amazonWebServicesGetUsageStatistics
  /usage:
    GET:
      summary: Getusagetotals
      description: Retrieves (queries) aggregated usage data for an account.
      operationId: amazonWebServicesGetUsageTotals
  /jobs/list:
    POST:
      summary: Listclassificationjobs
      description: Retrieves a subset of information about one or more classification jobs.
      operationId: amazonWebServicesListClassificationJobs
  /classification-scopes:
    GET:
      summary: Listclassificationscopes
      description: >-
        Retrieves a subset of information about the classification scope for an
        account.
      operationId: amazonWebServicesListClassificationScopes
  /custom-data-identifiers/list:
    POST:
      summary: Listcustomdataidentifiers
      description: >-
        Retrieves a subset of information about all the custom data identifiers
        for an account.
      operationId: amazonWebServicesListCustomDataIdentifiers
  /findings:
    POST:
      summary: Listfindings
      description: Retrieves a subset of information about one or more findings.
      operationId: amazonWebServicesListFindings
  /managed-data-identifiers/list:
    POST:
      summary: Listmanageddataidentifiers
      description: >-
        Retrieves information about all the managed data identifiers that Amazon
        Macie currently provides.
      operationId: amazonWebServicesListManagedDataIdentifiers
  /resource-profiles/artifacts:
    GET:
      summary: Listresourceprofileartifacts
      description: >-
        Retrieves information about objects that were selected from an S3 bucket
        for automated sensitive data discovery.
      operationId: amazonWebServicesListResourceProfileArtifacts
  /resource-profiles/detections:
    PATCH:
      summary: Updateresourceprofiledetections
      description: Updates the sensitivity scoring settings for an S3 bucket.
      operationId: amazonWebServicesUpdateResourceProfileDetections
  /templates/sensitivity-inspections:
    GET:
      summary: Listsensitivityinspectiontemplates
      description: ' Retrieves a subset of information about the sensitivity inspection template for an account.'
      operationId: amazonWebServicesListSensitivityInspectionTemplates
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: >-
        Removes one or more tags (keys and values) from an Amazon Macie
        resource.
      operationId: amazonWebServicesUntagResource
  /datasources/search-resources:
    POST:
      summary: Searchresources
      description: >-
        Retrieves (queries) statistical data and other information about Amazon
        Web Services resources that Amazon Macie monitors and analyzes.
      operationId: amazonWebServicesSearchResources
  /custom-data-identifiers/test:
    POST:
      summary: Testcustomdataidentifier
      description: Tests a custom data identifier.
      operationId: amazonWebServicesTestCustomDataIdentifier
  /macie/members/{id}:
    PATCH:
      summary: Updatemembersession
      description: >-
        Enables an Amazon Macie administrator to suspend or re-enable Macie for
        a member account.
      operationId: amazonWebServicesUpdateMemberSession
tags: []
