openapi: 3.1.0
info:
  title: managedblockchain
  description: >-
    <p/> <p>Amazon Managed Blockchain is a fully managed service for creating
    and managing blockchain networks using open-source frameworks. Blockchain
    allows you to build applications where multiple parties can securely and
    transparently run transactions and share data without the need for a
    trusted, central authority.</p> <p>Managed Blockchain supports the
    Hyperledger Fabric and Ethereum open-source frameworks. Because of
    fundamental differences between the frameworks, some API actions or data
    types may only apply in the context of one framework and not the other. For
    example, actions related to Hyperledger Fabric network members such as
    <code>CreateMember</code> and <code>DeleteMember</code> don't apply to
    Ethereum.</p> <p>The description for each action indicates the framework or
    frameworks to which it applies. Data types and properties that apply only in
    the context of a particular framework are similarly indicated.</p>
paths:
  /accessors:
    GET:
      summary: Listaccessors
      description: >-
        Returns a list of the accessors and their properties. Accessor objects
        are containers that have the information required for token based access
        to your Ethereum nodes.
      operationId: amazonWebServicesListAccessors
  /networks/{networkId}/members:
    GET:
      summary: Listmembers
      description: >-
        Returns a list of the members in a network and properties of their
        configurations. Applies only to Hyperledger Fabric.
      operationId: amazonWebServicesListMembers
  /networks:
    GET:
      summary: Listnetworks
      description: >-
        Returns information about the networks in which the current Amazon Web
        Services account participates. Applies to Hyperledger Fabric and
        Ethereum.
      operationId: amazonWebServicesListNetworks
  /networks/{networkId}/nodes:
    GET:
      summary: Listnodes
      description: >-
        Returns information about the nodes within a network. Applies to
        Hyperledger Fabric and Ethereum.
      operationId: amazonWebServicesListNodes
  /networks/{networkId}/proposals:
    GET:
      summary: Listproposals
      description: >-
        Returns a list of proposals for the network. Applies only to Hyperledger
        Fabric.
      operationId: amazonWebServicesListProposals
  /accessors/{AccessorId}:
    GET:
      summary: Getaccessor
      description: >-
        Returns detailed information about an accessor. An accessor object is a
        container that has the information required for token based access to
        your Ethereum nodes.
      operationId: amazonWebServicesGetAccessor
  /networks/{networkId}/members/{memberId}:
    PATCH:
      summary: Updatemember
      description: >-
        Updates a member configuration with new parameters. Applies only to
        Hyperledger Fabric.
      operationId: amazonWebServicesUpdateMember
  /networks/{networkId}/nodes/{nodeId}:
    PATCH:
      summary: Updatenode
      description: >-
        Updates a node configuration with new parameters. Applies only to
        Hyperledger Fabric.
      operationId: amazonWebServicesUpdateNode
  /networks/{networkId}:
    GET:
      summary: Getnetwork
      description: >-
        Returns detailed information about a network. Applies to Hyperledger
        Fabric and Ethereum.
      operationId: amazonWebServicesGetNetwork
  /networks/{networkId}/proposals/{proposalId}:
    GET:
      summary: Getproposal
      description: >-
        Returns detailed information about a proposal. Applies only to
        Hyperledger Fabric.
      operationId: amazonWebServicesGetProposal
  /invitations:
    GET:
      summary: Listinvitations
      description: >-
        Returns a list of all invitations for the current Amazon Web Services
        account. Applies only to Hyperledger Fabric.
      operationId: amazonWebServicesListInvitations
  /networks/{networkId}/proposals/{proposalId}/votes:
    POST:
      summary: Voteonproposal
      description: >-
        Casts a vote for a specified ProposalId on behalf of a member. The
        member to vote as, specified by VoterMemberId, must be in the same
        Amazon Web Services account as the principal that calls the action.
        Applies only to Hyperledger Fabric.
      operationId: amazonWebServicesVoteOnProposal
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: >-
        Removes the specified tags from the Amazon Managed Blockchain resource.
        For more information about tags, see Tagging Resources in the Amazon
        Managed Blockchain Ethereum Developer Guide, or Tagging Resources in the
        Amazon Managed Blockchain Hyperledger Fabric Developer Guide.
      operationId: amazonWebServicesUntagResource
  /invitations/{invitationId}:
    DELETE:
      summary: Rejectinvitation
      description: >-
        Rejects an invitation to join a network. This action can be called by a
        principal in an Amazon Web Services account that has received an
        invitation to create a member and join a network. Applies only to
        Hyperledger Fabric.
      operationId: amazonWebServicesRejectInvitation
tags: []
