openapi: 3.1.0
info:
  title: marketplace-agreement
  description: >-
    <p>AWS Marketplace is a curated digital catalog that customers can use to
    find, buy, deploy, and manage third-party software, data, and services to
    build solutions and run their businesses. The AWS Marketplace Agreement
    Service provides an API interface that helps AWS Marketplace sellers manage
    their product-related agreements, including listing, searching, and
    filtering agreements.</p> <p>To manage agreements in AWS Marketplace, you
    must ensure that your AWS Identity and Access Management (IAM) policies and
    roles are set up. The user must have the required policies/permissions that
    allow them to carry out the actions in AWS:</p> <ul> <li> <p>
    <code>DescribeAgreement</code> – Grants permission to users to obtain
    detailed meta data about any of their agreements.</p> </li> <li> <p>
    <code>GetAgreementTerms</code> – Grants permission to users to obtain
    details about the terms of an agreement.</p> </li> <li> <p>
    <code>SearchAgreements</code> – Grants permission to users to search through
    all their agreements.</p> </li> </ul>
paths:
  /:
    POST:
      summary: Searchagreements
      description: >-
        Searches across all agreements that a proposer or an acceptor has in AWS
        Marketplace. The search returns a list of agreements with basic
        agreement information. The following filter combinations are
        supported:    PartyType as Proposer + AgreementType +
        ResourceIdentifier     PartyType as Proposer + AgreementType +
        OfferId     PartyType as Proposer + AgreementType +
        AcceptorAccountId     PartyType as Proposer + AgreementType + Status    
        PartyType as Proposer + AgreementType + ResourceIdentifier + Status    
        PartyType as Proposer + AgreementType + OfferId + Status     PartyType
        as Proposer + AgreementType + AcceptorAccountId + Status     PartyType
        as Proposer + AgreementType + ResourceType + Status     PartyType as
        Proposer + AgreementType + AcceptorAccountId + ResourceType + Status    
        PartyType as Proposer + AgreementType + AcceptorAccountId + OfferId    
        PartyType as Proposer + AgreementType + AcceptorAccountId + OfferId +
        Status     PartyType as Proposer + AgreementType + AcceptorAccountId +
        ResourceIdentifier     PartyType as Proposer + AgreementType +
        AcceptorAccountId + ResourceIdentifier + Status     PartyType as
        Proposer + AgreementType + AcceptorAccountId + ResourceType   
      operationId: amazonWebServicesSearchAgreements
tags: []
