openapi: 3.1.0
info:
  title: marketplace-catalog
  description: >-
    <p>Catalog API actions allow you to manage your entities through list,
    describe, and update capabilities. An entity can be a product or an offer on
    AWS Marketplace. </p> <p>You can automate your entity update process by
    integrating the AWS Marketplace Catalog API with your AWS Marketplace
    product build or deployment pipelines. You can also create your own
    applications on top of the Catalog API to manage your products on AWS
    Marketplace.</p>
paths:
  /BatchDescribeEntities:
    POST:
      summary: Batchdescribeentities
      description: >-
        Returns metadata and content for multiple entities. This is the Batch
        version of the DescribeEntity API and uses the same IAM permission
        action as DescribeEntity API.
      operationId: amazonWebServicesBatchDescribeEntities
  /CancelChangeSet:
    PATCH:
      summary: Cancelchangeset
      description: >-
        Used to cancel an open change request. Must be sent before the status of
        the request changes to APPLYING, the final stage of completing your
        change request. You can describe a change during the 60-day request
        history retention period for API calls.
      operationId: amazonWebServicesCancelChangeSet
  /DeleteResourcePolicy:
    DELETE:
      summary: Deleteresourcepolicy
      description: >-
        Deletes a resource-based policy on an entity that is identified by its
        resource ARN.
      operationId: amazonWebServicesDeleteResourcePolicy
  /DescribeChangeSet:
    GET:
      summary: Describechangeset
      description: Provides information about a given change set.
      operationId: amazonWebServicesDescribeChangeSet
  /DescribeEntity:
    GET:
      summary: Describeentity
      description: Returns the metadata and content of the entity.
      operationId: amazonWebServicesDescribeEntity
  /GetResourcePolicy:
    GET:
      summary: Getresourcepolicy
      description: >-
        Gets a resource-based policy of an entity that is identified by its
        resource ARN.
      operationId: amazonWebServicesGetResourcePolicy
  /ListChangeSets:
    POST:
      summary: Listchangesets
      description: >-
        Returns the list of change sets owned by the account being used to make
        the call. You can filter this list by providing any combination of
        entityId, ChangeSetName, and status. If you provide more than one
        filter, the API operation applies a logical AND between the filters. You
        can describe a change during the 60-day request history retention period
        for API calls.
      operationId: amazonWebServicesListChangeSets
  /ListEntities:
    POST:
      summary: Listentities
      description: Provides the list of entities of a given type.
      operationId: amazonWebServicesListEntities
  /ListTagsForResource:
    POST:
      summary: Listtagsforresource
      description: >-
        Lists all tags that have been added to a resource (either an entity or
        change set).
      operationId: amazonWebServicesListTagsForResource
  /PutResourcePolicy:
    POST:
      summary: Putresourcepolicy
      description: >-
        Attaches a resource-based policy to an entity. Examples of an entity
        include: AmiProduct and ContainerProduct.
      operationId: amazonWebServicesPutResourcePolicy
  /StartChangeSet:
    POST:
      summary: Startchangeset
      description: >-
        Allows you to request changes for your entities. Within a single
        ChangeSet, you can't start the same change type against the same entity
        multiple times. Additionally, when a ChangeSet is running, all the
        entities targeted by the different changes are locked until the change
        set has completed (either succeeded, cancelled, or failed). If you try
        to start a change set containing a change against an entity that is
        already locked, you will receive a ResourceInUseException error. For
        example, you can't start the ChangeSet described in the example later in
        this topic because it contains two changes to run the same change type
        (AddRevisions) against the same entity (entity-id@1). For more
        information about working with change sets, see  Working with change
        sets. For information about change types for single-AMI products, see
        Working with single-AMI products. Also, for more information about
        change types available for container-based products, see Working with
        container products.
      operationId: amazonWebServicesStartChangeSet
  /TagResource:
    POST:
      summary: Tagresource
      description: Tags a resource (either an entity or change set).
      operationId: amazonWebServicesTagResource
  /UntagResource:
    POST:
      summary: Untagresource
      description: >-
        Removes a tag or list of tags from a resource (either an entity or
        change set).
      operationId: amazonWebServicesUntagResource
tags: []
