openapi: 3.1.0
info:
  title: mediapackage-vod
  description: AWS Elemental MediaPackage VOD
paths:
  /packaging_groups/{id}/configure_logs:
    PUT:
      summary: Configurelogs
      description: Changes the packaging group's properities to configure log subscription
      operationId: amazonWebServicesConfigureLogs
  /assets:
    GET:
      summary: Listassets
      description: Returns a collection of MediaPackage VOD Asset resources.
      operationId: amazonWebServicesListAssets
  /packaging_configurations:
    GET:
      summary: Listpackagingconfigurations
      description: >-
        Returns a collection of MediaPackage VOD PackagingConfiguration
        resources.
      operationId: amazonWebServicesListPackagingConfigurations
  /packaging_groups:
    GET:
      summary: Listpackaginggroups
      description: Returns a collection of MediaPackage VOD PackagingGroup resources.
      operationId: amazonWebServicesListPackagingGroups
  /assets/{id}:
    GET:
      summary: Describeasset
      description: Returns a description of a MediaPackage VOD Asset resource.
      operationId: amazonWebServicesDescribeAsset
  /packaging_configurations/{id}:
    GET:
      summary: Describepackagingconfiguration
      description: >-
        Returns a description of a MediaPackage VOD PackagingConfiguration
        resource.
      operationId: amazonWebServicesDescribePackagingConfiguration
  /packaging_groups/{id}:
    PUT:
      summary: Updatepackaginggroup
      description: >-
        Updates a specific packaging group. You can't change the id attribute or
        any other system-generated attributes.
      operationId: amazonWebServicesUpdatePackagingGroup
  /tags/{resource-arn}:
    DELETE:
      summary: Untagresource
      description: >-
        Removes tags from the specified resource. You can specify one or more
        tags to remove.
      operationId: amazonWebServicesUntagResource
tags: []
