openapi: 3.1.0
info:
  title: mediastore-data
  description: >-
    <p>An AWS Elemental MediaStore asset is an object, similar to an object in
    the Amazon S3 service. Objects are the fundamental entities that are stored
    in AWS Elemental MediaStore.</p>
paths:
  /{Path+}:
    PUT:
      summary: Putobject
      description: >-
        Uploads an object to the specified path. Object sizes are limited to 25
        MB for standard upload availability and 10 MB for streaming upload
        availability.
      operationId: amazonWebServicesPutObject
  /:
    GET:
      summary: Listitems
      description: >-
        Provides a list of metadata entries about folders and objects in the
        specified folder.
      operationId: amazonWebServicesListItems
tags: []
