openapi: 3.1.0
info:
  title: medical-imaging
  description: >-
    <p>This is the <i>AWS HealthImaging API Reference</i>. AWS HealthImaging is
    a HIPAA-eligible service that helps health care providers and their medical
    imaging ISV partners store, transform, and apply machine learning to medical
    images. For an introduction to the service, see the <a
    href="https://docs.aws.amazon.com/healthimaging/latest/devguide/what-is.html">
    <i>AWS HealthImaging Developer Guide</i> </a>.</p> <note> <p>We recommend
    using one of the AWS Software Development Kits (SDKs) for your programming
    language, as they take care of request authentication, serialization, and
    connection management. For more information, see <a
    href="http://aws.amazon.com/developer/tools">Tools to build on AWS</a>.</p>
    <p>For information about using HealthImaging API actions in one of the
    language-specific AWS SDKs, refer to the <i>See Also</i> link at the end of
    each section that describes an API action or data type.</p> </note> <p>The
    following sections list AWS HealthImaging API actions categorized according
    to functionality. Links are provided to actions within this Reference, along
    with links back to corresponding sections in the <i>AWS HealthImaging
    Developer Guide</i> where you can view console procedures and CLI/SDK code
    examples.</p> <p class="title"> <b>Data store actions</b> </p> <ul> <li> <p>
    <a
    href="https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_CreateDatastore.html">CreateDatastore</a>
    – See <a
    href="https://docs.aws.amazon.com/healthimaging/latest/devguide/create-data-store.html">Creating
    a data store</a>.</p> </li> <li> <p> <a
    href="https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_GetDatastore.html">GetDatastore</a>
    – See <a
    href="https://docs.aws.amazon.com/healthimaging/latest/devguide/get-data-store.html">Getting
    data store properties</a>.</p> </li> <li> <p> <a
    href="https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_ListDatastores.html">ListDatastores</a>
    – See <a
    href="https://docs.aws.amazon.com/healthimaging/latest/devguide/list-data-stores.html">Listing
    data stores</a>.</p> </li> <li> <p> <a
    href="https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_DeleteDatastore.html">DeleteDatastore</a>
    – See <a
    href="https://docs.aws.amazon.com/healthimaging/latest/devguide/delete-data-store.html">Deleting
    a data store</a>.</p> </li> </ul> <p class="title"> <b>Import job
    actions</b> </p> <ul> <li> <p> <a
    href="https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_StartDICOMImportJob.html">StartDICOMImportJob</a>
    – See <a
    href="https://docs.aws.amazon.com/healthimaging/latest/devguide/start-dicom-import-job.html">Starting
    an import job</a>.</p> </li> <li> <p> <a
    href="https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_GetDICOMImportJob.html">GetDICOMImportJob</a>
    – See <a
    href="https://docs.aws.amazon.com/healthimaging/latest/devguide/get-dicom-import-job.html">Getting
    import job properties</a>.</p> </li> <li> <p> <a
    href="https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_ListDICOMImportJobs.html">ListDICOMImportJobs</a>
    – See <a
    href="https://docs.aws.amazon.com/healthimaging/latest/devguide/list-dicom-import-jobs.html">Listing
    import jobs</a>.</p> </li> </ul> <p class="title"> <b>Image set access
    actions</b> </p> <ul> <li> <p> <a
    href="https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_SearchImageSets.html">SearchImageSets</a>
    – See <a
    href="https://docs.aws.amazon.com/healthimaging/latest/devguide/search-image-sets.html">Searching
    image sets</a>.</p> </li> <li> <p> <a
    href="https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_GetImageSet.html">GetImageSet</a>
    – See <a
    href="https://docs.aws.amazon.com/healthimaging/latest/devguide/get-image-set-properties.html">Getting
    image set properties</a>.</p> </li> <li> <p> <a
    href="https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_GetImageSetMetadata.html">GetImageSetMetadata</a>
    – See <a
    href="https://docs.aws.amazon.com/healthimaging/latest/devguide/get-image-set-metadata.html">Getting
    image set metadata</a>.</p> </li> <li> <p> <a
    href="https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_GetImageFrame.html">GetImageFrame</a>
    – See <a
    href="https://docs.aws.amazon.com/healthimaging/latest/devguide/get-image-frame.html">Getting
    image set pixel data</a>.</p> </li> </ul> <p class="title"> <b>Image set
    modification actions</b> </p> <ul> <li> <p> <a
    href="https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_ListImageSetVersions.html">ListImageSetVersions</a>
    – See <a
    href="https://docs.aws.amazon.com/healthimaging/latest/devguide/list-image-set-versions.html">Listing
    image set versions</a>.</p> </li> <li> <p> <a
    href="https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_UpdateImageSetMetadata.html">UpdateImageSetMetadata</a>
    – See <a
    href="https://docs.aws.amazon.com/healthimaging/latest/devguide/update-image-set-metadata.html">Updating
    image set metadata</a>.</p> </li> <li> <p> <a
    href="https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_CopyImageSet.html">CopyImageSet</a>
    – See <a
    href="https://docs.aws.amazon.com/healthimaging/latest/devguide/copy-image-set.html">Copying
    an image set</a>.</p> </li> <li> <p> <a
    href="https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_DeleteImageSet.html">DeleteImageSet</a>
    – See <a
    href="https://docs.aws.amazon.com/healthimaging/latest/devguide/delete-image-set.html">Deleting
    an image set</a>.</p> </li> </ul> <p class="title"> <b>Tagging actions</b>
    </p> <ul> <li> <p> <a
    href="https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_TagResource.html">TagResource</a>
    – See <a
    href="https://docs.aws.amazon.com/healthimaging/latest/devguide/tag-list-untag-data-store.html">Tagging
    a data store</a> and <a
    href="https://docs.aws.amazon.com/healthimaging/latest/devguide/tag-list-untag-image-set.html">Tagging
    an image set</a>.</p> </li> <li> <p> <a
    href="https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_ListTagsForResource.html">ListTagsForResource</a>
    – See <a
    href="https://docs.aws.amazon.com/healthimaging/latest/devguide/tag-list-untag-data-store.html">Tagging
    a data store</a> and <a
    href="https://docs.aws.amazon.com/healthimaging/latest/devguide/tag-list-untag-image-set.html">Tagging
    an image set</a>.</p> </li> <li> <p> <a
    href="https://docs.aws.amazon.com/healthimaging/latest/APIReference/API_UntagResource.html">UntagResource</a>
    – See <a
    href="https://docs.aws.amazon.com/healthimaging/latest/devguide/tag-list-untag-data-store.html">Tagging
    a data store</a> and <a
    href="https://docs.aws.amazon.com/healthimaging/latest/devguide/tag-list-untag-image-set.html">Tagging
    an image set</a>.</p> </li> </ul>
paths:
  /datastore/{datastoreId}/imageSet/{sourceImageSetId}/copyImageSet:
    POST:
      summary: Copyimageset
      description: Copy an image set.
      operationId: amazonWebServicesCopyImageSet
  /datastore:
    GET:
      summary: Listdatastores
      description: List data stores.
      operationId: amazonWebServicesListDatastores
  /datastore/{datastoreId}:
    GET:
      summary: Getdatastore
      description: Get data store properties.
      operationId: amazonWebServicesGetDatastore
  /datastore/{datastoreId}/imageSet/{imageSetId}/deleteImageSet:
    POST:
      summary: Deleteimageset
      description: Delete an image set.
      operationId: amazonWebServicesDeleteImageSet
  /getDICOMImportJob/datastore/{datastoreId}/job/{jobId}:
    GET:
      summary: Getdicomimportjob
      description: >-
        Get the import job properties to learn more about the job or job
        progress.
      operationId: amazonWebServicesGetDICOMImportJob
  /datastore/{datastoreId}/imageSet/{imageSetId}/getImageFrame:
    POST:
      summary: Getimageframe
      description: Get an image frame (pixel data) for an image set.
      operationId: amazonWebServicesGetImageFrame
  /datastore/{datastoreId}/imageSet/{imageSetId}/getImageSet:
    POST:
      summary: Getimageset
      description: Get image set properties.
      operationId: amazonWebServicesGetImageSet
  /datastore/{datastoreId}/imageSet/{imageSetId}/getImageSetMetadata:
    POST:
      summary: Getimagesetmetadata
      description: Get metadata attributes for an image set.
      operationId: amazonWebServicesGetImageSetMetadata
  /listDICOMImportJobs/datastore/{datastoreId}:
    GET:
      summary: Listdicomimportjobs
      description: List import jobs created for a specific data store.
      operationId: amazonWebServicesListDICOMImportJobs
  /datastore/{datastoreId}/imageSet/{imageSetId}/listImageSetVersions:
    POST:
      summary: Listimagesetversions
      description: List image set versions.
      operationId: amazonWebServicesListImageSetVersions
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes tags from a medical imaging resource.
      operationId: amazonWebServicesUntagResource
  /datastore/{datastoreId}/searchImageSets:
    POST:
      summary: Searchimagesets
      description: >-
        Search image sets based on defined input attributes.   SearchImageSets
        accepts a single search query parameter and returns a paginated response
        of all image sets that have the matching criteria. All range queries
        must be input as (lowerBound, upperBound).  SearchImageSets uses the
        updatedAt field for sorting in decreasing order from latest to oldest. 
      operationId: amazonWebServicesSearchImageSets
  /startDICOMImportJob/datastore/{datastoreId}:
    POST:
      summary: Startdicomimportjob
      description: >-
        Start importing bulk data into an ACTIVE data store. The import job
        imports DICOM P10 files found in the S3 prefix specified by the
        inputS3Uri parameter. The import job stores processing results in the
        file specified by the outputS3Uri parameter.
      operationId: amazonWebServicesStartDICOMImportJob
  /datastore/{datastoreId}/imageSet/{imageSetId}/updateImageSetMetadata:
    POST:
      summary: Updateimagesetmetadata
      description: Update image set metadata attributes.
      operationId: amazonWebServicesUpdateImageSetMetadata
tags: []
