openapi: 3.1.0
info:
  title: mediatailor
  description: >-
    <p>Use the AWS Elemental MediaTailor SDKs and CLI to configure scalable ad
    insertion and linear channels. With MediaTailor, you can assemble existing
    content into a linear stream and serve targeted ads to viewers while
    maintaining broadcast quality in over-the-top (OTT) video applications. For
    information about using the service, including detailed information about
    the settings covered in this guide, see the <a
    href="https://docs.aws.amazon.com/mediatailor/latest/ug/">AWS Elemental
    MediaTailor User Guide</a>.</p> <p>Through the SDKs and the CLI you manage
    AWS Elemental MediaTailor configurations and channels the same as you do
    through the console. For example, you specify ad insertion behavior and
    mapping information for the origin server and the ad decision server
    (ADS).</p>
paths:
  /configureLogs/channel:
    PUT:
      summary: Configurelogsforchannel
      description: Configures Amazon CloudWatch log settings for a channel.
      operationId: amazonWebServicesConfigureLogsForChannel
  /configureLogs/playbackConfiguration:
    PUT:
      summary: Configurelogsforplaybackconfiguration
      description: Amazon CloudWatch log settings for a playback configuration.
      operationId: amazonWebServicesConfigureLogsForPlaybackConfiguration
  /channel/{ChannelName}:
    PUT:
      summary: Updatechannel
      description: >-
        Updates a channel. For information about MediaTailor channels, see
        Working with channels in the MediaTailor User Guide.
      operationId: amazonWebServicesUpdateChannel
  /sourceLocation/{SourceLocationName}/liveSource/{LiveSourceName}:
    PUT:
      summary: Updatelivesource
      description: Updates a live source's configuration.
      operationId: amazonWebServicesUpdateLiveSource
  /prefetchSchedule/{PlaybackConfigurationName}/{Name}:
    GET:
      summary: Getprefetchschedule
      description: >-
        Retrieves a prefetch schedule for a playback configuration. A prefetch
        schedule allows you to tell MediaTailor to fetch and prepare certain ads
        before an ad break happens. For more information about ad prefetching,
        see Using ad prefetching in the MediaTailor User Guide.
      operationId: amazonWebServicesGetPrefetchSchedule
  /channel/{ChannelName}/program/{ProgramName}:
    PUT:
      summary: Updateprogram
      description: Updates a program within a channel.
      operationId: amazonWebServicesUpdateProgram
  /sourceLocation/{SourceLocationName}:
    PUT:
      summary: Updatesourcelocation
      description: >-
        Updates a source location. A source location is a container for sources.
        For more information about source locations, see Working with source
        locations in the MediaTailor User Guide.
      operationId: amazonWebServicesUpdateSourceLocation
  /sourceLocation/{SourceLocationName}/vodSource/{VodSourceName}:
    PUT:
      summary: Updatevodsource
      description: Updates a VOD source's configuration.
      operationId: amazonWebServicesUpdateVodSource
  /channel/{ChannelName}/policy:
    PUT:
      summary: Putchannelpolicy
      description: >-
        Creates an IAM policy for the channel. IAM policies are used to control
        access to your channel.
      operationId: amazonWebServicesPutChannelPolicy
  /playbackConfiguration/{Name}:
    GET:
      summary: Getplaybackconfiguration
      description: >-
        Retrieves a playback configuration. For information about MediaTailor
        configurations, see Working with configurations in AWS Elemental
        MediaTailor.
      operationId: amazonWebServicesGetPlaybackConfiguration
  /channel/{ChannelName}/schedule:
    GET:
      summary: Getchannelschedule
      description: Retrieves information about your channel's schedule.
      operationId: amazonWebServicesGetChannelSchedule
  /alerts:
    GET:
      summary: Listalerts
      description: >-
        Lists the alerts that are associated with a MediaTailor channel assembly
        resource.
      operationId: amazonWebServicesListAlerts
  /channels:
    GET:
      summary: Listchannels
      description: >-
        Retrieves information about the channels that are associated with the
        current AWS account.
      operationId: amazonWebServicesListChannels
  /sourceLocation/{SourceLocationName}/liveSources:
    GET:
      summary: Listlivesources
      description: >-
        Lists the live sources contained in a source location. A source
        represents a piece of content.
      operationId: amazonWebServicesListLiveSources
  /playbackConfigurations:
    GET:
      summary: Listplaybackconfigurations
      description: >-
        Retrieves existing playback configurations. For information about
        MediaTailor configurations, see Working with Configurations in AWS
        Elemental MediaTailor.
      operationId: amazonWebServicesListPlaybackConfigurations
  /prefetchSchedule/{PlaybackConfigurationName}:
    POST:
      summary: Listprefetchschedules
      description: Lists the prefetch schedules for a playback configuration.
      operationId: amazonWebServicesListPrefetchSchedules
  /sourceLocations:
    GET:
      summary: Listsourcelocations
      description: >-
        Lists the source locations for a channel. A source location defines the
        host server URL, and contains a list of sources.
      operationId: amazonWebServicesListSourceLocations
  /tags/{ResourceArn}:
    DELETE:
      summary: Untagresource
      description: The resource to untag.
      operationId: amazonWebServicesUntagResource
  /sourceLocation/{SourceLocationName}/vodSources:
    GET:
      summary: Listvodsources
      description: >-
        Lists the VOD sources contained in a source location. A source
        represents a piece of content.
      operationId: amazonWebServicesListVodSources
  /playbackConfiguration:
    PUT:
      summary: Putplaybackconfiguration
      description: >-
        Creates a playback configuration. For information about MediaTailor
        configurations, see Working with configurations in AWS Elemental
        MediaTailor.
      operationId: amazonWebServicesPutPlaybackConfiguration
  /channel/{ChannelName}/start:
    PUT:
      summary: Startchannel
      description: >-
        Starts a channel. For information about MediaTailor channels, see
        Working with channels in the MediaTailor User Guide.
      operationId: amazonWebServicesStartChannel
  /channel/{ChannelName}/stop:
    PUT:
      summary: Stopchannel
      description: >-
        Stops a channel. For information about MediaTailor channels, see Working
        with channels in the MediaTailor User Guide.
      operationId: amazonWebServicesStopChannel
tags: []
