openapi: 3.1.0
info:
  title: medialive
  description: API for AWS Elemental MediaLive
paths:
  /prod/inputDevices/{inputDeviceId}/accept:
    POST:
      summary: Acceptinputdevicetransfer
      description: >-
        Accept an incoming input device transfer. The ownership of the device
        will transfer to your AWS account.
      operationId: amazonWebServicesAcceptInputDeviceTransfer
  /prod/batch/delete:
    POST:
      summary: Batchdelete
      description: Starts delete of resources.
      operationId: amazonWebServicesBatchDelete
  /prod/batch/start:
    POST:
      summary: Batchstart
      description: Starts existing resources
      operationId: amazonWebServicesBatchStart
  /prod/batch/stop:
    POST:
      summary: Batchstop
      description: Stops running resources
      operationId: amazonWebServicesBatchStop
  /prod/channels/{channelId}/schedule:
    GET:
      summary: Describeschedule
      description: Get a channel schedule
      operationId: amazonWebServicesDescribeSchedule
  /prod/inputDevices/{inputDeviceId}/cancel:
    POST:
      summary: Cancelinputdevicetransfer
      description: Cancel an input device transfer that you have requested.
      operationId: amazonWebServicesCancelInputDeviceTransfer
  /prod/claimDevice:
    POST:
      summary: Claimdevice
      description: >-
        Send a request to claim an AWS Elemental device that you have purchased
        from a third-party vendor. After the request succeeds, you will own the
        device.
      operationId: amazonWebServicesClaimDevice
  /prod/channels:
    GET:
      summary: Listchannels
      description: Produces list of channels that have been created
      operationId: amazonWebServicesListChannels
  /prod/inputs:
    GET:
      summary: Listinputs
      description: Produces list of inputs that have been created
      operationId: amazonWebServicesListInputs
  /prod/inputSecurityGroups:
    GET:
      summary: Listinputsecuritygroups
      description: Produces a list of Input Security Groups for an account
      operationId: amazonWebServicesListInputSecurityGroups
  /prod/multiplexes:
    GET:
      summary: Listmultiplexes
      description: Retrieve a list of the existing multiplexes.
      operationId: amazonWebServicesListMultiplexes
  /prod/multiplexes/{multiplexId}/programs:
    GET:
      summary: Listmultiplexprograms
      description: List the programs that currently exist for a specific multiplex.
      operationId: amazonWebServicesListMultiplexPrograms
  /prod/inputs/{inputId}/partners:
    POST:
      summary: Createpartnerinput
      description: Create a partner input
      operationId: amazonWebServicesCreatePartnerInput
  /prod/tags/{resource-arn}:
    GET:
      summary: Listtagsforresource
      description: Produces list of tags that have been created for a resource
      operationId: amazonWebServicesListTagsForResource
  /prod/channels/{channelId}:
    PUT:
      summary: Updatechannel
      description: Updates a channel.
      operationId: amazonWebServicesUpdateChannel
  /prod/inputs/{inputId}:
    PUT:
      summary: Updateinput
      description: Updates an input.
      operationId: amazonWebServicesUpdateInput
  /prod/inputSecurityGroups/{inputSecurityGroupId}:
    PUT:
      summary: Updateinputsecuritygroup
      description: Update an Input Security Group's Whilelists.
      operationId: amazonWebServicesUpdateInputSecurityGroup
  /prod/multiplexes/{multiplexId}:
    PUT:
      summary: Updatemultiplex
      description: Updates a multiplex.
      operationId: amazonWebServicesUpdateMultiplex
  /prod/multiplexes/{multiplexId}/programs/{programName}:
    PUT:
      summary: Updatemultiplexprogram
      description: Update a program in a multiplex.
      operationId: amazonWebServicesUpdateMultiplexProgram
  /prod/reservations/{reservationId}:
    PUT:
      summary: Updatereservation
      description: Update reservation.
      operationId: amazonWebServicesUpdateReservation
  /prod/accountConfiguration:
    PUT:
      summary: Updateaccountconfiguration
      description: Update account configuration
      operationId: amazonWebServicesUpdateAccountConfiguration
  /prod/inputDevices/{inputDeviceId}:
    PUT:
      summary: Updateinputdevice
      description: Updates the parameters for the input device.
      operationId: amazonWebServicesUpdateInputDevice
  /prod/inputDevices/{inputDeviceId}/thumbnailData:
    GET:
      summary: Describeinputdevicethumbnail
      description: Get the latest thumbnail data for the input device.
      operationId: amazonWebServicesDescribeInputDeviceThumbnail
  /prod/offerings/{offeringId}:
    GET:
      summary: Describeoffering
      description: Get details for an offering.
      operationId: amazonWebServicesDescribeOffering
  /prod/channels/{channelId}/thumbnails:
    GET:
      summary: Describethumbnails
      description: Describe the latest thumbnails data.
      operationId: amazonWebServicesDescribeThumbnails
  /prod/inputDeviceTransfers:
    GET:
      summary: Listinputdevicetransfers
      description: >-
        List input devices that are currently being transferred. List input
        devices that you are transferring from your AWS account or input devices
        that another AWS account is transferring to you.
      operationId: amazonWebServicesListInputDeviceTransfers
  /prod/inputDevices:
    GET:
      summary: Listinputdevices
      description: List input devices
      operationId: amazonWebServicesListInputDevices
  /prod/offerings:
    GET:
      summary: Listofferings
      description: List offerings available for purchase.
      operationId: amazonWebServicesListOfferings
  /prod/reservations:
    GET:
      summary: Listreservations
      description: List purchased reservations.
      operationId: amazonWebServicesListReservations
  /prod/offerings/{offeringId}/purchase:
    POST:
      summary: Purchaseoffering
      description: Purchase an offering and create a reservation.
      operationId: amazonWebServicesPurchaseOffering
  /prod/inputDevices/{inputDeviceId}/reboot:
    POST:
      summary: Rebootinputdevice
      description: >-
        Send a reboot command to the specified input device. The device will
        begin rebooting within a few seconds of sending the command. When the
        reboot is complete, the device’s connection status will change to
        connected.
      operationId: amazonWebServicesRebootInputDevice
  /prod/inputDevices/{inputDeviceId}/reject:
    POST:
      summary: Rejectinputdevicetransfer
      description: Reject the transfer of the specified input device to your AWS account.
      operationId: amazonWebServicesRejectInputDeviceTransfer
  /prod/channels/{channelId}/start:
    POST:
      summary: Startchannel
      description: Starts an existing channel
      operationId: amazonWebServicesStartChannel
  /prod/inputDevices/{inputDeviceId}/start:
    POST:
      summary: Startinputdevice
      description: >-
        Start an input device that is attached to a MediaConnect flow. (There is
        no need to start a device that is attached to a MediaLive input;
        MediaLive starts the device when the channel starts.)
      operationId: amazonWebServicesStartInputDevice
  /prod/inputDevices/{inputDeviceId}/startInputDeviceMaintenanceWindow:
    POST:
      summary: Startinputdevicemaintenancewindow
      description: >-
        Start a maintenance window for the specified input device. Starting a
        maintenance window will give the device up to two hours to install
        software. If the device was streaming prior to the maintenance, it will
        resume streaming when the software is fully installed. Devices
        automatically install updates while they are powered on and their
        MediaLive channels are stopped. A maintenance window allows you to
        update a device without having to stop MediaLive channels that use the
        device. The device must remain powered on and connected to the internet
        for the duration of the maintenance.
      operationId: amazonWebServicesStartInputDeviceMaintenanceWindow
  /prod/multiplexes/{multiplexId}/start:
    POST:
      summary: Startmultiplex
      description: >-
        Start (run) the multiplex. Starting the multiplex does not start the
        channels. You must explicitly start each channel.
      operationId: amazonWebServicesStartMultiplex
  /prod/channels/{channelId}/stop:
    POST:
      summary: Stopchannel
      description: Stops a running channel
      operationId: amazonWebServicesStopChannel
  /prod/inputDevices/{inputDeviceId}/stop:
    POST:
      summary: Stopinputdevice
      description: >-
        Stop an input device that is attached to a MediaConnect flow. (There is
        no need to stop a device that is attached to a MediaLive input;
        MediaLive automatically stops the device when the channel stops.)
      operationId: amazonWebServicesStopInputDevice
  /prod/multiplexes/{multiplexId}/stop:
    POST:
      summary: Stopmultiplex
      description: >-
        Stops a running multiplex. If the multiplex isn't running, this action
        has no effect.
      operationId: amazonWebServicesStopMultiplex
  /prod/inputDevices/{inputDeviceId}/transfer:
    POST:
      summary: Transferinputdevice
      description: >-
        Start an input device transfer to another AWS account. After you make
        the request, the other account must accept or reject the transfer.
      operationId: amazonWebServicesTransferInputDevice
  /prod/channels/{channelId}/channelClass:
    PUT:
      summary: Updatechannelclass
      description: Changes the class of the channel.
      operationId: amazonWebServicesUpdateChannelClass
tags: []
