openapi: 3.1.0
info:
  title: mediapackage
  description: AWS Elemental MediaPackage
paths:
  /channels/{id}/configure_logs:
    PUT:
      summary: Configurelogs
      description: Changes the Channel's properities to configure log subscription
      operationId: amazonWebServicesConfigureLogs
  /channels:
    GET:
      summary: Listchannels
      description: Returns a collection of Channels.
      operationId: amazonWebServicesListChannels
  /harvest_jobs:
    GET:
      summary: Listharvestjobs
      description: Returns a collection of HarvestJob records.
      operationId: amazonWebServicesListHarvestJobs
  /origin_endpoints:
    GET:
      summary: Listoriginendpoints
      description: Returns a collection of OriginEndpoint records.
      operationId: amazonWebServicesListOriginEndpoints
  /channels/{id}:
    PUT:
      summary: Updatechannel
      description: Updates an existing Channel.
      operationId: amazonWebServicesUpdateChannel
  /origin_endpoints/{id}:
    PUT:
      summary: Updateoriginendpoint
      description: Updates an existing OriginEndpoint.
      operationId: amazonWebServicesUpdateOriginEndpoint
  /harvest_jobs/{id}:
    GET:
      summary: Describeharvestjob
      description: Gets details about an existing HarvestJob.
      operationId: amazonWebServicesDescribeHarvestJob
  /tags/{resource-arn}:
    DELETE:
      summary: Untagresource
      description: Needs a more full description created.
      operationId: amazonWebServicesUntagResource
  /channels/{id}/credentials:
    PUT:
      summary: Rotatechannelcredentials
      description: >-
        Changes the Channel's first IngestEndpoint's username and password.
        WARNING - This API is deprecated. Please use
        RotateIngestEndpointCredentials instead
      operationId: amazonWebServicesRotateChannelCredentials
  /channels/{id}/ingest_endpoints/{ingest_endpoint_id}/credentials:
    PUT:
      summary: Rotateingestendpointcredentials
      description: >-
        Rotate the IngestEndpoint's username and password, as specified by the
        IngestEndpoint's id.
      operationId: amazonWebServicesRotateIngestEndpointCredentials
tags: []
