openapi: 3.1.0
info:
  title: mgn
  description: <p>The Application Migration Service service.</p>
paths:
  /ArchiveApplication:
    POST:
      summary: Archiveapplication
      description: Archive application.
      operationId: amazonWebServicesArchiveApplication
  /ArchiveWave:
    POST:
      summary: Archivewave
      description: Archive wave.
      operationId: amazonWebServicesArchiveWave
  /AssociateApplications:
    POST:
      summary: Associateapplications
      description: Associate applications to wave.
      operationId: amazonWebServicesAssociateApplications
  /AssociateSourceServers:
    POST:
      summary: Associatesourceservers
      description: Associate source servers to application.
      operationId: amazonWebServicesAssociateSourceServers
  /ChangeServerLifeCycleState:
    POST:
      summary: Changeserverlifecyclestate
      description: >-
        Allows the user to set the SourceServer.LifeCycle.state property for
        specific Source Server IDs to one of the following: READY_FOR_TEST or
        READY_FOR_CUTOVER. This command only works if the Source Server is
        already launchable (dataReplicationInfo.lagDuration is not null.)
      operationId: amazonWebServicesChangeServerLifeCycleState
  /CreateApplication:
    POST:
      summary: Createapplication
      description: Create application.
      operationId: amazonWebServicesCreateApplication
  /CreateConnector:
    POST:
      summary: Createconnector
      description: Create Connector.
      operationId: amazonWebServicesCreateConnector
  /CreateLaunchConfigurationTemplate:
    POST:
      summary: Createlaunchconfigurationtemplate
      description: Creates a new Launch Configuration Template.
      operationId: amazonWebServicesCreateLaunchConfigurationTemplate
  /CreateReplicationConfigurationTemplate:
    POST:
      summary: Createreplicationconfigurationtemplate
      description: Creates a new ReplicationConfigurationTemplate.
      operationId: amazonWebServicesCreateReplicationConfigurationTemplate
  /CreateWave:
    POST:
      summary: Createwave
      description: Create wave.
      operationId: amazonWebServicesCreateWave
  /DeleteApplication:
    POST:
      summary: Deleteapplication
      description: Delete application.
      operationId: amazonWebServicesDeleteApplication
  /DeleteConnector:
    POST:
      summary: Deleteconnector
      description: Delete Connector.
      operationId: amazonWebServicesDeleteConnector
  /DeleteJob:
    POST:
      summary: Deletejob
      description: Deletes a single Job by ID.
      operationId: amazonWebServicesDeleteJob
  /DeleteLaunchConfigurationTemplate:
    POST:
      summary: Deletelaunchconfigurationtemplate
      description: Deletes a single Launch Configuration Template by ID.
      operationId: amazonWebServicesDeleteLaunchConfigurationTemplate
  /DeleteReplicationConfigurationTemplate:
    POST:
      summary: Deletereplicationconfigurationtemplate
      description: Deletes a single Replication Configuration Template by ID
      operationId: amazonWebServicesDeleteReplicationConfigurationTemplate
  /DeleteSourceServer:
    POST:
      summary: Deletesourceserver
      description: Deletes a single source server by ID.
      operationId: amazonWebServicesDeleteSourceServer
  /DeleteVcenterClient:
    POST:
      summary: Deletevcenterclient
      description: Deletes a given vCenter client by ID.
      operationId: amazonWebServicesDeleteVcenterClient
  /DeleteWave:
    POST:
      summary: Deletewave
      description: Delete wave.
      operationId: amazonWebServicesDeleteWave
  /DescribeJobLogItems:
    POST:
      summary: Describejoblogitems
      description: Retrieves detailed job log items with paging.
      operationId: amazonWebServicesDescribeJobLogItems
  /DescribeJobs:
    POST:
      summary: Describejobs
      description: >-
        Returns a list of Jobs. Use the JobsID and fromDate and toData filters
        to limit which jobs are returned. The response is sorted by
        creationDataTime - latest date first. Jobs are normally created by the
        StartTest, StartCutover, and TerminateTargetInstances APIs. Jobs are
        also created by DiagnosticLaunch and TerminateDiagnosticInstances, which
        are APIs available only to *Support* and only used in response to
        relevant support tickets.
      operationId: amazonWebServicesDescribeJobs
  /DescribeLaunchConfigurationTemplates:
    POST:
      summary: Describelaunchconfigurationtemplates
      description: >-
        Lists all Launch Configuration Templates, filtered by Launch
        Configuration Template IDs
      operationId: amazonWebServicesDescribeLaunchConfigurationTemplates
  /DescribeReplicationConfigurationTemplates:
    POST:
      summary: Describereplicationconfigurationtemplates
      description: >-
        Lists all ReplicationConfigurationTemplates, filtered by Source Server
        IDs.
      operationId: amazonWebServicesDescribeReplicationConfigurationTemplates
  /DescribeSourceServers:
    POST:
      summary: Describesourceservers
      description: Retrieves all SourceServers or multiple SourceServers by ID.
      operationId: amazonWebServicesDescribeSourceServers
  /DescribeVcenterClients:
    GET:
      summary: Describevcenterclients
      description: Returns a list of the installed vCenter clients.
      operationId: amazonWebServicesDescribeVcenterClients
  /DisassociateApplications:
    POST:
      summary: Disassociateapplications
      description: Disassociate applications from wave.
      operationId: amazonWebServicesDisassociateApplications
  /DisassociateSourceServers:
    POST:
      summary: Disassociatesourceservers
      description: Disassociate source servers from application.
      operationId: amazonWebServicesDisassociateSourceServers
  /DisconnectFromService:
    POST:
      summary: Disconnectfromservice
      description: >-
        Disconnects specific Source Servers from Application Migration Service.
        Data replication is stopped immediately. All AWS resources created by
        Application Migration Service for enabling the replication of these
        source servers will be terminated / deleted within 90 minutes. Launched
        Test or Cutover instances will NOT be terminated. If the agent on the
        source server has not been prevented from communicating with the
        Application Migration Service service, then it will receive a command to
        uninstall itself (within approximately 10 minutes). The following
        properties of the SourceServer will be changed immediately:
        dataReplicationInfo.dataReplicationState will be set to DISCONNECTED;
        The totalStorageBytes property for each of
        dataReplicationInfo.replicatedDisks will be set to zero;
        dataReplicationInfo.lagDuration and dataReplicationInfo.lagDuration will
        be nullified.
      operationId: amazonWebServicesDisconnectFromService
  /FinalizeCutover:
    POST:
      summary: Finalizecutover
      description: >-
        Finalizes the cutover immediately for specific Source Servers. All AWS
        resources created by Application Migration Service for enabling the
        replication of these source servers will be terminated / deleted within
        90 minutes. Launched Test or Cutover instances will NOT be terminated.
        The AWS Replication Agent will receive a command to uninstall itself
        (within 10 minutes). The following properties of the SourceServer will
        be changed immediately: dataReplicationInfo.dataReplicationState will be
        changed to DISCONNECTED; The SourceServer.lifeCycle.state will be
        changed to CUTOVER; The totalStorageBytes property fo each of
        dataReplicationInfo.replicatedDisks will be set to zero;
        dataReplicationInfo.lagDuration and dataReplicationInfo.lagDuration will
        be nullified.
      operationId: amazonWebServicesFinalizeCutover
  /GetLaunchConfiguration:
    POST:
      summary: Getlaunchconfiguration
      description: Lists all LaunchConfigurations available, filtered by Source Server IDs.
      operationId: amazonWebServicesGetLaunchConfiguration
  /GetReplicationConfiguration:
    POST:
      summary: Getreplicationconfiguration
      description: Lists all ReplicationConfigurations, filtered by Source Server ID.
      operationId: amazonWebServicesGetReplicationConfiguration
  /InitializeService:
    POST:
      summary: Initializeservice
      description: Initialize Application Migration Service.
      operationId: amazonWebServicesInitializeService
  /ListApplications:
    POST:
      summary: Listapplications
      description: Retrieves all applications or multiple applications by ID.
      operationId: amazonWebServicesListApplications
  /ListConnectors:
    POST:
      summary: Listconnectors
      description: List Connectors.
      operationId: amazonWebServicesListConnectors
  /ListExportErrors:
    POST:
      summary: Listexporterrors
      description: List export errors.
      operationId: amazonWebServicesListExportErrors
  /ListExports:
    POST:
      summary: Listexports
      description: List exports.
      operationId: amazonWebServicesListExports
  /ListImportErrors:
    POST:
      summary: Listimporterrors
      description: List import errors.
      operationId: amazonWebServicesListImportErrors
  /ListImports:
    POST:
      summary: Listimports
      description: List imports.
      operationId: amazonWebServicesListImports
  /ListManagedAccounts:
    POST:
      summary: Listmanagedaccounts
      description: List Managed Accounts.
      operationId: amazonWebServicesListManagedAccounts
  /ListSourceServerActions:
    POST:
      summary: Listsourceserveractions
      description: List source server post migration custom actions.
      operationId: amazonWebServicesListSourceServerActions
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: >-
        Deletes the specified set of tags from the specified set of Application
        Migration Service resources.
      operationId: amazonWebServicesUntagResource
  /ListTemplateActions:
    POST:
      summary: Listtemplateactions
      description: List template post migration custom actions.
      operationId: amazonWebServicesListTemplateActions
  /ListWaves:
    POST:
      summary: Listwaves
      description: Retrieves all waves or multiple waves by ID.
      operationId: amazonWebServicesListWaves
  /MarkAsArchived:
    POST:
      summary: Markasarchived
      description: >-
        Archives specific Source Servers by setting the SourceServer.isArchived
        property to true for specified SourceServers by ID. This command only
        works for SourceServers with a lifecycle. state which equals
        DISCONNECTED or CUTOVER.
      operationId: amazonWebServicesMarkAsArchived
  /PauseReplication:
    POST:
      summary: Pausereplication
      description: Pause Replication.
      operationId: amazonWebServicesPauseReplication
  /PutSourceServerAction:
    POST:
      summary: Putsourceserveraction
      description: Put source server post migration custom action.
      operationId: amazonWebServicesPutSourceServerAction
  /PutTemplateAction:
    POST:
      summary: Puttemplateaction
      description: Put template post migration custom action.
      operationId: amazonWebServicesPutTemplateAction
  /RemoveSourceServerAction:
    POST:
      summary: Removesourceserveraction
      description: Remove source server post migration custom action.
      operationId: amazonWebServicesRemoveSourceServerAction
  /RemoveTemplateAction:
    POST:
      summary: Removetemplateaction
      description: Remove template post migration custom action.
      operationId: amazonWebServicesRemoveTemplateAction
  /ResumeReplication:
    POST:
      summary: Resumereplication
      description: Resume Replication.
      operationId: amazonWebServicesResumeReplication
  /RetryDataReplication:
    POST:
      summary: Retrydatareplication
      description: >-
        Causes the data replication initiation sequence to begin immediately
        upon next Handshake for specified SourceServer IDs, regardless of when
        the previous initiation started. This command will not work if the
        SourceServer is not stalled or is in a DISCONNECTED or STOPPED state.
      operationId: amazonWebServicesRetryDataReplication
  /StartCutover:
    POST:
      summary: Startcutover
      description: >-
        Launches a Cutover Instance for specific Source Servers. This command
        starts a LAUNCH job whose initiatedBy property is StartCutover and
        changes the SourceServer.lifeCycle.state property to CUTTING_OVER.
      operationId: amazonWebServicesStartCutover
  /StartExport:
    POST:
      summary: Startexport
      description: Start export.
      operationId: amazonWebServicesStartExport
  /StartImport:
    POST:
      summary: Startimport
      description: Start import.
      operationId: amazonWebServicesStartImport
  /StartReplication:
    POST:
      summary: Startreplication
      description: Starts replication for SNAPSHOT_SHIPPING agents.
      operationId: amazonWebServicesStartReplication
  /StartTest:
    POST:
      summary: Starttest
      description: >-
        Launches a Test Instance for specific Source Servers. This command
        starts a LAUNCH job whose initiatedBy property is StartTest and changes
        the SourceServer.lifeCycle.state property to TESTING.
      operationId: amazonWebServicesStartTest
  /StopReplication:
    POST:
      summary: Stopreplication
      description: Stop Replication.
      operationId: amazonWebServicesStopReplication
  /TerminateTargetInstances:
    POST:
      summary: Terminatetargetinstances
      description: >-
        Starts a job that terminates specific launched EC2 Test and Cutover
        instances. This command will not work for any Source Server with a
        lifecycle.state of TESTING, CUTTING_OVER, or CUTOVER.
      operationId: amazonWebServicesTerminateTargetInstances
  /UnarchiveApplication:
    POST:
      summary: Unarchiveapplication
      description: Unarchive application.
      operationId: amazonWebServicesUnarchiveApplication
  /UnarchiveWave:
    POST:
      summary: Unarchivewave
      description: Unarchive wave.
      operationId: amazonWebServicesUnarchiveWave
  /UpdateApplication:
    POST:
      summary: Updateapplication
      description: Update application.
      operationId: amazonWebServicesUpdateApplication
  /UpdateConnector:
    POST:
      summary: Updateconnector
      description: Update Connector.
      operationId: amazonWebServicesUpdateConnector
  /UpdateLaunchConfiguration:
    POST:
      summary: Updatelaunchconfiguration
      description: Updates multiple LaunchConfigurations by Source Server ID.
      operationId: amazonWebServicesUpdateLaunchConfiguration
  /UpdateLaunchConfigurationTemplate:
    POST:
      summary: Updatelaunchconfigurationtemplate
      description: Updates an existing Launch Configuration Template by ID.
      operationId: amazonWebServicesUpdateLaunchConfigurationTemplate
  /UpdateReplicationConfiguration:
    POST:
      summary: Updatereplicationconfiguration
      description: >-
        Allows you to update multiple ReplicationConfigurations by Source Server
        ID.
      operationId: amazonWebServicesUpdateReplicationConfiguration
  /UpdateReplicationConfigurationTemplate:
    POST:
      summary: Updatereplicationconfigurationtemplate
      description: Updates multiple ReplicationConfigurationTemplates by ID.
      operationId: amazonWebServicesUpdateReplicationConfigurationTemplate
  /UpdateSourceServer:
    POST:
      summary: Updatesourceserver
      description: Update Source Server.
      operationId: amazonWebServicesUpdateSourceServer
  /UpdateSourceServerReplicationType:
    POST:
      summary: Updatesourceserverreplicationtype
      description: >-
        Allows you to change between the AGENT_BASED replication type and the
        SNAPSHOT_SHIPPING replication type.
      operationId: amazonWebServicesUpdateSourceServerReplicationType
  /UpdateWave:
    POST:
      summary: Updatewave
      description: Update wave.
      operationId: amazonWebServicesUpdateWave
tags: []
