openapi: 3.1.0
info:
  title: migration-hub-refactor-spaces
  description: >-
    <p><fullname>Amazon Web Services Migration Hub Refactor Spaces</fullname>
    <p>This API reference provides descriptions, syntax, and other details about
    each of the actions and data types for Amazon Web Services Migration Hub
    Refactor Spaces (Refactor Spaces). The topic for each action shows the API
    request parameters and the response. Alternatively, you can use one of the
    Amazon Web Services SDKs to access an API that is tailored to the
    programming language or platform that you're using. For more information,
    see <a href="https://aws.amazon.com/tools/#SDKs">Amazon Web Services
    SDKs</a>.</p> <p>To share Refactor Spaces environments with other Amazon Web
    Services accounts or with Organizations and their OUs, use Resource Access
    Manager's <code>CreateResourceShare</code> API. See <a
    href="https://docs.aws.amazon.com/ram/latest/APIReference/API_CreateResourceShare.html">CreateResourceShare</a>
    in the <i>Amazon Web Services RAM API Reference</i>.</p></p>
paths:
  /environments/{EnvironmentIdentifier}/applications:
    GET:
      summary: Listapplications
      description: >-
        Lists all the Amazon Web Services Migration Hub Refactor Spaces
        applications within an environment. 
      operationId: amazonWebServicesListApplications
  /environments:
    GET:
      summary: Listenvironments
      description: >-
        Lists Amazon Web Services Migration Hub Refactor Spaces environments
        owned by a caller account or shared with the caller account. 
      operationId: amazonWebServicesListEnvironments
  /environments/{EnvironmentIdentifier}/applications/{ApplicationIdentifier}/routes:
    GET:
      summary: Listroutes
      description: >-
        Lists all the Amazon Web Services Migration Hub Refactor Spaces routes
        within an application. 
      operationId: amazonWebServicesListRoutes
  /environments/{EnvironmentIdentifier}/applications/{ApplicationIdentifier}/services:
    GET:
      summary: Listservices
      description: >-
        Lists all the Amazon Web Services Migration Hub Refactor Spaces services
        within an application. 
      operationId: amazonWebServicesListServices
  /environments/{EnvironmentIdentifier}/applications/{ApplicationIdentifier}:
    GET:
      summary: Getapplication
      description: Gets an Amazon Web Services Migration Hub Refactor Spaces application.
      operationId: amazonWebServicesGetApplication
  /environments/{EnvironmentIdentifier}:
    GET:
      summary: Getenvironment
      description: Gets an Amazon Web Services Migration Hub Refactor Spaces environment.
      operationId: amazonWebServicesGetEnvironment
  /resourcepolicy/{Identifier}:
    GET:
      summary: Getresourcepolicy
      description: >-
        Gets the resource-based permission policy that is set for the given
        environment. 
      operationId: amazonWebServicesGetResourcePolicy
  /environments/{EnvironmentIdentifier}/applications/{ApplicationIdentifier}/routes/{RouteIdentifier}:
    PATCH:
      summary: Updateroute
      description: ' Updates an Amazon Web Services Migration Hub Refactor Spaces route. '
      operationId: amazonWebServicesUpdateRoute
  /environments/{EnvironmentIdentifier}/applications/{ApplicationIdentifier}/services/{ServiceIdentifier}:
    GET:
      summary: Getservice
      description: 'Gets an Amazon Web Services Migration Hub Refactor Spaces service. '
      operationId: amazonWebServicesGetService
  /environments/{EnvironmentIdentifier}/vpcs:
    GET:
      summary: Listenvironmentvpcs
      description: >-
        Lists all Amazon Web Services Migration Hub Refactor Spaces service
        virtual private clouds (VPCs) that are part of the environment. 
      operationId: amazonWebServicesListEnvironmentVpcs
  /tags/{ResourceArn}:
    DELETE:
      summary: Untagresource
      description: >-
        Adds to or modifies the tags of the given resource. Tags are metadata
        which can be used to manage a resource. To untag a resource, the caller
        account must be the same as the resource’s OwnerAccountId. Untagging
        resources across accounts is not supported. 
      operationId: amazonWebServicesUntagResource
  /resourcepolicy:
    PUT:
      summary: Putresourcepolicy
      description: >-
        Attaches a resource-based permission policy to the Amazon Web Services
        Migration Hub Refactor Spaces environment. The policy must contain the
        same actions and condition statements as the
        arn:aws:ram::aws:permission/AWSRAMDefaultPermissionRefactorSpacesEnvironment
        permission in Resource Access Manager. The policy must not contain new
        lines or blank lines. 
      operationId: amazonWebServicesPutResourcePolicy
tags: []
