openapi: 3.1.0
info:
  title: migrationhubstrategy
  description: >-
    <p><fullname>Migration Hub Strategy Recommendations</fullname> <p>This API
    reference provides descriptions, syntax, and other details about each of the
    actions and data types for Migration Hub Strategy Recommendations (Strategy
    Recommendations). The topic for each action shows the API request parameters
    and the response. Alternatively, you can use one of the AWS SDKs to access
    an API that is tailored to the programming language or platform that you're
    using. For more information, see <a
    href="http://aws.amazon.com/tools/#SDKs">AWS SDKs</a>.</p></p>
paths:
  /get-applicationcomponent-details/{applicationComponentId}:
    GET:
      summary: Getapplicationcomponentdetails
      description: ' Retrieves details about an application component. '
      operationId: amazonWebServicesGetApplicationComponentDetails
  /get-applicationcomponent-strategies/{applicationComponentId}:
    GET:
      summary: Getapplicationcomponentstrategies
      description: ' Retrieves a list of all the recommended strategies and tools for an application component running on a server. '
      operationId: amazonWebServicesGetApplicationComponentStrategies
  /get-assessment/{id}:
    GET:
      summary: Getassessment
      description: ' Retrieves the status of an on-going assessment. '
      operationId: amazonWebServicesGetAssessment
  /get-import-file-task/{id}:
    GET:
      summary: Getimportfiletask
      description: ' Retrieves the details about a specific import task. '
      operationId: amazonWebServicesGetImportFileTask
  /get-latest-assessment-id:
    GET:
      summary: Getlatestassessmentid
      description: Retrieve the latest ID of a specific assessment task.
      operationId: amazonWebServicesGetLatestAssessmentId
  /get-portfolio-preferences:
    GET:
      summary: Getportfoliopreferences
      description: ' Retrieves your migration and modernization preferences. '
      operationId: amazonWebServicesGetPortfolioPreferences
  /get-portfolio-summary:
    GET:
      summary: Getportfoliosummary
      description: ' Retrieves overall summary including the number of servers to rehost and the overall number of anti-patterns. '
      operationId: amazonWebServicesGetPortfolioSummary
  /get-recommendation-report-details/{id}:
    GET:
      summary: Getrecommendationreportdetails
      description: ' Retrieves detailed information about the specified recommendation report. '
      operationId: amazonWebServicesGetRecommendationReportDetails
  /get-server-details/{serverId}:
    GET:
      summary: Getserverdetails
      description: ' Retrieves detailed information about a specified server. '
      operationId: amazonWebServicesGetServerDetails
  /get-server-strategies/{serverId}:
    GET:
      summary: Getserverstrategies
      description: ' Retrieves recommended strategies and tools for the specified server. '
      operationId: amazonWebServicesGetServerStrategies
  /list-analyzable-servers:
    POST:
      summary: Listanalyzableservers
      description: >-
        Retrieves a list of all the servers fetched from customer vCenter using
        Strategy Recommendation Collector.
      operationId: amazonWebServicesListAnalyzableServers
  /list-applicationcomponents:
    POST:
      summary: Listapplicationcomponents
      description: ' Retrieves a list of all the application components (processes). '
      operationId: amazonWebServicesListApplicationComponents
  /list-collectors:
    GET:
      summary: Listcollectors
      description: ' Retrieves a list of all the installed collectors. '
      operationId: amazonWebServicesListCollectors
  /list-import-file-task:
    GET:
      summary: Listimportfiletask
      description: ' Retrieves a list of all the imports performed. '
      operationId: amazonWebServicesListImportFileTask
  /list-servers:
    POST:
      summary: Listservers
      description: ' Returns a list of all the servers. '
      operationId: amazonWebServicesListServers
  /put-portfolio-preferences:
    POST:
      summary: Putportfoliopreferences
      description: ' Saves the specified migration and modernization preferences. '
      operationId: amazonWebServicesPutPortfolioPreferences
  /start-assessment:
    POST:
      summary: Startassessment
      description: ' Starts the assessment of an on-premises environment. '
      operationId: amazonWebServicesStartAssessment
  /start-import-file-task:
    POST:
      summary: Startimportfiletask
      description: ' Starts a file import. '
      operationId: amazonWebServicesStartImportFileTask
  /start-recommendation-report-generation:
    POST:
      summary: Startrecommendationreportgeneration
      description: ' Starts generating a recommendation report. '
      operationId: amazonWebServicesStartRecommendationReportGeneration
  /stop-assessment:
    POST:
      summary: Stopassessment
      description: ' Stops the assessment of an on-premises environment. '
      operationId: amazonWebServicesStopAssessment
  /update-applicationcomponent-config/:
    POST:
      summary: Updateapplicationcomponentconfig
      description: ' Updates the configuration of an application component. '
      operationId: amazonWebServicesUpdateApplicationComponentConfig
  /update-server-config/:
    POST:
      summary: Updateserverconfig
      description: ' Updates the configuration of the specified server. '
      operationId: amazonWebServicesUpdateServerConfig
tags: []
