openapi: 3.1.0
info:
  title: migrationhuborchestrator
  description: >-
    <p>This API reference provides descriptions, syntax, and other details about
    each of the actions and data types for AWS Migration Hub Orchestrator. he
    topic for each action shows the API request parameters and the response.
    Alternatively, you can use one of the AWS SDKs to access an API that is
    tailored to the programming language or platform that you're using.</p>
paths:
  /migrationworkflow/:
    POST:
      summary: Createworkflow
      description: Create a workflow to orchestrate your migrations.
      operationId: amazonWebServicesCreateWorkflow
  /workflowstep:
    POST:
      summary: Createworkflowstep
      description: Create a step in the migration workflow.
      operationId: amazonWebServicesCreateWorkflowStep
  /workflowstepgroups:
    GET:
      summary: Listworkflowstepgroups
      description: List the step groups in a migration workflow.
      operationId: amazonWebServicesListWorkflowStepGroups
  /migrationworkflow/{id}:
    POST:
      summary: Updateworkflow
      description: Update a migration workflow.
      operationId: amazonWebServicesUpdateWorkflow
  /workflowstep/{id}:
    POST:
      summary: Updateworkflowstep
      description: Update a step in a migration workflow.
      operationId: amazonWebServicesUpdateWorkflowStep
  /workflowstepgroup/{id}:
    POST:
      summary: Updateworkflowstepgroup
      description: Update the step group in a migration workflow.
      operationId: amazonWebServicesUpdateWorkflowStepGroup
  /migrationworkflowtemplate/{id}:
    GET:
      summary: Gettemplate
      description: Get the template you want to use for creating a migration workflow.
      operationId: amazonWebServicesGetTemplate
  /templatestep/{id}:
    GET:
      summary: Gettemplatestep
      description: Get a specific step in a template.
      operationId: amazonWebServicesGetTemplateStep
  /templates/{templateId}/stepgroups/{id}:
    GET:
      summary: Gettemplatestepgroup
      description: Get a step group in a template.
      operationId: amazonWebServicesGetTemplateStepGroup
  /plugins:
    GET:
      summary: Listplugins
      description: List AWS Migration Hub Orchestrator plugins.
      operationId: amazonWebServicesListPlugins
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Deletes the tags for a resource.
      operationId: amazonWebServicesUntagResource
  /templatestepgroups/{templateId}:
    GET:
      summary: Listtemplatestepgroups
      description: List the step groups in a template.
      operationId: amazonWebServicesListTemplateStepGroups
  /templatesteps:
    GET:
      summary: Listtemplatesteps
      description: List the steps in a template.
      operationId: amazonWebServicesListTemplateSteps
  /migrationworkflowtemplates:
    GET:
      summary: Listtemplates
      description: >-
        List the templates available in Migration Hub Orchestrator to create a
        migration workflow.
      operationId: amazonWebServicesListTemplates
  /workflow/{workflowId}/workflowstepgroups/{stepGroupId}/workflowsteps:
    GET:
      summary: Listworkflowsteps
      description: List the steps in a workflow.
      operationId: amazonWebServicesListWorkflowSteps
  /migrationworkflows:
    GET:
      summary: Listworkflows
      description: List the migration workflows.
      operationId: amazonWebServicesListWorkflows
  /retryworkflowstep/{id}:
    POST:
      summary: Retryworkflowstep
      description: Retry a failed step in a migration workflow.
      operationId: amazonWebServicesRetryWorkflowStep
  /migrationworkflow/{id}/start:
    POST:
      summary: Startworkflow
      description: Start a migration workflow.
      operationId: amazonWebServicesStartWorkflow
  /migrationworkflow/{id}/stop:
    POST:
      summary: Stopworkflow
      description: Stop an ongoing migration workflow.
      operationId: amazonWebServicesStopWorkflow
tags: []
