openapi: 3.1.0
info:
  title: mobile
  description: >-
    <p> AWS Mobile Service provides mobile app and website developers with
    capabilities required to configure AWS resources and bootstrap their
    developer desktop projects with the necessary SDKs, constants, tools and
    samples to make use of those resources. </p>
paths:
  /projects:
    GET:
      summary: Listprojects
      description: ' Lists projects in AWS Mobile Hub. '
      operationId: amazonWebServicesListProjects
  /projects/{projectId}:
    DELETE:
      summary: Deleteproject
      description: ' Delets a project in AWS Mobile Hub. '
      operationId: amazonWebServicesDeleteProject
  /bundles/{bundleId}:
    POST:
      summary: Exportbundle
      description: ' Generates customized software development kit (SDK) and or tool packages used to integrate mobile web or mobile app clients with backend AWS resources. '
      operationId: amazonWebServicesExportBundle
  /project:
    GET:
      summary: Describeproject
      description: ' Gets details about a project in AWS Mobile Hub. '
      operationId: amazonWebServicesDescribeProject
  /exports/{projectId}:
    POST:
      summary: Exportproject
      description: ' Exports project configuration to a snapshot which can be downloaded and shared. Note that mobile app push credentials are encrypted in exported projects, so they can only be shared successfully within the same AWS account. '
      operationId: amazonWebServicesExportProject
  /bundles:
    GET:
      summary: Listbundles
      description: ' List all available bundles. '
      operationId: amazonWebServicesListBundles
  /update:
    POST:
      summary: Updateproject
      description: ' Update an existing project. '
      operationId: amazonWebServicesUpdateProject
tags: []
