openapi: 3.1.0
info:
  title: mq
  description: >-
    <p>Amazon MQ is a managed message broker service for Apache ActiveMQ and
    RabbitMQ that makes it easy to set up and operate message brokers in the
    cloud. A message broker allows software applications and components to
    communicate using various programming languages, operating systems, and
    formal messaging protocols.</p>
paths:
  /v1/brokers:
    GET:
      summary: Listbrokers
      description: Returns a list of all brokers.
      operationId: amazonWebServicesListBrokers
  /v1/configurations:
    GET:
      summary: Listconfigurations
      description: Returns a list of all configurations.
      operationId: amazonWebServicesListConfigurations
  /v1/tags/{resource-arn}:
    GET:
      summary: Listtags
      description: Lists tags for a resource.
      operationId: amazonWebServicesListTags
  /v1/brokers/{broker-id}/users/{username}:
    PUT:
      summary: Updateuser
      description: Updates the information for an ActiveMQ user.
      operationId: amazonWebServicesUpdateUser
  /v1/brokers/{broker-id}:
    PUT:
      summary: Updatebroker
      description: Adds a pending configuration change to a broker.
      operationId: amazonWebServicesUpdateBroker
  /v1/broker-engine-types:
    GET:
      summary: Describebrokerenginetypes
      description: Describe available engine types and versions.
      operationId: amazonWebServicesDescribeBrokerEngineTypes
  /v1/broker-instance-options:
    GET:
      summary: Describebrokerinstanceoptions
      description: Describe available broker instance options.
      operationId: amazonWebServicesDescribeBrokerInstanceOptions
  /v1/configurations/{configuration-id}:
    PUT:
      summary: Updateconfiguration
      description: Updates the specified configuration.
      operationId: amazonWebServicesUpdateConfiguration
  /v1/configurations/{configuration-id}/revisions/{configuration-revision}:
    GET:
      summary: Describeconfigurationrevision
      description: >-
        Returns the specified configuration revision for the specified
        configuration.
      operationId: amazonWebServicesDescribeConfigurationRevision
  /v1/configurations/{configuration-id}/revisions:
    GET:
      summary: Listconfigurationrevisions
      description: Returns a list of all revisions for the specified configuration.
      operationId: amazonWebServicesListConfigurationRevisions
  /v1/brokers/{broker-id}/users:
    GET:
      summary: Listusers
      description: Returns a list of all ActiveMQ users.
      operationId: amazonWebServicesListUsers
  /v1/brokers/{broker-id}/promote:
    POST:
      summary: Promote
      description: Promotes a data replication replica broker to the primary broker role.
      operationId: amazonWebServicesPromote
  /v1/brokers/{broker-id}/reboot:
    POST:
      summary: Rebootbroker
      description: 'Reboots a broker. Note: This API is asynchronous.'
      operationId: amazonWebServicesRebootBroker
tags: []
