openapi: 3.1.0
info:
  title: neptune-graph
  description: >-
    <p>Neptune Analytics is a new analytics database engine for Amazon Neptune
    that helps customers get to insights faster by quickly processing large
    amounts of graph data, invoking popular graph analytic algorithms in
    low-latency queries, and getting analytics results in seconds.</p>
paths:
  /importtasks/{taskIdentifier}:
    GET:
      summary: Getimporttask
      description: Retrieves a specified import task.
      operationId: amazonWebServicesGetImportTask
  /queries/{queryId}:
    GET:
      summary: Getquery
      description: >-
        Retrieves the status of a specified query.   When invoking this
        operation in a Neptune Analytics cluster, the IAM user or role making
        the request must have the neptune-graph:GetQueryStatus IAM action
        attached.  
      operationId: amazonWebServicesGetQuery
  /graphs:
    GET:
      summary: Listgraphs
      description: Lists available Neptune Analytics graphs.
      operationId: amazonWebServicesListGraphs
  /snapshots:
    GET:
      summary: Listgraphsnapshots
      description: Lists available snapshots of a specified Neptune Analytics graph.
      operationId: amazonWebServicesListGraphSnapshots
  /importtasks:
    GET:
      summary: Listimporttasks
      description: Lists import tasks.
      operationId: amazonWebServicesListImportTasks
  /graphs/{graphIdentifier}/endpoints/:
    GET:
      summary: Listprivategraphendpoints
      description: Lists private endpoints for a specified Neptune Analytics graph.
      operationId: amazonWebServicesListPrivateGraphEndpoints
  /graphs/{graphIdentifier}:
    PATCH:
      summary: Updategraph
      description: Updates the configuration of a specified Neptune Analytics graph
      operationId: amazonWebServicesUpdateGraph
  /snapshots/{snapshotIdentifier}:
    GET:
      summary: Getgraphsnapshot
      description: Retrieves a specified graph snapshot.
      operationId: amazonWebServicesGetGraphSnapshot
  /graphs/{graphIdentifier}/endpoints/{vpcId}:
    GET:
      summary: Getprivategraphendpoint
      description: Retrieves information about a specified private endpoint.
      operationId: amazonWebServicesGetPrivateGraphEndpoint
  /queries:
    GET:
      summary: Listqueries
      description: Lists active openCypher queries.
      operationId: amazonWebServicesListQueries
  /summary:
    GET:
      summary: Getgraphsummary
      description: Gets a graph summary for a property graph.
      operationId: amazonWebServicesGetGraphSummary
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes the specified tags from the specified resource.
      operationId: amazonWebServicesUntagResource
  /snapshots/{snapshotIdentifier}/restore:
    POST:
      summary: Restoregraphfromsnapshot
      description: Restores a graph from a snapshot.
      operationId: amazonWebServicesRestoreGraphFromSnapshot
tags: []
