openapi: 3.1.0
info:
  title: networkmanager
  description: >-
    <p>Amazon Web Services enables you to centrally manage your Amazon Web
    Services Cloud WAN core network and your Transit Gateway network across
    Amazon Web Services accounts, Regions, and on-premises locations.</p>
paths:
  /attachments/{attachmentId}/accept:
    POST:
      summary: Acceptattachment
      description: >-
        Accepts a core network attachment request.  Once the attachment request
        is accepted by a core network owner, the attachment is created and
        connected to a core network.
      operationId: amazonWebServicesAcceptAttachment
  /global-networks/{globalNetworkId}/connect-peer-associations:
    GET:
      summary: Getconnectpeerassociations
      description: Returns information about a core network Connect peer associations.
      operationId: amazonWebServicesGetConnectPeerAssociations
  /global-networks/{globalNetworkId}/customer-gateway-associations:
    GET:
      summary: Getcustomergatewayassociations
      description: >-
        Gets the association information for customer gateways that are
        associated with devices and links in your global network.
      operationId: amazonWebServicesGetCustomerGatewayAssociations
  /global-networks/{globalNetworkId}/link-associations:
    GET:
      summary: Getlinkassociations
      description: >-
        Gets the link associations for a device or a link. Either the device ID
        or the link ID must be specified.
      operationId: amazonWebServicesGetLinkAssociations
  /global-networks/{globalNetworkId}/transit-gateway-connect-peer-associations:
    GET:
      summary: Gettransitgatewayconnectpeerassociations
      description: >-
        Gets information about one or more of your transit gateway Connect peer
        associations in a global network.
      operationId: amazonWebServicesGetTransitGatewayConnectPeerAssociations
  /connect-attachments:
    POST:
      summary: Createconnectattachment
      description: >-
        Creates a core network Connect attachment from a specified core network
        attachment.  A core network Connect attachment is a GRE-based tunnel
        attachment that you can use to establish a connection between a core
        network and an appliance. A core network Connect attachment uses an
        existing VPC attachment as the underlying transport mechanism.
      operationId: amazonWebServicesCreateConnectAttachment
  /connect-peers:
    GET:
      summary: Listconnectpeers
      description: Returns a list of core network Connect peers.
      operationId: amazonWebServicesListConnectPeers
  /global-networks/{globalNetworkId}/connections:
    GET:
      summary: Getconnections
      description: >-
        Gets information about one or more of your connections in a global
        network.
      operationId: amazonWebServicesGetConnections
  /core-networks:
    GET:
      summary: Listcorenetworks
      description: Returns a list of owned and shared core networks.
      operationId: amazonWebServicesListCoreNetworks
  /global-networks/{globalNetworkId}/devices:
    GET:
      summary: Getdevices
      description: Gets information about one or more of your devices in a global network.
      operationId: amazonWebServicesGetDevices
  /global-networks:
    GET:
      summary: Describeglobalnetworks
      description: >-
        Describes one or more global networks. By default, all global networks
        are described. To describe the objects in your global network, you must
        use the appropriate Get* action. For example, to list the transit
        gateways in your global network, use GetTransitGatewayRegistrations.
      operationId: amazonWebServicesDescribeGlobalNetworks
  /global-networks/{globalNetworkId}/links:
    GET:
      summary: Getlinks
      description: >-
        Gets information about one or more links in a specified global network.
        If you specify the site ID, you cannot specify the type or provider in
        the same request. You can specify the type and provider in the same
        request.
      operationId: amazonWebServicesGetLinks
  /global-networks/{globalNetworkId}/sites:
    GET:
      summary: Getsites
      description: Gets information about one or more of your sites in a global network.
      operationId: amazonWebServicesGetSites
  /site-to-site-vpn-attachments:
    POST:
      summary: Createsitetositevpnattachment
      description: >-
        Creates an Amazon Web Services site-to-site VPN attachment on an edge
        location of a core network.
      operationId: amazonWebServicesCreateSiteToSiteVpnAttachment
  /transit-gateway-peerings:
    POST:
      summary: Createtransitgatewaypeering
      description: Creates a transit gateway peering connection.
      operationId: amazonWebServicesCreateTransitGatewayPeering
  /transit-gateway-route-table-attachments:
    POST:
      summary: Createtransitgatewayroutetableattachment
      description: Creates a transit gateway route table attachment.
      operationId: amazonWebServicesCreateTransitGatewayRouteTableAttachment
  /vpc-attachments:
    POST:
      summary: Createvpcattachment
      description: Creates a VPC attachment on an edge location of a core network.
      operationId: amazonWebServicesCreateVpcAttachment
  /attachments/{attachmentId}:
    DELETE:
      summary: Deleteattachment
      description: Deletes an attachment. Supports all attachment types.
      operationId: amazonWebServicesDeleteAttachment
  /connect-peers/{connectPeerId}:
    GET:
      summary: Getconnectpeer
      description: Returns information about a core network Connect peer.
      operationId: amazonWebServicesGetConnectPeer
  /global-networks/{globalNetworkId}/connections/{connectionId}:
    PATCH:
      summary: Updateconnection
      description: >-
        Updates the information for an existing connection. To remove
        information for any of the parameters, specify an empty string.
      operationId: amazonWebServicesUpdateConnection
  /core-networks/{coreNetworkId}:
    PATCH:
      summary: Updatecorenetwork
      description: Updates the description of a core network.
      operationId: amazonWebServicesUpdateCoreNetwork
  /core-networks/{coreNetworkId}/core-network-policy-versions/{policyVersionId}:
    DELETE:
      summary: Deletecorenetworkpolicyversion
      description: >-
        Deletes a policy version from a core network. You can't delete the
        current LIVE policy.
      operationId: amazonWebServicesDeleteCoreNetworkPolicyVersion
  /global-networks/{globalNetworkId}/devices/{deviceId}:
    PATCH:
      summary: Updatedevice
      description: >-
        Updates the details for an existing device. To remove information for
        any of the parameters, specify an empty string.
      operationId: amazonWebServicesUpdateDevice
  /global-networks/{globalNetworkId}:
    PATCH:
      summary: Updateglobalnetwork
      description: >-
        Updates an existing global network. To remove information for any of the
        parameters, specify an empty string.
      operationId: amazonWebServicesUpdateGlobalNetwork
  /global-networks/{globalNetworkId}/links/{linkId}:
    PATCH:
      summary: Updatelink
      description: >-
        Updates the details for an existing link. To remove information for any
        of the parameters, specify an empty string.
      operationId: amazonWebServicesUpdateLink
  /peerings/{peeringId}:
    DELETE:
      summary: Deletepeering
      description: Deletes an existing peering connection.
      operationId: amazonWebServicesDeletePeering
  /resource-policy/{resourceArn}:
    POST:
      summary: Putresourcepolicy
      description: Creates or updates a resource policy.
      operationId: amazonWebServicesPutResourcePolicy
  /global-networks/{globalNetworkId}/sites/{siteId}:
    PATCH:
      summary: Updatesite
      description: >-
        Updates the information for an existing site. To remove information for
        any of the parameters, specify an empty string.
      operationId: amazonWebServicesUpdateSite
  /global-networks/{globalNetworkId}/transit-gateway-registrations/{transitGatewayArn}:
    DELETE:
      summary: Deregistertransitgateway
      description: >-
        Deregisters a transit gateway from your global network. This action does
        not delete your transit gateway, or modify any of its attachments. This
        action removes any customer gateway associations.
      operationId: amazonWebServicesDeregisterTransitGateway
  /global-networks/{globalNetworkId}/connect-peer-associations/{connectPeerId}:
    DELETE:
      summary: Disassociateconnectpeer
      description: 'Disassociates a core network Connect peer from a device and a link. '
      operationId: amazonWebServicesDisassociateConnectPeer
  /global-networks/{globalNetworkId}/customer-gateway-associations/{customerGatewayArn}:
    DELETE:
      summary: Disassociatecustomergateway
      description: Disassociates a customer gateway from a device and a link.
      operationId: amazonWebServicesDisassociateCustomerGateway
  /global-networks/{globalNetworkId}/transit-gateway-connect-peer-associations/{transitGatewayConnectPeerArn}:
    DELETE:
      summary: Disassociatetransitgatewayconnectpeer
      description: Disassociates a transit gateway Connect peer from a device and link.
      operationId: amazonWebServicesDisassociateTransitGatewayConnectPeer
  /core-networks/{coreNetworkId}/core-network-change-sets/{policyVersionId}/execute:
    POST:
      summary: Executecorenetworkchangeset
      description: >-
        Executes a change set on your core network. Deploys changes globally
        based on the policy submitted..
      operationId: amazonWebServicesExecuteCoreNetworkChangeSet
  /connect-attachments/{attachmentId}:
    GET:
      summary: Getconnectattachment
      description: Returns information about a core network Connect attachment.
      operationId: amazonWebServicesGetConnectAttachment
  /core-networks/{coreNetworkId}/core-network-change-events/{policyVersionId}:
    GET:
      summary: Getcorenetworkchangeevents
      description: Returns information about a core network change event.
      operationId: amazonWebServicesGetCoreNetworkChangeEvents
  /core-networks/{coreNetworkId}/core-network-change-sets/{policyVersionId}:
    GET:
      summary: Getcorenetworkchangeset
      description: >-
        Returns a change set between the LIVE core network policy and a
        submitted policy.
      operationId: amazonWebServicesGetCoreNetworkChangeSet
  /core-networks/{coreNetworkId}/core-network-policy:
    POST:
      summary: Putcorenetworkpolicy
      description: >-
        Creates a new, immutable version of a core network policy. A subsequent
        change set is created showing the differences between the LIVE policy
        and the submitted policy.
      operationId: amazonWebServicesPutCoreNetworkPolicy
  /global-networks/{globalNetworkId}/network-resource-count:
    GET:
      summary: Getnetworkresourcecounts
      description: >-
        Gets the count of network resources, by resource type, for the specified
        global network.
      operationId: amazonWebServicesGetNetworkResourceCounts
  /global-networks/{globalNetworkId}/network-resource-relationships:
    GET:
      summary: Getnetworkresourcerelationships
      description: >-
        Gets the network resource relationships for the specified global
        network.
      operationId: amazonWebServicesGetNetworkResourceRelationships
  /global-networks/{globalNetworkId}/network-resources:
    GET:
      summary: Getnetworkresources
      description: >-
        Describes the network resources for the specified global network. The
        results include information from the corresponding Describe call for the
        resource, minus any sensitive information such as pre-shared keys.
      operationId: amazonWebServicesGetNetworkResources
  /global-networks/{globalNetworkId}/network-routes:
    POST:
      summary: Getnetworkroutes
      description: Gets the network routes of the specified global network.
      operationId: amazonWebServicesGetNetworkRoutes
  /global-networks/{globalNetworkId}/network-telemetry:
    GET:
      summary: Getnetworktelemetry
      description: Gets the network telemetry of the specified global network.
      operationId: amazonWebServicesGetNetworkTelemetry
  /global-networks/{globalNetworkId}/route-analyses/{routeAnalysisId}:
    GET:
      summary: Getrouteanalysis
      description: Gets information about the specified route analysis.
      operationId: amazonWebServicesGetRouteAnalysis
  /site-to-site-vpn-attachments/{attachmentId}:
    GET:
      summary: Getsitetositevpnattachment
      description: Returns information about a site-to-site VPN attachment.
      operationId: amazonWebServicesGetSiteToSiteVpnAttachment
  /transit-gateway-peerings/{peeringId}:
    GET:
      summary: Gettransitgatewaypeering
      description: Returns information about a transit gateway peer.
      operationId: amazonWebServicesGetTransitGatewayPeering
  /global-networks/{globalNetworkId}/transit-gateway-registrations:
    POST:
      summary: Registertransitgateway
      description: >-
        Registers a transit gateway in your global network. Not all Regions
        support transit gateways for global networks. For a list of the
        supported Regions, see Region Availability in the Amazon Web Services
        Transit Gateways for Global Networks User Guide. The transit gateway can
        be in any of the supported Amazon Web Services Regions, but it must be
        owned by the same Amazon Web Services account that owns the global
        network. You cannot register a transit gateway in more than one global
        network.
      operationId: amazonWebServicesRegisterTransitGateway
  /transit-gateway-route-table-attachments/{attachmentId}:
    GET:
      summary: Gettransitgatewayroutetableattachment
      description: Returns information about a transit gateway route table attachment.
      operationId: amazonWebServicesGetTransitGatewayRouteTableAttachment
  /vpc-attachments/{attachmentId}:
    PATCH:
      summary: Updatevpcattachment
      description: Updates a VPC attachment.
      operationId: amazonWebServicesUpdateVpcAttachment
  /attachments:
    GET:
      summary: Listattachments
      description: Returns a list of core network attachments.
      operationId: amazonWebServicesListAttachments
  /core-networks/{coreNetworkId}/core-network-policy-versions:
    GET:
      summary: Listcorenetworkpolicyversions
      description: Returns a list of core network policy versions.
      operationId: amazonWebServicesListCoreNetworkPolicyVersions
  /organizations/service-access:
    POST:
      summary: Startorganizationserviceaccessupdate
      description: >-
        Enables the Network Manager service for an Amazon Web Services
        Organization. This can only be called by a management account within the
        organization. 
      operationId: amazonWebServicesStartOrganizationServiceAccessUpdate
  /peerings:
    GET:
      summary: Listpeerings
      description: Lists the peerings for a core network.
      operationId: amazonWebServicesListPeerings
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes tags from a specified resource.
      operationId: amazonWebServicesUntagResource
  /attachments/{attachmentId}/reject:
    POST:
      summary: Rejectattachment
      description: Rejects a core network attachment request.
      operationId: amazonWebServicesRejectAttachment
  /core-networks/{coreNetworkId}/core-network-policy-versions/{policyVersionId}/restore:
    POST:
      summary: Restorecorenetworkpolicyversion
      description: >-
        Restores a previous policy version as a new, immutable version of a core
        network policy. A subsequent change set is created showing the
        differences between the LIVE policy and restored policy.
      operationId: amazonWebServicesRestoreCoreNetworkPolicyVersion
  /global-networks/{globalNetworkId}/route-analyses:
    POST:
      summary: Startrouteanalysis
      description: >-
        Starts analyzing the routing path between the specified source and
        destination. For more information, see Route Analyzer.
      operationId: amazonWebServicesStartRouteAnalysis
  /global-networks/{globalNetworkId}/network-resources/{resourceArn}/metadata:
    PATCH:
      summary: Updatenetworkresourcemetadata
      description: Updates the resource metadata for the specified global network.
      operationId: amazonWebServicesUpdateNetworkResourceMetadata
tags: []
