openapi: 3.1.0
info:
  title: networkmonitor
  description: >-
    <p>Amazon CloudWatch Network Monitor is an Amazon Web Services active
    network monitoring service that identifies if a network issues exists within
    the Amazon Web Services network or your own company network. Within Network
    Monitor you'll choose the source VPCs and subnets from the Amazon Web
    Services network in which you operate and then you'll choose the destination
    IP addresses from your on-premises network. From these sources and
    destinations, Network Monitor creates a monitor containing all the possible
    source and destination combinations, each of which is called a probe, within
    a single monitor. These probes then monitor network traffic to help you
    identify where network issues might be affecting your traffic.</p> <p>For
    more information, see <a
    href="https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/what-is-network-monitor.html">Using
    Amazon CloudWatch Network Monitor</a> in the <i>Amazon CloudWatch User
    Guide</i>.</p>
paths:
  /monitors:
    GET:
      summary: Listmonitors
      description: Returns a list of all of your monitors.
      operationId: amazonWebServicesListMonitors
  /monitors/{monitorName}/probes:
    POST:
      summary: Createprobe
      description: >-
        Create a probe within a monitor. Once you create a probe, and it begins
        monitoring your network traffic, you'll incur billing charges for that
        probe. 
      operationId: amazonWebServicesCreateProbe
  /monitors/{monitorName}:
    PATCH:
      summary: Updatemonitor
      description: >-
        Updates the aggregationPeriod for a monitor. Monitors support an
        aggregationPeriod of either 30 or 60 seconds.
      operationId: amazonWebServicesUpdateMonitor
  /monitors/{monitorName}/probes/{probeId}:
    PATCH:
      summary: Updateprobe
      description: >-
        Updates a monitor probe. This action requires both the monitorName and
        probeId parameters. Run ListMonitors to get a list of monitor names. Run
        GetMonitor to get a list of probes and probe IDs. 
      operationId: amazonWebServicesUpdateProbe
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes a key-value pair from a monitor or probe.
      operationId: amazonWebServicesUntagResource
tags: []
