openapi: 3.1.0
info:
  title: nimble
  description: >-
    <p>Welcome to the Amazon Nimble Studio API reference. This API reference
    provides methods, schema, resources, parameters, and more to help you get
    the most out of Nimble Studio.</p> <p>Nimble Studio is a virtual studio that
    empowers visual effects, animation, and interactive content teams to create
    content securely within a scalable, private cloud service.</p>
paths:
  /2020-08-01/studios/{studioId}/eula-acceptances:
    GET:
      summary: Listeulaacceptances
      description: List EULA acceptances.
      operationId: amazonWebServicesListEulaAcceptances
  /2020-08-01/studios/{studioId}/launch-profiles:
    GET:
      summary: Listlaunchprofiles
      description: List all the launch profiles a studio.
      operationId: amazonWebServicesListLaunchProfiles
  /2020-08-01/studios/{studioId}/streaming-images:
    GET:
      summary: Liststreamingimages
      description: >-
        List the streaming image resources available to this studio. This list
        will contain both images provided by Amazon Web Services, as well as
        streaming images that you have created in your studio.
      operationId: amazonWebServicesListStreamingImages
  /2020-08-01/studios/{studioId}/streaming-sessions:
    GET:
      summary: Liststreamingsessions
      description: Lists the streaming sessions in a studio.
      operationId: amazonWebServicesListStreamingSessions
  /2020-08-01/studios/{studioId}/streaming-sessions/{sessionId}/streams:
    POST:
      summary: Createstreamingsessionstream
      description: >-
        Creates a streaming session stream for a streaming session. After
        invoking this API, invoke GetStreamingSessionStream with the returned
        streamId to poll the resource until it is in the READY state.
      operationId: amazonWebServicesCreateStreamingSessionStream
  /2020-08-01/studios:
    GET:
      summary: Liststudios
      description: >-
        List studios in your Amazon Web Services accounts in the requested
        Amazon Web Services Region.
      operationId: amazonWebServicesListStudios
  /2020-08-01/studios/{studioId}/studio-components:
    GET:
      summary: Liststudiocomponents
      description: Lists the StudioComponents in a studio.
      operationId: amazonWebServicesListStudioComponents
  /2020-08-01/studios/{studioId}/launch-profiles/{launchProfileId}:
    PATCH:
      summary: Updatelaunchprofile
      description: Update a launch profile.
      operationId: amazonWebServicesUpdateLaunchProfile
  /2020-08-01/studios/{studioId}/launch-profiles/{launchProfileId}/membership/{principalId}:
    PATCH:
      summary: Updatelaunchprofilemember
      description: Update a user persona in launch profile membership.
      operationId: amazonWebServicesUpdateLaunchProfileMember
  /2020-08-01/studios/{studioId}/streaming-images/{streamingImageId}:
    PATCH:
      summary: Updatestreamingimage
      description: Update streaming image.
      operationId: amazonWebServicesUpdateStreamingImage
  /2020-08-01/studios/{studioId}/streaming-sessions/{sessionId}:
    GET:
      summary: Getstreamingsession
      description: >-
        Gets StreamingSession resource. Invoke this operation to poll for a
        streaming session state while creating or deleting a session.
      operationId: amazonWebServicesGetStreamingSession
  /2020-08-01/studios/{studioId}:
    PATCH:
      summary: Updatestudio
      description: >-
        Update a Studio resource. Currently, this operation only supports
        updating the displayName of your studio.
      operationId: amazonWebServicesUpdateStudio
  /2020-08-01/studios/{studioId}/studio-components/{studioComponentId}:
    PATCH:
      summary: Updatestudiocomponent
      description: Updates a studio component resource.
      operationId: amazonWebServicesUpdateStudioComponent
  /2020-08-01/studios/{studioId}/membership/{principalId}:
    GET:
      summary: Getstudiomember
      description: Get a user's membership in a studio.
      operationId: amazonWebServicesGetStudioMember
  /2020-08-01/eulas/{eulaId}:
    GET:
      summary: Geteula
      description: Get EULA.
      operationId: amazonWebServicesGetEula
  /2020-08-01/studios/{studioId}/launch-profiles/{launchProfileId}/details:
    GET:
      summary: Getlaunchprofiledetails
      description: >-
        Launch profile details include the launch profile resource and summary
        information of resources that are used by, or available to, the launch
        profile. This includes the name and description of all studio components
        used by the launch profiles, and the name and description of streaming
        images that can be used with this launch profile.
      operationId: amazonWebServicesGetLaunchProfileDetails
  /2020-08-01/studios/{studioId}/launch-profiles/{launchProfileId}/init:
    GET:
      summary: Getlaunchprofileinitialization
      description: Get a launch profile initialization.
      operationId: amazonWebServicesGetLaunchProfileInitialization
  /2020-08-01/studios/{studioId}/streaming-session-backups/{backupId}:
    GET:
      summary: Getstreamingsessionbackup
      description: >-
        Gets StreamingSessionBackup resource. Invoke this operation to poll for
        a streaming session backup while stopping a streaming session.
      operationId: amazonWebServicesGetStreamingSessionBackup
  /2020-08-01/studios/{studioId}/streaming-sessions/{sessionId}/streams/{streamId}:
    GET:
      summary: Getstreamingsessionstream
      description: >-
        Gets a StreamingSessionStream for a streaming session. Invoke this
        operation to poll the resource after invoking
        CreateStreamingSessionStream. After the StreamingSessionStream changes
        to the READY state, the url property will contain a stream to be used
        with the DCV streaming client.
      operationId: amazonWebServicesGetStreamingSessionStream
  /2020-08-01/eulas:
    GET:
      summary: Listeulas
      description: List EULAs.
      operationId: amazonWebServicesListEulas
  /2020-08-01/studios/{studioId}/launch-profiles/{launchProfileId}/membership:
    POST:
      summary: Putlaunchprofilemembers
      description: Add/update users with given persona to launch profile membership.
      operationId: amazonWebServicesPutLaunchProfileMembers
  /2020-08-01/studios/{studioId}/streaming-session-backups:
    GET:
      summary: Liststreamingsessionbackups
      description: Lists the backups of a streaming session in a studio.
      operationId: amazonWebServicesListStreamingSessionBackups
  /2020-08-01/studios/{studioId}/membership:
    POST:
      summary: Putstudiomembers
      description: Add/update users with given persona to studio membership.
      operationId: amazonWebServicesPutStudioMembers
  /2020-08-01/tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Deletes the tags for a resource.
      operationId: amazonWebServicesUntagResource
  /2020-08-01/studios/{studioId}/streaming-sessions/{sessionId}/start:
    POST:
      summary: Startstreamingsession
      description: >-
        Transitions sessions from the STOPPED state into the READY state. The
        START_IN_PROGRESS state is the intermediate state between the STOPPED
        and READY states.
      operationId: amazonWebServicesStartStreamingSession
  /2020-08-01/studios/{studioId}/sso-configuration:
    PUT:
      summary: Startstudiossoconfigurationrepair
      description: >-
        Repairs the IAM Identity Center configuration for a given studio. If the
        studio has a valid IAM Identity Center configuration currently
        associated with it, this operation will fail with a validation error. If
        the studio does not have a valid IAM Identity Center configuration
        currently associated with it, then a new IAM Identity Center application
        is created for the studio and the studio is changed to the READY state.
        After the IAM Identity Center application is repaired, you must use the
        Amazon Nimble Studio console to add administrators and users to your
        studio.
      operationId: amazonWebServicesStartStudioSSOConfigurationRepair
  /2020-08-01/studios/{studioId}/streaming-sessions/{sessionId}/stop:
    POST:
      summary: Stopstreamingsession
      description: >-
        Transitions sessions from the READY state into the STOPPED state. The
        STOP_IN_PROGRESS state is the intermediate state between the READY and
        STOPPED states.
      operationId: amazonWebServicesStopStreamingSession
tags: []
