openapi: 3.1.0
info:
  title: omics
  description: >-
    <p>This is the <i>AWS HealthOmics API Reference</i>. For an introduction to
    the service, see <a
    href="https://docs.aws.amazon.com/omics/latest/dev/">What is AWS
    HealthOmics?</a> in the <i>AWS HealthOmics User Guide</i>.</p>
paths:
  /sequencestore/{sequenceStoreId}/upload/{uploadId}/abort:
    DELETE:
      summary: Abortmultipartreadsetupload
      description: ' Stops a multipart upload. '
      operationId: amazonWebServicesAbortMultipartReadSetUpload
  /share/{shareId}:
    GET:
      summary: Getshare
      description: ' Retrieves the metadata for a share. '
      operationId: amazonWebServicesGetShare
  /sequencestore/{sequenceStoreId}/readset/batch/delete:
    POST:
      summary: Batchdeletereadset
      description: Deletes one or more read sets.
      operationId: amazonWebServicesBatchDeleteReadSet
  /import/annotation/{jobId}:
    GET:
      summary: Getannotationimportjob
      description: Gets information about an annotation import job.
      operationId: amazonWebServicesGetAnnotationImportJob
  /run/{id}/cancel:
    POST:
      summary: Cancelrun
      description: Cancels a run.
      operationId: amazonWebServicesCancelRun
  /import/variant/{jobId}:
    GET:
      summary: Getvariantimportjob
      description: Gets information about a variant import job.
      operationId: amazonWebServicesGetVariantImportJob
  /sequencestore/{sequenceStoreId}/upload/{uploadId}/complete:
    POST:
      summary: Completemultipartreadsetupload
      description: ' Concludes a multipart upload once you have uploaded all the components. '
      operationId: amazonWebServicesCompleteMultipartReadSetUpload
  /annotationStore:
    POST:
      summary: Createannotationstore
      description: Creates an annotation store.
      operationId: amazonWebServicesCreateAnnotationStore
  /annotationStore/{name}/version:
    POST:
      summary: Createannotationstoreversion
      description: ' Creates a new version of an annotation store. '
      operationId: amazonWebServicesCreateAnnotationStoreVersion
  /sequencestore/{sequenceStoreId}/upload:
    POST:
      summary: Createmultipartreadsetupload
      description: ' Begins a multipart read set upload. '
      operationId: amazonWebServicesCreateMultipartReadSetUpload
  /referencestore:
    POST:
      summary: Createreferencestore
      description: Creates a reference store.
      operationId: amazonWebServicesCreateReferenceStore
  /runGroup:
    GET:
      summary: Listrungroups
      description: Retrieves a list of run groups.
      operationId: amazonWebServicesListRunGroups
  /sequencestore:
    POST:
      summary: Createsequencestore
      description: Creates a sequence store.
      operationId: amazonWebServicesCreateSequenceStore
  /share:
    POST:
      summary: Createshare
      description: ' Creates a share offer that can be accepted outside the account by a subscriber. The share is created by the owner and accepted by the principal subscriber. '
      operationId: amazonWebServicesCreateShare
  /variantStore:
    POST:
      summary: Createvariantstore
      description: Creates a variant store.
      operationId: amazonWebServicesCreateVariantStore
  /workflow:
    GET:
      summary: Listworkflows
      description: Retrieves a list of workflows.
      operationId: amazonWebServicesListWorkflows
  /annotationStore/{name}:
    POST:
      summary: Updateannotationstore
      description: Updates an annotation store.
      operationId: amazonWebServicesUpdateAnnotationStore
  /annotationStore/{name}/versions/delete:
    POST:
      summary: Deleteannotationstoreversions
      description: ' Deletes one or multiple versions of an annotation store. '
      operationId: amazonWebServicesDeleteAnnotationStoreVersions
  /referencestore/{referenceStoreId}/reference/{id}:
    GET:
      summary: Getreference
      description: Gets a reference file.
      operationId: amazonWebServicesGetReference
  /referencestore/{id}:
    GET:
      summary: Getreferencestore
      description: Gets information about a reference store.
      operationId: amazonWebServicesGetReferenceStore
  /run/{id}:
    GET:
      summary: Getrun
      description: Gets information about a workflow run.
      operationId: amazonWebServicesGetRun
  /runGroup/{id}:
    POST:
      summary: Updaterungroup
      description: Updates a run group.
      operationId: amazonWebServicesUpdateRunGroup
  /sequencestore/{id}:
    GET:
      summary: Getsequencestore
      description: Gets information about a sequence store.
      operationId: amazonWebServicesGetSequenceStore
  /variantStore/{name}:
    POST:
      summary: Updatevariantstore
      description: Updates a variant store.
      operationId: amazonWebServicesUpdateVariantStore
  /workflow/{id}:
    POST:
      summary: Updateworkflow
      description: Updates a workflow.
      operationId: amazonWebServicesUpdateWorkflow
  /annotationStore/{name}/version/{versionName}:
    POST:
      summary: Updateannotationstoreversion
      description: ' Updates the description of an annotation store version. '
      operationId: amazonWebServicesUpdateAnnotationStoreVersion
  /sequencestore/{sequenceStoreId}/readset/{id}:
    GET:
      summary: Getreadset
      description: Gets a file from a read set.
      operationId: amazonWebServicesGetReadSet
  /sequencestore/{sequenceStoreId}/activationjob/{id}:
    GET:
      summary: Getreadsetactivationjob
      description: Gets information about a read set activation job.
      operationId: amazonWebServicesGetReadSetActivationJob
  /sequencestore/{sequenceStoreId}/exportjob/{id}:
    GET:
      summary: Getreadsetexportjob
      description: Gets information about a read set export job.
      operationId: amazonWebServicesGetReadSetExportJob
  /sequencestore/{sequenceStoreId}/importjob/{id}:
    GET:
      summary: Getreadsetimportjob
      description: Gets information about a read set import job.
      operationId: amazonWebServicesGetReadSetImportJob
  /sequencestore/{sequenceStoreId}/readset/{id}/metadata:
    GET:
      summary: Getreadsetmetadata
      description: Gets details about a read set.
      operationId: amazonWebServicesGetReadSetMetadata
  /referencestore/{referenceStoreId}/importjob/{id}:
    GET:
      summary: Getreferenceimportjob
      description: Gets information about a reference import job.
      operationId: amazonWebServicesGetReferenceImportJob
  /referencestore/{referenceStoreId}/reference/{id}/metadata:
    GET:
      summary: Getreferencemetadata
      description: Gets information about a genome reference's metadata.
      operationId: amazonWebServicesGetReferenceMetadata
  /run/{id}/task/{taskId}:
    GET:
      summary: Getruntask
      description: Gets information about a workflow run task.
      operationId: amazonWebServicesGetRunTask
  /import/annotations:
    POST:
      summary: Listannotationimportjobs
      description: Retrieves a list of annotation import jobs.
      operationId: amazonWebServicesListAnnotationImportJobs
  /annotationStore/{name}/versions:
    POST:
      summary: Listannotationstoreversions
      description: ' Lists the versions of an annotation store. '
      operationId: amazonWebServicesListAnnotationStoreVersions
  /annotationStores:
    POST:
      summary: Listannotationstores
      description: Retrieves a list of annotation stores.
      operationId: amazonWebServicesListAnnotationStores
  /sequencestore/{sequenceStoreId}/uploads:
    POST:
      summary: Listmultipartreadsetuploads
      description: ' Lists multipart read set uploads and for in progress uploads. Once the upload is completed, a read set is created and the upload will no longer be returned in the respone. '
      operationId: amazonWebServicesListMultipartReadSetUploads
  /sequencestore/{sequenceStoreId}/activationjobs:
    POST:
      summary: Listreadsetactivationjobs
      description: Retrieves a list of read set activation jobs.
      operationId: amazonWebServicesListReadSetActivationJobs
  /sequencestore/{sequenceStoreId}/exportjobs:
    POST:
      summary: Listreadsetexportjobs
      description: Retrieves a list of read set export jobs.
      operationId: amazonWebServicesListReadSetExportJobs
  /sequencestore/{sequenceStoreId}/importjobs:
    POST:
      summary: Listreadsetimportjobs
      description: Retrieves a list of read set import jobs.
      operationId: amazonWebServicesListReadSetImportJobs
  /sequencestore/{sequenceStoreId}/upload/{uploadId}/parts:
    POST:
      summary: Listreadsetuploadparts
      description: ' This operation will list all parts in a requested multipart upload for a sequence store. '
      operationId: amazonWebServicesListReadSetUploadParts
  /sequencestore/{sequenceStoreId}/readsets:
    POST:
      summary: Listreadsets
      description: Retrieves a list of read sets.
      operationId: amazonWebServicesListReadSets
  /referencestore/{referenceStoreId}/importjobs:
    POST:
      summary: Listreferenceimportjobs
      description: Retrieves a list of reference import jobs.
      operationId: amazonWebServicesListReferenceImportJobs
  /referencestores:
    POST:
      summary: Listreferencestores
      description: Retrieves a list of reference stores.
      operationId: amazonWebServicesListReferenceStores
  /referencestore/{referenceStoreId}/references:
    POST:
      summary: Listreferences
      description: Retrieves a list of references.
      operationId: amazonWebServicesListReferences
  /run/{id}/task:
    GET:
      summary: Listruntasks
      description: Retrieves a list of tasks for a run.
      operationId: amazonWebServicesListRunTasks
  /run:
    POST:
      summary: Startrun
      description: >-
        Starts a workflow run. To duplicate a run, specify the run's ID and a
        role ARN. The remaining parameters are copied from the previous run. The
        total number of runs in your account is subject to a quota per Region.
        To avoid needing to delete runs manually, you can set the retention mode
        to REMOVE. Runs with this setting are deleted automatically when the run
        quoata is exceeded.
      operationId: amazonWebServicesStartRun
  /sequencestores:
    POST:
      summary: Listsequencestores
      description: Retrieves a list of sequence stores.
      operationId: amazonWebServicesListSequenceStores
  /shares:
    POST:
      summary: Listshares
      description: ' Lists all shares associated with an account. '
      operationId: amazonWebServicesListShares
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes tags from a resource.
      operationId: amazonWebServicesUntagResource
  /import/variants:
    POST:
      summary: Listvariantimportjobs
      description: Retrieves a list of variant import jobs.
      operationId: amazonWebServicesListVariantImportJobs
  /variantStores:
    POST:
      summary: Listvariantstores
      description: Retrieves a list of variant stores.
      operationId: amazonWebServicesListVariantStores
  /import/annotation:
    POST:
      summary: Startannotationimportjob
      description: Starts an annotation import job.
      operationId: amazonWebServicesStartAnnotationImportJob
  /sequencestore/{sequenceStoreId}/activationjob:
    POST:
      summary: Startreadsetactivationjob
      description: >-
        Activates an archived read set. To reduce storage charges, Amazon Omics
        archives unused read sets after 30 days.
      operationId: amazonWebServicesStartReadSetActivationJob
  /sequencestore/{sequenceStoreId}/exportjob:
    POST:
      summary: Startreadsetexportjob
      description: Exports a read set to Amazon S3.
      operationId: amazonWebServicesStartReadSetExportJob
  /sequencestore/{sequenceStoreId}/importjob:
    POST:
      summary: Startreadsetimportjob
      description: Starts a read set import job.
      operationId: amazonWebServicesStartReadSetImportJob
  /referencestore/{referenceStoreId}/importjob:
    POST:
      summary: Startreferenceimportjob
      description: Starts a reference import job.
      operationId: amazonWebServicesStartReferenceImportJob
  /import/variant:
    POST:
      summary: Startvariantimportjob
      description: Starts a variant import job.
      operationId: amazonWebServicesStartVariantImportJob
  /sequencestore/{sequenceStoreId}/upload/{uploadId}/part:
    PUT:
      summary: Uploadreadsetpart
      description: ' This operation uploads a specific part of a read set. If you upload a new part using a previously used part number, the previously uploaded part will be overwritten. '
      operationId: amazonWebServicesUploadReadSetPart
tags: []
