openapi: 3.1.0
info:
  title: osis
  description: >-
    <p>Use the Amazon OpenSearch Ingestion API to create and manage ingestion
    pipelines. OpenSearch Ingestion is a fully managed data collector that
    delivers real-time log and trace data to OpenSearch Service domains. For
    more information, see <a
    href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/ingestion.html">Getting
    data into your cluster using OpenSearch Ingestion</a>.</p>
paths:
  /2022-01-01/osis/createPipeline:
    POST:
      summary: Createpipeline
      description: >-
        Creates an OpenSearch Ingestion pipeline. For more information, see
        Creating Amazon OpenSearch Ingestion pipelines.
      operationId: amazonWebServicesCreatePipeline
  /2022-01-01/osis/deletePipeline/{PipelineName}:
    DELETE:
      summary: Deletepipeline
      description: >-
        Deletes an OpenSearch Ingestion pipeline. For more information, see
        Deleting Amazon OpenSearch Ingestion pipelines.
      operationId: amazonWebServicesDeletePipeline
  /2022-01-01/osis/getPipeline/{PipelineName}:
    GET:
      summary: Getpipeline
      description: Retrieves information about an OpenSearch Ingestion pipeline.
      operationId: amazonWebServicesGetPipeline
  /2022-01-01/osis/getPipelineBlueprint/{BlueprintName}:
    GET:
      summary: Getpipelineblueprint
      description: >-
        Retrieves information about a specific blueprint for OpenSearch
        Ingestion. Blueprints are templates for the configuration needed for a
        CreatePipeline request. For more information, see Using blueprints to
        create a pipeline.
      operationId: amazonWebServicesGetPipelineBlueprint
  /2022-01-01/osis/getPipelineChangeProgress/{PipelineName}:
    GET:
      summary: Getpipelinechangeprogress
      description: >-
        Returns progress information for the current change happening on an
        OpenSearch Ingestion pipeline. Currently, this operation only returns
        information when a pipeline is being created. For more information, see
        Tracking the status of pipeline creation.
      operationId: amazonWebServicesGetPipelineChangeProgress
  /2022-01-01/osis/listPipelineBlueprints:
    POST:
      summary: Listpipelineblueprints
      description: >-
        Retrieves a list of all available blueprints for Data Prepper. For more
        information, see Using blueprints to create a pipeline.
      operationId: amazonWebServicesListPipelineBlueprints
  /2022-01-01/osis/listPipelines:
    GET:
      summary: Listpipelines
      description: >-
        Lists all OpenSearch Ingestion pipelines in the current Amazon Web
        Services account and Region. For more information, see Viewing Amazon
        OpenSearch Ingestion pipelines.
      operationId: amazonWebServicesListPipelines
  /2022-01-01/osis/listTagsForResource/:
    GET:
      summary: Listtagsforresource
      description: >-
        Lists all resource tags associated with an OpenSearch Ingestion
        pipeline. For more information, see Tagging Amazon OpenSearch Ingestion
        pipelines.
      operationId: amazonWebServicesListTagsForResource
  /2022-01-01/osis/startPipeline/{PipelineName}:
    PUT:
      summary: Startpipeline
      description: >-
        Starts an OpenSearch Ingestion pipeline. For more information, see
        Starting an OpenSearch Ingestion pipeline.
      operationId: amazonWebServicesStartPipeline
  /2022-01-01/osis/stopPipeline/{PipelineName}:
    PUT:
      summary: Stoppipeline
      description: >-
        Stops an OpenSearch Ingestion pipeline. For more information, see
        Stopping an OpenSearch Ingestion pipeline.
      operationId: amazonWebServicesStopPipeline
  /2022-01-01/osis/tagResource/:
    POST:
      summary: Tagresource
      description: >-
        Tags an OpenSearch Ingestion pipeline. For more information, see Tagging
        Amazon OpenSearch Ingestion pipelines.
      operationId: amazonWebServicesTagResource
  /2022-01-01/osis/untagResource/:
    POST:
      summary: Untagresource
      description: >-
        Removes one or more tags from an OpenSearch Ingestion pipeline. For more
        information, see Tagging Amazon OpenSearch Ingestion pipelines.
      operationId: amazonWebServicesUntagResource
  /2022-01-01/osis/updatePipeline/{PipelineName}:
    PUT:
      summary: Updatepipeline
      description: >-
        Updates an OpenSearch Ingestion pipeline. For more information, see
        Updating Amazon OpenSearch Ingestion pipelines.
      operationId: amazonWebServicesUpdatePipeline
  /2022-01-01/osis/validatePipeline:
    POST:
      summary: Validatepipeline
      description: >-
        Checks whether an OpenSearch Ingestion pipeline configuration is valid
        prior to creation. For more information, see Creating Amazon OpenSearch
        Ingestion pipelines.
      operationId: amazonWebServicesValidatePipeline
tags: []
