openapi: 3.1.0
info:
  title: outposts
  description: >-
    <p>Amazon Web Services Outposts is a fully managed service that extends
    Amazon Web Services infrastructure, APIs, and tools to customer premises. By
    providing local access to Amazon Web Services managed infrastructure, Amazon
    Web Services Outposts enables customers to build and run applications on
    premises using the same programming interfaces as in Amazon Web Services
    Regions, while using local compute and storage resources for lower latency
    and local data processing needs.</p>
paths:
  /orders/{OrderId}/cancel:
    POST:
      summary: Cancelorder
      description: Cancels the specified order for an Outpost.
      operationId: amazonWebServicesCancelOrder
  /orders:
    POST:
      summary: Createorder
      description: Creates an order for an Outpost.
      operationId: amazonWebServicesCreateOrder
  /outposts:
    GET:
      summary: Listoutposts
      description: >-
        Lists the Outposts for your Amazon Web Services account. Use filters to
        return specific results. If you specify multiple filters, the results
        include only the resources that match all of the specified filters. For
        a filter where you can specify multiple values, the results include
        items that match any of the values that you specify for the filter.
      operationId: amazonWebServicesListOutposts
  /sites:
    GET:
      summary: Listsites
      description: >-
        Lists the Outpost sites for your Amazon Web Services account. Use
        filters to return specific results. Use filters to return specific
        results. If you specify multiple filters, the results include only the
        resources that match all of the specified filters. For a filter where
        you can specify multiple values, the results include items that match
        any of the values that you specify for the filter.
      operationId: amazonWebServicesListSites
  /outposts/{OutpostId}:
    PATCH:
      summary: Updateoutpost
      description: ' Updates an Outpost. '
      operationId: amazonWebServicesUpdateOutpost
  /sites/{SiteId}:
    PATCH:
      summary: Updatesite
      description: Updates the specified site.
      operationId: amazonWebServicesUpdateSite
  /catalog/item/{CatalogItemId}:
    GET:
      summary: Getcatalogitem
      description: Gets information about the specified catalog item.
      operationId: amazonWebServicesGetCatalogItem
  /connections/{ConnectionId}:
    GET:
      summary: Getconnection
      description: '  Amazon Web Services uses this action to install Outpost servers.   Gets information about the specified connection.   Use CloudTrail to monitor this action or Amazon Web Services managed policy for Amazon Web Services Outposts to secure it. For more information, see  Amazon Web Services managed policies for Amazon Web Services Outposts and  Logging Amazon Web Services Outposts API calls with Amazon Web Services CloudTrail in the Amazon Web Services Outposts User Guide. '
      operationId: amazonWebServicesGetConnection
  /orders/{OrderId}:
    GET:
      summary: Getorder
      description: Gets information about the specified order.
      operationId: amazonWebServicesGetOrder
  /outposts/{OutpostId}/instanceTypes:
    GET:
      summary: Getoutpostinstancetypes
      description: Gets the instance types for the specified Outpost.
      operationId: amazonWebServicesGetOutpostInstanceTypes
  /sites/{SiteId}/address:
    PUT:
      summary: Updatesiteaddress
      description: >-
        Updates the address of the specified site. You can't update a site
        address if there is an order in progress. You must wait for the order to
        complete or cancel the order. You can update the operating address
        before you place an order at the site, or after all Outposts that belong
        to the site have been deactivated.
      operationId: amazonWebServicesUpdateSiteAddress
  /outposts/{OutpostId}/assets:
    GET:
      summary: Listassets
      description: >-
        Lists the hardware assets for the specified Outpost. Use filters to
        return specific results. If you specify multiple filters, the results
        include only the resources that match all of the specified filters. For
        a filter where you can specify multiple values, the results include
        items that match any of the values that you specify for the filter.
      operationId: amazonWebServicesListAssets
  /catalog/items:
    GET:
      summary: Listcatalogitems
      description: >-
        Lists the items in the catalog. Use filters to return specific results.
        If you specify multiple filters, the results include only the resources
        that match all of the specified filters. For a filter where you can
        specify multiple values, the results include items that match any of the
        values that you specify for the filter.
      operationId: amazonWebServicesListCatalogItems
  /list-orders:
    GET:
      summary: Listorders
      description: Lists the Outpost orders for your Amazon Web Services account.
      operationId: amazonWebServicesListOrders
  /tags/{ResourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes tags from the specified resource.
      operationId: amazonWebServicesUntagResource
  /connections:
    POST:
      summary: Startconnection
      description: '  Amazon Web Services uses this action to install Outpost servers.   Starts the connection required for Outpost server installation.   Use CloudTrail to monitor this action or Amazon Web Services managed policy for Amazon Web Services Outposts to secure it. For more information, see  Amazon Web Services managed policies for Amazon Web Services Outposts and  Logging Amazon Web Services Outposts API calls with Amazon Web Services CloudTrail in the Amazon Web Services Outposts User Guide. '
      operationId: amazonWebServicesStartConnection
  /sites/{SiteId}/rackPhysicalProperties:
    PATCH:
      summary: Updatesiterackphysicalproperties
      description: >-
        Update the physical and logistical details for a rack at a site. For
        more information about hardware requirements for racks, see Network
        readiness checklist in the Amazon Web Services Outposts User Guide.  To
        update a rack at a site with an order of IN_PROGRESS, you must wait for
        the order to complete or cancel the order.
      operationId: amazonWebServicesUpdateSiteRackPhysicalProperties
tags: []
