openapi: 3.1.0
info:
  title: panorama
  description: >-
    <p><fullname>AWS Panorama</fullname> <p> <b>Overview</b> </p> <p>This is the
    <i>AWS Panorama API Reference</i>. For an introduction to the service, see
    <a
    href="https://docs.aws.amazon.com/panorama/latest/dev/panorama-welcome.html">What
    is AWS Panorama?</a> in the <i>AWS Panorama Developer Guide</i>.</p></p>
paths:
  /application-instances:
    GET:
      summary: Listapplicationinstances
      description: Returns a list of application instances.
      operationId: amazonWebServicesListApplicationInstances
  /jobs:
    GET:
      summary: Listdevicesjobs
      description: Returns a list of jobs.
      operationId: amazonWebServicesListDevicesJobs
  /packages/template-job:
    GET:
      summary: Listnodefromtemplatejobs
      description: Returns a list of camera stream node jobs.
      operationId: amazonWebServicesListNodeFromTemplateJobs
  /packages:
    GET:
      summary: Listpackages
      description: Returns a list of packages.
      operationId: amazonWebServicesListPackages
  /packages/import-jobs:
    GET:
      summary: Listpackageimportjobs
      description: Returns a list of package import jobs.
      operationId: amazonWebServicesListPackageImportJobs
  /devices/{DeviceId}:
    PUT:
      summary: Updatedevicemetadata
      description: Updates a device's metadata.
      operationId: amazonWebServicesUpdateDeviceMetadata
  /packages/{PackageId}:
    DELETE:
      summary: Deletepackage
      description: >-
        Deletes a package.  To delete a package, you need permission to call
        s3:DeleteObject in addition to permissions for the AWS Panorama API. 
      operationId: amazonWebServicesDeletePackage
  /packages/{PackageId}/versions/{PackageVersion}/patch/{PatchVersion}:
    PUT:
      summary: Registerpackageversion
      description: Registers a package version.
      operationId: amazonWebServicesRegisterPackageVersion
  /application-instances/{ApplicationInstanceId}:
    DELETE:
      summary: Removeapplicationinstance
      description: Removes an application instance.
      operationId: amazonWebServicesRemoveApplicationInstance
  /application-instances/{ApplicationInstanceId}/details:
    GET:
      summary: Describeapplicationinstancedetails
      description: >-
        Returns information about an application instance's configuration
        manifest.
      operationId: amazonWebServicesDescribeApplicationInstanceDetails
  /jobs/{JobId}:
    GET:
      summary: Describedevicejob
      description: Returns information about a device job.
      operationId: amazonWebServicesDescribeDeviceJob
  /nodes/{NodeId}:
    GET:
      summary: Describenode
      description: Returns information about a node.
      operationId: amazonWebServicesDescribeNode
  /packages/template-job/{JobId}:
    GET:
      summary: Describenodefromtemplatejob
      description: Returns information about a job to create a camera stream node.
      operationId: amazonWebServicesDescribeNodeFromTemplateJob
  /packages/metadata/{PackageId}:
    GET:
      summary: Describepackage
      description: Returns information about a package.
      operationId: amazonWebServicesDescribePackage
  /packages/import-jobs/{JobId}:
    GET:
      summary: Describepackageimportjob
      description: Returns information about a package import job.
      operationId: amazonWebServicesDescribePackageImportJob
  /packages/metadata/{PackageId}/versions/{PackageVersion}:
    GET:
      summary: Describepackageversion
      description: Returns information about a package version.
      operationId: amazonWebServicesDescribePackageVersion
  /application-instances/{ApplicationInstanceId}/package-dependencies:
    GET:
      summary: Listapplicationinstancedependencies
      description: Returns a list of application instance dependencies.
      operationId: amazonWebServicesListApplicationInstanceDependencies
  /application-instances/{ApplicationInstanceId}/node-instances:
    GET:
      summary: Listapplicationinstancenodeinstances
      description: Returns a list of application node instances.
      operationId: amazonWebServicesListApplicationInstanceNodeInstances
  /devices:
    POST:
      summary: Provisiondevice
      description: >-
        Creates a device and returns a configuration archive. The configuration
        archive is a ZIP file that contains a provisioning certificate that is
        valid for 5 minutes. Name the configuration archive
        certificates-omni_device-name.zip and transfer it to the device within 5
        minutes. Use the included USB storage device and connect it to the USB
        3.0 port next to the HDMI output.
      operationId: amazonWebServicesProvisionDevice
  /nodes:
    GET:
      summary: Listnodes
      description: Returns a list of nodes.
      operationId: amazonWebServicesListNodes
  /tags/{ResourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes tags from a resource.
      operationId: amazonWebServicesUntagResource
  /application-instances/{ApplicationInstanceId}/node-signals:
    PUT:
      summary: Signalapplicationinstancenodeinstances
      description: Signal camera nodes to stop or resume.
      operationId: amazonWebServicesSignalApplicationInstanceNodeInstances
tags: []
