openapi: 3.1.0
info:
  title: pca-connector-ad
  description: >-
    <p>Amazon Web Services Private CA Connector for Active Directory creates a
    connector between Amazon Web Services Private CA and Active Directory (AD)
    that enables you to provision security certificates for AD signed by a
    private CA that you own. For more information, see <a
    href="https://docs.aws.amazon.com/privateca/latest/userguide/ad-connector.html">Amazon
    Web Services Private CA Connector for Active Directory</a>.</p>
paths:
  /connectors:
    GET:
      summary: Listconnectors
      description: >-
        Lists the connectors that you created by using the
        https://docs.aws.amazon.com/pca-connector-ad/latest/APIReference/API_CreateConnector
        action.
      operationId: amazonWebServicesListConnectors
  /directoryRegistrations:
    GET:
      summary: Listdirectoryregistrations
      description: >-
        Lists the directory registrations that you created by using the
        https://docs.aws.amazon.com/pca-connector-ad/latest/APIReference/API_CreateDirectoryRegistration
        action.
      operationId: amazonWebServicesListDirectoryRegistrations
  /directoryRegistrations/{DirectoryRegistrationArn}/servicePrincipalNames/{ConnectorArn}:
    GET:
      summary: Getserviceprincipalname
      description: >-
        Lists the service principal name that the connector uses to authenticate
        with Active Directory.
      operationId: amazonWebServicesGetServicePrincipalName
  /templates:
    GET:
      summary: Listtemplates
      description: Lists the templates, if any, that are associated with a connector.
      operationId: amazonWebServicesListTemplates
  /templates/{TemplateArn}/accessControlEntries:
    GET:
      summary: Listtemplategroupaccesscontrolentries
      description: 'Lists group access control entries you created. '
      operationId: amazonWebServicesListTemplateGroupAccessControlEntries
  /connectors/{ConnectorArn}:
    GET:
      summary: Getconnector
      description: >-
        Lists information about your connector. You specify the connector on
        input by its ARN (Amazon Resource Name). 
      operationId: amazonWebServicesGetConnector
  /directoryRegistrations/{DirectoryRegistrationArn}:
    GET:
      summary: Getdirectoryregistration
      description: A structure that contains information about your directory registration.
      operationId: amazonWebServicesGetDirectoryRegistration
  /templates/{TemplateArn}:
    PATCH:
      summary: Updatetemplate
      description: >-
        Update template configuration to define the information included in
        certificates.
      operationId: amazonWebServicesUpdateTemplate
  /templates/{TemplateArn}/accessControlEntries/{GroupSecurityIdentifier}:
    PATCH:
      summary: Updatetemplategroupaccesscontrolentry
      description: >-
        Update a group access control entry you created using
        CreateTemplateGroupAccessControlEntry. 
      operationId: amazonWebServicesUpdateTemplateGroupAccessControlEntry
  /directoryRegistrations/{DirectoryRegistrationArn}/servicePrincipalNames:
    GET:
      summary: Listserviceprincipalnames
      description: >-
        Lists the service principal names that the connector uses to
        authenticate with Active Directory.
      operationId: amazonWebServicesListServicePrincipalNames
  /tags/{ResourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes one or more tags from your resource.
      operationId: amazonWebServicesUntagResource
tags: []
