openapi: 3.1.0
info:
  title: personalize-events
  description: >-
    <p>Amazon Personalize can consume real-time user event data, such as
    <i>stream</i> or <i>click</i> data, and use it for model training either
    alone or combined with historical data. For more information see <a
    href="https://docs.aws.amazon.com/personalize/latest/dg/recording-item-interaction-events.html">Recording
    item interaction events</a>.</p>
paths:
  /action-interactions:
    POST:
      summary: Putactioninteractions
      description: >-
        Records action interaction event data. An action interaction event is an
        interaction between a user and an action. For example, a user taking an
        action, such a enrolling in a membership program or downloading your
        app.  For more information about recording action interactions, see
        Recording action interaction events. For more information about actions
        in an Actions dataset, see Actions dataset.
      operationId: amazonWebServicesPutActionInteractions
  /actions:
    POST:
      summary: Putactions
      description: >-
        Adds one or more actions to an Actions dataset. For more information see
        Importing actions individually. 
      operationId: amazonWebServicesPutActions
  /events:
    POST:
      summary: Putevents
      description: >-
        Records item interaction event data. For more information see Recording
        item interaction events.
      operationId: amazonWebServicesPutEvents
  /items:
    POST:
      summary: Putitems
      description: >-
        Adds one or more items to an Items dataset. For more information see
        Importing items individually. 
      operationId: amazonWebServicesPutItems
  /users:
    POST:
      summary: Putusers
      description: >-
        Adds one or more users to a Users dataset. For more information see
        Importing users individually.
      operationId: amazonWebServicesPutUsers
tags: []
