openapi: 3.1.0
info:
  title: personalize
  description: >-
    <p>Amazon Personalize is a machine learning service that makes it easy to
    add individualized recommendations to customers.</p>
paths:
  /:
    POST:
      summary: Updaterecommender
      description: >-
        Updates the recommender to modify the recommender configuration. If you
        update the recommender to modify the columns used in training, Amazon
        Personalize automatically starts a full retraining of the models backing
        your recommender. While the update completes, you can still get
        recommendations from the recommender. The recommender uses the previous
        configuration until the update completes. To track the status of this
        update, use the latestRecommenderUpdate returned in the
        DescribeRecommender operation. 
      operationId: amazonWebServicesUpdateRecommender
tags: []
