openapi: 3.1.0
info:
  title: pinpoint
  description: <p>Doc Engage API - Amazon Pinpoint API</p>
paths:
  /v1/apps:
    GET:
      summary: Getapps
      description: >-
        Retrieves information about all the applications that are associated
        with your Amazon Pinpoint account.
      operationId: amazonWebServicesGetApps
  /v1/apps/{application-id}/campaigns:
    GET:
      summary: Getcampaigns
      description: >-
        Retrieves information about the status, configuration, and other
        settings for all the campaigns that are associated with an application.
      operationId: amazonWebServicesGetCampaigns
  /v1/templates/{template-name}/email:
    PUT:
      summary: Updateemailtemplate
      description: >-
        Updates an existing message template for messages that are sent through
        the email channel.
      operationId: amazonWebServicesUpdateEmailTemplate
  /v1/apps/{application-id}/jobs/export:
    GET:
      summary: Getexportjobs
      description: >-
        Retrieves information about the status and settings of all the export
        jobs for an application.
      operationId: amazonWebServicesGetExportJobs
  /v1/apps/{application-id}/jobs/import:
    GET:
      summary: Getimportjobs
      description: >-
        Retrieves information about the status and settings of all the import
        jobs for an application.
      operationId: amazonWebServicesGetImportJobs
  /v1/templates/{template-name}/inapp:
    PUT:
      summary: Updateinapptemplate
      description: >-
        Updates an existing message template for messages sent through the
        in-app message channel.
      operationId: amazonWebServicesUpdateInAppTemplate
  /v1/apps/{application-id}/journeys:
    GET:
      summary: Listjourneys
      description: >-
        Retrieves information about the status, configuration, and other
        settings for all the journeys that are associated with an application.
      operationId: amazonWebServicesListJourneys
  /v1/templates/{template-name}/push:
    PUT:
      summary: Updatepushtemplate
      description: >-
        Updates an existing message template for messages that are sent through
        a push notification channel.
      operationId: amazonWebServicesUpdatePushTemplate
  /v1/recommenders:
    GET:
      summary: Getrecommenderconfigurations
      description: >-
        Retrieves information about all the recommender model configurations
        that are associated with your Amazon Pinpoint account.
      operationId: amazonWebServicesGetRecommenderConfigurations
  /v1/apps/{application-id}/segments:
    GET:
      summary: Getsegments
      description: >-
        Retrieves information about the configuration, dimension, and other
        settings for all the segments that are associated with an application.
      operationId: amazonWebServicesGetSegments
  /v1/templates/{template-name}/sms:
    PUT:
      summary: Updatesmstemplate
      description: >-
        Updates an existing message template for messages that are sent through
        the SMS channel.
      operationId: amazonWebServicesUpdateSmsTemplate
  /v1/templates/{template-name}/voice:
    PUT:
      summary: Updatevoicetemplate
      description: >-
        Updates an existing message template for messages that are sent through
        the voice channel.
      operationId: amazonWebServicesUpdateVoiceTemplate
  /v1/apps/{application-id}/channels/adm:
    PUT:
      summary: Updateadmchannel
      description: >-
        Enables the ADM channel for an application or updates the status and
        settings of the ADM channel for an application.
      operationId: amazonWebServicesUpdateAdmChannel
  /v1/apps/{application-id}/channels/apns:
    PUT:
      summary: Updateapnschannel
      description: >-
        Enables the APNs channel for an application or updates the status and
        settings of the APNs channel for an application.
      operationId: amazonWebServicesUpdateApnsChannel
  /v1/apps/{application-id}/channels/apns_sandbox:
    PUT:
      summary: Updateapnssandboxchannel
      description: >-
        Enables the APNs sandbox channel for an application or updates the
        status and settings of the APNs sandbox channel for an application.
      operationId: amazonWebServicesUpdateApnsSandboxChannel
  /v1/apps/{application-id}/channels/apns_voip:
    PUT:
      summary: Updateapnsvoipchannel
      description: >-
        Enables the APNs VoIP channel for an application or updates the status
        and settings of the APNs VoIP channel for an application.
      operationId: amazonWebServicesUpdateApnsVoipChannel
  /v1/apps/{application-id}/channels/apns_voip_sandbox:
    PUT:
      summary: Updateapnsvoipsandboxchannel
      description: >-
        Enables the APNs VoIP sandbox channel for an application or updates the
        status and settings of the APNs VoIP sandbox channel for an application.
      operationId: amazonWebServicesUpdateApnsVoipSandboxChannel
  /v1/apps/{application-id}:
    GET:
      summary: Getapp
      description: Retrieves information about an application.
      operationId: amazonWebServicesGetApp
  /v1/apps/{application-id}/channels/baidu:
    PUT:
      summary: Updatebaiduchannel
      description: >-
        Enables the Baidu channel for an application or updates the status and
        settings of the Baidu channel for an application.
      operationId: amazonWebServicesUpdateBaiduChannel
  /v1/apps/{application-id}/campaigns/{campaign-id}:
    PUT:
      summary: Updatecampaign
      description: Updates the configuration and other settings for a campaign.
      operationId: amazonWebServicesUpdateCampaign
  /v1/apps/{application-id}/channels/email:
    PUT:
      summary: Updateemailchannel
      description: >-
        Enables the email channel for an application or updates the status and
        settings of the email channel for an application.
      operationId: amazonWebServicesUpdateEmailChannel
  /v1/apps/{application-id}/endpoints/{endpoint-id}:
    PUT:
      summary: Updateendpoint
      description: >-
        Creates a new endpoint for an application or updates the settings and
        attributes of an existing endpoint for an application. You can also use
        this operation to define custom attributes for an endpoint. If an update
        includes one or more values for a custom attribute, Amazon Pinpoint
        replaces (overwrites) any existing values with the new values.
      operationId: amazonWebServicesUpdateEndpoint
  /v1/apps/{application-id}/eventstream:
    POST:
      summary: Puteventstream
      description: >-
        Creates a new event stream for an application or updates the settings of
        an existing event stream for an application.
      operationId: amazonWebServicesPutEventStream
  /v1/apps/{application-id}/channels/gcm:
    PUT:
      summary: Updategcmchannel
      description: >-
        Enables the GCM channel for an application or updates the status and
        settings of the GCM channel for an application.
      operationId: amazonWebServicesUpdateGcmChannel
  /v1/apps/{application-id}/journeys/{journey-id}:
    PUT:
      summary: Updatejourney
      description: Updates the configuration and other settings for a journey.
      operationId: amazonWebServicesUpdateJourney
  /v1/recommenders/{recommender-id}:
    PUT:
      summary: Updaterecommenderconfiguration
      description: Updates an Amazon Pinpoint configuration for a recommender model.
      operationId: amazonWebServicesUpdateRecommenderConfiguration
  /v1/apps/{application-id}/segments/{segment-id}:
    PUT:
      summary: Updatesegment
      description: >-
        Creates a new segment for an application or updates the configuration,
        dimension, and other settings for an existing segment that's associated
        with an application.
      operationId: amazonWebServicesUpdateSegment
  /v1/apps/{application-id}/channels/sms:
    PUT:
      summary: Updatesmschannel
      description: >-
        Enables the SMS channel for an application or updates the status and
        settings of the SMS channel for an application.
      operationId: amazonWebServicesUpdateSmsChannel
  /v1/apps/{application-id}/users/{user-id}:
    GET:
      summary: Getuserendpoints
      description: >-
        Retrieves information about all the endpoints that are associated with a
        specific user ID.
      operationId: amazonWebServicesGetUserEndpoints
  /v1/apps/{application-id}/channels/voice:
    PUT:
      summary: Updatevoicechannel
      description: >-
        Enables the voice channel for an application or updates the status and
        settings of the voice channel for an application.
      operationId: amazonWebServicesUpdateVoiceChannel
  /v1/apps/{application-id}/kpis/daterange/{kpi-name}:
    GET:
      summary: Getapplicationdaterangekpi
      description: >-
        Retrieves (queries) pre-aggregated data for a standard metric that
        applies to an application.
      operationId: amazonWebServicesGetApplicationDateRangeKpi
  /v1/apps/{application-id}/settings:
    PUT:
      summary: Updateapplicationsettings
      description: Updates the settings for an application.
      operationId: amazonWebServicesUpdateApplicationSettings
  /v1/apps/{application-id}/campaigns/{campaign-id}/activities:
    GET:
      summary: Getcampaignactivities
      description: Retrieves information about all the activities for a campaign.
      operationId: amazonWebServicesGetCampaignActivities
  /v1/apps/{application-id}/campaigns/{campaign-id}/kpis/daterange/{kpi-name}:
    GET:
      summary: Getcampaigndaterangekpi
      description: >-
        Retrieves (queries) pre-aggregated data for a standard metric that
        applies to a campaign.
      operationId: amazonWebServicesGetCampaignDateRangeKpi
  /v1/apps/{application-id}/campaigns/{campaign-id}/versions/{version}:
    GET:
      summary: Getcampaignversion
      description: >-
        Retrieves information about the status, configuration, and other
        settings for a specific version of a campaign.
      operationId: amazonWebServicesGetCampaignVersion
  /v1/apps/{application-id}/campaigns/{campaign-id}/versions:
    GET:
      summary: Getcampaignversions
      description: >-
        Retrieves information about the status, configuration, and other
        settings for all versions of a campaign.
      operationId: amazonWebServicesGetCampaignVersions
  /v1/apps/{application-id}/channels:
    GET:
      summary: Getchannels
      description: >-
        Retrieves information about the history and status of each channel for
        an application.
      operationId: amazonWebServicesGetChannels
  /v1/apps/{application-id}/jobs/export/{job-id}:
    GET:
      summary: Getexportjob
      description: >-
        Retrieves information about the status and settings of a specific export
        job for an application.
      operationId: amazonWebServicesGetExportJob
  /v1/apps/{application-id}/jobs/import/{job-id}:
    GET:
      summary: Getimportjob
      description: >-
        Retrieves information about the status and settings of a specific import
        job for an application.
      operationId: amazonWebServicesGetImportJob
  /v1/apps/{application-id}/endpoints/{endpoint-id}/inappmessages:
    GET:
      summary: Getinappmessages
      description: Retrieves the in-app messages targeted for the provided endpoint ID.
      operationId: amazonWebServicesGetInAppMessages
  /v1/apps/{application-id}/journeys/{journey-id}/kpis/daterange/{kpi-name}:
    GET:
      summary: Getjourneydaterangekpi
      description: >-
        Retrieves (queries) pre-aggregated data for a standard engagement metric
        that applies to a journey.
      operationId: amazonWebServicesGetJourneyDateRangeKpi
  /v1/apps/{application-id}/journeys/{journey-id}/activities/{journey-activity-id}/execution-metrics:
    GET:
      summary: Getjourneyexecutionactivitymetrics
      description: >-
        Retrieves (queries) pre-aggregated data for a standard execution metric
        that applies to a journey activity.
      operationId: amazonWebServicesGetJourneyExecutionActivityMetrics
  /v1/apps/{application-id}/journeys/{journey-id}/execution-metrics:
    GET:
      summary: Getjourneyexecutionmetrics
      description: >-
        Retrieves (queries) pre-aggregated data for a standard execution metric
        that applies to a journey.
      operationId: amazonWebServicesGetJourneyExecutionMetrics
  /v1/apps/{application-id}/journeys/{journey-id}/runs/{run-id}/activities/{journey-activity-id}/execution-metrics:
    GET:
      summary: Getjourneyrunexecutionactivitymetrics
      description: >-
        Retrieves (queries) pre-aggregated data for a standard run execution
        metric that applies to a journey activity.
      operationId: amazonWebServicesGetJourneyRunExecutionActivityMetrics
  /v1/apps/{application-id}/journeys/{journey-id}/runs/{run-id}/execution-metrics:
    GET:
      summary: Getjourneyrunexecutionmetrics
      description: >-
        Retrieves (queries) pre-aggregated data for a standard run execution
        metric that applies to a journey.
      operationId: amazonWebServicesGetJourneyRunExecutionMetrics
  /v1/apps/{application-id}/journeys/{journey-id}/runs:
    GET:
      summary: Getjourneyruns
      description: Provides information about the runs of a journey.
      operationId: amazonWebServicesGetJourneyRuns
  /v1/apps/{application-id}/segments/{segment-id}/jobs/export:
    GET:
      summary: Getsegmentexportjobs
      description: >-
        Retrieves information about the status and settings of the export jobs
        for a segment.
      operationId: amazonWebServicesGetSegmentExportJobs
  /v1/apps/{application-id}/segments/{segment-id}/jobs/import:
    GET:
      summary: Getsegmentimportjobs
      description: >-
        Retrieves information about the status and settings of the import jobs
        for a segment.
      operationId: amazonWebServicesGetSegmentImportJobs
  /v1/apps/{application-id}/segments/{segment-id}/versions/{version}:
    GET:
      summary: Getsegmentversion
      description: >-
        Retrieves information about the configuration, dimension, and other
        settings for a specific version of a segment that's associated with an
        application.
      operationId: amazonWebServicesGetSegmentVersion
  /v1/apps/{application-id}/segments/{segment-id}/versions:
    GET:
      summary: Getsegmentversions
      description: >-
        Retrieves information about the configuration, dimension, and other
        settings for all the versions of a specific segment that's associated
        with an application.
      operationId: amazonWebServicesGetSegmentVersions
  /v1/tags/{resource-arn}:
    DELETE:
      summary: Untagresource
      description: >-
        Removes one or more tags (keys and values) from an application,
        campaign, message template, or segment.
      operationId: amazonWebServicesUntagResource
  /v1/templates/{template-name}/{template-type}/versions:
    GET:
      summary: Listtemplateversions
      description: >-
        Retrieves information about all the versions of a specific message
        template.
      operationId: amazonWebServicesListTemplateVersions
  /v1/templates:
    GET:
      summary: Listtemplates
      description: >-
        Retrieves information about all the message templates that are
        associated with your Amazon Pinpoint account.
      operationId: amazonWebServicesListTemplates
  /v1/phone/number/validate:
    POST:
      summary: Phonenumbervalidate
      description: Retrieves information about a phone number.
      operationId: amazonWebServicesPhoneNumberValidate
  /v1/apps/{application-id}/events:
    POST:
      summary: Putevents
      description: >-
        Creates a new event to record for endpoints, or creates or updates
        endpoint data that existing events are associated with.
      operationId: amazonWebServicesPutEvents
  /v1/apps/{application-id}/attributes/{attribute-type}:
    PUT:
      summary: Removeattributes
      description: >-
        Removes one or more custom attributes, of the same attribute type, from
        the application. Existing endpoints still have the attributes but Amazon
        Pinpoint will stop capturing new or changed values for these attributes.
      operationId: amazonWebServicesRemoveAttributes
  /v1/apps/{application-id}/messages:
    POST:
      summary: Sendmessages
      description: Creates and sends a direct message.
      operationId: amazonWebServicesSendMessages
  /v1/apps/{application-id}/otp:
    POST:
      summary: Sendotpmessage
      description: Send an OTP message
      operationId: amazonWebServicesSendOTPMessage
  /v1/apps/{application-id}/users-messages:
    POST:
      summary: Sendusersmessages
      description: Creates and sends a message to a list of users.
      operationId: amazonWebServicesSendUsersMessages
  /v1/apps/{application-id}/endpoints:
    PUT:
      summary: Updateendpointsbatch
      description: >-
        Creates a new batch of endpoints for an application or updates the
        settings and attributes of a batch of existing endpoints for an
        application. You can also use this operation to define custom attributes
        for a batch of endpoints. If an update includes one or more values for a
        custom attribute, Amazon Pinpoint replaces (overwrites) any existing
        values with the new values.
      operationId: amazonWebServicesUpdateEndpointsBatch
  /v1/apps/{application-id}/journeys/{journey-id}/state:
    PUT:
      summary: Updatejourneystate
      description: Pause, resume or cancels (stops) a journey.
      operationId: amazonWebServicesUpdateJourneyState
  /v1/templates/{template-name}/{template-type}/active-version:
    PUT:
      summary: Updatetemplateactiveversion
      description: >-
        Changes the status of a specific version of a message template to
        active.
      operationId: amazonWebServicesUpdateTemplateActiveVersion
  /v1/apps/{application-id}/verify-otp:
    POST:
      summary: Verifyotpmessage
      description: Verify an OTP
      operationId: amazonWebServicesVerifyOTPMessage
tags: []
