openapi: 3.1.0
info:
  title: pipes
  description: >-
    <p>Amazon EventBridge Pipes connects event sources to targets. Pipes reduces
    the need for specialized knowledge and integration code when developing
    event driven architectures. This helps ensures consistency across your
    company’s applications. With Pipes, the target can be any available
    EventBridge target. To set up a pipe, you select the event source, add
    optional event filtering, define optional enrichment, and select the target
    for the event data. </p>
paths:
  /v1/pipes/{Name}:
    PUT:
      summary: Updatepipe
      description: >-
        Update an existing pipe. When you call UpdatePipe, EventBridge only the
        updates fields you have specified in the request; the rest remain
        unchanged. The exception to this is if you modify any Amazon Web
        Services-service specific fields in the SourceParameters,
        EnrichmentParameters, or TargetParameters objects. For example,
        DynamoDBStreamParameters or EventBridgeEventBusParameters. EventBridge
        updates the fields in these objects atomically as one and overrides
        existing values. This is by design, and means that if you don't specify
        an optional field in one of these Parameters objects, EventBridge sets
        that field to its system-default value during the update. For more
        information about pipes, see  Amazon EventBridge Pipes in the Amazon
        EventBridge User Guide.
      operationId: amazonWebServicesUpdatePipe
  /v1/pipes:
    GET:
      summary: Listpipes
      description: >-
        Get the pipes associated with this account. For more information about
        pipes, see Amazon EventBridge Pipes in the Amazon EventBridge User
        Guide.
      operationId: amazonWebServicesListPipes
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes one or more tags from the specified pipes.
      operationId: amazonWebServicesUntagResource
  /v1/pipes/{Name}/start:
    POST:
      summary: Startpipe
      description: Start an existing pipe.
      operationId: amazonWebServicesStartPipe
  /v1/pipes/{Name}/stop:
    POST:
      summary: Stoppipe
      description: Stop an existing pipe.
      operationId: amazonWebServicesStopPipe
tags: []
