openapi: 3.1.0
info:
  title: polly
  description: >-
    <p>Amazon Polly is a web service that makes it easy to synthesize speech
    from text.</p> <p>The Amazon Polly service provides API operations for
    synthesizing high-quality speech from plain text and Speech Synthesis Markup
    Language (SSML), along with managing pronunciations lexicons that enable you
    to get the best results for your application domain.</p>
paths:
  /v1/lexicons/{LexiconName}:
    PUT:
      summary: Putlexicon
      description: >-
        Stores a pronunciation lexicon in an Amazon Web Services Region. If a
        lexicon with the same name already exists in the region, it is
        overwritten by the new lexicon. Lexicon operations have eventual
        consistency, therefore, it might take some time before the lexicon is
        available to the SynthesizeSpeech operation. For more information, see
        Managing Lexicons.
      operationId: amazonWebServicesPutLexicon
  /v1/voices:
    GET:
      summary: Describevoices
      description: >-
        Returns the list of voices that are available for use when requesting
        speech synthesis. Each voice speaks a specified language, is either male
        or female, and is identified by an ID, which is the ASCII version of the
        voice name.  When synthesizing speech ( SynthesizeSpeech ), you provide
        the voice ID for the voice you want from the list of voices returned by
        DescribeVoices. For example, you want your news reader application to
        read news in a specific language, but giving a user the option to choose
        the voice. Using the DescribeVoices operation you can provide the user
        with a list of available voices to select from.  You can optionally
        specify a language code to filter the available voices. For example, if
        you specify en-US, the operation returns a list of all available US
        English voices.  This operation requires permissions to perform the
        polly:DescribeVoices action.
      operationId: amazonWebServicesDescribeVoices
  /v1/synthesisTasks/{TaskId}:
    GET:
      summary: Getspeechsynthesistask
      description: >-
        Retrieves a specific SpeechSynthesisTask object based on its TaskID.
        This object contains information about the given speech synthesis task,
        including the status of the task, and a link to the S3 bucket containing
        the output of the task.
      operationId: amazonWebServicesGetSpeechSynthesisTask
  /v1/lexicons:
    GET:
      summary: Listlexicons
      description: >-
        Returns a list of pronunciation lexicons stored in an Amazon Web
        Services Region. For more information, see Managing Lexicons.
      operationId: amazonWebServicesListLexicons
  /v1/synthesisTasks:
    POST:
      summary: Startspeechsynthesistask
      description: >-
        Allows the creation of an asynchronous synthesis task, by starting a new
        SpeechSynthesisTask. This operation requires all the standard
        information needed for speech synthesis, plus the name of an Amazon S3
        bucket for the service to store the output of the synthesis task and two
        optional parameters (OutputS3KeyPrefix and SnsTopicArn). Once the
        synthesis task is created, this operation will return a
        SpeechSynthesisTask object, which will include an identifier of this
        task as well as the current status. The SpeechSynthesisTask object is
        available for 72 hours after starting the asynchronous synthesis task.
      operationId: amazonWebServicesStartSpeechSynthesisTask
  /v1/speech:
    POST:
      summary: Synthesizespeech
      description: >-
        Synthesizes UTF-8 input, plain text or SSML, to a stream of bytes. SSML
        input must be valid, well-formed SSML. Some alphabets might not be
        available with all the voices (for example, Cyrillic might not be read
        at all by English voices) unless phoneme mapping is used. For more
        information, see How it Works.
      operationId: amazonWebServicesSynthesizeSpeech
tags: []
