openapi: 3.1.0
info:
  title: privatenetworks
  description: >-
    <p>Amazon Web Services Private 5G is a managed service that makes it easy to
    deploy, operate, and scale your own private mobile network at your
    on-premises location. Private 5G provides the pre-configured hardware and
    software for mobile networks, helps automate setup, and scales capacity on
    demand to support additional devices as needed.</p>
paths:
  /v1/orders/acknowledge:
    POST:
      summary: Acknowledgeorderreceipt
      description: Acknowledges that the specified network order was received.
      operationId: amazonWebServicesAcknowledgeOrderReceipt
  /v1/device-identifiers/activate:
    POST:
      summary: Activatedeviceidentifier
      description: Activates the specified device identifier.
      operationId: amazonWebServicesActivateDeviceIdentifier
  /v1/network-sites/activate:
    POST:
      summary: Activatenetworksite
      description: Activates the specified network site.
      operationId: amazonWebServicesActivateNetworkSite
  /v1/network-resources/configure:
    POST:
      summary: Configureaccesspoint
      description: >-
        Configures the specified network resource.   Use this action to specify
        the geographic position of the hardware. You must provide Certified
        Professional Installer (CPI) credentials in the request so that we can
        obtain spectrum grants. For more information, see Radio units in the
        Amazon Web Services Private 5G User Guide. 
      operationId: amazonWebServicesConfigureAccessPoint
  /v1/networks:
    POST:
      summary: Createnetwork
      description: Creates a network.
      operationId: amazonWebServicesCreateNetwork
  /v1/network-sites:
    POST:
      summary: Createnetworksite
      description: Creates a network site.
      operationId: amazonWebServicesCreateNetworkSite
  /v1/device-identifiers/deactivate:
    POST:
      summary: Deactivatedeviceidentifier
      description: Deactivates the specified device identifier.
      operationId: amazonWebServicesDeactivateDeviceIdentifier
  /v1/networks/{networkArn}:
    GET:
      summary: Getnetwork
      description: Gets the specified network.
      operationId: amazonWebServicesGetNetwork
  /v1/network-sites/{networkSiteArn}:
    GET:
      summary: Getnetworksite
      description: Gets the specified network site.
      operationId: amazonWebServicesGetNetworkSite
  /v1/device-identifiers/{deviceIdentifierArn}:
    GET:
      summary: Getdeviceidentifier
      description: Gets the specified device identifier.
      operationId: amazonWebServicesGetDeviceIdentifier
  /v1/network-resources/{networkResourceArn}:
    GET:
      summary: Getnetworkresource
      description: Gets the specified network resource.
      operationId: amazonWebServicesGetNetworkResource
  /v1/orders/{orderArn}:
    GET:
      summary: Getorder
      description: Gets the specified order.
      operationId: amazonWebServicesGetOrder
  /v1/device-identifiers/list:
    POST:
      summary: Listdeviceidentifiers
      description: >-
        Lists device identifiers. Add filters to your request to return a more
        specific list of results. Use filters to match the Amazon Resource Name
        (ARN) of an order, the status of device identifiers, or the ARN of the
        traffic group. If you specify multiple filters, filters are joined with
        an OR, and the request returns results that match all of the specified
        filters.
      operationId: amazonWebServicesListDeviceIdentifiers
  /v1/network-resources:
    POST:
      summary: Listnetworkresources
      description: >-
        Lists network resources. Add filters to your request to return a more
        specific list of results. Use filters to match the Amazon Resource Name
        (ARN) of an order or the status of network resources. If you specify
        multiple filters, filters are joined with an OR, and the request returns
        results that match all of the specified filters.
      operationId: amazonWebServicesListNetworkResources
  /v1/network-sites/list:
    POST:
      summary: Listnetworksites
      description: >-
        Lists network sites. Add filters to your request to return a more
        specific list of results. Use filters to match the status of the network
        site.
      operationId: amazonWebServicesListNetworkSites
  /v1/networks/list:
    POST:
      summary: Listnetworks
      description: >-
        Lists networks. Add filters to your request to return a more specific
        list of results. Use filters to match the status of the network.
      operationId: amazonWebServicesListNetworks
  /v1/orders/list:
    POST:
      summary: Listorders
      description: >-
        Lists orders. Add filters to your request to return a more specific list
        of results. Use filters to match the Amazon Resource Name (ARN) of the
        network site or the status of the order. If you specify multiple
        filters, filters are joined with an OR, and the request returns results
        that match all of the specified filters.
      operationId: amazonWebServicesListOrders
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes tags from the specified resource.
      operationId: amazonWebServicesUntagResource
  /ping:
    GET:
      summary: Ping
      description: Checks the health of the service.
      operationId: amazonWebServicesPing
  /v1/network-resources/update:
    POST:
      summary: Startnetworkresourceupdate
      description: >-
        Use this action to do the following tasks:   Update the duration and
        renewal status of the commitment period for a radio unit. The update
        goes into effect immediately.   Request a replacement for a network
        resource.   Request that you return a network resource.   After you
        submit a request to replace or return a network resource, the status of
        the network resource changes to CREATING_SHIPPING_LABEL. The shipping
        label is available when the status of the network resource is
        PENDING_RETURN. After the network resource is successfully returned, its
        status changes to DELETED. For more information, see Return a radio
        unit.
      operationId: amazonWebServicesStartNetworkResourceUpdate
  /v1/network-sites/site:
    PUT:
      summary: Updatenetworksite
      description: Updates the specified network site.
      operationId: amazonWebServicesUpdateNetworkSite
  /v1/network-sites/plan:
    PUT:
      summary: Updatenetworksiteplan
      description: Updates the specified network site plan.
      operationId: amazonWebServicesUpdateNetworkSitePlan
tags: []
