openapi: 3.1.0
info:
  title: qbusiness
  description: >-
    <note> <p>Amazon Q is in preview release and is subject to change.</p>
    </note> <p>This is the <i>Amazon Q (for business use)</i> API Reference.
    Amazon Q is a fully managed, generative-AI powered enterprise chat assistant
    that you can deploy within your organization. Amazon Q enhances employee
    productivity by supporting key tasks such as question-answering, knowledge
    discovery, writing email messages, summarizing text, drafting document
    outlines, and brainstorming ideas. Users ask questions of Amazon Q and get
    answers that are presented in a conversational manner. For an introduction
    to the service, see the <a
    href="https://docs.aws.amazon.com/amazonq/latest/business-use-dg/what-is.html">
    <i>Amazon Q (for business use) Developer Guide</i> </a>.</p> <p>For an
    overview of the Amazon Q APIs, see <a
    href="https://docs.aws.amazon.com/amazonq/latest/business-use-dg/api-ref.html#api-overview">Overview
    of Amazon Q API operations</a>.</p> <p>For information about the IAM access
    control permissions you need to use this API, see <a
    href="https://docs.aws.amazon.com/amazonq/latest/business-use-dg/iam-roles.html">IAM
    roles for Amazon Q</a> in the <i>Amazon Q (for business use) Developer
    Guide</i>.</p> <p>You can use the following AWS SDKs to access Amazon Q
    APIs:</p> <ul> <li> <p> <a
    href="https://docs.aws.amazon.com/sdk-for-cpp">AWS SDK for C++</a> </p>
    </li> <li> <p> <a href="https://docs.aws.amazon.com/sdk-for-go">AWS SDK for
    Go</a> </p> </li> <li> <p> <a
    href="https://docs.aws.amazon.com/sdk-for-java">AWS SDK for Java</a> </p>
    </li> <li> <p> <a href="https://docs.aws.amazon.com/sdk-for-javascript">AWS
    SDK for JavaScript</a> </p> </li> <li> <p> <a
    href="https://docs.aws.amazon.com/sdk-for-net">AWS SDK for .NET</a> </p>
    </li> <li> <p> <a href="https://docs.aws.amazon.com/pythonsdk">AWS SDK for
    Python (Boto3)</a> </p> </li> <li> <p> <a
    href="https://docs.aws.amazon.com/sdk-for-ruby">AWS SDK for Ruby</a> </p>
    </li> </ul> <p>The following resources provide additional information about
    using the Amazon Q API:</p> <ul> <li> <p> <i> <a
    href="https://docs.aws.amazon.com/amazonq/latest/business-use-dg/setting-up.html">Setting
    up for Amazon Q</a> </i> </p> </li> <li> <p> <i> <a
    href="https://awscli.amazonaws.com/v2/documentation/api/latest/reference/qbusiness/index.html">Amazon
    Q CLI Reference</a> </i> </p> </li> <li> <p> <i> <a
    href="https://docs.aws.amazon.com/general/latest/gr/amazonq.html">Amazon Web
    Services General Reference</a> </i> </p> </li> </ul>
paths:
  /applications/{applicationId}/indices/{indexId}/documents/delete:
    POST:
      summary: Batchdeletedocument
      description: >-
        Asynchronously deletes one or more documents added using the
        BatchPutDocument API from an Amazon Q index. You can see the progress of
        the deletion, and any error messages related to the process, by using
        CloudWatch.
      operationId: amazonWebServicesBatchDeleteDocument
  /applications/{applicationId}/indices/{indexId}/documents:
    POST:
      summary: Batchputdocument
      description: >-
        Adds one or more documents to an Amazon Q index. You use this API to:  
        ingest your structured and unstructured documents and documents stored
        in an Amazon S3 bucket into an Amazon Q index.   add custom attributes
        to documents in an Amazon Q index.   attach an access control list to
        the documents added to an Amazon Q index.   You can see the progress of
        the deletion, and any error messages related to the process, by using
        CloudWatch.
      operationId: amazonWebServicesBatchPutDocument
  /applications/{applicationId}/conversations?sync:
    POST:
      summary: Chatsync
      description: Starts or continues a non-streaming Amazon Q conversation.
      operationId: amazonWebServicesChatSync
  /applications:
    GET:
      summary: Listapplications
      description: Lists Amazon Q applications.
      operationId: amazonWebServicesListApplications
  /applications/{applicationId}/indices/{indexId}/datasources:
    GET:
      summary: Listdatasources
      description: Lists the Amazon Q data source connectors that you have created.
      operationId: amazonWebServicesListDataSources
  /applications/{applicationId}/indices:
    GET:
      summary: Listindices
      description: Lists the Amazon Q indices you have created.
      operationId: amazonWebServicesListIndices
  /applications/{applicationId}/plugins:
    GET:
      summary: Listplugins
      description: Lists configured Amazon Q plugins.
      operationId: amazonWebServicesListPlugins
  /applications/{applicationId}/retrievers:
    GET:
      summary: Listretrievers
      description: Lists the retriever used by an Amazon Q application.
      operationId: amazonWebServicesListRetrievers
  /applications/{applicationId}/users:
    POST:
      summary: Createuser
      description: >-
        Creates a universally unique identifier (UUID) mapped to a list of local
        user ids within an application.
      operationId: amazonWebServicesCreateUser
  /applications/{applicationId}/experiences:
    GET:
      summary: Listwebexperiences
      description: Lists one or more Amazon Q Web Experiences.
      operationId: amazonWebServicesListWebExperiences
  /applications/{applicationId}:
    PUT:
      summary: Updateapplication
      description: Updates an existing Amazon Q application.
      operationId: amazonWebServicesUpdateApplication
  /applications/{applicationId}/chatcontrols:
    PATCH:
      summary: Updatechatcontrolsconfiguration
      description: >-
        Updates an set of chat controls configured for an existing Amazon Q
        application.
      operationId: amazonWebServicesUpdateChatControlsConfiguration
  /applications/{applicationId}/conversations/{conversationId}:
    GET:
      summary: Listmessages
      description: Gets a list of messages associated with an Amazon Q web experience.
      operationId: amazonWebServicesListMessages
  /applications/{applicationId}/indices/{indexId}/datasources/{dataSourceId}:
    PUT:
      summary: Updatedatasource
      description: Updates an existing Amazon Q data source connector.
      operationId: amazonWebServicesUpdateDataSource
  /applications/{applicationId}/indices/{indexId}/groups/{groupName}:
    GET:
      summary: Getgroup
      description: Describes a group by group name.
      operationId: amazonWebServicesGetGroup
  /applications/{applicationId}/indices/{indexId}:
    PUT:
      summary: Updateindex
      description: Updates an Amazon Q index.
      operationId: amazonWebServicesUpdateIndex
  /applications/{applicationId}/plugins/{pluginId}:
    PUT:
      summary: Updateplugin
      description: Updates an Amazon Q plugin.
      operationId: amazonWebServicesUpdatePlugin
  /applications/{applicationId}/retrievers/{retrieverId}:
    PUT:
      summary: Updateretriever
      description: Updates the retriever used for your Amazon Q application.
      operationId: amazonWebServicesUpdateRetriever
  /applications/{applicationId}/users/{userId}:
    PUT:
      summary: Updateuser
      description: Updates a information associated with a user id.
      operationId: amazonWebServicesUpdateUser
  /applications/{applicationId}/experiences/{webExperienceId}:
    PUT:
      summary: Updatewebexperience
      description: 'Updates an Amazon Q web experience. '
      operationId: amazonWebServicesUpdateWebExperience
  /applications/{applicationId}/conversations:
    GET:
      summary: Listconversations
      description: Lists one or more Amazon Q conversations.
      operationId: amazonWebServicesListConversations
  /applications/{applicationId}/indices/{indexId}/datasources/{dataSourceId}/syncjobs:
    GET:
      summary: Listdatasourcesyncjobs
      description: Get information about an Amazon Q data source connector synchronization.
      operationId: amazonWebServicesListDataSourceSyncJobs
  /applications/{applicationId}/index/{indexId}/documents:
    GET:
      summary: Listdocuments
      description: A list of documents attached to an index.
      operationId: amazonWebServicesListDocuments
  /applications/{applicationId}/indices/{indexId}/groups:
    PUT:
      summary: Putgroup
      description: >-
        Create, or updates, a mapping of users—who have access to a document—to
        groups. You can also map sub groups to groups. For example, the group
        "Company Intellectual Property Teams" includes sub groups "Research" and
        "Engineering". These sub groups include their own list of users or
        people who work in these teams. Only users who work in research and
        engineering, and therefore belong in the intellectual property group,
        can see top-secret company documents in their Amazon Q chat results.
      operationId: amazonWebServicesPutGroup
  /v1/tags/{resourceARN}:
    DELETE:
      summary: Untagresource
      description: Removes a tag from an Amazon Q application or a data source.
      operationId: amazonWebServicesUntagResource
  /applications/{applicationId}/conversations/{conversationId}/messages/{messageId}/feedback:
    POST:
      summary: Putfeedback
      description: >-
        Enables your end user to to provide feedback on their Amazon Q generated
        chat responses.
      operationId: amazonWebServicesPutFeedback
  /applications/{applicationId}/indices/{indexId}/datasources/{dataSourceId}/startsync:
    POST:
      summary: Startdatasourcesyncjob
      description: >-
        Starts a data source connector synchronization job. If a synchronization
        job is already in progress, Amazon Q returns a ConflictException.
      operationId: amazonWebServicesStartDataSourceSyncJob
  /applications/{applicationId}/indices/{indexId}/datasources/{dataSourceId}/stopsync:
    POST:
      summary: Stopdatasourcesyncjob
      description: >-
        Stops an Amazon Q data source connector synchronization job already in
        progress.
      operationId: amazonWebServicesStopDataSourceSyncJob
tags: []
