openapi: 3.1.0
info:
  title: qldb
  description: <p>The resource management API for Amazon QLDB</p>
paths:
  /ledgers/{name}/journal-kinesis-streams/{streamId}:
    GET:
      summary: Describejournalkinesisstream
      description: >-
        Returns detailed information about a given Amazon QLDB journal stream.
        The output includes the Amazon Resource Name (ARN), stream name, current
        status, creation time, and the parameters of the original stream
        creation request. This action does not return any expired journal
        streams. For more information, see Expiration for terminal streams in
        the Amazon QLDB Developer Guide.
      operationId: amazonWebServicesDescribeJournalKinesisStream
  /ledgers:
    GET:
      summary: Listledgers
      description: >-
        Returns all ledgers that are associated with the current Amazon Web
        Services account and Region. This action returns a maximum of MaxResults
        items and is paginated so that you can retrieve all the items by calling
        ListLedgers multiple times.
      operationId: amazonWebServicesListLedgers
  /ledgers/{name}:
    PATCH:
      summary: Updateledger
      description: Updates properties on a ledger.
      operationId: amazonWebServicesUpdateLedger
  /ledgers/{name}/journal-s3-exports/{exportId}:
    GET:
      summary: Describejournals3export
      description: >-
        Returns information about a journal export job, including the ledger
        name, export ID, creation time, current status, and the parameters of
        the original export creation request. This action does not return any
        expired export jobs. For more information, see Export job expiration in
        the Amazon QLDB Developer Guide. If the export job with the given
        ExportId doesn't exist, then throws ResourceNotFoundException. If the
        ledger with the given Name doesn't exist, then throws
        ResourceNotFoundException.
      operationId: amazonWebServicesDescribeJournalS3Export
  /ledgers/{name}/journal-s3-exports:
    GET:
      summary: Listjournals3exportsforledger
      description: >-
        Returns all journal export jobs for a specified ledger. This action
        returns a maximum of MaxResults items, and is paginated so that you can
        retrieve all the items by calling ListJournalS3ExportsForLedger multiple
        times. This action does not return any expired export jobs. For more
        information, see Export job expiration in the Amazon QLDB Developer
        Guide.
      operationId: amazonWebServicesListJournalS3ExportsForLedger
  /ledgers/{name}/block:
    POST:
      summary: Getblock
      description: >-
        Returns a block object at a specified address in a journal. Also returns
        a proof of the specified block for verification if DigestTipAddress is
        provided. For information about the data contents in a block, see
        Journal contents in the Amazon QLDB Developer Guide. If the specified
        ledger doesn't exist or is in DELETING status, then throws
        ResourceNotFoundException. If the specified ledger is in CREATING
        status, then throws ResourcePreconditionNotMetException. If no block
        exists with the specified address, then throws
        InvalidParameterException.
      operationId: amazonWebServicesGetBlock
  /ledgers/{name}/digest:
    POST:
      summary: Getdigest
      description: >-
        Returns the digest of a ledger at the latest committed block in the
        journal. The response includes a 256-bit hash value and a block address.
      operationId: amazonWebServicesGetDigest
  /ledgers/{name}/revision:
    POST:
      summary: Getrevision
      description: >-
        Returns a revision data object for a specified document ID and block
        address. Also returns a proof of the specified revision for verification
        if DigestTipAddress is provided.
      operationId: amazonWebServicesGetRevision
  /ledgers/{name}/journal-kinesis-streams:
    POST:
      summary: Streamjournaltokinesis
      description: >-
        Creates a journal stream for a given Amazon QLDB ledger. The stream
        captures every document revision that is committed to the ledger's
        journal and delivers the data to a specified Amazon Kinesis Data Streams
        resource.
      operationId: amazonWebServicesStreamJournalToKinesis
  /journal-s3-exports:
    GET:
      summary: Listjournals3exports
      description: >-
        Returns all journal export jobs for all ledgers that are associated with
        the current Amazon Web Services account and Region. This action returns
        a maximum of MaxResults items, and is paginated so that you can retrieve
        all the items by calling ListJournalS3Exports multiple times. This
        action does not return any expired export jobs. For more information,
        see Export job expiration in the Amazon QLDB Developer Guide.
      operationId: amazonWebServicesListJournalS3Exports
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: >-
        Removes one or more tags from a specified Amazon QLDB resource. You can
        specify up to 50 tag keys to remove.
      operationId: amazonWebServicesUntagResource
  /ledgers/{name}/permissions-mode:
    PATCH:
      summary: Updateledgerpermissionsmode
      description: >-
        Updates the permissions mode of a ledger.  Before you switch to the
        STANDARD permissions mode, you must first create all required IAM
        policies and table tags to avoid disruption to your users. To learn
        more, see Migrating to the standard permissions mode in the Amazon QLDB
        Developer Guide. 
      operationId: amazonWebServicesUpdateLedgerPermissionsMode
tags: []
