openapi: 3.1.0
info:
  title: rbin
  description: >-
    <p>This is the <i>Recycle Bin API Reference</i>. This documentation provides
    descriptions and syntax for each of the actions and data types in Recycle
    Bin.</p> <p>Recycle Bin is a resource recovery feature that enables you to
    restore accidentally deleted snapshots and EBS-backed AMIs. When using
    Recycle Bin, if your resources are deleted, they are retained in the Recycle
    Bin for a time period that you specify.</p> <p>You can restore a resource
    from the Recycle Bin at any time before its retention period expires. After
    you restore a resource from the Recycle Bin, the resource is removed from
    the Recycle Bin, and you can then use it in the same way you use any other
    resource of that type in your account. If the retention period expires and
    the resource is not restored, the resource is permanently deleted from the
    Recycle Bin and is no longer available for recovery. For more information
    about Recycle Bin, see <a
    href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/recycle-bin.html">
    Recycle Bin</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p>
paths:
  /rules:
    POST:
      summary: Createrule
      description: >-
        Creates a Recycle Bin retention rule. For more information, see  Create
        Recycle Bin retention rules in the Amazon Elastic Compute Cloud User
        Guide.
      operationId: amazonWebServicesCreateRule
  /rules/{identifier}:
    PATCH:
      summary: Updaterule
      description: >-
        Updates an existing Recycle Bin retention rule. You can update a
        retention rule's description, resource tags, and retention period at any
        time after creation. You can't update a retention rule's resource type
        after creation. For more information, see  Update Recycle Bin retention
        rules in the Amazon Elastic Compute Cloud User Guide.
      operationId: amazonWebServicesUpdateRule
  /list-rules:
    POST:
      summary: Listrules
      description: Lists the Recycle Bin retention rules in the Region.
      operationId: amazonWebServicesListRules
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Unassigns a tag from a retention rule.
      operationId: amazonWebServicesUntagResource
  /rules/{identifier}/lock:
    PATCH:
      summary: Lockrule
      description: >-
        Locks a retention rule. A locked retention rule can't be modified or
        deleted.
      operationId: amazonWebServicesLockRule
  /rules/{identifier}/unlock:
    PATCH:
      summary: Unlockrule
      description: >-
        Unlocks a retention rule. After a retention rule is unlocked, it can be
        modified or deleted only after the unlock delay period expires.
      operationId: amazonWebServicesUnlockRule
tags: []
