openapi: 3.1.0
info:
  title: rds
  description: null
paths:
  /:
    POST:
      summary: Switchoverreadreplica
      description: >-
        Switches over an Oracle standby database in an Oracle Data Guard
        environment, making it the new primary database. Issue this command in
        the Region that hosts the current standby database.
      operationId: amazonWebServicesSwitchoverReadReplica
tags: []
