openapi: 3.1.0
info:
  title: repostspace
  description: >-
    <p>AWS re:Post Private is a private version of AWS re:Post for enterprises
    with Enterprise Support or Enterprise On-Ramp Support plans. It provides
    access to knowledge and experts to accelerate cloud adoption and increase
    developer productivity. With your organization-specific private re:Post, you
    can build an organization-specific developer community that drives
    efficiencies at scale and provides access to valuable knowledge resources.
    Additionally, re:Post Private centralizes trusted AWS technical content and
    offers private discussion forums to improve how your teams collaborate
    internally and with AWS to remove technical obstacles, accelerate
    innovation, and scale more efficiently in the cloud.</p>
paths:
  /spaces:
    GET:
      summary: Listspaces
      description: >-
        Returns a list of AWS re:Post Private private re:Posts in the account
        with some information about each private re:Post.
      operationId: amazonWebServicesListSpaces
  /spaces/{spaceId}:
    PUT:
      summary: Updatespace
      description: Modifies an existing AWS re:Post Private private re:Post.
      operationId: amazonWebServicesUpdateSpace
  /spaces/{spaceId}/admins/{adminId}:
    POST:
      summary: Registeradmin
      description: >-
        Adds a user or group to the list of administrators of the private
        re:Post.
      operationId: amazonWebServicesRegisterAdmin
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: >-
        Removes the association of the tag with the AWS re:Post Private
        resource.
      operationId: amazonWebServicesUntagResource
  /spaces/{spaceId}/invite:
    POST:
      summary: Sendinvites
      description: Sends an invitation email to selected users and groups.
      operationId: amazonWebServicesSendInvites
tags: []
