openapi: 3.1.0
info:
  title: resiliencehub
  description: >-
    <p>Resilience Hub helps you proactively prepare and protect your Amazon Web
    Services applications from disruptions. It offers continual resiliency
    assessment and validation that integrates into your software development
    lifecycle. This enables you to uncover resiliency weaknesses, ensure
    recovery time objective (RTO) and recovery point objective (RPO) targets for
    your applications are met, and resolve issues before they are released into
    production. </p>
paths:
  /add-draft-app-version-resource-mappings:
    POST:
      summary: Adddraftappversionresourcemappings
      description: >-
        Adds the source of resource-maps to the draft version of an application.
        During assessment, Resilience Hub will use these resource-maps to
        resolve the latest physical ID for each resource in the application
        template. For more information about different types of resources
        suported by Resilience Hub and how to add them in your application, see
        Step 2: How is your application managed? in the Resilience Hub User
        Guide.
      operationId: amazonWebServicesAddDraftAppVersionResourceMappings
  /batch-update-recommendation-status:
    POST:
      summary: Batchupdaterecommendationstatus
      description: >-
        Enables you to include or exclude one or more operational
        recommendations.
      operationId: amazonWebServicesBatchUpdateRecommendationStatus
  /create-app:
    POST:
      summary: Createapp
      description: >-
        Creates an Resilience Hub application. An Resilience Hub application is
        a collection of Amazon Web Services resources structured to prevent and
        recover Amazon Web Services application disruptions. To describe a
        Resilience Hub application, you provide an application name, resources
        from one or more CloudFormation stacks, Resource Groups, Terraform state
        files, AppRegistry applications, and an appropriate resiliency policy.
        In addition, you can also add resources that are located on Amazon
        Elastic Kubernetes Service (Amazon EKS) clusters as optional resources.
        For more information about the number of resources supported per
        application, see Service quotas. After you create an Resilience Hub
        application, you publish it so that you can run a resiliency assessment
        on it. You can then use recommendations from the assessment to improve
        resiliency by running another assessment, comparing results, and then
        iterating the process until you achieve your goals for recovery time
        objective (RTO) and recovery point objective (RPO).
      operationId: amazonWebServicesCreateApp
  /create-app-version-app-component:
    POST:
      summary: Createappversionappcomponent
      description: >-
        Creates a new Application Component in the Resilience Hub application. 
        This API updates the Resilience Hub application draft version. To use
        this Application Component for running assessments, you must publish the
        Resilience Hub application using the PublishAppVersion API. 
      operationId: amazonWebServicesCreateAppVersionAppComponent
  /create-app-version-resource:
    POST:
      summary: Createappversionresource
      description: >-
        Adds a resource to the Resilience Hub application and assigns it to the
        specified Application Components. If you specify a new Application
        Component, Resilience Hub will automatically create the Application
        Component.    This action has no effect outside Resilience Hub.   This
        API updates the Resilience Hub application draft version. To use this
        resource for running resiliency assessments, you must publish the
        Resilience Hub application using the PublishAppVersion API.   To update
        application version with new physicalResourceID, you must call
        ResolveAppVersionResources API.   
      operationId: amazonWebServicesCreateAppVersionResource
  /create-recommendation-template:
    POST:
      summary: Createrecommendationtemplate
      description: >-
        Creates a new recommendation template for the Resilience Hub
        application.
      operationId: amazonWebServicesCreateRecommendationTemplate
  /create-resiliency-policy:
    POST:
      summary: Createresiliencypolicy
      description: >-
        Creates a resiliency policy for an application.  Resilience Hub allows
        you to provide a value of zero for rtoInSecs and rpoInSecs of your
        resiliency policy. But, while assessing your application, the lowest
        possible assessment result is near zero. Hence, if you provide value
        zero for rtoInSecs and rpoInSecs, the estimated workload RTO and
        estimated workload RPO result will be near zero and the Compliance
        status for your application will be set to Policy breached. 
      operationId: amazonWebServicesCreateResiliencyPolicy
  /delete-app:
    POST:
      summary: Deleteapp
      description: >-
        Deletes an Resilience Hub application. This is a destructive action that
        can't be undone.
      operationId: amazonWebServicesDeleteApp
  /delete-app-assessment:
    POST:
      summary: Deleteappassessment
      description: >-
        Deletes an Resilience Hub application assessment. This is a destructive
        action that can't be undone.
      operationId: amazonWebServicesDeleteAppAssessment
  /delete-app-input-source:
    POST:
      summary: Deleteappinputsource
      description: >-
        Deletes the input source and all of its imported resources from the
        Resilience Hub application.
      operationId: amazonWebServicesDeleteAppInputSource
  /delete-app-version-app-component:
    POST:
      summary: Deleteappversionappcomponent
      description: >-
        Deletes an Application Component from the Resilience Hub application.   
        This API updates the Resilience Hub application draft version. To use
        this Application Component for running assessments, you must publish the
        Resilience Hub application using the PublishAppVersion API.   You will
        not be able to delete an Application Component if it has resources
        associated with it.   
      operationId: amazonWebServicesDeleteAppVersionAppComponent
  /delete-app-version-resource:
    POST:
      summary: Deleteappversionresource
      description: >-
        Deletes a resource from the Resilience Hub application.    You can only
        delete a manually added resource. To exclude non-manually added
        resources, use the UpdateAppVersionResource API.   This action has no
        effect outside Resilience Hub.   This API updates the Resilience Hub
        application draft version. To use this resource for running resiliency
        assessments, you must publish the Resilience Hub application using the
        PublishAppVersion API.   
      operationId: amazonWebServicesDeleteAppVersionResource
  /delete-recommendation-template:
    POST:
      summary: Deleterecommendationtemplate
      description: >-
        Deletes a recommendation template. This is a destructive action that
        can't be undone.
      operationId: amazonWebServicesDeleteRecommendationTemplate
  /delete-resiliency-policy:
    POST:
      summary: Deleteresiliencypolicy
      description: >-
        Deletes a resiliency policy. This is a destructive action that can't be
        undone.
      operationId: amazonWebServicesDeleteResiliencyPolicy
  /describe-app:
    POST:
      summary: Describeapp
      description: Describes an Resilience Hub application.
      operationId: amazonWebServicesDescribeApp
  /describe-app-assessment:
    POST:
      summary: Describeappassessment
      description: Describes an assessment for an Resilience Hub application.
      operationId: amazonWebServicesDescribeAppAssessment
  /describe-app-version:
    POST:
      summary: Describeappversion
      description: Describes the Resilience Hub application version.
      operationId: amazonWebServicesDescribeAppVersion
  /describe-app-version-app-component:
    POST:
      summary: Describeappversionappcomponent
      description: Describes an Application Component in the Resilience Hub application.
      operationId: amazonWebServicesDescribeAppVersionAppComponent
  /describe-app-version-resource:
    POST:
      summary: Describeappversionresource
      description: >-
        Describes a resource of the Resilience Hub application.  This API
        accepts only one of the following parameters to descibe the resource:   
        resourceName     logicalResourceId     physicalResourceId (Along with
        physicalResourceId, you can also provide awsAccountId, and awsRegion)   
      operationId: amazonWebServicesDescribeAppVersionResource
  /describe-app-version-resources-resolution-status:
    POST:
      summary: Describeappversionresourcesresolutionstatus
      description: >-
        Returns the resolution status for the specified resolution identifier
        for an application version. If resolutionId is not specified, the
        current resolution status is returned.
      operationId: amazonWebServicesDescribeAppVersionResourcesResolutionStatus
  /describe-app-version-template:
    POST:
      summary: Describeappversiontemplate
      description: Describes details about an Resilience Hub application.
      operationId: amazonWebServicesDescribeAppVersionTemplate
  /describe-draft-app-version-resources-import-status:
    POST:
      summary: Describedraftappversionresourcesimportstatus
      description: >-
        Describes the status of importing resources to an application version. 
        If you get a 404 error with
        ResourceImportStatusNotFoundAppMetadataException, you must call
        importResourcesToDraftAppVersion after creating the application and
        before calling describeDraftAppVersionResourcesImportStatus to obtain
        the status. 
      operationId: amazonWebServicesDescribeDraftAppVersionResourcesImportStatus
  /describe-resiliency-policy:
    POST:
      summary: Describeresiliencypolicy
      description: >-
        Describes a specified resiliency policy for an Resilience Hub
        application. The returned policy object includes creation time, data
        location constraints, the Amazon Resource Name (ARN) for the policy,
        tags, tier, and more.
      operationId: amazonWebServicesDescribeResiliencyPolicy
  /import-resources-to-draft-app-version:
    POST:
      summary: Importresourcestodraftappversion
      description: >-
        Imports resources to Resilience Hub application draft version from
        different input sources. For more information about the input sources
        supported by Resilience Hub, see Discover the structure and describe
        your Resilience Hub application.
      operationId: amazonWebServicesImportResourcesToDraftAppVersion
  /list-alarm-recommendations:
    POST:
      summary: Listalarmrecommendations
      description: Lists the alarm recommendations for an Resilience Hub application.
      operationId: amazonWebServicesListAlarmRecommendations
  /list-app-assessment-compliance-drifts:
    POST:
      summary: Listappassessmentcompliancedrifts
      description: >-
        List of compliance drifts that were detected while running an
        assessment.
      operationId: amazonWebServicesListAppAssessmentComplianceDrifts
  /list-app-assessments:
    GET:
      summary: Listappassessments
      description: >-
        Lists the assessments for an Resilience Hub application. You can use
        request parameters to refine the results for the response object.
      operationId: amazonWebServicesListAppAssessments
  /list-app-component-compliances:
    POST:
      summary: Listappcomponentcompliances
      description: Lists the compliances for an Resilience Hub Application Component.
      operationId: amazonWebServicesListAppComponentCompliances
  /list-app-component-recommendations:
    POST:
      summary: Listappcomponentrecommendations
      description: Lists the recommendations for an Resilience Hub Application Component.
      operationId: amazonWebServicesListAppComponentRecommendations
  /list-app-input-sources:
    POST:
      summary: Listappinputsources
      description: >-
        Lists all the input sources of the Resilience Hub application. For more
        information about the input sources supported by Resilience Hub, see
        Discover the structure and describe your Resilience Hub application.
      operationId: amazonWebServicesListAppInputSources
  /list-app-version-app-components:
    POST:
      summary: Listappversionappcomponents
      description: Lists all the Application Components in the Resilience Hub application.
      operationId: amazonWebServicesListAppVersionAppComponents
  /list-app-version-resource-mappings:
    POST:
      summary: Listappversionresourcemappings
      description: >-
        Lists how the resources in an application version are mapped/sourced
        from. Mappings can be physical resource identifiers, CloudFormation
        stacks, resource-groups, or an application registry app.
      operationId: amazonWebServicesListAppVersionResourceMappings
  /list-app-version-resources:
    POST:
      summary: Listappversionresources
      description: Lists all the resources in an Resilience Hub application.
      operationId: amazonWebServicesListAppVersionResources
  /list-app-versions:
    POST:
      summary: Listappversions
      description: Lists the different versions for the Resilience Hub applications.
      operationId: amazonWebServicesListAppVersions
  /list-apps:
    GET:
      summary: Listapps
      description: >-
        Lists your Resilience Hub applications.  You can filter applications
        using only one filter at a time or without using any filter. If you try
        to filter applications using multiple filters, you will get the
        following error:  An error occurred (ValidationException) when calling
        the ListApps operation: Only one filter is supported for this
        operation.  
      operationId: amazonWebServicesListApps
  /list-recommendation-templates:
    GET:
      summary: Listrecommendationtemplates
      description: Lists the recommendation templates for the Resilience Hub applications.
      operationId: amazonWebServicesListRecommendationTemplates
  /list-resiliency-policies:
    GET:
      summary: Listresiliencypolicies
      description: Lists the resiliency policies for the Resilience Hub applications.
      operationId: amazonWebServicesListResiliencyPolicies
  /list-sop-recommendations:
    POST:
      summary: Listsoprecommendations
      description: >-
        Lists the standard operating procedure (SOP) recommendations for the
        Resilience Hub applications.
      operationId: amazonWebServicesListSopRecommendations
  /list-suggested-resiliency-policies:
    GET:
      summary: Listsuggestedresiliencypolicies
      description: >-
        Lists the suggested resiliency policies for the Resilience Hub
        applications.
      operationId: amazonWebServicesListSuggestedResiliencyPolicies
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes one or more tags from a resource.
      operationId: amazonWebServicesUntagResource
  /list-test-recommendations:
    POST:
      summary: Listtestrecommendations
      description: Lists the test recommendations for the Resilience Hub application.
      operationId: amazonWebServicesListTestRecommendations
  /list-unsupported-app-version-resources:
    POST:
      summary: Listunsupportedappversionresources
      description: >-
        Lists the resources that are not currently supported in Resilience Hub.
        An unsupported resource is a resource that exists in the object that was
        used to create an app, but is not supported by Resilience Hub.
      operationId: amazonWebServicesListUnsupportedAppVersionResources
  /publish-app-version:
    POST:
      summary: Publishappversion
      description: Publishes a new version of a specific Resilience Hub application.
      operationId: amazonWebServicesPublishAppVersion
  /put-draft-app-version-template:
    POST:
      summary: Putdraftappversiontemplate
      description: >-
        Adds or updates the app template for an Resilience Hub application draft
        version.
      operationId: amazonWebServicesPutDraftAppVersionTemplate
  /remove-draft-app-version-resource-mappings:
    POST:
      summary: Removedraftappversionresourcemappings
      description: Removes resource mappings from a draft application version.
      operationId: amazonWebServicesRemoveDraftAppVersionResourceMappings
  /resolve-app-version-resources:
    POST:
      summary: Resolveappversionresources
      description: Resolves the resources for an application version.
      operationId: amazonWebServicesResolveAppVersionResources
  /start-app-assessment:
    POST:
      summary: Startappassessment
      description: Creates a new application assessment for an application.
      operationId: amazonWebServicesStartAppAssessment
  /update-app:
    POST:
      summary: Updateapp
      description: Updates an application.
      operationId: amazonWebServicesUpdateApp
  /update-app-version:
    POST:
      summary: Updateappversion
      description: >-
        Updates the Resilience Hub application version.  This API updates the
        Resilience Hub application draft version. To use this information for
        running resiliency assessments, you must publish the Resilience Hub
        application using the PublishAppVersion API. 
      operationId: amazonWebServicesUpdateAppVersion
  /update-app-version-app-component:
    POST:
      summary: Updateappversionappcomponent
      description: >-
        Updates an existing Application Component in the Resilience Hub
        application.  This API updates the Resilience Hub application draft
        version. To use this Application Component for running assessments, you
        must publish the Resilience Hub application using the PublishAppVersion
        API. 
      operationId: amazonWebServicesUpdateAppVersionAppComponent
  /update-app-version-resource:
    POST:
      summary: Updateappversionresource
      description: >-
        Updates the resource details in the Resilience Hub application.    This
        action has no effect outside Resilience Hub.   This API updates the
        Resilience Hub application draft version. To use this resource for
        running resiliency assessments, you must publish the Resilience Hub
        application using the PublishAppVersion API.   To update application
        version with new physicalResourceID, you must call
        ResolveAppVersionResources API.   
      operationId: amazonWebServicesUpdateAppVersionResource
  /update-resiliency-policy:
    POST:
      summary: Updateresiliencypolicy
      description: >-
        Updates a resiliency policy.  Resilience Hub allows you to provide a
        value of zero for rtoInSecs and rpoInSecs of your resiliency policy.
        But, while assessing your application, the lowest possible assessment
        result is near zero. Hence, if you provide value zero for rtoInSecs and
        rpoInSecs, the estimated workload RTO and estimated workload RPO result
        will be near zero and the Compliance status for your application will be
        set to Policy breached. 
      operationId: amazonWebServicesUpdateResiliencyPolicy
tags: []
