openapi: 3.1.0
info:
  title: resource-groups
  description: >-
    <p>Resource Groups lets you organize Amazon Web Services resources such as
    Amazon Elastic Compute Cloud instances, Amazon Relational Database Service
    databases, and Amazon Simple Storage Service buckets into groups using
    criteria that you define as tags. A resource group is a collection of
    resources that match the resource types specified in a query, and share one
    or more tags or portions of tags. You can create a group of resources based
    on their roles in your cloud infrastructure, lifecycle stages, regions,
    application layers, or virtually any criteria. Resource Groups enable you to
    automate management tasks, such as those in Amazon Web Services Systems
    Manager Automation documents, on tag-related resources in Amazon Web
    Services Systems Manager. Groups of tagged resources also let you quickly
    view a custom console in Amazon Web Services Systems Manager that shows
    Config compliance and other monitoring data about member resources.</p>
    <p>To create a resource group, build a resource query, and specify tags that
    identify the criteria that members of the group have in common. Tags are
    key-value pairs.</p> <p>For more information about Resource Groups, see the
    <a
    href="https://docs.aws.amazon.com/ARG/latest/userguide/welcome.html">Resource
    Groups User Guide</a>.</p> <p>Resource Groups uses a REST-compliant API that
    you can use to perform the following types of operations.</p> <ul> <li>
    <p>Create, Read, Update, and Delete (CRUD) operations on resource groups and
    resource query entities</p> </li> <li> <p>Applying, editing, and removing
    tags from resource groups</p> </li> <li> <p>Resolving resource group member
    ARNs so they can be returned as search results</p> </li> <li> <p>Getting
    data about resources that are members of a group</p> </li> <li> <p>Searching
    Amazon Web Services resources based on a resource query</p> </li> </ul>
paths:
  /groups:
    POST:
      summary: Creategroup
      description: >-
        Creates a resource group with the specified name and description. You
        can optionally include either a resource query or a service
        configuration. For more information about constructing a resource query,
        see Build queries and groups in Resource Groups in the Resource Groups
        User Guide. For more information about service-linked groups and service
        configurations, see Service configurations for Resource Groups.  Minimum
        permissions  To run this command, you must have the following
        permissions:    resource-groups:CreateGroup   
      operationId: amazonWebServicesCreateGroup
  /delete-group:
    POST:
      summary: Deletegroup
      description: >-
        Deletes the specified resource group. Deleting a resource group does not
        delete any resources that are members of the group; it only deletes the
        group structure.  Minimum permissions  To run this command, you must
        have the following permissions:    resource-groups:DeleteGroup   
      operationId: amazonWebServicesDeleteGroup
  /get-account-settings:
    POST:
      summary: Getaccountsettings
      description: Retrieves the current status of optional features in Resource Groups.
      operationId: amazonWebServicesGetAccountSettings
  /get-group:
    POST:
      summary: Getgroup
      description: >-
        Returns information about a specified resource group.  Minimum
        permissions  To run this command, you must have the following
        permissions:    resource-groups:GetGroup   
      operationId: amazonWebServicesGetGroup
  /get-group-configuration:
    POST:
      summary: Getgroupconfiguration
      description: >-
        Retrieves the service configuration associated with the specified
        resource group. For details about the service configuration syntax, see
        Service configurations for Resource Groups.  Minimum permissions  To run
        this command, you must have the following permissions:   
        resource-groups:GetGroupConfiguration   
      operationId: amazonWebServicesGetGroupConfiguration
  /get-group-query:
    POST:
      summary: Getgroupquery
      description: >-
        Retrieves the resource query associated with the specified resource
        group. For more information about resource queries, see Create a
        tag-based group in Resource Groups.  Minimum permissions  To run this
        command, you must have the following permissions:   
        resource-groups:GetGroupQuery   
      operationId: amazonWebServicesGetGroupQuery
  /resources/{Arn}/tags:
    PATCH:
      summary: Untag
      description: >-
        Deletes tags from a specified resource group.  Minimum permissions  To
        run this command, you must have the following permissions:   
        resource-groups:Untag   
      operationId: amazonWebServicesUntag
  /group-resources:
    POST:
      summary: Groupresources
      description: >-
        Adds the specified resources to the specified group.  You can use this
        operation with only resource groups that are configured with the
        following types:    AWS::EC2::HostManagement    
        AWS::EC2::CapacityReservationPool    Other resource group type and
        resource types aren't currently supported by this operation.   Minimum
        permissions  To run this command, you must have the following
        permissions:    resource-groups:GroupResources   
      operationId: amazonWebServicesGroupResources
  /list-group-resources:
    POST:
      summary: Listgroupresources
      description: >-
        Returns a list of ARNs of the resources that are members of a specified
        resource group.  Minimum permissions  To run this command, you must have
        the following permissions:    resource-groups:ListGroupResources    
        cloudformation:DescribeStacks     cloudformation:ListStackResources    
        tag:GetResources   
      operationId: amazonWebServicesListGroupResources
  /groups-list:
    POST:
      summary: Listgroups
      description: >-
        Returns a list of existing Resource Groups in your account.  Minimum
        permissions  To run this command, you must have the following
        permissions:    resource-groups:ListGroups   
      operationId: amazonWebServicesListGroups
  /put-group-configuration:
    POST:
      summary: Putgroupconfiguration
      description: >-
        Attaches a service configuration to the specified group. This occurs
        asynchronously, and can take time to complete. You can use
        GetGroupConfiguration to check the status of the update.  Minimum
        permissions  To run this command, you must have the following
        permissions:    resource-groups:PutGroupConfiguration   
      operationId: amazonWebServicesPutGroupConfiguration
  /resources/search:
    POST:
      summary: Searchresources
      description: >-
        Returns a list of Amazon Web Services resource identifiers that matches
        the specified query. The query uses the same format as a resource query
        in a CreateGroup or UpdateGroupQuery operation.  Minimum permissions  To
        run this command, you must have the following permissions:   
        resource-groups:SearchResources     cloudformation:DescribeStacks    
        cloudformation:ListStackResources     tag:GetResources   
      operationId: amazonWebServicesSearchResources
  /ungroup-resources:
    POST:
      summary: Ungroupresources
      description: >-
        Removes the specified resources from the specified group. This operation
        works only with static groups that you populated using the
        GroupResources operation. It doesn't work with any resource groups that
        are automatically populated by tag-based or CloudFormation stack-based
        queries.  Minimum permissions  To run this command, you must have the
        following permissions:    resource-groups:UngroupResources   
      operationId: amazonWebServicesUngroupResources
  /update-account-settings:
    POST:
      summary: Updateaccountsettings
      description: >-
        Turns on or turns off optional features in Resource Groups. The
        preceding example shows that the request to turn on group lifecycle
        events is IN_PROGRESS. You can call the GetAccountSettings operation to
        check for completion by looking for GroupLifecycleEventsStatus to change
        to ACTIVE.
      operationId: amazonWebServicesUpdateAccountSettings
  /update-group:
    POST:
      summary: Updategroup
      description: >-
        Updates the description for an existing group. You cannot update the
        name of a resource group.  Minimum permissions  To run this command, you
        must have the following permissions:    resource-groups:UpdateGroup   
      operationId: amazonWebServicesUpdateGroup
  /update-group-query:
    POST:
      summary: Updategroupquery
      description: >-
        Updates the resource query of a group. For more information about
        resource queries, see Create a tag-based group in Resource Groups. 
        Minimum permissions  To run this command, you must have the following
        permissions:    resource-groups:UpdateGroupQuery   
      operationId: amazonWebServicesUpdateGroupQuery
tags: []
