openapi: 3.1.0
info:
  title: robomaker
  description: >-
    <p>This section provides documentation for the AWS RoboMaker API
    operations.</p>
paths:
  /batchDeleteWorlds:
    POST:
      summary: Batchdeleteworlds
      description: Deletes one or more worlds in a batch operation.
      operationId: amazonWebServicesBatchDeleteWorlds
  /batchDescribeSimulationJob:
    POST:
      summary: Batchdescribesimulationjob
      description: Describes one or more simulation jobs.
      operationId: amazonWebServicesBatchDescribeSimulationJob
  /cancelDeploymentJob:
    POST:
      summary: Canceldeploymentjob
      description: >-
        Cancels the specified deployment job.  This API will no longer be
        supported as of May 2, 2022. Use it to remove resources that were
        created for Deployment Service. 
      operationId: amazonWebServicesCancelDeploymentJob
  /cancelSimulationJob:
    POST:
      summary: Cancelsimulationjob
      description: Cancels the specified simulation job.
      operationId: amazonWebServicesCancelSimulationJob
  /cancelSimulationJobBatch:
    POST:
      summary: Cancelsimulationjobbatch
      description: >-
        Cancels a simulation job batch. When you cancel a simulation job batch,
        you are also cancelling all of the active simulation jobs created as
        part of the batch. 
      operationId: amazonWebServicesCancelSimulationJobBatch
  /cancelWorldExportJob:
    POST:
      summary: Cancelworldexportjob
      description: Cancels the specified export job.
      operationId: amazonWebServicesCancelWorldExportJob
  /cancelWorldGenerationJob:
    POST:
      summary: Cancelworldgenerationjob
      description: Cancels the specified world generator job.
      operationId: amazonWebServicesCancelWorldGenerationJob
  /createDeploymentJob:
    POST:
      summary: Createdeploymentjob
      description: >-
        Deploys a specific version of a robot application to robots in a fleet. 
        This API is no longer supported and will throw an error if used.  The
        robot application must have a numbered applicationVersion for
        consistency reasons. To create a new version, use
        CreateRobotApplicationVersion or see Creating a Robot Application
        Version.   After 90 days, deployment jobs expire and will be deleted.
        They will no longer be accessible.  
      operationId: amazonWebServicesCreateDeploymentJob
  /createFleet:
    POST:
      summary: Createfleet
      description: >-
        Creates a fleet, a logical group of robots running the same robot
        application.  This API is no longer supported and will throw an error if
        used. 
      operationId: amazonWebServicesCreateFleet
  /createRobot:
    POST:
      summary: Createrobot
      description: >-
        Creates a robot.  This API is no longer supported and will throw an
        error if used. 
      operationId: amazonWebServicesCreateRobot
  /createRobotApplication:
    POST:
      summary: Createrobotapplication
      description: 'Creates a robot application. '
      operationId: amazonWebServicesCreateRobotApplication
  /createRobotApplicationVersion:
    POST:
      summary: Createrobotapplicationversion
      description: Creates a version of a robot application.
      operationId: amazonWebServicesCreateRobotApplicationVersion
  /createSimulationApplication:
    POST:
      summary: Createsimulationapplication
      description: Creates a simulation application.
      operationId: amazonWebServicesCreateSimulationApplication
  /createSimulationApplicationVersion:
    POST:
      summary: Createsimulationapplicationversion
      description: Creates a simulation application with a specific revision id.
      operationId: amazonWebServicesCreateSimulationApplicationVersion
  /createSimulationJob:
    POST:
      summary: Createsimulationjob
      description: >-
        Creates a simulation job.  After 90 days, simulation jobs expire and
        will be deleted. They will no longer be accessible.  
      operationId: amazonWebServicesCreateSimulationJob
  /createWorldExportJob:
    POST:
      summary: Createworldexportjob
      description: Creates a world export job.
      operationId: amazonWebServicesCreateWorldExportJob
  /createWorldGenerationJob:
    POST:
      summary: Createworldgenerationjob
      description: Creates worlds using the specified template.
      operationId: amazonWebServicesCreateWorldGenerationJob
  /createWorldTemplate:
    POST:
      summary: Createworldtemplate
      description: Creates a world template.
      operationId: amazonWebServicesCreateWorldTemplate
  /deleteFleet:
    POST:
      summary: Deletefleet
      description: >-
        Deletes a fleet.  This API will no longer be supported as of May 2,
        2022. Use it to remove resources that were created for Deployment
        Service. 
      operationId: amazonWebServicesDeleteFleet
  /deleteRobot:
    POST:
      summary: Deleterobot
      description: >-
        Deletes a robot.  This API will no longer be supported as of May 2,
        2022. Use it to remove resources that were created for Deployment
        Service. 
      operationId: amazonWebServicesDeleteRobot
  /deleteRobotApplication:
    POST:
      summary: Deleterobotapplication
      description: Deletes a robot application.
      operationId: amazonWebServicesDeleteRobotApplication
  /deleteSimulationApplication:
    POST:
      summary: Deletesimulationapplication
      description: Deletes a simulation application.
      operationId: amazonWebServicesDeleteSimulationApplication
  /deleteWorldTemplate:
    POST:
      summary: Deleteworldtemplate
      description: Deletes a world template.
      operationId: amazonWebServicesDeleteWorldTemplate
  /deregisterRobot:
    POST:
      summary: Deregisterrobot
      description: >-
        Deregisters a robot.  This API will no longer be supported as of May 2,
        2022. Use it to remove resources that were created for Deployment
        Service. 
      operationId: amazonWebServicesDeregisterRobot
  /describeDeploymentJob:
    POST:
      summary: Describedeploymentjob
      description: >-
        Describes a deployment job.  This API will no longer be supported as of
        May 2, 2022. Use it to remove resources that were created for Deployment
        Service. 
      operationId: amazonWebServicesDescribeDeploymentJob
  /describeFleet:
    POST:
      summary: Describefleet
      description: >-
        Describes a fleet.  This API will no longer be supported as of May 2,
        2022. Use it to remove resources that were created for Deployment
        Service. 
      operationId: amazonWebServicesDescribeFleet
  /describeRobot:
    POST:
      summary: Describerobot
      description: >-
        Describes a robot.  This API will no longer be supported as of May 2,
        2022. Use it to remove resources that were created for Deployment
        Service. 
      operationId: amazonWebServicesDescribeRobot
  /describeRobotApplication:
    POST:
      summary: Describerobotapplication
      description: Describes a robot application.
      operationId: amazonWebServicesDescribeRobotApplication
  /describeSimulationApplication:
    POST:
      summary: Describesimulationapplication
      description: Describes a simulation application.
      operationId: amazonWebServicesDescribeSimulationApplication
  /describeSimulationJob:
    POST:
      summary: Describesimulationjob
      description: Describes a simulation job.
      operationId: amazonWebServicesDescribeSimulationJob
  /describeSimulationJobBatch:
    POST:
      summary: Describesimulationjobbatch
      description: Describes a simulation job batch.
      operationId: amazonWebServicesDescribeSimulationJobBatch
  /describeWorld:
    POST:
      summary: Describeworld
      description: Describes a world.
      operationId: amazonWebServicesDescribeWorld
  /describeWorldExportJob:
    POST:
      summary: Describeworldexportjob
      description: Describes a world export job.
      operationId: amazonWebServicesDescribeWorldExportJob
  /describeWorldGenerationJob:
    POST:
      summary: Describeworldgenerationjob
      description: Describes a world generation job.
      operationId: amazonWebServicesDescribeWorldGenerationJob
  /describeWorldTemplate:
    POST:
      summary: Describeworldtemplate
      description: Describes a world template.
      operationId: amazonWebServicesDescribeWorldTemplate
  /getWorldTemplateBody:
    POST:
      summary: Getworldtemplatebody
      description: Gets the world template body.
      operationId: amazonWebServicesGetWorldTemplateBody
  /listDeploymentJobs:
    POST:
      summary: Listdeploymentjobs
      description: >-
        Returns a list of deployment jobs for a fleet. You can optionally
        provide filters to retrieve specific deployment jobs.  This API will no
        longer be supported as of May 2, 2022. Use it to remove resources that
        were created for Deployment Service. 
      operationId: amazonWebServicesListDeploymentJobs
  /listFleets:
    POST:
      summary: Listfleets
      description: >-
        Returns a list of fleets. You can optionally provide filters to retrieve
        specific fleets.  This API will no longer be supported as of May 2,
        2022. Use it to remove resources that were created for Deployment
        Service. 
      operationId: amazonWebServicesListFleets
  /listRobotApplications:
    POST:
      summary: Listrobotapplications
      description: >-
        Returns a list of robot application. You can optionally provide filters
        to retrieve specific robot applications.
      operationId: amazonWebServicesListRobotApplications
  /listRobots:
    POST:
      summary: Listrobots
      description: >-
        Returns a list of robots. You can optionally provide filters to retrieve
        specific robots.  This API will no longer be supported as of May 2,
        2022. Use it to remove resources that were created for Deployment
        Service. 
      operationId: amazonWebServicesListRobots
  /listSimulationApplications:
    POST:
      summary: Listsimulationapplications
      description: >-
        Returns a list of simulation applications. You can optionally provide
        filters to retrieve specific simulation applications. 
      operationId: amazonWebServicesListSimulationApplications
  /listSimulationJobBatches:
    POST:
      summary: Listsimulationjobbatches
      description: >-
        Returns a list simulation job batches. You can optionally provide
        filters to retrieve specific simulation batch jobs. 
      operationId: amazonWebServicesListSimulationJobBatches
  /listSimulationJobs:
    POST:
      summary: Listsimulationjobs
      description: >-
        Returns a list of simulation jobs. You can optionally provide filters to
        retrieve specific simulation jobs. 
      operationId: amazonWebServicesListSimulationJobs
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: >-
        Removes the specified tags from the specified AWS RoboMaker resource. To
        remove a tag, specify the tag key. To change the tag value of an
        existing tag key, use  TagResource . 
      operationId: amazonWebServicesUntagResource
  /listWorldExportJobs:
    POST:
      summary: Listworldexportjobs
      description: Lists world export jobs.
      operationId: amazonWebServicesListWorldExportJobs
  /listWorldGenerationJobs:
    POST:
      summary: Listworldgenerationjobs
      description: Lists world generator jobs.
      operationId: amazonWebServicesListWorldGenerationJobs
  /listWorldTemplates:
    POST:
      summary: Listworldtemplates
      description: Lists world templates.
      operationId: amazonWebServicesListWorldTemplates
  /listWorlds:
    POST:
      summary: Listworlds
      description: Lists worlds.
      operationId: amazonWebServicesListWorlds
  /registerRobot:
    POST:
      summary: Registerrobot
      description: >-
        Registers a robot with a fleet.  This API is no longer supported and
        will throw an error if used. 
      operationId: amazonWebServicesRegisterRobot
  /restartSimulationJob:
    POST:
      summary: Restartsimulationjob
      description: Restarts a running simulation job.
      operationId: amazonWebServicesRestartSimulationJob
  /startSimulationJobBatch:
    POST:
      summary: Startsimulationjobbatch
      description: >-
        Starts a new simulation job batch. The batch is defined using one or
        more SimulationJobRequest objects. 
      operationId: amazonWebServicesStartSimulationJobBatch
  /syncDeploymentJob:
    POST:
      summary: Syncdeploymentjob
      description: >-
        Syncrhonizes robots in a fleet to the latest deployment. This is helpful
        if robots were added after a deployment.  This API will no longer be
        supported as of May 2, 2022. Use it to remove resources that were
        created for Deployment Service. 
      operationId: amazonWebServicesSyncDeploymentJob
  /updateRobotApplication:
    POST:
      summary: Updaterobotapplication
      description: Updates a robot application.
      operationId: amazonWebServicesUpdateRobotApplication
  /updateSimulationApplication:
    POST:
      summary: Updatesimulationapplication
      description: Updates a simulation application.
      operationId: amazonWebServicesUpdateSimulationApplication
  /updateWorldTemplate:
    POST:
      summary: Updateworldtemplate
      description: Updates a world template.
      operationId: amazonWebServicesUpdateWorldTemplate
tags: []
