openapi: 3.1.0
info:
  title: rolesanywhere
  description: >-
    <p>Identity and Access Management Roles Anywhere provides a secure way for
    your workloads such as servers, containers, and applications that run
    outside of Amazon Web Services to obtain temporary Amazon Web Services
    credentials. Your workloads can use the same IAM policies and roles you have
    for native Amazon Web Services applications to access Amazon Web Services
    resources. Using IAM Roles Anywhere eliminates the need to manage long-term
    credentials for workloads running outside of Amazon Web Services.</p> <p> To
    use IAM Roles Anywhere, your workloads must use X.509 certificates issued by
    their certificate authority (CA). You register the CA with IAM Roles
    Anywhere as a trust anchor to establish trust between your public key
    infrastructure (PKI) and IAM Roles Anywhere. If you don't manage your own
    PKI system, you can use Private Certificate Authority to create a CA and
    then use that to establish trust with IAM Roles Anywhere. </p> <p>This guide
    describes the IAM Roles Anywhere operations that you can call
    programmatically. For more information about IAM Roles Anywhere, see the <a
    href="https://docs.aws.amazon.com/rolesanywhere/latest/userguide/introduction.html">IAM
    Roles Anywhere User Guide</a>.</p>
paths:
  /profiles:
    GET:
      summary: Listprofiles
      description: >-
        Lists all profiles in the authenticated account and Amazon Web Services
        Region.  Required permissions:  rolesanywhere:ListProfiles. 
      operationId: amazonWebServicesListProfiles
  /trustanchors:
    GET:
      summary: Listtrustanchors
      description: >-
        Lists the trust anchors in the authenticated account and Amazon Web
        Services Region.  Required permissions: 
        rolesanywhere:ListTrustAnchors. 
      operationId: amazonWebServicesListTrustAnchors
  /crl/{crlId}:
    PATCH:
      summary: Updatecrl
      description: >-
        Updates the certificate revocation list (CRL). A CRL is a list of
        certificates that have been revoked by the issuing certificate authority
        (CA). IAM Roles Anywhere validates against the CRL before issuing
        credentials.  Required permissions:  rolesanywhere:UpdateCrl. 
      operationId: amazonWebServicesUpdateCrl
  /profile/{profileId}:
    PATCH:
      summary: Updateprofile
      description: >-
        Updates a profile, a list of the roles that IAM Roles Anywhere service
        is trusted to assume. You use profiles to intersect permissions with IAM
        managed policies.  Required permissions:  rolesanywhere:UpdateProfile. 
      operationId: amazonWebServicesUpdateProfile
  /trustanchor/{trustAnchorId}:
    PATCH:
      summary: Updatetrustanchor
      description: >-
        Updates a trust anchor. You establish trust between IAM Roles Anywhere
        and your certificate authority (CA) by configuring a trust anchor. You
        can define a trust anchor as a reference to an Private Certificate
        Authority (Private CA) or by uploading a CA certificate. Your Amazon Web
        Services workloads can authenticate with the trust anchor using
        certificates issued by the CA in exchange for temporary Amazon Web
        Services credentials.  Required permissions: 
        rolesanywhere:UpdateTrustAnchor. 
      operationId: amazonWebServicesUpdateTrustAnchor
  /crl/{crlId}/disable:
    POST:
      summary: Disablecrl
      description: >-
        Disables a certificate revocation list (CRL).  Required permissions: 
        rolesanywhere:DisableCrl. 
      operationId: amazonWebServicesDisableCrl
  /profile/{profileId}/disable:
    POST:
      summary: Disableprofile
      description: >-
        Disables a profile. When disabled, temporary credential requests with
        this profile fail.  Required permissions: 
        rolesanywhere:DisableProfile. 
      operationId: amazonWebServicesDisableProfile
  /trustanchor/{trustAnchorId}/disable:
    POST:
      summary: Disabletrustanchor
      description: >-
        Disables a trust anchor. When disabled, temporary credential requests
        specifying this trust anchor are unauthorized.  Required permissions: 
        rolesanywhere:DisableTrustAnchor. 
      operationId: amazonWebServicesDisableTrustAnchor
  /crl/{crlId}/enable:
    POST:
      summary: Enablecrl
      description: >-
        Enables a certificate revocation list (CRL). When enabled, certificates
        stored in the CRL are unauthorized to receive session credentials. 
        Required permissions:  rolesanywhere:EnableCrl. 
      operationId: amazonWebServicesEnableCrl
  /profile/{profileId}/enable:
    POST:
      summary: Enableprofile
      description: >-
        Enables temporary credential requests for a profile.   Required
        permissions:  rolesanywhere:EnableProfile. 
      operationId: amazonWebServicesEnableProfile
  /trustanchor/{trustAnchorId}/enable:
    POST:
      summary: Enabletrustanchor
      description: >-
        Enables a trust anchor. When enabled, certificates in the trust anchor
        chain are authorized for trust validation.   Required permissions: 
        rolesanywhere:EnableTrustAnchor. 
      operationId: amazonWebServicesEnableTrustAnchor
  /subject/{subjectId}:
    GET:
      summary: Getsubject
      description: >-
        Gets a subject, which associates a certificate identity with
        authentication attempts. The subject stores auditing information such as
        the status of the last authentication attempt, the certificate data used
        in the attempt, and the last time the associated identity attempted
        authentication.   Required permissions:  rolesanywhere:GetSubject. 
      operationId: amazonWebServicesGetSubject
  /crls:
    GET:
      summary: Listcrls
      description: >-
        Lists all certificate revocation lists (CRL) in the authenticated
        account and Amazon Web Services Region.  Required permissions: 
        rolesanywhere:ListCrls. 
      operationId: amazonWebServicesListCrls
  /subjects:
    GET:
      summary: Listsubjects
      description: >-
        Lists the subjects in the authenticated account and Amazon Web Services
        Region.  Required permissions:  rolesanywhere:ListSubjects. 
      operationId: amazonWebServicesListSubjects
  /ListTagsForResource:
    GET:
      summary: Listtagsforresource
      description: >-
        Lists the tags attached to the resource.  Required permissions: 
        rolesanywhere:ListTagsForResource. 
      operationId: amazonWebServicesListTagsForResource
  /put-notifications-settings:
    PATCH:
      summary: Putnotificationsettings
      description: >-
        Attaches a list of notification settings to a trust anchor. A
        notification setting includes information such as event name, threshold,
        status of the notification setting, and the channel to notify.  Required
        permissions:  rolesanywhere:PutNotificationSettings. 
      operationId: amazonWebServicesPutNotificationSettings
  /reset-notifications-settings:
    PATCH:
      summary: Resetnotificationsettings
      description: >-
        Resets the custom notification setting to IAM Roles Anywhere default
        setting.   Required permissions: 
        rolesanywhere:ResetNotificationSettings. 
      operationId: amazonWebServicesResetNotificationSettings
  /TagResource:
    POST:
      summary: Tagresource
      description: >-
        Attaches tags to a resource.  Required permissions: 
        rolesanywhere:TagResource. 
      operationId: amazonWebServicesTagResource
  /UntagResource:
    POST:
      summary: Untagresource
      description: >-
        Removes tags from the resource.  Required permissions: 
        rolesanywhere:UntagResource. 
      operationId: amazonWebServicesUntagResource
tags: []
