openapi: 3.1.0
info:
  title: route53-recovery-readiness
  description: <p>Recovery readiness</p>
paths:
  /cells:
    GET:
      summary: Listcells
      description: Lists the cells for an account.
      operationId: amazonWebServicesListCells
  /crossaccountauthorizations:
    GET:
      summary: Listcrossaccountauthorizations
      description: >-
        Lists the cross-account readiness authorizations that are in place for
        an account.
      operationId: amazonWebServicesListCrossAccountAuthorizations
  /readinesschecks:
    GET:
      summary: Listreadinesschecks
      description: Lists the readiness checks for an account.
      operationId: amazonWebServicesListReadinessChecks
  /recoverygroups:
    GET:
      summary: Listrecoverygroups
      description: Lists the recovery groups in an account.
      operationId: amazonWebServicesListRecoveryGroups
  /resourcesets:
    GET:
      summary: Listresourcesets
      description: Lists the resource sets in an account.
      operationId: amazonWebServicesListResourceSets
  /cells/{cellName}:
    PUT:
      summary: Updatecell
      description: >-
        Updates a cell to replace the list of nested cells with a new list of
        nested cells.
      operationId: amazonWebServicesUpdateCell
  /crossaccountauthorizations/{crossAccountAuthorization}:
    DELETE:
      summary: Deletecrossaccountauthorization
      description: Deletes cross account readiness authorization.
      operationId: amazonWebServicesDeleteCrossAccountAuthorization
  /readinesschecks/{readinessCheckName}:
    PUT:
      summary: Updatereadinesscheck
      description: Updates a readiness check.
      operationId: amazonWebServicesUpdateReadinessCheck
  /recoverygroups/{recoveryGroupName}:
    PUT:
      summary: Updaterecoverygroup
      description: Updates a recovery group.
      operationId: amazonWebServicesUpdateRecoveryGroup
  /resourcesets/{resourceSetName}:
    PUT:
      summary: Updateresourceset
      description: Updates a resource set.
      operationId: amazonWebServicesUpdateResourceSet
  /recoverygroups/{recoveryGroupName}/architectureRecommendations:
    GET:
      summary: Getarchitecturerecommendations
      description: >-
        Gets recommendations about architecture designs for improving resiliency
        for an application, based on a recovery group.
      operationId: amazonWebServicesGetArchitectureRecommendations
  /cellreadiness/{cellName}:
    GET:
      summary: Getcellreadinesssummary
      description: >-
        Gets readiness for a cell. Aggregates the readiness of all the resources
        that are associated with the cell into a single value.
      operationId: amazonWebServicesGetCellReadinessSummary
  /readinesschecks/{readinessCheckName}/resource/{resourceIdentifier}/status:
    GET:
      summary: Getreadinesscheckresourcestatus
      description: >-
        Gets individual readiness status for a readiness check. To see the
        overall readiness status for a recovery group, that considers the
        readiness status for all the readiness checks in the recovery group, use
        GetRecoveryGroupReadinessSummary.
      operationId: amazonWebServicesGetReadinessCheckResourceStatus
  /readinesschecks/{readinessCheckName}/status:
    GET:
      summary: Getreadinesscheckstatus
      description: >-
        Gets the readiness status for an individual readiness check. To see the
        overall readiness status for a recovery group, that considers the
        readiness status for all the readiness checks in a recovery group, use
        GetRecoveryGroupReadinessSummary.
      operationId: amazonWebServicesGetReadinessCheckStatus
  /recoverygroupreadiness/{recoveryGroupName}:
    GET:
      summary: Getrecoverygroupreadinesssummary
      description: >-
        Displays a summary of information about a recovery group's readiness
        status. Includes the readiness checks for resources in the recovery
        group and the readiness status of each one.
      operationId: amazonWebServicesGetRecoveryGroupReadinessSummary
  /rules:
    GET:
      summary: Listrules
      description: >-
        Lists all readiness rules, or lists the readiness rules for a specific
        resource type.
      operationId: amazonWebServicesListRules
  /tags/{resource-arn}:
    DELETE:
      summary: Untagresource
      description: Removes a tag from a resource.
      operationId: amazonWebServicesUntagResource
tags: []
