openapi: 3.1.0
info:
  title: route53domains
  description: >-
    <p>Amazon Route 53 API actions let you register domain names and perform
    related operations.</p>
paths:
  /:
    POST:
      summary: Viewbilling
      description: >-
        Returns all the domain-related billing records for the current Amazon
        Web Services account for a specified period
      operationId: amazonWebServicesViewBilling
tags: []
