openapi: 3.1.0
info:
  title: rum
  description: >-
    <p>With Amazon CloudWatch RUM, you can perform real-user monitoring to
    collect client-side data about your web application performance from actual
    user sessions in real time. The data collected includes page load times,
    client-side errors, and user behavior. When you view this data, you can see
    it all aggregated together and also see breakdowns by the browsers and
    devices that your customers use.</p> <p>You can use the collected data to
    quickly identify and debug client-side performance issues. CloudWatch RUM
    helps you visualize anomalies in your application performance and find
    relevant debugging data such as error messages, stack traces, and user
    sessions. You can also use RUM to understand the range of end-user impact
    including the number of users, geolocations, and browsers used.</p>
paths:
  /rummetrics/{AppMonitorName}/metrics:
    PATCH:
      summary: Updaterummetricdefinition
      description: >-
        Modifies one existing metric definition for CloudWatch RUM extended
        metrics. For more information about extended metrics, see
        BatchCreateRumMetricsDefinitions.
      operationId: amazonWebServicesUpdateRumMetricDefinition
  /appmonitor:
    POST:
      summary: Createappmonitor
      description: >-
        Creates a Amazon CloudWatch RUM app monitor, which collects telemetry
        data from your application and sends that data to RUM. The data includes
        performance and reliability information such as page load time,
        client-side errors, and user behavior. You use this operation only to
        create a new app monitor. To update an existing app monitor, use
        UpdateAppMonitor instead. After you create an app monitor, sign in to
        the CloudWatch RUM console to get the JavaScript code snippet to add to
        your web application. For more information, see How do I find a code
        snippet that I've already generated? 
      operationId: amazonWebServicesCreateAppMonitor
  /appmonitor/{Name}:
    PATCH:
      summary: Updateappmonitor
      description: >-
        Updates the configuration of an existing app monitor. When you use this
        operation, only the parts of the app monitor configuration that you
        specify in this operation are changed. For any parameters that you omit,
        the existing values are kept. You can't use this operation to change the
        tags of an existing app monitor. To change the tags of an existing app
        monitor, use TagResource. To create a new app monitor, use
        CreateAppMonitor. After you update an app monitor, sign in to the
        CloudWatch RUM console to get the updated JavaScript code snippet to add
        to your web application. For more information, see How do I find a code
        snippet that I've already generated? 
      operationId: amazonWebServicesUpdateAppMonitor
  /rummetrics/{AppMonitorName}/metricsdestination:
    POST:
      summary: Putrummetricsdestination
      description: >-
        Creates or updates a destination to receive extended metrics from
        CloudWatch RUM. You can send extended metrics to CloudWatch or to a
        CloudWatch Evidently experiment. For more information about extended
        metrics, see BatchCreateRumMetricDefinitions.
      operationId: amazonWebServicesPutRumMetricsDestination
  /appmonitor/{Name}/data:
    POST:
      summary: Getappmonitordata
      description: >-
        Retrieves the raw performance events that RUM has collected from your
        web application, so that you can do your own processing or analysis of
        this data.
      operationId: amazonWebServicesGetAppMonitorData
  /appmonitors:
    POST:
      summary: Listappmonitors
      description: Returns a list of the Amazon CloudWatch RUM app monitors in the account.
      operationId: amazonWebServicesListAppMonitors
  /tags/{ResourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes one or more tags from the specified resource.
      operationId: amazonWebServicesUntagResource
  /appmonitors/{Id}/:
    POST:
      summary: Putrumevents
      description: >-
        Sends telemetry events about your application performance and user
        behavior to CloudWatch RUM. The code snippet that RUM generates for you
        to add to your application includes PutRumEvents operations to send this
        data to RUM. Each PutRumEvents operation can send a batch of events from
        one user session.
      operationId: amazonWebServicesPutRumEvents
tags: []
