openapi: 3.1.0
info:
  title: AWS S3
  description: |-
    The API for Amazon Simple Storage Service (Amazon S3) provides an object
    storage solution with top-notch scalability, data availability, security,
    and performance. It caters to customers of varying sizes and industries,
    offering the ability to store and secure any volume of data for a wide
    range of purposes, including data lakes, cloud-native applications, and
    mobile apps. 
paths:
  /{Bucket}/{Key+}:
    PUT:
      summary: Upload Part Copy
      description: >-
        Uploads a part by copying data from an existing object as data source To
        specify the data source, you add the request header x-amz-copy-source in
        your request.
      tags:
        - Upload Part
  /{Bucket}:
    GET:
      summary: List Objects
      description: >-
        This operation is not supported by directory buckets  Returns some or
        all (up to 1,000) of the objects in a bucket
      tags:
        - Objects
  /{Bucket}/{Key+}?uploads:
    POST:
      summary: Create Multipart Upload
      description: >-
        This action initiates a multipart upload and returns an upload ID This
        upload ID is used to associate all of the parts in the specific
        multipart upload.
      tags:
        - Create Multipart Upload
  /{Bucket}?session:
    GET:
      summary: Create Session
      description: >-
        Creates a session that establishes temporary security credentials to
        support fast authentication and authorization for the Zonal endpoint
        APIs on directory buckets For more information about Zonal endpoint APIs
        that include the Availability Zone in the request endpoint, see .
      tags:
        - Create Session
  /{Bucket}?analytics:
    PUT:
      summary: Put Bucket Analytics Configuration
      description: >-
        This operation is not supported by directory buckets  Sets an analytics
        configuration for the bucket (specified by the analytics configuration
        ID)
      tags:
        - Bucket Analytics Configuration
  /{Bucket}?cors:
    PUT:
      summary: Put Bucket Cors
      description: >-
        This operation is not supported by directory buckets  Sets the cors
        configuration for your bucket
      tags:
        - Bucket CORS
  /{Bucket}?encryption:
    PUT:
      summary: Put Bucket Encryption
      description: >-
        This operation is not supported by directory buckets  This action uses
        the encryption subresource to configure default encryption and Amazon S3
        Bucket Keys for an existing bucket
      tags:
        - Bucket Encryption
  /{Bucket}?intelligent-tiering:
    PUT:
      summary: Put Bucket Intelligent Tiering Configuration
      description: >-
        This operation is not supported by directory buckets  Puts a S3
        Intelligent-Tiering configuration to the specified bucket
      tags:
        - Bucket Intelligent Tiering Configuration
  /{Bucket}?inventory:
    PUT:
      summary: Put Bucket Inventory Configuration
      description: >-
        This operation is not supported by directory buckets  This
        implementation of the PUT action adds an inventory configuration
        (identified by the inventory ID) to the bucket
      tags:
        - Bucket Inventory Configuration
  /{Bucket}?lifecycle:
    PUT:
      summary: Put Bucket Lifecycle Configuration
      description: >-
        This operation is not supported by directory buckets  Creates a new
        lifecycle configuration for the bucket or replaces an existing lifecycle
        configuration
      tags:
        - Bucket Lifecycle Configuration
  /{Bucket}?metrics:
    PUT:
      summary: Put Bucket Metrics Configuration
      description: >-
        This operation is not supported by directory buckets  Sets a metrics
        configuration (specified by the metrics configuration ID) for the bucket
      tags:
        - Bucket Metrics Configuration
  /{Bucket}?ownershipControls:
    PUT:
      summary: Put Bucket Ownership Controls
      description: >-
        This operation is not supported by directory buckets  Creates or
        modifies OwnershipControls for an Amazon S3 bucket
      tags:
        - Bucket Ownership Controls
  /{Bucket}?policy:
    PUT:
      summary: Put Bucket Policy
      description: >-
        Applies an Amazon S3 bucket policy to an Amazon S3 bucket   Directory
        buckets  - For directory buckets, you must make requests for this API
        operation to the Regional endpoint.
      tags:
        - Bucket Policy
  /{Bucket}?replication:
    PUT:
      summary: Put Bucket Replication
      description: >-
        This operation is not supported by directory buckets   Creates a
        replication configuration or replaces an existing one
      tags:
        - Bucket Replication
  /{Bucket}?tagging:
    PUT:
      summary: Put Bucket Tagging
      description: >-
        This operation is not supported by directory buckets  Sets the tags for
        a bucket
      tags:
        - Bucket Tagging
  /{Bucket}?website:
    PUT:
      summary: Put Bucket Website
      description: >-
        This operation is not supported by directory buckets  Sets the
        configuration of the website that is specified in the website
        subresource
      tags:
        - Bucket Website
  /{Bucket}/{Key+}?tagging:
    PUT:
      summary: Put Object Tagging
      description: >-
        This operation is not supported by directory buckets  Sets the supplied
        tag-set to an object that already exists in a bucket
      tags:
        - Object Tagging
  /{Bucket}?delete:
    POST:
      summary: Delete Objects
      description: >-
        This operation enables you to delete multiple objects from a bucket
        using a single HTTP request If you know the object keys that you want to
        delete, then this operation provides a suitable alternative to sending
        individual delete requests, reducing per-request overhead.
      tags:
        - Delete Objects.
  /{Bucket}?publicAccessBlock:
    PUT:
      summary: Put Public Access Block
      description: >-
        This operation is not supported by directory buckets  Creates or
        modifies the PublicAccessBlock configuration for an Amazon S3 bucket
      tags:
        - Public Access Block
  /{Bucket}?accelerate:
    PUT:
      summary: Put Bucket Accelerate Configuration
      description: >-
        This operation is not supported by directory buckets  Sets the
        accelerate configuration of an existing bucket
      tags:
        - Bucket Accelerate Configuration
  /{Bucket}?acl:
    PUT:
      summary: Put Bucket ACL
      description: >-
        This operation is not supported by directory buckets  Sets the
        permissions on an existing bucket using access control lists (ACL)
      tags:
        - Bucket ACL
  /{Bucket}?location:
    GET:
      summary: Get Bucket Location
      description: >-
        This operation is not supported by directory buckets  Returns the Region
        the bucket resides in
      tags:
        - Bucket Location
  /{Bucket}?logging:
    PUT:
      summary: Put Bucket Logging
      description: >-
        This operation is not supported by directory buckets  Set the logging
        parameters for a bucket and to specify permissions for who can view and
        modify the logging parameters
      tags:
        - Bucket Logging
  /{Bucket}?notification:
    PUT:
      summary: Put Bucket Notification Configuration
      description: >-
        This operation is not supported by directory buckets  Enables
        notifications of specified events for a bucket
      tags:
        - Bucket Notification Configuration
  /{Bucket}?policyStatus:
    GET:
      summary: Get Bucket Policy Status
      description: >-
        This operation is not supported by directory buckets  Retrieves the
        policy status for an Amazon S3 bucket, indicating whether the bucket is
        public
      tags:
        - Bucket Policy Status
  /{Bucket}?requestPayment:
    PUT:
      summary: Put Bucket Request Payment
      description: >-
        This operation is not supported by directory buckets  Sets the request
        payment configuration for a bucket
      tags:
        - Bucket Request Payment
  /{Bucket}?versioning:
    PUT:
      summary: Put Bucket Versioning
      description: >-
        This operation is not supported by directory buckets  Sets the
        versioning state of an existing bucket
      tags:
        - Bucket Versioning
  /{Bucket}/{Key+}?acl:
    PUT:
      summary: Put Object ACL
      description: >-
        This operation is not supported by directory buckets  Uses the acl
        subresource to set the access control list (ACL) permissions for a new
        or existing object in an S3 bucket
      tags:
        - Object ACL
  /{Bucket}/{Key+}?attributes:
    GET:
      summary: Get Object Attributes
      description: >-
        Retrieves all the metadata from an object without returning the object
        itself This operation is useful if you're interested only in an object's
        metadata.
      tags:
        - Object Attributes
  /{Bucket}/{Key+}?legal-hold:
    PUT:
      summary: Put Object Legal Hold
      description: >-
        This operation is not supported by directory buckets  Applies a legal
        hold configuration to the specified object
      tags:
        - Object Legal Hold
  /{Bucket}?object-lock:
    PUT:
      summary: Put Object Lock Configuration
      description: >-
        This operation is not supported by directory buckets  Places an Object
        Lock configuration on the specified bucket
      tags:
        - Object Lock Configuration
  /{Bucket}/{Key+}?retention:
    PUT:
      summary: Put Object Retention
      description: >-
        This operation is not supported by directory buckets  Places an Object
        Retention configuration on an object
      tags:
        - Object Retention
  /{Bucket}/{Key+}?torrent:
    GET:
      summary: Get Object Torrent
      description: >-
        This operation is not supported by directory buckets  Returns torrent
        files from a bucket
      tags:
        - Object Torrent
  /:
    GET:
      summary: List Directory Buckets
      description: >-
        Returns a list of all Amazon S3 directory buckets owned by the
        authenticated sender of the request For more information about directory
        buckets, see .
      tags:
        - Directory Buckets
  /{Bucket}?uploads:
    GET:
      summary: List Multipart Uploads
      description: >-
        This operation lists in-progress multipart uploads in a bucket An
        in-progress multipart upload is a multipart upload that has been
        initiated by the CreateMultipartUpload request, but has not yet been
        completed or aborted.
      tags:
        - Multipart Uploads
  /{Bucket}?versions:
    GET:
      summary: List Object Versions
      description: >-
        This operation is not supported by directory buckets  Returns metadata
        about all versions of the objects in a bucket
      tags:
        - Object Versions
  /{Bucket}?list-type=2:
    GET:
      summary: List Objects V 2
      description: >-
        Returns some or all (up to 1,000) of the objects in a bucket with each
        request You can use the request parameters as selection criteria to
        return a subset of the objects in a bucket.
      tags:
        - Objects V 2
  /{Bucket}/{Key+}?restore:
    POST:
      summary: Restore Object
      description: >-
        This operation is not supported by directory buckets  Restores an
        archived copy of an object back into Amazon S3 This functionality is not
        supported for Amazon S3 on Outposts
      tags:
        - Restore Object.
  /{Bucket}/{Key+}?select&select-type=2:
    POST:
      summary: Select Object Content
      description: >-
        This operation is not supported by directory buckets  This action
        filters the contents of an Amazon S3 object based on a simple structured
        query language (SQL) statement
      tags:
        - Select Object Content.
  /WriteGetObjectResponse:
    POST:
      summary: Write Get Object Response
      description: >-
        This operation is not supported by directory buckets  Passes transformed
        objects to a GetObject operation when using Object Lambda access points
      tags:
        - Write  Object Response.
tags: []
