openapi: 3.1.0
info:
  title: s3outposts
  description: <p>Amazon S3 on Outposts provides access to S3 on Outposts operations.</p>
paths:
  /S3Outposts/CreateEndpoint:
    POST:
      summary: Createendpoint
      description: >-
        Creates an endpoint and associates it with the specified Outpost.  It
        can take up to 5 minutes for this action to finish.   Related actions
        include:    DeleteEndpoint     ListEndpoints   
      operationId: amazonWebServicesCreateEndpoint
  /S3Outposts/DeleteEndpoint:
    DELETE:
      summary: Deleteendpoint
      description: >-
        Deletes an endpoint.  It can take up to 5 minutes for this action to
        finish.   Related actions include:    CreateEndpoint    
        ListEndpoints   
      operationId: amazonWebServicesDeleteEndpoint
  /S3Outposts/ListEndpoints:
    GET:
      summary: Listendpoints
      description: >-
        Lists endpoints associated with the specified Outpost.  Related actions
        include:    CreateEndpoint     DeleteEndpoint   
      operationId: amazonWebServicesListEndpoints
  /S3Outposts/ListOutpostsWithS3:
    GET:
      summary: Listoutpostswiths3
      description: >-
        Lists the Outposts with S3 on Outposts capacity for your Amazon Web
        Services account. Includes S3 on Outposts that you have access to as the
        Outposts owner, or as a shared user from Resource Access Manager (RAM). 
      operationId: amazonWebServicesListOutpostsWithS3
  /S3Outposts/ListSharedEndpoints:
    GET:
      summary: Listsharedendpoints
      description: >-
        Lists all endpoints associated with an Outpost that has been shared by
        Amazon Web Services Resource Access Manager (RAM). Related actions
        include:    CreateEndpoint     DeleteEndpoint   
      operationId: amazonWebServicesListSharedEndpoints
tags: []
