openapi: 3.1.0
info:
  title: sagemaker-featurestore-runtime
  description: >-
    <p>Contains all data plane API operations and data types for the Amazon
    SageMaker Feature Store. Use this API to put, delete, and retrieve (get)
    features from a feature store.</p> <p>Use the following operations to
    configure your <code>OnlineStore</code> and <code>OfflineStore</code>
    features, and to create and manage feature groups:</p> <ul> <li> <p> <a
    href="https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateFeatureGroup.html">CreateFeatureGroup</a>
    </p> </li> <li> <p> <a
    href="https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_DeleteFeatureGroup.html">DeleteFeatureGroup</a>
    </p> </li> <li> <p> <a
    href="https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_DescribeFeatureGroup.html">DescribeFeatureGroup</a>
    </p> </li> <li> <p> <a
    href="https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_ListFeatureGroups.html">ListFeatureGroups</a>
    </p> </li> </ul>
paths:
  /BatchGetRecord:
    POST:
      summary: Batchgetrecord
      description: Retrieves a batch of Records from a FeatureGroup.
      operationId: amazonWebServicesBatchGetRecord
  /FeatureGroup/{FeatureGroupName}:
    PUT:
      summary: Putrecord
      description: >-
        The PutRecord API is used to ingest a list of Records into your feature
        group.  If a new record’s EventTime is greater, the new record is
        written to both the OnlineStore and OfflineStore. Otherwise, the record
        is a historic record and it is written only to the OfflineStore.  You
        can specify the ingestion to be applied to the OnlineStore,
        OfflineStore, or both by using the TargetStores request parameter.  You
        can set the ingested record to expire at a given time to live (TTL)
        duration after the record’s event time, ExpiresAt = EventTime +
        TtlDuration, by specifying the TtlDuration parameter. A record level
        TtlDuration is set when specifying the TtlDuration parameter using the
        PutRecord API call. If the input TtlDuration is null or unspecified,
        TtlDuration is set to the default feature group level TtlDuration. A
        record level TtlDuration supersedes the group level TtlDuration.
      operationId: amazonWebServicesPutRecord
tags: []
