openapi: 3.1.0
info:
  title: sagemaker-edge
  description: >-
    <p>SageMaker Edge Manager dataplane service for communicating with active
    agents.</p>
paths:
  /GetDeployments:
    POST:
      summary: Getdeployments
      description: Use to get the active deployments from a device.
      operationId: amazonWebServicesGetDeployments
  /GetDeviceRegistration:
    POST:
      summary: Getdeviceregistration
      description: Use to check if a device is registered with SageMaker Edge Manager.
      operationId: amazonWebServicesGetDeviceRegistration
  /SendHeartbeat:
    POST:
      summary: Sendheartbeat
      description: >-
        Use to get the current status of devices registered on SageMaker Edge
        Manager.
      operationId: amazonWebServicesSendHeartbeat
tags: []
