openapi: 3.1.0
info:
  title: sagemaker-geospatial
  description: >-
    <p>Provides APIs for creating and managing SageMaker geospatial
    resources.</p>
paths:
  /earth-observation-jobs/{Arn}:
    GET:
      summary: Getearthobservationjob
      description: Get the details for a previously initiated Earth Observation job.
      operationId: amazonWebServicesGetEarthObservationJob
  /vector-enrichment-jobs/{Arn}:
    GET:
      summary: Getvectorenrichmentjob
      description: >-
        Retrieves details of a Vector Enrichment Job for a given job Amazon
        Resource Name (ARN).
      operationId: amazonWebServicesGetVectorEnrichmentJob
  /export-earth-observation-job:
    POST:
      summary: Exportearthobservationjob
      description: >-
        Use this operation to export results of an Earth Observation job and
        optionally source images used as input to the EOJ to an Amazon S3
        location.
      operationId: amazonWebServicesExportEarthObservationJob
  /export-vector-enrichment-jobs:
    POST:
      summary: Exportvectorenrichmentjob
      description: >-
        Use this operation to copy results of a Vector Enrichment job to an
        Amazon S3 location.
      operationId: amazonWebServicesExportVectorEnrichmentJob
  /raster-data-collection/{Arn}:
    GET:
      summary: Getrasterdatacollection
      description: Use this operation to get details of a specific raster data collection.
      operationId: amazonWebServicesGetRasterDataCollection
  /tile/{z}/{x}/{y}:
    GET:
      summary: Gettile
      description: Gets a web mercator tile for the given Earth Observation job.
      operationId: amazonWebServicesGetTile
  /list-earth-observation-jobs:
    POST:
      summary: Listearthobservationjobs
      description: >-
        Use this operation to get a list of the Earth Observation jobs
        associated with the calling Amazon Web Services account.
      operationId: amazonWebServicesListEarthObservationJobs
  /raster-data-collections:
    GET:
      summary: Listrasterdatacollections
      description: Use this operation to get raster data collections.
      operationId: amazonWebServicesListRasterDataCollections
  /tags/{ResourceArn}:
    DELETE:
      summary: Untagresource
      description: The resource you want to untag.
      operationId: amazonWebServicesUntagResource
  /list-vector-enrichment-jobs:
    POST:
      summary: Listvectorenrichmentjobs
      description: Retrieves a list of vector enrichment jobs.
      operationId: amazonWebServicesListVectorEnrichmentJobs
  /search-raster-data-collection:
    POST:
      summary: Searchrasterdatacollection
      description: >-
        Allows you run image query on a specific raster data collection to get a
        list of the satellite imagery matching the selected filters.
      operationId: amazonWebServicesSearchRasterDataCollection
  /earth-observation-jobs:
    POST:
      summary: Startearthobservationjob
      description: Use this operation to create an Earth observation job.
      operationId: amazonWebServicesStartEarthObservationJob
  /vector-enrichment-jobs:
    POST:
      summary: Startvectorenrichmentjob
      description: >-
        Creates a Vector Enrichment job for the supplied job type. Currently,
        there are two supported job types: reverse geocoding and map matching.
      operationId: amazonWebServicesStartVectorEnrichmentJob
  /earth-observation-jobs/stop:
    POST:
      summary: Stopearthobservationjob
      description: Use this operation to stop an existing earth observation job.
      operationId: amazonWebServicesStopEarthObservationJob
  /vector-enrichment-jobs/stop:
    POST:
      summary: Stopvectorenrichmentjob
      description: Stops the Vector Enrichment job for a given job ARN.
      operationId: amazonWebServicesStopVectorEnrichmentJob
tags: []
