openapi: 3.1.0
info:
  title: savingsplans
  description: >-
    <p>Savings Plans are a pricing model that offer significant savings on AWS
    usage (for example, on Amazon EC2 instances). You commit to a consistent
    amount of usage, in USD per hour, for a term of 1 or 3 years, and receive a
    lower price for that usage. For more information, see the <a
    href="https://docs.aws.amazon.com/savingsplans/latest/userguide/">AWS
    Savings Plans User Guide</a>.</p>
paths:
  /CreateSavingsPlan:
    POST:
      summary: Createsavingsplan
      description: Creates a Savings Plan.
      operationId: amazonWebServicesCreateSavingsPlan
  /DeleteQueuedSavingsPlan:
    POST:
      summary: Deletequeuedsavingsplan
      description: Deletes the queued purchase for the specified Savings Plan.
      operationId: amazonWebServicesDeleteQueuedSavingsPlan
  /DescribeSavingsPlanRates:
    POST:
      summary: Describesavingsplanrates
      description: Describes the specified Savings Plans rates.
      operationId: amazonWebServicesDescribeSavingsPlanRates
  /DescribeSavingsPlans:
    POST:
      summary: Describesavingsplans
      description: Describes the specified Savings Plans.
      operationId: amazonWebServicesDescribeSavingsPlans
  /DescribeSavingsPlansOfferingRates:
    POST:
      summary: Describesavingsplansofferingrates
      description: Describes the specified Savings Plans offering rates.
      operationId: amazonWebServicesDescribeSavingsPlansOfferingRates
  /DescribeSavingsPlansOfferings:
    POST:
      summary: Describesavingsplansofferings
      description: Describes the specified Savings Plans offerings.
      operationId: amazonWebServicesDescribeSavingsPlansOfferings
  /ListTagsForResource:
    POST:
      summary: Listtagsforresource
      description: Lists the tags for the specified resource.
      operationId: amazonWebServicesListTagsForResource
  /TagResource:
    POST:
      summary: Tagresource
      description: Adds the specified tags to the specified resource.
      operationId: amazonWebServicesTagResource
  /UntagResource:
    POST:
      summary: Untagresource
      description: Removes the specified tags from the specified resource.
      operationId: amazonWebServicesUntagResource
tags: []
