openapi: 3.1.0
info:
  title: schemas
  description: <p>Amazon EventBridge Schema Registry</p>
paths:
  /v1/discoverers:
    GET:
      summary: Listdiscoverers
      description: List the discoverers.
      operationId: amazonWebServicesListDiscoverers
  /v1/registries/name/{registryName}:
    PUT:
      summary: Updateregistry
      description: Updates a registry.
      operationId: amazonWebServicesUpdateRegistry
  /v1/registries/name/{registryName}/schemas/name/{schemaName}:
    PUT:
      summary: Updateschema
      description: >-
        Updates the schema definition Inactive schemas will be deleted after two
        years.
      operationId: amazonWebServicesUpdateSchema
  /v1/discoverers/id/{discovererId}:
    PUT:
      summary: Updatediscoverer
      description: Updates the discoverer
      operationId: amazonWebServicesUpdateDiscoverer
  /v1/policy:
    PUT:
      summary: Putresourcepolicy
      description: The name of the policy.
      operationId: amazonWebServicesPutResourcePolicy
  /v1/registries/name/{registryName}/schemas/name/{schemaName}/version/{schemaVersion}:
    DELETE:
      summary: Deleteschemaversion
      description: Delete the schema version definition
      operationId: amazonWebServicesDeleteSchemaVersion
  /v1/registries/name/{registryName}/schemas/name/{schemaName}/language/{language}:
    POST:
      summary: Putcodebinding
      description: Put code binding URI
      operationId: amazonWebServicesPutCodeBinding
  /v1/registries/name/{registryName}/schemas/name/{schemaName}/language/{language}/source:
    GET:
      summary: Getcodebindingsource
      description: Get the code binding source URI.
      operationId: amazonWebServicesGetCodeBindingSource
  /v1/discover:
    POST:
      summary: Getdiscoveredschema
      description: Get the discovered schema that was generated based on sampled events.
      operationId: amazonWebServicesGetDiscoveredSchema
  /v1/registries:
    GET:
      summary: Listregistries
      description: List the registries.
      operationId: amazonWebServicesListRegistries
  /v1/registries/name/{registryName}/schemas/name/{schemaName}/versions:
    GET:
      summary: Listschemaversions
      description: Provides a list of the schema versions and related information.
      operationId: amazonWebServicesListSchemaVersions
  /v1/registries/name/{registryName}/schemas:
    GET:
      summary: Listschemas
      description: List the schemas.
      operationId: amazonWebServicesListSchemas
  /tags/{resource-arn}:
    DELETE:
      summary: Untagresource
      description: Removes tags from a resource.
      operationId: amazonWebServicesUntagResource
  /v1/registries/name/{registryName}/schemas/search:
    GET:
      summary: Searchschemas
      description: Search the schemas
      operationId: amazonWebServicesSearchSchemas
  /v1/discoverers/id/{discovererId}/start:
    POST:
      summary: Startdiscoverer
      description: Starts the discoverer
      operationId: amazonWebServicesStartDiscoverer
  /v1/discoverers/id/{discovererId}/stop:
    POST:
      summary: Stopdiscoverer
      description: Stops the discoverer
      operationId: amazonWebServicesStopDiscoverer
  /v1/registries/name/{registryName}/schemas/name/{schemaName}/export:
    GET:
      summary: Exportschema
      description: Exports a schema to a different specification.
      operationId: amazonWebServicesExportSchema
tags: []
