openapi: 3.1.0
info:
  title: scheduler
  description: >-
    <p> Amazon EventBridge Scheduler is a serverless scheduler that allows you
    to create, run, and manage tasks from one central, managed service.
    EventBridge Scheduler delivers your tasks reliably, with built-in mechanisms
    that adjust your schedules based on the availability of downstream targets.
    The following reference lists the available API actions, and data types for
    EventBridge Scheduler. </p>
paths:
  /schedules/{Name}:
    PUT:
      summary: Updateschedule
      description: ' Updates the specified schedule. When you call UpdateSchedule, EventBridge Scheduler uses all values, including empty values, specified in the request and overrides the existing schedule. This is by design. This means that if you do not set an optional field in your request, that field will be set to its system-default value after the update.   Before calling this operation, we recommend that you call the GetSchedule API operation and make a note of all optional parameters for your UpdateSchedule call. '
      operationId: amazonWebServicesUpdateSchedule
  /schedule-groups/{Name}:
    GET:
      summary: Getschedulegroup
      description: Retrieves the specified schedule group.
      operationId: amazonWebServicesGetScheduleGroup
  /schedule-groups:
    GET:
      summary: Listschedulegroups
      description: Returns a paginated list of your schedule groups.
      operationId: amazonWebServicesListScheduleGroups
  /schedules:
    GET:
      summary: Listschedules
      description: Returns a paginated list of your EventBridge Scheduler schedules.
      operationId: amazonWebServicesListSchedules
  /tags/{ResourceArn}:
    DELETE:
      summary: Untagresource
      description: >-
        Removes one or more tags from the specified EventBridge Scheduler
        schedule group.
      operationId: amazonWebServicesUntagResource
tags: []
