openapi: 3.1.0
info:
  title: servicediscovery
  description: >-
    <fullname>Cloud Map</fullname> <p>With Cloud Map, you can configure public
    DNS, private DNS, or HTTP namespaces that your microservice applications run
    in. When an instance becomes available, you can call the Cloud Map API to
    register the instance with Cloud Map. For public or private DNS namespaces,
    Cloud Map automatically creates DNS records and an optional health check.
    Clients that submit public or private DNS queries, or HTTP requests, for the
    service receive an answer that contains up to eight healthy records. </p>
paths:
  /:
    POST:
      summary: Updateservice
      description: >-
        Submits a request to perform the following operations:   Update the TTL
        setting for existing DnsRecords configurations   Add, update, or delete
        HealthCheckConfig for a specified service  You can't add, update, or
        delete a HealthCheckCustomConfig configuration.    For public and
        private DNS namespaces, note the following:   If you omit any existing
        DnsRecords or HealthCheckConfig configurations from an UpdateService
        request, the configurations are deleted from the service.   If you omit
        an existing HealthCheckCustomConfig configuration from an UpdateService
        request, the configuration isn't deleted from the service.   When you
        update settings for a service, Cloud Map also updates the corresponding
        settings in all the records and health checks that were created by using
        the specified service.
      operationId: amazonWebServicesUpdateService
tags: []
