openapi: 3.1.0
info:
  title: servicecatalog-appregistry
  description: >-
    <p> Amazon Web Services Service Catalog AppRegistry enables organizations to
    understand the application context of their Amazon Web Services resources.
    AppRegistry provides a repository of your applications, their resources, and
    the application metadata that you use within your enterprise.</p>
paths:
  /applications/{application}/attribute-groups/{attributeGroup}:
    DELETE:
      summary: Disassociateattributegroup
      description: >-
        Disassociates an attribute group from an application to remove the extra
        attributes contained in the attribute group from the application's
        metadata. This operation reverts AssociateAttributeGroup.
      operationId: amazonWebServicesDisassociateAttributeGroup
  /applications/{application}/resources/{resourceType}/{resource}:
    GET:
      summary: Getassociatedresource
      description: Gets the resource associated with the application.
      operationId: amazonWebServicesGetAssociatedResource
  /applications:
    GET:
      summary: Listapplications
      description: Retrieves a list of all of your applications. Results are paginated.
      operationId: amazonWebServicesListApplications
  /attribute-groups:
    GET:
      summary: Listattributegroups
      description: >-
        Lists all attribute groups which you have access to. Results are
        paginated.
      operationId: amazonWebServicesListAttributeGroups
  /applications/{application}:
    PATCH:
      summary: Updateapplication
      description: Updates an existing application with new attributes.
      operationId: amazonWebServicesUpdateApplication
  /attribute-groups/{attributeGroup}:
    PATCH:
      summary: Updateattributegroup
      description: 'Updates an existing attribute group with new details. '
      operationId: amazonWebServicesUpdateAttributeGroup
  /configuration:
    PUT:
      summary: Putconfiguration
      description: ' Associates a TagKey configuration to an account. '
      operationId: amazonWebServicesPutConfiguration
  /applications/{application}/attribute-groups:
    GET:
      summary: Listassociatedattributegroups
      description: >-
        Lists all attribute groups that are associated with specified
        application. Results are paginated.
      operationId: amazonWebServicesListAssociatedAttributeGroups
  /applications/{application}/resources:
    GET:
      summary: Listassociatedresources
      description: ' Lists all of the resources that are associated with the specified application. Results are paginated.    If you share an application, and a consumer account associates a tag query to the application, all of the users who can access the application can also view the tag values in all accounts that are associated with it using this API.  '
      operationId: amazonWebServicesListAssociatedResources
  /applications/{application}/attribute-group-details:
    GET:
      summary: Listattributegroupsforapplication
      description: >-
        Lists the details of all attribute groups associated with a specific
        application. The results display in pages.
      operationId: amazonWebServicesListAttributeGroupsForApplication
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: >-
        Removes tags from a resource. This operation returns an empty response
        if the call was successful.
      operationId: amazonWebServicesUntagResource
  /sync/{resourceType}/{resource}:
    POST:
      summary: Syncresource
      description: >-
        Syncs the resource with current AppRegistry records. Specifically, the
        resource’s AppRegistry system tags sync with its associated application.
        We remove the resource's AppRegistry system tags if it does not
        associate with the application. The caller must have permissions to read
        and update the resource.
      operationId: amazonWebServicesSyncResource
tags: []
