openapi: 3.1.0
info:
  title: signer
  description: >-
    <p>AWS Signer is a fully managed code-signing service to help you ensure the
    trust and integrity of your code. </p> <p>Signer supports the following
    applications:</p> <p>With code signing for AWS Lambda, you can sign <a
    href="http://docs.aws.amazon.com/lambda/latest/dg/">AWS Lambda</a>
    deployment packages. Integrated support is provided for <a
    href="http://docs.aws.amazon.com/AmazonS3/latest/gsg/">Amazon S3</a>, <a
    href="http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/">Amazon
    CloudWatch</a>, and <a
    href="http://docs.aws.amazon.com/awscloudtrail/latest/userguide/">AWS
    CloudTrail</a>. In order to sign code, you create a signing profile and then
    use Signer to sign Lambda zip files in S3. </p> <p>With code signing for
    IoT, you can sign code for any IoT device that is supported by AWS. IoT code
    signing is available for <a
    href="http://docs.aws.amazon.com/freertos/latest/userguide/">Amazon
    FreeRTOS</a> and <a
    href="http://docs.aws.amazon.com/iot/latest/developerguide/">AWS IoT Device
    Management</a>, and is integrated with <a
    href="http://docs.aws.amazon.com/acm/latest/userguide/">AWS Certificate
    Manager (ACM)</a>. In order to sign code, you import a third-party
    code-signing certificate using ACM, and use that to sign updates in Amazon
    FreeRTOS and AWS IoT Device Management. </p> <p>With Signer and the Notation
    CLI from the <a href="https://notaryproject.dev/">Notary&#x2028;
    Project</a>, you can sign container images stored in a container registry
    such as Amazon Elastic Container Registry (ECR). The signatures are stored
    in the registry alongside the images, where they are available for verifying
    image authenticity and integrity.</p> <p>For more information about Signer,
    see the <a
    href="https://docs.aws.amazon.com/signer/latest/developerguide/Welcome.html">AWS
    Signer Developer Guide</a>.</p>
paths:
  /signing-profiles/{profileName}/permissions:
    GET:
      summary: Listprofilepermissions
      description: Lists the cross-account permissions associated with a signing profile.
      operationId: amazonWebServicesListProfilePermissions
  /signing-profiles/{profileName}:
    PUT:
      summary: Putsigningprofile
      description: >-
        Creates a signing profile. A signing profile is a code-signing template
        that can be used to carry out a pre-defined signing job. 
      operationId: amazonWebServicesPutSigningProfile
  /signing-jobs/{jobId}:
    GET:
      summary: Describesigningjob
      description: >-
        Returns information about a specific code signing job. You specify the
        job by using the jobId value that is returned by the StartSigningJob
        operation. 
      operationId: amazonWebServicesDescribeSigningJob
  /revocations:
    GET:
      summary: Getrevocationstatus
      description: >-
        Retrieves the revocation status of one or more of the signing profile,
        signing job, and signing certificate.
      operationId: amazonWebServicesGetRevocationStatus
  /signing-platforms/{platformId}:
    GET:
      summary: Getsigningplatform
      description: Returns information on a specific signing platform.
      operationId: amazonWebServicesGetSigningPlatform
  /signing-jobs:
    POST:
      summary: Startsigningjob
      description: >-
        Initiates a signing job to be performed on the code provided. Signing
        jobs are viewable by the ListSigningJobs operation for two years after
        they are performed. Note the following requirements:     You must create
        an Amazon S3 source bucket. For more information, see Creating a Bucket
        in the Amazon S3 Getting Started Guide.    Your S3 source bucket must be
        version enabled.   You must create an S3 destination bucket. AWS Signer
        uses your S3 destination bucket to write your signed code.   You specify
        the name of the source and destination buckets when calling the
        StartSigningJob operation.   You must also specify a request token that
        identifies your request to Signer.   You can call the DescribeSigningJob
        and the ListSigningJobs actions after you call StartSigningJob. For a
        Java example that shows how to use this action, see StartSigningJob.
      operationId: amazonWebServicesStartSigningJob
  /signing-platforms:
    GET:
      summary: Listsigningplatforms
      description: >-
        Lists all signing platforms available in AWS Signer that match the
        request parameters. If additional jobs remain to be listed, Signer
        returns a nextToken value. Use this value in subsequent calls to
        ListSigningJobs to fetch the remaining values. You can continue calling
        ListSigningJobs with your maxResults parameter and with new values that
        Signer returns in the nextToken parameter until all of your signing jobs
        have been returned.
      operationId: amazonWebServicesListSigningPlatforms
  /signing-profiles:
    GET:
      summary: Listsigningprofiles
      description: >-
        Lists all available signing profiles in your AWS account. Returns only
        profiles with an ACTIVE status unless the includeCanceled request field
        is set to true. If additional jobs remain to be listed, AWS Signer
        returns a nextToken value. Use this value in subsequent calls to
        ListSigningJobs to fetch the remaining values. You can continue calling
        ListSigningJobs with your maxResults parameter and with new values that
        Signer returns in the nextToken parameter until all of your signing jobs
        have been returned.
      operationId: amazonWebServicesListSigningProfiles
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: >-
        Removes one or more tags from a signing profile. To remove the tags,
        specify a list of tag keys.
      operationId: amazonWebServicesUntagResource
  /signing-profiles/{profileName}/permissions/{statementId}:
    DELETE:
      summary: Removeprofilepermission
      description: Removes cross-account permissions from a signing profile.
      operationId: amazonWebServicesRemoveProfilePermission
  /signing-jobs/{jobId}/revoke:
    PUT:
      summary: Revokesignature
      description: >-
        Changes the state of a signing job to REVOKED. This indicates that the
        signature is no longer valid.
      operationId: amazonWebServicesRevokeSignature
  /signing-profiles/{profileName}/revoke:
    PUT:
      summary: Revokesigningprofile
      description: >-
        Changes the state of a signing profile to REVOKED. This indicates that
        signatures generated using the signing profile after an effective start
        date are no longer valid.
      operationId: amazonWebServicesRevokeSigningProfile
  /signing-jobs/with-payload:
    POST:
      summary: Signpayload
      description: Signs a binary payload and returns a signature envelope.
      operationId: amazonWebServicesSignPayload
tags: []
