openapi: 3.1.0
info:
  title: simspaceweaver
  description: >-
    <p>SimSpace Weaver (SimSpace Weaver) is a service that you can use to build
    and run large-scale spatial simulations in the Amazon Web Services Cloud.
    For example, you can create crowd simulations, large real-world
    environments, and immersive and interactive experiences. For more
    information about SimSpace Weaver, see the <i> <a
    href="https://docs.aws.amazon.com/simspaceweaver/latest/userguide/">SimSpace
    Weaver User Guide</a> </i>.</p> <p>This API reference describes the API
    operations and data types that you can use to communicate directly with
    SimSpace Weaver.</p> <p>SimSpace Weaver also provides the SimSpace Weaver
    app SDK, which you use for app development. The SimSpace Weaver app SDK API
    reference is included in the SimSpace Weaver app SDK documentation. This
    documentation is part of the SimSpace Weaver app SDK distributable
    package.</p>
paths:
  /createsnapshot:
    POST:
      summary: Createsnapshot
      description: >-
        Creates a snapshot of the specified simulation. A snapshot is a file
        that contains simulation state data at a specific time. The state data
        saved in a snapshot includes entity data from the State Fabric, the
        simulation configuration specified in the schema, and the clock tick
        number. You can use the snapshot to initialize a new simulation. For
        more information about snapshots, see Snapshots in the SimSpace Weaver
        User Guide.  You specify a Destination when you create a snapshot. The
        Destination is the name of an Amazon S3 bucket and an optional
        ObjectKeyPrefix. The ObjectKeyPrefix is usually the name of a folder in
        the bucket. SimSpace Weaver creates a snapshot folder inside the
        Destination and places the snapshot file there. The snapshot file is an
        Amazon S3 object. It has an object key with the form: 
        object-key-prefix/snapshot/simulation-name-YYMMdd-HHmm-ss.zip,
        where:      YY  is the 2-digit year     MM  is the 2-digit month     dd 
        is the 2-digit day of the month     HH  is the 2-digit hour (24-hour
        clock)     mm  is the 2-digit minutes     ss  is the 2-digit seconds  
      operationId: amazonWebServicesCreateSnapshot
  /deleteapp:
    DELETE:
      summary: Deleteapp
      description: Deletes the instance of the given custom app.
      operationId: amazonWebServicesDeleteApp
  /deletesimulation:
    DELETE:
      summary: Deletesimulation
      description: >-
        Deletes all SimSpace Weaver resources assigned to the given simulation. 
        Your simulation uses resources in other Amazon Web Services. This API
        operation doesn't delete resources in other Amazon Web Services. 
      operationId: amazonWebServicesDeleteSimulation
  /describeapp:
    GET:
      summary: Describeapp
      description: Returns the state of the given custom app.
      operationId: amazonWebServicesDescribeApp
  /describesimulation:
    GET:
      summary: Describesimulation
      description: Returns the current state of the given simulation.
      operationId: amazonWebServicesDescribeSimulation
  /listapps:
    GET:
      summary: Listapps
      description: >-
        Lists all custom apps or service apps for the given simulation and
        domain.
      operationId: amazonWebServicesListApps
  /listsimulations:
    GET:
      summary: Listsimulations
      description: >-
        Lists the SimSpace Weaver simulations in the Amazon Web Services account
        used to make the API call.
      operationId: amazonWebServicesListSimulations
  /tags/{ResourceArn}:
    DELETE:
      summary: Untagresource
      description: >-
        Removes tags from a SimSpace Weaver resource. For more information about
        tags, see Tagging Amazon Web Services resources in the Amazon Web
        Services General Reference.
      operationId: amazonWebServicesUntagResource
  /startapp:
    POST:
      summary: Startapp
      description: >-
        Starts a custom app with the configuration specified in the simulation
        schema.
      operationId: amazonWebServicesStartApp
  /startclock:
    POST:
      summary: Startclock
      description: Starts the simulation clock.
      operationId: amazonWebServicesStartClock
  /startsimulation:
    POST:
      summary: Startsimulation
      description: >-
        Starts a simulation with the given name. You must choose to start your
        simulation from a schema or from a snapshot. For more information about
        the schema, see the schema reference in the SimSpace Weaver User Guide.
        For more information about snapshots, see Snapshots in the SimSpace
        Weaver User Guide.
      operationId: amazonWebServicesStartSimulation
  /stopapp:
    POST:
      summary: Stopapp
      description: >-
        Stops the given custom app and shuts down all of its allocated compute
        resources.
      operationId: amazonWebServicesStopApp
  /stopclock:
    POST:
      summary: Stopclock
      description: Stops the simulation clock.
      operationId: amazonWebServicesStopClock
  /stopsimulation:
    POST:
      summary: Stopsimulation
      description: >-
        Stops the given simulation.  You can't restart a simulation after you
        stop it. If you want to restart a simulation, then you must stop it,
        delete it, and start a new instance of it. 
      operationId: amazonWebServicesStopSimulation
tags: []
