openapi: 3.1.0
info:
  title: sms-voice
  description: Pinpoint SMS and Voice Messaging public facing APIs
paths:
  /v1/sms-voice/configuration-sets:
    GET:
      summary: Listconfigurationsets
      description: >-
        List all of the configuration sets associated with your Amazon Pinpoint
        account in the current region.
      operationId: amazonWebServicesListConfigurationSets
  /v1/sms-voice/configuration-sets/{ConfigurationSetName}/event-destinations:
    GET:
      summary: Getconfigurationseteventdestinations
      description: >-
        Obtain information about an event destination, including the types of
        events it reports, the Amazon Resource Name (ARN) of the destination,
        and the name of the event destination.
      operationId: amazonWebServicesGetConfigurationSetEventDestinations
  /v1/sms-voice/configuration-sets/{ConfigurationSetName}:
    DELETE:
      summary: Deleteconfigurationset
      description: Deletes an existing configuration set.
      operationId: amazonWebServicesDeleteConfigurationSet
  /v1/sms-voice/configuration-sets/{ConfigurationSetName}/event-destinations/{EventDestinationName}:
    PUT:
      summary: Updateconfigurationseteventdestination
      description: >-
        Update an event destination in a configuration set. An event destination
        is a location that you publish information about your voice calls to.
        For example, you can log an event to an Amazon CloudWatch destination
        when a call fails.
      operationId: amazonWebServicesUpdateConfigurationSetEventDestination
  /v1/sms-voice/voice/message:
    POST:
      summary: Sendvoicemessage
      description: Create a new voice message and send it to a recipient's phone number.
      operationId: amazonWebServicesSendVoiceMessage
tags: []
