openapi: 3.1.0
info:
  title: snow-device-management
  description: <p>Amazon Web Services Snow Device Management documentation.</p>
paths:
  /task/{taskId}/cancel:
    POST:
      summary: Canceltask
      description: >-
        Sends a cancel request for a specified task. You can cancel a task only
        if it's still in a QUEUED state. Tasks that are already running can't be
        cancelled.  A task might still run if it's processed from the queue
        before the CancelTask operation changes the task's state. 
      operationId: amazonWebServicesCancelTask
  /task:
    POST:
      summary: Createtask
      description: >-
        Instructs one or more devices to start a task, such as unlocking or
        rebooting.
      operationId: amazonWebServicesCreateTask
  /managed-device/{managedDeviceId}/describe:
    POST:
      summary: Describedevice
      description: >-
        Checks device-specific information, such as the device type, software
        version, IP addresses, and lock status.
      operationId: amazonWebServicesDescribeDevice
  /managed-device/{managedDeviceId}/resources/ec2/describe:
    POST:
      summary: Describedeviceec2instances
      description: >-
        Checks the current state of the Amazon EC2 instances. The output is
        similar to describeDevice, but the results are sourced from the device
        cache in the Amazon Web Services Cloud and include a subset of the
        available fields. 
      operationId: amazonWebServicesDescribeDeviceEc2Instances
  /task/{taskId}/execution/{managedDeviceId}:
    POST:
      summary: Describeexecution
      description: >-
        Checks the status of a remote task running on one or more target
        devices.
      operationId: amazonWebServicesDescribeExecution
  /task/{taskId}:
    POST:
      summary: Describetask
      description: 'Checks the metadata for a given task on a device. '
      operationId: amazonWebServicesDescribeTask
  /managed-device/{managedDeviceId}/resources:
    GET:
      summary: Listdeviceresources
      description: >-
        Returns a list of the Amazon Web Services resources available for a
        device. Currently, Amazon EC2 instances are the only supported resource
        type.
      operationId: amazonWebServicesListDeviceResources
  /managed-devices:
    GET:
      summary: Listdevices
      description: >-
        Returns a list of all devices on your Amazon Web Services account that
        have Amazon Web Services Snow Device Management enabled in the Amazon
        Web Services Region where the command is run.
      operationId: amazonWebServicesListDevices
  /executions:
    GET:
      summary: Listexecutions
      description: Returns the status of tasks for one or more target devices.
      operationId: amazonWebServicesListExecutions
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes a tag from a device or task.
      operationId: amazonWebServicesUntagResource
  /tasks:
    GET:
      summary: Listtasks
      description: Returns a list of tasks that can be filtered by state.
      operationId: amazonWebServicesListTasks
tags: []
