openapi: 3.1.0
info:
  title: ssm-sap
  description: >-
    <p>This API reference provides descriptions, syntax, and other details about
    each of the actions and data types for AWS Systems Manager for SAP. The
    topic for each action shows the API request parameters and responses. </p>
paths:
  /delete-resource-permission:
    POST:
      summary: Deleteresourcepermission
      description: Removes permissions associated with the target database.
      operationId: amazonWebServicesDeleteResourcePermission
  /deregister-application:
    POST:
      summary: Deregisterapplication
      description: >-
        Deregister an SAP application with AWS Systems Manager for SAP. This
        action does not aﬀect the existing setup of your SAP workloads on Amazon
        EC2.
      operationId: amazonWebServicesDeregisterApplication
  /get-application:
    POST:
      summary: Getapplication
      description: >-
        Gets an application registered with AWS Systems Manager for SAP. It also
        returns the components of the application.
      operationId: amazonWebServicesGetApplication
  /get-component:
    POST:
      summary: Getcomponent
      description: >-
        Gets the component of an application registered with AWS Systems Manager
        for SAP.
      operationId: amazonWebServicesGetComponent
  /get-database:
    POST:
      summary: Getdatabase
      description: >-
        Gets the SAP HANA database of an application registered with AWS Systems
        Manager for SAP.
      operationId: amazonWebServicesGetDatabase
  /get-operation:
    POST:
      summary: Getoperation
      description: Gets the details of an operation by specifying the operation ID.
      operationId: amazonWebServicesGetOperation
  /get-resource-permission:
    POST:
      summary: Getresourcepermission
      description: Gets permissions associated with the target database.
      operationId: amazonWebServicesGetResourcePermission
  /list-applications:
    POST:
      summary: Listapplications
      description: Lists all the applications registered with AWS Systems Manager for SAP.
      operationId: amazonWebServicesListApplications
  /list-components:
    POST:
      summary: Listcomponents
      description: Lists all the components registered with AWS Systems Manager for SAP.
      operationId: amazonWebServicesListComponents
  /list-databases:
    POST:
      summary: Listdatabases
      description: >-
        Lists the SAP HANA databases of an application registered with AWS
        Systems Manager for SAP.
      operationId: amazonWebServicesListDatabases
  /list-operations:
    POST:
      summary: Listoperations
      description: Lists the operations performed by AWS Systems Manager for SAP.
      operationId: amazonWebServicesListOperations
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Delete the tags for a resource.
      operationId: amazonWebServicesUntagResource
  /put-resource-permission:
    POST:
      summary: Putresourcepermission
      description: Adds permissions to the target database.
      operationId: amazonWebServicesPutResourcePermission
  /register-application:
    POST:
      summary: Registerapplication
      description: >-
        Register an SAP application with AWS Systems Manager for SAP. You must
        meet the following requirements before registering.  The SAP application
        you want to register with AWS Systems Manager for SAP is running on
        Amazon EC2. AWS Systems Manager Agent must be setup on an Amazon EC2
        instance along with the required IAM permissions. Amazon EC2 instance(s)
        must have access to the secrets created in AWS Secrets Manager to manage
        SAP applications and components.
      operationId: amazonWebServicesRegisterApplication
  /start-application-refresh:
    POST:
      summary: Startapplicationrefresh
      description: Refreshes a registered application.
      operationId: amazonWebServicesStartApplicationRefresh
  /update-application-settings:
    POST:
      summary: Updateapplicationsettings
      description: >-
        Updates the settings of an application registered with AWS Systems
        Manager for SAP.
      operationId: amazonWebServicesUpdateApplicationSettings
tags: []
