openapi: 3.1.0
info:
  title: streams.dynamodb
  description: >-
    <fullname>Amazon DynamoDB</fullname> <p>Amazon DynamoDB Streams provides API
    actions for accessing streams and processing stream records. To learn more
    about application development with Streams, see <a
    href="https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html">Capturing
    Table Activity with DynamoDB Streams</a> in the Amazon DynamoDB Developer
    Guide.</p>
paths:
  /:
    POST:
      summary: Liststreams
      description: >-
        Returns an array of stream ARNs associated with the current account and
        endpoint. If the TableName parameter is present, then ListStreams will
        return only the streams ARNs for that table.  You can call ListStreams
        at a maximum rate of 5 times per second. 
      operationId: amazonWebServicesListStreams
tags: []
