openapi: 3.1.0
info:
  title: synthetics
  description: >-
    <fullname>Amazon CloudWatch Synthetics</fullname> <p>You can use Amazon
    CloudWatch Synthetics to continually monitor your services. You can create
    and manage <i>canaries</i>, which are modular, lightweight scripts that
    monitor your endpoints and APIs from the outside-in. You can set up your
    canaries to run 24 hours a day, once per minute. The canaries help you check
    the availability and latency of your web services and troubleshoot anomalies
    by investigating load time data, screenshots of the UI, logs, and metrics.
    The canaries seamlessly integrate with CloudWatch ServiceLens to help you
    trace the causes of impacted nodes in your applications. For more
    information, see <a
    href="https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ServiceLens.html">Using
    ServiceLens to Monitor the Health of Your Applications</a> in the <i>Amazon
    CloudWatch User Guide</i>.</p> <p>Before you create and manage canaries, be
    aware of the security considerations. For more information, see <a
    href="https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/servicelens_canaries_security.html">Security
    Considerations for Synthetics Canaries</a>.</p>
paths:
  /group/{groupIdentifier}/associate:
    PATCH:
      summary: Associateresource
      description: >-
        Associates a canary with a group. Using groups can help you with
        managing and automating your canaries, and you can also view aggregated
        run results and statistics for all canaries in a group.  You must run
        this operation in the Region where the canary exists.
      operationId: amazonWebServicesAssociateResource
  /canary:
    POST:
      summary: Createcanary
      description: >-
        Creates a canary. Canaries are scripts that monitor your endpoints and
        APIs from the outside-in. Canaries help you check the availability and
        latency of your web services and troubleshoot anomalies by investigating
        load time data, screenshots of the UI, logs, and metrics. You can set up
        a canary to run continuously or just once.  Do not use CreateCanary to
        modify an existing canary. Use UpdateCanary instead. To create canaries,
        you must have the CloudWatchSyntheticsFullAccess policy. If you are
        creating a new IAM role for the canary, you also need the
        iam:CreateRole, iam:CreatePolicy and iam:AttachRolePolicy permissions.
        For more information, see Necessary Roles and Permissions. Do not
        include secrets or proprietary information in your canary names. The
        canary name makes up part of the Amazon Resource Name (ARN) for the
        canary, and the ARN is included in outbound calls over the internet. For
        more information, see Security Considerations for Synthetics Canaries.
      operationId: amazonWebServicesCreateCanary
  /group:
    POST:
      summary: Creategroup
      description: >-
        Creates a group which you can use to associate canaries with each other,
        including cross-Region canaries. Using groups can help you with managing
        and automating your canaries, and you can also view aggregated run
        results and statistics for all canaries in a group.  Groups are global
        resources. When you create a group, it is replicated across Amazon Web
        Services Regions, and you can view it and add canaries to it from any
        Region. Although the group ARN format reflects the Region name where it
        was created, a group is not constrained to any Region. This means that
        you can put canaries from multiple Regions into the same group, and then
        use that group to view and manage all of those canaries in a single
        view. Groups are supported in all Regions except the Regions that are
        disabled by default. For more information about these Regions, see
        Enabling a Region. Each group can contain as many as 10 canaries. You
        can have as many as 20 groups in your account. Any single canary can be
        a member of up to 10 groups.
      operationId: amazonWebServicesCreateGroup
  /canary/{name}:
    PATCH:
      summary: Updatecanary
      description: >-
        Updates the configuration of a canary that has already been created. You
        can't use this operation to update the tags of an existing canary. To
        change the tags of an existing canary, use TagResource.
      operationId: amazonWebServicesUpdateCanary
  /group/{groupIdentifier}:
    GET:
      summary: Getgroup
      description: >-
        Returns information about one group. Groups are a global resource, so
        you can use this operation from any Region.
      operationId: amazonWebServicesGetGroup
  /canaries:
    POST:
      summary: Describecanaries
      description: >-
        This operation returns a list of the canaries in your account, along
        with full details about each canary. This operation supports
        resource-level authorization using an IAM policy and the Names
        parameter. If you specify the Names parameter, the operation is
        successful only if you have authorization to view all the canaries that
        you specify in your request. If you do not have permission to view any
        of the canaries, the request fails with a 403 response. You are required
        to use the Names parameter if you are logged on to a user or role that
        has an IAM policy that restricts which canaries that you are allowed to
        view. For more information, see  Limiting a user to viewing specific
        canaries.
      operationId: amazonWebServicesDescribeCanaries
  /canaries/last-run:
    POST:
      summary: Describecanarieslastrun
      description: >-
        Use this operation to see information from the most recent run of each
        canary that you have created. This operation supports resource-level
        authorization using an IAM policy and the Names parameter. If you
        specify the Names parameter, the operation is successful only if you
        have authorization to view all the canaries that you specify in your
        request. If you do not have permission to view any of the canaries, the
        request fails with a 403 response. You are required to use the Names
        parameter if you are logged on to a user or role that has an IAM policy
        that restricts which canaries that you are allowed to view. For more
        information, see  Limiting a user to viewing specific canaries.
      operationId: amazonWebServicesDescribeCanariesLastRun
  /runtime-versions:
    POST:
      summary: Describeruntimeversions
      description: >-
        Returns a list of Synthetics canary runtime versions. For more
        information, see  Canary Runtime Versions.
      operationId: amazonWebServicesDescribeRuntimeVersions
  /group/{groupIdentifier}/disassociate:
    PATCH:
      summary: Disassociateresource
      description: >-
        Removes a canary from a group. You must run this operation in the Region
        where the canary exists.
      operationId: amazonWebServicesDisassociateResource
  /canary/{name}/runs:
    POST:
      summary: Getcanaryruns
      description: Retrieves a list of runs for a specified canary.
      operationId: amazonWebServicesGetCanaryRuns
  /resource/{resourceArn}/groups:
    POST:
      summary: Listassociatedgroups
      description: >-
        Returns a list of the groups that the specified canary is associated
        with. The canary that you specify must be in the current Region.
      operationId: amazonWebServicesListAssociatedGroups
  /group/{groupIdentifier}/resources:
    POST:
      summary: Listgroupresources
      description: >-
        This operation returns a list of the ARNs of the canaries that are
        associated with the specified group.
      operationId: amazonWebServicesListGroupResources
  /groups:
    POST:
      summary: Listgroups
      description: >-
        Returns a list of all groups in the account, displaying their names,
        unique IDs, and ARNs. The groups from all Regions are returned.
      operationId: amazonWebServicesListGroups
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes one or more tags from the specified resource.
      operationId: amazonWebServicesUntagResource
  /canary/{name}/start:
    POST:
      summary: Startcanary
      description: >-
        Use this operation to run a canary that has already been created. The
        frequency of the canary runs is determined by the value of the canary's
        Schedule. To see a canary's schedule, use GetCanary.
      operationId: amazonWebServicesStartCanary
  /canary/{name}/stop:
    POST:
      summary: Stopcanary
      description: >-
        Stops the canary to prevent all future runs. If the canary is currently
        running,the run that is in progress completes on its own, publishes
        metrics, and uploads artifacts, but it is not recorded in Synthetics as
        a completed run. You can use StartCanary to start it running again with
        the canary’s current schedule at any point in the future. 
      operationId: amazonWebServicesStopCanary
tags: []
