openapi: 3.1.0
info:
  title: timestream-query
  description: <fullname>Amazon Timestream Query </fullname> <p/>
paths:
  /:
    POST:
      summary: Updatescheduledquery
      description: Update a scheduled query.
      operationId: amazonWebServicesUpdateScheduledQuery
tags: []
