openapi: 3.1.0
info:
  title: tnb
  description: >-
    <p> Amazon Web Services Telco Network Builder (TNB) is a network automation
    service that helps you deploy and manage telecom networks. AWS TNB helps you
    with the lifecycle management of your telecommunication network functions
    throughout planning, deployment, and post-deployment activities.</p>
paths:
  /sol/nslcm/v1/ns_lcm_op_occs/{nsLcmOpOccId}/cancel:
    POST:
      summary: Cancelsolnetworkoperation
      description: >-
        Cancels a network operation. A network operation is any operation that
        is done to your network, such as network instance instantiation or
        termination.
      operationId: amazonWebServicesCancelSolNetworkOperation
  /sol/vnfpkgm/v1/vnf_packages:
    GET:
      summary: Listsolfunctionpackages
      description: >-
        Lists information about function packages. A function package is a .zip
        file in CSAR (Cloud Service Archive) format that contains a network
        function (an ETSI standard telecommunication application) and function
        package descriptor that uses the TOSCA standard to describe how the
        network functions should run on your network.
      operationId: amazonWebServicesListSolFunctionPackages
  /sol/nslcm/v1/ns_instances:
    GET:
      summary: Listsolnetworkinstances
      description: >-
        Lists your network instances. A network instance is a single network
        created in Amazon Web Services TNB that can be deployed and on which
        life-cycle operations (like terminate, update, and delete) can be
        performed.
      operationId: amazonWebServicesListSolNetworkInstances
  /sol/nsd/v1/ns_descriptors:
    GET:
      summary: Listsolnetworkpackages
      description: >-
        Lists network packages. A network package is a .zip file in CSAR (Cloud
        Service Archive) format defines the function packages you want to deploy
        and the Amazon Web Services infrastructure you want to deploy them on.
      operationId: amazonWebServicesListSolNetworkPackages
  /sol/vnfpkgm/v1/vnf_packages/{vnfPkgId}:
    PATCH:
      summary: Updatesolfunctionpackage
      description: >-
        Updates the operational state of function package. A function package is
        a .zip file in CSAR (Cloud Service Archive) format that contains a
        network function (an ETSI standard telecommunication application) and
        function package descriptor that uses the TOSCA standard to describe how
        the network functions should run on your network.
      operationId: amazonWebServicesUpdateSolFunctionPackage
  /sol/nslcm/v1/ns_instances/{nsInstanceId}:
    GET:
      summary: Getsolnetworkinstance
      description: >-
        Gets the details of the network instance. A network instance is a single
        network created in Amazon Web Services TNB that can be deployed and on
        which life-cycle operations (like terminate, update, and delete) can be
        performed.
      operationId: amazonWebServicesGetSolNetworkInstance
  /sol/nsd/v1/ns_descriptors/{nsdInfoId}:
    PATCH:
      summary: Updatesolnetworkpackage
      description: >-
        Updates the operational state of a network package. A network package is
        a .zip file in CSAR (Cloud Service Archive) format defines the function
        packages you want to deploy and the Amazon Web Services infrastructure
        you want to deploy them on. A network service descriptor is a .yaml file
        in a network package that uses the TOSCA standard to describe the
        network functions you want to deploy and the Amazon Web Services
        infrastructure you want to deploy the network functions on.
      operationId: amazonWebServicesUpdateSolNetworkPackage
  /sol/vnflcm/v1/vnf_instances/{vnfInstanceId}:
    GET:
      summary: Getsolfunctioninstance
      description: >-
        Gets the details of a network function instance, including the
        instantation state and metadata from the function package descriptor in
        the network function package. A network function instance is a function
        in a function package .
      operationId: amazonWebServicesGetSolFunctionInstance
  /sol/vnfpkgm/v1/vnf_packages/{vnfPkgId}/package_content:
    PUT:
      summary: Putsolfunctionpackagecontent
      description: >-
        Uploads the contents of a function package. A function package is a .zip
        file in CSAR (Cloud Service Archive) format that contains a network
        function (an ETSI standard telecommunication application) and function
        package descriptor that uses the TOSCA standard to describe how the
        network functions should run on your network.
      operationId: amazonWebServicesPutSolFunctionPackageContent
  /sol/vnfpkgm/v1/vnf_packages/{vnfPkgId}/vnfd:
    GET:
      summary: Getsolfunctionpackagedescriptor
      description: >-
        Gets a function package descriptor in a function package. A function
        package descriptor is a .yaml file in a function package that uses the
        TOSCA standard to describe how the network function in the function
        package should run on your network. A function package is a .zip file in
        CSAR (Cloud Service Archive) format that contains a network function (an
        ETSI standard telecommunication application) and function package
        descriptor that uses the TOSCA standard to describe how the network
        functions should run on your network.
      operationId: amazonWebServicesGetSolFunctionPackageDescriptor
  /sol/nslcm/v1/ns_lcm_op_occs/{nsLcmOpOccId}:
    GET:
      summary: Getsolnetworkoperation
      description: >-
        Gets the details of a network operation, including the tasks involved in
        the network operation and the status of the tasks. A network operation
        is any operation that is done to your network, such as network instance
        instantiation or termination.
      operationId: amazonWebServicesGetSolNetworkOperation
  /sol/nsd/v1/ns_descriptors/{nsdInfoId}/nsd_content:
    PUT:
      summary: Putsolnetworkpackagecontent
      description: >-
        Uploads the contents of a network package. A network package is a .zip
        file in CSAR (Cloud Service Archive) format defines the function
        packages you want to deploy and the Amazon Web Services infrastructure
        you want to deploy them on.
      operationId: amazonWebServicesPutSolNetworkPackageContent
  /sol/nsd/v1/ns_descriptors/{nsdInfoId}/nsd:
    GET:
      summary: Getsolnetworkpackagedescriptor
      description: >-
        Gets the content of the network service descriptor. A network service
        descriptor is a .yaml file in a network package that uses the TOSCA
        standard to describe the network functions you want to deploy and the
        Amazon Web Services infrastructure you want to deploy the network
        functions on.
      operationId: amazonWebServicesGetSolNetworkPackageDescriptor
  /sol/nslcm/v1/ns_instances/{nsInstanceId}/instantiate:
    POST:
      summary: Instantiatesolnetworkinstance
      description: >-
        Instantiates a network instance. A network instance is a single network
        created in Amazon Web Services TNB that can be deployed and on which
        life-cycle operations (like terminate, update, and delete) can be
        performed. Before you can instantiate a network instance, you have to
        create a network instance. For more information, see
        CreateSolNetworkInstance.
      operationId: amazonWebServicesInstantiateSolNetworkInstance
  /sol/vnflcm/v1/vnf_instances:
    GET:
      summary: Listsolfunctioninstances
      description: >-
        Lists network function instances. A network function instance is a
        function in a function package .
      operationId: amazonWebServicesListSolFunctionInstances
  /sol/nslcm/v1/ns_lcm_op_occs:
    GET:
      summary: Listsolnetworkoperations
      description: >-
        Lists details for a network operation, including when the operation
        started and the status of the operation. A network operation is any
        operation that is done to your network, such as network instance
        instantiation or termination.
      operationId: amazonWebServicesListSolNetworkOperations
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: >-
        Untags an AWS TNB resource. A tag is a label that you assign to an
        Amazon Web Services resource. Each tag consists of a key and an optional
        value. You can use tags to search and filter your resources or track
        your Amazon Web Services costs.
      operationId: amazonWebServicesUntagResource
  /sol/nslcm/v1/ns_instances/{nsInstanceId}/terminate:
    POST:
      summary: Terminatesolnetworkinstance
      description: >-
        Terminates a network instance. A network instance is a single network
        created in Amazon Web Services TNB that can be deployed and on which
        life-cycle operations (like terminate, update, and delete) can be
        performed. You must terminate a network instance before you can delete
        it.
      operationId: amazonWebServicesTerminateSolNetworkInstance
  /sol/nslcm/v1/ns_instances/{nsInstanceId}/update:
    POST:
      summary: Updatesolnetworkinstance
      description: >-
        Update a network instance. A network instance is a single network
        created in Amazon Web Services TNB that can be deployed and on which
        life-cycle operations (like terminate, update, and delete) can be
        performed.
      operationId: amazonWebServicesUpdateSolNetworkInstance
  /sol/vnfpkgm/v1/vnf_packages/{vnfPkgId}/package_content/validate:
    PUT:
      summary: Validatesolfunctionpackagecontent
      description: >-
        Validates function package content. This can be used as a dry run before
        uploading function package content with PutSolFunctionPackageContent. A
        function package is a .zip file in CSAR (Cloud Service Archive) format
        that contains a network function (an ETSI standard telecommunication
        application) and function package descriptor that uses the TOSCA
        standard to describe how the network functions should run on your
        network.
      operationId: amazonWebServicesValidateSolFunctionPackageContent
  /sol/nsd/v1/ns_descriptors/{nsdInfoId}/nsd_content/validate:
    PUT:
      summary: Validatesolnetworkpackagecontent
      description: >-
        Validates network package content. This can be used as a dry run before
        uploading network package content with PutSolNetworkPackageContent. A
        network package is a .zip file in CSAR (Cloud Service Archive) format
        defines the function packages you want to deploy and the Amazon Web
        Services infrastructure you want to deploy them on.
      operationId: amazonWebServicesValidateSolNetworkPackageContent
tags: []
