openapi: 3.1.0
info:
  title: transcribe-streaming
  description: >-
    <p>Amazon Transcribe streaming offers three main types of real-time
    transcription: <b>Standard</b>, <b>Medical</b>, and <b>Call
    Analytics</b>.</p> <ul> <li> <p> <b>Standard transcriptions</b> are the most
    common option. Refer to for details.</p> </li> <li> <p> <b>Medical
    transcriptions</b> are tailored to medical professionals and incorporate
    medical terms. A common use case for this service is transcribing
    doctor-patient dialogue in real time, so doctors can focus on their patient
    instead of taking notes. Refer to for details.</p> </li> <li> <p> <b>Call
    Analytics transcriptions</b> are designed for use with call center audio on
    two different channels; if you're looking for insight into customer service
    calls, use this option. Refer to for details.</p> </li> </ul>
paths:
  /call-analytics-stream-transcription:
    POST:
      summary: Startcallanalyticsstreamtranscription
      description: >-
        Starts a bidirectional HTTP/2 or WebSocket stream where audio is
        streamed to Amazon Transcribe and the transcription results are streamed
        to your application. Use this operation for Call Analytics
        transcriptions. The following parameters are required:   
        language-code     media-encoding     sample-rate    For more information
        on streaming with Amazon Transcribe, see Transcribing streaming audio.
      operationId: amazonWebServicesStartCallAnalyticsStreamTranscription
  /medical-stream-transcription:
    POST:
      summary: Startmedicalstreamtranscription
      description: >-
        Starts a bidirectional HTTP/2 or WebSocket stream where audio is
        streamed to Amazon Transcribe Medical and the transcription results are
        streamed to your application. The following parameters are required:   
        language-code     media-encoding     sample-rate    For more information
        on streaming with Amazon Transcribe Medical, see Transcribing streaming
        audio.
      operationId: amazonWebServicesStartMedicalStreamTranscription
  /stream-transcription:
    POST:
      summary: Startstreamtranscription
      description: >-
        Starts a bidirectional HTTP/2 or WebSocket stream where audio is
        streamed to Amazon Transcribe and the transcription results are streamed
        to your application. The following parameters are required:   
        language-code or identify-language or identify-multiple-language    
        media-encoding     sample-rate    For more information on streaming with
        Amazon Transcribe, see Transcribing streaming audio.
      operationId: amazonWebServicesStartStreamTranscription
tags: []
