openapi: 3.1.0
info:
  title: trustedadvisor
  description: <p>TrustedAdvisor Public API</p>
paths:
  /v1/organization-recommendations/{organizationRecommendationIdentifier}:
    GET:
      summary: Getorganizationrecommendation
      description: >-
        Get a specific recommendation within an AWS Organizations organization.
        This API supports only prioritized recommendations. 
      operationId: amazonWebServicesGetOrganizationRecommendation
  /v1/recommendations/{recommendationIdentifier}:
    GET:
      summary: Getrecommendation
      description: Get a specific Recommendation
      operationId: amazonWebServicesGetRecommendation
  /v1/checks:
    GET:
      summary: Listchecks
      description: List a filterable set of Checks
      operationId: amazonWebServicesListChecks
  /v1/organization-recommendations/{organizationRecommendationIdentifier}/accounts:
    GET:
      summary: Listorganizationrecommendationaccounts
      description: >-
        Lists the accounts that own the resources for an organization aggregate
        recommendation. This API only supports prioritized recommendations. 
      operationId: amazonWebServicesListOrganizationRecommendationAccounts
  /v1/organization-recommendations/{organizationRecommendationIdentifier}/resources:
    GET:
      summary: Listorganizationrecommendationresources
      description: >-
        List Resources of a Recommendation within an Organization. This API only
        supports prioritized recommendations. 
      operationId: amazonWebServicesListOrganizationRecommendationResources
  /v1/organization-recommendations:
    GET:
      summary: Listorganizationrecommendations
      description: >-
        List a filterable set of Recommendations within an Organization. This
        API only supports prioritized recommendations. 
      operationId: amazonWebServicesListOrganizationRecommendations
  /v1/recommendations/{recommendationIdentifier}/resources:
    GET:
      summary: Listrecommendationresources
      description: List Resources of a Recommendation
      operationId: amazonWebServicesListRecommendationResources
  /v1/recommendations:
    GET:
      summary: Listrecommendations
      description: List a filterable set of Recommendations
      operationId: amazonWebServicesListRecommendations
  /v1/organization-recommendations/{organizationRecommendationIdentifier}/lifecycle:
    PUT:
      summary: Updateorganizationrecommendationlifecycle
      description: >-
        Update the lifecyle of a Recommendation within an Organization. This API
        only supports prioritized recommendations. 
      operationId: amazonWebServicesUpdateOrganizationRecommendationLifecycle
  /v1/recommendations/{recommendationIdentifier}/lifecycle:
    PUT:
      summary: Updaterecommendationlifecycle
      description: >-
        Update the lifecyle of a Recommendation. This API only supports
        prioritized recommendations.
      operationId: amazonWebServicesUpdateRecommendationLifecycle
tags: []
