openapi: 3.1.0
info:
  title: voice-id
  description: >-
    <p>Amazon Connect Voice ID provides real-time caller authentication and
    fraud risk detection, which make voice interactions in contact centers more
    secure and efficient.</p>
paths:
  /:
    POST:
      summary: Updatewatchlist
      description: >-
        Updates the specified watchlist. Every domain has a default watchlist
        which cannot be updated. 
      operationId: amazonWebServicesUpdateWatchlist
tags: []
