openapi: 3.1.0
info:
  title: waf-regional
  description: >-
    <note> <p>This is <b>AWS WAF Classic Regional</b> documentation. For more
    information, see <a
    href="https://docs.aws.amazon.com/waf/latest/developerguide/classic-waf-chapter.html">AWS
    WAF Classic</a> in the developer guide.</p> <p> <b>For the latest version of
    AWS WAF</b>, use the AWS WAFV2 API and see the <a
    href="https://docs.aws.amazon.com/waf/latest/developerguide/waf-chapter.html">AWS
    WAF Developer Guide</a>. With the latest version, AWS WAF has a single set
    of endpoints for regional and global use. </p> </note> <p>This is the <i>AWS
    WAF Regional Classic API Reference</i> for using AWS WAF Classic with the
    AWS resources, Elastic Load Balancing (ELB) Application Load Balancers and
    API Gateway APIs. The AWS WAF Classic actions and data types listed in the
    reference are available for protecting Elastic Load Balancing (ELB)
    Application Load Balancers and API Gateway APIs. You can use these actions
    and data types by means of the endpoints listed in <a
    href="https://docs.aws.amazon.com/general/latest/gr/rande.html#waf_region">AWS
    Regions and Endpoints</a>. This guide is for developers who need detailed
    information about the AWS WAF Classic API actions, data types, and errors.
    For detailed information about AWS WAF Classic features and an overview of
    how to use the AWS WAF Classic API, see the <a
    href="https://docs.aws.amazon.com/waf/latest/developerguide/classic-waf-chapter.html">AWS
    WAF Classic</a> in the developer guide.</p>
paths:
  /:
    POST:
      summary: Updatexssmatchset
      description: ' This is AWS WAF Classic documentation. For more information, see AWS WAF Classic in the developer guide.  For the latest version of AWS WAF, use the AWS WAFV2 API and see the AWS WAF Developer Guide. With the latest version, AWS WAF has a single set of endpoints for regional and global use.   Inserts or deletes XssMatchTuple objects (filters) in an XssMatchSet. For each XssMatchTuple object, you specify the following values:    Action: Whether to insert the object into or delete the object from the array. To change an XssMatchTuple, you delete the existing object and add a new one.    FieldToMatch: The part of web requests that you want AWS WAF to inspect and, if you want AWS WAF to inspect a header or custom query parameter, the name of the header or parameter.    TextTransformation: Which text transformation, if any, to perform on the web request before inspecting the request for cross-site scripting attacks. You can only specify a single type of TextTransformation.   You use XssMatchSet objects to specify which CloudFront requests that you want to allow, block, or count. For example, if you''re receiving requests that contain cross-site scripting attacks in the request body and you want to block the requests, you can create an XssMatchSet with the applicable settings, and then configure AWS WAF to block the requests.  To create and configure an XssMatchSet, perform the following steps:   Submit a CreateXssMatchSet request.   Use GetChangeToken to get the change token that you provide in the ChangeToken parameter of an UpdateIPSet request.   Submit an UpdateXssMatchSet request to specify the parts of web requests that you want AWS WAF to inspect for cross-site scripting attacks.   For more information about how to use the AWS WAF API to allow or block HTTP requests, see the AWS WAF Developer Guide.'
      operationId: amazonWebServicesUpdateXssMatchSet
tags: []
