openapi: 3.1.0
info:
  title: wellarchitected
  description: >-
    <fullname>Well-Architected Tool</fullname> <p>This is the
    <i>Well-Architected Tool API Reference</i>. The WA Tool API provides
    programmatic access to the <a
    href="http://aws.amazon.com/well-architected-tool">Well-Architected Tool</a>
    in the <a href="https://console.aws.amazon.com/wellarchitected">Amazon Web
    Services Management Console</a>. For information about the Well-Architected
    Tool, see the <a
    href="https://docs.aws.amazon.com/wellarchitected/latest/userguide/intro.html">Well-Architected
    Tool User Guide</a>.</p>
paths:
  /workloads/{WorkloadId}/associateLenses:
    PATCH:
      summary: Associatelenses
      description: >-
        Associate a lens to a workload. Up to 10 lenses can be associated with a
        workload in a single API operation. A maximum of 20 lenses can be
        associated with a workload.   Disclaimer  By accessing and/or applying
        custom lenses created by another Amazon Web Services user or account,
        you acknowledge that custom lenses created by other users and shared
        with you are Third Party Content as defined in the Amazon Web Services
        Customer Agreement.  
      operationId: amazonWebServicesAssociateLenses
  /workloads/{WorkloadId}/associateProfiles:
    PATCH:
      summary: Associateprofiles
      description: Associate a profile with a workload.
      operationId: amazonWebServicesAssociateProfiles
  /lenses/{LensAlias}/shares:
    GET:
      summary: Listlensshares
      description: List the lens shares associated with the lens.
      operationId: amazonWebServicesListLensShares
  /lenses/{LensAlias}/versions:
    POST:
      summary: Createlensversion
      description: >-
        Create a new lens version. A lens can have up to 100 versions. Use this
        operation to publish a new lens version after you have imported a lens.
        The LensAlias is used to identify the lens to be published. The owner of
        a lens can share the lens with other Amazon Web Services accounts and
        users in the same Amazon Web Services Region. Only the owner of a lens
        can delete it. 
      operationId: amazonWebServicesCreateLensVersion
  /workloads/{WorkloadId}/milestones:
    POST:
      summary: Createmilestone
      description: Create a milestone for an existing workload.
      operationId: amazonWebServicesCreateMilestone
  /profiles:
    POST:
      summary: Createprofile
      description: Create a profile.
      operationId: amazonWebServicesCreateProfile
  /profiles/{ProfileArn}/shares:
    GET:
      summary: Listprofileshares
      description: List profile shares.
      operationId: amazonWebServicesListProfileShares
  /reviewTemplates:
    GET:
      summary: Listreviewtemplates
      description: List review templates.
      operationId: amazonWebServicesListReviewTemplates
  /templates/shares/{TemplateArn}:
    GET:
      summary: Listtemplateshares
      description: List review template shares.
      operationId: amazonWebServicesListTemplateShares
  /workloads:
    POST:
      summary: Createworkload
      description: >-
        Create a new workload. The owner of a workload can share the workload
        with other Amazon Web Services accounts, users, an organization, and
        organizational units (OUs) in the same Amazon Web Services Region. Only
        the owner of a workload can delete it. For more information, see
        Defining a Workload in the Well-Architected Tool User Guide.  Either
        AwsRegions, NonAwsRegions, or both must be specified when creating a
        workload. You also must specify ReviewOwner, even though the parameter
        is listed as not being required in the following section.   When
        creating a workload using a review template, you must have the following
        IAM permissions:    wellarchitected:GetReviewTemplate    
        wellarchitected:GetReviewTemplateAnswer    
        wellarchitected:ListReviewTemplateAnswers    
        wellarchitected:GetReviewTemplateLensReview   
      operationId: amazonWebServicesCreateWorkload
  /workloads/{WorkloadId}/shares:
    GET:
      summary: Listworkloadshares
      description: List the workload shares associated with the workload.
      operationId: amazonWebServicesListWorkloadShares
  /lenses/{LensAlias}:
    GET:
      summary: Getlens
      description: Get an existing lens.
      operationId: amazonWebServicesGetLens
  /lenses/{LensAlias}/shares/{ShareId}:
    DELETE:
      summary: Deletelensshare
      description: >-
        Delete a lens share. After the lens share is deleted, Amazon Web
        Services accounts, users, organizations, and organizational units (OUs)
        that you shared the lens with can continue to use it, but they will no
        longer be able to apply it to new workloads.   Disclaimer  By sharing
        your custom lenses with other Amazon Web Services accounts, you
        acknowledge that Amazon Web Services will make your custom lenses
        available to those other accounts. Those other accounts may continue to
        access and use your shared custom lenses even if you delete the custom
        lenses from your own Amazon Web Services account or terminate your
        Amazon Web Services account. 
      operationId: amazonWebServicesDeleteLensShare
  /profiles/{ProfileArn}:
    PATCH:
      summary: Updateprofile
      description: Update a profile.
      operationId: amazonWebServicesUpdateProfile
  /profiles/{ProfileArn}/shares/{ShareId}:
    DELETE:
      summary: Deleteprofileshare
      description: Delete a profile share.
      operationId: amazonWebServicesDeleteProfileShare
  /reviewTemplates/{TemplateArn}:
    PATCH:
      summary: Updatereviewtemplate
      description: Update a review template.
      operationId: amazonWebServicesUpdateReviewTemplate
  /templates/shares/{TemplateArn}/{ShareId}:
    DELETE:
      summary: Deletetemplateshare
      description: >-
        Delete a review template share. After the review template share is
        deleted, Amazon Web Services accounts, users, organizations, and
        organizational units (OUs) that you shared the review template with will
        no longer be able to apply it to new workloads.
      operationId: amazonWebServicesDeleteTemplateShare
  /workloads/{WorkloadId}:
    PATCH:
      summary: Updateworkload
      description: Update an existing workload.
      operationId: amazonWebServicesUpdateWorkload
  /workloads/{WorkloadId}/shares/{ShareId}:
    PATCH:
      summary: Updateworkloadshare
      description: Update a workload share.
      operationId: amazonWebServicesUpdateWorkloadShare
  /workloads/{WorkloadId}/disassociateLenses:
    PATCH:
      summary: Disassociatelenses
      description: >-
        Disassociate a lens from a workload. Up to 10 lenses can be
        disassociated from a workload in a single API operation.  The Amazon Web
        Services Well-Architected Framework lens (wellarchitected) cannot be
        removed from a workload. 
      operationId: amazonWebServicesDisassociateLenses
  /workloads/{WorkloadId}/disassociateProfiles:
    PATCH:
      summary: Disassociateprofiles
      description: Disassociate a profile from a workload.
      operationId: amazonWebServicesDisassociateProfiles
  /lenses/{LensAlias}/export:
    GET:
      summary: Exportlens
      description: >-
        Export an existing lens. Only the owner of a lens can export it. Lenses
        provided by Amazon Web Services (Amazon Web Services Official Content)
        cannot be exported. Lenses are defined in JSON. For more information,
        see JSON format specification in the Well-Architected Tool User Guide.  
        Disclaimer  Do not include or gather personal identifiable information
        (PII) of end users or other identifiable individuals in or via your
        custom lenses. If your custom lens or those shared with you and used in
        your account do include or collect PII you are responsible for: ensuring
        that the included PII is processed in accordance with applicable law,
        providing adequate privacy notices, and obtaining necessary consents for
        processing such data. 
      operationId: amazonWebServicesExportLens
  /workloads/{WorkloadId}/lensReviews/{LensAlias}/answers/{QuestionId}:
    PATCH:
      summary: Updateanswer
      description: Update the answer to a specific question in a workload review.
      operationId: amazonWebServicesUpdateAnswer
  /consolidatedReport:
    GET:
      summary: Getconsolidatedreport
      description: >-
        Get a consolidated report of your workloads. You can optionally choose
        to include workloads that have been shared with you.
      operationId: amazonWebServicesGetConsolidatedReport
  /workloads/{WorkloadId}/lensReviews/{LensAlias}:
    PATCH:
      summary: Updatelensreview
      description: Update lens review for a particular workload.
      operationId: amazonWebServicesUpdateLensReview
  /workloads/{WorkloadId}/lensReviews/{LensAlias}/report:
    GET:
      summary: Getlensreviewreport
      description: Get lens review report.
      operationId: amazonWebServicesGetLensReviewReport
  /lenses/{LensAlias}/versionDifference:
    GET:
      summary: Getlensversiondifference
      description: Get lens version differences.
      operationId: amazonWebServicesGetLensVersionDifference
  /workloads/{WorkloadId}/milestones/{MilestoneNumber}:
    GET:
      summary: Getmilestone
      description: Get a milestone for an existing workload.
      operationId: amazonWebServicesGetMilestone
  /profileTemplate:
    GET:
      summary: Getprofiletemplate
      description: Get profile template.
      operationId: amazonWebServicesGetProfileTemplate
  /reviewTemplates/{TemplateArn}/lensReviews/{LensAlias}/answers/{QuestionId}:
    PATCH:
      summary: Updatereviewtemplateanswer
      description: Update a review template answer.
      operationId: amazonWebServicesUpdateReviewTemplateAnswer
  /reviewTemplates/{TemplateArn}/lensReviews/{LensAlias}:
    PATCH:
      summary: Updatereviewtemplatelensreview
      description: Update a lens review associated with a review template.
      operationId: amazonWebServicesUpdateReviewTemplateLensReview
  /importLens:
    PUT:
      summary: Importlens
      description: >-
        Import a new custom lens or update an existing custom lens. To update an
        existing custom lens, specify its ARN as the LensAlias. If no ARN is
        specified, a new custom lens is created. The new or updated lens will
        have a status of DRAFT. The lens cannot be applied to workloads or
        shared with other Amazon Web Services accounts until it's published with
        CreateLensVersion. Lenses are defined in JSON. For more information, see
        JSON format specification in the Well-Architected Tool User Guide. A
        custom lens cannot exceed 500 KB in size.   Disclaimer  Do not include
        or gather personal identifiable information (PII) of end users or other
        identifiable individuals in or via your custom lenses. If your custom
        lens or those shared with you and used in your account do include or
        collect PII you are responsible for: ensuring that the included PII is
        processed in accordance with applicable law, providing adequate privacy
        notices, and obtaining necessary consents for processing such data. 
      operationId: amazonWebServicesImportLens
  /workloads/{WorkloadId}/lensReviews/{LensAlias}/answers:
    GET:
      summary: Listanswers
      description: List of answers for a particular workload and lens.
      operationId: amazonWebServicesListAnswers
  /workloads/{WorkloadId}/checks:
    POST:
      summary: Listcheckdetails
      description: >-
        List of Trusted Advisor check details by account related to the
        workload.
      operationId: amazonWebServicesListCheckDetails
  /workloads/{WorkloadId}/checkSummaries:
    POST:
      summary: Listchecksummaries
      description: >-
        List of Trusted Advisor checks summarized for all accounts related to
        the workload.
      operationId: amazonWebServicesListCheckSummaries
  /workloads/{WorkloadId}/lensReviews/{LensAlias}/improvements:
    GET:
      summary: Listlensreviewimprovements
      description: List lens review improvements.
      operationId: amazonWebServicesListLensReviewImprovements
  /workloads/{WorkloadId}/lensReviews:
    GET:
      summary: Listlensreviews
      description: List lens reviews for a particular workload.
      operationId: amazonWebServicesListLensReviews
  /lenses:
    GET:
      summary: Listlenses
      description: List the available lenses.
      operationId: amazonWebServicesListLenses
  /workloads/{WorkloadId}/milestonesSummaries:
    POST:
      summary: Listmilestones
      description: List all milestones for an existing workload.
      operationId: amazonWebServicesListMilestones
  /notifications:
    POST:
      summary: Listnotifications
      description: List lens notifications.
      operationId: amazonWebServicesListNotifications
  /profileNotifications/:
    GET:
      summary: Listprofilenotifications
      description: List profile notifications.
      operationId: amazonWebServicesListProfileNotifications
  /profileSummaries:
    GET:
      summary: Listprofiles
      description: List profiles.
      operationId: amazonWebServicesListProfiles
  /reviewTemplates/{TemplateArn}/lensReviews/{LensAlias}/answers:
    GET:
      summary: Listreviewtemplateanswers
      description: List the answers of a review template.
      operationId: amazonWebServicesListReviewTemplateAnswers
  /shareInvitations:
    GET:
      summary: Listshareinvitations
      description: >-
        List the share invitations.  WorkloadNamePrefix, LensNamePrefix,
        ProfileNamePrefix, and TemplateNamePrefix are mutually exclusive. Use
        the parameter that matches your ShareResourceType.
      operationId: amazonWebServicesListShareInvitations
  /tags/{WorkloadArn}:
    DELETE:
      summary: Untagresource
      description: >-
        Deletes specified tags from a resource.  The WorkloadArn parameter can
        be a workload ARN, a custom lens ARN, a profile ARN, or review template
        ARN.  To specify multiple tags, use separate tagKeys parameters, for
        example:  DELETE /tags/WorkloadArn?tagKeys=key1&amp;tagKeys=key2 
      operationId: amazonWebServicesUntagResource
  /workloadsSummaries:
    POST:
      summary: Listworkloads
      description: Paginated list of workloads.
      operationId: amazonWebServicesListWorkloads
  /global-settings:
    PATCH:
      summary: Updateglobalsettings
      description: >-
        Updates whether the Amazon Web Services account is opted into
        organization sharing and discovery integration features.
      operationId: amazonWebServicesUpdateGlobalSettings
  /shareInvitations/{ShareInvitationId}:
    PATCH:
      summary: Updateshareinvitation
      description: >-
        Update a workload or custom lens share invitation.  This API operation
        can be called independently of any resource. Previous documentation
        implied that a workload ARN must be specified. 
      operationId: amazonWebServicesUpdateShareInvitation
  /workloads/{WorkloadId}/lensReviews/{LensAlias}/upgrade:
    PUT:
      summary: Upgradelensreview
      description: Upgrade lens review for a particular workload.
      operationId: amazonWebServicesUpgradeLensReview
  /workloads/{WorkloadId}/profiles/{ProfileArn}/upgrade:
    PUT:
      summary: Upgradeprofileversion
      description: Upgrade a profile.
      operationId: amazonWebServicesUpgradeProfileVersion
  /reviewTemplates/{TemplateArn}/lensReviews/{LensAlias}/upgrade:
    PUT:
      summary: Upgradereviewtemplatelensreview
      description: Upgrade the lens review of a review template.
      operationId: amazonWebServicesUpgradeReviewTemplateLensReview
tags: []
