openapi: 3.1.0
info:
  title: wisdom
  description: >-
    <p>Amazon Connect Wisdom delivers agents the information they need to solve
    customer issues as they're actively speaking with customers. Agents can
    search across connected repositories from within their agent desktop to find
    answers quickly. Use Amazon Connect Wisdom to create an assistant and a
    knowledge base, for example, or manage content by uploading custom
    files.</p>
paths:
  /assistants:
    GET:
      summary: Listassistants
      description: Lists information about assistants.
      operationId: amazonWebServicesListAssistants
  /assistants/{assistantId}/associations:
    GET:
      summary: Listassistantassociations
      description: Lists information about assistant associations.
      operationId: amazonWebServicesListAssistantAssociations
  /knowledgeBases/{knowledgeBaseId}/contents:
    GET:
      summary: Listcontents
      description: Lists the content.
      operationId: amazonWebServicesListContents
  /knowledgeBases:
    GET:
      summary: Listknowledgebases
      description: Lists the knowledge bases.
      operationId: amazonWebServicesListKnowledgeBases
  /knowledgeBases/{knowledgeBaseId}/quickResponses:
    GET:
      summary: Listquickresponses
      description: Lists information about quick response.
      operationId: amazonWebServicesListQuickResponses
  /assistants/{assistantId}/sessions:
    POST:
      summary: Createsession
      description: >-
        Creates a session. A session is a contextual container used for
        generating recommendations. Amazon Connect creates a new Wisdom session
        for each contact on which Wisdom is enabled.
      operationId: amazonWebServicesCreateSession
  /assistants/{assistantId}:
    GET:
      summary: Getassistant
      description: Retrieves information about an assistant.
      operationId: amazonWebServicesGetAssistant
  /assistants/{assistantId}/associations/{assistantAssociationId}:
    GET:
      summary: Getassistantassociation
      description: Retrieves information about an assistant association.
      operationId: amazonWebServicesGetAssistantAssociation
  /knowledgeBases/{knowledgeBaseId}/contents/{contentId}:
    POST:
      summary: Updatecontent
      description: Updates information about the content.
      operationId: amazonWebServicesUpdateContent
  /knowledgeBases/{knowledgeBaseId}/importJobs/{importJobId}:
    GET:
      summary: Getimportjob
      description: Retrieves the started import job.
      operationId: amazonWebServicesGetImportJob
  /knowledgeBases/{knowledgeBaseId}:
    GET:
      summary: Getknowledgebase
      description: Retrieves information about the knowledge base.
      operationId: amazonWebServicesGetKnowledgeBase
  /knowledgeBases/{knowledgeBaseId}/quickResponses/{quickResponseId}:
    POST:
      summary: Updatequickresponse
      description: Updates an existing Wisdom quick response.
      operationId: amazonWebServicesUpdateQuickResponse
  /knowledgeBases/{knowledgeBaseId}/contents/{contentId}/summary:
    GET:
      summary: Getcontentsummary
      description: Retrieves summary information about the content.
      operationId: amazonWebServicesGetContentSummary
  /assistants/{assistantId}/sessions/{sessionId}/recommendations:
    GET:
      summary: Getrecommendations
      description: >-
        Retrieves recommendations for the specified session. To avoid retrieving
        the same recommendations in subsequent calls, use
        NotifyRecommendationsReceived. This API supports long-polling behavior
        with the waitTimeSeconds parameter. Short poll is the default behavior
        and only returns recommendations already available. To perform a manual
        query against an assistant, use QueryAssistant.
      operationId: amazonWebServicesGetRecommendations
  /assistants/{assistantId}/sessions/{sessionId}:
    GET:
      summary: Getsession
      description: Retrieves information for a specified session.
      operationId: amazonWebServicesGetSession
  /knowledgeBases/{knowledgeBaseId}/importJobs:
    POST:
      summary: Startimportjob
      description: >-
        Start an asynchronous job to import Wisdom resources from an uploaded
        source file. Before calling this API, use StartContentUpload to upload
        an asset that contains the resource data.   For importing Wisdom quick
        responses, you need to upload a csv file including the quick responses.
        For information about how to format the csv file for importing quick
        responses, see Import quick responses.  
      operationId: amazonWebServicesStartImportJob
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes the specified tags from the specified resource.
      operationId: amazonWebServicesUntagResource
  /assistants/{assistantId}/sessions/{sessionId}/recommendations/notify:
    POST:
      summary: Notifyrecommendationsreceived
      description: >-
        Removes the specified recommendations from the specified assistant's
        queue of newly available recommendations. You can use this API in
        conjunction with GetRecommendations and a waitTimeSeconds input for
        long-polling behavior and avoiding duplicate recommendations.
      operationId: amazonWebServicesNotifyRecommendationsReceived
  /assistants/{assistantId}/query:
    POST:
      summary: Queryassistant
      description: >-
        Performs a manual search against the specified assistant. To retrieve
        recommendations for an assistant, use GetRecommendations. 
      operationId: amazonWebServicesQueryAssistant
  /knowledgeBases/{knowledgeBaseId}/templateUri:
    POST:
      summary: Updateknowledgebasetemplateuri
      description: >-
        Updates the template URI of a knowledge base. This is only supported for
        knowledge bases of type EXTERNAL. Include a single variable in
        ${variable} format; this interpolated by Wisdom using ingested content.
        For example, if you ingest a Salesforce article, it has an Id value, and
        you can set the template URI to
        https://myInstanceName.lightning.force.com/lightning/r/Knowledge__kav/*${Id}*/view. 
      operationId: amazonWebServicesUpdateKnowledgeBaseTemplateUri
  /knowledgeBases/{knowledgeBaseId}/search:
    POST:
      summary: Searchcontent
      description: >-
        Searches for content in a specified knowledge base. Can be used to get a
        specific content resource by its name.
      operationId: amazonWebServicesSearchContent
  /knowledgeBases/{knowledgeBaseId}/search/quickResponses:
    POST:
      summary: Searchquickresponses
      description: Searches existing Wisdom quick responses in a Wisdom knowledge base.
      operationId: amazonWebServicesSearchQuickResponses
  /assistants/{assistantId}/searchSessions:
    POST:
      summary: Searchsessions
      description: Searches for sessions.
      operationId: amazonWebServicesSearchSessions
  /knowledgeBases/{knowledgeBaseId}/upload:
    POST:
      summary: Startcontentupload
      description: >-
        Get a URL to upload content to a knowledge base. To upload content,
        first make a PUT request to the returned URL with your file, making sure
        to include the required headers. Then use CreateContent to finalize the
        content creation process or UpdateContent to modify an existing
        resource. You can only upload content to a knowledge base of type
        CUSTOM.
      operationId: amazonWebServicesStartContentUpload
tags: []
