openapi: 3.1.0
info:
  title: worklink
  description: >-
    <p>Amazon WorkLink is a cloud-based service that provides secure access to
    internal websites and web apps from iOS and Android phones. In a single
    step, your users, such as employees, can access internal websites as
    efficiently as they access any other public website. They enter a URL in
    their web browser, or choose a link to an internal website in an email.
    Amazon WorkLink authenticates the user's access and securely renders
    authorized internal web content in a secure rendering service in the AWS
    cloud. Amazon WorkLink doesn't download or store any internal web content on
    mobile devices.</p>
paths:
  /associateDomain:
    POST:
      summary: Associatedomain
      description: Specifies a domain to be associated to Amazon WorkLink.
      operationId: amazonWebServicesAssociateDomain
  /associateWebsiteAuthorizationProvider:
    POST:
      summary: Associatewebsiteauthorizationprovider
      description: >-
        Associates a website authorization provider with a specified fleet. This
        is used to authorize users against associated websites in the company
        network.
      operationId: amazonWebServicesAssociateWebsiteAuthorizationProvider
  /associateWebsiteCertificateAuthority:
    POST:
      summary: Associatewebsitecertificateauthority
      description: >-
        Imports the root certificate of a certificate authority (CA) used to
        obtain TLS certificates used by associated websites within the company
        network.
      operationId: amazonWebServicesAssociateWebsiteCertificateAuthority
  /createFleet:
    POST:
      summary: Createfleet
      description: >-
        Creates a fleet. A fleet consists of resources and the configuration
        that delivers associated websites to authorized users who download and
        set up the Amazon WorkLink app.
      operationId: amazonWebServicesCreateFleet
  /deleteFleet:
    POST:
      summary: Deletefleet
      description: >-
        Deletes a fleet. Prevents users from accessing previously associated
        websites. 
      operationId: amazonWebServicesDeleteFleet
  /describeAuditStreamConfiguration:
    POST:
      summary: Describeauditstreamconfiguration
      description: >-
        Describes the configuration for delivering audit streams to the customer
        account.
      operationId: amazonWebServicesDescribeAuditStreamConfiguration
  /describeCompanyNetworkConfiguration:
    POST:
      summary: Describecompanynetworkconfiguration
      description: >-
        Describes the networking configuration to access the internal websites
        associated with the specified fleet.
      operationId: amazonWebServicesDescribeCompanyNetworkConfiguration
  /describeDevice:
    POST:
      summary: Describedevice
      description: Provides information about a user's device.
      operationId: amazonWebServicesDescribeDevice
  /describeDevicePolicyConfiguration:
    POST:
      summary: Describedevicepolicyconfiguration
      description: Describes the device policy configuration for the specified fleet.
      operationId: amazonWebServicesDescribeDevicePolicyConfiguration
  /describeDomain:
    POST:
      summary: Describedomain
      description: Provides information about the domain.
      operationId: amazonWebServicesDescribeDomain
  /describeFleetMetadata:
    POST:
      summary: Describefleetmetadata
      description: >-
        Provides basic information for the specified fleet, excluding identity
        provider, networking, and device configuration details.
      operationId: amazonWebServicesDescribeFleetMetadata
  /describeIdentityProviderConfiguration:
    POST:
      summary: Describeidentityproviderconfiguration
      description: Describes the identity provider configuration of the specified fleet.
      operationId: amazonWebServicesDescribeIdentityProviderConfiguration
  /describeWebsiteCertificateAuthority:
    POST:
      summary: Describewebsitecertificateauthority
      description: Provides information about the certificate authority.
      operationId: amazonWebServicesDescribeWebsiteCertificateAuthority
  /disassociateDomain:
    POST:
      summary: Disassociatedomain
      description: >-
        Disassociates a domain from Amazon WorkLink. End users lose the ability
        to access the domain with Amazon WorkLink. 
      operationId: amazonWebServicesDisassociateDomain
  /disassociateWebsiteAuthorizationProvider:
    POST:
      summary: Disassociatewebsiteauthorizationprovider
      description: >-
        Disassociates a website authorization provider from a specified fleet.
        After the disassociation, users can't load any associated websites that
        require this authorization provider.
      operationId: amazonWebServicesDisassociateWebsiteAuthorizationProvider
  /disassociateWebsiteCertificateAuthority:
    POST:
      summary: Disassociatewebsitecertificateauthority
      description: Removes a certificate authority (CA).
      operationId: amazonWebServicesDisassociateWebsiteCertificateAuthority
  /listDevices:
    POST:
      summary: Listdevices
      description: Retrieves a list of devices registered with the specified fleet.
      operationId: amazonWebServicesListDevices
  /listDomains:
    POST:
      summary: Listdomains
      description: Retrieves a list of domains associated to a specified fleet.
      operationId: amazonWebServicesListDomains
  /listFleets:
    POST:
      summary: Listfleets
      description: Retrieves a list of fleets for the current account and Region.
      operationId: amazonWebServicesListFleets
  /tags/{ResourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes one or more tags from the specified resource.
      operationId: amazonWebServicesUntagResource
  /listWebsiteAuthorizationProviders:
    POST:
      summary: Listwebsiteauthorizationproviders
      description: >-
        Retrieves a list of website authorization providers associated with a
        specified fleet.
      operationId: amazonWebServicesListWebsiteAuthorizationProviders
  /listWebsiteCertificateAuthorities:
    POST:
      summary: Listwebsitecertificateauthorities
      description: >-
        Retrieves a list of certificate authorities added for the current
        account and Region.
      operationId: amazonWebServicesListWebsiteCertificateAuthorities
  /restoreDomainAccess:
    POST:
      summary: Restoredomainaccess
      description: Moves a domain to ACTIVE status if it was in the INACTIVE status.
      operationId: amazonWebServicesRestoreDomainAccess
  /revokeDomainAccess:
    POST:
      summary: Revokedomainaccess
      description: Moves a domain to INACTIVE status if it was in the ACTIVE status.
      operationId: amazonWebServicesRevokeDomainAccess
  /signOutUser:
    POST:
      summary: Signoutuser
      description: >-
        Signs the user out from all of their devices. The user can sign in again
        if they have valid credentials.
      operationId: amazonWebServicesSignOutUser
  /updateAuditStreamConfiguration:
    POST:
      summary: Updateauditstreamconfiguration
      description: Updates the audit stream configuration for the fleet.
      operationId: amazonWebServicesUpdateAuditStreamConfiguration
  /updateCompanyNetworkConfiguration:
    POST:
      summary: Updatecompanynetworkconfiguration
      description: Updates the company network configuration for the fleet.
      operationId: amazonWebServicesUpdateCompanyNetworkConfiguration
  /updateDevicePolicyConfiguration:
    POST:
      summary: Updatedevicepolicyconfiguration
      description: Updates the device policy configuration for the fleet.
      operationId: amazonWebServicesUpdateDevicePolicyConfiguration
  /updateDomainMetadata:
    POST:
      summary: Updatedomainmetadata
      description: Updates domain metadata, such as DisplayName.
      operationId: amazonWebServicesUpdateDomainMetadata
  /UpdateFleetMetadata:
    POST:
      summary: Updatefleetmetadata
      description: Updates fleet metadata, such as DisplayName.
      operationId: amazonWebServicesUpdateFleetMetadata
  /updateIdentityProviderConfiguration:
    POST:
      summary: Updateidentityproviderconfiguration
      description: Updates the identity provider configuration for the fleet.
      operationId: amazonWebServicesUpdateIdentityProviderConfiguration
tags: []
