openapi: 3.1.0
info:
  title: workmailmessageflow
  description: >-
    <p>The WorkMail Message Flow API provides access to email messages as they
    are being sent and received by a WorkMail organization.</p>
paths:
  /messages/{messageId}:
    POST:
      summary: Putrawmessagecontent
      description: >-
        Updates the raw content of an in-transit email message, in MIME format.
        This example describes how to update in-transit email message. For more
        information and examples for using this API, see  Updating message
        content with AWS Lambda.  Updates to an in-transit message only appear
        when you call PutRawMessageContent from an AWS Lambda function
        configured with a synchronous  Run Lambda rule. If you call
        PutRawMessageContent on a delivered or sent message, the message remains
        unchanged, even though GetRawMessageContent returns an updated
        message.  
      operationId: amazonWebServicesPutRawMessageContent
tags: []
