openapi: 3.1.0
info:
  title: workspaces-web
  description: >-
    <p>WorkSpaces Web is a low cost, fully managed WorkSpace built specifically
    to facilitate secure, web-based workloads. WorkSpaces Web makes it easy for
    customers to safely provide their employees with access to internal websites
    and SaaS web applications without the administrative burden of appliances or
    specialized client software. WorkSpaces Web provides simple policy tools
    tailored for user interactions, while offloading common tasks like capacity
    management, scaling, and maintaining browser images.</p>
paths:
  /portals/{portalArn+}/browserSettings:
    DELETE:
      summary: Disassociatebrowsersettings
      description: Disassociates browser settings from a web portal.
      operationId: amazonWebServicesDisassociateBrowserSettings
  /portals/{portalArn+}/ipAccessSettings:
    DELETE:
      summary: Disassociateipaccesssettings
      description: Disassociates IP access settings from a web portal.
      operationId: amazonWebServicesDisassociateIpAccessSettings
  /portals/{portalArn+}/networkSettings:
    DELETE:
      summary: Disassociatenetworksettings
      description: Disassociates network settings from a web portal.
      operationId: amazonWebServicesDisassociateNetworkSettings
  /portals/{portalArn+}/trustStores:
    DELETE:
      summary: Disassociatetruststore
      description: Disassociates a trust store from a web portal.
      operationId: amazonWebServicesDisassociateTrustStore
  /portals/{portalArn+}/userAccessLoggingSettings:
    DELETE:
      summary: Disassociateuseraccessloggingsettings
      description: Disassociates user access logging settings from a web portal.
      operationId: amazonWebServicesDisassociateUserAccessLoggingSettings
  /portals/{portalArn+}/userSettings:
    DELETE:
      summary: Disassociateusersettings
      description: Disassociates user settings from a web portal.
      operationId: amazonWebServicesDisassociateUserSettings
  /browserSettings:
    GET:
      summary: Listbrowsersettings
      description: Retrieves a list of browser settings.
      operationId: amazonWebServicesListBrowserSettings
  /identityProviders:
    POST:
      summary: Createidentityprovider
      description: >-
        Creates an identity provider resource that is then associated with a web
        portal.
      operationId: amazonWebServicesCreateIdentityProvider
  /ipAccessSettings:
    GET:
      summary: Listipaccesssettings
      description: Retrieves a list of IP access settings.
      operationId: amazonWebServicesListIpAccessSettings
  /networkSettings:
    GET:
      summary: Listnetworksettings
      description: Retrieves a list of network settings.
      operationId: amazonWebServicesListNetworkSettings
  /portals:
    GET:
      summary: Listportals
      description: Retrieves a list or web portals.
      operationId: amazonWebServicesListPortals
  /trustStores:
    GET:
      summary: Listtruststores
      description: Retrieves a list of trust stores.
      operationId: amazonWebServicesListTrustStores
  /userAccessLoggingSettings:
    GET:
      summary: Listuseraccessloggingsettings
      description: Retrieves a list of user access logging settings.
      operationId: amazonWebServicesListUserAccessLoggingSettings
  /userSettings:
    GET:
      summary: Listusersettings
      description: Retrieves a list of user settings.
      operationId: amazonWebServicesListUserSettings
  /browserSettings/{browserSettingsArn+}:
    PATCH:
      summary: Updatebrowsersettings
      description: Updates browser settings.
      operationId: amazonWebServicesUpdateBrowserSettings
  /identityProviders/{identityProviderArn+}:
    PATCH:
      summary: Updateidentityprovider
      description: 'Updates the identity provider. '
      operationId: amazonWebServicesUpdateIdentityProvider
  /ipAccessSettings/{ipAccessSettingsArn+}:
    PATCH:
      summary: Updateipaccesssettings
      description: Updates IP access settings.
      operationId: amazonWebServicesUpdateIpAccessSettings
  /networkSettings/{networkSettingsArn+}:
    PATCH:
      summary: Updatenetworksettings
      description: Updates network settings.
      operationId: amazonWebServicesUpdateNetworkSettings
  /portals/{portalArn+}:
    PUT:
      summary: Updateportal
      description: Updates a web portal.
      operationId: amazonWebServicesUpdatePortal
  /trustStores/{trustStoreArn+}:
    PATCH:
      summary: Updatetruststore
      description: Updates the trust store.
      operationId: amazonWebServicesUpdateTrustStore
  /userAccessLoggingSettings/{userAccessLoggingSettingsArn+}:
    PATCH:
      summary: Updateuseraccessloggingsettings
      description: Updates the user access logging settings.
      operationId: amazonWebServicesUpdateUserAccessLoggingSettings
  /userSettings/{userSettingsArn+}:
    PATCH:
      summary: Updateusersettings
      description: Updates the user settings.
      operationId: amazonWebServicesUpdateUserSettings
  /portalIdp/{portalArn+}:
    GET:
      summary: Getportalserviceprovidermetadata
      description: Gets the service provider metadata.
      operationId: amazonWebServicesGetPortalServiceProviderMetadata
  /trustStores/{trustStoreArn+}/certificate:
    GET:
      summary: Gettruststorecertificate
      description: Gets the trust store certificate.
      operationId: amazonWebServicesGetTrustStoreCertificate
  /portals/{portalArn+}/identityProviders:
    GET:
      summary: Listidentityproviders
      description: Retrieves a list of identity providers for a specific web portal.
      operationId: amazonWebServicesListIdentityProviders
  /tags/{resourceArn+}:
    DELETE:
      summary: Untagresource
      description: Removes one or more tags from the specified resource.
      operationId: amazonWebServicesUntagResource
  /trustStores/{trustStoreArn+}/certificates:
    GET:
      summary: Listtruststorecertificates
      description: Retrieves a list of trust store certificates.
      operationId: amazonWebServicesListTrustStoreCertificates
tags: []
