openapi: 3.1.0
info:
  title: workdocs
  description: >-
    <p>The Amazon WorkDocs API is designed for the following use cases:</p> <ul>
    <li> <p>File Migration: File migration applications are supported for users
    who want to migrate their files from an on-premises or off-premises file
    system or service. Users can insert files into a user directory structure,
    as well as allow for basic metadata changes, such as modifications to the
    permissions of files.</p> </li> <li> <p>Security: Support security
    applications are supported for users who have additional security needs,
    such as antivirus or data loss prevention. The API actions, along with
    CloudTrail, allow these applications to detect when changes occur in Amazon
    WorkDocs. Then, the application can take the necessary actions and replace
    the target file. If the target file violates the policy, the application can
    also choose to email the user.</p> </li> <li> <p>eDiscovery/Analytics:
    General administrative applications are supported, such as eDiscovery and
    analytics. These applications can choose to mimic or record the actions in
    an Amazon WorkDocs site, along with CloudTrail, to replicate data for
    eDiscovery, backup, or analytical applications.</p> </li> </ul> <p>All
    Amazon WorkDocs API actions are Amazon authenticated and certificate-signed.
    They not only require the use of the Amazon Web Services SDK, but also allow
    for the exclusive use of IAM users and roles to help facilitate access,
    trust, and permission policies. By creating a role and allowing an IAM user
    to access the Amazon WorkDocs site, the IAM user gains full administrative
    visibility into the entire Amazon WorkDocs site (or as set in the IAM
    policy). This includes, but is not limited to, the ability to modify file
    permissions and upload any file to any user. This allows developers to
    perform the three use cases above, as well as give users the ability to
    grant access on a selective basis using the IAM model.</p> <note> <p>The
    pricing for Amazon WorkDocs APIs varies depending on the API call type for
    these actions:</p> <ul> <li> <p> <code>READ (Get*)</code> </p> </li> <li>
    <p> <code>WRITE (Activate*, Add*, Create*, Deactivate*, Initiate*,
    Update*)</code> </p> </li> <li> <p> <code>LIST (Describe*)</code> </p> </li>
    <li> <p> <code>DELETE*, CANCEL</code> </p> </li> </ul> <p>For information
    about Amazon WorkDocs API pricing, see <a
    href="https://aws.amazon.com/workdocs/pricing/">Amazon WorkDocs
    Pricing</a>.</p> </note>
paths:
  /api/v1/documents/{DocumentId}/versions/{VersionId}:
    PATCH:
      summary: Updatedocumentversion
      description: >-
        Changes the status of the document version to ACTIVE.  Amazon WorkDocs
        also sets its document container to ACTIVE. This is the last step in a
        document upload, after the client uploads the document to an
        S3-presigned URL returned by InitiateDocumentVersionUpload. 
      operationId: amazonWebServicesUpdateDocumentVersion
  /api/v1/users/{UserId}/activation:
    DELETE:
      summary: Deactivateuser
      description: >-
        Deactivates the specified user, which revokes the user's access to
        Amazon WorkDocs.
      operationId: amazonWebServicesDeactivateUser
  /api/v1/resources/{ResourceId}/permissions:
    DELETE:
      summary: Removeallresourcepermissions
      description: Removes all the permissions from the specified resource.
      operationId: amazonWebServicesRemoveAllResourcePermissions
  /api/v1/documents/{DocumentId}/versions/{VersionId}/comment:
    POST:
      summary: Createcomment
      description: Adds a new comment to the specified document version.
      operationId: amazonWebServicesCreateComment
  /api/v1/resources/{ResourceId}/customMetadata:
    DELETE:
      summary: Deletecustommetadata
      description: Deletes custom metadata from the specified resource.
      operationId: amazonWebServicesDeleteCustomMetadata
  /api/v1/folders:
    POST:
      summary: Createfolder
      description: Creates a folder with the specified name and parent folder.
      operationId: amazonWebServicesCreateFolder
  /api/v1/resources/{ResourceId}/labels:
    DELETE:
      summary: Deletelabels
      description: Deletes the specified list of labels from a resource.
      operationId: amazonWebServicesDeleteLabels
  /api/v1/organizations/{OrganizationId}/subscriptions:
    GET:
      summary: Describenotificationsubscriptions
      description: Lists the specified notification subscriptions.
      operationId: amazonWebServicesDescribeNotificationSubscriptions
  /api/v1/users:
    GET:
      summary: Describeusers
      description: >-
        Describes the specified users. You can describe all users or filter the
        results (for example, by status or organization). By default, Amazon
        WorkDocs returns the first 24 active or pending users. If there are more
        results, the response includes a marker that you can use to request the
        next set of results.
      operationId: amazonWebServicesDescribeUsers
  /api/v1/documents/{DocumentId}/versions/{VersionId}/comment/{CommentId}:
    DELETE:
      summary: Deletecomment
      description: Deletes the specified comment from the document version.
      operationId: amazonWebServicesDeleteComment
  /api/v1/documents/{DocumentId}:
    PATCH:
      summary: Updatedocument
      description: >-
        Updates the specified attributes of a document. The user must have
        access to both the document and its parent folder, if applicable.
      operationId: amazonWebServicesUpdateDocument
  /api/v1/documentVersions/{DocumentId}/versions/{VersionId}:
    DELETE:
      summary: Deletedocumentversion
      description: Deletes a specific version of a document.
      operationId: amazonWebServicesDeleteDocumentVersion
  /api/v1/folders/{FolderId}:
    PATCH:
      summary: Updatefolder
      description: >-
        Updates the specified attributes of the specified folder. The user must
        have access to both the folder and its parent folder, if applicable.
      operationId: amazonWebServicesUpdateFolder
  /api/v1/folders/{FolderId}/contents:
    GET:
      summary: Describefoldercontents
      description: >-
        Describes the contents of the specified folder, including its documents
        and subfolders. By default, Amazon WorkDocs returns the first 100 active
        document and folder metadata items. If there are more results, the
        response includes a marker that you can use to request the next set of
        results. You can also request initialized documents.
      operationId: amazonWebServicesDescribeFolderContents
  /api/v1/organizations/{OrganizationId}/subscriptions/{SubscriptionId}:
    DELETE:
      summary: Deletenotificationsubscription
      description: Deletes the specified subscription from the specified organization.
      operationId: amazonWebServicesDeleteNotificationSubscription
  /api/v1/users/{UserId}:
    PATCH:
      summary: Updateuser
      description: >-
        Updates the specified attributes of the specified user, and grants or
        revokes administrative privileges to the Amazon WorkDocs site.
      operationId: amazonWebServicesUpdateUser
  /api/v1/activities:
    GET:
      summary: Describeactivities
      description: Describes the user activities in a specified time period.
      operationId: amazonWebServicesDescribeActivities
  /api/v1/documents/{DocumentId}/versions/{VersionId}/comments:
    GET:
      summary: Describecomments
      description: List all the comments for the specified document version.
      operationId: amazonWebServicesDescribeComments
  /api/v1/documents/{DocumentId}/versions:
    GET:
      summary: Describedocumentversions
      description: >-
        Retrieves the document versions for the specified document. By default,
        only active versions are returned.
      operationId: amazonWebServicesDescribeDocumentVersions
  /api/v1/groups:
    GET:
      summary: Describegroups
      description: >-
        Describes the groups specified by the query. Groups are defined by the
        underlying Active Directory.
      operationId: amazonWebServicesDescribeGroups
  /api/v1/me/root:
    GET:
      summary: Describerootfolders
      description: >-
        Describes the current user's special folders; the RootFolder and the
        RecycleBin. RootFolder is the root of user's files and folders and
        RecycleBin is the root of recycled items. This is not a valid action for
        SigV4 (administrative API) clients. This action requires an
        authentication token. To get an authentication token, register an
        application with Amazon WorkDocs. For more information, see
        Authentication and Access Control for User Applications in the Amazon
        WorkDocs Developer Guide.
      operationId: amazonWebServicesDescribeRootFolders
  /api/v1/me:
    GET:
      summary: Getcurrentuser
      description: >-
        Retrieves details of the current user for whom the authentication token
        was generated. This is not a valid action for SigV4 (administrative API)
        clients. This action requires an authentication token. To get an
        authentication token, register an application with Amazon WorkDocs. For
        more information, see Authentication and Access Control for User
        Applications in the Amazon WorkDocs Developer Guide.
      operationId: amazonWebServicesGetCurrentUser
  /api/v1/documents/{DocumentId}/path:
    GET:
      summary: Getdocumentpath
      description: >-
        Retrieves the path information (the hierarchy from the root folder) for
        the requested document. By default, Amazon WorkDocs returns a maximum of
        100 levels upwards from the requested document and only includes the IDs
        of the parent folders in the path. You can limit the maximum number of
        levels. You can also request the names of the parent folders.
      operationId: amazonWebServicesGetDocumentPath
  /api/v1/folders/{FolderId}/path:
    GET:
      summary: Getfolderpath
      description: >-
        Retrieves the path information (the hierarchy from the root folder) for
        the specified folder. By default, Amazon WorkDocs returns a maximum of
        100 levels upwards from the requested folder and only includes the IDs
        of the parent folders in the path. You can limit the maximum number of
        levels. You can also request the parent folder names.
      operationId: amazonWebServicesGetFolderPath
  /api/v1/resources:
    GET:
      summary: Getresources
      description: >-
        Retrieves a collection of resources, including folders and documents.
        The only CollectionType supported is SHARED_WITH_ME.
      operationId: amazonWebServicesGetResources
  /api/v1/documents:
    POST:
      summary: Initiatedocumentversionupload
      description: >-
        Creates a new document object and version object. The client specifies
        the parent folder ID and name of the document to upload. The ID is
        optionally specified when creating a new version of an existing
        document. This is the first step to upload a document. Next, upload the
        document to the URL returned from the call, and then call
        UpdateDocumentVersion. To cancel the document upload, call
        AbortDocumentVersionUpload.
      operationId: amazonWebServicesInitiateDocumentVersionUpload
  /api/v1/resources/{ResourceId}/permissions/{PrincipalId}:
    DELETE:
      summary: Removeresourcepermission
      description: >-
        Removes the permission for the specified principal from the specified
        resource.
      operationId: amazonWebServicesRemoveResourcePermission
  /api/v1/documentVersions/restore/{DocumentId}:
    POST:
      summary: Restoredocumentversions
      description: Recovers a deleted version of an Amazon WorkDocs document.
      operationId: amazonWebServicesRestoreDocumentVersions
  /api/v1/search:
    POST:
      summary: Searchresources
      description: >-
        Searches metadata and the content of folders, documents, document
        versions, and comments.
      operationId: amazonWebServicesSearchResources
tags: []
