openapi: 3.1.0
info:
  title: workspaces-thin-client
  description: >-
    <p>Amazon WorkSpaces Thin Client is a affordable device built to work with
    Amazon Web Services End User Computing (EUC) virtual desktops to provide
    users with a complete cloud desktop solution. WorkSpaces Thin Client is a
    compact device designed to connect up to two monitors and USB devices like a
    keyboard, mouse, headset, and webcam. To maximize endpoint security,
    WorkSpaces Thin Client devices do not allow local data storage or
    installation of unapproved applications. The WorkSpaces Thin Client device
    ships preloaded with device management software.</p> <p>You can use these
    APIs to complete WorkSpaces Thin Client tasks, such as creating environments
    or viewing devices. For more information about WorkSpaces Thin Client,
    including the required permissions to use the service, see the <a
    href="https://docs.aws.amazon.com/workspaces-thin-client/latest/ag/">Amazon
    WorkSpaces Thin Client Administrator Guide</a>. For more information about
    using the Command Line Interface (CLI) to manage your WorkSpaces Thin Client
    resources, see the <a
    href="https://docs.aws.amazon.com/cli/latest/reference/workspaces-thin-client/index.html">WorkSpaces
    Thin Client section of the CLI Reference</a>.</p>
paths:
  /environments:
    GET:
      summary: Listenvironments
      description: Returns a list of environments.
      operationId: amazonWebServicesListEnvironments
  /devices/{id}:
    PATCH:
      summary: Updatedevice
      description: Updates a thin client device.
      operationId: amazonWebServicesUpdateDevice
  /environments/{id}:
    PATCH:
      summary: Updateenvironment
      description: Updates an environment.
      operationId: amazonWebServicesUpdateEnvironment
  /deregister-device/{id}:
    POST:
      summary: Deregisterdevice
      description: Deregisters a thin client device.
      operationId: amazonWebServicesDeregisterDevice
  /softwaresets/{id}:
    PATCH:
      summary: Updatesoftwareset
      description: Updates a software set.
      operationId: amazonWebServicesUpdateSoftwareSet
  /devices:
    GET:
      summary: Listdevices
      description: Returns a list of thin client devices.
      operationId: amazonWebServicesListDevices
  /softwaresets:
    GET:
      summary: Listsoftwaresets
      description: Returns a list of software sets.
      operationId: amazonWebServicesListSoftwareSets
  /tags/{resourceArn}:
    DELETE:
      summary: Untagresource
      description: Removes a tag or tags from a resource.
      operationId: amazonWebServicesUntagResource
tags: []
