openapi: 3.1.0
info:
  title: Amazon Web Services omics
  description: >-
    <p>This is the <i>AWS HealthOmics API Reference</i>. For an introduction to
    the service, see <a
    href="https://docs.aws.amazon.com/omics/latest/dev/">What is AWS
    HealthOmics?</a> in the <i>AWS HealthOmics User Guide</i>.</p>
paths:
  /sequencestore/{sequenceStoreId}/upload/{uploadId}/abort:
    DELETE:
      summary: Amazon Web Services Abortmultipartreadsetupload
      description: ' Stops a multipart upload. '
      operationId: amazonWebServicesAbortMultipartReadSetUpload
      tags:
        - Sequencestore
  /share/{shareId}:
    GET:
      summary: Amazon Web Services Getshare
      description: ' Retrieves the metadata for a share. '
      operationId: amazonWebServicesGetShare
      tags:
        - Share
  /sequencestore/{sequenceStoreId}/readset/batch/delete:
    POST:
      summary: Amazon Web Services Batchdeletereadset
      description: Deletes one or more read sets.
      operationId: amazonWebServicesBatchDeleteReadSet
      tags:
        - Sequencestore
  /import/annotation/{jobId}:
    GET:
      summary: Amazon Web Services Getannotationimportjob
      description: Gets information about an annotation import job.
      operationId: amazonWebServicesGetAnnotationImportJob
      tags:
        - Import
  /run/{id}/cancel:
    POST:
      summary: Amazon Web Services Cancelrun
      description: Cancels a run.
      operationId: amazonWebServicesCancelRun
      tags:
        - Run
  /import/variant/{jobId}:
    GET:
      summary: Amazon Web Services Getvariantimportjob
      description: Gets information about a variant import job.
      operationId: amazonWebServicesGetVariantImportJob
      tags:
        - Import
  /sequencestore/{sequenceStoreId}/upload/{uploadId}/complete:
    POST:
      summary: Amazon Web Services Completemultipartreadsetupload
      description: ' Concludes a multipart upload once you have uploaded all the components. '
      operationId: amazonWebServicesCompleteMultipartReadSetUpload
      tags:
        - Sequencestore
  /annotationStore:
    POST:
      summary: Amazon Web Services Createannotationstore
      description: Creates an annotation store.
      operationId: amazonWebServicesCreateAnnotationStore
      tags:
        - annotationStore
  /annotationStore/{name}/version:
    POST:
      summary: Amazon Web Services Createannotationstoreversion
      description: ' Creates a new version of an annotation store. '
      operationId: amazonWebServicesCreateAnnotationStoreVersion
      tags:
        - annotationStore
  /sequencestore/{sequenceStoreId}/upload:
    POST:
      summary: Amazon Web Services Createmultipartreadsetupload
      description: ' Begins a multipart read set upload. '
      operationId: amazonWebServicesCreateMultipartReadSetUpload
      tags:
        - Sequencestore
  /referencestore:
    POST:
      summary: Amazon Web Services Createreferencestore
      description: Creates a reference store.
      operationId: amazonWebServicesCreateReferenceStore
      tags:
        - Referencestore
  /runGroup:
    GET:
      summary: Amazon Web Services Listrungroups
      description: Retrieves a list of run groups.
      operationId: amazonWebServicesListRunGroups
      tags:
        - runGroup
  /sequencestore:
    POST:
      summary: Amazon Web Services Createsequencestore
      description: Creates a sequence store.
      operationId: amazonWebServicesCreateSequenceStore
      tags:
        - Sequencestore
  /share:
    POST:
      summary: Amazon Web Services Createshare
      description: ' Creates a share offer that can be accepted outside the account by a subscriber. The share is created by the owner and accepted by the principal subscriber. '
      operationId: amazonWebServicesCreateShare
      tags:
        - Share
  /variantStore:
    POST:
      summary: Amazon Web Services Createvariantstore
      description: Creates a variant store.
      operationId: amazonWebServicesCreateVariantStore
      tags:
        - variantStore
  /workflow:
    GET:
      summary: Amazon Web Services Listworkflows
      description: Retrieves a list of workflows.
      operationId: amazonWebServicesListWorkflows
      tags:
        - Workflow
  /annotationStore/{name}:
    POST:
      summary: Amazon Web Services Updateannotationstore
      description: Updates an annotation store.
      operationId: amazonWebServicesUpdateAnnotationStore
      tags:
        - annotationStore
  /annotationStore/{name}/versions/delete:
    POST:
      summary: Amazon Web Services Deleteannotationstoreversions
      description: ' Deletes one or multiple versions of an annotation store. '
      operationId: amazonWebServicesDeleteAnnotationStoreVersions
      tags:
        - annotationStore
  /referencestore/{referenceStoreId}/reference/{id}:
    GET:
      summary: Amazon Web Services Getreference
      description: Gets a reference file.
      operationId: amazonWebServicesGetReference
      tags:
        - Referencestore
  /referencestore/{id}:
    GET:
      summary: Amazon Web Services Getreferencestore
      description: Gets information about a reference store.
      operationId: amazonWebServicesGetReferenceStore
      tags:
        - Referencestore
  /run/{id}:
    GET:
      summary: Amazon Web Services Getrun
      description: Gets information about a workflow run.
      operationId: amazonWebServicesGetRun
      tags:
        - Run
  /runGroup/{id}:
    POST:
      summary: Amazon Web Services Updaterungroup
      description: Updates a run group.
      operationId: amazonWebServicesUpdateRunGroup
      tags:
        - runGroup
  /sequencestore/{id}:
    GET:
      summary: Amazon Web Services Getsequencestore
      description: Gets information about a sequence store.
      operationId: amazonWebServicesGetSequenceStore
      tags:
        - Sequencestore
  /variantStore/{name}:
    POST:
      summary: Amazon Web Services Updatevariantstore
      description: Updates a variant store.
      operationId: amazonWebServicesUpdateVariantStore
      tags:
        - variantStore
  /workflow/{id}:
    POST:
      summary: Amazon Web Services Updateworkflow
      description: Updates a workflow.
      operationId: amazonWebServicesUpdateWorkflow
      tags:
        - Workflow
  /annotationStore/{name}/version/{versionName}:
    POST:
      summary: Amazon Web Services Updateannotationstoreversion
      description: ' Updates the description of an annotation store version. '
      operationId: amazonWebServicesUpdateAnnotationStoreVersion
      tags:
        - annotationStore
  /sequencestore/{sequenceStoreId}/readset/{id}:
    GET:
      summary: Amazon Web Services Getreadset
      description: Gets a file from a read set.
      operationId: amazonWebServicesGetReadSet
      tags:
        - Sequencestore
  /sequencestore/{sequenceStoreId}/activationjob/{id}:
    GET:
      summary: Amazon Web Services Getreadsetactivationjob
      description: Gets information about a read set activation job.
      operationId: amazonWebServicesGetReadSetActivationJob
      tags:
        - Sequencestore
  /sequencestore/{sequenceStoreId}/exportjob/{id}:
    GET:
      summary: Amazon Web Services Getreadsetexportjob
      description: Gets information about a read set export job.
      operationId: amazonWebServicesGetReadSetExportJob
      tags:
        - Sequencestore
  /sequencestore/{sequenceStoreId}/importjob/{id}:
    GET:
      summary: Amazon Web Services Getreadsetimportjob
      description: Gets information about a read set import job.
      operationId: amazonWebServicesGetReadSetImportJob
      tags:
        - Sequencestore
  /sequencestore/{sequenceStoreId}/readset/{id}/metadata:
    GET:
      summary: Amazon Web Services Getreadsetmetadata
      description: Gets details about a read set.
      operationId: amazonWebServicesGetReadSetMetadata
      tags:
        - Sequencestore
  /referencestore/{referenceStoreId}/importjob/{id}:
    GET:
      summary: Amazon Web Services Getreferenceimportjob
      description: Gets information about a reference import job.
      operationId: amazonWebServicesGetReferenceImportJob
      tags:
        - Referencestore
  /referencestore/{referenceStoreId}/reference/{id}/metadata:
    GET:
      summary: Amazon Web Services Getreferencemetadata
      description: Gets information about a genome reference's metadata.
      operationId: amazonWebServicesGetReferenceMetadata
      tags:
        - Referencestore
  /run/{id}/task/{taskId}:
    GET:
      summary: Amazon Web Services Getruntask
      description: Gets information about a workflow run task.
      operationId: amazonWebServicesGetRunTask
      tags:
        - Run
  /import/annotations:
    POST:
      summary: Amazon Web Services Listannotationimportjobs
      description: Retrieves a list of annotation import jobs.
      operationId: amazonWebServicesListAnnotationImportJobs
      tags:
        - Import
  /annotationStore/{name}/versions:
    POST:
      summary: Amazon Web Services Listannotationstoreversions
      description: ' Lists the versions of an annotation store. '
      operationId: amazonWebServicesListAnnotationStoreVersions
      tags:
        - annotationStore
  /annotationStores:
    POST:
      summary: Amazon Web Services Listannotationstores
      description: Retrieves a list of annotation stores.
      operationId: amazonWebServicesListAnnotationStores
      tags:
        - annotationStores
  /sequencestore/{sequenceStoreId}/uploads:
    POST:
      summary: Amazon Web Services Listmultipartreadsetuploads
      description: ' Lists multipart read set uploads and for in progress uploads. Once the upload is completed, a read set is created and the upload will no longer be returned in the respone. '
      operationId: amazonWebServicesListMultipartReadSetUploads
      tags:
        - Sequencestore
  /sequencestore/{sequenceStoreId}/activationjobs:
    POST:
      summary: Amazon Web Services Listreadsetactivationjobs
      description: Retrieves a list of read set activation jobs.
      operationId: amazonWebServicesListReadSetActivationJobs
      tags:
        - Sequencestore
  /sequencestore/{sequenceStoreId}/exportjobs:
    POST:
      summary: Amazon Web Services Listreadsetexportjobs
      description: Retrieves a list of read set export jobs.
      operationId: amazonWebServicesListReadSetExportJobs
      tags:
        - Sequencestore
  /sequencestore/{sequenceStoreId}/importjobs:
    POST:
      summary: Amazon Web Services Listreadsetimportjobs
      description: Retrieves a list of read set import jobs.
      operationId: amazonWebServicesListReadSetImportJobs
      tags:
        - Sequencestore
  /sequencestore/{sequenceStoreId}/upload/{uploadId}/parts:
    POST:
      summary: Amazon Web Services Listreadsetuploadparts
      description: ' This operation will list all parts in a requested multipart upload for a sequence store. '
      operationId: amazonWebServicesListReadSetUploadParts
      tags:
        - Sequencestore
  /sequencestore/{sequenceStoreId}/readsets:
    POST:
      summary: Amazon Web Services Listreadsets
      description: Retrieves a list of read sets.
      operationId: amazonWebServicesListReadSets
      tags:
        - Sequencestore
  /referencestore/{referenceStoreId}/importjobs:
    POST:
      summary: Amazon Web Services Listreferenceimportjobs
      description: Retrieves a list of reference import jobs.
      operationId: amazonWebServicesListReferenceImportJobs
      tags:
        - Referencestore
  /referencestores:
    POST:
      summary: Amazon Web Services Listreferencestores
      description: Retrieves a list of reference stores.
      operationId: amazonWebServicesListReferenceStores
      tags:
        - Referencestores
  /referencestore/{referenceStoreId}/references:
    POST:
      summary: Amazon Web Services Listreferences
      description: Retrieves a list of references.
      operationId: amazonWebServicesListReferences
      tags:
        - Referencestore
  /run/{id}/task:
    GET:
      summary: Amazon Web Services Listruntasks
      description: Retrieves a list of tasks for a run.
      operationId: amazonWebServicesListRunTasks
      tags:
        - Run
  /run:
    POST:
      summary: Amazon Web Services Startrun
      description: >-
        Starts a workflow run. To duplicate a run, specify the run's ID and a
        role ARN. The remaining parameters are copied from the previous run. The
        total number of runs in your account is subject to a quota per Region.
        To avoid needing to delete runs manually, you can set the retention mode
        to REMOVE. Runs with this setting are deleted automatically when the run
        quoata is exceeded.
      operationId: amazonWebServicesStartRun
      tags:
        - Run
  /sequencestores:
    POST:
      summary: Amazon Web Services Listsequencestores
      description: Retrieves a list of sequence stores.
      operationId: amazonWebServicesListSequenceStores
      tags:
        - Sequencestores
  /shares:
    POST:
      summary: Amazon Web Services Listshares
      description: ' Lists all shares associated with an account. '
      operationId: amazonWebServicesListShares
      tags:
        - Shares
  /tags/{resourceArn}:
    DELETE:
      summary: Amazon Web Services Untagresource
      description: Removes tags from a resource.
      operationId: amazonWebServicesUntagResource
      tags:
        - Tags
  /import/variants:
    POST:
      summary: Amazon Web Services Listvariantimportjobs
      description: Retrieves a list of variant import jobs.
      operationId: amazonWebServicesListVariantImportJobs
      tags:
        - Import
  /variantStores:
    POST:
      summary: Amazon Web Services Listvariantstores
      description: Retrieves a list of variant stores.
      operationId: amazonWebServicesListVariantStores
      tags:
        - variantStores
  /import/annotation:
    POST:
      summary: Amazon Web Services Startannotationimportjob
      description: Starts an annotation import job.
      operationId: amazonWebServicesStartAnnotationImportJob
      tags:
        - Import
  /sequencestore/{sequenceStoreId}/activationjob:
    POST:
      summary: Amazon Web Services Startreadsetactivationjob
      description: >-
        Activates an archived read set. To reduce storage charges, Amazon Omics
        archives unused read sets after 30 days.
      operationId: amazonWebServicesStartReadSetActivationJob
      tags:
        - Sequencestore
  /sequencestore/{sequenceStoreId}/exportjob:
    POST:
      summary: Amazon Web Services Startreadsetexportjob
      description: Exports a read set to Amazon S3.
      operationId: amazonWebServicesStartReadSetExportJob
      tags:
        - Sequencestore
  /sequencestore/{sequenceStoreId}/importjob:
    POST:
      summary: Amazon Web Services Startreadsetimportjob
      description: Starts a read set import job.
      operationId: amazonWebServicesStartReadSetImportJob
      tags:
        - Sequencestore
  /referencestore/{referenceStoreId}/importjob:
    POST:
      summary: Amazon Web Services Startreferenceimportjob
      description: Starts a reference import job.
      operationId: amazonWebServicesStartReferenceImportJob
      tags:
        - Referencestore
  /import/variant:
    POST:
      summary: Amazon Web Services Startvariantimportjob
      description: Starts a variant import job.
      operationId: amazonWebServicesStartVariantImportJob
      tags:
        - Import
  /sequencestore/{sequenceStoreId}/upload/{uploadId}/part:
    PUT:
      summary: Amazon Web Services Uploadreadsetpart
      description: ' This operation uploads a specific part of a read set. If you upload a new part using a previously used part number, the previously uploaded part will be overwritten. '
      operationId: amazonWebServicesUploadReadSetPart
      tags:
        - Sequencestore
tags:
  - name: annotationStore
  - name: annotationStores
  - name: Import
  - name: Referencestore
  - name: Referencestores
  - name: Run
  - name: runGroup
  - name: Sequencestore
  - name: Sequencestores
  - name: Share
  - name: Shares
  - name: Tags
  - name: variantStore
  - name: variantStores
  - name: Workflow
